### ISSUE TITLE
Question: Configuring types of metadata from mp3 id3 tag

### ISSUE THREAD

**Issue by njmiano** [AzuraCast/AzuraCast#1021]
Hello,
First thank you to all of the contributors of this project. I am working on a small streaming solution and azuracast has pretty much met my needs out of the box.

I have a question that I have tried finding in answer in google and icecast docs and not finding much helpful info, so hoping this is the right place to ask. I would like to use the azuracast web player as is, but am using opensource mp3s which have a comment field in the id3 with a URL to the original source. I would love if this could be displayed in the web player. If that is not possible, I could design my own, but when I view the metadata in the stream with VLC, I do not see the "comment" field being included in the stream. Is there any way to configure this in azuracast? 

Thanks in advance for any help and if this is not the correct way to ask for assistance, please let me know and I will move on.

**Comment by Vaalyn** [comment]
AzuraCast's public player is meant to be an example of a lightweight player that you can build your own on top of. If you need a more complex one I'd recommend you to build one that is more tailored to your needs. You can use the AzuraCast player as a starting point for that. However I don't think that the comment field is currently being processed AzuraCast at all so that will not be available in the API. You could add a `custom_field` in your AzuraCast that you can then fill via the web interface that will be exposed through the API.

The metadata that liquidsoap inserts into the stream is currently limited to `artist`, `title`, `album` and `song`. That's why VLC and other players won't show the comment field. I think it's currently not possible to extend this list via the web interface.

**Comment by njmiano** [comment]
"You could add a custom_field in your AzuraCast that you can then fill via the web interface that will be exposed through the API."

That is probably exactly the info I needed to get me on the right track. Thanks.
