### ISSUE TITLE
Live listeners filter report is not working anymore

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#1056]
**Installation method**
Docker 

**Host OS (for Docker installations)**
Ubuntu 18

**Describe the bug**
Live reporting filter is not working and shows a weird layout 

**To Reproduce**
1. Go to 'Reports > Listeners'
2. Click on '..Live listeners dropdown menu.'
3. Shows a weird layout (see screenshot)
**Screenshots**
https://prnt.sc/ly5v9y
**Device(s):**
 - Device: MacBook Pro 
 - OS: MacOS
 - Browser: All browsers affected
 - Version: Sierra

**Comment by SlvrEagle23** [comment]
@ErnestPH Our upstream provider for numerous Node assets (CDNJS, a CloudFlare service) is intermittently experiencing outages across a number of their servers, specifically including errors that cause pages to fail to render like this.

I'm seeing the same problem on my local instance.

At the moment, there's nothing we can do but wait for the issue to be fixed. I've pinged the Cloudflare team, but I'm sure this is something they're already well aware of.

**Comment by CodeSteele** [comment]
@SlvrEagle23 I know this is a controversial thing but -- stuff like this is why I generally don't rely on 3rd parties for assets and just ship them with the app. It just means that the app is _more_ likely to break because I'm relying on multiple parties to all be online at the same time (and if my app isn't serving assets at all it doesn't work, period).


Just a thought.

**Comment by ErnestPH** [comment]
ok understood. thanks guys. will close this one as we can only wait for them...
