### ISSUE TITLE
Redirect public homepage 

### ISSUE THREAD

**Issue by djcyry** [AzuraCast/AzuraCast#1063]
Hi ,

How can i redirect www.myradio.com/public/myradio to myradio.com ? 
I mean , the azura index ( www.myradio.com/public/myradio ) convert / show them to the index page of 
my radio station . Using the www.myradio.com/public/myradio for my index/root page of my website. 
Is there any way to use that "template" as index of your web radio station ? 
eg : https://i.imgur.com/8763VPf.png

**Comment by CodeSteele** [comment]
First you'll have to move Azuracast off of your root domain, because AzuraCast's login is always going to take the root. So if you moved your AzuraCast install to say `azuracast.myradio.com` you could do some things below:

- Put an iframe on your myraido.com site and link to the public page in the iframe, usability isn't the best but this is super easy.
- Drop in a custom player (we see a lot of people doing this) on your page, looks the best, but takes a bit more technical work.
- Use the embedded player code found on the station admin page, it's an _okay_ player, a little simplified but works easily.

All of these solutions require you to host your own site at myradio.com and use one of the many options to plug your site into AzuraCast.

As far as I know there is nothing on the radar to really make AzuraCast both a radio host and a _borderline_ CMS that can "become" your site. I'd even argue if we were to do that that should still be a separate project. Therefore I'm going to close this as out-of-scope.

**Comment by SlvrEagle23** [comment]
@djcyry The closest AzuraCast can come to this is to set up your station's public page as the "Homepage Redirect URL" under the Custom Branding section. Non-logged-in users will be bounced to the public page, and then to access AzuraCast you will need to directly access `https://your-site.example.com/login`. This won't actually update the path of the public-facing site, but the experience will be the same for users.
