### ISSUE TITLE
sync/nowplaying error 500

### ISSUE THREAD

**Issue by inetactief** [AzuraCast/AzuraCast#1067]
Very nice new item in this control panel Webdj! Great! 
We update Azuracast and the SHOUTcast v2 is gone for a user? We replace it for Icecast but
SHOUTcast v2.5 work fine. very stable. But the new version 2.6 i understand that you not want to use it.

I update Azuracast to the last version  v0.9.1, #23e6fbb (2018-12-22 20:29) • Docker • PHP 7.2

I see nowplaying is not working and when we click on admin/sync/nowplaying (other sync working fine)
We see 500 
a cURL error 6: Could not resolve host: www.basilachill.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
CurlFactory.php : 185

**Comment by SlvrEagle23** [comment]
@inetactief This seems like an issue with your DNS resolution on your machine. If you run `nslookup basilachill.com` (or `dig www.basilachill.com`) on the same server running AzuraCast, do you get a response?

**Comment by inetactief** [comment]
Yes i fix the dns problem..on CentOS 7 but the sync stil not work. Must i restart some services in Azuracast?

**Comment by inetactief** [comment]
i reboot the server, But same problem.. 
If fix the /etc/resolv.conf problem when i reboot the old setting are back?? 

Selinux is off:
I check: sestatus
SELinux status:                 disabled

**Comment by SlvrEagle23** [comment]
@inetactief It's fairly common that some program manages `resolv.conf` and overwrites it. [Here are some instructions for how to handle this with Ubuntu](https://askubuntu.com/questions/157154/how-do-i-include-lines-in-resolv-conf-that-wont-get-lost-on-reboot).

This seems likely to be an issue with your host server rather than AzuraCast itself, so I would recommend you look into how to fix this for your specific setup.
