### ISSUE TITLE
Media with UTF-8 filenames are not processed

### ISSUE THREAD

**Issue by VTCAKAVSMoACE** [AzuraCast/AzuraCast#1075]
**Installation method**
Docker

**Host OS (for Docker installations)**
```
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={76E245CF-C0D0-444D-BA50-36739C18EB00}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={76E245CF-C0D0-444D-BA50-36739C18EB00}
CHROMEOS_RELEASE_BOARD=lakitu-signed-mp-v2keys
CHROMEOS_RELEASE_BRANCH_NUMBER=60
CHROMEOS_RELEASE_BUILDER_PATH=lakitu-release/R71-11151.60.0
CHROMEOS_RELEASE_BUILD_NUMBER=11151
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=71
CHROMEOS_RELEASE_DESCRIPTION=11151.60.0 (Official Build) stable-channel lakitu 
CHROMEOS_RELEASE_KEYSET=mp-v2
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=11151.60.0
DEVICETYPE=OTHER
GOOGLE_RELEASE=11151.60.0
HWID_OVERRIDE=LAKITU DEFAULT
```
OS with SELinux, optimized for running containers.

**Describe the bug**
Media reprocess errors while processing files with UTF-8 characters.

**To Reproduce**
1. Upload files over SFTP containing UTF-8 characters in the name.
2. `docker-compose run --rm cli azuracast_cli azuracast:media:reprocess`

**Expected behavior**
All files are reprocessed.

**Relevant Logs**
```
head: cannot open '/var/azuracast/stations/cm_live/temp/451fc_NTR.MND() - 100 Minutes In The Sky.mp3' for reading: No such file or directory
Processed: NTR.MND(네이쳐마인드) - 100 Minutes In The Sky.mp3
head: cannot open '/var/azuracast/stations/cm_live/temp/d1875_NTR.MND() - chinese morning.mp3' for reading: No such file or directory
Processed: NTR.MND(네이쳐마인드) - chinese morning.mp3
head: cannot open '/var/azuracast/stations/cm_live/temp/cc0f7_NTR.MND() - decisions.mp3' for reading: No such file or directory
Processed: NTR.MND(네이쳐마인드) - decisions.mp3
head: cannot open '/var/azuracast/stations/cm_live/temp/faade_NTR.MND() - is this a dream_.mp3' for reading: No such file or directory
Processed: NTR.MND(네이쳐마인드) - is this a dream_.mp3
head: cannot open '/var/azuracast/stations/cm_live/temp/adf27_NTR.MND() - j.p (soulmate).mp3' for reading: No such file or directory
Processed: NTR.MND(네이쳐마인드) - j.p (soulmate).mp3
head: cannot open '/var/azuracast/stations/cm_live/temp/26c66_NTR.MND() - NTR.MND  a k u m a - growing.mp3' for reading: No such file or directory
Processed: NTR.MND(네이쳐마인드) - NTR.MND ｘ a k u m a - growing.mp3
head: cannot open '/var/azuracast/stations/cm_live/temp/ba9ab_NTR.MND() - space_.mp3' for reading: No such file or directory
Processed: NTR.MND(네이쳐마인드) - space_.mp3
head: cannot open '/var/azuracast/stations/cm_live/temp/a6d2d_NTR.MND() - summer.evening.in.japan.mp3' for reading: No such file or directory
Processed: NTR.MND(네이쳐마인드) - summer.evening.in.japan.mp3
head: cannot open '/var/azuracast/stations/cm_live/temp/1fb59_NTR.MND() - (summer).mp3' for reading: No such file or directory
Processed: NTR.MND(네이쳐마인드) - 여름(summer).mp3
head: cannot open '/var/azuracast/stations/cm_live/temp/f6fd8_NTR.MND() -  (chung ha).mp3' for reading: No such file or directory
Processed: NTR.MND(네이쳐마인드) - 청하 (chung ha).mp3
```

**Device(s):**
N/A

**Additional context**
Appears to be related to the change created for #1052 .

**Comment by VTCAKAVSMoACE** [comment]
This also appears to happen somewhat during `sync:run medium`:

```
vtcakavsmoace@azura-docker-host ~ $ docker-compose run --rm cli azuracast_cli sync:run medium
Starting azuracast_redis_1    ... done
Starting azuracast_influxdb_1 ... done
Starting azuracast_mariadb_1  ... done
Starting azuracast_stations   ... done
Starting azuracast_web_1      ... done
2018/12/27 20:32:15 Waiting for: tcp://mariadb:3306
2018/12/27 20:32:15 Waiting for: tcp://influxdb:8086
2018/12/27 20:32:15 Connected to tcp://mariadb:3306
2018/12/27 20:32:15 Connected to tcp://influxdb:8086
Running Medium (5-minutes) Sync...
[2018-12-27 20:32:16] AzuraCast.ERROR: Error creating media from path 3. Sky.High - Amor.wav: Media path "media://3. Sky.High - Amor.wav" not found. [] []
[2018-12-27 20:32:16] AzuraCast.ERROR: Error creating media from path a l e x - ﻿Ｄ  ｒ  ｏ  ｗ  ｚ  ｙ.mp3: Media path "media://a l e x - ﻿Ｄ  ｒ  ｏ  ｗ  ｚ  ｙ.mp3" not found. [] []
[2018-12-27 20:32:16] AzuraCast.ERROR: Error creating media from path a l e x - ﻿ｉ      ｌ  ｏ  ｖ  ｅ      ｙ  ｏ  ｕ.mp3: Media path "media://a l e x - ﻿ｉ      ｌ  ｏ  ｖ  ｅ      ｙ  ｏ  ｕ.mp3" not found. [] []
[2018-12-27 20:32:16] AzuraCast.ERROR: Error creating media from path ‍‍‍kelpie - calming breeze.mp3: Media path "media://‍‍‍kelpie - calming breeze.mp3" not found. [] []
2018/12/27 20:32:16 Command finished successfully.
```

**Comment by SlvrEagle23** [comment]
@VTCAKAVSMoACE This is actually what was causing your sync process to fail to run before, it just was hard-failing the process previously and now it's logging the error and moving on instead of exiting.

This seems to have something to do with Flysystem handling UTF-8 filenames. When uploading files via the web interface, the filenames are always "sanitized" and UTF-8 characters are transliterated into escaped ASCII sequences specifically to avoid issues of mixed encoding support across products.

I'll take a look and get back to you. Those same files should work just fine if uploaded via the web interface, however.

**Comment by SlvrEagle23** [comment]
@VTCAKAVSMoACE This appears to have something to do with the fact that Flysystem won't properly read or parse UTF-8 files on the filesystem unless the PHP locale is set to something with ".UTF-8" at the end of it. In general web usage, it always is, as all of our locales are set up that way, but on the CLI it isn't, and this would likely have been causing issues.

I've updated the codebase; update your installation and let me know if it helps.

**Comment by VTCAKAVSMoACE** [comment]
I am still seeing the same behaviour as before.

**Comment by VTCAKAVSMoACE** [comment]
As a workaround, I started Firefox with X Forwarding on a virtual machine in the network and uploaded the files over HTTP instead. It's taking some time, but I'll let you know when this finishes whether or not it worked.

**Comment by Vaalyn** [comment]
@SlvrEagle23 @VTCAKAVSMoACE  I've tried to reproduce this bug and I am not able to get the media processing to fail.

This is what I did:

1. Copy a media file with the name `NTR.MND(네이쳐마인드) - 100 Minutes In The Sky.mp3` and the corresponding ID3 tags to the media directory
2. Run the 5-Min Sync Task from the System Administration
3. Look at the `Music Files` list to see if the file was processed
4. Tags and length were showing up correctly
5. Check if the `azuracast_cli azuracast:media:reprocess` shows any errors
6. No errors with the file

@VTCAKAVSMoACE Can you send me a file that is failing to be processed in your installation so that I can test with that?

**Comment by Vaalyn** [comment]
I'll close this issue now as I have not been able to reproduce the issue nor has there been an answer from to my request for a file that fails to be processed. If you still encounter this problem on the newest version of AzuraCast please let us know and include a file that causes this issue so that we can try to reproduce it.
