### ISSUE TITLE
Way to steam from audio server

### ISSUE THREAD

**Issue by ptcfind** [AzuraCast/AzuraCast#1123]
Hi,

I was wondering if exists any way to stream audio from TS/Discord Channel to Azuracast server.
I would like to have a single channel with this "bot" that listen users in the channel and stream their voices/music directly to the stream server.

Do you think that this is possible using some tools?

Thank you in advice.

**Comment by Vaalyn** [comment]
AzuraCast is able to handle audio input from an sources that supply the data in a format that is compatible with IceCast / SHOUTcast / Liquidsoap. So ideally you'd build a bot that joins a Discord or TS channel (Discord will be a lot easier since they are a lot more open to 3rd party tools than TS) capture the audio signal and stream it to AzuraCast. You could also setup a VM that connects to the channels and streams the internal audio directly to AzuraCast via something like [Mixxx](https://www.mixxx.org/) & [Virtual Audio Cable](https://www.vb-audio.com/Cable/)
