### ISSUE TITLE
⭐️ AzuraCast ⭐️ WooCommerce or WHMCS plugin/Integration 💡

### ISSUE THREAD

**Issue by ARIS-GREECE** [AzuraCast/AzuraCast#1132]
### **I've read that**
-  WHMCS Integration #284 

----
### **maybe this could work with woocommerce?**

An **open source** eCommerce plugin for WordPress
https ://github.com/woocommerce/woocommerce

**woocommerce** can also work with **subscriptions**
https ://woocommerce.com/products/woocommerce-subscriptions/
I know who **Commerce subscription** is a **non-free** plugin but there is **nulled**

1. It would be very good if there is automation for creating radio stations and deleting or deactivating it,
2. It would be very good if there is a user management system that works automatically with user permissions,

**Overall, automation is very important of so was AzuraCast for hosting providers .**

----

**Backstory why am I writing this**
**I should offer radio station hosting at very good prices**

My friends did not know that you have to run a server 24/7
I do not think many people can run your PC or a server at home 24/7.

Also, a friend of mine showed this system an Internet radio station that contacted me immediately,
but I declined because I have no company and,
I do not want to commit copyright infringement with my IP address,

If the integration exists for an automatic that I will make such a company,
for radio station hosting🤩,

----
I'm sorry I do not speak English very well and that's why I use the Google translator. 🇩🇪 🇬🇷

----
I hope the developer of azuracast will not be mad at me for writing this,
I hope so.😟

**Comment by CodeSteele** [comment]
Selling stuff via woocommerce is easy (and could be done yourself) the more complicated part is automating the deployment of AzuraCast (which WooCommerce doesn't provide a platform for infrastructure automation), managing their deployments at scale (eg: handling updates) which is more of what WHMCS gives us access to.

These kinds of integrations are pretty intensive for us to do -- and if we're writing the code for these _we'd_ be providing those services ourselves (it would be a good way to fund the project long-term), especially because we can provide a lot of infrastructure orchestration beyond just selling via Woocommerce.


Ultimately it's not something we'd be doing for a 3rd party -- if you want to do it we'll be happy to accept a PR.
