### ISSUE TITLE
WebDj not showing up in the interface; Docker installation; Debian 9

### ISSUE THREAD

**Issue by T3chnoMaciej** [AzuraCast/AzuraCast#1138]
Hi!
I just installed your program, because i was not satisfied with with Libretime. I want to use your Web DJ function, that is awesome. I'd like to stream microphone AND have metadata of my song displayed. After search I found your project, you guys had webdj on the demo nad I thought " Thats exacly what im loioking for! Brilliant!". Installed newset version with docker on debian 9. Did update twice and i don;t have web DJ in the menu. The streamer user was set up. Is it about not using SSL? Is it about using Icecast 2.4 instead of Shoutcast? I did a lot of goolging, but didnt find the answer. Please help me.

Thank you in advance and cheers from Poland,
Maciej
![2scr](https://user-images.githubusercontent.com/20857124/52165796-8c14bd80-2705-11e9-939c-1bea408b62c2.png)
![1scr](https://user-images.githubusercontent.com/20857124/52165797-8c14bd80-2705-11e9-9068-667a2350d032.png)

**Comment by Vaalyn** [comment]
The WebDJ page will be hidden from the menu if you have `Public Pages` or `Streamer Accounts` disabled. Can you check these 2 settings in your station profile?

Apart from that the WebDJ will only work correctly and reliably if your installation is using SSL since the access to the media devices will be blocked by most browsers on insecure sites. Setting up SSL with AzuraCast with docker is quite easy you just need to execute the command found [here](https://www.azuracast.com/docker_sh.html#set-up-letsencrypt) in the documentation.

**Comment by T3chnoMaciej** [comment]
Thank you very much! It worked! One more noob question, does the mic has to be connected to the machine hosting Azuracast to be seen in the interface or could it be vonnected to the machine i'm opening website on?

**Comment by Vaalyn** [comment]
The microphone has to be connected to the machine on which you are using the browser to access the WebDJ site. The page is built on Webcast.js and is executed client-side.
