### ISSUE TITLE
Ability to mount several radios on the same icecast port

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#114]
Is it possible to mount several radios on the same icecast instance, hence on the same port ?

PS : you are doing a fantastic job !

**Comment by SlvrEagle23** [comment]
@griffon56 Thank you :D

IceCast does support running any number of radio stations from the same port, but the idea of AzuraCast is to have each station have its own independently-controlled instance of LiquidSoap and IceCast, so that they can be started/stopped/updated without interfering with the other stations on the same server. To accomplish that, they're always on separate ports, in AzuraCast's case separated by 10 ports from one another (to allow for utility ports like DJ broadcasting in the middle).

You can always add new mount points to each individual station, including relay mount points of other streams, which may accomplish a similar purpose to what you're wanting to do. Otherwise, I would say lumping multiple stations into the same IceCast instance would go against the separation-of-duties principle that AzuraCast was originally built on.
