### ISSUE TITLE
Big WAV file failed to upload

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#1141]
Hi, 

I tried to upload a 2.3GB WAV which started all right (see attached snapshot) but at some point (before 100%) the process stopped, the progress bar disappeared, no error message was shown but the file didn't appear in the files list. It doesn't seem to be a simply cancel because the used storage grew by 2GB (compared to the picture's 10GB I use 12GB now). 

Where did the file go? 

Thanks, 

Peter

![image](https://user-images.githubusercontent.com/28865986/52175761-fc284f80-27a8-11e9-808a-ee8f69f3a38c.png)

**Comment by SlvrEagle23** [comment]
@gammaw The AzuraCast system is not particularly built to handle individual music files that are 2GB in size. At best, most of the files being uploaded are 5-10MB MP3 files, and at worst they're somewhat larger FLAC files.

When you upload a file via the web manager, it's split into smaller chunks that are individually streamed up to the server. This helps avoid problems caused by having to manage a large transfer. If any of those transfers encounters an error, the upload will stop processing.

You can check for errors by opening the web inspector (right click a blank area on the media page and click "Inspect" on Chrome), then clicking the "Console" tab in the web inspector. Any errors encountered should be logged here, where you can copy and paste the message here for further diagnosis.

Also, the upload system *should* support auto-resuming failed downloads, so if your download fails for any reason, you can just reupload that same file and the first already-uploaded chunk will be processed immediately.

**Comment by gammaw** [comment]
@SlvrEagle23 thanks, it helped! I managed to resume the upload and it succeeded eventually. I also found unfinished uploads in the temp directory inside the docker container which I deleted to free up GBs of space. It worked too. FYI: typically we're working with music files of 100-300MB and it works fine for us.
