### ISSUE TITLE
Sound output double ( live & autodj mode )

### ISSUE THREAD

**Issue by reans** [AzuraCast/AzuraCast#115]
Thank you for your support. I already update my installed azuracast. I saw the ICECAST and Shoutcast Client in DJ/Streamer page using Shoutcast 2 stream server with this port for ICECAST client : 8005 and the for Shoutcast v1 : 8006. I pretty sure the same procedure using the Centova Cast the shoutcast v1 djuser:djpassword format. But one problem ive try now in azuracast is this, i try to use the port given for shoutcast v1 which is 8006 with password format as mention djuser:password it wasnt connected but I try the port of icecast 8005 using the shoutcast server type option instead of icecast it was connect and the sound is double. the sound of live stream and the sound of autodj. The autodj must be stop if the live stream got IN but it wasnt stop. I try using the icecast type with the icecast port provide yes im still IN but same problem the sound is double from live source and the autodj source. thats what i notice. any idea where is the problem?

**Comment by SlvrEagle23** [comment]
@reans This shouldn't normally ever happen, and as far as I've seen there's nothing in the LiquidSoap configuration that would cause it to happen, but I can think of at least one reason why it might be happening: if you have your broadcasting tool set to broadcast the "Stereo Mix" output from your soundcard, and you're listening to the station directly, it'll include that in the stereo mix and rebroadcast itself on top of itself.

Otherwise, I would make sure you have the latest version of AzuraCast, then go to your station's profile page, then "Utilities", then "Restart Broadcasting". This will force a rewrite of any configuration and should resolve any such issues.

**Comment by rolradio** [comment]
Hello. I'm using azuracast now for a month. Running on a vps.  It Works great. Only i have the same problem for  live Dj. When i the use live Dj, its conect for 2sec.  Then the autodj   commes back in. Afther 2 sec. So its goose on and of. On another pc i heare the sound switching. I try icecast and shoutcast for stream to liquidsoap. I used butt, mixx, sambroadcaster.... always the same problem. What can be the problem here?
Ps. My upload is not the problem, i try my centovacast there its running normal.

**Comment by reans** [comment]
i also update my azuracast installation but same issues. while you are in live stream the autodj stream suddenly appeared.

**Comment by SlvrEagle23** [comment]
@rolradio @reans My apologies...I have been playing with this on my local AzuraCast installations more, and I can completely verify that this is an issue. LiquidSoap was constantly overrunning its internal buffer of live music, triggering a transition over to the AutoDJ, but this was happening every 2 seconds or so, causing the music to constantly switch between AutoDJ and live DJ.

I have made several changes to how LiquidSoap handles live DJs, including increasing the buffer, allocating them a dedicated stream so if a buffer underrun does occur, it'll just play silence for a moment rather than completely swapping back and forth constantly.

Sorry for initially missing the severity of this issue...after testing long enough, it turns out the problem appeared on _every_ instance of AzuraCast that I had access to.

Please try out the fixed version and let me know if it helps things.

**Comment by rolradio** [comment]
After the update, the live broadcast works perfectly now!
Thank you
