### ISSUE TITLE
Songs repeating

### ISSUE THREAD

**Issue by georgethedev98** [AzuraCast/AzuraCast#1150]
**Is your feature request related to a problem? Please describe.**
Songs keep repeating in the same hour. This messes up our licensing. Is there a fix?
**Describe the solution you'd like**
A option to stop this happening
**Describe alternatives you've considered**
Weight changes and priority changes. Doesn't work
**Additional context**
we have over 2000 songs in there

**Comment by CodeSteele** [comment]
We'd have to know how the radio station is set up, you mentioned you're messing with weights and priorities so you have multiple playlists? what do those look like? Keep in mind multiple playlists do not auto-weight, eg: a playlist with 100 songs at weight 1 and a playlist with 1 song at weight one will play the same song every other song.

Generally: a single playlist with 2000 songs will build a properly queue fine, any problems with song repeating have been due to improper weights.

**Comment by JDBlackman** [comment]
I have experienced the same issue recently. 

I'm have songs repeating just a few songs after being played. Currently I have 6 playlists.

Playlist 1: Weight 5 (38.5%) -  550 Songs
Playlist 2: Weight 3 (23.1%) - 20 Songs
Playlist 3: Weight 3 (23.1%) - 32 Songs
Playlist 4: Weight 2 (15.4%) - 147 Songs
Playlist 5: Once per 29 minutes 
Playlist 6: Once per 3 songs

I have read some issues with the "once per x" playlist, however not sure if same issue as its not that playlist that is repeating.

I am on the latest Azura update (0.9.3) with the fix for 

"The AutoDJ's weighting tool will factor in the total size of each playlist. If you have one playlist with 5 songs and another with 500, this should greatly prevent the tendency to hear the 5-song playlist far more often than you would otherwise want.".

I have automated assignment disabled.

**Comment by SlvrEagle23** [comment]
@JDBlackman I have reverted the changes to playlist weighting that were applied in that commit, so it should be performing as normal.

We've done a great deal of research on the "repeating songs" issue, because it comes up quite a lot, and our reports have shown that this is frequently caused by:
- A song being uploaded twice via different albums or in different folders, but both in the same playlist;
- A song being placed in two playlists that are both in general rotation (thus doubling its chance of playing);
- Playlists being specified as "random" instead of "shuffled", which is truly random and can definitely result in duplicate songs; or
- Frequent modifications to the playlist contents causing the entire playlist to be "reshuffled" after the changes, which briefly creates the possibility of the song playing again too closely after the reshuffling takes place.

Unless we get a song playback timeline showing that the same song is indeed playing too closely without any of these things happening, there's not much we can do to further resolve these reports.
