### ISSUE TITLE
Does not play

### ISSUE THREAD

**Issue by ZapicoGT** [AzuraCast/AzuraCast#1156]
Does not play

https://gyazo.com/563812b1fb587b5f4b33a7fff2f1dedd

**Comment by ZapicoGT** [comment]
With SSL it does not let me play

**Comment by SlvrEagle23** [comment]
@ZapicoGT These issues you are opening are of very low quality. They do not provide us with any details that we would need to diagnose or fix the issue, and it seems as though you've chosen to completely disregard the template that's provided to you when creating a new issue, despite it having information that we absolutely need in order to test and resolve issues.
