### ISSUE TITLE
Allow DJs to have fixed metadata that is set while they're live

### ISSUE THREAD

**Issue by stemvantwente** [AzuraCast/AzuraCast#1159]
Hello

When a Dj is going live the stream title stays at last played song what the autodj played, no the metadata isnt updating to the dj name :(
at profile I see the Dj name who is live, Now did I find https://github.com/AzuraCast/AzuraCast/issues/180 but I cannot find the files I need to edit when I login with ftp to the server, cannot find the maps, who can help me out?

Sorry for my english hope you guys can understand me :)

Greets
Roy

**Comment by Vaalyn** [comment]
To make sure that I understand the issue and setup correctly let me ask some clarification questions.

- Is this a Docker or Traditional installation?
- Are using the newest version?
- What OS is AzuraCast installed on?
- When your live DJ is connected to stream does the Station Profile page look like [this](http://prntscr.com/mih9io) and if not can you clarify, maybe with a screenshot, what is shown?
- What software are your DJs using to stream to AzuraCast?

When a DJ is connected the `On the Air` panel on the Station Profile page should show you the `Now Playing:` with the song the DJ is streaming and the `Now Streaming:` should show the name of the Stream User that is currently connected.

You should not have to edit anything in an AzuraCast installation manually and we advise against doing that since every update would overwrite any changes you did to the core files of AzuraCast.

**Comment by stemvantwente** [comment]
@Vaalyn 
* Traditional installation
* * Are you using the newest version? | Yes
* linux 16.04 ubuntu
* * When your live DJ is connected to stream does the Station Profile page look like [this](http://prntscr.com/mih9io) and if not can you clarify, maybe with a screenshot, what is shown? | Yes
* * What software are your DJs using to stream to AzuraCast? | Simplecast

**Comment by SlvrEagle23** [comment]
@stemvantwente This may be related to the pinned issue #867 where DJs don't properly send over the first metadata header when they first connect, but it sounds like you're saying that they simply don't send metadata fields over at all, and you want the software to manually set the metadata for them. That would be a new feature that we'd class as an enhancement.

**Comment by stemvantwente** [comment]
> @stemvantwente This may be related to the pinned issue #867 where DJs don't properly send over the first metadata header when they first connect, but it sounds like you're saying that they simply don't send metadata fields over at all, and you want the software to manually set the metadata for them. That would be a new feature that we'd class as an enhancement.

Yeah thats what I mean @SlvrEagle23

**Comment by rubensben** [comment]
same pb here. I believe the problem come from the way Icecast and Mixxx interact with each other. Mixxx only send any id info when a song is played in the application. Before that nothing. This is why I believe an option for default Artist/Track should be set on Azuracast when it detect a live connection instead of waiting a signal from mixxx.
