### ISSUE TITLE
Playlist - do not repeat

### ISSUE THREAD

**Issue by andrewyv** [AzuraCast/AzuraCast#1162]
Hello
Now that i figured how to install and how to run the program, i have the following suggestion which is very useful!

Add to every playlist an option, if it's possible to:
-> do not repeat an artist every X minutes
-> do not repeat an track every X minutes
-> do not repeat an album every X minutes

It would be nice to have this feature.

**Comment by BjarnBronsveld** [comment]
I've seen this in EverestCast and works amazingly well. Definitely a good feature to be added.

Vouched :)

**Comment by CodeSteele** [comment]
How does Everest handle this in the case of the requested conditions not being able to be met?

Eg: I have a playlist, it's weighted 50%, it's all from a single artist. Do we start ignoring weights? What if I only have a single playlist? Do we analyze the playlist and provide errors? Do we also re-analyze on playlist updates so you cannot violate the constraints?

**Comment by BjarnBronsveld** [comment]
@CodeSteele Not really sure about that, it's closed source and haven't been able to find out how it works.

When setting up the feature, I was able to set the limit to a maximum of 30 songs to be played until the same artist was played again. It worked pretty good and since that was enabled, there weren't any artists being repeated within xx minutes.
They did not have weights included yet.

**Comment by SlvrEagle23** [comment]
While this would be a nice feature that would be handy to see in AzuraCast, there are two major barriers to its implementation:

- There appears to be no open-source example of how this is accomplished in other systems, and what scarce information is available about the closed-source implementations doesn't give us enough to build a solution around; and

- Since our AutoDJ relies heavily on Liquidsoap's internal shuffler to handle rotation of playlists, and we can't control how Liquidsoap internally shuffles songs, any changes we made to shuffling on our end would be of little benefit to the station in the end, and this issue may be better resolved upstream with Liquidsoap themselves.
