### ISSUE TITLE
Plugin section

### ISSUE THREAD

**Issue by muppathimoonu** [AzuraCast/AzuraCast#1167]
A plugin section would be fine,

**Comment by SlvrEagle23** [comment]
@muppathimoonu Can you elaborate on this request?

**Comment by muppathimoonu** [comment]
I am using azuracast. Writing a module to auto tweet songs, and to response tweets inside webDJ page. 
An other module to download songs from youtube/other online sources to help RJ's. 
instead of adding it to core azuracast, A plugin section can be helpful manage addons.

**Comment by Vaalyn** [comment]
@muppathimoonu AzuraCast already includes a plugin system. [Here](https://github.com/AzuraCast/example-plugin) is an example plugin and documentation about that feature. I'm currently not aware of any real plugins existing yet so if you encounter any problems feel free to report them to us in a separate issue.

In the plugin documentation you will find the part where it says to update your `docker-compose.yml` but I'd recommend creating a `docker-compose.override.yml` beside you normal `docker-compose.yml` so that updates won't delete any additions.

**Comment by SlvrEagle23** [comment]
@muppathimoonu I'm assuming you're looking for a page that lists all the plugins you're using and their version, etc.?

**Comment by muppathimoonu** [comment]
Yes

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39038/plugin-overview-page
