### ISSUE TITLE
Custom URL Streaming

### ISSUE THREAD

**Issue by ptsleon** [AzuraCast/AzuraCast#1181]
I want to be able to listen to the station on https://stream01.energyfm.de/radio.mp3 but don't know how to do that.

**Comment by SlvrEagle23** [comment]
@ptsleon This is not currently possible to do via the web interface given our current infrastructure. Because rules for the nginx server have to be established at the time the server starts, we can't dynamically add in new rules from within the web app without causing problems. With that said, however, all stations can always be accessed both via `your-stream-url:8000/stream.mp3`, for example, and `your-stream-url/radio/8000/stream.mp3`, via the port 80/443 proxy that is already built into our configuration.

If you wanted, you could manually override your nginx configuration to add those same proxying rules for other URLs, but this is a rather technically advanced task that I wouldn't recommend for most users.
