### ISSUE TITLE
In return for this wonderful software AZURACAST

### ISSUE THREAD

**Issue by damidani** [AzuraCast/AzuraCast#1195]
Hello, 

 Introduction
I am a volunteer in the hosting company but I am also talking about what I think of azuracast.

I have known azuracast for a long time and I have been using it since then except that now I am modifying the code to send it to you later because it is a project with a future. I come from a hosting company and I proposed your solutions so do we have to provide you with anything?
an ad?
financing?
I propose rather that we help you develop levels because it intersects me more money I would be revisited if you accept because azuracast and the best 
But I ask if you need anything or not in return for marketing stations with your code.
I'm currently changing the theme, and seeing for the plugins (Which doesn't work for me:'()
I'll make a separate ticket for it.
On this Good Day / Evening

**Comment by Vaalyn** [comment]
Hey, thank you for introducing AzuraCast to a broader audience.

We'd really appreciate donations via our [Patreon](https://www.patreon.com/bePatron?u=232463) or [Kofi](https://ko-fi.com/A736ATQ) page to help support our main developer in making AzuraCast even better.

If you can help by providing new features, fixing bugs or supporting other users that would also be awesome. We have a [guide](https://www.azuracast.com/developing.html#best-practices) on how to setup a local development environment for AzuraCast on our website.

If you want you can also mention that your radio is powered by AzuraCast on your website.

I'll close this issue for now since there is nothing that we can actively help you with but you can still comment on here if you have further questions in about how you can support us.
