### ISSUE TITLE
Do not update metadata for a specific audio

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#1219]
Hi, I've already done a similar post a long time ago, where I was asking to implement something that would block jingles' metadata. Now I have seen that it will be implemented in the future by you. The problem is that my mutli-channel radio has been inserted into sites, bots, etc. .. and every time the title of the jingle appears, which is very annoying. I therefore ask you if I can intervene in any way with some icecast or other files. If you could describe me briefly without disturbing, how I should do it.

#1086 

I'm waiting for your answer.
Kind regards!

**Comment by SlvrEagle23** [comment]
@Ilario42 Please do not create a new issue to ask about the status of a previous issue.

This is still a pending enhancement that we have not been able to get to. We will happily accept pull requests from any developers wishing to implement the feature ahead of us; otherwise, your patience is appreciated.

**Comment by Ilario42** [comment]
Solved!
