### ISSUE TITLE
Playlist rotation is acting differently since 0.9.3

### ISSUE THREAD

**Issue by BjarnBronsveld** [AzuraCast/AzuraCast#1230]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 18.04

**Describe the bug**
In the latest update, 0.9.3, a change was made to the auto dj playlist weighting system. As noted in the changelog, it now also uses the playlist size for weighting the playlist. Playlists with a lower weight but more songs, are now played too often.

**To Reproduce**

I have got several playlists at the moment. Let's make the example easy; there's 3 playlists:
Heavy rotation - weight 20 - ~100 songs
Medium rotation - weight 15 - ~300 songs
Rare rotation - weight 5 - ~600 songs

What happened before, was that the heavy rotation was played more often than the others. So the more popular songs were played multiple times per day.
Since the change, the rare rotation playlist is played even more than the heavy rotation because of the playlist size.
Previously, it worked as intended to me. Rare rotation contains older songs that you only hear every xx days or something. This isn't the case anymore. Changing the weights doesn't seem to work.

**Expected behavior**
The rare rotation playlist should be played far less than the heavy rotation playlist. Even though the sizes are different.

**Comment by SlvrEagle23** [comment]
@BjarnBronsveld This is definitely a valid point. I will look into the weighting and see if I can reach a happy middle ground.

Basically, the complaints we've been getting are almost always something like:

```
Playlist 1 - Weight 5 - 3 songs
Playlist 2 - Weight 2 - 400 songs
```

People are (understandably) irritated that seemingly every second or third song is one of the Playlist 1 songs. Including the song count basically results in a distributed weight of 15 vs 800, meaning the larger playlist will proportionally play far more often.

In your case, the original weighting method was working fine and this new method isn't.

I'm not sure there is a perfect solution, and it may wind up being something we make configurable on a per-station level.

**Comment by Vaalyn** [comment]
@SlvrEagle23 Maybe the confusion can also be resolved by adding a display value besides that weight field to indicate the percentage chance of playing a song from that playlist in relation to all active playlists. This seems more like a UI/UX issue as opposed to a technical one.

**Comment by SlvrEagle23** [comment]
@BjarnBronsveld @Vaalyn I'm inclined to agree that the previous weighting is not only desirable in a number of cases but is also how Liquidsoap itself, if given the responsibility of managing playlist shuffling (as it is in "Manual AutoDJ" mode), would do it.

I also remembered after the fact that we have a visible percentage shown on the main Playlists page, which indicates the likelihood of any given general rotation playlist being played, and that percentage is calculated using the old weighting method, so it has been inaccurate since it switched over.

For now I'm reverting back to the original weighting method. I'll work on polishing up the UI/UX of that feature to help explain it better, and possibly expanding the allowed weights even further via a number field as opposed to a limited selection.

**Comment by BjarnBronsveld** [comment]
Awesome, thanks a lot for the quick response @SlvrEagle23 💯
