### ISSUE TITLE
shoutcast tutorial ?

### ISSUE THREAD

**Issue by rubensben** [AzuraCast/AzuraCast#1232]
Hi all, I realized I was doing a mess trying to configure shoutcast, could we have a tutorial about how to use it ? From my part I just want to mirror what's playing LiquideSoap to it. 

I tried many things (entering in the docker image, modyfing the sc_serv.conf etc..., adding a shoutcast configuation as a remote relay etc.... but I only got more confused

**Comment by Vaalyn** [comment]
> From my part I just want to mirror what's playing LiquideSoap to it.

Do you want to relay an audio stream from one station to another?
What exactly are you having problems with and what do you want to achieve?

There is an abundance of generic tutorials for ShoutCast available on the internet. Without knowing what you are looking for exactly we will not be able to help you.

**Comment by rubensben** [comment]
I would simply to have the station also running on shoutcast. Ive managed to make it work before updating to 0.9.3 but then my playlists got crazy + when trying to run the "Now Playing Data" task, I had errors trying to login to the shoutcast server

**Comment by Vaalyn** [comment]
The issue with the "play each x" is already under investigation and a known issue. You can follow the progress in issue #1198 and has no relation to ShoutCast itself.

Is there anything apart from the "play each x" issue and the #1233 that is related to ShoutCast where you need help with? Otherwise I'll close this issue as it seems like the errors you are experiencing are already taken care of in other issues.

**Comment by rubensben** [comment]
thx i guess that's it, I will try again tmrow
