### ISSUE TITLE
Add a DJ streaming calendar with API

### ISSUE THREAD

**Issue by Manuel19861** [AzuraCast/AzuraCast#1241]
It would be nice if there is a calendar where the DJs can enroll their submissions. You could put API into the homepage Sorry my english is not that good

**Comment by Vaalyn** [comment]
I'm not sure if I understand your feature request correctly. From the issue title I assume that you speak german? If so then write it in german and I'll translate it for you.

**Comment by Manuel19861** [comment]
Es wäre schön, wenn es einen Sendeplan gibt, in dem die DJs oder Moderatoren ihre Sendungen eintragen können. und man es  API in die eigene Homepage einbauen könnte

**Comment by Vaalyn** [comment]
This is a feature request for adding a calendar where DJs or administrators can enter when a DJ will be streaming and making the calendar data available via the API.

**Comment by Manuel19861** [comment]
Ja das wäre sehr schön wenn so was gibt gerade in webradio bereich braucht man so was

**Comment by MrSteelMiner** [comment]
Ja das stimmt. Das wäre echt ein nützliches Feature!
--
Indeed, this would be a nice and useful feature!

**Comment by SlvrEagle23** [comment]
Merging this with an existing feature request. Vote on it here: https://azuracast.featureupvote.com/suggestions/38913/schedule-when-djs-can-connect

**Comment by Moonbase59** [comment]
@Radio-Quergedacht You can use the API (plus a little programming) for that. Check out https://your.station.com/static/api/index.html#/Stations%3A%20Schedules/getSchedule for documentation, then try something like (the `1` is your station_id):

```
https://your.station.com/api/station/1/schedule
```
or even use a start time (2023-04-23T00:00:00) and # rows (10) to return:
```
https://your.station.com/api/station/1/schedule?now=2023-04-23T00%3A00%3A00&rows=10
```

You’ll get a nice clean JSON response that you can work on:

![Auswahl_205](https://user-images.githubusercontent.com/3706922/233834065-5408f6a5-c5c1-4c5a-bcd0-584d026baf76.png)

You don’t even need to authorize with the API since the schedule is usually public.

HTH. Good luck.
