### ISSUE TITLE
massive load since update

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#1291]
- Traditional Install

since last update my server (ubuntu 18.04) has a cpu-usage of 98-100% all the time. Load average is normally between 0.1-0.5, now ~5.0
Reboot doesn't help. Logs don't help either.

![grafik](https://user-images.githubusercontent.com/47743654/54103488-ecfe7800-43cc-11e9-98d8-852e825e7bfa.png)

**Comment by SlvrEagle23** [comment]
@MrSteelMiner It looks like Liquidsoap is running multiple times per station. You said a restart didn't fix the issue...do all of those instances come back after a restart? That definitely shouldn't be happening.

I'd be interested in seeing the contents of `/var/azuracast/stations/main/config/supervisord.conf`.

**Comment by MrSteelMiner** [comment]
[group:station_1]
programs=station_1_backend,station_1_frontend

[program:station_1_frontend]
user=azuracast
priority=90
command=/usr/local/bin/icecast -c /var/azuracast/stations/main/config/icecast.xml
directory=/var/azuracast/stations/main/config
stdout_logfile=/var/azuracast/stations/main/config/icecast.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=10
redirect_stderr=true

[program:station_1_backend]
user=azuracast
priority=100
command=/var/azuracast/.opam/system/bin/liquidsoap /var/azuracast/stations/main/config/liquidsoap.liq
directory=/var/azuracast/stations/main/config
stdout_logfile=/var/azuracast/stations/main/config/liquidsoap.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=10
redirect_stderr=true

**Comment by MrSteelMiner** [comment]
I took the screenshot after rebooting the vserver. So, yes. Came back after restart.

**Comment by MrSteelMiner** [comment]
I have 2 mountpoints with active AutoDJ (320kbit/s and 128kbits) per station. Maybe this is the problem?

**Comment by SlvrEagle23** [comment]
@MrSteelMiner No, that's fine and normal. What I'm wondering is why a recent update changed the total CPU load so significantly. Did you also change the number of mount points or stations around the same time, or did they just suddenly start taking up far more resources?

**Comment by MrSteelMiner** [comment]
I just ran the update-script like everytime and then this happened.

**Comment by Rafaelrds2017** [comment]
It happened to me too. I had to add more cpu, doubling the value of my plan :(

**Comment by SlvrEagle23** [comment]
@MrSteelMiner @Rafaelrds2017 I can sympathize and I want to fix this for you all, but "my CPU is running high" isn't really enough information for me to diagnose the cause of the problem. There haven't been any significant changes of any sort to the stations container, and I really doubt that disabling the log output alone would be causing that. I'll get to testing with a traditional installation and see if I can reproduce the issue.

**Comment by MrSteelMiner** [comment]
Can I help somehow?

**Comment by SlvrEagle23** [comment]
@MrSteelMiner @inetactief @Rafaelrds2017 I've spun up a traditional installation and I can't reproduce any errors that are leading to unusually high load. The load on my instance is about 10-13% of a single CPU core per mount point, which is quite normal.

The only way I'm likely going to be able to resolve this issue is to look at one of your installations directly. If one of you is willing to share your server details with me, you can e-mail me at the address associated with my GitHub account.

Otherwise, I will continue to investigate as best as I can, but the response will be limited.

**Comment by MrSteelMiner** [comment]
Check your mail. Do you need more than AzuraCast-login?

**Comment by Rafaelrds2017** [comment]
Data sent to your email ..

**Comment by SlvrEagle23** [comment]
@Rafaelrds2017 @MrSteelMiner For traditional installs, we have had to lag behind on Liquidsoap versions because we were using OPAM 1, which Liquidsoap no longer distributes updates through.

In order to help resolve this issue (among others), I've updated traditional installs to use OPAM 2. The update is a fairly intensive one, because it's building and compiling both Liquidsoap and several other components from source. It can take anywhere from 15 to 20 minutes.

Once it's complete, though, you should notice an improvement in performance. I've immediately been able to see a drop of CPU load of roughly 40-50% for a single station.

**Comment by MrSteelMiner** [comment]
I will try it... Thanks for all your efforts!

Greetings from Germany!
I want to help you, so I'm working on the German translation :)

**Comment by MrSteelMiner** [comment]
Worked! Many thanks!
