### ISSUE TITLE
11 Zombie processes after update

### ISSUE THREAD

**Issue by Zellouser** [AzuraCast/AzuraCast#1294]
![Zombie](https://user-images.githubusercontent.com/48444758/54131811-6456fa80-4413-11e9-8c3f-fd661b0ff5b7.PNG)

**Comment by Zellouser** [comment]
Docker - Installation
Host OS Ubuntu 18.04

testing with 2 servers

**Comment by Vaalyn** [comment]
This seems to be a problem that is most likely caused by an issue that the s6 overlay has with your kernel versions behaviour with AUFS. At least that is what I suspect after reading about a [`s6 zombie process`](https://github.com/just-containers/s6-overlay/issues/135) in s6 overlay. There is a rather old issue linked there from a different project where they posted a [list of workarounds / fixes](https://github.com/moby/moby/issues/18180#issuecomment-193708192) and also an [issue](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1533043) from the Ubuntu bug tracker about this issue where the recommendation is to update AUFS to `v20160111`. The easiest way to solve this problem should be to just upgrade the kernel of your Ubuntu installation.

**Comment by SlvrEagle23** [comment]
@Zellouser I've reverted the latest commits to the `web_v2` container; update and you should be back to normal.

**Comment by Zellouser** [comment]
After renewed update no more zombie processes.
My kernel version is 4.15.0-46
Thank you for quick support.

**Comment by SlvrEagle23** [comment]
@Zellouser You reopened this issue; is it still happening? It should be fixed because the entire container image that would've used s6 was reverted.

**Comment by Zellouser** [comment]
Sorry, a user error.

**Comment by SlvrEagle23** [comment]
@Zellouser No worries, glad it's fixed. :)
