### ISSUE TITLE
Cant use ubuntu 16.04

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#1309]
Hello,
this is only for information, because i think many will have the Problem.
opam2 don't work on ubuntu 16.04 without this workaround: https://github.com/ocaml/opam/issues/3424

**Comment by SlvrEagle23** [comment]
Reopening this as this is something we can (and should) be including in our Ansible setup for 16.04.

**Comment by preterive** [comment]
:)
But it was difficult (for me) because i can't install the actually ocaml and opam normaly on openvz. I had to use the system ocaml and init the new opam with --disable-sandboxing
Sorry but i don't know what i'm exactly done anymore, i searched a lot on serverfault and many Github issues.

**Comment by SlvrEagle23** [comment]
@preterive The fact that we use OPAM2 is a new addition so that we can use the latest version of Liquidsoap. We've had a fair amount of frustration with the process of moving to OPAM2, which actually has _increased_ the complexity and build times for our process rather than making anything faster or easier.

On our Docker builds, we already added the `--disable-sandboxing` flag as it was simply impossible to build anything there otherwise.

In the interest of avoiding trouble on traditional installs, I've added the same flag there. That should resolve things, as well as making updates work for 16.04.

**Comment by JDBlackman** [comment]
I'm having an issue with after latest update on traditional install 16.04 (using the --disable-sandboxing flag) - I am unable to start liquidsoap it says check log for errors however nothing in liquidsoap.log or icecast.log. Icecast is running fine.  There isn't any conflict of ports that I can find.  Really scratching my head on this one.

**Comment by SlvrEagle23** [comment]
@JDBlackman that might not be related to this issue. You should probably make a new issue for that.

**Comment by preterive** [comment]
Yes, but i Had the Same Problem too. Today i would Upgrade another Server, i would make an Video and Post it Her

**Comment by preterive** [comment]
But it could be fixed with this: https://github.com/AzuraCast/AzuraCast/commit/33d9c7d84ae6f162087a7805601dfb8aadfb866c

**Comment by preterive** [comment]
bwrap is still missing.
I made a video

**Comment by preterive** [comment]
https://www.youtube.com/watch?v=gtl3HHOrSaM&feature=youtu.be
Warning: it is loud at some times and i done something other at the same time.

**Comment by SlvrEagle23** [comment]
@preterive This is the same issue as #1316 and should be fixed as of the latest update. Follow that issue for updates.
