### ISSUE TITLE
Error after sending META with "ö"

### ISSUE THREAD

**Issue by MrSteelMiner** [AzuraCast/AzuraCast#1313]
Traditional Installation

In a livestream one of my DJs is playing the song "Wölfe", so the META-data contains a "ö". After that, I cannot open the LiquidSoap-Log via log-viewer
![image](https://user-images.githubusercontent.com/47743654/54462732-0eff4e00-4771-11e9-9554-0b00b7ea98ac.png)

The original log contains the following:
`2019/03/15 21:16:03 [camomile:3] Failed to convert "Kontra K. - W\246lfe" from UTF-8 to UTF-8 (CamomileLibrary__CharEncoding.Configure(Config).Malformed_code)!
2019/03/15 21:16:03 [main_input_streamer:3] New metadata chunk ? -- Kontra K. - W�lfe.`

![image](https://user-images.githubusercontent.com/47743654/54462795-3ce49280-4771-11e9-88ea-9228acb1157a.png)

Hope you can solve the problem.
Thanks in advance!

**Comment by Vaalyn** [comment]
The `ö` in your metadata seems like it's not a normal ö character or somehow malformed / wrongly encoded. The error is thrown inside of liquidsoap so that seems like the data is alread "corrupted" when it's send to the autodj by your DJs client. I'd advise you to edit the metadata of the file that was used here to fix the metadata corruption.

For the log viewer problem I think the easiest solution would be to manually edit the log file with a plaintext editor and remove the entry from that file.

**Comment by MrSteelMiner** [comment]
The 'ö' seems to be encoded in ANSI, not in UTF8 ...

**Comment by MrSteelMiner** [comment]
Any idea, how to change it?

**Comment by Vaalyn** [comment]
You could edit the ID3 tags of the song file with an ID3 tag editor and save it with UTF-8. You could use [MP3Tag](https://www.mp3tag.de/en/) for this as is supports more than just mp3 files.
