### ISSUE TITLE
Liquidsoap not building on Ubuntu 16.04

### ISSUE THREAD

**Issue by JDBlackman** [AzuraCast/AzuraCast#1316]
**Installation method**
Traditional

**Host OS (for Docker installations)**
Ubuntu 16.04

**Describe the bug**
After updating to latest update, Liquidsoap will not run and no logs are being produced. I have tried reverting to an older commit but it doesn't seem to recompile the older version of the liquidsoap, so the bug is still persisting. 

Icecast is running but with no mounts being streamed too.

**Comment by JDBlackman** [comment]
I figured out how to manually recompiled liquidsoap by playing with ansible and setting the revision back one. When compiling liquidsoap I get this error

`TASK [azuracast-radio : Build and Install Liquidsoap (This process takes some time)] ************                                                      *************************************************************************************************                                                      ****************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "opam init --disable-sandboxing -a && opa                                                      m install -y taglib.0.3.3 mad.0.4.5 faad.0.4.0 fdkaac.0.2.1 lame.0.3.3 vorbis.0.7.1 cry.0.6.0 fla                                                      c.0.1.4 opus.0.1.2 duppy.0.8.0 ssl liquidsoap.1.3.6", "delta": "0:00:36.941807", "end": "2019-03-                                                      16 03:30:54.137455", "msg": "non-zero return code", "rc": 20, "start": "2019-03-16 03:30:17.19564                                                      8", "stderr": "[NOTE] Will configure from built-in defaults.\n[NOTE] Make sure that ~/.bash_profi                                                      le is well sourced in your ~/.bashrc.", "stderr_lines": ["[NOTE] Will configure from built-in def                                                      aults.", "[NOTE] Make sure that ~/.bash_profile is well sourced in your ~/.bashrc."], "stdout": "                                                      Checking for available remotes: rsync and local, git, mercurial, darcs. Perfect!\n\n<><> Fetching                                                       repository information ><><><><><><><><><><><><><><><><><><><><><>\n[default] Initialised\n\nUse                                                      r configuration:\n  ~/.bash_profile is already up-to-date.\n\n<><> Creating initial switch (ocaml                                                      -system>=4.02.3) <><><><><><><><><><><><><><>\n\n<><> Gathering sources ><><><><><><><><><><><><>                                                      <><><><><><><><><><><><><><><><>\n\n<><> Processing actions <><><><><><><><><><><><><><><><><><><                                                      ><><><><><><><><><>\n∗ installed base-bigarray.base\n∗ installed base-threads.base\n∗ installed b                                                      ase-unix.base\n∗ installed ocaml-system.4.02.3\n∗ installed ocaml-config.1\n∗ installed ocaml.4.0                                                      2.3\nDone.\n# Run eval $(opam env) to update the current shell environment\nThe following depende                                                      ncies couldn't be met:\n  - vorbis → ocaml >= 4.03\n      base of this switch (use `--unlock-base                                                      ' to force)\n\nNo solution found, exiting", "stdout_lines": ["Checking for available remotes: rsy                                                      nc and local, git, mercurial, darcs. Perfect!", "", "<><> Fetching repository information ><><><>                                                      <><><><><><><><><><><><><><><><><><>", "[default] Initialised", "", "User configuration:", "  ~/.                                                      bash_profile is already up-to-date.", "", "<><> Creating initial switch (ocaml-system>=4.02.3) <>                                                      <><><><><><><><><><><><><>", "", "<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><                                                      ><><><><><><><><>", "", "<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><>                                                      <><><><>", "∗ installed base-bigarray.base", "∗ installed base-threads.base", "∗ installed base-u                                                      nix.base", "∗ installed ocaml-system.4.02.3", "∗ installed ocaml-config.1", "∗ installed ocaml.4.                                                      02.3", "Done.", "# Run eval $(opam env) to update the current shell environment", "The following                                                       dependencies couldn't be met:", "  - vorbis → ocaml >= 4.03", "      base of this switch (use `--                                                      unlock-base' to force)", "", "No solution found, `exiting"]}`

**Comment by SlvrEagle23** [comment]
@JDBlackman I just changed how Liquidsoap is built to take advantage of PPAs that speed up the process, so if you could try the update again, it should help with this issue.

**Comment by reans** [comment]
i have the same issue in my traditional installation. here is the error output..

TASK [azuracast-radio : Build and Install Liquidsoap (This process takes some time)] ***********************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "opam init -a && opam install -y taglib.0.3.3 mad.0.4.5 faad.0.4.0 fdkaac.0.2.1 lame.0.3.3 vorbis.0.7.1 cry.0.6.0 flac.0.1.4 opus.0.1.2 duppy.0.8.0 ssl liquidsoap.1.3.6", "delta": "0:00:34.536869", "end": "2019-03-18 10:03:24.399417", "msg": "non-zero return code", "rc": 31, "start": "2019-03-18 10:02:49.862548", "stderr": "[NOTE] Will configure from built-in defaults.\n[NOTE] Make sure that ~/.bash_profile is well sourced in your ~/.bashrc.\n\n[ERROR] The compilation of ocaml-system failed at \"/var/azuracast/.opam/opam-init/hooks/sandbox.sh build ocaml gen_ocaml_config.ml\".\n\n#=== ERROR while compiling ocaml-system.4.02.3 ================================#\n# context              2.0.2 | linux/x86_64 |  | https://opam.ocaml.org#ec9aff98\n# path                 ~/.opam/default/.opam-switch/build/ocaml-system.4.02.3\n# command              ~/.opam/opam-init/hooks/sandbox.sh build ocaml gen_ocaml_config.ml\n# exit-code            1\n# env-file             /tmp/opam-reans-21789/ocaml-system-21789-b76d46.env\n# output-file          /tmp/opam-reans-21789/ocaml-system-21789-b76d46.out\n### output ###\n# bwrap: No permissions to creating new namespace, likely because the kernel does not allow non-privileged user namespaces. On e.g. debian this can be enabled with 'sysctl kernel.unprivileged_userns_clone=1'.", "stderr_lines": ["[NOTE] Will configure from built-in defaults.", "[NOTE] Make sure that ~/.bash_profile is well sourced in your ~/.bashrc.", "", "[ERROR] The compilation of ocaml-system failed at \"/var/azuracast/.opam/opam-init/hooks/sandbox.sh build ocaml gen_ocaml_config.ml\".", "", "#=== ERROR while compiling ocaml-system.4.02.3 ================================#", "# context              2.0.2 | linux/x86_64 |  | https://opam.ocaml.org#ec9aff98", "# path                 ~/.opam/default/.opam-switch/build/ocaml-system.4.02.3", "# command              ~/.opam/opam-init/hooks/sandbox.sh build ocaml gen_ocaml_config.ml", "# exit-code            1", "# env-file             /tmp/opam-reans-21789/ocaml-system-21789-b76d46.env", "# output-file          /tmp/opam-reans-21789/ocaml-system-21789-b76d46.out", "### output ###", "# bwrap: No permissions to creating new namespace, likely because the kernel does not allow non-privileged user namespaces. On e.g. debian this can be enabled with 'sysctl kernel.unprivileged_userns_clone=1'."], "stdout": "Checking for available remotes: rsync and local, git, mercurial, darcs. Perfect!\n\n<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><><><>\n[default] Initialised\n\nUser configuration:\n  ~/.bash_profile is already up-to-date.\n\n<><> Creating initial switch (ocaml-system>=4.02.3) <><><><><><><><><><><><><><>\n\n<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>\n\n<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>\n-> installed base-bigarray.base\n-> installed base-threads.base\n-> installed base-unix.base\n\n\n<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>\n+- The following actions failed\n| - build ocaml-system 4.02.3\n+- \n+- The following changes have been performed (the rest was aborted)\n| - install base-bigarray base\n| - install base-threads  base\n| - install base-unix     base\n+- \n# Run eval $(opam env) to update the current shell environment\nSwitch initialisation failed: clean up? ('n' will leave the switch partially installed) [Y/n] n", "stdout_lines": ["Checking for available remotes: rsync and local, git, mercurial, darcs. Perfect!", "", "<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><><><>", "[default] Initialised", "", "User configuration:", "  ~/.bash_profile is already up-to-date.", "", "<><> Creating initial switch (ocaml-system>=4.02.3) <><><><><><><><><><><><><><>", "", "<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>", "", "<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>", "-> installed base-bigarray.base", "-> installed base-threads.base", "-> installed base-unix.base", "", "", "<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>", "+- The following actions failed", "| - build ocaml-system 4.02.3", "+- ", "+- The following changes have been performed (the rest was aborted)", "| - install base-bigarray base", "| - install base-threads  base", "| - install base-unix     base", "+- ", "# Run eval $(opam env) to update the current shell environment", "Switch initialisation failed: clean up? ('n' will leave the switch partially installed) [Y/n] n"]}

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=18   changed=4    unreachable=0    failed=1

**Comment by SlvrEagle23** [comment]
@JDBlackman @reans I've fixed the issue with 16.04 not working correctly because of an outdated OCaml system installation. Unfortunately, the newer version of OCaml must be built from source, so the first update is back up to taking something like 15-20 minutes because of that. Once you're on that new version, though, the updates should be faster.
