### ISSUE TITLE
ERROR NEW INSTALLATION

### ISSUE THREAD

**Issue by reans** [AzuraCast/AzuraCast#1321]
Method: Traditional
OS: Ubuntu 16.04

I tried to update my azuracast traditional installation method but i end up and error. fresh install but i still got the error during installation.

Here is the error code..

TASK [azuracast-radio : Configure Sandboxing on Host] ******************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "sysctl kernel.unprivileged_userns_clone=1", "delta": "0:00:00.006838", "end": "2019-03-19 08:43:58.382710", "msg": "non-zero return code", "rc": 255, "start": "2019-03-19 08:43:58.375872", "stderr": "sysctl: cannot stat /proc/sys/kernel/unprivileged_userns_clone: No such file or directory", "stderr_lines": ["sysctl: cannot stat /proc/sys/kernel/unprivileged_userns_clone: No such file or directory"], "stdout": "", "stdout_lines": []}

RUNNING HANDLER [azuracast-user : send user notification] **************************************************************************************************************

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=21   changed=5    unreachable=0    failed=1

**Comment by Vaalyn** [comment]
`unprivileged_userns_clone` is disabled in your kernel. You need to enable this. See this thread on stackexchange for more information about that: https://unix.stackexchange.com/questions/303213/how-to-enable-user-namespaces-in-the-kernel-for-unprivileged-unshare

In general we recommend using the Docker installation method instead of the bare-metal one (previously called traditional). Docker makes it a lot easier for us to support any issues that may arise since every installation will behave pretty much the same way with docker and also easier to maintain for station owners.

Do you mind me asking why you are using the bare-metal installation? I would like to get more insights into how AzuraCast is used and why people chose the more complicated installation method.

**Comment by JDBlackman** [comment]
@Vaalyn thought I would slightly hijack this thread to give my reason to using bare-metal installation. When first starting out I had no idea what Docker was and was slightly confused by the entire thing. After a while I now know all the advantages to using it, however switching over to a Docker container installation would cause downtime to the station, and haven't had a good opportunity to do so.

**Comment by SlvrEagle23** [comment]
@reans I've updated the traditional installer to disable sandboxing on OPAM2, since it seems to be causing a world of problems on certain hosts that I can't account for.
