### ISSUE TITLE
Streamer/DJ Accounts Not Showing Up/Connecting

### ISSUE THREAD

**Issue by oznorts** [AzuraCast/AzuraCast#1332]
When AutoDJ (Liquidsoap) is disabled, the station seems to be always "offline" and I'm unable to connect with my streamer account. In fact, the streamer sidebar link isn't even shown, and when trying to go to the Web DJ page, it says the station doesn't support live streaming. How do we fix this, as we do not want AutoDJ on but need streamer accounts.

**Comment by muppathimoonu** [comment]
Under station settings page under AUTO DJ configuration tab,  Enable / check "Allow streamers/DJ" Option. While disabling Audio DJ you must have accidentally disabled this.

**Comment by SlvrEagle23** [comment]
@oznorts The way AzuraCast is built, your DJ/streamers connect to Liquidsoap directly so that it can smoothly transition between your AutoDJ music and the live stream, and to help abstract out connection problems that are specific to the Icecast and SHOUTcast frontends.

If you have the AutoDJ disabled, you can't manage streamer accounts, as only Liquidsoap authenticates with AzuraCast when new streamer accounts are connecting. You can still provide the source password for your frontend (Icecast/SHOUTcast) stream directly to DJs, but you can't manage separate accounts.

**Comment by dengue8830** [comment]
for the next souls who comes here, i have some notes about autodj and shoutcast

shoutcast is propietary software so azuracast can't include it by default. At the same time, most radio stations uses shoutcast so azuracast figured out some way to provide some way to these clients connects anyways by default, some like an 'shoutcast emulator'. This is cool but confusing and should be more documented because the config (ports, etc) that allows that is bound to an autodj instance, so when you disable autodj this feature stop working, unless you `install shoutcast to azuracast` and `edit the station to just work with shoutcast`.

We discovered that because autodj is too expensive so we disabled it but at the same time the clients uses shoutcast connection data.

I don't know if open a new issue to make this more searcheable

Thanks for this awesome project
