### ISSUE TITLE
Sam CAST Update Metadata

### ISSUE THREAD

**Issue by berkaygndzs** [AzuraCast/AzuraCast#1335]
Hey, 
I'm using Sam CAST application to capture sound from my machine and I want to send it to Shoutcast, It gives you this information for updating metadata on their end: https://support.spacial.com/hc/en-us/articles/229534787-How-to-Send-Artist-Title-and-Song-Metadata-to-the-Player 
How can I make it update in Azura? Thanks.

**Comment by SlvrEagle23** [comment]
@berkaygndzs Unfortunately, I can't afford to buy a license for any of the SAM broadcasting components, and when we contacted them about getting an evaluation copy of the software to ensure its compatibility with AzuraCast, they refused and directed us to their standard licensing instead.

Typically when DJs are connected, we receive metadata updates alongside the audio connection itself. I would be surprised if SAM doesn't support sending this metadata (often referred to as "ICY" metadata after the specification SHOUTcast uses to transmit it) in-stream.

**Comment by Vaalyn** [comment]
I did a quick search in their knowledge database and I think that if you follow [this tutorial](https://support.spacial.com/hc/en-us/articles/229534727-How-To-Set-Up-Your-MP3-Encoder-with-SHOUTCast) from them SAM should send the metadata alongside the stream data. Instead of getting the stream connection details from spacial you'll need to get them from your AzuraCast installation though. Select the streaming protocol `ShoutCAST 1` to stream with DJ accounts and check `Enable title streaming`.
