### ISSUE TITLE
IP address

### ISSUE THREAD

**Issue by justwolfii** [AzuraCast/AzuraCast#1336]
Hello,
I have small question. Can I disable using ip address from azuracast and have it only on domain? Because I need to have MySQL and xenforo on my VPS, but when I will install MySQL, azuracast will crash. 
Thanks for answers.

**Comment by SlvrEagle23** [comment]
@AnUnknowsTygerosy To answer your first question, yes, it's possible to set the "base URL" as a domain name, and then all traffic will be routed through that domain name instead of directly through the IP address.

I'm not sure what this has to do with MySQL, though...

**Comment by AnUnknowsTygerosy** [comment]
So.. where I can set base URL?

**Comment by SlvrEagle23** [comment]
@AnUnknowsTygerosy It's the first item in the system settings (via Administration > System Settings), labeled "Site Base URL".

**Comment by AnUnknowsTygerosy** [comment]
So.. that will be problem. I have it, but it still reacting on ip address (and domain too)

**Comment by SlvrEagle23** [comment]
@AnUnknowsTygerosy When you set the base URL, it sets what URL it refers to inside AzuraCast. It should always be referring to the URL you specified when providing radio links, embedding graphics/CSS, etc. unless you also specified "Prefer Browser URL" on that same settings page.

If you don't have any other virtual hosts on the same server, then AzuraCast will also respond to the IP address. This isn't normally a problem at all, though, and I'm not sure why it is causing a problem in your situation. Your explanation about MySQL doesn't make any sense as MySQL uses completely unrelated ports (3306 by default).

**Comment by Vaalyn** [comment]
Is this installation a recommended docker installation or an advanced Bare-metal installation of AzuraCast?

**Comment by AnUnknowsTygerosy** [comment]
Normal installation (without docker)

**Comment by Vaalyn** [comment]
When using the Bare-metal installation method (which we don't recommend since it can interfere with you host systems software and is harder to debug for us) you should not install an additional MySQL server on the machine. The ansible scripts for the Bare-metal installation already install a MariaDB server which is a fork of MySQL. If you really want to install a MySQL server on the same server that AzuraCast runs on you are better off switching to the recommended Docker installation method. When using Docker the MariaDB server that AzuraCast uses is only available inside of the local Docker network and can't interfere with any MySQL servers on the host machine. Since you also want to have Xenforo running on that machine you'll need a webserver like NGINX or Apache2 which will run on port 80 by default so you will have to change the default port of the AzuraCast web interface from port 80 to something different like 8080. See our [guide](https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#use-non-standard-ports) for this.

**Comment by AnUnknowsTygerosy** [comment]
I have apache2 running on port 8080 and nginx on port 80. My domains going thru apache2 to nginx.
So.. if I will want to install docker version, will I lose my data?

**Comment by Vaalyn** [comment]
I'm guessing you are asking about the data of your existing AzuraCast Bare-metal installation.

If I'm not mistaken we have a migration script for switching from Bare-metal to Docker though I'm not quite sure how exactly it should be used since I can't find that in the documentation. @SlvrEagle23 can you help me out here, is that script save to use and how should it be used?

Regardless, you should not lose any station data when migrating from Bare-metal to Docker.

**Comment by AnUnknowsTygerosy** [comment]
So.. okay.. how I can switch from bare-metal to docker?

**Comment by Vaalyn** [comment]
@AnUnknowsTygerosy Let's wait until we Silver has time to chime in. I'm not that versed in migrations from Bare-metal to Docker yet.

**Comment by SlvrEagle23** [comment]
@AnUnknowsTygerosy @Vaalyn We do have a migrate script (`./docker-migrate.sh`) and it should work without issue, but it isn't very well tested and it may cause problems. You should definitely back up the contents of your station before doing the migration.

**Comment by AnUnknowsTygerosy** [comment]
Okay. So.. now.. how I can install docker version and disable bare-metal?

**Comment by SlvrEagle23** [comment]
@AnUnknowsTygerosy That's what the migrator script does. Your best bet of course is to just start off with a fresh OS and install the Docker version on that, but barring that, the migration script is a good option. Again, be sure to back up your music.

**Comment by AnUnknowsTygerosy** [comment]
Yeah.. I cant start with fresh OS.. If Iam right.. I will only run migration script and it will install docker version and remove bare-metal? And.. what about nginx config? (00-azuracast) will it change?

**Comment by SlvrEagle23** [comment]
@AnUnknowsTygerosy Docker uses a completely different set of configurations so the only thing that will transfer are your AzuraCast settings (stations, database, statistics, etc) and not customizations made to nginx, etc.

**Comment by AnUnknowsTygerosy** [comment]
Okay.. because I have more websites in that config.

**Comment by SlvrEagle23** [comment]
@AnUnknowsTygerosy This is likely beyond the scope of the support we provide for free via our GitHub, as this involves things that aren't AzuraCast running on the same server as ours, which we don't officially support.

**Comment by AnUnknowsTygerosy** [comment]
Okay.. I will try to migrate it. I will write here when it will be done.
Thanks for support.

**Comment by AnUnknowsTygerosy** [comment]
So.. I migrated to docker.. everything worked fine.. After restarting my VPS, ip address is going to apache2 defauld site, my domain set as base URL have Error 525.. As I said.. I have apache2 on port 8080 that is going to nginx to port 80 and 443.

**Comment by Vaalyn** [comment]
Have you set custom ports for AzuraCasts web interface as mention [here](https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#use-non-standard-ports)?

**Comment by AnUnknowsTygerosy** [comment]
No, I dont need custom port on AzuraCast. I want it normally on 80 and 443.

**Comment by Vaalyn** [comment]
Okay, let me explain a little bit on how you can achieve that AzuraCast is accessible through port 80 while also having the nginx running on that port.

You need to set custom ports for AzuraCasts web interface and then add a proxy configuration to your nginx config so that when you access the domain where you want to have AzuraCast available on port 80 the requests will be proxied from nginx to AzuraCast on the custom port.

**Comment by AnUnknowsTygerosy** [comment]
Okay.. I maybe found my problem. I disabled automatic ssl on cloudflare and its working.

**Comment by AnUnknowsTygerosy** [comment]
Okay.. fixed.. but now, where I can find azuracast on my VPS? (folders and files)

**Comment by Vaalyn** [comment]
Docker saves persistent data in the following location `/var/lib/docker/volumes`. There you'll find several directories with hashes as names and a few `azuracast_` directories. The station files, so logs, configs and media are located inside the `azuracast_stations` directory.

**Comment by AnUnknowsTygerosy** [comment]
Okay. Maybe my last question. I have domain and azuracast on port 8099 (https) and 8098 (http). How I can make it listen to 80 and 443 with my domain?

**Comment by Vaalyn** [comment]
@justwolfii Hey, sorry for the late response. Do you still need help with that?
