### ISSUE TITLE
Map of listeners trough Google map api key

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#138]
Hello,

I have setup map of listeners  with Google Maps api key. Its working great but only for 1 radio station.
All the others i see the google map but no live listener and total and their place in the map.

**Comment by SlvrEagle23** [comment]
@surihost Are all of your stations local icecast/shoutcast stations? We can't pull data currently on remote stations or relays, as we can't guarantee that the host software has the proper version/capability to provide the data we need.

**Comment by surihost** [comment]
Yes the stations hosted local in shoutcast.Only 1 station the live listener is working the other stations not.

**Comment by surihost** [comment]
I noticed that the very first station is created the  live listener map is working, all the other that there after are created its not working on them.

**Comment by SlvrEagle23** [comment]
@surihost I actually can't reproduce this issue on any machine I have running. On all machines, the live listener report works just fine for any station, even if multiple are created.

If there's any specific information you can provide me, that would be helpful. It's difficult to diagnose the issue otherwise.

**Comment by surihost** [comment]
How can i sent you a email/ pm with my logins ?

**Comment by SlvrEagle23** [comment]
@surihost Send me an e-mail at loobalightdark@gmail.com

**Comment by surihost** [comment]
Sure thing, i am sending you an email.
