### ISSUE TITLE
Streamer disconnection issue.

### ISSUE THREAD

**Issue by muppathimoonu** [AzuraCast/AzuraCast#1383]
When streamer page hangs or network down, streamer is not auto disconnecting, 
Previously, auto DJ used to start stream and disconnect  streamer from stream.

**Comment by SlvrEagle23** [comment]
@muppathimoonu Unstable connections are always going to be a problem for handling incoming DJ connections, but we can definitely look into slight modifications to help with this.

The reason we have the system set up the way we do now (where, once a DJ has authenticated, until they explicitly disconnect, their signal is being played instead of the radio) is because some DJs with unstable connections were having their signals constantly faded in and out between their audio and the AutoDJ. Having the live mode be more persistent helps resolve that issue in many cases.

**Comment by muppathimoonu** [comment]
The problem is even when the network connection established back, it's not auto connecting to stream.

**Comment by Vaalyn** [comment]
Maybe this can be resolved in a similar way as in #1420 with an error listener that tries to re-establish the connection.
