### ISSUE TITLE
Raspberry Pi support

### ISSUE THREAD

**Issue by z3a** [AzuraCast/AzuraCast#1389]
Hi there!!

I'm interested to install AzuraCast in a Raspberry Pi board, is it possible with the current release? The documentation said that it is possible without using the docker method, but the in the issue #332 is not clear if the problem is already solved.

Any hints?

**Comment by SlvrEagle23** [comment]
@z3a Currently, we haven't been able to devote any development resources toward checking up on the necessary steps to get the Raspberry Pi working again. As long as that issue is open, currently we don't support Raspberry Pi or the ARMHF architecture for installations.

**Comment by z3a** [comment]
I've got my answer:  "AzuraCast cannot currently be installed on non-x86 architectures."

**Comment by maxlinux2000** [comment]
Hi the problem is Ansible.
doing by hand the process when ansible fail, I've installed azudacast stable version in ubuntu 18.04lts on a RaspberryPi4 (4GB ram)
![Captura de pantalla de 2020-09-17 13-03-44](https://user-images.githubusercontent.com/5683921/93462223-46126a80-f8e6-11ea-9ff7-2e3d0d0359e3.png)

```
root@ubuntu:/var/azuracast/www# uname -a
Linux ubuntu 5.4.0-1015-raspi #15~18.04.1-Ubuntu SMP Fri Jul 10 09:20:51 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
root@ubuntu:/var/azuracast/www# 
```
I will try to build it on a docker image on raspbianOS 32bit...I don't know if it works
