### ISSUE TITLE
activate web proxy for radio

### ISSUE THREAD

**Issue by EBII** [AzuraCast/AzuraCast#139]
i hope remove :8000 to the stream path

if not activate the path is https://www.domain.tld:8000/radio.mp3?xxxxx and it is working 

if activate web proxy  the path in station profile is https/radio.mp3?xxxxxx
and it not working with https://www.domain.tld/radio.mp3?xxxx  with 404 
and connection error with https://www.domain.tld:8000/radio.mp3?xxxx

when disable web proxy it is works again as same as start with :8000 in the url and the profil is up to date.

Regards

**Comment by SlvrEagle23** [comment]
@EBII The "enable web proxy" setting just updates the links inside AzuraCast to refer to "azuracast.site/radio/8000/etc" instead of "azuracast.site:8000/etc". It doesn't actually disable direct access to the original port, and in fact, even with the web proxy setting turned off, the "/radio/8000" URLs still continue to work. This is intentional, so regardless of the link you give listeners, it will always work regardless of this setting.

There are a few big reasons you would want to enable the web proxy:
 - You're testing locally (i.e. on Vagrant) and don't want to forward each port individually
 - You're using a service like CloudFlare that doesn't forward non-web ports, or
 - You have listeners accessing your service from an SSL-enabled (HTTPS) homepage and you don't want them to receive the "insecure content" notice, so you want to proxy through a secure web port instead

In your specific case, it sounds like the base URL setting is causing problems. What is your "Site Base URL" setting on the site currently? You may need to update it or remove the leading "https://" prefix.

**Comment by SlvrEagle23** [comment]
@EBII I found a problem in the code that may be causing the issue you're referring to: if you're on an HTTPS connection, AzuraCast was converting all URLs to "httpsurl.com" instead of "https://url.com". This is fixed as of the latest update. Sorry for the inconvenience and thank you for your patience.
