### ISSUE TITLE
AzuraCast als Auto DJ und DJ Verwaltung für laut.fm

### ISSUE THREAD

**Issue by Manuel19861** [AzuraCast/AzuraCast#1392]
Das man AzuraCast als Auto DJ und DJ Verwaltung für laut.fm verwenden kann wehre es Praktich eine laut.fm schnietselle zu haben

**Comment by SlvrEagle23** [comment]
@Manuel19861 We've received many requests to be compatible with Laut.fm's unique API, but we have never received any details of laut.fm's API specifications nor heard any communications from their team.

We would be happy to review a pull request, either to our main library or to the AzuraCast/nowplaying library, that implements this functionality, but as it stands right now we don't have the information necessary to do so.

**Comment by Manuel19861** [comment]
Was für infvermationen Breuchtet ihr denn von Laut fm ?

**Comment by Vaalyn** [comment]
@Manuel19861 Ich denke das Hauptproblem war bisher, dass die Laut.fm API Dokumentation komplett auf Deutsch ist und nicht auf Englisch und aus dem Entwicklerteam von AzuraCast bin ich der einzige deutschsprachige. Da Laut.fm ein komplett deutscher Dienst ist bezweifle ich, dass sie eine Englische API Doku haben, was es schwerer für die anderen macht sich damit zu beschäftigen und mit der Laut.fm Oberfläche zu experimentieren. Ein großer Vorteil wäre bereits eine fertige PHP Bibliothek für den Zugriff auf die API.

Das hier sind alle Informationen die ich über die Laut.fm API gefunden habe:

Allgemeine API Beschreibung:
https://api.laut.fm/

Informationen über die Suche per API:
https://api.laut.fm/documentation/search

JSON Referenz aller API Routen:
https://api.laut.fm/doc

Beispiel PHP Code zum benutzen der API:
https://api.laut.fm/static/example.phps

-----------------------------------------------------

@Manuel19861 I think the main problem until now was that the Laut.fm API documentation is completely in German and I'm the only native German speaker of the AzuraCast team. Since Laut.fm is a German service I doubt that they even have an API documentation in English which makes it quite hard for the others to take a look at and play around with Laut.fm. A big help would be a PHP library for accessing the API.

These are all informations I found about the Laut.fm API:

General API description:
https://api.laut.fm/

Information about the search via API:
https://api.laut.fm/documentation/search

JSON reference of all API routes:
https://api.laut.fm/doc

Example PHP Code:
https://api.laut.fm/static/example.phps

**Comment by Manuel19861** [comment]
Oky ich frage mal bei uns in Laut fm Forum nach mal sehen ob wir da für eine Lösung hin bekommen

**Comment by Manuel19861** [comment]
eine laut fm php gibt es schon hier https://github.com/fkorf/lautfm-php-admin

**Comment by Manuel19861** [comment]
https://github.com/niko/lautfm_js_tools/blob/master/lautfm_js_tools.js

**Comment by Manuel19861** [comment]
https://github.com/niko/lautfm-streamer

**Comment by Manuel19861** [comment]
https://github.com/lautde/radioadmin-client

**Comment by Manuel19861** [comment]
Hoffe das kann fieleicht auch weiter helfen

**Comment by Vaalyn** [comment]
Die von dir verlinkte `fkorf/lautfm-php-admin` ist nicht über [Packagist](https://packagist.org/) / [Composer](https://getcomposer.org/) installierbar (Composer ist die Standard Paketverwaltung für PHP Projekte). Unabhängig davon sieht diese Library recht schlecht programmiert aus. Es werden Funktionen teilweise global anstatt in Klassen festgelegt, mehrere Klassen in einer Datei erstellt, Einstellungen für Error Reporting fest geändert, etc. Ich würde diese Lib sehr ungerne in das Projekt mit reinziehen. Die JS Lib können wir von PHP aus schlecht benutzen und das Go Programm ist seit 2014 nicht mehr aktualisiert worden. Der Radioadmin-client scheint der offizielle Laut.fm Radioadmin zu sein, also eine ganze Webanwendung. Wir bräuchten entweder einen fertigen API Client für Laut.fm der über Packagist installierbar ist (ich habe keinen finden können) oder jemanden der einen solchen für das Projekt erstellt, sollte noch keiner existieren.

-------------------------
The `fkorf/lautfm-php-admin` that you linked is not installable via [Packagist](https://packagist.org/) / [Composer](https://getcomposer.org/) (Composer is the standard package manager for PHP projects). The library also looks badly programmed. Functions are defined in the global scope, multiple classes in the same file, changes error reporting settings, etc. I don't wan't to pull this lib into the project. The JS lib is not something we can use from PHP and the Go application has not been update since 2014. The Radioadmin-client seems to be the official Laut.fm Radio admin web application. We'd need either a ready to use API client for Laut.fm that is installable via Packagist (I couldn't find one) or someone who would create something like that for the project if none exist.

**Comment by Manuel19861** [comment]
so würde es auch fungsonieren wann man da so mit ein bauen könnte
https://pastebin.com/Ey3Uqkz8

**Comment by Vaalyn** [comment]
Um einmal etwas allgemeiner zu fragen, möchtest du den Stream von einem bestehenden Laut.fm Radio auf AzuraCast weiterleiten, so dass AzuraCast das Signal von Laut.fm als Eingabequelle benutzt oder möchtest du das Signal von AzuraCast an ein Laut.fm Radio senden?

**Comment by Manuel19861** [comment]
ich möschte das Signal von AzuraCast an ein Laut.fm Radio senden

**Comment by Vaalyn** [comment]
Ich gehe mal davon aus, dass Laut.fm IceCast oder ShoutCast verwendet. Hast du schon die `Remote-Relay` Funktion von AzuraCast probiert? Diese ist für genau solche Anwendungsfälle gedacht.

**Comment by Manuel19861** [comment]
Laut fm verwenden IceCast

**Comment by Vaalyn** [comment]
Super, dann sollte es eigentlich kein Problem sein deinen Stream über diese Funktion auf Laut.fm zu übertragen.

-------

Fantastic! Then it shouldn't be a problem to relay your stream via that feature to Laut.fm.

**Comment by Manuel19861** [comment]
genau darum sage ich ja fungsoniren tut das schon nur leider ist es bei azuracast noch nicht mit drin

**Comment by Vaalyn** [comment]
Ich bin mir dann ehrlich gesagt nicht sicher was genau das Problem ist. Mit dem Remote-Relay feature von AzuraCast kannst du sowohl einen Stream von AzuraCast an andere IceCast oder ShoutCast Server übertragen als auch andere Streams als Quelle für AzuraCast nutzen.

![image](https://user-images.githubusercontent.com/13745863/55650537-413b2300-57e6-11e9-9706-1de7876056b8.png)

![image](https://user-images.githubusercontent.com/13745863/55650568-5adc6a80-57e6-11e9-9dc7-cc8b2aa6b479.png)


Was genau fehlt dir dort damit das zusammen mit Laut.fm funktioniert?

**Comment by Manuel19861** [comment]
ubs sory das habe ich dann über sehen

**Comment by Vaalyn** [comment]
👍 Wenn du Fragen zu diesem Feature hast oder auf Probleme stößt, gib uns einfach bescheid was genau du probiert hast und was nicht funktioniert und wir schauen es uns an.

--------

👍 If you have any questions about that feature or if you encounter any problems just tell us what you tried and what didn't work and we'll look into it.

**Comment by preterive** [comment]
hey Manuel, lüge uns doch einfach nicht an, dann hätte ich dir gerne im laut.fm Forum geholfen.
Da laut.fm keine xls Dateien anbietet ist es erforderlich lautfm als remote relay einzurichten.

**Comment by MrSteelMiner** [comment]
Ich verwende selbst AzuraCast bei allen meinen Stationen und muss sagen, dass sich das ganze echt super verträgt. Ich musste zwar die IP des Streamservers eintragen, weil es bei Erstellung noch gehakt hat bei der Hostnameauflösung, aber ich glaube, das ist mittlerweile gefixt worden. Hatte noch keine Zeit, das zu testen. Mache ich bei Gelegenheit mal.

**Comment by MrSteelMiner** [comment]
Aber was genau möchtest du denn einbauen? Also wo hakt es aktuell bei dir?

**Comment by Manuel19861** [comment]
Ja es hat fungsoniert auch die tietel über tragung zur Laut.fm fungsoniert auch bei Live senudgen habe es teste @preterive  es geht auch one xls Datei habe es vor ein parminuten getestet es fungsoniert alles wunder bar

**Comment by preterive** [comment]
Dann kann hier ja zu.

**Comment by Vaalyn** [comment]
Da das Problem anscheinend gelöst wurde mache ich jetzt hier erstmal zu.

-------------------

I'll close this issue as it seems to be solved now.
