### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by Donokami** [AzuraCast/AzuraCast#141]
Hello,
I am here simply to suggest to allow the installation of Azuracast using Docker. This would make it possible to have no problem with different environments and facilitate installation.
I read in other issues that @SlvrEagle23 did not have too much time to take care of a Docker configuration, so why not other people?
Personally I really have no knowledge about Docker, so I could unfortunately not take care of it
Thanks !

**Comment by SlvrEagle23** [comment]
@Donokami I've actually been doing a lot of research into the best ways to put together Docker containers, and I've come up with a combination of docker images that should handle AzuraCast quite well:

- nginx
- mariadb
- php7.1
- influxdb
- supervisord (the radio stations would run inside this container)

The only problem, of course, is that reworking this whole system to use Docker would essentially require rebuilding the deployment script from scratch and having the entire web app be compatible with living inside a docker-composed environment.

It's a lot of work and it still wouldn't particularly grant the flexibility that would be expected of the situation, due to the stations all living inside the single supervisord container. It would, however, let AzuraCast run on _any_ host machine regardless of OS, and this would be a huge plus.

**Comment by SlvrEagle23** [comment]
@Donokami It's been a very very busy week but we now not only have a Docker Compose setup for AzuraCast, but each of the individual customized images for AzuraCast are published up to the Docker Hub, making installation very fast and easy on any Docker-supported host.

I'm closing this ticket for now, as any future issues with Docker will be treated as a first-class supported method of use and can be their own individual tickets.

Thank you for your patience, and I hope you have a chance to play with the new Dockerized AzuraCast soon!
