### ISSUE TITLE
Possible to exclude a playlist and its songs when its scheduled ?

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#1412]
I have a lot of playlists that are scheduled on a specific time and i don't want this songs
are being played on general rotation?
Is this possible?

Thanks

**Comment by SlvrEagle23** [comment]
@macbroadcast You're saying that scheduled playlists are playing when "General Rotation" playlists should be playing?

The first thing I would check is to make sure that the server isn't misreading the server time zone when it writes the Liquidsoap configuration file. Sometimes it does this, so you hear your scheduled music at the wrong time. You can tell this by looking at `liquidsoap.liq` using the "Log Viewer" feature; any scheduled items will have the time (in server time) that they should play, (i.e. 22h0m-23h0m for 10pm to 11pm). Often, setting your server time zone to UTC can resolve any issues caused by these time zones going out of sync with the host.
