### ISSUE TITLE
"Skip Song" button re-shuffling the playlist

### ISSUE THREAD

**Issue by afonsosantos** [AzuraCast/AzuraCast#1421]
Hi,

Installation method: **Docker**

When i click in the **Skip Song** button, the **Playing Next** song is not played and the **On the Air** panel gets updated with new songs.

![image](https://user-images.githubusercontent.com/46262740/55842798-efb7ce80-5b2c-11e9-8972-a3322c66cea4.png)

After pressing the **Skip Song** button:

![image](https://user-images.githubusercontent.com/46262740/55842810-02ca9e80-5b2d-11e9-966a-e71d204d80b2.png)

and again:

![image](https://user-images.githubusercontent.com/46262740/55842865-432a1c80-5b2d-11e9-9cae-96c0c6206448.png)

My playlist is set to **Shuffle**

After a while, it plays the song that "disappeared" from the queue: 

![image](https://user-images.githubusercontent.com/46262740/55843083-4bcf2280-5b2e-11e9-8884-24bd0e26f585.png)

![image](https://user-images.githubusercontent.com/46262740/55843222-07905200-5b2f-11e9-9dce-afbdb825fe3a.png)

**Comment by SlvrEagle23** [comment]
@afonsosantos There's a very complicated explanation for why this happens, but to summarize:

In Liquidsoap, each of these sources is the "fallback" for the one above it, so if the one above disconnects for any reason, the "fallback" below will start:

 - Live broadcasting
 - Scheduled/once-per-x/special playlists
 - Requested songs
 - AzuraCast's AutoDJ (which controls "Playing Next")
 - Liquidsoap's general rotation AutoDJ
 - Silence

When you skip a song from AzuraCast's AutoDJ, it goes to the "next available" source, in this case Liquidsoap's general rotation AutoDJ, as the source of the next song. AzuraCast has an idea internally what the next song should be (since it's already sent it over) but Liquidsoap does what it wants for that next song. Once that song is over, it looks back at the queue, sees AzuraCast's AutoDJ is ready with another song, and plays that, which is where you get the "Playing Next" song.

There's likely nothing we can do about this on our end.

**Comment by afonsosantos** [comment]
Now i get it, thanks for the explanation!
