### ISSUE TITLE
CloudFlare breaks script loading in HTTPS

### ISSUE THREAD

**Issue by Metal-Mighty** [AzuraCast/AzuraCast#1439]
**Installation method**

Docker

**Host OS (for Docker installations)**

Debian 8 (Jessie)

**Describe the bug**

Enabling CloudFlare for the domain will result in a script loading failure. The following error message is present in the Chrome console:

> Refused to load the script 'https://ajax.cloudflare.com/cdn-cgi/scripts/a2bd7673/cloudflare-static/rocket-loader.min.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'nonce-oRJ+doQCy3ixkj24VkvoznVv'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

The interface is rendered unusable (no action on button clicks) and some text is replaced by tags (e.g. _{{ row.station.name }}_). See screenshots below.

**To Reproduce**

1. Enable HTTPS for AzuraCast (Force HTTPS set to Yes) 
2. Serve AzuraCast with a reverse-proxy (Apache in my case) pointing to the https port
3. Configure SSL certificates for the domain
4. Enable full CloudFlare support for the domain (not only DNS support)
5. Visit the AzuraCast install

**Expected behavior**

Just work as expected? :)

**Relevant Logs**

**Screenshots**

![image](https://user-images.githubusercontent.com/5247527/56164342-cab1d880-5fd0-11e9-8998-b2587cfd9af3.png)
![image](https://user-images.githubusercontent.com/5247527/56164350-ceddf600-5fd0-11e9-92a6-d8d0ca9bb4f5.png)
![image](https://user-images.githubusercontent.com/5247527/56164485-12d0fb00-5fd1-11e9-87b1-d0c382abd671.png)

**Device(s):**
 - Device: Desktop, 
 - OS: Windows 10, Android
 - Browser: Firefox 66, Chrome 73
 - Version: Latest

**Additional context**

**Comment by SlvrEagle23** [comment]
@Metal-Mighty The problem is definitely being caused by Rocket Loader, which loads content from sources that aren't in our specific approved list of sources. As part of improving the security of our application, we implement a "Content Security Policy" that specifies exactly what sources can be included on the page.

If this doesn't work with CloudFlare's rocket loader, you should disable that one feature. Other caching and other features within CloudFlare should work without issue.

**Comment by Metal-Mighty** [comment]
Disabling CF's Rocket Loader did solve the problem! Big thanks :)
