### ISSUE TITLE
Advertising Manager

### ISSUE THREAD

**Issue by Manuel19861** [AzuraCast/AzuraCast#1468]
Play jingles or advertising triggers with set times The jinges or advertising triggers are supposed to be able to lay down over DJs

**Comment by ivellios1988** [comment]
I think that a better idea would be to report issues in English rather than in German.

**Comment by Vaalyn** [comment]
For feature requests / proposals please use https://azuracast.featureupvote.com/. There people can upvote which features they'd like to have the most which helps us to prioritize them.

Also @Manuel19861 please write your text in english so that other people can also understand your proposal. You can also just translate your text from german to english via Google Translate.

**Comment by Manuel19861** [comment]
I have tried to translate in English unfortunately my Englich is not so good
