### ISSUE TITLE
Howto download a file from url and play it?

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#1477]
Hi, there are some content providers where you can buy news, weather, cinema news, etc. Mostly you can download a mp3 file from ftp or http. So my question is what would be the best way to download a file into a docker container and play it? It should be downloaded automatically every hour.

**Comment by ivellios1988** [comment]
You can create a PLS file with links to your MP3s (links should be starting with HTTP) and then upload this PLS in Playlist section in your AzuraCast installation. Just go to Playlists, add new playlist, put your PLS, send it and restart Liquidsoap. Provided that there are no connection issues between your server and server containing MP3s, AzuraCast will start downloading your MP3s and if all files are correct, Liquidsoap should play them fine.

Alternatively, you may place your PLS on an external server and put a link to it in Playlists section in your AzuraCast installation.

I don't recommend placing direct links to MP3 files in Playlist section. I already tried that in my AzuraCast installation and all MP3s were skipping instead of being played correctly.
