### ISSUE TITLE
What's going on while uploading song?

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#1487]
Hi,

it happened that a scheduled (custom) playlist didn't start on time (in fact, it never started). The log shows nothing. It's been very stable Liquidsoap starting scheduled playlists, if it could not, I always could see a hint the log. The only thing I can think of is that a long upload was in progress when the scheduled playlist was supposed to start. Do you think it's possible that Liquidsoap may not get a "chance" to work while uploads are going on?

Thanks

**Comment by SlvrEagle23** [comment]
@gammaw Highly unlikely, since Liquidsoap's scheduling happens internal to Liquidsoap itself, so as long as it's playing music it is taking into consideration all of the schedule switches that are configured.

If it's a problem with the system overall having too much CPU load, the error you'll see on Liquidsoap is often more along the lines of "we must catch up 0.xx seconds!" repeated over and over.

**Comment by Vaalyn** [comment]
I suspect that this issue is related to #1564. I'd advise you to follow that issue.

I'll close this issue now. If you still experience this problem after the other issue has been solved please let us know.
