### ISSUE TITLE
Playlist For Specific Time/Day failed to launch

### ISSUE THREAD

**Issue by adwinter** [AzuraCast/AzuraCast#1500]
**Installation method**
Bare-metal

**Describe the bug**
I set a playlist to play at a specific time and day and it failed to launch.

**To Reproduce**
I setup a playlist to play at a time that was the same day and about 15 minutes in the future. When the time came, even several songs after the allotted time, the playlist failed to fire.

**Expected behavior**
When the time came, the playlist should be played after the currently playing track.

**Relevant Logs**
The log did not reveal the playlist ever trying to fire at all. it just kept picking songs from the rotations.

**Additional context**
I did not restart the station when I made the new playlist and scheduled it. Is a restart required in this instance? Not sure if this is related to the "time of day" bug previously mentioned, or if its something else. Any help would be greatly appreciated.. Thanks all. :)

**Comment by Vaalyn** [comment]
Have you still not restarted your station? If not could you look into the liquidsoap config and see if the playlist schedule was updated there?

**Comment by adwinter** [comment]
Yeah, further testing -- after the restart the schedule worked as intended.
I should have done more testing before submitting the ticket.

It would be handy however if a restart was not required -- but I'm guessing this is a liquidsoap issue and not something Azuracast is doing. Thanks for your reply @Vaalyn - I appreciate the support even when I mess up on the troubleshooting. :(

Andrew

**Comment by Vaalyn** [comment]
I'm glad that it's working now.

About the reloading of Liquidsoaps configuration, yeah that's not something we can influence that much. LS configurations files are more fully fledged scripts / programs rather than just configurations. This makes it rather hard for the LS devs to add a hot-reload to the software. We also don't want to automatically restart the station when the config has changed as that would disrupt the streams for a moment.

You can read more about this stuff in these two issues ([1](https://github.com/savonet/liquidsoap/issues/110), [2](https://github.com/savonet/liquidsoap/issues/49)) on the LS repo.
