### ISSUE TITLE
Webdj doesn't work: some clarifications

### ISSUE THREAD

**Issue by dreinn** [AzuraCast/AzuraCast#1506]
Docker installation:
Hello,
Just a note, Azuracast is simply amazing, great work!
The only part I can't figure how to make working is Webdj.
Google Chrome doesn't ask me to enable microphone and all combobox are empty.
Since in the demo version of Azuracast it workss, I suspect there is something on my server.
Do you know if Webdj need specific ports?
For now, I use the port 81 for web and 8004 for stream, because the standard port are busy with other services.
The radioproxy is enabled, otherwise radio doesn't play.
Do you have some hints to give me in order to attempt to make Webdj running well?

**Comment by afonsosantos** [comment]
Hi @dreinn !

Do you have SSL enabled? I was having some trouble with my installation, and after enabling SSL, the WebDJ is working. You can create a free SSL certificate using [this ](https://www.azuracast.com/docker_sh.html#set-up-letsencrypt)tutorial, for free.
SSL is required due to some Chrome security rules.

**Comment by Vaalyn** [comment]
To add some further explanation, most browsers are tightening up their security restrictions on specific browser functions so that they only work on SSL secured pages. Access to media devices like mic and camera fall into this category so for the WebDJ to work you'll need to have this set up like @afonsosantos said. In general you should have SSL set up so that your login is also secure.

**Comment by Weigand-Dev** [comment]
I can't found the webdj in the profile

![1](https://user-images.githubusercontent.com/47525042/57313490-016ea080-70f0-11e9-80a7-28c685bc5acd.png)

**Comment by afonsosantos** [comment]
Hey @Weigand-Dev ,

You need to activate WebDJ in the Station Profile before using it.

**Comment by SlvrEagle23** [comment]
To clarify, @Weigand-Dev you have to enable public pages for your station, as the WebDJ is considered a "public" page since you can access it without an AzuraCast account.

**Comment by dreinn** [comment]
ok, first of all thank you for replying.
I made a test and yes, the problem is ssl, because with microsoft edge WebDJ ask me if I want to use the microphone, so I will solve the issue implementing ssl.
Last question, then I will close the ticket:
I created a DJ Streamer on Azuracast interface; 
On WEBDJ Screen I see the username and password field, but I don't find a button like "login".
Is it normal?
You digit your username, password, and then start streaming?

**Comment by afonsosantos** [comment]
Hi @dreinn 

After inputing your username and password, in the WebDJ interface, you should click on the **Start Streaming** button, like the screenshot below:

![image](https://user-images.githubusercontent.com/46262740/57384941-633f1100-71a9-11e9-9ccb-a36e435b919f.png)

**Comment by Vaalyn** [comment]
To explain why this works like @afonsosantos wrote, this is done because Liquidsoap our AutoDJ is responsible of taking care that the login of DJs is handled. So you have to connect to the stream with the account details in order to login. The WebDJ uses the [`webcast websocket protocol`](https://github.com/webcast/webcast.js) for streaming which is natively supported by LS.

**Comment by dreinn** [comment]
Hello!
I think if I solve this question this ticket will be closed :-)
I obtained a letsencrypt certificate with azuracast, so now I have ssl!
Chrome ask me permissions for using microphone. yeah.
But it is not enough.
Do you know if it is necessary to implement ssl in icecast also?
I modified the icecast configuration in order to implement ssl, it doesn't accept the letsencrypt certificate, so I put another that I have and is valid.
I obtain a 301 handshake protocol error with webdj, Google Console is my friend.
So the question is:: is it mandatory to have icecast secure?

Just for give complete information, I read that with letsencrypt I must concatenate 2 files into one for icecast, for example:
cat fullchain.pem privkey.pem > icecast.pem
No luck, always bad certificate.
I think I will write a little tutorial when Webdj will work!

**Comment by Vaalyn** [comment]
Sorry for the late response. As the WebDJ will only connect to Liquidsoap and not directly to Icecast you shouldn't need to have Icecast running on SSL.

**Comment by Vaalyn** [comment]
Closing the issue as there has been no further replies so I assume it to be resolved.
