### ISSUE TITLE
error 500 playlist 

### ISSUE THREAD

**Issue by alexwilliamlex** [AzuraCast/AzuraCast#1519]
Good evening, 
when I want to program my playlist it gives this. 
```
Call to a member function getError() on null
StationPlaylistForm.php : 39
```
thank's

**Comment by Vaalyn** [comment]
This is most likely due to a missing `enctype="multipart/form-data"` attribute on the form. I'm not sure why that is missing there as it is still in the forms configuration. I'll look into why this attribute is missing.

**Comment by Vaalyn** [comment]
The problem seems to be [this line](https://github.com/AzuraCast/azuraforms/blob/master/src/Form.php#L238). With the new UI update we implement a custom `File` class which now leads to the enctype missing due to a class mismatch as the `App\Form\Field\File` should extend the `File` class and not the `AbstractField` class.

**Comment by alexwilliamlex** [comment]
In which files should I modify?

**Comment by Vaalyn** [comment]
@alexwilliamlex You don't need to modify anything. I've already created a fix for this and submitted a PR. After the PR is merged you can update your installation and it should work again.

**Comment by Vaalyn** [comment]
@alexwilliamlex The PR is merged now. Please update your installation and try it again.

**Comment by Vaalyn** [comment]
@alexwilliamlex Have you updated your installation and is it working for you now?

**Comment by alexwilliamlex** [comment]
Thank you indeed it works. Question how do I program a podcast and jingles without passing the playlists?
