### ISSUE TITLE
Interrupt AutoDJ and Live Streams with Advertising / Jingle playlist

### ISSUE THREAD

**Issue by Manuel19861** [AzuraCast/AzuraCast#1535]
how is that?
WebHook triggers every 30 minutes

**Comment by Vaalyn** [comment]
@Manuel19861 Please be more descriptive with your issues!

This issue is so vague that I don't know if you are asking how you can let WebHooks trigger every 30 minutes or if you have WebHooks that only trigger every 30 minutes and you don't know why or even something entirely different.

If you don't know enough english to write the issue in english by yourself please just write the issue in Google Translate in your native language and post the translated text here. But please add more details!

**Comment by Manuel19861** [comment]
I'd like to START_AD_BREAK.mp3 every 30 minutes with WebHook. send to my stream even if a DJ is on air

**Comment by Vaalyn** [comment]
I think you misunderstand what WebHooks are. WebHooks are not something that you send TO AzuraCast, they are send FROM AzuraCast to external services via an URL.

@SlvrEagle23 Is it possible to interrupt live streams with automated ads?

**Comment by Manuel19861** [comment]
I would also be fine if he did a metadata update every 30 minutes with START_AD_BREAK.mp3

**Comment by SlvrEagle23** [comment]
@Manuel19861 @Vaalyn This is possible if you set up an "advanced" playlist and then provide manual configuration that interrupts _any_ stream audio and plays the jingle or advertisement. It's not possible using standard playlists, because the live audio signal has a higher priority than any other playlists.

**Comment by Manuel19861** [comment]
Then a question like how do I set up a playlist that sounds every 30 minutes I tried but it does not sound

**Comment by Vaalyn** [comment]
Closing this issue as there hasn't been a reply for quite some time and this is only possible by manually overriding the stream via the LS configuration. If you figured out how to do this via the advanced playlist feature please let us know so we can maybe put it in the documentation.
