### ISSUE TITLE
advanced playlist Works Not

### ISSUE THREAD

**Issue by Manuel19861** [AzuraCast/AzuraCast#1539]
advanced playlist Works Not

My attitudes are

![Unbenannt1](https://user-images.githubusercontent.com/43165831/57697397-6592e680-7653-11e9-96a3-e0818e5adac9.PNG)
![Unbenannt123](https://user-images.githubusercontent.com/43165831/57697399-66c41380-7653-11e9-8309-1f7a58e6fd4c.PNG)
![Unbenannt567](https://user-images.githubusercontent.com/43165831/57697402-66c41380-7653-11e9-8991-3c9d81046496.PNG)
![Unbenannt678](https://user-images.githubusercontent.com/43165831/57697516-b86c9e00-7653-11e9-8209-021bee9bcf39.PNG)

**Comment by Vaalyn** [comment]
Have you read the documentation for [Advanced Playlists](https://github.com/AzuraCast/azuracast.com/blob/master/AdvancedPlaylists.md)?

What did you add to your liquidsoap configuration?

**Comment by Manuel19861** [comment]
Liquid Soap configuration
![Unbenannt910](https://user-images.githubusercontent.com/43165831/57701299-05547280-765c-11e9-9e60-26e7c4696659.PNG)

**Comment by Vaalyn** [comment]
This is not the liquidsoap configuration that you have to add by hand like described in the document I linked. Please post what you added to the `Advanced Custom Configuration`.

**Comment by Manuel19861** [comment]
where can I find the advanced custom configuration

**Comment by Vaalyn** [comment]
At the bottom of the same page where you took the last screenshot.

**Comment by Manuel19861** [comment]
![Screenshot_2019-05-14 Edit Station - AzuraCast(1)](https://user-images.githubusercontent.com/43165831/57703311-1606e780-7660-11e9-948e-a27f543a5fcd.png)
![Screenshot_2019-05-14 Edit Station - AzuraCast(1)w](https://user-images.githubusercontent.com/43165831/57703312-169f7e00-7660-11e9-8fe2-6b3174a126f7.png)
![Screenshot_2019-05-14 Edit Station - AzuraCast(1)we](https://user-images.githubusercontent.com/43165831/57703315-169f7e00-7660-11e9-8071-ce56db1ef2b5.png)

**Comment by Vaalyn** [comment]
@Manuel19861 Do you realize that you posted EVERYTHING except the field that I requested from you? I want to see the field at the bottom of your last screenshot which is not readable there.

If you don't fully understand what I want to know from you please say so. If we have to pry everything we need to know out of you we are wasting time which helps nobody and is frustrating!

As I'm assuming that you didn't read or understood the document that I linked to you, you most likely haven't created a `Advanced Custom Configuration` so that field will be empty. Which is also the reason why your playlist is not working as an `Advanced Playlist`. You have to manually set your playlist to the `Song Playback Type` `Advanced` and then manually define how that playlist should be used in the `Advanced Custom Configuration` field. You can find more information about that in the document I linked to you.

-----

@Manuel19861 Ist dir bewusst, dass du alle Felder geposted hast bis auf das, dass ich von dir haben möchte? Das Feld ganz unten auf dem Screenshot ist das was ich sehen möchte und es ist nicht auf dem Screenshot zu sehen.

Wenn du nicht genau verstehst was ich von dir möchte, dann sag das bitte. Wenn wir dir die Infos aus der Nase ziehen müssen kostet uns das unnötig Zeit, hilft keinem weiter und frustriert!

Da ich davon ausgehe, dass du das Dokument das ich vorher verlinkt habe nicht gelesen oder verstanden hast, hast du auch keinerlei `Advanced Custom Configuration` erstellt also wird das Feld vermutlich komplett leer sein. Was auch der Grund ist warum deine Playlist nicht als `Advanced Playlist` funktioniert. Du musst deine Playlist selbst auf den `Song Playback Type` `Advanced` stellen und dann in dem `Advanced Custom Configuration` manuell einstellen wie diese Playlist benutzt werden soll. Mehr dazu findest du in dem vorher von mir verlinktem Dokument.

**Comment by Manuel19861** [comment]
@Vaalyn Meinst du das hier ?
![Unbenannt](https://user-images.githubusercontent.com/43165831/57704887-1785df00-7663-11e9-8830-a32c660efa1f.PNG)

**Comment by Manuel19861** [comment]
if so I would have to know what comes in there
because I do not understand the documentation unfortunately

**Comment by Vaalyn** [comment]
Yeah, that is the correct field and as I already thought it is empty. Please take some time to understand how [Advanced Playlists](https://github.com/AzuraCast/azuracast.com/blob/master/AdvancedPlaylists.md) work and build your own configuration. The `Advanced Playlists` feature is meant for power users that want something to work differently than what we offer by default so we don't have a piece of code laying around that we can just give you. We'd need to spend time to build and test everything first which we don't have the time for to do every time someone wants something custom build for them. If you don't understand the documentation because of the language then copy and paste it into [Google Translate](https://translate.google.com/?hl=de) if there is something in there that is not clear enough or something is missing then tell us and we see that we improve the documentation.

Alternatively you could also contact @SlvrEagle23 and pay him to build something customized to your use-case.

I'll close this issue now as it's clear that this is not an issue with the feature itself. I have changed the title of your other issue (#1535) where you already asked for this to better match what you search for.

--------

Ja, das ist das richtige Feld und wie ich bereits dachte ist es leer. Nimm dir bitte etwas Zeit um zu verstehen wie [Advanced Playlists](https://github.com/AzuraCast/azuracast.com/blob/master/AdvancedPlaylists.md) funktionieren und erstell dir deine eigene Konfiguration. Das `Advanced Playlists` Feature is für Power User gedacht die möchten, dass etwas anders funktioniert als wir es im Standard anbieten, dementsprechend haben wir auch keinen fertigen Code rumliegen den wir dir einfach geben können. Wir müssten erst Zeit darin investieren das selbst zu erstellen und zu testen. Wir haben keine Zeit das jedes mal zu machen wenn jemand etwas auf sich zugeschnittenes haben möchte. Wenn du die Dokumentation wegen der Sprache nicht verstehst, dann kopier sie nach [Google Translate](https://translate.google.com/?hl=de), wenn etwas in der Dokumentation nicht klar genug ist oder fehlt dann sag uns das und wir passen die Dokumentation entsprechend an.

Alternativ kannst du auch @SlvrEagle23 darum bitten gegen Bezahlung etwas auf deinen Use-Case zugeschnittenes zu entwickeln.

Ich schließe diesen Issue jetzt da es offensichtlich ist, dass das hier kein Problem mit dem Feature an sich ist. Ich habe den Titel deines anderen Issues (#1535) geändert um besser wiederzugeben was du eigentlich suchst.
