### ISSUE TITLE
Scheduling issue after update

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#1543]
Hi,
I updated this morning my docker installation today and, in now the scheduling view, all my scheduling has been shifted by 4 hours before the time it was set to. I am using CET. I tried to change times of several playlists, or change category but the changes are not taken into account. When pressing save changes in the playlist settings, it would bring me back to the Basic information Tab. Pressing 'save changes" again would reload this Basic information tab.

The current time in the station's time zone is shown correct.
I am getting this problem on the radio where I have the most programmed items. On other radio of the same azuracast instance, I don't have this issue.

**Comment by SlvrEagle23** [comment]
@griffon56 As we were converting from global timezones to per-station timezones, we also had to try to offset the existing schedule times for stations against UTC, so that they would work in the new version of the system. That's why your schedule times are modified.

The changes should definitely be saving, though...if you are returned back to the main "Basic Information" tab, try switching the tabs again and see if the system thinks you're missing information in a field on a different tab.

**Comment by griffon56** [comment]
Thanks for your feedback. Even if I turned off and on every option, changing names etc... It woulnd not take my modifications into account. I had to manually delete and create all my playlist.
