### ISSUE TITLE
Hide the jingle playlists from the schedule view

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#1545]
Hi,

The schedule view is a great tool to have an overview of a station programming.

I use customized "top if the hour jingle" and I have one playlist scheduled to be played for every hour. 9h playhlist is set to "scheduled" to start 9:00 AM and end at 9:00 AM .
RIght now the schedule view show this 10 seconds jingles playlist in a 2 hours slot (why 2 hours BTW?) on the schedule view.

Q : would it be possible to hide a playlist of the schedule view as soon as the "jingle mode" is set on it ?

**Comment by SlvrEagle23** [comment]
@griffon56 Turns out that's the default duration for timed events, 2 hours. Doesn't make much sense, so I set it to 20 minutes, which is the lowest you can go before it starts cutting off the visible text.

I also agree with the notion that "Jingle Mode" playlists probably aren't meant to be seen on the schedule view either.

Update includes both items.

**Comment by griffon56** [comment]
Many thanks for your help and hard work. I love Azuracast !!
