### ISSUE TITLE
Error in Icecast Config

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#1548]
Hi, i think there is a little error in icecast config file. When i look thru icecast logs i find entries like this 
`WARN xml/parsing unknown element "stream-genre" parsing "mount" at line 29`
in icecast config i find
`<stream-genre>Rock, Pop, Sport</stream-genre>`

But in Icecast Documentation http://icecast.org/docs/icecast-2.4.0/config-file.html i find
`<genre>classical</genre>`

**Comment by SlvrEagle23** [comment]
@LordHelmchen666 I've seen this in the logs for a while now, but it really wasn't a high priority to fix since it's a minor thing, and I wasn't sure if it was due to minor differences between Icecast versions.

It appears that I made the mistake of expecting Icecast to be consistent with its tags, i.e. `stream-name`, `stream-description`, `stream-url`, and then....`genre`.

It's fixed as of the latest update.
