### ISSUE TITLE
DJ Streamers/accounts for IceCast

### ISSUE THREAD

**Issue by athensguy** [AzuraCast/AzuraCast#155]
DJ streamers is a good option while it works only if set LiquidSoap (AutoDJ Service) as source and service suppose to be running. What If I'd like to use external playlist/autodj source not LiquidSoap ?

**Comment by SlvrEagle23** [comment]
@athensguy We actually originally had support for IceCast DJs, but as ShoutCast started becoming a more popular and supported platform on AzuraCast, LiquidSoap became the dominant method to handle DJs because it worked consistently across both frontends without any changes.

It's possible for me to turn back on the IceCast streamer/DJ support, though it likely wouldn't be advertised on the main web app, since it's less intuitive how failovers work in an IceCast situation.

**Comment by SlvrEagle23** [comment]
Closing this issue, as the more recent improvements (#308) depend entirely on Liquidsoap properly reporting back when a DJ connects or disconnects. It wouldn't be straightforward for us to support direct source connections via Icecast itself, as the notification method Icecast uses when DJs connect and disconnect is different.

An added benefit of using Liquidsoap as a mediator in this process is that Liquidsoap always counts as an actively broadcasting source to Icecast, so whether or not a DJ is connected to Liquidsoap, _something_ will always be broadcasting, and users won't be booted off because of dead air. If you intend to use Liquidsoap as a solution like this, it is recommended to add a blank MP3 file and have it loop on its own dedicated playlist (or just add a few AutoDJ songs/bumpers) so that there's something for the audience to hear in case a streamer/DJ disconnects from Liquidsoap. If you don't do this, your listeners will hear my voice telling you that you set up AzuraCast wrong. :P
