### ISSUE TITLE
Webdj: Unexpected response code: 301

### ISSUE THREAD

**Issue by dreinn** [AzuraCast/AzuraCast#1559]
Hello,
SSl regularly installed with letsencrypt.
When I make start stream in WEBDJ I obtain this (google console):
Error
webcast.js:395 WebSocket connection to 'wss://azura.nv-radio.it:444/radio/8001/' failed: Error during WebSocket handshake: Unexpected response code: 301

I'm using port 444 for https, 8001 for streaming dj.

**Comment by Vaalyn** [comment]
There seems to be a redirect happening when the connection to `wss://azura.nv-radio.it:444/radio/8001/` is started. Could you take a look at the Network tab in the browsers dev tools and see where the redirect is leading you to? I'm not sure what exactly is happening here so that may help us further understand that behaviour.
