### ISSUE TITLE
Known Issue: Playlists Not Playing at Scheduled Time

### ISSUE THREAD

**Issue by SlvrEagle23** [AzuraCast/AzuraCast#1564]
We're receiving a ton of reports that all basically mention the same situation:
- A playlist is scheduled to play once per hour or at a scheduled time during the day
- When this scheduled time arrives, either only a part of the playlist plays or none of the playlist plays.

We are aware of this issue and are working with the Liquidsoap team to come up with a suitable resolution (follow savonet/liquidsoap#779 for updates on that issue).

In the meantime, we are aware of at least two mitigations you can apply to increase the likelihood of songs playing during their scheduled block:
 - Expand the scheduled time to include a longer length of time (i.e. instead of playing at exactly 2:30, play from 2:30 to 2:45)
 - Check the box labeled "Interrupt other songs", which will cause Liquidsoap to play your scheduled playlist at its exact scheduled time regardless of what's currently playing.

This is a "super-issue" meant to be the merge destination for a number of very similar issue reports we're receiving via our GitHub. Please follow this issue for updates.

Thank you as always for your patience!

**Comment by johnjdutton** [comment]
FWIW, I have not had anything from my "Jingles" playlists ever play on any of my Azuracast stations since first installation back in mid-April.  And, I have updated the installation on both occasions that I received notification on the Dashboard interface to do so since then.  It is set up with "Default" weight, Random selection, hide metadata ("Jingle mode), Once every 30 minutes, Only play one track at scheduled time checked.  Perhaps this is also related to the issue mentioned here, or could there be something wrong with how I have this set up?

**Comment by themadcap1976** [comment]
Did this issue return? None of my scheduled playlists are activating.

**Comment by themadcap1976** [comment]
I can't seen to get the playlists to play at the set times. I have one playlist set to play at mulptiple times. Open a new case?
