### ISSUE TITLE
can't see administrator's page

### ISSUE THREAD

**Issue by jokic33** [AzuraCast/AzuraCast#1569]
**Using Docker installation method**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by jokic33** [comment]
i installed successfully via the docker but when i open the broswer and hit my ip, i see plesk's default page.is something that i missed?

**Comment by Vaalyn** [comment]
@jokic33 please fill out the issue template in the first comment of this issue so that we know more about your setup. Just submitting an issue where you've not filled out any of the basic information that we request from you is quite unhelpful for us and requires more time from us to get that information from you.

---

In general, if you see a different web page than the AzuraCast page then you most likely have another web server (like Apache or NGINX) running on your host machine. When starting AzuraCast via `docker-compose up -d` you'll get an error about the port `80` or `443` already being used by another process.

As you mentioned that you see a Plesk default page I'm assuming that you've installed Plesk on the same server where you've installed AzuraCast. You will either need to remove Plesk, let Plesk run on a different port/s or let AzuraCast run on a custom port/s. [Here](https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#use-non-standard-ports) is a guide on how you'd change the ports AzuraCast is running on.

**Comment by jokic33** [comment]
For the reason that i faced issues with ports 80 and 443 (already running), i have already changed them to 8999 and 10443 from .env file

**Comment by Vaalyn** [comment]
When trying to access AzuraCasts web interface, did you use these ports in the URL?
Example `http://example.com:8999/login`

**Comment by jokic33** [comment]
you have right...i didn't use the port to the url...thanks a lot!!!!!!!
