### ISSUE TITLE
Help troubleshooting stereotool integration

### ISSUE THREAD

**Issue by falcon03** [AzuraCast/AzuraCast#1570]
I am trying to integrate the command line version of stereotool within the azuracast pipeline, but I'm having no luck. I'd like to ask for help in order to troubleshoot the issue and get it working...

Following the advice in #749, first I tried adding
```
radio = mksafe(pipe(process='/extras/stereotool - - -s /extras/1.sts -q', radio))
```

in the advanced auto dj configuration. I got no errors, but the stream doesn't play anything; no audio is broadcasted even if apparently things are working, at least according to logs.

Then I tried creating a wave file output from the radio object, then piping that through stereotool, i.e.
```
output.file(%wav(stereo=true, channels=2, samplesize=16, header=true, duration=1.), "/tmp/audio.pcm", radio)
radio = mksafe(pipe(process='/extras/stereotool /tmp/audio.pcm - -s /extras/1.sts -q', radio))
```
getting the same result: no errors, but no audio as well.

Finally I tried an old snippet I wrote some time ago that worked fine in a previous liquidsoap setup not using Azuracast:
```
output.file(%wav(stereo=true, channels=2, samplesize=16, header=true, duration=1.), "/tmp/audioin.pcm", radio)
radio = mksafe(input.external("dd if=/tmp/audioout.pcm 2>/dev/null"))
```
but the same problem occurred: after running stereotool manually as required, no errors, but no broadcasted audio as well...

Could you help me integrate stereotool in azuracast please? I've already checked that a volume is created in /extras and that both stereotool and its settings preset are there and can be used from inside the container. Azuracast has been installed via docker on a Debian Jessie host.

While testing snippets 2 and 3 I noticed that the output file inside the container is never created. I've already inspected the logs, but I didn't find something that could explain this situation.

**Comment by SlvrEagle23** [comment]
@falcon03 We've received a bunch of questions about Stereotool and AzuraCast, so I want to summarize what our existing position has been for this software:

 - We have seen examples of Stereotool working with AzuraCast, though clearly from follow-up we've seen that "your mileage may vary". It isn't supported directly by us as it is entirely third-party software to our own.

 - We aren't rich people. Well, I'm not rich. I'm the opposite of that, think more "financially destitute". So, just like with SAM Broadcaster and other commercial software, if we contact Stereotool and they won't let us have an evaluation license to test integration with our software, we can't afford it.

 - Almost all questions (including this one) regarding how to integrate Stereotool into AzuraCast are actually questions about how to integrate Stereotool into _Liquidsoap_. While we know enough about Liquidsoap to use it as our software's AutoDJ, we are far from the subject-matter experts that the folks on [their repository](https://github.com/savonet/liquidsoap) are.

 - There are some questions about how Stereotool's license would work with our Docker image distribution method, and whether it would be permitted for us to distribute it directly alongside the rest of our software. Similar licensing situations are exactly why we don't offer SHOUTcast out of the box any more.

 - Given the number of requests we get for this specific thing, it would be worthwhile to add it to our [feature upvote page](https://features.azuracast.com/) for possible future inclusion as a "first-class" feature directly built into our software. Surprisingly, it hasn't been submitted there yet.

**Comment by falcon03** [comment]
@SlvrEagle23 First off, thank you so muhch for your explanation!

> * We have seen examples of Stereotool working with AzuraCast, though clearly from follow-up we've seen that "your mileage may vary". It isn't supported directly by us as it is entirely third-party software to our own.

I see, and in deed it's easy to find such discussions. The sad thing is that who says to have been able to get stereotool to work with azuracast never shared anything on the "final solution" :/ While stereotool is in deed a third party software, the high level component to integrate it with is azuracast, so I think its perfectly reasonable to expect people asking for information on its integration here in the first place.

> * We aren't rich people. Well, I'm not rich. I'm the opposite of that, think more "financially destitute". So, just like with SAM Broadcaster and other commercial software, if we contact Stereotool and they won't let us have an evaluation license to test integration with our software, we can't afford it.

Never, ever supposed that. And this adds to the fact that this software is amazing, really! But as you know unfortunately there are certain quality standards that need to be satisfied when broadcasting, and audio quality is one of them. Stereotool is emerging as a de-facto standard for accomplishing such goals as it allows you to get impressive results in no time. Just FYI, I'm not asking for it to be embedded in azuracast (even if it'll be great), but rather to have a way to integrate it within the pipeline...

Just FYI, you don't need to have a license in order to test stereotool; in the command line version, all of its features work. The only limitation is that if you use a feature that requires purchasing the license, the processed audio will contain some beeps and eventually a message announcing that the output has been processed by stereotool. We've been using the free version for over 3 years now, never needed to buy the license. This is better explained in the
[Stereotool FAQ](https://www.stereotool.com/faq/)

> * Almost all questions (including this one) regarding how to integrate Stereotool into AzuraCast are actually questions about how to integrate Stereotool into _Liquidsoap_. While we know enough about Liquidsoap to use it as our software's AutoDJ, we are far from the subject-matter experts that the folks on [their repository](https://github.com/savonet/liquidsoap) are.

OK, so I'll try asking for help on the liquidsoap repository as well. I just wanted to be sure the problem was in between liquidsoap and stereotool and not in the way, say, azuracast interacts with liquidsoap.

> * There are some questions about how Stereotool's license would work with our Docker image distribution method, and whether it would be permitted for us to distribute it directly alongside the rest of our software. Similar licensing situations are exactly why we don't offer SHOUTcast out of the box any more.

While it would be a great addition, I think that at least offering a working integration method (even requiring manual installation and configuration steps) could suffice for now. :)

> * Given the number of requests we get for this specific thing, it would be worthwhile to add it to our [feature upvote page](https://features.azuracast.com/) for possible future inclusion as a "first-class" feature directly built into our software. Surprisingly, it hasn't been submitted there yet.

While I understand that they are useful, I still tend to prefer Github issues directly. :) Once I'll get our setup moved to Azuracast I'll create that proposal if no one beats me on time!

**Comment by TraceOrdin** [comment]
I have a slightly different use case trying to get stereotool working on the live input, and it's been an uphill battle but I have been able to get audio coming through part of the time so I'll share where I'm at here in case it's useful to someone.

One thing that seems to make a difference is where in the order of things the stereotool pipe happens. For example I get audio if I put it right after the audio_to_stereo command, but if I put it after the part where it sets the fallback there isn't any audio.

So far it works when the first streamer connects and then disconnects, but when a second streamer tries to connect there's no audio and the logs show a repeating buffering error. So far it looks like the reason for this is that the stereotool instance spawned by the first streamer doesn't die and there's some kind of conflict.

Here's the part that makes it work for the first streamer, as set in the /var/azuracast/www/src/Radio/Backend/Liquidsoap.php file in a traditional install around line 547 (https://github.com/AzuraCast/AzuraCast/blob/master/src/Radio/Backend/Liquidsoap.php#L547) - the addition is the line with a comment above it:
```
            '# Live Broadcasting',
            'live = audio_to_stereo(input.harbor('.implode(', ', $harbor_params).'))',
            //next line added for stereotool routing
            'live = mksafe(pipe(process=\'/media/sf_web/azresources/stereo_tool_cmd_64 - - -s /media/sf_web/azresources/stereoToolConfig.sts\', live))',            
            'ignore(output.dummy(live, fallible=true))',
            'live = fallback(id="'.$this->_getVarName('live_fallback', $station).'", track_sensitive=false, [live, blank(duration=2.)])',
```

One thing I've been thinking is that maybe a 'named pipe' solution mentioned at the below post would help, so that it always uses the same pipe and hopefully the same instance of Stereotool, but haven't gotten to playing with it so that might be a red herring: https://github.com/AzuraCast/AzuraCast/issues/749

There's also some interesting discussion about that named pipe process as well as restarting of the process in this item from the Liquidsoap repo: https://github.com/savonet/liquidsoap/issues/607

I think stereotool by default wants PCM input and I also think (but can't find confirming docs anymore so it might not even be true) that the liquidsoap 'pipe' by default moves stuff around in PCM format too. This might not be the case but this idea is what got me to stop messing around with trying to convert the output format before piping.

I'm fairly new to liquidsoap, but definitely learning a lot trying to figure this out :)

**Comment by TraceOrdin** [comment]
so following on the logic from that last post I'm thinking that Stereotool needs a pure audio feed - without any of the liquidsoap routing data - in order to work.

That audio_to_stereo liquidsoap command seems to be where we can count on a clean audio feed that stereotool will digest.

my use case was for input and the use case in @falcon03's question is the output - so maybe there's a way to set up an audio_to_stereo at the tail end then route that through stereotool, before sending it to icecast or wherever? metadata would probably be an issue but maybe the sound would work
