### ISSUE TITLE
Twitter Webhook enhancement

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#1571]
Hello there
since Twitter has very strict rules , when it becomes to automated tweets, ( i became a victim twice in the past 24 hours, for unsolicited mentioning ) my goals is that each tweet has to be as much different as possible, so adding playlist, next song, duration would be great, but none of this works, it´s just blank
` {{ now_playing.album }} {{ now_playing.playing_next }}  {{ now_playing.duration }} `
I tried with and without `now_playing`
Only "Playlist" works, i double checked if the data/entry is available.

![Bildschirmfoto von 2019-05-22 22-06-26](https://user-images.githubusercontent.com/7961/58205112-2103ec80-7cde-11e9-807c-19825b5a32f8.png)

Thanks

P.S. I was asking about the album art lately, which is available in most cases. e.g. 
`"art":"https:\/\/stream.iradio.guru\/api\/station\/1\/art\/44e868d2f5983ad5c3f302bc.jpg`but why isn't it easy to embed into the twitter webhook again?

**Comment by Vaalyn** [comment]
The variables used for replacing these placeholder are coming from the [`NowPlaying`](https://github.com/AzuraCast/AzuraCast/blob/master/src/Entity/Api/NowPlaying.php) entity thus you can use what this entity and all entities available through it have to offer. That means if the `NowPlaying` entity has a field called `$playing_next` which is of the type [`SongHistory`](https://github.com/AzuraCast/AzuraCast/blob/master/src/Entity/Api/SongHistory.php) and has a field called `$played_at` then you can access the value by writing `{{ playing_next.played_at }}`.

For example to get the current songs artist + title you'd need to access `{{ now_playing.song.text }}` and to access the album art you'd write `{{ now_playing.song.art }}`.

**Comment by macbroadcast** [comment]
Thanks for your reply @Vaalyn but i don't understand what you're saying :confused:  
I tried `{{ playing_next.played_at }}` and it display "0" and `{{ now_playing.song.art }}` display nothing at all.Can you give me an example for Album/Duration and Play Next?
Here is my Play now output https://stream.iradio.guru/api/nowplaying

Thanks :blush:

**Comment by Vaalyn** [comment]
@macbroadcast As you can see in your API output the value of `playing_next.played_at` is `0` because it wasn't played yet. Frankly I don't really now why you want to show the `played_at` of the **next** song and not the current one.

`now_playing.song.art` will indeed give you a link to the image and it is on twitter to display it as an image. I didn't see any parameters in the Twitter API to specifically add an image URL that is not linking to an already uploaded image on Twitter.

**Comment by macbroadcast** [comment]
@Vaalyn My goal is that i want to display the name of the next song, so people know what's coming up after the current song. Display a link for the Artwork  isn't helpful at all, but thanks.
Isnt it possible to embed the Azuracast player (iframe ) into a webhook ? THis would be awsome,because people dont klick on external links, but if it would play on twitter, this would be it.

**Comment by Vaalyn** [comment]
@macbroadcast okay so you want to access `{{ next_playing.song.text }}` to display the next song but I still don't understand why you wanted to access the `played_at` data for the next song.

Regarding the Artwork link, that is not something that we can influence that much. Twitter decides what to do with links in Twitter posts so if they decide to not show previews for directly linked images that's up to them, not us. We could implement a specific [Twitter Card](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started.html) public page or add Open Graph data to the public player page so that you can link to that page and Twitter automatically displays a Card with a preview image and some information for that page. But you'll need to create a feature request for that over at https://features.azuracast.com.
Furthermore it is not possible to just embed iframes / arbitrary content in Twitter posts so we can't display a player on Twitter directly. If you find something that would enable us to do that in Twitter documentation let us know.

**Comment by macbroadcast** [comment]
Thanks @Vaalyn, i will try right now, guess you meant song "next" not text right ?`{{ next_playing.song.next }}` and what about the actual Album title since `{{ now_playing.album }}`does not work and the duration ? Will the duration displayed in seconds or minutes? 
I don't want to access the `play_at `data , misunderstanding i guess, you came up with this :smile:
I will investigate about the Twitter API / Twitter card , see hat i can find.

**Comment by Vaalyn** [comment]
@macbroadcast No, I meant exactly what I wrote. Take a closer look at the JSON from the API response:
```
"playing_next":{  
  "sh_id":17666,
  "played_at":0,
  "duration":191,
  "playlist":"Fresh",
  "is_request":false,
  "song":{  
    "id":"4bd70574de229bcd0fa4a4ff170d59cb",
    "text":"Shawn Mendes - if i cant have you",
    "artist":"Shawn Mendes",
    "title":"if i cant have you",
    "album":"2019",
    "lyrics":"",
    "art":"https:\/\/stream.iradio.guru\/api\/station\/1\/art\/2fe7f7cb9ce679f63e36cf3f.jpg",
    "custom_fields":[]
  }
},
```

The keys are `playing_next` -> `song` -> `text`. The same for the Album `playing_next.song.album`. Do you understand that mapping? The keys from the API response need to be chained by a `.` to access the fields. You cannot just skip keys inbetween that doesn't make sense to the software.

The variables of the entities I mentioned are used to access the data. Take a look at both the API response and the entities to better unterstand how that works together.

> Will the duration displayed in seconds or minutes?

The API response gives you seconds so that will also give you the value in seconds here.

>I don't want to access the play_at data , misunderstanding i guess, you came up with this 😄

That was just an example on how the mapping works, I somehow misinterpreted your question about why the value is `0` so sorry for that confusion. 😅

**Comment by macbroadcast** [comment]
Perfect, got it, thanks a lot @Vaalyn , :smile:  I see there is a custom field also, could i use the custom field to link to the artist twitter account or as "buy album link" for example?

**Comment by Vaalyn** [comment]
@macbroadcast The `custom_fields` can be defined in the administration pages, you could add for example `artist_twitter_handle` and `album_referal_link` as custom fields. Then you can manually add the handle / link to the music files. So yeah, you can do this but depending on the amount of songs you have this can become quite a monstrous task to do by hand. You may want to utilize the API for doing that and build a script to do that for you.

**Comment by macbroadcast** [comment]
Now there is a problem showing always the same song/artist as next song....
