### ISSUE TITLE
Referencing back issue - Can't update playlist. Mac browsers except Safari works fine #1555

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#1577]
#1555 - Save changes button doesn't work or does not do anything at all.
Maybe @Vaalyn can help for Mac users? Thanks guys!

**Comment by Vaalyn** [comment]
@ErnestPH Let's see if we can find out what it is that is preventing the save button from working.

Are you on the newest version with the number #a3f8db7 ?
If not please update and try again.

Then when you clicked on the save button if something went wrong on the server side you'd get an error message at the top of the page, telling you what went wrong. Is there something like that now?

When you open the browsers JavaScript console do you see any errors?

**Comment by ErnestPH** [comment]
Hey @Vaalyn thanks for the reply…

Yes I am on the newest version.

I saw few JS errors
```
[Error] Failed to load resource: the server responded with a status of 404 () 
[Error] Failed to load resource: the server responded with a status of 404 () (zxcvbn.js.map, line 0)
(bootstrap.bundle.min.js.map, line 0) - probably the listeners report (could be a different issue: z-index issue)
```
[This one when clicking the save event
[Error] An invalid form control with name='schedule_start_time' is not focusable.
[Error] An invalid form control with name='schedule_end_time' is not focusable.](url)

**Comment by Vaalyn** [comment]
Which browser are you using? If it is Safari, can you check if this also happens in Chrome and Firefox?

**Comment by ErnestPH** [comment]
It works both fine in Chrome and Firefox. Only Safari has the bug

**Comment by Vaalyn** [comment]
I can only see the 404 errors on my machine with the demo installation. The save button on that installation also worked for me on Safari.

Can you do some screenshots of how you configure the playlist before trying to save it?

**Comment by ErnestPH** [comment]
I was just changing the weight… 
[https://prnt.sc/nsrce4](url)

**Comment by ErnestPH** [comment]
Still not working after the update… Thanks @Vaalyn

**Comment by Vaalyn** [comment]
@ErnestPH Can you also show screenshots of all other tabs of that playlist? I want to try reproducing it with the exact same config.

**Comment by ErnestPH** [comment]
sure. [https://prnt.sc/nss0md](https://prnt.sc/nss0md)

**Comment by Vaalyn** [comment]
@ErnestPH You may have misunderstood me. I need to see the other configs of that playlist to be able to create a playlist with the same settings.

**Comment by ErnestPH** [comment]
oops… here you go [https://prnt.sc/nss522](https://prnt.sc/nss522)

**Comment by ErnestPH** [comment]
every time I click the save button, this error comes out in console

`[Error] An invalid form control with name='schedule_start_time' is not focusable.`

**Comment by Vaalyn** [comment]
@ErnestPH Thank you for the screenshots. I could finally reproduce the issue on the demo installation although I'm not sure yet what the cause is exactly.

**Comment by ErnestPH** [comment]
Awesome!

Quick question, is there an API already for automatic creation of radio stations once a button is submitted? Thanks again @Vaalyn

**Comment by Vaalyn** [comment]
Thanks to the work of @SlvrEagle23 the AzuraCast API has a lot of features that allow you to create and manage most things via API requests. Take a look at https://demo.azuracast.com/static/api/index.html#/ and scroll down to `Administration: Stations`

I think I've also found out why the form issue is happening: https://stackoverflow.com/questions/22148080/an-invalid-form-control-with-name-is-not-focusable

In short: The form has some elements that are `required` to be filled out correctly and the fields for `schedule_start_time` and `schedule_end_time` are normally set to be of the type `time` but Safari doesn't implement that form type yet so the elements are filled with the value `0` instead of the required `00:00` format thus the form validation will fail and when the browser tries to focus that element to show the error message the browser can't find the element (because it's hidden) and craps out.

**Comment by Vaalyn** [comment]
I think the best solution would be a polyfill for the form type `time` so that Safari users and users of other browsers who might not have that type too can use that more easily.

Right now you can use a workaround to get it working. Switch the playlist to Scheduled, set the value of those fields to `00:00` and switch back to the correct scheduling option you want. Then it should work.

**Comment by ErnestPH** [comment]
Confirmed working on the temp solution. Thanks!

**Comment by ErnestPH** [comment]
will close this as it's not a priority… and it's not replicating when doing the temp solution. Thanks guys!
