### ISSUE TITLE
Replace jQuery Bootgrid with a better maintained solution

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#1590]
When looking into how to style the selection checkboxes for the Music Files list I've noticed that the jQuery Bootgrid library hasn't been updated since 2015 on their GitHub repository.

We should replace this component with one that is actively maintained.

Currently with bootstrap-vue replaced jQuery Bootgrid tables:

- [x] Media Manager
- [ ] Song Requests
- [ ] Song Playback Timeline
- [ ] Song Listener Impact
- [ ] Audit Log

**Comment by Vaalyn** [comment]
As we are already using Vue.js for some parts of the application it would make sense to look for a solution that utilizes Vue. There seems to be a quite popular Material Design oriented component framework for Vue named Vuetify. If possible we could pull in just the [Data Table](https://vuetifyjs.com/en/components/data-tables) component from that.

**Comment by SlvrEagle23** [comment]
@Vaalyn Definitely open to ideas on this one, including just making these components Vue-driven as we migrate more and more of the application over to Vue components. Something like [this](https://ratiw.github.io/vuetable-2/#/) is a good contender.

**Comment by SlvrEagle23** [comment]
@Vaalyn Currently the two options I'm looking at are:

 - https://vuejsexamples.com/a-lightweight-vue-datatable-component-with-no-dependencies/

 - https://ratiw.github.io/vuetable-2/#/

I don't want to use the Vuetify one out of the box, because it seems fairly latched onto the Vuetify toolkit and I don't want to be tied down to any sort of Vue framework if we can help it. There's also a Material-ish looking one, but we don't need the Vue compoent itself to provide the material styling when our parent theme does that just fine.

**Comment by Vaalyn** [comment]
In commit cbe15e17e102f82e2c4b9e3ee5aab719d77cb6fc the media manager has been rebuild with bootstrap-vue. This is already a big step to replace jQuery Bootgrid and brought us some nice UX improvements there. I'll edit this issue to reflect the current status of the switch to bootstrap-vue for the jQuery Bootgrid tables.
