### ISSUE TITLE
Title/Artist data not streamed to VLC

### ISSUE THREAD

**Issue by Denniz** [AzuraCast/AzuraCast#1598]
**Using Docker installation method**
YES

**Host Operating System**
Ubuntu Server 16.04

**Describe the bug**
Using MP3 or OGG streaming the META data for each song played is not sent.
I've checked the settings on my station and broadcasting options, but except for "jingle mode" I can't find an option to enable/disable sending of Title/Artist data along with the stream.
On the webplayer (or public page) the META data is visible, but using an external player like VLC does not show the Title/Artist when the song changes.

- When using OGG streaming VLC usually shows the Title/Artist of the song playing when it first connects, but once that song finishes and a new song starts the first song data is still shown.
- When using MP3 streaming VLC shows no Title/Artist, instead it shows "stream / unknown artist" (on Android).

**To Reproduce**
Open stream in VLC using either PLS playlist or "stream" feature with URL.

**Expected behavior**
Title/Artist data in VLC changes when a new song comes on.

**Device(s):**
 - Device: VLC on Windows 7 & Android Phone or Table.
 - OS: Windows 7, Android
 - Browser: -none-
 - Version: -latest release for OS-

**Comment by SlvrEagle23** [comment]
@Denniz It sounds like this could be an issue with how VLC is dealing with the streaming audio signal coming from Icecast.

Just to confirm, you're using the Icecast broadcasting frontend, not SHOUTcast, right?

**Comment by Denniz** [comment]
> @Denniz It sounds like this could be an issue with how VLC is dealing with the streaming audio signal coming from Icecast.
> 
> Just to confirm, you're using the Icecast broadcasting frontend, not SHOUTcast, right?

Yes, I'm using the Icecast frontend that comes with the docker install. And no additional software (that might influence AzuraCast) is installed on the server.

**Comment by SlvrEagle23** [comment]
@Denniz Whether media players show the metadata sent through Icecast has always been a bit of a gamble. It's not consistent across the board between players.

The problem is that the components in charge of this (in this case, both Liquidsoap and Icecast) are likely functioning by design, since as long as you're still seeing "Now Playing" data inside AzuraCast, metadata is being correctly managed by Liquidsoap and correctly transmitted over to Icecast. That would mean the issue is between Icecast and the listening client, which isn't something AzuraCast can really influence.

The problem with Icecast is that we maintain a fork-of-a-fork (our own customized fork of icecast-KH, Karl Heyes' customized version of Icecast with numerous improvements), so if there is a fix to the metadata handling, it would have to make its way downstream to us.

**Comment by JDBlackman** [comment]
I've had this issue in the past and put it down to https. It seemed to work 100% of the time with non https.

I found this issue with VLC which sums up that Icecast's implementation of HTTPS isnt properly implemented and refuses to support the "legacy hack"

https://trac.videolan.org/vlc/ticket/21057

**Comment by fafamonge** [comment]
I have the same problem. VLC cannot catch correctly the metadata over the HTPPS. But works with Non-HTTPS (HTTP). 

So, I suppose  is something related to this because  it doesn't works in any player. Maybe the way the metadata is sending through the protocol.

In web player shows good, all metadata complete.

**Comment by Vaalyn** [comment]
I’ve done some tests using VLC macOS version 2.2.1 and 3.0.7.1. For my radio it is working on both versions with non SSL URL:
https://prnt.sc/oo56bl
http://prntscr.com/oo58mx

When using the https URL it stops working.

To further investigate the cause of this I’ve also tested it with my local dev installation (newest AC version) on VLC 3.0.7.1 both with `/radio.mp3` and `/stream` as well as with the web proxy and without:

Without SSL:

- `/radio.mp3` no proxy = working
- `/radio.mp3` with proxy = working
- `/stream` no proxy = working
- `/stream` with proxy = working

With SSL:

- `/radio.mp3` no proxy = not working
- `/radio.mp3` with proxy = not working
- `/stream` no proxy = not working
- `/stream` with proxy = not working

So it looks like it’s the SSL encryption that seems to be causing the issue and the mountpoint name seems to be of no importance to this issue.

For comparison in iTunes the metadata is showing both with and without SSL. So the metadata itself seems to be available on the stream but VLC seems to be unable to use it.

I’ve found an interesting post on the videolan forum that recommends using `icyx://` instead of `https://` and when I use that for the URL in VLC the metadata is correctly shown.
I’ve tried that with both my radio and the demo radio. On my radio it works with the web proxy and without but on the demo installation it still doesn’t work at all. That one is also running behind CloudFlare so that might also have some impact there. In iTunes `icyx://` is also working correctly for my radio but not for the demo radio.

**Comment by christiansacks** [comment]
using icyx:// it does work fine, but https:// doesn't. has there been any movement on this? is icyx:// still using SSL?
