### ISSUE TITLE
Managing Docker environment

### ISSUE THREAD

**Issue by bayubad** [AzuraCast/AzuraCast#1609]
Do you recommend managing AzuraCast Docker environment with Portainer CE?

**Comment by Vaalyn** [comment]
I have no experience with Portainer so I can't say much about it but it seems to support creating stacks from docker-compose.yml files and supports the version we are using. In theorie it should work but I don't know if it will.

**Comment by SlvrEagle23** [comment]
@bayubad I used Portainer locally a few times, and it seemed to work just fine for me. It's a neat tool. I would still use the `docker.sh` script for updates (as we run a few other commands during updates that are important, beyond just pulling down the latest container images), but otherwise it's completely okay to use it in my experience.
