### ISSUE TITLE
Custom CSS for Public Pages

### ISSUE THREAD

**Issue by bayubad** [AzuraCast/AzuraCast#1613]
How can I find a complete tutorial and examples for Custom CSS for Public Pages and Custom JS for Public Pages codes?

**Comment by SlvrEagle23** [comment]
@bayubad I don't think this is the first time you've posted this question on here, but to answer your question, since the custom CSS supports any type of CSS that the browser supports (it's literally just injecting a block of CSS directly into the HTML for rendering) and the same applies to the JavaScript in the custom JS block, it's outside the scope of our work here on AzuraCast to provide tutorials for CSS and JavaScript themselves.

If you have something in particular you would like to change, you can post the question and see if other community members will help you with the instructions, but we are a very small team who works very hard and can't provide answers for every possible scenario.
