### ISSUE TITLE
Playing all songs by artist in same playlist

### ISSUE THREAD

**Issue by JDBlackman** [AzuraCast/AzuraCast#1616]
(First of all apologies for the weird title, I couldn't really sum up what it was without it sounding like i'm complaining about multiple artists in a row again). 

**Using Docker installation method**
yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
This bug is a bit of a strange one and hard to explain. I've noticed this across two of my stations. 

What seems to be occurring is that it will play from a weighted playlist, for example, this playlist is weighted at 2 (15.4%). 

<img src="https://i.imgur.com/Hxe7XCq.png">

Something seems to happen, where it will then repeat that artist (which is in the same playlist) multiple times in a row. I would say this happens a little too much to be a coincidence that its the same artist from the playlist. This playlist in particular has 87 songs in it. 

<img src="https://i.imgur.com/FgsCWz3.png">

It seemed to play the artist 3 times in a row before finally switching to a different playlist. 

This happens with quite a few songs, it seems to play all tracks by the artist (in that playlist) before moving on. Heres a few more examples:

<img src="https://i.imgur.com/9jtYbpo.png">
<img src="https://i.imgur.com/YkvOjOq.png">
<img src="https://i.imgur.com/R3NrUPV.png">
<img src="https://i.imgur.com/m9575G6.png">

All these playlists are on "Shuffled" mode for the playlist. 

**Additional context**
This is just my observation, and could be another cause completely but just my thoughts. Any input on this would be greatly appreciated.

**Comment by Vaalyn** [comment]
This could be bad luck. A "shuffled" playlist is shuffled once and then the same order will be used over and over again. If the first shuffling randomly ordered the tracks in that way this will happen quite often.

**Comment by JDBlackman** [comment]
Anyway to force a reshuffle? Just a simple from Shuffle to random back to shuffle?

**Comment by Vaalyn** [comment]
@JDBlackman That should work to reshuffle them I think.

@SlvrEagle23 General question from me about the shuffled mode. In my mind a shuffled playlist is quite similiar to a sequential playlist just that it is shuffled once. Would it make sense to merge the shuffled and sequential playlists into the same type and just add an option to re-shuffle a sequential playlist?

**Comment by SlvrEagle23** [comment]
@Vaalyn A shuffled playlist is actually shuffled at the end of every "loop" of the playlist, or whenever it's reloaded remotely (i.e. by AzuraCast). We internally were attempting to change the shuffling on the AzuraCast AutoDJ from the way you described to the way Liquidsoap operates, and it caused a really alarming number of incidents like this, where songs weren't distributed evenly, which is why it got replaced by the Liquidsoap AutoDJ for now.

@JDBlackman Are you on the very latest version of the codebase (i.e. rolling-release, not the latest point release)?

**Comment by JDBlackman** [comment]
@SlvrEagle23 

We use rolling-release however we are currently on "v0.9.5, #54c9e52 (2019-05-19 15:30) • Docker • PHP 7.2". I did check if there was any updates regarding shuffling or playlists but couldn't see anything significant before making the post.

It is quite hard to find times to update because of the process we have to go through without bringing downtime to the station.

**Comment by Vaalyn** [comment]
If you are on the newest AzuraCast version / the newest that changes the playlist / shuffling then I think this is most likely just bad luck with the shuffling. I'm not sure if there is much that we can do to improve the shuffling itself in that regard without introducing some new feature.

There is already a [feature request](https://features.azuracast.com/suggestions/39446/setting-for-not-repeating-an-artist-within-x-amount-of-time) for implementing a configuration to prevent the same artist from playing in x amount of time. I'm not sure how much work it would be to implement this but it seems to be important for professional users who are required to ensure such a limit because of licensing reasons. I'll see if I can get more information about how this could be implemented so that we have a more clear picture of what would need to be done for that.

As there is currently no obvious bug (at least none that I can see) in the shuffling I'll close this issue now.
