### ISSUE TITLE
NGINX????? i though it was APACHE2

### ISSUE THREAD

**Issue by darkjedeye** [AzuraCast/AzuraCast#162]
DID an install on my ubuntu 14.04 server (VPS) and it fails on the mariadb user clense, and then, when trying to access server... it tells me that inginx is installed. am i doing something wrong????

**Comment by mkody** [comment]
The install script will **indeed install Nginx**.  
Since the installation failed mid-part, it's obvious that you'll only see the "Nginx is installed" page, until the installation script can be completed.

Please try to re-execute the `install.sh` script and if it still fails, please copy the logs in the comments here :arrow_down: so we can help you.  
Saying "IT'S NOT WORKING" without any details isn't actually the good solution if you expect some help. :wink:

**Comment by darkjedeye** [comment]
lol... sorry my bad... thought you may have had the experience with this... trying the docker rout though... will let you know

**Comment by darkjedeye** [comment]
got the following on my vps which has been updated to 16.04

563a83b645e2: Pull complete
129339fddbc9: Pull complete
46334e3fd686: Pull complete
Digest: sha256:d145c5d70f798700941ef1b4343f40c48336cbd1676710db3ba8b44b55a436bc
Status: Downloaded newer image for azuracast/azuracast_web:latest
Pulling nginx (azuracast/azuracast_nginx:latest)...
latest: Pulling from azuracast/azuracast_nginx
6f821164d5b7: Already exists
43dfefee8e05: Pull complete
a93f78d7923c: Pull complete
a9ea3624aa7f: Pull complete
eec2e6c33c41: Pull complete
531b9a05a9c6: Pull complete
4c508415c385: Pull complete
86bddd335f6d: Pull complete
d5d83c614481: Pull complete
baf35dbab695: Pull complete
Digest: sha256:16f14329dcc8cdaaf35ceaf7ab18fdfe6399d4e726d7f57e9a759a9e5866952d
Status: Downloaded newer image for azuracast/azuracast_nginx:latest
Pulling cron (azuracast/azuracast_web:latest)...
latest: Pulling from azuracast/azuracast_web
Digest: sha256:d145c5d70f798700941ef1b4343f40c48336cbd1676710db3ba8b44b55a436bc
Status: Image is up to date for azuracast/azuracast_web:latest
Pulling cli (azuracast/azuracast_web:latest)...
latest: Pulling from azuracast/azuracast_web
Digest: sha256:d145c5d70f798700941ef1b4343f40c48336cbd1676710db3ba8b44b55a436bc
Status: Image is up to date for azuracast/azuracast_web:latest
Creating network "azuracast_default" with the default driver
Creating volume "azuracast_db_data" with default driver
Creating volume "azuracast_influx_data" with default driver
Creating volume "azuracast_station_data" with default driver
Creating azuracast_redis_1
Creating azuracast_influxdb_1
Creating azuracast_mariadb_1
Creating azuracast_stations
WARNING: Connection pool is full, discarding connection: localhost
WARNING: Connection pool is full, discarding connection: localhost
WARNING: Connection pool is full, discarding connection: localhost

ERROR: for stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (d1fcd966cdc0e22cae51dd274b1b0897a6686e30a550bf33c49d279abacc45a6): Error starting userland proxy: listen tcp 0.0.0.0:8088: bind: address already in use
ERROR: Encountered errors while bringing up the project.
azuracast_redis_1 is up-to-date
azuracast_influxdb_1 is up-to-date
azuracast_mariadb_1 is up-to-date
Starting azuracast_stations

ERROR: for stations  Cannot start service stations: driver failed programming external connectivity on endpoint azuracast_stations (e143e1727cf437c8c9f83d8134314e80ce21256a7634df319390062311bda640): Error starting userland proxy: listen tcp 0.0.0.0:8088: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by darkjedeye** [comment]
fixed it by using service influxdb stop

**Comment by darkjedeye** [comment]
working on docker

**Comment by SlvrEagle23** [comment]
@darkjedeye Yes, AzuraCast does use nginx as its web server. I have updated the readme to clarify specifically what software stack is "bundled" with AzuraCast's default installer.

If you've already installed AzuraCast using the traditional method, I would recommend re-imaging your server using a fresh OS image before moving to Docker, preferably an image of Ubuntu 16.04 instead of 14.04. That will help prevent future issues.

As for your original installation problem with 14.04, do you happen to have the logs from that installation? I would like to look into it and see if we can fix the issue that caused it.

**Comment by darkjedeye** [comment]
Hi there... sorry... i will reinstall on a 14.04 system soon... just been busy developing the station for a community.... and will get back to you...but if i am not mistaken, he problem came about as the server had ispconfig3 previously installed... and was not a fresh reload

**Comment by SlvrEagle23** [comment]
Closing this issue for now. Feel free to create a new one if the same issue appears on a fresh install.
