### ISSUE TITLE
Backup and restore Docker install

### ISSUE THREAD

**Issue by williambatson** [AzuraCast/AzuraCast#1624]
Ubuntu 16.04  Docker Install - migrating from Ansible, just completely ruined 2 perfectly good / working servers.
Can someone share how to back up the stations and content in these 'new' Docker installations in such a way as I can wipe this messed up migration and start all over - then import my stations and content back?    I need to get on get my servers back up and found no solution to the migration problem.
I'm not familiar with Docker -  should have stayed where I was with Ansible - it worked for me anyway....    So I could use a hand with back and restore functions of my station sand content if possible.
Thanks in advance.

**Comment by SlvrEagle23** [comment]
@williambatson You never actually talked to us via Slack...we're happy to work with you on this situation, but I didn't ever see you join the server even.

**Comment by williambatson** [comment]
I posted 2 questions there -   maybe I didn't do it right??    
https://gyazo.com/b40812556417d17b3c25814f35c16056

there are my 2 posts -  what did i mess up?  lol   If i did, my bad.

**Comment by williambatson** [comment]
btw -  uploads are not working either....   first few songs get half way up and then everything stalls
So it's getting weird and frustrating

**Comment by SlvrEagle23** [comment]
@williambatson Ohhhh we have the Github channel muted. You can talk in general and we can help you. You'll want to DM me directly on there with your installation details.

**Comment by SlvrEagle23** [comment]
Update: after discussing this issue further, it appears the majority of the problems were caused by the fact that by default, our Docker installation only directly forwards ports from 8000 to 8099.

As this may indeed be a common problem for operators looking to run more than 10 stations on a Docker installation, I have added instructions for this specific scenario to our Support document: https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#expand-the-docker-radio-station-port-range
