### ISSUE TITLE
Requested song doesn't play when the current song is skipped. 

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#1642]
**Using Docker installation method**
Yes
**Host Operating System**
Ubuntu Linux 18.04.2

**Describe the bug**
When you request a song and then skip the current playing song, it doesn't play the requested song. 
**To Reproduce**
- Turn on the radio
- Request a song
- Skip the current playing song
- Check what song comes next. 

**Expected behavior**
The correct song to play, not a random song from playlist. 
**Relevant Logs**
Unable to locate any abnormal logs.
**Screenshots**
[Current song](https://puu.sh/DDFVd.png)
[Requested song list](https://puu.sh/DDFW2.png)
[Incorrect song plays](https://puu.sh/DDFXu.png)
**Device(s):**
 - Device: Desktop 
 - OS: W10
 - Browser: Brave
 - Version: Latest

**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch Just to be clear, does the requested song play one song after the one that plays when skipped? If so, this is likely a result of the fact that in order to prevent you from hearing the "This station is powered by AzuraCast" jingle when skipping songs, we maintain a constant buffer of two songs to play (the one currently playing, and the next one), so it would make sense that it skips to the next song in that queue instead of to the requested song.
