### ISSUE TITLE
Native app install smart banner in FM public page.

### ISSUE THREAD

**Issue by muppathimoonu** [AzuraCast/AzuraCast#1647]
It would be better if we have prebuilt native app (Android & iOS) install banner. which can be enabled/ disabled / configured in system administration page.

**Comment by Vaalyn** [comment]
I think this needs some clarification.
Do you mean an app that enables you to control AzuraCast?
Or one that enables you to listen to the streams via that app?
Or one that enables you to broadcast from the app to AzuraCast?
Or do you want to be able to just configure App Store links for iOS and Android so that you can link to any app that you want to promote on the public page?

**Comment by muppathimoonu** [comment]
one that enables listeners to listen to the streams via that app. which also lnks to Android / iOS app Store if the app is not installed in user's device.
https://github.com/kudago/smart-app-banner or
https://github.com/ain/smartbanner.js this with proper configuration options in admin page.

**Comment by Vaalyn** [comment]
Thank you for the clarification.
Please create a feature request for this on https://features.azuracast.com/.
