### ISSUE TITLE
Getting Errors on Installing

### ISSUE THREAD

**Issue by ThePlugTM** [AzuraCast/AzuraCast#1658]
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by Vaalyn** [comment]
After talking via Slack the problem in this case is that the VPS used is virtualized via OpenVZ. Getting Docker to run on another container is rather difficult. The recommended solution is to switch the VPS to one that is not a containerized one like for example via KVM.

As we have been getting a few reports were this was also the problem I've created an issue for the documentation so that this will be highlighted on the installation page as a warning: https://github.com/AzuraCast/azuracast.com/issues/8
