### ISSUE TITLE
not function view next played song in script

### ISSUE THREAD

**Issue by radiowestcz** [AzuraCast/AzuraCast#1659]
**PLEASE DO NOT SUBMIT FEATURE REQUESTS THROUGH GITHUB!**

We have a special web site dedicated to submitting and voting on new features for completion.

Submit your feature request at [features.azuracast.com](https://features.azuracast.com/).

**Comment by Vaalyn** [comment]
If you want to report an issue please use the correct issue template and supply us with a description that helps us to identify what the actual issue is and what you expect.

Please edit this issue to provide us with the information we request from you in the [bug report template](https://github.com/AzuraCast/AzuraCast/issues/new?template=bug_report.md).

Until then I'll close this issue.
