### ISSUE TITLE
Sequential playlist crisscrossed and without Playist in Metadata

### ISSUE THREAD

**Issue by aldorr** [AzuraCast/AzuraCast#1660]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
Playlist doesn't always show up in metadata. (While playing same playlist, the playlist name just drops and returns from track to track.)
When they play, a lot of times the sequence is messed up and sometimes tracks are repeated.

**To Reproduce**

**Expected behavior**
I expected the playlists to play only once, and in order.
I also expected the playlist name to show up in the meta.

**Relevant Logs**

[fuxpax_timeline_20190607_to_20190613.xlsx](https://github.com/AzuraCast/AzuraCast/files/3286936/fuxpax_timeline_20190607_to_20190613.xlsx)

**Screenshots**
<img width="895" alt="Screen Shot 2019-06-13 at 17 29 37" src="https://user-images.githubusercontent.com/181683/59445997-eb47b480-8e00-11e9-81fb-9dabab0107c3.png">

**Device(s):**
 N/A

**Additional context**
It seems Azuracast believes it is a live broadcast, when it's really coming from a playlist.

**Comment by SlvrEagle23** [comment]
@aldorr Are you actively adding or removing things from the playlist as you're checking it for changes? Making changes to the playlist will trigger Liquidsoap to reload it, which will cause it to play "out of order" by resetting.

Also, the issue with some songs displaying as "live broadcast" and not getting playlist association is known, and we're struggling to come up with a reliable solution to this due to the involvement of multiple pieces of software. We're definitely aware of it, though, and working to resolve it.

**Comment by aldorr** [comment]
Thanks @SlvrEagle23.
Currently I have not changed the playlists for about a week. So, no one is changing playlists while running. That would have been too easy. ;-) I'll keep an eye on it, and see if I can figure out when it's happening. If there's a pattern.
And okay, that's great that it's not just me, but sorry to hear about the struggle. I don't believe I will be able to help, but I started thinking about alternatives... like extra song id3 tags for the playlist.
