### ISSUE TITLE
Matrix bot/web hook just like the discord bot and webhook (suggestion)

### ISSUE THREAD

**Issue by andrewfer000** [AzuraCast/AzuraCast#1662]
Matrix (and riot.im) are great Privacy and user right supporting chat networks. They are Free Open Source Software like AzuraCast and I think it would be cool to be able have a bot for that too. I'm not sure if a Matrix bot would work but the web hook is still a good option if that's easier and will work better.

**Comment by Vaalyn** [comment]
Please create a feature request over at https://features.azuracast.com/. We are managing feature request for AzuraCast through this tool so that we can better prioritise them.

I've done a quick search for WebHooks in Matrix but I seem to only find 3rd party extensions for different WebHooks. Does Matrix have some native WebHook implementation or is there a preferred default project that most people use for that?
