### ISSUE TITLE
Live streamers unable to connect

### ISSUE THREAD

**Issue by BlazinWings** [AzuraCast/AzuraCast#1675]
I've tried just about everything imaginable here. I've tried the source:password (which was generated by default), I have tried creating a streamer account and connecting to it with both Icecast and shoutcast using their respective ports, I've tried changing mountpoints and stream formats, with no luck. The server isn't firewalled, and the ports should be open regardless. Thoughts?

**Comment by SlvrEagle23** [comment]
@BlazinWings Do you have any unusual characters in your password, and can you try swapping those characters out for a regular alphanumeric password and seeing if that connects?

Also, what software are you using to connect?

If you're on the Docker installation, you should make sure that you're using one of the forwarded ports, which is the range from 8000-8499 (excluding 8080), or manually forwarding whatever port your station is using.

**Comment by BlazinWings** [comment]
Thanks so much for your quick reply! Both the streamer account
password and the password generated by Azura are alphanumerical. I
haven't tried creating a custom source password, but regardless I
would think that the streamer account would work.
I am using station playlist to connect, via Oddcast V3. Azura is
generating its own ports, and they seem to be open because I can tune
into the auto DJ.

Thank you again for your help and patience!

**Comment by SlvrEagle23** [comment]
@BlazinWings The outgoing listening ports and incoming connection ports are different for each account, and in order to broadcast using the Liquidsoap incoming connection port, you should enable the Streamer/DJs feature and then use the connection information available on the "Streamers/DJs" page.

**Comment by BlazinWings** [comment]
That's the process I have followed, ensuring that DJ's are allowed to
connect and using the Icecast connection info on the page mentioned.

**Comment by BlazinWings** [comment]
After extensive trouble shooting, I am still unable to connect. I have tried with both Oddcast and Sam encoders using station playlist, using the source credentials and the custom DJ credentials, various mountpoints and streaming formats, all via the info provided on the DJ page. Nothing seems to be working. Could anything else be affecting this?

**Comment by Simon818** [comment]
I've been troubleshooting this sporadically and haven't got anything new to add. I notice that the icecast connection info doesn't include a password; is that still just user:password? If so, both Icecast and Shoutcast are not able to connect. Of course I can connect directly to the icecast server using the source password, but this does not allow me to kick off the automation stream and has no support for DJ accounts. Connecting through Liquidsoap's provided server fails. More specifically, a connection is established but the credentials are rejected. Suggestions would be appreciated.

**Comment by SlvrEagle23** [comment]
@Simon818 @BlazinWings I've added some logging to AzuraCast's side in the most recent versions of the app, so it will indicate if there's an error during the DJ authentication process. You should try to connect again, and check the AzuraCast logs (visible from the system-wide "Log Viewer" page) to see if it reports back any errors.

**Comment by Simon818** [comment]
Thanks. one quick larification: I notice that the shoultcast connection details list the password as username:password while the icecast details don't list a password at all. Am I still supposed to use the username:password format there? We've opted not to use Shoutcast because of its quality restrictions.

**Comment by SlvrEagle23** [comment]
@Simon818 Those aren't different instructions based on whether you're using Icecast or SHOUTcast as your broadcasting frontend; you can connect with either protocol to Liquidsoap regardless of frontend. The reason we list both is because some DJ clients will only support one or the other, so you should use whichever your client supports.

If you're connecting with an Icecast-capable DJ software, you should see both a username and password field. This corresponds to the DJ's username and password, so there's no need for splitting them with ':' or any other character.
