### ISSUE TITLE
External Radio Server Stats

### ISSUE THREAD

**Issue by kbysfm** [AzuraCast/AzuraCast#168]
Should I be able to see listener reports / google map listeners locations while configured as an external radio server? I have generated an API, but i have to manually type in station/sid/reports/listeners in order to see the page. 

That said, the page does resolve and even shows the google map, however stats are missing.

**Comment by SlvrEagle23** [comment]
@kbysfm At the moment, no, external radio servers don't have the more detailed listener tracking that the internal IceCast/ShoutCast does, for one simple reason: I can't guarantee that the version of the external radio server will be the exact version that offers those listener APIs, so rather than assume that it might be, right now I'm leaving that feature out to ensure the rest of the syndication works well regardless of the remote server's software version.
