### ISSUE TITLE
How do I custom the PLS playlist file

### ISSUE THREAD

**Issue by fafamonge** [AzuraCast/AzuraCast#1686]
By default, the system generates this:

```
[playlist]
File1=https://www.hdradiostreaming.com:10443/radio/8000/fafas_smooth_jazz.mp3?1559996295
Length1=-1

NumberOfEntries=1
Version=2
```

I want to custom to this:

```
[playlist]
NumberOfEntries=1
File1=https://www.hdradiostreaming.com:10443/radio/8000/fafas_smooth_jazz.mp3?1561132934
Length1=0
Title1=HDRADIOSTREAMING.com - Fafa's Smooth Radio
Version=2
```

What means the number after the "?" in the mounted point?

**Comment by SlvrEagle23** [comment]
@fafamonge The `?` and the number after it are the current UNIX timestamp, which is appended to the URI as a "cache-buster" in order to prevent certain browsers/players from playing back a previously played stream file instead of the live stream. In most cases you can safely remove it, as this issue is more prevalent with older browsers like IE6-8.

**Comment by Vaalyn** [comment]
Regarding customizing the automatically generated .pls files there is no official way to do that at the moment. You can create a feature request for that over at https://features.azuracast.com/ if you like.
