### ISSUE TITLE
Automatic Backup still not running

### ISSUE THREAD

**Issue by afonsosantos** [AzuraCast/AzuraCast#1691]
Hi!

After the update, my automatic updates are still not running at the specified time/hour.

(Docker install)

**Comment by SlvrEagle23** [comment]
@afonsosantos So at the specified hour, does anything appear in your logs?

**Comment by afonsosantos** [comment]
It's now working, IDK why it was'nt. If you need any log still, say something.

**Comment by afonsosantos** [comment]
Just wondering what are those **(stored 0%)**

![image](https://user-images.githubusercontent.com/46262740/59974849-b1b53d00-95a8-11e9-860b-f4e4a78b047b.png)

**Comment by SlvrEagle23** [comment]
@afonsosantos That's just normal output from the archive command indicating that instead of trying to re-compress the file (which is already a .tar.gz) it's just "storing" it inside the backup. This significantly improves performance by avoiding attempts to compress things that won't yield very beneficial compression results.

**Comment by afonsosantos** [comment]
Thanks!
