### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Luislife2004** [AzuraCast/AzuraCast#1693]
Hallo ich versuche gerade mit der API von azuracast zu arbeiten ,aber irgendwie bekomme ich es nicht hin.Ich möchte nämlich auf meiner webseite sehen welches Lied gerade auf meiner station laüft . Könnte mir da jemand weiterhelfen ? 
LG Luis

**Comment by Vaalyn** [comment]
When you create an issue here please write in english so that other people are able to read your question and help you with it. Also you should show us what you did try and any errors you encountered.

As the question currently reads I can only tell you to either take a look at the [Swagger API documentation](https://demo.azuracast.com/static/api/index.html), read up on how to do AJAX requests with JavaScript or just use the player embed widget that you can find on a stations profile page.

**Comment by Vaalyn** [comment]
I'm closing this issue until further clarification is supplied.
