### ISSUE TITLE
Question: Why can't I use a subdomain name to connect my broadcasting software when using Cloudflare?

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#1695]
Hi Guys!

My subdomain is pointed to my Azuracast server IP and hosted in Cloudflare.

But I can only connect BUTT software (or ay broadcasting software) when using the IP address only. Using subdomain is not connecting…

Is this the way it's set up?

Although when DNS is not via Cloudflare. Example directly in Godaddy or IONOS, subdomain connection is working...

Thanks!

**Comment by SlvrEagle23** [comment]
@ErnestPH This is a property of how Cloudflare provides its reverse proxying service. Incoming connections aren't proxied directly through to your server but rather routed through their edge servers, which then cache the response if necessary. Their edge servers are configured to only operate on ports 80 and 443 and to not allow incoming connections on other ports.

This is specifically why we set up the "web proxy" that generates the `/radio/8xxx/radio.mp3` URLs, specifically to handle this. We also use the same proxy with the Web DJ, since it uses Websockets and can thus be used with Cloudflare, but there's no way for us to proxy the connection type required for a DJ connecting directly with broadcasting software. They'll always have to use either direct IP or a non-Cloudflare-protected subdomain.

**Comment by ErnestPH** [comment]
Thank you for the reply! I hope others can read this too. So they will know.

**Comment by CodeSteele** [comment]
Another solution: put your public-facing site on cloudflare with cloudflare reverse proxy enabled.

Add a 2nd domain that does *not* use CloudFlare's reverse proxy, connect to BUTT via that.
