### ISSUE TITLE
Publish to "Yellow Pages" Directories

### ISSUE THREAD

**Issue by bayubad** [AzuraCast/AzuraCast#1713]
I am trying to publish my station to internet-radio.com directory and I enabled the option on Mount Point settings and followed the publisher instructions to add the following code to icecast.xml file
`
    <directory>
        <yp-url-timeout>15</yp-url-timeout>
        <yp-url>http://icecast-yp.internet-radio.com</yp-url>
    </directory>

`
but still my icecast server is not sending anything to radio-internet.

**Comment by SC2Mitch** [comment]
For me to help, I need logs... which you lack, can you provide some logs from IceCast? What does it say exactly?

**Comment by LordHelmchen666** [comment]
You must add in your Profile Custom Configuration for Icecast
`<directory>
    <yp-url-timeout>15</yp-url-timeout>
    <yp-url>http://dir.xiph.org/cgi-bin/yp-cgi</yp-url>
</directory>`

And activate "Publish on Yellow Pages" in your mountpoint settings

Look here http://dir.xiph.org/search?search=eisradio my station is Eisradio.

**Comment by mbncr** [comment]
Hi. Same problem here.
Apparently, something changed since this issue was closed, and the proposed code is not formatted properly for Liquidsoap anymore. After adding ...
`<directory> <yp-url-timeout>15</yp-url-timeout> <yp-url>http://dir.xiph.org/cgi-bin/yp-cgi</yp-url> </directory>`
into the Advanced Configuration, rebooting the station, Liquidsoap doesn't restart. On the liquidsoap log, you can read : 

>`At line 159, char 4:
Error 3: Syntax error!



The solution would be to rewrite this in compliance with Liquidsoap language. No clue on how to proceed, but I'll look into it.

**Comment by SlvrEagle23** [comment]
@mbncr That code should not be going into the Liquidsoap configuration editor, it should be going into the custom configuration for the mount point itself, under the `Mount Points` management page. It is indeed not valid Liquidsoap and is instead Icecast XML configuration that we append to the inside of our generated Icecast config.
