### ISSUE TITLE
Daily and Scheduled Playlists

### ISSUE THREAD

**Issue by anyall** [AzuraCast/AzuraCast#172]
Hello,

I'm using Daily or Scheduled mode for a playlist (podcast 01) but it doesn't work.

Liquipsoap config is :
# Fallback Playlists
playlist_hits_01 = playlist(reload_mode="watch","/var/azuracast/stations/radio_1/playlists/playlist_hits_01.m3u")
playlist_default = playlist(reload_mode="watch","/var/azuracast/stations/radio_1/playlists/playlist_default.m3u")
playlist_podcast_01 = playlist(reload_mode="watch","/var/azuracast/stations/radio_1/playlists/playlist_podcast_01.m3u")

playlists = random(weights=[5, 3,], [playlist_hits_01, playlist_default]);
dynamic = request.dynamic(id="azuracast_next_song", azuracast_next_song)
dynamic = cue_cut(id="azuracast_next_song_cued", dynamic)
radio = fallback(track_sensitive = false, [dynamic, playlists, blank(duration=2.)])

Playlists is random for the first two but not add daily or scheduled playlist playlist_podcast_01.

Did I miss something ?

**Comment by linksilver** [comment]
same issue

**Comment by anyall** [comment]
Hello,

It's now OK :
- I installed NTP on the server
- In the menu My account, Customization, I configured the good GMT timezone

But Azuracast seems to take his time to make the change...

**Comment by SlvrEagle23** [comment]
The only playlists written directly to LiquidSoap are the standard playlists, because these are intended as "fallbacks" in the event that the normal scheduling doesn't work for some reason.

In normal use, LiquidSoap pings AzuraCast itself for the next song, and AzuraCast checks for currently scheduled playlists, "once per x songs" playlists, etc. to determine the next song. You won't see this written into the configuration file, as it happens dynamically each time the next song is queued up.

All scheduled playlist times are relative to the server's timezone, which is typically (and generally should be) UTC/GMT.

I have some work planned to make the time zone conversion more intuitive, in particular to use your user-specified time zone and to convert, behind the scenes, to GMT, so there is less confusion.
