### ISSUE TITLE
Deployment and sizing

### ISSUE THREAD

**Issue by bayubad** [AzuraCast/AzuraCast#1724]
Please suggest a deployment strategy (distributed), hardware sizing (servers hardware config) and network architecture for a radio station with 100K listeners per day.

**Comment by SC2Mitch** [comment]
For that kind of power, you considered going with Amazon Web Services? Fairly sure that's scale-able.

**Comment by bayubad** [comment]
I am planning to use bare metal servers (not cloud) so I need hardware configuration (CPU, RAM) for a big deployment.
Also, the platform sizing. For example, does a single Icecast server on a single server can handle 100K listeners per day? What happens when the server goes down?
How can I build a HA for Icecast and AzuraCast platform?

**Comment by VinylVault** [comment]
@bayubad  100k listeners would probably need 300+ servers due to the bandwidth required for each listener stream.  

I can't see a way that a single server can provide the service you need.

If I was doing it, I would scatter the servers geographically and use some geo-location & load balancing service to point at the relevant server.

As for the server config, I'd have one Main/Master server, unlisted, and only used for relay connectors and DJ connections. Each relay would only connect to the Main/Master server and they would allow listener connections obviously.

Unfortunately, there are a handful major drawbacks to this ...

1. Cost, its going to be crazy expensive
2. Complexity, this would be one of the most complex setups I've ever seen, only huge organisations like BBC, NPR etc have such setups
3. You couldn't I don't believe reliably use a service like TuneIn Radio to pass feed the masses, unless you could somehow get geo.station.site/stream.mp3 to work correctly.
