### ISSUE TITLE
Azuracast rebranding

### ISSUE THREAD

**Issue by Bouzec** [AzuraCast/AzuraCast#1733]
Hi

How can I rebrand the Azuracast in header and footer as marked in below images?

![ac1](https://user-images.githubusercontent.com/52761586/61003286-ccddc600-a378-11e9-9a30-32976312e93c.jpg)

![ac2](https://user-images.githubusercontent.com/52761586/61003300-d7985b00-a378-11e9-92f7-ae2bd68d3cff.jpg)

**Comment by SlvrEagle23** [comment]
@Bouzec AzuraCast is given out to the public for free, built by volunteers like me who depend on the support of the public to afford rent and groceries, and while we have no record of you having donated to the project, one of the things you want to remove in your white-labeled version is the subtle, small _link to donate to us_ in the footer?

Questions like this really stress me out after years of having worked tirelessly to put this software together.

In any case, due to the volume of requests we've received from people about this type of thing, we _already do_ support custom branding across the whole application, using both custom CSS and custom JavaScript. You can modify either from the system Administration page, then "Custom Branding". There's a rich CSS/JS editor built into the page that color-codes everything and formats it nicely for you.

**Comment by Bouzec** [comment]
Ok.
Can I change the Azuracast name in the header to the radio station name? (top left)

**Comment by SlvrEagle23** [comment]
@Bouzec You can do that with custom JavaScript or CSS that modifies that element.

**Comment by Bouzec** [comment]
Could you help me with the code?
