### ISSUE TITLE
Live broadcast

### ISSUE THREAD

**Issue by ismaelazanza** [AzuraCast/AzuraCast#1736]
Excuse the question, I created a radio station using Icecast, but I want the station without autodj, only broadcast live. My question is. What are the data to transmit only live ?. Because when disabling the Autodj at the time of creating the radio I do not share the data to place in the program or encoder

**Comment by afonsosantos** [comment]
Hey @ismaelazanza 

You need to enable AutoDj to be able to live broadcast. Liquidsoap manages live broadcast.

**Comment by Vaalyn** [comment]
It is possible to live stream without the Liquidsoap autodj running but you will not be able to make use of the DJ Accounts feature without it.

When Liquidsoap is not running you are able to connect to Icecast directly with the source connection details shown on the station profile page under `Broadcasting-Service`.

We don't recommend to do this if you have multiple DJs that need to connect to the stream as all of them would then share the same connection details and when you have to change the password because for example one of the DJs shouldn't be able to connect anymore all of them would have to update that in their DJ software.
