### ISSUE TITLE
API: Search media files

### ISSUE THREAD

**Issue by oussamatn** [AzuraCast/AzuraCast#1752]
Hi,

I would like to send a search request to the API and get medias list as a response . 
I tried  : `api/station/1/requests?searchPhrase=artist` but the problem is that I can't find the song id so I can update its information later.
I'm trying to automate some tasks, I hope it will be done asap and I'll share it with the Azuracast Community.

Best,

**Comment by Vaalyn** [comment]
This is what I get as a return value from the API when I search for something via the API:
```
{  
    "request_id":"7ede9b383029f0a66af6400d",
    "request_url":"\/api\/station\/1\/request\/7ede9b383029f0a66af6400d",
    "song_id":"c7903e7e5b1eedef6457d270d4a65600",
    "song_text":"&I - Dive (ft. Giggly Maria)",
    "song_artist":"&I",
    "song_title":"Dive (ft. Giggly Maria)",
    "song_album":"",
    "song_lyrics":"",
    "song_art":"https:\/\/radio.bronyradiogermany.com\/api\/station\/1\/art\/7ede9b383029f0a66af6400d.jpg"
}
```

The `song_id` field should be the ID that you are looking for.

**Comment by oussamatn** [comment]
I got the same response, but the `song_id` it's not the same that we can use to update track informations with a `PUT ` request to `/station/{station_id}/file/{id}`.
The `song_id `look like a hash key but the `{id}` is an integer.

What i want to do with the script I m writing is to look for a song then add it to a specific playlist by pushing the playlist ID.

**Comment by adwinter** [comment]
Just throwing it out there... but I'm using a "traditional" install, and I've automated tasks like this by writing directly to the database. I didn't have much luck with some of the API functionality either, so I "talk" directly to the database to move songs from one playlist to another, etc...  I can provide you with more details on this method if you are interested...

If you are using the docker setup, I know connecting to the database is more involved and you may not want to go that route. Totally understand that as well.

Anyway, just offering up a possible alternative solution. :)
Have a great day.

**Comment by oussamatn** [comment]
Hey @adwinter,

Thank you for you response.
Yes, I'm down even if I have the docker installation. I'll try to work my way out.

Can you explain me how it works ?


Best,

**Comment by adwinter** [comment]
The database installation has all of the data for your playlists. I'm assuming you have some SQL knowledge, because connecting to the SQL database in Docker can be tricky. And I'm assuming you are familiar with how to put together mysql queries in your programming language of choice.

First you need to determine the `playlist_id` for all the playlists you want to move data to and from. You can get this information from `station_playlists' table.

You also need the `media_id` of the song you want to move. you can get this from the `station_media` table.

Playlist entries are stored in `station_playlist_media` and simply stores the `playlist_id`, `media_id`, `weight` and `last_played`.  (note it uses `media_id` of the song NOT THE "song id")

So all you need to do to move media to a playlist using a script is store an entry in `station_playlist_media` with the `playlist_id`  & `media_id`... for the `weight` I just store the next number in the series, and last played you can leave blank.

In my case I'm moving from one to the other, so I **DELETE** the entry for the current playlist, and then **INSERT** a new entry for the new playlist.

That's the MySQL info you need anyway.   I wrote my scripts in **PHP 7**. I also use scripts to view the songs in a current playlist, and their play order, an ability to re-shuffle a playlist, and insert, move or delete tracks from playlists. I do all this using MySQL commands without the API.

(FYI - I DO use the API for status type requests.. song history, current playing song, and I send song requests using the API interface)

**A FINAL NOTE:**  If you are running multiple stations, you'll need to use `station_id` for the `station_media` table to get the proper `media_id`. Playlist ID's are unique no matter what the station, so you don't need to differentiate what station your editing for the playlist tables.

Hope this is helpful.. It took me a while to figure out the database scheme, but it is quite straight-forward when diving into it. :)

**Comment by oussamatn** [comment]
Hey @adwinter, 
Thank you so much for your explanation. 
I had also a look at you github repository, and nice work ! 

Unfortunately, I'm facing a new problem. I can't connect to MariaDB from outsite the docker container.
Which host address you use to establish the connection ? 

Best,

**Comment by ErnestPH** [comment]
> Hey @adwinter,
> Thank you so much for your explanation.
> I had also a look at you github repository, and nice work !
> 
> Unfortunately, I'm facing a new problem. I can't connect to MariaDB from outsite the docker container.
> Which host address you use to establish the connection ?
> 
> Best,

Hey @oussamatn it was clearly stated by him that docker installation will be having problems… You must use the Ansible installation to make it possible. Your installation is not the same as his...

**Comment by oussamatn** [comment]
Hey @ErnestPH ,
Yes, we don't have the same installation. I have the docker installation (recommended).

For me it should works, because Azura_web container is connected to the same database. So, the connection is possible from container to another container. But, I don't know why i can't access to it from the host machine .

Best,

**Comment by Vaalyn** [comment]
You guys really shouldn't directly access the DB to change things around.

AzuraCast is still beta software so it's only natural that some things that are not used by that many people yet are still rough in some parts or lack data / functionality. That's why we'd love if you'd use the API we offer and help us to improve it when you encounter issues with it. That way everyone who wants to automate things via the API can profit from your help.

When you write scripts to directly change things in the DB you will risk that your scripts brake as soon as there is a DB update that changes something there that the script is not prepared for. It can also happen that an action needs to trigger additional things in the background which might not be recognized by the system when you directly manipulate the DB.

We also don't offer support for your scripts if you are not using the API to manipulate AzuraCast from other applications.

We offer a [PHP API client](https://github.com/AzuraCast/php-api-client) for AzuraCast that you can install via [Packagist](https://packagist.org/packages/azuracast/php-api-client) (currently with `:dev-master` as version requirement). This library still lacks some functionality but it's being worked on to bring it to feature parity with the API. Currently it is not possible to use the `searchPhrase` parameter with the library but adding that should be quite easy.

Regarding the original issue about getting the `{id}` for the `PUT` call to `/station/{station_id}/file/{id}` the ID there is not the Song ID but the StationMedia ID which you can get from calling `GET` `/station/{station_id}/files`. This `GET` endpoint currently does not implement searching for specific files though.

We'd really appreciate it if you'd help us to improve those things.

> Yes, we don't have the same installation. I have the docker installation (recommended).

> For me it should works, because Azura_web container is connected to the same database. So, the connection is possible from container to another container. But, I don't know why i can't access to it from the host machine .

@oussamatn  That's the way that Docker works. It isolates the containers as much as possible from your host machine. The containers communicate inside a network created by Docker so only stuff inside the network can reach other things inside there. It is possible to expose containers to the outside which is how the web and stations container get their connections to your listeners but opening up the DB to the outside is a security risk.

> it was clearly stated by him that docker installation will be having problems… You must use the Ansible installation to make it possible. Your installation is not the same as his… From what I understand :)

@ErnestPH it is technically possible to do with Docker but doing it in a secure way is something different. By default all Docker installations use the same password from the `azuracast.env` which is not a problem when the DB is only accessible inside the Docker network.

**Comment by oussamatn** [comment]
@Vaalyn ,
Apperciate you message.

> You guys really shouldn't directly access the DB to change things around.
That's why I first asked if there's any way to get it done without any risky modification. It will be a pleasure for me sharing my code if I can find a solution.

I recently found a way to access the DB from the host machine for testing stuffs. But I would like to know how to add new API endpoint that can search station media files. It's very similar to the request send by the frontend when we search music files 
`POST ` `/station/1/files/list`

Best,
