### ISSUE TITLE
Next Song

### ISSUE THREAD

**Issue by adwinter** [AzuraCast/AzuraCast#1755]
Hey Team:

I've been following several post which mentions "Next Song" not being available in the API, which I know first hand about.. My question though is this... Is there another mechanism that I could find out what the next queued song is? This became an issue the other day because a request was sent for an Artist, and unknown to my script, the song that was queued next was from the same artist. I try and separate playing the same artist by about 90-120 minutes, and in fact it is part of my SOCAN license to do this...

I used to pull the "next song" from the API and add it to my ongoing list of artists unavailable for request because its within the 120 minute window.. I understand that it was removed for other more pressing infrastructure changes, and I'm not trying to push for adding it back to the API.. but is there a way I can poll the database or liquidsoap itself to get the required info?

Any ideas? Honestly the amount of time this would happen is minimal, so I'm not super worried about it -- it would just be a 'nice to have' at this point.

Thanks for the amazing support.
Talk Soon.

Andrew

**Comment by SlvrEagle23** [comment]
@adwinter This has been a big concern of mine since we made the infrastructural changes that led to us not having the "Next Song" data. The primary reason has been that when we first asked the Liquidsoap team about this, their response was that LS internally had no way of managing an internal "queue" that was deeper than one song, thus allowing you to view the next song and manipulate the queue overall.

I wrote out a message to the LS team in their Slack asking for full clarification on this, because losing "Next Song" was kind of a big deal for us, and if there's no way LS can replicate this functionality I'd rather revert to the way we did it before. I'll keep you updated.

**Comment by adwinter** [comment]
@SlvrEagle23 thanks for the update. I figured the issue was complex. I know I had brief experience with LS before and I really struggled making sense of some of it. 

Good luck with the effort here and glad to hear "next song" is still on the radar.

A

**Comment by SlvrEagle23** [comment]
@adwinter Next Song is back.

It was bugging me a lot to have it gone too, and we had a number of requests to bring it back, so I talked with the Liquidsoap team, who confirmed with me that their software doesn't currently have anything that can handle what we're needing in that regard (and there's too little time before the next release date to get it in), so I worked today to reimplement our existing AutoDJ, but with the new station-wide time zones and other improvements that should help a lot with its reliability.

**Comment by adwinter** [comment]
@SlvrEagle23 Great News!!! Thanks a lot for this.
