### ISSUE TITLE
Just an Idea for a new side project

### ISSUE THREAD

**Issue by andrewfer000** [AzuraCast/AzuraCast#1764]
AzuraCast is an amazing project, It made internet radio accessible to everyone by making complex tools such as Icecast and Liquidsoap easy to use with a beautiful responsive interface and I know Silver Eagle and other contributors a working hard on the new features on the the features page (looking forward to some of those) Like I said before AzuraCast takes hard-ish to use programs and makes them easy and intuitive for everyone and puts it all into a nice and sweet docker container. I don't know if this would be an interest to the developers but how about a AzuraCast for videos and live streams? The Apache licensed Red5 media server seems very powerful yet complex for most users so I was hoping that you can take a look and see if you would be interested in new project. 

Thank You Silver Eagle and other contributors for your contributions to the Free and Open Source Software World and I hope you continue to make software that makes the internet a better & more fair place for all content creators and consumers.

**Comment by SlvrEagle23** [comment]
@andrewfer000 We've had a number of requests to build an "AzuraCast for Video", but there are a few big obstacles to that:

 - Transcoding video requires _far_ more powerful hardware than audio transcoding, which can happen on just about the cheapest VPS host you can find. This would not only mean a lot of people trying to run it on computers that can't run it, but it would mean we have to devote some money ourselves into hardware capable of developing and testing for it.

 - We couldn't use our existing toolchain for any almost any aspect of video delivery. While Liquidsoap is capable of shuffling video playlists and, as of its latest version, outputting HLS video streams, that's still just one component that transfers over, with much of the functionality not making it.

 - PHP itself isn't very well-suited to the task of parsing through large files for the purpose of generating thumbnails, pulling metadata, etc. The only reason we can get away with that performance penalty for AzuraCast is because audio files are, on average, just a few megabytes. For any sort of AzuraCast video service, we'd depend entirely on "piping out" to a standalone binary for that work, which would be more error prone.

I don't disagree that it would be really neat to see such a thing, but as it is we're already working very hard just to keep our existing project running smoothly, adding new features to it and trying to balance working on AzuraCast with the very real stresses of everyday life (namely the fact that AzuraCast isn't a revenue source, so I don't actually _have_ a revenue source).
