### ISSUE TITLE
avoid multiple plays by same artist.

### ISSUE THREAD

**Issue by darkjedeye** [AzuraCast/AzuraCast#181]
Hi, 
is there any provision to avoid too many songs being played by the same artist, like a time delay or something?

I am running this server for a community radio that is used to showcase national talent... so having the same artist play two songs in a row, may construe favoritism.

**Comment by j0llyc** [comment]
There are also licensing requirements for artist separation, and from memory, each licensing body requires different time-frames.

However, it is a tricky area, as there is the separation of songs in the same album, anthology, etc to consider, but it would be a wonderful feature to be able to control that through the web panel.

In terms of programming, I am somewhat of a noob, but on the surface, it seems like it may be similar to issue [#42](https://github.com/AzuraCast/AzuraCast/issues/42). Is it possible to implement based on that solution?

By the way, thank you for such an awesome web broadcast solution. I used Airtime years ago, only getting back into the idea of hosting an internet radio station again, hence me testing out AzuraCast.

Take care.

**Comment by JDBlackman** [comment]
Just wondering if this has any updates, I am experiencing lots of same artist songs played literally next to each other.  Its not great for licensing reasons and also listening experience.

**Comment by SlvrEagle23** [comment]
@JDBlackman There has been no new development in changing how the AutoDJ handles shuffling. While it's been explained in a few other threads, it appears I didn't type it out in this one:

Because stations have the option of using the AzuraCast AutoDJ or having Liquidsoap manage its own shuffling ("Manual AutoDJ" mode), we want those two methods of shuffling to be as similar to one another as possible. If their shuffling behavior is significantly different, people may not realize this and may enable Manual AutoDJ mode, then find that it doesn't meet their expectations (or worse yet, their licensing requirements). Further complicating the issue is the fact that almost nobody who submits issues via our GitHub indicates whether they have this setting turned on or off, which makes it even harder to diagnose reported issues.

I also find it extremely hard to find _any_ reference material on an optimal way of accomplishing shuffling such that duplicate artist or album plays are reduced. I've looked several times over the years, and basically all the systems I could find that don't just blindly shuffle playlists are proprietary or entirely undocumented.
