### ISSUE TITLE
Help with CSS or 

### ISSUE THREAD

**Issue by mele-uk** [AzuraCast/AzuraCast#1815]
Hi,

Can anyone help me with Custom CSS for Internal Pages for changing Azuracast to my station's name on the upper left corner of Dashboard?

**Comment by afonsosantos** [comment]
You can change the text nexto to the AzuraCast text in `Administration `-> `Custom Branding`

**Comment by mele-uk** [comment]
I mean this:
![header](https://user-images.githubusercontent.com/53567566/62416513-6aaf7280-b651-11e9-87bf-9a0e8ec489da.jpg)

I think I need to code in CSS or JS!

**Comment by afonsosantos** [comment]
Why would you want to remove the AzuraCast logo? I mean, it's free software, you should give the AzuraCast's team some credit.
I can't help you with this subject, as I never tried to hide/change that text.

**Comment by mele-uk** [comment]
I think as long as I keep the Azuracast footer, it's fine.

**Comment by SlvrEagle23** [comment]
@mele-uk Well, that's for us to say, isn't it? :)

You can of course customize AzuraCast however you like via the Custom CSS branding, but we do take particular issue with folks who hit up our GitHub and other channels to ask us for instructions on _how_ to remove our own branding. You're basically asking us to take up more of our time so you can give us less credit for our software. This is especially unkind to us if you're not donating or otherwise supporting us yourself.

Anyway, the short answer is, to hide the logo and replace it with your own text:

```css
header.navbar .navbar-brand {
    visibility: hidden;
}
```

To replace it with your own text, you can use custom JS to this effect:

```javascript
$(function() {
    $('header.navbar .navbar-brand').text('new name');
});
```

**Comment by mele-uk** [comment]
Thanks for you time :)
The following code does not replace Azuracast when inserted into Custom CSS for Internal Pages:

$(function() {
    $('header.navbar .navbar-brand').text('new name');
});

**Comment by SlvrEagle23** [comment]
@mele-uk As I said, that's custom JS (JavaScript), not CSS.

**Comment by mele-uk** [comment]
Where to insert in Custom Branding page?

**Comment by SlvrEagle23** [comment]
@mele-uk There is a "Custom JS" section directly below "Custom CSS" on the Custom Branding page.

**Comment by mele-uk** [comment]
I see only the below:

Custom CSS for Public Pages
Custom JS for Public Pages
Custom CSS for Internal Pages

**Comment by SlvrEagle23** [comment]
@mele-uk Ah I remember now, we don't allow custom JS on the internal pages as that represents a bit more of a security risk than we were willing to accept.

Your best bet is to hide the entire banner with CSS, then show the smaller "product name", which you can customize, and modify the font size for that accordingly. Or just hide the entire thing and use a custom background image.

I am not going to provide instructions on how to do this.

**Comment by ErnestPH** [comment]
@mele-uk this is quite an insult to the developer of Azuracast to be honest :) You can always ask someone else (not here).

**Comment by mele-uk** [comment]
Honestly I respect his great job!
