### ISSUE TITLE
0 unique listeners while streaming to remote relays

### ISSUE THREAD

**Issue by yarik2720** [AzuraCast/AzuraCast#1841]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu Server 16.04

**Describe the bug**
On station profile I see number of listeners, but number of unique is 0

**Screenshots**
![chrome_2019-08-11_23-47-25](https://user-images.githubusercontent.com/1839978/62839440-6eb34400-bc92-11e9-922d-391e36a55a3c.png)

**Comment by SlvrEagle23** [comment]
@yarik2720 What type of remote relays are you using? It's possible that they're not properly reporting back unique listener counts.

**Comment by yarik2720** [comment]
Icecast 2.4-kh8

**Comment by SlvrEagle23** [comment]
@yarik2720 Ah, that makes sense then. Icecast can only deliver unique listener counts if we have direct access to the administration panel for the instance (like we do with our own AzuraCast mount points), but we don't currently have a way to provide that credential for remote relays, so that they can get a more accurate unique listener count. This is something we're wanting to add in the near future to help improve accuracy of the remote relays.
