### ISSUE TITLE
Cross fading results in silence between track, in any mode

### ISSUE THREAD

**Issue by parksquare** [AzuraCast/AzuraCast#1869]
**Using Docker installation method**

Yes
**Host Operating System**

Debian 10
**Describe the bug**

Regardless of which cross fade mode is selected, hear silence between tracks quite regularly. I would at least expect the smart mode to do a better job of this.
**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@parksquare Our GitHub error template isn't just a suggestion that's meant to be ignored. Please follow it, because we are a team of basically two people dealing with hundreds of incoming issues, along with bug fixes, new features, and other development work, all for donations that basically amount to half of minimum wage.
