### ISSUE TITLE
Stream client other than butt? (clipping issue)

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#1871]
We use butt for live sessions and a problem we have is that it doesn't have a built-in limiter and it clips very harsh in the "red zone". The effect is that the listeners will hear noise. Otherwise it's a very nice tool, simple and reliable. Is there any other option for butt that we can try? 

The reason we think it could be solved via SW is because the same laptop (the one we use for streaming) can record the same signal without clipping (we use Quicktime, it's a Mac machine).  We could use HW I'm sure but since we see it works well with Quicktime we try to look around for simpler (and cheaper) options. Any help is appreciated.

PS: we can't thank enough for Azura's (and butt's) creators for the good work. And there is no really a forum for it (except donations) so I will just randomly post it here :) Keep it up, you're great!

**Comment by gammaw** [comment]
Hmm, it seems that the latest version of butt (0.1.18) behaves differently than the previous version  we had installed (0.1.16). The new version seems to be much more robust against (too) strong signals, I hear practically no clipping. I checked the release notes of 0.1.18 and I see no trace of such improvements but who cares if it works :) 

Anyway, if you know of butt alternatives, let me know, I would be curious to try them out. Also, do you see any possibility to send cover arts from the streaming client to Azura? I know it sounds like a a very advanced feature but is anything like this planned?

**Comment by SlvrEagle23** [comment]
@gammaw Glad to hear it's improved in the latest BUTT version! We have guides on several pieces of streaming software [on our web site](https://www.azuracast.com/help/streaming_software.html), but none of them do exactly what BUTT does in the sense of just broadcasting anything on your computer.

As for the album art, unfortunately neither Liquidsoap nor Icecast lets us really stream album art through the metadata streams. The only way we're able to do it is because we have the album art associated with the media on our end, so we pull the song identifier and match it back up against our own database.
