### ISSUE TITLE
OS and AZ on separate drives

### ISSUE THREAD

**Issue by xifayib** [AzuraCast/AzuraCast#1877]
Planning to install Ubuntu on a SSD drive and Azuracast on a different 10K SAS drive.
How is it possible?

**Comment by xifayib** [comment]
Clarification:
I have two Hard Drivers on a machine.
Drive 1 (SSD): Ubuntu already Installed.
Drive 2 (SAS): Planning to install Azuracast on this drive.

How would it be possible to install Azuracast  (Docker version) on Drive 2?

**Comment by SlvrEagle23** [comment]
@xifayib I'd recommend using our standard Docker installation and installing AzuraCast into a location on your primary Ubuntu drive, then mounting your station data to the secondary SAS drive so that AzuraCast can use it as a data store. This will allow you to take advantage of the SSD performance for the AzuraCast core application code while giving you the flexibility to expand the storage space as needed.

We have a guide for doing this [in our help section](https://www.azuracast.com/help/faq_docker.html#mounting-a-directory-into-a-station) on our web site. Check it out and see if it is helpful for your purposes.

**Comment by fafafoya** [comment]
That's what I am looking for!
