### ISSUE TITLE
Music storage limit

### ISSUE THREAD

**Issue by AleAmla987** [AzuraCast/AzuraCast#188]
Is there any way to limit the amount of space each station has?

**Comment by shaundewberry** [comment]
Not sure if it will work for you, but I run each station's music off a different mountpoint under /var/www/azuracast/stations/stationname/music , which allows me to manage the space effectively.

**Comment by AleAmla987** [comment]
I understand, I meant limiting the capacity for each station ... eg Radio1 1GB storage, Radio2 1GB storage, do you understand?

**Comment by SlvrEagle23** [comment]
@AleAmla987 @shaundewberry You two are actually referring to the same idea, limiting the amount of total storage available to each station to use.

Since AzuraCast is (and wants to be) independent of the underlying operating system or host (including running inside Docker containers), it's difficult to implement a quota feature like this inside our software.

I think, for now at least, the suggestion @shaundewberry made is your best bet; set up each station's media directory (by default, `/var/azuracast/stations/{station_short_name}/media`) as its own mount point and set quota restrictions on those mount points. This is more advanced Linux work, but will provide an immediate solution.
