### ISSUE TITLE
Download the Stream content

### ISSUE THREAD

**Issue by fafafoya** [AzuraCast/AzuraCast#1886]
It's possible to download the streaming content by any Download Manager.
For example, I can download http://radio.station.com/radio/8000/radio.mp3 by FDM to my PC and listen later.
Due to Royalty issues, we can't allow the listeners to download the content.
Is it possible to prevent this?

**Comment by fafafoya** [comment]
I see many station remove file name (radio.mp3) and the streaming URL is like http://radio.station.com/radio/

**Comment by SlvrEagle23** [comment]
@fafafoya By design, internet radio _is_ a download streaming from your server directly to your listeners' computers. There is nothing we can do that would prevent them from being able to retain the downloaded stream for later use that wouldn't also prevent them from just listening to it as a normal user.

In the context of royalties, the concept of making audio available for download is often referring to "on-demand" downloads, where a user can select a specific song and download it to their computer, rather than the ability to capture an ongoing stream of audio which they have no direct control over. AzuraCast doesn't offer on-demand downloads of media to public listeners.

**Comment by fafafoya** [comment]
But most Radio streaming services, remove radio.mp3 file from the Streaming URL and make it hard for download managers to download the content.
For example, streaming URL should be  https://stream.radiostation.com/radio/8000/ instead of https://stream.radiostation.com/radio/8000/radio.mp3
Is it possible?

**Comment by SlvrEagle23** [comment]
@fafafoya That's just a matter of changing the mount point name to "/". I don't know what unintended consequences this will have with AzuraCast, but that's the answer to the question.

In the end, really that's only providing "security through obscurity" and not limiting in any way the ability of the end-user to capture the radio stream if they really wanted to.

**Comment by fafafoya** [comment]
I agree.
But I read on Radio.co that they have a Ripper Protection system. 
This is useful if you want to prevent listeners recording your stream which will ultimately waste precious bandwidth. We have added some known stream ripping applications to the list already.

Reference: https://help.radio.co/en/articles/899745-settings

**Comment by btoplak** [comment]
Even the FM radio can be recorded. We did it to audio cassettes decades ago... so the radio ripping is not a new issue, nor should that be a radio operator's responsibility. Not 30 years a go, not now.

You simply can't prevent anyone from ripping your stream, period. When the data comes to the client, the client side can do with the data as it pleases. Be it a regular software player which will just play the music to your speaker, or software intended to save the data instead of just playing it out. 
Removing the "filename" from your stream URL doesn't prevent anyone with a good tool or a better knowledge to simply save your stream to a file.

> But I read on Radio.co that they have a Ripper Protection system.
> Reference: https://help.radio.co/en/articles/899745-settings

What they most probably do is just trying to identify a ripping application by the "user agent" HTTP header. It simply can't be much more than that. You can either block by IP, or try to identify the "player", aka "client" soft on the other side and decide to send stream or not.
And if you're afraid of the really capable stream rippers which split the stream into individual song files, then you could turn off the song display in your stream.
