### ISSUE TITLE
Thoughts/questions regarding deployment procedure

### ISSUE THREAD

**Issue by It4lik** [AzuraCast/AzuraCast#1901]
Hi, 

First of all, thanks to all of you for this amazing tool. Azura is awesome, I was looking for such a tool for a while.

I got questions/thoughts about your deployment procedure : 
* why do you deliver an empty container (web container) and then clone your code inside it with a `docker-compose run` ? I mean, it's the opposite of the docker philosophy, I think it'd be better if the code was already present inside the container. It would be way more portable.
* I need to deploy AzuraCast in a swarm, but you don(t support it natively. I saw this thread https://github.com/AzuraCast/AzuraCast/issues/1202 in which you were kinda narrow-minded on this subject, could we know why ?
* I got to admit that it's a real pain to deal with your packaging at the moment, when trying to custom it a bit (I got a lot of errors regarding Database or Let's Encrypt when trying to use local volumes)

Anyway, do you got any new thoughts on docker-compose v3 ? Or at least swarm mode (same goes for k8s).

EDIT : same thing if I want to use an external Redis server, I need to hack your deployment

I understand (and I agree) what you said in https://github.com/AzuraCast/AzuraCast/issues/1202 (_"Not everyone who operates Docker and Docker Compose is running the latest versions of both. While it is advisable to do so, in some cases the packaged versions of either for a given OS/platform are not the latest version. Since, again, there's no technical benefit in us upgrading from 2.x to 3.7, this would exclude those users and cause their updates to fail."_) But that doesn't mean that you can deliver multiple deployment methods.
Keeping docker-compose 2.x, as you said is great for compatibility. But in my case, it's a total block to adopt your solution, I'm on the other side : I need a 3.x version. 

Yours,
it4.

**Comment by It4lik** [comment]
Also, same thing if I want to use an external redis server for example.

**Comment by SlvrEagle23** [comment]
@It4lik Our Docker infrastructure is the result of years of slowly refining things to work for the broadest set of either non-technical users or users with relatively uncomplicated setups, who benefit from taking advantage of the improved compartmentalization, easier updates and more predictable software stack setup that Docker offers.

**To answer your first question:**

We support both updating to release and "dev-master" rolling-release versions. If we built out different images for both, it would not only require a time-intensive rebuild of the web image on every single commit to the main repository, but it would require modifying the `docker-compose.yml` file to specify which branch you wanted to be on; our current update mechanism doesn't require that.

Even with our current mechanism, there's still a huge benefit to having the web container built on our end (besides nginx and the rest of the stack being loaded): we pre-warm the Composer cache so that regardless of which version you install, you're getting the latest version.

You do have a valid point about altering that setup to take advantage of Docker's own tagging system to track releases, as it would also lock web image changes to the corresponding codebase that goes along with that image.

I'll definitely look into it, especially now that we have GitHub Actions access and can do fancier stuff. You probably have a valid point from a "docker way" perspective; we even do it that way in our other deployments.

**For the second question:**

My original answer wasn't intended to be "closed-minded" with regard to support for Docker Compose 3, but rather to say there's a valid reason we don't support it right now and if we switched to it, it would break a bunch of things overnight for people updating from the previous version to this one, which until then has been a smooth transition.

The reason I haven't added support for Swarm is simply because, well, if I was going to go for that level of complexity I'd just spring directly for Kubernetes.

In my head, here's my predominant philosophy about that: if you're dealing with a broadcast infrastructure of the scale where a single well-provisioned VPS (and any number of relays, as supported by our AzuraRelay service) wouldn't be sufficient to handle it, then you're large enough to be sponsoring the development of this project financially. To date, no sponsor of our project has ever indicated that they wanted to see Kubernetes or other scaling of that sort. (I've been called, by other users, everything from greedy to arrogant for suggesting that there are some features that I think should be paid for by _somebody_, but it's hard to feel all that greedy when I'm as aggressively broke as I am. I donate a _ton_ of my time to this project as it is.)

**For the third question:**

I've done some work already to improve the support for custom environment variables to control the AzuraCast docker installation, including custom variables for external database connections, but it's definitely fair to say there is some room for improvement with regard to the "power user" experience, such as moving to an external Redis server or some other similar setup.

What problems are you running into with the LetsEncrypt setup? Our little utility scripts are really just wrappers around Certbot, which is itself installed in the web container, so you're free to manually run it inside the container if you need to. The reason we do the symlink dance with the main cert file is to avoid having to reconfigure nginx when the SSL certificate is set up.

**Comment by It4lik** [comment]
@SlvrEagle23 , thank you this detailed answer ! 

Indeed, I didn't think about the actual members of your user base. Your software being a webradio, you surely had (and have) to deal with many non-technical users. 
Your various choices are more understandable to me now. 

As you did, I will go in each point separately : 

**First question :**
I did see what you do with the build cache and this is quite smart indeed (by the way, the AWS sdk PHP lib you're using is not using the cache, looks weird to me : constantly re-downloading at each deployment).
Working with tags would allow to completely bypass the local build process and speed up even more the deployment process ; but I agree that this need a completely different process to update for example. And perhaps it won't suit deployments for non-technical users.

**Second : **
Makes sense too. 
We chose Swarm over Kubernetes because Kubernetes is a lot more complex that Swarm at the moment. 
Even if we got little experience with Kubernetes, we only got a small 3-nodes cluster for our personal use and don't want the overhead generated by a Kube stack. 
But we still want to benefit from cloud-like features when deploying applications, so Swarm was our way to go.
Purely subjective, but I think Kube is a bit overlooked when it comes to small infrastructures. Whereas a nicely configured Swarm will fit nicely. So I do not "bulk-agree" with what you said about Kube/Swarm, but that's another topic :)

I actually succeed to make Azuracast run in a Swarm with a bit of ugly settings and deployment process. I'll deep further to make something nice, straightforward and good-practices-compliant. I can share it with you if you want me to. 

**Third**
Yeah that would be awesome ! But I now understand that this is not in your main objectives. Such setups enable a team like us to repackage more easily the whole solution, and share it with the community. Since the present setup is more or less monolithic, we have to do separate each role/function/container ourselves and it's a bit empiric, since we don't know how you design the whole solution.

ps : Once more, thank you for your answer, and moreover, thank you for AzuraCast.
