### ISSUE TITLE
Can't operate with files if there is symbol '|' in filename

### ISSUE THREAD

**Issue by yarik2720** [AzuraCast/AzuraCast#1932]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 16.04

**Describe the bug**
Can't add to playlist or delete file if filename has symbol `|`

**To Reproduce**
1. Upload file with filename that contains symbol `|`
2. Try to add to playlist or delete it
3. Nothing happens

**Comment by Vaalyn** [comment]
I can't reproduce the issue. Are there any errors in your browsers JavaScript console or the Network console? Please also check the AzuraCast Application Log.

Can you also provide the exact filename that you are using?

**Comment by yarik2720** [comment]
full filename: `unknown-Monstercat: Call of the Wild Ep. 164 | Featuring Kayzo, Gammer & KUURO-320kbps.mp3`
File were imported to folder with os operation of file moving from old folder.
There is also no errors in log or any activity while I adding track to playlist. On website I only see notification `Playlists updated for selected files:
monstercat podcast/unknown-Monstercat: Call of the Wild Ep. 164 | Featuring Kayzo, Gammer & KUURO-320kbps.mp3`

**Comment by Vaalyn** [comment]
I have replicated the error in my dev installation and found out where this problem is coming from.

The batch operation for adding files to a playlist (is also the case for other batch operations), has this line of code in it:
```
// Convert from pipe-separated files parameter into actual paths.
$files_raw = explode('|', $_POST['files']);
```

When selecting multiple files for a batch operation the files will be send looking like this:
```
test_1.mp3|test_2.mp3
```

So the batch operations will interpret the filename for file with a `|` as being 2 separate files.
