### ISSUE TITLE
Next song stuck

### ISSUE THREAD

**Issue by stemvantwente** [AzuraCast/AzuraCast#1940]
Installation method
"Traditional" installation method" (v0.9.6.2,)

Host OS (for Docker installations)
Ubuntu 1804 (VPS)

Describe the bug:
Next song is stuck

Doesnt update the next song anymore, songname After all - if you need me stays there all the time. but the playlists are running with no problem I hear my songs in random order.

What I have tryed:
php /var/azuracast/www/util/cli.php orm:generate-proxies
php /var/azuracast/www/util/cli.php cache:clear
php /var/azuracast/www/util/cli.php sync:run

I added some screenshots.
![nextsongstuck](https://user-images.githubusercontent.com/44572433/64391852-96f05180-d04a-11e9-8f32-d961b658538e.jpg)

Also cannot deleted the song in queue, when I click delete it gives a popup, I click again delete popup goes away but the song name stays there.
![nextsongstuck2](https://user-images.githubusercontent.com/44572433/64391857-99eb4200-d04a-11e9-8a57-af9a72d33eef.jpg)

Also when I run on AzuraCasts AutoDJ request from listeners arent playing.

When I say go advanced dj mode the Liquidsoap version, then the requested songs are playing again.

**Comment by mariustgv2004** [comment]
I have the same problem. Next song is stucked, not playing..

**Comment by fafamonge** [comment]
Same problem here, how could I clear or empty the queue? Is it possible delete the queue without confirmation and with batch method instead one by one? I've notice this may cloud be caused because I upload some music files via SFTP but using the web interface appears like NOT PROCESSED and reprocess button was no able in my version so I'd selected and clicked on ADD TO QUEUE and then the files get processed status but stuck the queue and next song or skip song functionality.

**Comment by gabek** [comment]
I'm running into this. Has anybody discovered a fix for it?
