### ISSUE TITLE
Cant see metadata for external player

### ISSUE THREAD

**Issue by machetedj** [AzuraCast/AzuraCast#1941]
Since some updates, i cant see see anymore on some external players the song title, (the metadata) because now the links are no more  this http://[domain]:[port]/mountpoint. Any advise?

**Comment by VinylVault** [comment]
hi Team, 

This issue is affecting streams using VLC and other web players (not website related) also, is there any fix possible? maybe via an advanced config, liquidsoap variable (ive seen the solution to remove metadata, so wonder if there is the opposite functionality)

new AC user, trying to configure correctly before launching a new station.  the software looks great though

**Comment by SlvrEagle23** [comment]
@VinylVault see issue #1598 for more information on the causes of this issue.
