### ISSUE TITLE
No Icecast source details wihout AutoDJ/Liquid Soap

### ISSUE THREAD

**Issue by ronanramos** [AzuraCast/AzuraCast#1963]
**Using Docker installation method**

Yes
**Host Operating System**

Ubuntu 19.04 x64 
**Describe the bug**

New station without auto DJ activated cant see the source details to connect encoder on icecast
**To Reproduce**

I created a new station to test, without auto DJ option (no liquidsoap)
after i can see the icecast running perfectly on port 8040 trough proxy (https)

but i can found the port to connect my remote encoder.

And the stream url is always as, on dashboard
https://127.0.0.1/radio/8040/radio.mp3?1568312045

If i want to broadcast my encoder as mp4/aac or other format ?

**Expected behavior**

i think we can create new stations without auto DJ with icecast option to use remote encoders, because theres the option to use or not auto DJ on creating new station.

The source info is on dj accounts page, but when no auto DJ is configured on new station account, i cant see the connection details for icecast.
**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device: Desktop 
 - OS: Windows 10, Windows 7
 - Browser: Mozilla, Chrome
 - Version: Last ones

**Additional context**

Thanks in advance!!!

**Comment by Vaalyn** [comment]
When using a station without an auto DJ you can only connect via the IceCast source user/password. The connection details for connecting directly to the IceCast server are shown on the stations Profile page in the card with the header `Broadcasting Service`.

The DJ accounts feature only works for stations with the auto DJ enabled because the auto DJ (LiquidSoap) is handling them / the authentication of them.
