### ISSUE TITLE
Shoutcast dosent work

### ISSUE THREAD

**Issue by LukasRappl** [AzuraCast/AzuraCast#1975]
Hey!

I had placed the sc_serv2_linux_x64-latest.tar.gz in the Panel but when i change my Station to ShoutCAST is the Stream offline.

**Comment by ogrenci01** [comment]
Hello @LukasRappl ;

You should consider the warnings here because ShoutCast is paid software.
![01](https://user-images.githubusercontent.com/24523085/65042207-0b879200-d961-11e9-907e-dca08a964647.jpg)

Can you download to it and test it?
Official Shoutcast: http://www.arkacadde.org/sc_serv2_linux_x64-latest.tar.gz

This will solve your problem. Enjoy!
