### ISSUE TITLE
 Restart a single station from the command line

### ISSUE THREAD

**Issue by cristianocarrozzi** [AzuraCast/AzuraCast#1976]
I found a solution for a situation, its not perfect but works. 
I need to know if is possible restart only one station from command line.

**Comment by iDJHost** [comment]
If you have cURL installed you could use the API

curl --header "X-API-Key: your_api_key" https://your.domain.tld/api/station/{station_id}/restart

replace "your_api_key" with your actual API Key & {station_id} with the stations id no brackets

**Comment by SlvrEagle23** [comment]
@cristianocarrozzi @iDJHost Since it seems like this is a particularly useful tool to have, I've added an extra parameter for the `azuracast:radio:restart` command...if you specify a station's numeric ID or shortcode as the extra argument (i.e. `azuracast:radio:restart my_station`) it'll restart just that station.

**Comment by cristianocarrozzi** [comment]
@SlvrEagle23 Thank you! Worked perfectly!
