### ISSUE TITLE
Direct connection to the port

### ISSUE THREAD

**Issue by KoneSV** [AzuraCast/AzuraCast#1986]
I want to make direct connection to port 8020 of shoutcast but it doesn't connect
only connect by streamers / DJ which is port 8025
What can I do to make it direct to 8020, since I don't need AutoDJ
sorry for my bad English

**Comment by ogrenci01** [comment]
Hello there;

"Do not use an AutoDJ service" should be selected on the AutoDJ tab on the station profile page. In the Mount Point section, "Enable AutoDJ" should not be selected. Finally set 8020 for the broadcast port on the station profile page. Let me know again if you experience problems. I use many radios without AutoDJ.

**Comment by KoneSV** [comment]
El problema que tengo es que mi cliente quiere puerto 8020 y 8022 en shoutcast pero solo funciona el 8020 (y tiene que enviar streaming al 8019) hay una manera que envie la señal al puerto shoutcast 8020?

**Comment by ogrenci01** [comment]
I hope I understood you correctly.

I want to make a suggestion for that. Add a station with port 8020. Add another station with port 8022. Route port 8022 to the station with port 8020. In this way, the broadcast will be the same for both stations. When your client broadcasts live with port 8020, port 8022 will listen to it.

Azuracast You can easily do this from the "REMOTE RELAY" tab. You can use this configuration for ShoutCast v2, which is a custom configuration.

streamrelayurl_1=http://youripadress:8020

**Comment by KoneSV** [comment]
They are not 2 ports of 2 different stations, but when creating port 8022 does not work, it is activated but in reality it is not active

**Comment by ogrenci01** [comment]
Hello;

Could you please tell us more about what you want to do? You should provide detailed information about your installation. AzuraCast team will find a solution.

**Comment by KoneSV** [comment]
Ok, I need to operate port 8020 for "Radio A" and port 8022 for "Radio B", but the problem is that I create port 8022 but it does not work, only 8020, although I believe 8024, 8026, 8028 do not work only with termination 20, 30, 40 ...

**Comment by ogrenci01** [comment]
Hi;

I am sorry and I did not understand you correctly. I hope I understood you correctly.

I assume you are using the Azuracast Docker installation. You must define the ports you want to use for Azuracast Docker installation. Please review the guide below.

https://www.azuracast.com/help/faq_docker.html#expand-the-docker-radio-station-port-range

Click on the link below to see the station ports that Azuracast Docker installation uses by default.

https://github.com/AzuraCast/AzuraCast/blob/df775c6108708abbb0d3d7a1174eff39368fd99c/docker-compose.sample.yml#L84-L231

**Comment by KoneSV** [comment]
I am not using Docker,

but in the same way as change there?

**Comment by ogrenci01** [comment]
Hello;

I'm using AzuraCast Ansible. I can use ports 8022, 8026, ..., 8044,8046. You should make sure that you configure the firewall correctly.

Please join the Azuracast Slack app. I'd like to help you.

**Comment by KoneSV** [comment]
I'll try the Ansible method, what happens

**Comment by ogrenci01** [comment]
Hello Everybody;

Error # 1848 is still unsolved. Your problem is the same as this problem.

I want to help you with an immediate solution.

1-) `sudo apt-get update -y`
2-) `sudo apt-get install -q -y git`
3-) `sudo mkdir -p /var/azuracast/www`
4-) `cd /var/azuracast/www`
5-) `sudo git clone https://github.com/AzuraCast/AzuraCast.git .`
6-) ``sudo chmod a+x install.sh`
7-) `sudo chmod a+x update.sh`
8-) Download an older version:
**https://github.com/azuracast/azuracast/archive/0.9.6.zip**
9-) Use FTP to upload this archive to the directory "/var/azuracast/www". Accept changes.
10-) After completing the installation, start and complete the installation.
`sudo ./install.sh`
11-) Download the latest version after completing the installation.
**https://codeload.github.com/AzuraCast/AzuraCast/zip/master**
12-) Upload this archive to FTP directory "/var/azuracast/www"
13-) After the installation is complete, start and complete the update.
`sudo ./update.sh`
14-) After the update is completed, Azuracast will be ready to use.

Enjoy!

**Comment by KoneSV** [comment]
Thanks friend, that helped me install the previous version and be able to activate nearby ports
