### ISSUE TITLE
id tag

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2012]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
Hi,
Is it possible to automatically associate the custom fields with the mp3 ID tag in similar as the Song Title, Song Artist,  in order to get the relevant info in the "now_paying" API?
Or alternativ get more info on "song" field. I saw somethig here:
https://github.com/AzuraCast/AzuraCast/blob/469a727e6457fa7a45865d255c295aa21488b32e/app/library/App/Sync/Media.php#L147 .

Thank you

**Comment by eranwo** [comment]
@Vaalyn Hi, is that something that can manage? its very important for royalties reports especially in "Song Playback Timeline" report.

**Comment by SlvrEagle23** [comment]
@eranwo Please do not post messages "following up" on your issue that directly mention developers. We are a small team and are often working on other things, so your patience is appreciated.

This is actually a request for a new feature, which should be submitted [on our FeatureUpvote site](https://features.azuracast.com/). I'm looking into the possibility of implementing it sooner rather than later, though, because it has been very frequently requested.

**Comment by SlvrEagle23** [comment]
This has now been added as of the latest update.
