### ISSUE TITLE
after update my azuracast, 404 error and ip server not redirect to login page.

### ISSUE THREAD

**Issue by kazwashere** [AzuraCast/AzuraCast#2013]
Installation Method: Traditional
Host OS : Ubuntu 16.04 LTS

Describe the issue in full detail, including screenshots if possible:

Hello. i would like to report something. so, after roughly 6 months since i upgrade my azuracast, i decide to instal latest update build aka update my azuracast server. 

everything seems fine, no error whatsoever. but when i go to my radio server ip addres public page, i got 404. notice something did not right i try just type my address and the result is ip address not directly go into azurecast login screen. but apache2 successfull instalation page. 

the last time i update i never encounter this problem. do i have to edit my apache file into default folder or what?

**Comment by SlvrEagle23** [comment]
@kazwashere We don't bundle Apache with AzuraCast. In fact, our updater will attempt to uninstall Apache, because it often conflicts with the web server we do use, nginx.

If you're seeing an Apache welcome page, it may be that Apache was somehow otherwise installed on the server. You may want to uninstall it using `sudo apt-get remove apache2` or something similar.

**Comment by kazwashere** [comment]
wow. that means i have to clean uninstall and remove my apache2 from my already running server. since i already forget (and forget to check list plus write how i install this thing again) i use apache as to redirect the index.hmtl file so i can properly login into azuracast. 

i am worrying if i proceed to uninstall and remove apache2 from the system the azuracast got conflict or any similiar issue. 

oh yes, somehow my IP Address still can be used to connect and run normally but cannot access home/index/login screen.

**Comment by SlvrEagle23** [comment]
@kazwashere I'm afraid I don't fully understand your response.

We didn't install Apache on your server; if you installed Apache in order to do something else on the same server, then it's likely that this caused the problem with nginx and prevented it from working normally.

We can't control how any given piece of software will interact with the software we use for AzuraCast. This is one of the huge reasons why we recommend using our Docker installation instead of the Ansible/Traditional one, so that our entire software stack is self-contained and has less risk of interacting with other software on the same server.

**Comment by kazwashere** [comment]
yep. bye the love of god, i try to re-update again and somehow my station work again. 

well. that is weird case me. i am sorry for this problem SlvrEagle23.  

since i instal properly with traditional one and not familiar with docking so i prefer use that. 

again i am sorry for this problem. 

also thank you for always developing this azuracast! love it.
