### ISSUE TITLE
Automatically Set from ID3v2

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2028]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
The new feature works like a charm ! 
it's great !
Does the "Song Playback Timeline" report will also update with the new data from ID3v2? now it contain very limit data and not pass the royalties regulation.

<img width="316" alt="vuS4Mkk" src="https://user-images.githubusercontent.com/2701228/65994759-c608b000-e49c-11e9-8e49-5dbe172f5f2e.PNG">

**Comment by eranwo** [comment]
Please consider adding this as the new version is great and i think it ( add the custom fields to the time line report) can be very useful for most and pro users

**Comment by eranwo** [comment]
@SlvrEagle23 Hi,
Just sending you a gentle reminder on this request.
Hope you can find a few minutes on this. Appreciate your time.

**Comment by SlvrEagle23** [comment]
@eranwo That's not how we do things on this project. We're volunteers working on the project at our own leisure, and when we have the time and energy to work on new features that make sense within our current objectives, we do so.

Since this is a request for a new feature that doesn't exist yet, you should submit it to our [FeatureUpvote page](https://features.azuracast.com/), where it can join the queue along with our other enhancement requests.
