### ISSUE TITLE
Profanity filter

### ISSUE THREAD

**Issue by darkjedeye** [AzuraCast/AzuraCast#204]
Is there anything that can be added to this system for realtime profanity filter? or do you know of anything that can be used with either Mixxx or SAM?

**Comment by SlvrEagle23** [comment]
@darkjedeye Are you referring to a profanity filter for the *audio* that's being played? If so, that's not only virtually impossible to implement without huge computing power, but it's not even something available to commercial radio stations, who instead opt for a multi-second delay where they can manually censor content where needed.

The issue with any kind of censoring software is always localization; i.e. what is "vulgar" in one language may be a normal word in another, and vice versa. Since AzuraCast supports multiple languages at once, it would be all but impossible for us to develop a foolproof profanity filter.
