### ISSUE TITLE
The song title is not displayed correctly for my local language.

### ISSUE THREAD

**Issue by kokoloman001** [AzuraCast/AzuraCast#2044]
The song title is not displayed correctly for my local language.

My language is Thai.

I use SAMCAST and BUTT for Broadcast.

![image](https://user-images.githubusercontent.com/29307350/66545022-f9fe6800-eb63-11e9-8c75-c5b00d303f69.png)

![image](https://user-images.githubusercontent.com/29307350/66545062-0f739200-eb64-11e9-80b1-bb271d16d67d.png)

And... I hope you will add Thai to the interface for Azuracast

Thank for support

**Comment by biguenique** [comment]
AzuraCast is Unicode -- which means "supports all known languages, even Klingon".

This looks to me like some 8-bit extended ASCII charset wrongly interpreted as ISO-8859-1. I guess the OS you are using is configured in Thaï, right?

I don't know them, but is there a place in SAMCAST and BUTT where you can define the *character encoding* (sometimes *charset*) for the metadata? If you do find one, set it to UTF-8 if you can.

Otherwise, which piece of software is the last in the pipeline to display the titles correctly?

**Comment by SlvrEagle23** [comment]
@kokoloman001 Agreed with @biguenique on this one; AzuraCast has full Unicode support across every part of the application. It's possible that SAM Broadcaster is sending the wrong encoding to the DJ software, or perhaps you have the wrong encoding turned on in the station profile (it should be UTF-8).
