### ISSUE TITLE
is possible install without docker?

### ISSUE THREAD

**Issue by JavierGallego** [AzuraCast/AzuraCast#2047]
Hi! is possible install without docker? and if is possible where is the documentation?

**Comment by biguenique** [comment]
Have you tried the instructions to install with Ansible? It shouldn't be much different to set up on Debian. Just make sure all the required software is installed.

**Comment by stemvantwente** [comment]
> Hi!, we have a vps with debian+plesk, how is possible install from source?

Yes you can install but you need to do something in plesk first! you need to be sure that nginx is your main web server!,if you using apache2 now put on proxy for nginx! Ive you already have an website or something else running on port 80 and 443 change ports in the installation folder in the file .env.

Then change in the file docker-compose port numbers who are already used by plesk! recommend not use allot port numbers! so make sure you only have port numbers in there wish are not used by plesk or other applications on youre server!

For more info check https://www.azuracast.com/help/faq_docker.html#use-non-standard-ports
There is allot info to!

Greets

**Comment by SlvrEagle23** [comment]
@JavierGallego We strongly recommend using the Docker installation whenever possible, because Docker allows us to distribute the entire properly-configured software stack, complete with all dependencies. Updates are quite a lot easier, and there is a much lower risk of conflicting with other software on your server, since the AzuraCast installation is entirely self-contained.

In addition, if you're using Debian or any existing software on your server (i.e. Plesk), it is *only* possible to install AzuraCast using Docker. Our other installation method (which is now unsupported for a majority of scenarios) is only supported on Ubuntu 16.04 or 18.04.
