### ISSUE TITLE
Update translate

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#2053]
How can I update this file with translation AzuraCast/resources/locale/translations.json ?

**Comment by afonsosantos** [comment]
You can contribute with translations for AzuraCast in this page: https://translate.azuracast.com/

**Comment by SlvrEagle23** [comment]
@susl16c It's a valid question, since we have only had this new localization method for a while, we haven't had a chance to document any of the process of developing for the frontend.

I've updated our documentation to show how to do both the "generate" and "import" steps for both backend and frontend locales here: https://www.azuracast.com/developers/#translations-locales

**Comment by susl16c** [comment]
./docker.sh cli locales:generate
Starting azuracast_influxdb_1 ...
Starting azuracast_redis_1 ... done
Starting azuracast_stations ... done
2019/10/13 09:46:44 Waiting for: tcp://mariadb:3306
2019/10/13 09:46:44 Waiting for: tcp://influxdb:8086
2019/10/13 09:46:44 Connected to tcp://mariadb:3306
2019/10/13 09:46:44 Connected to tcp://influxdb:8086

  There are no commands defined in the "locales" namespace.

  Did you mean this?
      locale
2019/10/13 09:46:44 Command exited with error: exit status 1
------------------------------------------------------------------------------
