### ISSUE TITLE
Empty playlist tag for queued songs (new Azuracast version)

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#2055]
We updated to 0.9.7.1 and discovered the new feature for queueing songs. I have two questions about the feature: 
- When the song is played, the playlist tag of the song is empty in the nowplaying API. Is it intended? 
- When exactly the song is going to be scheduled? What we could see is that the song would be scheduled "soon" (after about 2-3 songs already in the queue). Is there a way to see more than one songs ahead (similar to the song history list)?

**Comment by SlvrEagle23** [comment]
@gammaw Right now, the "queue" feature just essentially functions as if you're making a song request that doesn't have to go through any approval steps to get approved. In the future I plan on giving the administrator queue its own pipeline which you can examine separate from the requests pipeline. Currently, you can view the "Song Requests" report (if requests are enabled on the station) to see the queued up items.

As for them not being associated with a playlist, that's by design as if you're queueing something up from the media manager, it can be associated with no playlist or multiple playlists, so we can't reasonably infer that you meant it to be from one playlist or another.

**Comment by gammaw** [comment]
@SlvrEagle23 I see, thanks. Is there a way to see the next songs (say the next 4-5 songs), not only the one which is played after the current song? Btw, sometimes the next song cannot be displayed. Why is that?

**Comment by SlvrEagle23** [comment]
@gammaw That "song requests" report is the only way to view what will be upcoming in the queue beyond the next song.

As for why the next song can't be displayed, that depends a lot on what's happening in the system at that exact moment. It's crazy hard to diagnose. I can't guess just from the question what caused it.
