### ISSUE TITLE
Different Musical Genre

### ISSUE THREAD

**Issue by ValentinOgier** [AzuraCast/AzuraCast#2064]
Hello there, I hope you are doing good, I was making some changes on my station and our team and I got an idea.

We currently got a web radio with POP musics, but we'd like to open a new radio with another genre: RAP.

Created a new station, adding files, make the programmation, any problem found.

But, we are currently thinking about it, our team and I are making live, but we'd like to broadcast to all our web radios during live ? We found one possibility: the broadcaster broadcast to all web radios: pop, rap, etc.

It could be easily done if our whole team have the greatest internet speed of France, but some have no good internet connexion so we were thinking about AzuraCast can stop all the web radios and broadcast our live, could this be done ? If yes can you tell us how to process ?

Thank's in advance.

**Comment by SlvrEagle23** [comment]
@ValentinOgier I don't think this is possible in any easy way with how AzuraCast is currently set up.

You could set up the other stations to have mount points that relay the signal from a master "Live" station out to each station, but the individual stations would have no way of knowing when the "live" station is on air or not, so it would constantly play the silence of the offline stream the rest of the time.

It would theoretically be possible if you created an advanced playlist and configured Liquidsoap to use it as a source with silence detection, but I'm not sure that even that would work exactly as you're intending.

**Comment by biguenique** [comment]
One possible (and pretty robust) solution would be this :

You can ask your live DJ to connect directly to one of the Icecast server (port 8000 for the first station) instead of the Liquidsoap harbor (port 8005 for the first station) using the *Source Password* password that is displayed under *Broadcasting Service* in the station main profile (mode: `Icecast2`, username `source` (default), in this example mountpoint would be `/live`).

### Enable one more source on main Icecast
You will first need to allow more sources connected to your main Icecast server (by default AzuraCast only allows the exact number of mountpoints defined). Add the following in *Edit Profile* > *Broadcast* > *Custom Configuration*:
```
{ "limits" : { "sources" : "3" } }
```
Adjust the number to <your number of mountpoints>+1.

### Broadcast live on every station
You can then add something along these lines in *Edit Profile* > *AutoDJ* > *Custom Configuration* for each station (you don't need to change anything else in that screen) :
```
# Relaying live stream connected directly on Icecast
live_mount = audio_to_stereo(id="live_mount",input.http("http://localhost:8000/live",buffer=5.0,max=30.0))
radio = fallback(id="live_switch",track_sensitive=false,[live_mount,radio])
```

I'm testing it right now and it works perfectly well.

See also 
- [Icecast Docs - Config File - limits](https://icecast.org/docs/icecast-2.4.1/config-file.html#limits)
- [Liquidsoap API Reference : fallback](https://www.liquidsoap.info/doc-1.3.7/reference.html#fallback)
- [Liquidsoap API Reference : input.http](https://www.liquidsoap.info/doc-1.3.7/reference.html#input.http)

**Comment by biguenique** [comment]
This switches directly to live as soon as it is available, and right back to the main programme when it disconnects.
