### ISSUE TITLE
Edit Name Song

### ISSUE THREAD

**Issue by Takumi86ES** [AzuraCast/AzuraCast#2073]
When I edit the name of a song it is not saved or when I add to a playlist it returns to its previous name.

**Comment by SlvrEagle23** [comment]
@Takumi86ES I need some more information on the steps you're taking in this process. When the modal dialog box opens, are you closing it immediately or clicking the "Save Changes" button at the bottom? Also, you say it changes the name when setting the playlist...you mean it was showing the correct name before you set the playlists and then it switched?

**Comment by Takumi86ES** [comment]
I save the changes and when I reload the page or add the song to the playlist, the previous name of the song is put back.

**Comment by Takumi86ES** [comment]
It does not save the names of the songs.

**Comment by Takumi86ES** [comment]
Check your email (buster@busterneece.com)

**Comment by SC2Mitch** [comment]
https://puu.sh/EupZ6/1979b593a1.png
After trying it out on my host, it began to repeatedly spam my logs, but the song name did change after a restart of the station.

**Comment by SlvrEagle23** [comment]
@SC2Mitch That's probably unrelated; those are the log messages you'd see if you had a station your installation that had no (or only a few short) songs set up on it, and AzuraCast just kept looking for next songs to play.

@Takumi86ES I...I can actually confirm this bug is happening. If you edit a file, then add it to a new playlist, it returns to its previous name.

I have absolutely no idea why.

Looking into it now.

**Comment by SlvrEagle23** [comment]
@Takumi86ES I've figured out a problem; our updated API call wasn't properly writing changes back to the source file, or marking the database record as modified, so it would "reprocess" and return the metadata back to the original.

It should be fixed now as of the latest update.
