### ISSUE TITLE
Custom album art will not be shown 

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#2076]
Hi, 

with the latest Azuracast release (v0.9.7.1, #d19e50a) after setting a custom image for a song it won't be shown (on Public Player) and also the nowplaying API sends the default cover art URL. It's a high-res picture (over 500px) but the admin page accepted it (after Save Changes I see the custom image on the Music Files page). The song is scheduled in custom playlist but it shouldn't make a difference (at least it always worked with v0.9.6.5). 

Any idea?

**Comment by gammaw** [comment]
It seems that the problem only occurs for newly uploaded songs. If I change the art work for songs that were there before the update I can see the effect (on the player and in the nowplaying API).

**Comment by SlvrEagle23** [comment]
@gammaw I suspect this has to do with some cache settings internal to the system that aren't being properly flushed when new album art is updated.

When you upload the new art, you do see the updated art immediately on the left panel of that same editor page, right? You just don't see it in API responses?

**Comment by gammaw** [comment]
@SlvrEagle23 yes, I see the changes immediately on the admin page (in the left panel of the editor window and also in the Music Files list). But when the song is scheduled, the new art work  is not visible (neither on the Public Page nor in the API). The API returns the default art work URL. Like I said, it works for "old" songs but it doesn't for newly uploaded ones. For old songs I can even change the art work while the song is playing and I see the new picture on the Public Page and in the API.

**Comment by SlvrEagle23** [comment]
@gammaw I can't seem to reproduce this issue locally. As long as I update the album artwork, the next time it shows up on the API responses it uses the correct path.

If it's currently in an API response and you change the artwork while it's playing, that change won't take effect until the next update that changes the song record part of the API response, which happens any time a song change is detected.

The reason we do this is because we assign a unique identifier to each uploaded image, so that we can instruct the browser to cache them for very long periods of time; when uploading new album art, the old image is deleted and a new unique ID is generated so the browser won't load the (now outdated) cached version of the image.

**Comment by SlvrEagle23** [comment]
@gammaw So, I thought about it a little more and there's definitely a bottleneck in our current system that reduces both performance and ease of use: the system did not know whether album art was saved for a file or not, so we couldn't optimize to deliver the static file when needed (and, in your case, you couldn't check for that default album art URL in your software).

I've reworked how we do album art management so that there will always be a timestamp associated with the latest artwork update in the system. Rather than regenerating a new unique ID, we just generate a new timestamp (which means the unique ID is unchanged, so old URLs will work fine, they just might not cache ideally in the browser), and then append that URL into the album art image SRC itself.

This should overall fix a bunch of things.

**Comment by gammaw** [comment]
@SlvrEagle23 I'm a bit confused. Is the new commit related with the other open issue of ours: https://github.com/AzuraCast/AzuraCast/issues/2033 (Default cover art URL issue)?
Because this current issue (#2076) was my mistake which I never saw again after realising that a wrong Liquidsoap configuration was messing up things (this is why I asked you in https://github.com/AzuraCast/AzuraCast/issues/2077 to close both #2076 and #2077).

**Comment by SlvrEagle23** [comment]
@gammaw This was a legitimate issue actually, caused by the unique ID changing when you change album art.

I suppose it addresses both issues.

**Comment by gammaw** [comment]
@SlvrEagle23 that's great, thanks! We'll test it.
