### ISSUE TITLE
Music Page - "File Not Processed" after being fine...

### ISSUE THREAD

**Issue by TogarUshindi** [AzuraCast/AzuraCast#2086]
I was in the root folder. After I moved a single music file into a folder, the others in the root folder are now showing as "File Not Processed." I can still see the filename underneath it in small font.

**Comment by TogarUshindi** [comment]
Just as an experiment, I moved one of the "unprocessed" files into a folder, and inside that new folder it now shows as being processed again.

**Comment by SlvrEagle23** [comment]
@TogarUshindi I figured out the cause of this...if you navigate into a subfolder, then click the parent folder in the "breadcrumb" navigation, it will take you back to the same directory, but with a slash prepended to the front of the path, i.e. `/test` instead of `test`.

I've fixed both the error in breadcrumb navigation that caused this, and added protections to the underlying code to make sure it properly bounces you to the correct listing if you should wind up on the wrong one.

**Comment by TogarUshindi** [comment]
Cool, thanks for your work SE :)
