### ISSUE TITLE
Stream with no MeataData shows "Stream offline"

### ISSUE THREAD

**Issue by sherifkozman** [AzuraCast/AzuraCast#2100]
Hello, 

When an active stream through icecast is not sending any metdata it shows as "Stream offline" although the stream is working.

Not sure if there is a way to override such behaviour as it send a false message that service is not running

**Comment by SlvrEagle23** [comment]
@sherifkozman I don't think there's any way we could work around this, as sometimes the only indicator that we have that a portion of the stream stack isn't working is that the metadata is set to empty.

We could make it a customizable option, but I'm very concerned that users would turn it on, not fully aware of what it did, and it would have unintended consequences.

**Comment by mrnat7471** [comment]
Hi, I have this problem as well, It really needs to be solved soon as I have blank metadata being send down my api making me think the server has stopped work/streaming when its working fine. Hope to see a solve soon on this.

**Comment by SlvrEagle23** [comment]
@mrnat7471 As I just said in the previous response, this is not an error on our part! Empty metadata is often the only indicator we have that a stream is currently offline, so we interpret it as such.

We can add a new option to have the system ignore this either on a global or a per-station level, but in my previous message I explained why I have hesitations about this: because it will very likely result in a number of people selecting the option and then misinterpreting the resulting empty metadata as a bug on AzuraCast's part, thus unintentionally adding to our support burden.

In any case, this is an enhancement request, not a bug report.

**Comment by mrnat7471** [comment]
If that would be an option having system ignore and just using the song name that was played before as its never done it inbetween songs, always in the middle even if its autoDJ or streamer.
So it be a great enhancement.

**Comment by kloudxyz** [comment]
Is there now a solution for this to add manually a metadata line like ( Live Stream) on the panel it self for a stream which is not sending metadata? Because of the missing metadata the live listener report also doent work.
