### ISSUE TITLE
New features entered and PT-BR and others don't work

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#2111]
I updated my azuracast and now the PR-BR translation files don't work. I messed around trying to fix this translation problem and didn't find a solution.

Example, in the previous version in Media Files, I would click on EDIT next to a song and it would appear written in EN normally. Now it has changed and everything appears in English in a new window. Another option you removed was CLEAR PLAYLIST and entered QUEUE. I can not translate this and what appears written when passing the mouse. As part of submitting Drag files I could also translate and now it doesn't work either. Can you please let me know how I should correct these translations? It seems that a lot has changed.

**Comment by SlvrEagle23** [comment]
@Marcioghiraldelli As we move from server-side components to client-side Vue components, some of the strings we use in the application change slightly so the existing translations don't match exactly.

We try to avoid this, but sometimes there's not much we can do, because we had to make a necessary punctuation or grammar change.

When we make those changes, we do generate new translation base files (the `.pot` files in the locales folder), which our [translation site](https://translate.azuracast.com/) uses to allow contributors to submit translations. If you submit new translations for those strings, when we are able to do so we will import those new translations, rebuild the necessary files and update the application.

**Comment by Marcioghiraldelli** [comment]
Hello,
Today I woke up early to perform this task of translating to PT, I made a
large part of the translation file. I hope my work has been satisfactory
and whatever I can contribute to the system I will do!
If you can check this question I appreciate it immensely.

https://translate.azuracast.com/translate/azuracast/8/enus-ptbr

Em sáb., 28 de dez. de 2019 às 04:54, SlvrEagle23 <notifications@github.com>
escreveu:
