### ISSUE TITLE
AzuraCast streams slow to start in Safari browser

### ISSUE THREAD

**Issue by stevenaj** [AzuraCast/AzuraCast#2114]
**Using Docker installation method**

Docker installation as per instructions.  All appears fine at server side.

**Host Operating System**

Host OS is Debian 10 

**Describe the bug**

Streams played using the web player supplied indicated slow start of audio stream in Safari compared to Chrome and Firefox and Microsoft Edge.  Assumed this a browser issues initially until I tried other Icecast streams which started immediately in Safari on other html5 web players. Issue appears to be related only to the AzuraCast generated stream.

**To Reproduce**

Use these live links to best show the issue and test in Safari and Chrome for best demonstration.  Also I have linked to an external web player on our main platform. Click the CHANNELS link on the RIGHT hand side of the home page and I have included the AzuraCast on Channel 2 and our Primary Icecast stream on Channel 1.  The delay is noticeable when you switch between the two steams.

https://r1.zetcast.net/public/60_north_radio_1

https://60north.radio

**Expected behavior**

Stream should start immediately but AzuraCast stream in Safari appears to wait around 6 seconds before playing.

**Relevant Logs**

No error messages server side.

**Screenshots**

**Device(s):**
 - Device:  Desktop MacBook Pro, Windows 10 VM and iPhone 10 
 - OS: 10.14.5 MacOS 
 - Browser: Safari 
 - Version: Version 12.1.1 (14607.2.6.1.1)

**Additional context**

Thanks for an excellent product - best on the market by a very long way.

**Comment by Vaalyn** [comment]
I can confirm this issue happening with the player on the public pages of a station. I've tested it on the link provided above, the demo installation and my own radio.

The issue does not exist when including a stream url directly in an audio tag on a page and only happens when the audio src is set via JavaScript. This seems to be a general issue with Safari that apparently already exists for quite some time as seen in this Apple support forum thread: https://discussions.apple.com/thread/6886071

From reading some StackOverflow posts about this problem it seems to have something to do with how Safari downloads and caches audio streams. Some people write that the problem does not happen when using an `AudioContext` instead of an `audio` element.

https://stackoverflow.com/questions/9811429/html5-audio-tag-on-safari-has-a-delay
