### ISSUE TITLE
On the Air not showing current playing artist.

### ISSUE THREAD

**Issue by themadcap1976** [AzuraCast/AzuraCast#2124]
v0.9.7.1, #d5291dc (2019-11-06 21:20)

I'm seeing this error over and over on the liquidsoap.log

2019/11/06 21:56:25 [lang:3] AzuraCast Raw Response: Error: Undefined class constant 'TYPE_SCHEDULED' on /var/azuracast/www/src/Radio/AutoDJ.php L275
2019/11/06 21:56:25 [lang:3] AzuraCast Error: Delaying subsequent requests...

I tried restoring and I may have just made it worse.
Station is playing via Shoutcast, Artist shows up on Shoutcast, but Auto DJ isn't displaying current artist under "on the air" nor the number of listeners.

![Screen Shot 2019-11-06 at 10 04 12 PM](https://user-images.githubusercontent.com/32073620/68356838-688e0180-00e1-11ea-993c-78023ece8218.png)

**Comment by SlvrEagle23** [comment]
@themadcap1976 Thank you for the report. The issue is a fairly minor oversight on my part as of the latest update. I'm pushing out a fix that should be available shortly; I'd wait about 5 minutes before updating your installation just to make sure you're on the very latest version, but it should be completely resolved.

**Comment by themadcap1976** [comment]
Logs look clean now, thank you. Looks good now. I was in panic mode :)
