### ISSUE TITLE
Scheduling not working since latest update

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#2132]
Hi, 
I am using Azuracast and I love its ease of use.
My radio plays scheduled playlist and the rest of the time it plays general rotation playlist (using the handy 'weight' parameter).
After the last update I am quite confused of how the playlist should be configured.

We used to have 
- General Rotation playlist, which where played all day, using the "weight" parameter
- Scheduled playlist, where no general rotation playlist was played

After a very recent update, I got general rotation playlist playing during scheduled.
I understand every general rotation playlist nows need to have scheduled time items outside the "scheduled playlist" times, otherwise we end up having general rotation tracks playing during scheduled playlist.

Am I right?
----
So I did the above and as expected, no general rotation playlist is played when a scheduled playlist is. But outside the scheduled playlist times, only one of the general rotation playlist is played. it seems it is the one with the highest 'weight' parameter.
Here is what the station log shows endlessly

```
[2019-11-12T09:28:31.445682+00:00] AzuraCast.INFO: AzuraCast AutoDJ is calculating the next song to play... [] {"station":{"id":3,"name":"My radio"}}
[2019-11-12T09:28:31.482676+00:00] AzuraCast.ERROR: No playable tracks were found. [] {"station":{"id":3,"name":"My radio"}}
```
Could you please tell me how should I solve this issue?

**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04

**Comment by SlvrEagle23** [comment]
@griffon56 This is a valid question...if you have scheduled entries, in the past those took priority over general rotation playlists during those scheduled times, and now they will blend in with general rotation playlists during those times. I can see how that wouldn't be the intended functionality.

I'll look into a possible solution for this problem. Scheduled entries should have priority over non-scheduled (general rotation) ones.

**Comment by rmacari** [comment]
@griffon56 @SlvrEagle23 We are having the same issue here. Our workaround on this was to set up a scheduled time for every general playlist so they don´t play while the one that we want is playing. (We have 3 general playlist, i´ll show just one so you can understand)

General Playlist 1:
![Screen Shot 2019-11-15 at 12 01 38](https://user-images.githubusercontent.com/5432270/68942185-ce445280-079f-11ea-8053-592d0d629999.png)

Slow music songs:
![Screen Shot 2019-11-15 at 12 02 10](https://user-images.githubusercontent.com/5432270/68942186-ce445280-079f-11ea-8a85-82c2d9eab8e4.png)

And you will get this nightware view in your View Schedule:
![Screen Shot 2019-11-15 at 12 04 20](https://user-images.githubusercontent.com/5432270/68942293-29764500-07a0-11ea-9479-988fa164ba95.png)


I hope this helps you quick fix your problem.

**Comment by SlvrEagle23** [comment]
@griffon56 @rmacari Clearly that kind of workaround isn't what we were envisioning when we made the new schedule changes, so I've updated the codebase accordingly to fix the issue.

Now, just as was the functionality before, if you have any scheduled playlists, they will pre-empt any unscheduled ones in the time(s) that they should play. This applies for the scheduled and unscheduled variants of all playlist types.

**Comment by hottweelz** [comment]
We are experiencing this exact issue, however, if we update a show in the playlist, we have to "restart" autodj for it to work....  everyone else has confirmed that this is fine? 

Restarting AUTODJ is not good.  We are on the latest version

**Comment by hottweelz** [comment]
I did reply to issue #2132 and I'm not sure what "additional details" you'd need.

With all due respect the statement "this exact issue" kind of speaks for itself.

You want a screenshot of a scheduled playlist?

Also, again, with all due respect, don't close out tickets because you believe they're not priority.
<img width="837" alt="Screen Shot 2019-12-27 at 3 04 48 PM" src="https://user-images.githubusercontent.com/52544955/71530952-821a2100-28ba-11ea-9d76-d01209b5e7fd.png">
<img width="826" alt="Screen Shot 2019-12-27 at 3 04 32 PM" src="https://user-images.githubusercontent.com/52544955/71530953-821a2100-28ba-11ea-8de8-b5acfdd50644.png">

**Comment by SlvrEagle23** [comment]
@hottweelz The reason you're having to restart your AutoDJ with every change to the playlist is because you have "interrupt other songs" turned on. The only way we can interrupt other songs via our AutoDJ is to write the configuration file to Liquidsoap directly and let it handle the scheduling, which means that every change would require a restart of broadcasting. The easiest way to avoid this is to turn off all settings in the "AutoDJ Scheduling Options".

**Comment by biguenique** [comment]
This other ticket is also directly concerned with scheduling issues: https://github.com/AzuraCast/AzuraCast/issues/2200

**Comment by SlvrEagle23** [comment]
We've made some very significant changes to how scheduling is handled in AzuraCast since this issue was last updated; if you continue to have scheduling problems, please see the new "super-issue" #2631 for more information.
