### ISSUE TITLE
Radio Won´t start after latest update

### ISSUE THREAD

**Issue by rmacari** [AzuraCast/AzuraCast#2135]
**Using Docker installation method**

Yes 

**Host Operating System**

**Describe the bug**

After the update, Liquidsoap won´t start and show an error message. 
**To Reproduce**

Update Azuracast to the latest release.

**Expected behavior**

**Relevant Logs**

**Screenshots**

![Screen Shot 2019-11-13 at 10 08 29](https://user-images.githubusercontent.com/5432270/68755126-f1380080-05ff-11ea-8949-7fd3f8d57a7a.png)

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by kemecs** [comment]
root@folk-ubuntu:/var/azuracast# tail -f /var/lib/docker/volumes/azuracast_station_data/_data/stream.folkradio.hu/config/liquidsoap.log
has no argument labeled "start_next"!
At line 40, char 29-31:
Error 6: Cannot apply that parameter because the function at line 40, char 8-18
has no argument labeled "start_next"!
At line 40, char 29-31:
Error 6: Cannot apply that parameter because the function at line 40, char 8-18
has no argument labeled "start_next"!
At line 40, char 29-31:
Error 6: Cannot apply that parameter because the function at line 40, char 8-18
has no argument labeled "start_next"!

**Comment by SlvrEagle23** [comment]
@rmacari This should be fixed as of the latest update to AzuraCast; you may need to run your update script agan to get the latest version.

**Comment by rmacari** [comment]
Same issue after the requested update.

Liquidsoap encountered an error
At line 168, char 125-128:
Error 6: Cannot apply that parameter because the function at line 168, char 8-17
has no argument labeled "rms_window"!
At line 168, char 125-128:
Error 6: Cannot apply that parameter because the function at line 168, char 8-17
has no argument labeled "rms_window"!

**Comment by kemecs** [comment]
2019/11/14 17:32:46 Command finished successfully.
azuracast_redis_1 is up-to-date
azuracast_stations is up-to-date
azuracast_influxdb_1 is up-to-date
azuracast_mariadb_1 is up-to-date
Creating azuracast_web ... done
Update complete!
root@list:/var/azuracast# tail -f /var/lib/docker/volumes/azuracast_station_data/_data/stream.folkradio.hu/config/liquidsoap.log
has no argument labeled "start_next"!
At line 40, char 29-31:
Error 6: Cannot apply that parameter because the function at line 40, char 8-18
has no argument labeled "start_next"!
At line 40, char 29-31:
Error 6: Cannot apply that parameter because the function at line 40, char 8-18
has no argument labeled "start_next"!
At line 40, char 29-31:
Error 6: Cannot apply that parameter because the function at line 40, char 8-18
has no argument labeled "start_next"!

**Comment by SlvrEagle23** [comment]
@rmacari That appears to be custom Liquidsoap code, as our code doesn't supply the "rms_window" parameter anywhere. You should check your custom code to ensure it wasn't broken by the Liquidsoap update.

@kemecs This should be fixed by updating to the latest version of AzuraCast's code base, which fixes this issue.

**Comment by kemecs** [comment]
> 2019/11/14 17:32:46 Command finished successfully.
> azuracast_redis_1 is up-to-date
> azuracast_stations is up-to-date
> azuracast_influxdb_1 is up-to-date
> azuracast_mariadb_1 is up-to-date
> Creating azuracast_web ... done
> Update complete!
> root@list:/var/azuracast# tail -f /var/lib/docker/volumes/azuracast_station_data/_data/stream.folkradio.hu/config/liquidsoap.log
> has no argument labeled "start_next"!
> At line 40, char 29-31:
> Error 6: Cannot apply that parameter because the function at line 40, char 8-18
> has no argument labeled "start_next"!
> At line 40, char 29-31:
> Error 6: Cannot apply that parameter because the function at line 40, char 8-18
> has no argument labeled "start_next"!
> At line 40, char 29-31:
> Error 6: Cannot apply that parameter because the function at line 40, char 8-18
> has no argument labeled "start_next"!
> 
> edit my liquidsoap.liq:
> 
> radio = amplify(1., radio)
> radio = crossfade(start_next=3.,fade_out=2.,fade_in=2.,radio)

**Comment by rmacari** [comment]
> @rmacari That appears to be custom Liquidsoap code, as our code doesn't supply the "rms_window" parameter anywhere. You should check your custom code to ensure it wasn't broken by the Liquidsoap update.
> 


@SlvrEagle23 You are right, i use the following code in the Avanced configuration for Auto DJ: 
`# Normalization and Compression for FM audio
radio = sky(radio)
radio = compress(radio, attack = 4.0, gain = 7.0, knee = 10.0, ratio = 5.0, release = 100.0, threshold = -18.0, rms_window = 0.7)
radio = normalize(radio, target = -1.0, threshold = -65.0)
radio = limit(radio, threshold = -0.2, attack = 2.0, release = 25.0, rms_window = 0.02)`

But I need this to make the sound of the radio good as this process the audio giving the listener a feeling of a PRO radio. I can´t remove or stop using it, SOUND QUALITY matters. 

The suggestion here to fix this: Give the option in the radio setup to choose the Liquidsoap version. Or give a better option in sound processing directly, with personal setup. 

Also, as this was the best option that I could find for sound processing and I did extensive tests, the results are really great, can you suggest a better one that works the same way with the new Liquidsoap version? I´ll appreciate it. Thanks.

**Comment by SlvrEagle23** [comment]
@rmacari As has been discussed in other channels, the simple fix here is just changing `rms_window` to `window`. It's a really simple change and probably doesn't merit the severe response of panicking and wanting to revert to the previous version.

In general, no, we have no plans to make multiple versions of Liquidsoap available. Just to build the _one_ version we use requires a 40-minute build process that we can't do anything about, so to build _multiple_ versions would push our build times upward of an hour, and would represent a very significant development load on our part.

**Comment by dbeiner** [comment]
Hi !

Liquidsoap doesn't start after the latest update (today) for me : 

1. **Error : no argument labeled "start_next"!** >> fixed temporary by adding a comment at the beginning of the line : radio = crossfade(start_next=3.,fade_out=2.,fade_in=2.,radio)

2. **Error : "rms_window"** >> fixed by renomming rms_window to window

BUT ! Now I get this error and Liquidsoap won't start : 

![image](https://user-images.githubusercontent.com/50744242/69240441-c53af300-0b9c-11ea-885c-5a542a97011c.png)

What can I do ? I use Docker...

Thank you !
