### ISSUE TITLE
Incorrect Listeners Parameters

### ISSUE THREAD

**Issue by YosefAdPro** [AzuraCast/AzuraCast#2136]
**Using Docker installation method**

No v0.9.7.1
**Host Operating System**
 Ubuntu 18.04.2

**Describe the bug**

The data in the Dashbroad or Api is incorrect
**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Dashbroad:**
![image](https://user-images.githubusercontent.com/11810187/68765495-91ece700-0625-11ea-9451-c66b2e5fd80f.png)

**SHOUTcast: (correct)**
![image](https://user-images.githubusercontent.com/11810187/68765277-1c811680-0625-11ea-91d5-02bb92a09b6d.png)

**Api:**

> "listeners":{"current":403,"unique":403,"total":403}}]

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@YosefAdPro This may not be an error, but just a difference in how AzuraCast calculates unique listeners. In the case of locally hosted SHOUTcast streams, we pull the details on each listener, and generate a unique hash based on their IP and user agent to determine whether they qualify as "unique" in a given situation. It's possible that we're arriving at slightly different conclusions than SHOUTcast does as a result of that.

**Comment by YosefAdPro** [comment]
@SlvrEagle23 Do you need more information on this issue?

**Comment by SlvrEagle23** [comment]
@YosefAdPro as I was mentioning in my previous response, I'm not sure that this is an issue that merits our follow-up at all. We directly pull the listeners from SHOUTcast or Icecast and manually remove duplicates using our own formula for determining what listeners are duplicate ones (we mainly do this because Icecast doesn't internally do this on its own). Thus, we may arrive at slightly different conclusions as to which listeners are unique, given the same numbers.

Unless you can demonstrate that your listener report is itself inaccurate in some way, I strongly suspect that's why the numbers are slightly off like that.
