### ISSUE TITLE
Can't edit artist name.

### ISSUE THREAD

**Issue by r0nd0n** [AzuraCast/AzuraCast#2138]
On v0.9.7.1, #d19e50a (2019-10-16 9:13) Docker PHP 7.2 with Ubuntu 18.04. Once a song is named in the music files, the artist name can't be changed. It will appear changed, but approx 15 mins after the change it will revert back.

**Comment by SlvrEagle23** [comment]
@r0nd0n You're about 3 weeks behind on updates if you're on `d19e50a`, you should update your installation to the latest version, which should resolve this issue.

Always make sure you're on the latest version before creating GitHub issues, because we iterate very quickly on this project and fix a number of things in any given week.
