### ISSUE TITLE
Metadata for tracks - new feature

### ISSUE THREAD

**Issue by RabidDog** [AzuraCast/AzuraCast#214]
Hi, would be really neat to have additional metadata attached to the track details. I have a situation where I need to attach the facebook page of an artist to their track but this feature might also enable other social media integration (not direct, more reference data).

**Comment by SlvrEagle23** [comment]
@RabidDog I'm definitely on board with this idea, especially since recent changes have already made it so that the AzuraCast API returns whatever metadata it has stored about a song instead of just repeating what ShoutCast/IceCast says, provided the song actually came from the AzuraCast AutoDJ. It would be trivial to add in other metadata elements.

The problem, of course, is picking which ones. I wouldn't want to specify some prebuilt set of possible metadata attributes, so it's likely that this "extra" metadata would be returned in a format like:

```json
"song": {
  "title": "Foo",
  "artist": "Bar",
  "text": "Bar - Foo",
  "extra": [
    { "key": "facebook_url", "value": "facebook.com/foobar" },
    { "key": "twitter_url", "value": "twitter.com/foobar" }
  ]
}
```

**Comment by RabidDog** [comment]
@SlvrEagle23 Precisely what I was thinking. A key value array is spot on. That way the operator can decide naming conventions for the metadata.

**Comment by SlvrEagle23** [comment]
@RabidDog This feature required a _lot_ of under-the-hood work, but now it's done and ready to use!

Here are the steps to setting up custom metadata:

- Visit the AzuraCast administration, click "Custom Fields", and create new fields that should be listed on every song's edit form.
- Visit any station, click "Music Files", then click "Edit" next to the file. You'll see the new custom fields, which you can then populate.
- Any populated fields will appear in any API responses, including the primary nowplaying APIs.
