### ISSUE TITLE
Question about using AutoDJ advanced custom configuration

### ISSUE THREAD

**Issue by dbeiner** [AzuraCast/AzuraCast#2143]
Hi AzuraCast Team !

Just one question about using AutoDJ Advanced Custom Configuration : 

If I've been understand, as soon as you use the custom AutoDJ configuration, all the options available in AzuraCast, especially for playlists (scheduler, rotation rules, etc.) are no longer usable in the Web GUI?

My thinking is that I would like to use the custom configuration only for audio processing and use the interface options to manage playlists programming and rotation.

Thank you for your response and congratulations for this wonderful project!

**Comment by SlvrEagle23** [comment]
@dbeiner At the moment, there's no way to just customize, say, the audio processing on a playlist without marking it as an "Advanced" playlist, which does indeed remove our GUI's control of the playlist and instead just defines a playlist variable in the Liquidsoap configuration, which you can then modify or use as needed.

If you want to apply audio processing to the entire stream, you can do that using our "Advanced Custom Configuration" at the station profile level, where the entire outbound radio stream is represented by the `radio` variable.

Otherwise, it would likely be an excellent [new feature suggestion](https://features.azuracast.com/).

**Comment by dbeiner** [comment]
Hello @SlvrEagle23 !

Ok thank you! I've submitted a new feature suggestion! ;)

One more time, thank you for this project and good luck!

David
