### ISSUE TITLE
Support More Than 5 Users on FTP At Once

### ISSUE THREAD

**Issue by CodeSteele** [AzuraCast/AzuraCast#2169]
```Status:	Connecting to 192.168.41.12:21...
Status:	Connection established, waiting for welcome message...
Response:	421 5 users (the maximum) are already logged in, sorry
Error:	Could not connect to server
```

Probably just a configuration tweak.

**Comment by CodeSteele** [comment]
Hmm, pureftpd reserves 2 passive ports per user, and we're using 10 here: https://github.com/AzuraCast/docker-azuracast-web-v2/blob/master/pure-ftpd/pure-ftpd.conf, so maybe we keep this limit?

**Comment by CodeSteele** [comment]
The 15 minute inactive time to kick may be a brutal part of it...

**Comment by SlvrEagle23** [comment]
The default port range has been expanded to 30000-30049, which allows for 25 simultaneous users, which should handle multiple users even if they're using multiple concurrent connections.

The reason I don't expand that further is because of existing known issues with Docker's userland proxy taking 1MB of RAM per port forwarded.
