### ISSUE TITLE
Total Listener Hours incorrect data

### ISSUE THREAD

**Issue by mikedorst** [AzuraCast/AzuraCast#2186]
Hey,

The total listener hours seem to display incorrect data to me. I'm filtering on "this month" and it tells me there are 47 unique listeners and over 4000 hours total listening time, this is simply impossible.

![image](https://user-images.githubusercontent.com/27761242/69913658-f20fc580-143a-11ea-8c2b-e99b2f660352.png)

After a quick refresh it shows 48 unique listeners and 2000+ listening hours.

![image](https://user-images.githubusercontent.com/27761242/69913667-ffc54b00-143a-11ea-8b4c-f07542f14e23.png)

Last month seem to have worked as intended.

![image](https://user-images.githubusercontent.com/27761242/69913674-1075c100-143b-11ea-88d1-4d1c89f5a6c1.png)

Filtering on "today" seems to show accurate data, however when you filter on "this month" it shows the incorrect data. Even though both should show exactly the same data as "this month" only consists of the 1st of December.

**Comment by mikedorst** [comment]
![CEvbQGHUA3](https://user-images.githubusercontent.com/27761242/70272134-08ee4900-17a8-11ea-9835-427952f83e37.gif)

Is this enough info? I start off at the "This month" screen and refresh after a minute and it shows like 200 extra hours. The data is incorrect overall for "this month".

**Comment by SlvrEagle23** [comment]
@mikedorst That is very helpful, but the interesting thing would be to see if, when you see the 10000 listener hours, if the seconds listed in the line-item reports actually add up to anything approximating that total. The TLH calculation is done based solely on the actual data it returns.

**Comment by SC2Mitch** [comment]
@SlvrEagle23 I've been looking into this on our side and it does appear to be an Azura related issue, after adding all the numbers up by filtering `this month` (date: dec 1st - dec 31st) it adds up to a total of 7186 hours (adjusted to current date) but even that value is incorrect, as it's impossible to have that many hours in 8 days. 
![%pn_uc6hFyPAMB](https://user-images.githubusercontent.com/29955942/70382831-64f8cf00-195a-11ea-963d-f0e96eb4a03a.png)
and there was a total of 12 unique listeners that broke the 2'000'000 second point (if that's at all helpful)

**Comment by SlvrEagle23** [comment]
@mikedorst @SC2Mitch I've figured out what can happen in this situation...multiple simultaneous connections from the same "user" (combination of IP and user agent) count individually toward your total listener count, which means that a single user could (inadvertently or otherwise) hold open several simultaneous connections, which would stack on top of each other. This often happens with "bad-behaving" clients that don't properly terminate older connections, and then reconnect and end up maintaining multiple concurrent connections.

The new report calculation takes every interval that a given listener is connected for and overlaps them, so no matter how many concurrent connections exist in a given moment, they're all only counted as a single "performance second".

This should yield much more realistic numbers. Update your installations and let me know how things look.

**Comment by SC2Mitch** [comment]
This can be closed, results are much better.
