### ISSUE TITLE
Error to install

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#2199]
**Using Docker installation method**
No

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
I was tried to install Azuracast on Ubuntu 18.04 64 bits by Ansible (Bare-metal/Traditional) , but it gave me an error.
![screenshot 1](https://user-images.githubusercontent.com/7109309/70377376-cd6c8f80-190b-11ea-914e-924bb00b72aa.jpg)

**Comment by SlvrEagle23** [comment]
@jonikane As a reminder, our Ansible/Traditional installation isn't officially supported for most cases. In most cases, there's no technical reason you can't use the Docker installation, and you're recommended to do so, because of the huge class of errors that are possible with the Ansible installation method.

This may be a simple fix, though, so I have updated our installation scripts to add another "wait for service to start up" delay after the service restarts. This should help with this issue.
