### ISSUE TITLE
Playlist option "Only play one track at scheduled time" not working

### ISSUE THREAD

**Issue by rmacari** [AzuraCast/AzuraCast#2200]
**Using Docker installation method**

yes

**Host Operating System**

**Describe the bug**

Option "Only play one track at scheduled time" not working anymore.
Even with the option checked system continues to play more sounds from the playlist.

**To Reproduce**

Create a playlist, check option Only play one track at scheduled time.

**Expected behavior**

**Relevant Logs**

**Screenshots**

![Screen Shot 2019-12-07 at 21 08 45](https://user-images.githubusercontent.com/5432270/70380620-323cdf80-1936-11ea-8c96-13dfcef3a8a4.png)

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@rmacari The checkboxes on the right (AutoDJ advanced playlist settings) cause us a whole bunch of problems, and are very difficult for us to support, as they tie directly into Liquidsoap functionality.

I'll see if we can look into it, but this just might not work for now.

**Comment by rmacari** [comment]
@SlvrEagle23 Appreciate if you can look into this because it used to work and is quite essential to any station that needs to play just one sound/music/program at that time. 

Thanks.

**Comment by biguenique** [comment]
@rmacari What do you have under the `Schedule` tab for that playlist?

**Comment by rmacari** [comment]
@biguenique 

![Screen Shot 2019-12-19 at 11 37 07](https://user-images.githubusercontent.com/5432270/71170758-f10ccf80-2253-11ea-8adb-6972b18f09ac.png)

**Comment by biguenique** [comment]
@rmacari Sorry my answer is so late, I couldn't find the time to do proper testing before now. I managed to reproduce your bug:

- Created a `test` playlist and add at least one song to it
- Left _Playlist Type_ to _General Rotation_
- Checked _Only play one track at schedule time_ in _AutoDJ Scheduling Options_
- Added _Scheduled Time_ for playlist to trigger in a certain time time span

**Expected behaviour**
One single title from the `test` playlist should be fed from the playlist and scheduled between two song as soon as the time reaches the scheduled time span.

**Actual behaviour**
The playlist keeps playing until the end of scheduled time span is reached; it fails to fall back to general rotations after the first title is played. It still honours _Once per Hour_ playlists, though.

@SlvrEagle23 It seems to me that the quirky behaviour is not caused 'upstream' by Liquidsoap, but rather by the internal scheduling logic of Azuracast.

### Looking at the Liquidsoap script
Looking at the generated script in _Log Viewer_ > _Liquidsoap Configuration_ after restarting Liquidsoap, everything _seems_ like it should play only as expected. All scheduled playlists get scheduled in a `switch()` command, along with any _Once per Hour_ playlists. Expanding the code on multiple lines, we get something along:

```
# Standard Schedule Switches
radio = switch(id="station_schedule_switch", track_sensitive=true, [
   ({ (1w or 6w) and 5h59m-6h30m }, once(playlist_test)),
   ({ 58m }, once(playlist_jingles)),
   ({ 57m }, once(playlist_spots)),
   ({true}, radio)
])
```

Since `once()` is used, we can expect that Liquidsoap will only play only one song from `playlist_test` as soon as the scheduled time span evaluates to true, then switch back to the following items.

It works perfectly well for my jingles and my spots... So what is going wrong with scheduled playlists?

### Looking at the Liquidsoap Log
Peeking at _Log Viewer_ > _Liquidsoap Log_ when the buggy behaviour triggers (it doesn't _always_ trigger immediately, I'm still trying to figure out _why_...), we realize the culprit is not the `switch()` (`station_schedule_switch`, but rather Azuracast's internal scheduler which keeps feeding titles from the `test` playlist.

```
...
2019/12/23 13:27:47 [station_next_song:3] Prepared "/var/azuracast/stations/share/media/test.mp3" (RID 21).
2019/12/23 13:27:47 [cross_7731:3] Analysis: -110.820391dB / -25.379335dB (4.99s / 5.01s)
2019/12/23 13:27:47 [crossfade:3] new >= old + margin, old <= medium and new <= high.
2019/12/23 13:27:47 [crossfade:3] Do not fade if it's already very low.
2019/12/23 13:27:47 [crossfade:3] Transition: crossed, no fade.
2019/12/23 13:27:48 [lang:3] AzuraCast Feedback Response: OK
2019/12/23 13:27:48 [lang:3] AzuraCast Raw Response: annotate:title="Test",artist="Test",duration="51.",song_id="aa2f11d65bb7b3578a35c59346639e18",media_id="2157",playlist_id="14":/var/azuracast/stations/share/media/test.mp3
2019/12/23 13:27:48 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/share/media/test.mp3".
2019/12/23 13:28:33 [station_next_song:3] Prepared "/var/azuracast/stations/share/media/test" (RID 22).
2019/12/23 13:28:33 [lang:3] AzuraCast Raw Response: annotate:title="Test",artist="Test",duration="51.",song_id="aa2f11d65bb7b3578a35c59346639e18",media_id="2157",playlist_id="14":/var/azuracast/stations/share/media/test.mp3
2019/12/23 13:28:33 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/share/media/test.mp3".
2019/12/23 13:28:33 [cross_7731:3] Analysis: -22.818710dB / -25.371044dB (4.97s / 4.99s)
2019/12/23 13:28:33 [crossfade:3] No transition: using default.
2019/12/23 13:28:34 [lang:3] AzuraCast Feedback Response: OK
...
```
And `station_next_song` then keeps re-scheduling the playlist over and over...

A 'normal' scheduling through `station_schedule_switch` can at times be observed:
```
...
2019/12/23 13:23:54 [playlist_test:3] Prepared "/var/azuracast/stations/share/media/test.mp3" (RID 8).
2019/12/23 13:23:54 [fallback_7703:3] Switch to station_schedule_switch with forgetful transition.
2019/12/23 13:23:54 [station_schedule_switch:3] Switch to sequence_7693.
2019/12/23 13:23:54 [decoder:3] Method "MAD" accepted "/var/azuracast/stations/share/media/test.mp3".
...
```

### Double scheduling logic?

Looking at the Liquidsoap script generated by Azuracast to understand the scheduling logic, we can schematize:

- Playlists definitions (`playlist_*`)
- Scheduling
  - _Standard Playlists_ (`<station>_standard_playlists` aka _General Rotations_, weighted random)
  - _Standard Schedule Switches_ (`<station>_schedule_switch`), including:
    - Playlists with one or more _Schedule_ item defined
    - _Once per Hour_ playlists
  - _Once per x Songs Playlists_ (one `rotate(...)` per playlist)
  - _Once per x Minutes Playlists_ (one `fallback(...)` per playlist)
  - _**AutoDJ Next Song Script**_ (`<station>_next_song`, `<station>_autodj_fallback`)
  - _Interrupting Schedule Switches_ (`<station>_interrupt_switch`)
  - Request Queue (`<station>_requests`+fallback)
  - Cue Cut
  - Skip Command
  - _Live Broadcasting_ logic (`<station>_live_switch`)
- Metadata
  - _Allow for Telnet-driven insertion of custom metadata_ (`custom_metadata`) 
- Post-processing
  - _Apply amplification metadata (if supplied)_ (`amplify(...)`)
  - _Normalization and Compression_
  - Crossfade
- Custom script
  - _Custom Configuration (Specified in Station Profile)_
- _Send metadata changes back to AzuraCast_
- _Local Broadcast_
- _Remote Relays_

Here is the part for __AutoDJ Next Song Script__ in Liquidsoap:
```
# AutoDJ Next Song Script
def azuracast_next_song() =
  uri = list.hd(get_process_lines("curl -s --request POST --url http://web/api/internal/1/nextsong --form api_auth="^string.quote(<Authentication key removed>)^""), default="")
  log("AzuraCast Raw Response: #{uri}")
  
  if uri == "" or string.match(pattern="Error", uri) then
    log("AzuraCast Error: Delaying subsequent requests...")
    system("sleep 2")
    request.create("")
  else
    request.create(uri)
  end
end

dynamic = audio_to_stereo(request.dynamic(id="station_next_song", timeout=20., azuracast_next_song))
radio = fallback(id="station_autodj_fallback", track_sensitive = true, [dynamic, radio])
```

Problems I see with the current implementation:
- **Double scheduler?**: from what I see, it seems that the Liquidsoap script is made to handle all the exposed possible scheduling options, and would run the station as expected without the intervention of the AutoDJ Next Song Script. Yet there is apparently another scheduler internal to Azuracast that feeds titles to Liquidsoap _on top_ of Liquidsoap's scheduled stream. Why is it so? Is it solely to control the next title? This leads to much confusion on wether scheduled events are triggered by Liquidsoap or Azuracast.
- **Limitations of the [_Advanced Playlist_](www.azuracast.com/help/advanced_playlists.html) mode**: I myself really appreciate the _Custom Configuration_ option available in _Station Profile_ > _AutoDJ_, as it allows you to leverage the full power of Liquidsoap. But leaving this as the only option for _Advanced Playlists_ is limitating, since the custom code gets inserted _after_ *a lot* of processing (namely: AutoDJ, Request Queue, Cue Cut, Skip Command, Live DJ, Telnet Metadata & Post-processing). That renders the option, if not useless, very hard to implement whilst preserving Azuracast's benefits. There should be a way to insert Advanced Playlist code _before_ all the processing takes place to render that option usable.

@SlvrEagle23 I think the entire scheduling logic in Azuracast would deserve some in-depth analysis. Liquidsoap is by itself a very capable scheduler, and I see very little incentive to maintain another internal scheduler, appart perharps from managing user _Requests_. But then there is this _Next Song_ feature... How well does it actually work, and how badly do we need this?

### Workaround?
@rmacari I'm still trying to figure out a workaround to your bug. I'll let you know if I find a working solution.

For now I can only tell that it works as expected when you check _Interrupt other songs to play at scheduled time_ in the playlist _AutoDJ Scheduling Options_, but it will cut any song that happens to play on triggering. As for relying on _Advanced Playlist_ for a workaround, it would only be an option if you don't rely on all the processing chain that gets skipped as reported above...

**Comment by SlvrEagle23** [comment]
@biguenique You are correct in that there's some duplication of scheduling between AzuraCast and Liquidsoap; this is by design, as we want the system to be able to operate solely within Liquidsoap if for whatever reason the AzuraCast AutoDJ stops working.

However, there are two major reasons we have our own AutoDJ implementation:
 - To be able to create a queue that also indicates what the next song is (several stations consider this extremely important to have, though several others prefer not to have it, especially since some royalty agencies don't allow it being displayed), and
 - To allow changes to playlists and configuration without needing to restart the Liquidsoap service. Currently, we're not aware of _any_ way to allow changes to playlists/configuration to reload without triggering a full service restart, which at the very least causes the audio to "jump". We've already seen in recent examples that users get _very_ upset about this, so we don't want to rely on it exclusively.

I agree that Liquidsoap is capable of being an excellent scheduler, and it can handle live time-based events a lot better than a PHP script handling these things on an as-requested basis. However, it definitely has its limitations (i.e. the "interrupting" schedule playlists only abruptly interrupt existing scheduled items) and the two issues above basically make it a dealbreaker if we want to be able to do  what we need to with it.

**Comment by rmacari** [comment]
@biguenique That was one impressive real in-depth look at the issue and I really appreciate it for doing. I really hope that this problem can be solved soon because it causes some issues with the regular broadcast when it plays two pre-recorded shows instead of one as it should be in our radio schedule.  And of course, as you pointed too, using that interrupting option is NOT an option. Thank you again. :)

**Comment by biguenique** [comment]
@SlvrEagle23 These make really good arguments for the existence of the AzuraCast AutoDJ scheduler on top of Liquidsoap's own scheduling abilities.

How I get it, _everything_ that is played by Liquidsoap should be fed by AudoDJ Next Song, without ever playing a single title on Liquidsoap's initiative (unless AutoDJ fails for some reason).

When I find some extra time, I'll try to analyze how one could make Liquidsoap give full control and initiative to AzuraCast's AutoDJ, only using it's own scheduling logic as an ultimate backup _fallback_. I'll come back with some results and/or suggestions about this.

@rmacari **Have you tried this**: reducing the window of your event, to say the length of the shortest pre-recorded show in the playlist? That would allow the scheduled event to expire _before_ a second show is triggered...

@SlvrEagle23 ...but that would still be only a _workaround_, not a _fix_. There is still an underlying bug (or design flaw) in AutoDJ that keeps feeding titles from the scheduled playlist (as I pointed out) even though the _Only play one track..._ option is checked...

Some thoughts:
- Since Liquidsoap's internal scheduler is _only_ purposed as a _fallback_, scheduling options should be designed so that they are to be handled _entirely_ by AzuraCast's scheduler and should _not rely_ on Liquidsoap's scheduling features (except as a fallback).
- Maybe AzuraCast's AutoDJ's capabilities should _mimic_ (or rather _be inspired_ by) what Liquidsoap is able to do itself, so that falling back would then happen seamlessly.
- But it would be way more interesting to have an AutoDJ that is robust, with well working options, and that never fails -- so that we never even ever need to fall back!
- Moreover, the way I see it now, the Liquidsoap script perfectly emulating the internal scheduler is, at least at the moment, more an _obstacle to development_ than it is a _desirable backup feature_, since things might _seem_ to be working as expected even when the AutoDJ is _not_ behaving as expected. It also renders debugging more complex. Perhaps a simpler fallback to the AutoDJ in Liquidsoap would ease development.

@rmacari I'm really enthousiastic about AzuraCast, and was already looking to grasp its scheduling logic. Looking at other people's issues is a good pretext to push yourself deeper into understanding things. Hopefully my past experience with Liquidsoap as well as programming can eventually benefit, one way or another, to this amazing open source project & its community.

(Adam Smith and the classical economists all thought that self-interest was the main force of social development, but I'm pretty sure they were only taking account of themselves. I think _helping others_, _caring_ and _sharing_ are key motivations to human activity, and the only forces that lead to a truly human society -- but in the meantime, I still got bills to pay, so I can only put so much time and effort into this!)

**Comment by SlvrEagle23** [comment]
@biguenique I'm all for the idea of building a better scheduler inside AzuraCast, so that it can serve as the authoritative AutoDJ even for those weird situations that people want, like "interrupt other songs" and "play once", but it's quite difficult to program those things, and even harder to test the edge cases they introduce.

Liquidsoap's internal scheduler is why we used Liquidsoap in the first place over other broadcasting backends. It's really quite powerful and useful, but we've never been able to figure out the solution to the two problems I mentioned (hot-reloading of configuration without downtime, and keeping a queue so stations can see what's playing next).

If we could figure those out...it would greatly simplify AzuraCast's role in the whole situation, which would greatly reduce the overall burden on me as a developer.

**Comment by biguenique** [comment]
@SlvrEagle23 I understand much better the constraints now. I guess the next assignment for me is to get familiar with the internal scheduler to get a better grasp of the scheduling process. Do you have any expert cue on a quick setup for diving into local development? Do you use Docker for development, or solely for deployment?

**Comment by SlvrEagle23** [comment]
@biguenique We use Docker for all local dev as well. You can find our full dev setup guide here: https://www.azuracast.com/developers/

**Comment by christiansacks** [comment]
I just installed AzuraCast using docker and I too am having this exact same issue

**Comment by samkitk** [comment]
Hey @SlvrEagle23 , any thoughts/plans on this old thread?

**Comment by donbeto97** [comment]
Hi. I proposed a workaround for this issue. [https://github.com/AzuraCast/AzuraCast/compare/master...donbeto97:patch-1](url)
I hope this could help you.
