### ISSUE TITLE
when DJ connects goes quiet for a while

### ISSUE THREAD

**Issue by djsammy629** [AzuraCast/AzuraCast#2211]
helllo 

im just wondering does anyone else have that issue where when a dj connects it goes silent for a few seconds then music comes on if there any help to this could anyone send me the link?

**Comment by jayhill90** [comment]
Hey Sammy,

Most internet radio streams will switch to silence for a few seconds before the DJ stream is fully connected. This is usually due to a delay in network stuff. The servers have to receive the audio, process it and transcode it before they can broadcast it back to the listener, this inevitably causes a delay between the streamer and the listener, ie: If I'm listening, I'm a few seconds behind what the DJ is currently playing. 

It's not really a big deal, and most internet radio streams I've DJ'd on or watched have this occur when switching between live performances and the autodj.

**Comment by djsammy629** [comment]
hey jay, 

i aware of this but on software like centova doesnt do this at all witch is werid cos it cuts of for 10 seconds then starts playing and its not good for the listeners at the end of the day

**Comment by biguenique** [comment]
This is definitely avoidable. For a technique that switches immediatly to live as soon as it's available with no silence, see my following comments on using an Icecast mountpoint as source instead of Liquidsoap's `harbour`:

- On how to set it up: https://github.com/AzuraCast/AzuraCast/issues/2228
- Some considerations on the technique + another example: https://github.com/AzuraCast/AzuraCast/issues/2228#issuecomment-567344163

I think I can remember Centova actually relying on a similar technique.

**Comment by alutus** [comment]
Howdy,

I have the same error, when a DJ connects on icecast2 with SamBroadcaster, the sound suddenly drops to 0 and then comes back up, and then it drops, what kind of bug is this?

**Comment by biguenique** [comment]
You do jump pretty fast to conclusions! Can you show me the custom code you used?

Did you try increasing the `buffer` and `max` parameters of `input.http(...)`?

Did you enable more sources to connect to your Icecast server?

> You will first need to allow more sources connected to your main Icecast server (by default AzuraCast only allows the exact number of mountpoints defined). Add the following in _Edit Profile_ > _Broadcast_ > _Custom Configuration_:
> 
> ```
> { "limits" : { "sources" : "10" } }
> ```

Did you try with another DJ client?
