### ISSUE TITLE
Song on default playlist recognize as "Live Broadcast"

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2212]
**Using Docker installation method**
Yes
**Host Operating System**
Ubuntu 18.04
v0.9.8, #dbb688d (2019-12-09 4:38) • Docker • PHP 7.4

**Describe the bug**
Strange error,
From some reason, Azuracast recognize [this song](https://we.tl/t-1ZptPrcrTH) (the attached song)  as "Live broadcast" source, (see pic -2) even though it is in the default playlist. As a result, there is no timing and no remaining time.

https://we.tl/t-1ZptPrcrTH

<img width="208" alt="‏‏1" src="https://user-images.githubusercontent.com/2701228/70569111-f312c680-1ba1-11ea-8fb4-7039d6d5683f.PNG">
<img width="697" alt="‏‏2" src="https://user-images.githubusercontent.com/2701228/70569117-f60db700-1ba1-11ea-99e5-7c51d290b312.PNG">
<img width="711" alt="‏‏3" src="https://user-images.githubusercontent.com/2701228/70569122-f9a13e00-1ba1-11ea-870b-1cc0497eb8d3.PNG">

**Comment by SlvrEagle23** [comment]
@eranwo Are you using Icecast or Shoutcast for your frontend?

I'm not sure that there is much we can do about this one in general. It happens from time to time, because in order to retrieve what song is now playing, we have to get that information directly from the frontend (i.e. Icecast), but it doesn't have the full metadata like Liquidsoap does for those same songs.

I'll take another look and see if things have changed, or if there is any more clever way around the issue on our end, and update accordingly.

**Comment by eranwo** [comment]
@SlvrEagle23 
I'm using Icecast

**Comment by eranwo** [comment]
@SlvrEagle23 I found quite a lot of files with the same issue but can't find anything in common.. Is there anything to do with it?
