### ISSUE TITLE
Plugin for Modifying liquidsoap.liq

### ISSUE THREAD

**Issue by jayhill90** [AzuraCast/AzuraCast#2228]
So I want to take a stab at enabling a feature to record live DJ performances to the local server disk, but I don't see any EventListener's around the generation of the LiquidSoap configuration file unless I'm missing it. Should this be a plugin still or would it need to go into the core app?

**Comment by jayhill90** [comment]
Would love some input on whether this is the right approach for a plugin to modify the liquidsoap configuration, and how to approach the solution.

I would need to create a new event and subscribe that event to the WriteLiquidSoapConfiguration  event class that getSubscribedEvents calls in `/src/Radio/Backend/Liquidsoap.php`  and then inside my callback function it would generate the lines needed and then write that to the actual config file. 

Maybe I'm completely off the mark here though.

**Comment by biguenique** [comment]
It would indeed be pretty cool if someone dared to develop a plugin to save the live DJ feeds.

I did look a bit a while ago into the Azuracast documentation, and came to the same conclusion as you: if I had the guts to write a plugin for that, I would hook WriteLiquidSoapConfiguration and insert the relevant code somewhere. Didn't try, though.

I rather managed to accomplish automatic recording of live shows on my server without a plugin. That might be relevant to you if you decide to pursue with plugin development.

- This example implies that the DJ connects to the Icecast server port (eg. 8000) in place of Liquidsoap's harbour port (eg. 8005), as I described here (to address a whole different issue) : https://github.com/AzuraCast/AzuraCast/issues/2064#issuecomment-543831602.
- I've been using Liquidsoap for several years and found that relying on and Icecast to proxy live sources instead of Liquidsoap harbour is much more robust and flexible, since you can use _any_ available Icecast server for that purpose.
- This example switches directly to live as soon as it is available, and right back to the main programme when it disconnects.
- But I guess you could simply use the readily available `live` source defined by Azuracast when DJs are enabled (I didn't try).

I use the following Liquidsoap code in _Edit Profile_ > _AutoDJ_ > _Custom Configuration_ of my station. Simple AGC (normalization) and compression is applied on the live stream (you might want to skip that part too).

```
# Live stream connected directly on Icecast
live_source = audio_to_stereo(id="live_source", input.http("http://localhost:8000/live", buffer=5.0, max=60.0, timeout=10.0))

# Apply normalization and compression on live stream (target = -15db + (6db/2:1) = -12db)
live_source = normalize(id="live_norm", live_source, target=-9.0, gain_min=-12.0, gain_max=12.0, k_down=0.05, k_up=0.01)
live_source = compress(id="live_comp", live_source, gain=0.0, threshold=-15.0, ratio=2.0)

# Immediately switch to live stream when available
radio = fallback(id="live_switch", track_sensitive=false, [live_source, radio])

# Can we, O, can we?
# Can we, good Lord, save live DJ streams directly?
live_strip = strip_blank(live_source, max_blank=3.0, start_blank=true, track_sensitive=false) 
ignore(live_strip)

# Dump live streams in a unique file each day
clock.assign_new(id="podcast_clock",[output.file(
 %fdkaac(channels=2, samplerate=44100, bitrate=48, afterburner=false, aot="mpeg4_he_aac_v2", sbr_mode=true),
 "/var/azuracast/stations/share/media/Public/premiere/podcast/%Y%m%d-podcast.aac",
 id="podcast",
 fallible=true,
 append=true,
 reopen_when={0h0m0s}, #every day!
 live_strip
 #live_source
)])

```

The live stream is stripped from blanks and saved in a unique file each day (audio data is appended). This actually only works well if you have a single DJ airing on the station each day, otherwise all shows will be saved in the same file. You can change this behaviour by changing the name of the output file to create a different file every hour, for instance.

Also note this technique is MUCH stabler if your host has at least 2 (v)cpus available. I ran into stability problems with only 1 vcpu. I've been running this code for recording a daily live show for more than one month now on a VPS with 2 cpus hosting 3 stations with no stability issues so far.

Good luck with that, and keep us informed if you come out with a plugin!

**Comment by jayhill90** [comment]
@biguenique I thought AzuraCast will overwrite your liquidsoap config changes is that not the case with your custom configuration? 

So your DJ's stream to a specific Icecast server which then relays to AzuraCast and then listeners connect to the AC server right? Just trying to make sure I understand how you're handling things. Thanks for the info :)

**Comment by Vaalyn** [comment]
@jayhill90 Regarding overwriting the liquidsoap configuration changes. If you put custom code into the input field at `Edit Profile` > `AutoDJ` > `Custom Configuration` AzuraCast will automatically include that in the final liquidsoap.liq so it.

There is also a feature request to add this to the core application where you can also find a small snippet that the poster used to record the live stream: https://features.azuracast.com/suggestions/38931/automatically-record-live-dj-streams

**Comment by biguenique** [comment]
@jayhill90 Yes, instead of relying on `input.harbor()`, I make the DJ connect to some (private) mountpoint on an Icecast server, and then Liquidsoap can relay that stream with `input.http()` (first line of my example above).

I found that Icecast is much more stable than Liquidsoap to handle incoming streams. It also allows you to use _any_ reachable Icecast server -- allowing eg. to run your Liquidsoap station on a different machine, perhaps a local machine that is not publicly exposed to the Internet. That's why I described the technique as more _robust_ and _flexible_.

But your initial question is _not_ about this specific issue, but about saving an incoming live DJ stream on disc. The example pointed out by @Vaalyn confirms that you can simply use the readily available _live_ stream to disc. Here's the example code that you can add in Custom Configuration:

> `output.file(%vorbis, "stream %H:%M:%S.ogg",fallible=true,reopen_when={0m0s}, on_stop=shutdown,live)
`

You might want to start by playing around with that code. I'm not sure what `on_stop=shutdown` is meant to do here... According to [Liquidsoap's API Reference for `output.file`](url), `on_stop` should be a _Callback executed when outputting stops_, so unless you have a `shutdown` function defined in your script (and you want it called), you can get rid of that argument.

**Comment by biguenique** [comment]
@jayhill90 See the original discussion about recording live DJs: https://github.com/AzuraCast/AzuraCast/issues/934

**Comment by SlvrEagle23** [comment]
Just as a note for anyone wanting to write a plugin to accomplish this: you are absolutely on the right path with hooking into the event dispatcher and listening for the `WriteLiquidsoapConfiguration` event. This event was created so that we could split the LS configuration generation into multiple steps, and so that any plugin could inject itself anywhere in that process (or entirely before or after it) and include its own code exactly as we do in `src/Radio/Backend/Liquidsoap.php`.

**Comment by jayhill90** [comment]
Thanks for the confirmation @SlvrEagle23

**Comment by jayhill90** [comment]
@SlvrEagle23 is there a way to modify the PHP.ini so that I can enable error logging or reporting when I'm causing 500 errors?

**Comment by SlvrEagle23** [comment]
@jayhill90 Easiest way is to probably set the `APPLICATION_ENV` environment variable to `development`, which will enable full debug display in a really nice format.

**Comment by jayhill90** [comment]
Broadcast streaming and recording of live streams is in Master. Guess we don't need the plugin now :) Thanks @SlvrEagle23

**Comment by ttodua** [comment]
I wrote the plugin for azuracast for hooking into liquidsoap config creation, if someone interested still that function looked like:


```
function setProperty($obj, $property, $value) {
	$reflection = new \ReflectionClass($obj);
	$property = $reflection->getProperty($property);
	$property->setAccessible(true);
	return $property->setValue($obj, $value);
}

...
$dispatcher->addListener(Event\Radio\WriteLiquidsoapConfiguration::class, function(Event\Radio\WriteLiquidsoapConfiguration $event) {
    $existing_config = $event->buildConfiguration();
    $new_content = str_replace("AAA", "BBB", $existing_config);
    $new_config = explode("\n", $new_content);
    setProperty($event, 'configLines', $new_config);
});

```

then you will need to save & restart from `Edit Liquidsoap configuration` page.
