### ISSUE TITLE
Shoutcast v2 with multiple SIDs 

### ISSUE THREAD

**Issue by kbysfm** [AzuraCast/AzuraCast#223]
@SlvrEagle23 I decided to start from scratch and try the docker version of AzuraCast. For some reason when adding an external shoutcast v2 server I noticed that http://serverip:port/index.html?sid=2 and http://serverip:port/index.html?sid=3 do not show stats or play music. 

The base url http://serverip:port works, displays listeners, metadata and plays music.

I noticed this behavior back in February - issue #83 

Thanks for hard work!

**Comment by SlvrEagle23** [comment]
@kbysfm I have worked to rewrite the Remote option for AzuraCast syndication, so you can now not only syndicate multiple streams in a single station, but also broadcast out from the on-server LiquidSoap instance to a remote server.

The new format asks for an SID or mount point for each stream you want to syndicate, including (if you don't use the mount points and just use a single remote URL, like before) the main one in the station profile.

Since this is a full rewrite of this functionality, it may introduce new bugs, but those can be reported as new bugs. For now I'm closing this one as resolved.
