### ISSUE TITLE
Which is the maximum number of files AzuraCast supports per folder?

### ISSUE THREAD

**Issue by radio2019** [AzuraCast/AzuraCast#2233]
Is the number limited to 5000?
Can it be increased?

**Comment by SlvrEagle23** [comment]
@radio2019 There is no hard limit established for the number of files an individual folder can contain, but because entering a folder requires iterating through all of the files in that directory at least once (subsequent requests are cached for faster performance), it's recommended to limit the size of each folder and not just dump your entire music collection into a single giant one.
