### ISSUE TITLE
Icecast server doesn't stop

### ISSUE THREAD

**Issue by radio2019** [AzuraCast/AzuraCast#2236]
How can it be that Icecast doesn't stop working, although all stations have been deleted.
It's even impossible for me to open up a new station.

When I want to start the broadcasting service I get this error message:

> 
> [2019-12-25 14:14:02] WARN xml/parsing warning:
> [2019-12-25 14:14:02] WARN xml/parsing skipping element "stream-description" parsing "mount" at line 27
> [2019-12-25 14:14:06] WARN xml/parsing warning:
> [2019-12-25 14:14:06] WARN xml/parsing skipping element "stream-description" parsing "mount" at line 27
> [2019-12-25 14:14:08] WARN xml/parsing warning:
> [2019-12-25 14:14:08] WARN xml/parsing skipping element "stream-description" parsing "mount" at line 27

And when I start Liquidsoap I get this:

> [frame:3] Targetting 'frame.duration': 0.04s = 1764 audio samples = 1764 ticks.
> 2019/12/25 14:14:47 [frame:3] Frames last 0.04s = 1764 audio samples = 1 video samples = 1764 ticks.
> 2019/12/25 14:14:47 [decoder:3] Method "MAD" accepted "/usr/local/share/icecast/web/error.mp3".
> 2019/12/25 14:14:47 [sandbox:3] Running inside a docker container, disabling sandboxing..
> init: exception encountered during start phase:
> Error while trying to bind server/telnet socket: Address already in use in bind()

I like freeware, but if it's so full of bugs I should better change to CentovaCast :-/

**Comment by SC2Mitch** [comment]
> When I want to start the broadcasting service I get this error message:

Those aren't error messages. Mere warnings that it's skipping something. 

Have you done any of the following
Restarted the server / VPS
Using SSL / HTTPS? 

> I like freeware, but if it's so full of bugs I should better change to CentovaCast :-/

This comment isn't needed at all, the developers here are working on their own time for donations from the public. It's not buggy, it's just a error that sometimes happens for people,

**Comment by SlvrEagle23** [comment]
This seems related to issue #1674, a long-running issue with Icecast in particular not freeing up ports after its process was terminated. May merit further investigation.

> I like freeware, but if it's so full of bugs I should better change to CentovaCast :-/

As a general rule of thumb @radio2019, it's pretty pointless to threaten free and open-source software maker with "taking your business elsewhere" to a closed-source, commercial competitor. Unless you donate to support our development, there is no financial incentive we have to support you at all; to the contrary, the time we spend developing and supporting AzuraCast is actually _taking away_ from the time we could be spending on other more profitable things, yet we do it anyway as a labor of love.

I understand that for lots of our users, this may be their first experience using and interacting with free and open-source software. I would advise those people to avoid the tendency to treat us like you would treat a large faceless corporate entity, because we aren't that. This project isn't even a large team of people; if you look at [the charts](https://github.com/AzuraCast/AzuraCast/graphs/contributors) you'll see just how much of the project is done by one person.

In the end, if you don't like it and want to move to CentovaCast, we wish you the best and hope you find a tool you enjoy. Just please don't preface your interactions with us in such an unfriendly manner.

**Comment by radio2019** [comment]
It wasn’t my intention to sound harsh in any way. 
Believe me: We've spend hours to fix this problem and only a complete new installation of AzuraCast worked (hopefully in a long run).
I know that freeware often has more bugs than commercial software, but in the end it didn't work at all: We haven't even been able to start the AutoDJ or the broadcasting service and only received the messages shown above.
That was simply frustrating.
