### ISSUE TITLE
Add ability to update now-playing data via API

### ISSUE THREAD

**Issue by smilingpeanut** [AzuraCast/AzuraCast#2249]
Related: #2223 .

### Issue:
A good majority of broadcasting software (at least on macOS) does not support sending full track metadata to Icecast because Icecast uses a single string for metadata. Full metadata (including track album, and either the ISRC OR label and year) is needed to generate accurate SoundExchange royalty reports. AzuraCast supports collecting this metadata but the data can only be sent by the broadcasting software.

### Proposal: 
Add GET endpoint to the AzuraCast API for updating the now-playing metadata via automation systems. Example request:

> https://hostname.tld/api/station/1/update_now_playing?title=Title&artist=Artist&album=Album&year=2019&label=Whatever%20Records

This issue exists to track progress of this feature.

**Comment by SlvrEagle23** [comment]
@smilingpeanut I've implemented this feature as of the latest update, so you can now update metadata via a programmatic endpoint.

The endpoint's URL is:
```
http://your-azuracast-install/api/station/(station_id)/nowplaying
```

This endpoint is excessively permissive since it's being used by automated software where you likely can't control the full nature of the request being submitted, so requests are accepted using either `GET` or `POST` HTTP methods.

You can, either via query string or POST form parameters, update the following metadata: 'title', 'artist', 'duration', 'song_id', 'media_id', 'liq_amplify', 'liq_cross_duration', 'liq_fade_in', 'liq_fade_out', 'liq_cue_in', 'liq_cue_out'.

You can also append the API key itself via a query parameter or form parameter named `api-key`. The user who executes this request must have the "Manage Station Broadcasting" permission, since it's able to basically control the entire metadata output of the station.
