### ISSUE TITLE
Unable to download MaxMind GeoIP Database

### ISSUE THREAD

**Issue by emeraldau** [AzuraCast/AzuraCast#2250]
**Using Docker installation method**
No

**Host Operating System**
Ubuntu 16.04

**Describe the bug**
Unable to continue the installer, with error message stating that the MaxMind GeoIP Database Cannot be Downloaded! When you visit the url which is stated it's trying to download, it presents as a 404! Please help!

![3c7d830c9ba574c687af615c62fe2d24](https://user-images.githubusercontent.com/34394420/71608963-c5390480-2bd8-11ea-9b95-e0520fb6272f.png)

**Comment by SlvrEagle23** [comment]
@emeraldau I looked into why this might be happening, only to stumble upon a notice from 12 days ago from MaxMind that they are discontinuing unauthenticated public access to their free GeoLite IP geolocation collection: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

My project (and countless others) depend on that public feed in order to provide approximate IP geolocation capabilities in our software; in AzuraCast's case, we use that to generate the Listeners report, complete with the interactive map view, showing where listeners are tuned in from around the world. This is a _very_ important report that is heavily used by our station managers.

We are actively looking into alternatives for this situation. For now, be aware that our Docker installation is unaffected by this, as it has an older copy of the database still preloaded inside of it (and will continue to for the indefinite future as we work to resolve this issue).

The immediate stopgap solution may be for us to disable this functionality entirely on Ansible installations that don't already have the database downloaded. Our medium-term solution may be to allow users to download a copy themselves from the MaxMind site, in a similar manner to how we do SHOUTcast DNAS installation.

**Comment by SlvrEagle23** [comment]
@emeraldau Fortunately, I was able to get this updated and fixed a little faster than I expected, so now the system has been updated to handle this new situation in a different way:

 - Neither the Ansible nor Docker installations will come with the GeoLite IP geolocation database shipped directly within them,
 - The system will function just fine without the database ever being downloaded, including the Listener report, which will just show an error message on the "Location" field noting that the location can't be retrieved without that database being installed,
 - A new "Install GeoLite IP Database" option has been created and added to the System Administration panel. Just like "Install SHOUTcast 2", it is only available to global system administrators for each installation. The page includes instructions for how to sign up for an account with MaxMind, where to find the downloads, and which download to use. You then attach the .tar.gz file to the form and upload it any time you want to update the database file.

This set of changes will bring both our Ansible and Docker installations fully into compliance with MaxMind's new policies. This will also let us better handle future changes, since the process will remain the same regardless of how MaxMind makes the files available to authenticated users.

Sorry for the inconvenience caused by this abrupt change; the fact that MaxMind rather quietly announced this change with only 12 days' notice (where those 12 days included Christmas) was out of our control and admittedly frustrating to us. However, this should remove any negative effects caused to AzuraCast by the changes.
