### ISSUE TITLE
Opening the nginx demo page after installation

### ISSUE THREAD

**Issue by dougllasvieira** [AzuraCast/AzuraCast#2251]
Hello, today I tried to install by ansible method on ubuntu 18.04 and when finishing when you access the ip or url it opens the default nginx page. I reinstalled my vps reinstalled and it happened again.
thank's for your time.

**Comment by SlvrEagle23** [comment]
@dougllasvieira Did you encounter any errors during the installation process?

Since the Ansible installation operates within an existing Ubuntu installation and not in its own sandboxed instance (as Docker does), it's possible that other configuration files could be present that override the ones we install. We try to prevent this, but we can't account for every possible configuration combination out there. That's part of why we strongly recommend the Docker installation, as it lets us provide prebuilt images that are configured exactly as we need them to be.

**Comment by dougllasvieira** [comment]
@SlvrEagle23 Hello, 
Didn't present any errors, which was strange.
But I just tried again and it's working now. 
But I didn't run the **sudo apt-get update** command _this time_, just these:
sudo apt-get install -q -y git
sudo mkdir -p /var/azuracast/www 
cd /var/azuracast/www 
sudo git clone https://github.com/AzuraCast/AzuraCast.git . 
 
sudo chmod a+x install.sh 
./install.sh
Thanks for the time.

**Comment by SlvrEagle23** [comment]
@dougllasvieira Glad it was fixed. It's possible that just restarting nginx is what fixed it too.
