### ISSUE TITLE
Any chance for several stations to use one Icecast server

### ISSUE THREAD

**Issue by radio2019** [AzuraCast/AzuraCast#2256]
Is there any chance to add several stations run by AzuraCast to one Icecast server?
Whenever I want to do that I get a "port already in use" message.

Sorry for asking so many questions.

**Comment by biguenique** [comment]
@radio2019 You can:
1. Disable Icecast on all stations but one (select _Broadcasting_ > _Connect to a remote radio server_)
2. Increase the allowed number of source on your main Icecast (add eg. `{ "limits" : { "sources" : "10" } }` in _Broadcast_ > _Custom Configuration_ for that station)
3. Add _Remote Relays_ (instead of _Mountpoints_) on other stations to _Broadcast AutoDJ to Remote Station_

I quickly tried to do exactly what you want, and it kinda worked but it didn't play very well with the AzuraCast public player, and it didn't feel it was worth it. Maybe someone could try harder. And you might just happen to be that person.

It would be interesting to know why you do need this?
