### ISSUE TITLE
AutoDJ Custom Config 

### ISSUE THREAD

**Issue by vamaresh** [AzuraCast/AzuraCast#2257]
Hi,

I'm new to use the Azuracast and finding my ways on doing it.
I have been going to docs and other links to reading the usage/settings etc.

I want to set the set the stream title to a constant value rather than showing the details of the artist/song. How can I do it.
I tried reading the liquidsoap documentation and some the info from here but still not clear on how to use the AutoDJ -> Advance Config to set custom value in liquidsoap.

I tried putting
set("title","English Radio Station") 
and 
{"title","English Radio Station"}

But no use. 

Please can you help me !
I want the station name to be displayed rather than the artist/song.

I also tried updating the playlist to not to send the Metadata which assigned itself as Jingles..Still no use - the album and artist data was sent.

Thanks very much.

**Comment by SlvrEagle23** [comment]
@vamaresh The Advanced configuration field allows you to directly insert custom configuration into Liquidsoap's main `.liq` configuration file for the station. Your code should be valid Liquidsoap code in order to be added there.

You can ask the Liquidsoap community for help with how to solve your specific problem (there are hundreds of example scripts out there that may also already solve the problem) or possibly one of the AzuraCast community members can help you out. I'll leave the issue open so folks can see it.

**Comment by biguenique** [comment]
@vamaresh Tested and working:
```
# Metadata override
def override_metadata(m) =
 [("title","Text replacing song title"),("artist","Text replacing song artist")]
end
radio = map_metadata(override_metadata, radio)
```

**Comment by vamaresh** [comment]
Thanks very much that worked.
