### ISSUE TITLE
Can't upload music files in the browser nor FTP

### ISSUE THREAD

**Issue by sevospl** [AzuraCast/AzuraCast#2264]
**Using Docker installation method** Yes
**Host Operating System** Alpine Linux

I think these screenshots are more than enough to describe the issue:

![image](https://user-images.githubusercontent.com/15851064/71767192-f0d62a80-2f09-11ea-994e-5f766062b1bb.png)

![image](https://user-images.githubusercontent.com/15851064/71767205-12cfad00-2f0a-11ea-995d-a36716d151ed.png)

**Comment by sevospl** [comment]
When it comes to web upload, the problem was "413 Request Entity Too Large" - I had to increase `client_max_body_size` in Nginx configuration (my reverse proxy). Now it s ok. Still trying to fix the FTP problem tho.

**Comment by sevospl** [comment]
This issue is not at all related to AzuraCast, it's all due to my NAT forwarding for FTP, so I'm going to close this issue.

**Comment by SlvrEagle23** [comment]
User contacted me directly on Telegram (note: please do not contact me on Telegram) and flooded me with messages about the problem. Their setup is unusually complex, involving NAT forwarding and custom iptables rules for handling passive FTP into their VM. This is not officially supported in any capacity by AzuraCast.

After explaining this, the user responded that because I wasn't willing to help them with their specific problem, that I was clearly "not a sysadmin, just dev, doing dev things" and was "not familiar with Linux".

Do not be this user. Do not do any of those things, either directly messaging me via personal social media platforms I don't use for providing support, or insulting my intellectual capacity as a developer.

I have zero tolerance for developer abuse like that here.
