### ISSUE TITLE
Geolite ip database too large

### ISSUE THREAD

**Issue by StringSurfer** [AzuraCast/AzuraCast#2266]
Hi there.
Due to the geolite from maxmind being a manual install, I`ve run into an issue.
I seem to get the error "413 Request Entity To Large"The Database itself is 65 megabytes, and I`ve altered the aura cast.env to accept file size, and memorylimit to 256 megabytes, and rebooted the server, still no luck.
Anyone knows what I`m doing wrong here?
Running Centos 8, and the Docker.

**Comment by SlvrEagle23** [comment]
@StringSurfer You might not be downloading the right database. The one we want is the `City` one, which is about 28MB in size. They're both on the same page so the confusion is understandable.

**Comment by StringSurfer** [comment]
Thanks for clarifying, but the Geolite2-City at my download page is 64 mb, and was updated 2020-01-07.
So if I want this thing installed, I have to enlarge the file upload size somewhere.
There are no downloads smaller than 64 mb at that page in gzip format.
The three downloads are GeoLite2-City, GeoLite2-Country, and Geolite2-ASN.

**Comment by lalafunn** [comment]
I cannot signup with Maxmind. 
Could anyone send me a link to download Geolite2-City file?

**Comment by StringSurfer** [comment]
> I cannot signup with Maxmind.
> Could anyone send me a link to download Geolite2-City file?

You actually have to register, as you cannot download the file anonymous.

**Comment by lalafunn** [comment]
I am not able to register an account. I get error message:
Sorry, we are not able to provide you with an account.

If somebody could share the file, I would appreciate.

**Comment by SlvrEagle23** [comment]
As of today, rather than requiring you to upload the entire GeoLite database yourself, we now just ask that you input a license key (generated from MaxMind's site once you register an account), after which we will automatically download and extract the proper copy of the GeoLite database and keep it up to date for you. This should remove any issues with the file sizes being too large, downloads varying between users from different locations, etc.

**Comment by StringSurfer** [comment]
Ah, this sounds great. Thanks for the update :-)
