### ISSUE TITLE
Unable to disable or enable playlists on direct IP

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2282]
**Using Docker installation method**

Yes
**Host Operating System**

Ubuntu 18.4
**Describe the bug**

Unable to disable or enable playlists when you use the direct IP. If you're using the website (Should you have one configured) it works. (It runs into a Authentication error) 
**To Reproduce**

Use your direct IP and attempt to disable / enable playlists
**Expected behavior**

To enable and disable playlists regardless. 
**Relevant Logs**

Check Screenshots, lots of console related errors. 
**Screenshots**

Console Errors: https://puu.sh/EZ7tu/e436168049.png | https://puu.sh/EZ7iQ/4e94dfb4bf.png
**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 
WIN 10, Chrome, latest versions. 
**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch This may be because you're serving the web site over port 8080.

You're saying if you visit `domainname.com:8080` it works fine, but if you visit `ip:8080` it doesn't?

Which one is set as the base URL? If you want to be able to access both easily, you can also enable the "Prefer Browser URL" setting, which will override the base URL with whatever URL you accessed the site with; this is very commonly the desired setting, so newer versions of AzuraCast enable this by default with new setups.

**Comment by SC2Mitch** [comment]
> You're saying if you visit domainname.com:8080 it works fine, but if you visit ip:8080 it doesn't?

Correct, 

> Which one is set as the base URL?

We're using subdomain.domain.com:8080 for base. 
![image](https://user-images.githubusercontent.com/29955942/72224771-e7863700-3575-11ea-9725-b434a04f3d25.png)

**Comment by SC2Mitch** [comment]
After trying your recommendation 

> Prefer Browser URL" setting

This appears to make it work properly.

**Comment by SlvrEagle23** [comment]
@SC2Mitch Yep, having that off was the cause of a bunch of problems, which is why we turn it on automatically on new installations. It's rare that people prefer to force everyone over onto a single URL if they have multiples, but I leave the option there in case that's what they want to do. Glad that was able to fix it.
