### ISSUE TITLE
SFTP errors when trying to access the page, returns cURL errors

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2287]
**Using Docker installation method**

Yes
**Host Operating System**

Ubuntu 18.4 
**Describe the bug**

I'm unable to access our SFTP user page. subdomain.domain.com/station/%/sftp_users
**To Reproduce**

Go directly to any sftp_user page and see the error
**Expected behavior**

To see the page and not the error 
**Relevant Logs**

500, cURL Error 28: Resolving timeout after 3513 milliseconds. CurlFactory.php: 200 
**Screenshots**

![image](https://user-images.githubusercontent.com/29955942/72267964-d9d5bd80-3618-11ea-9cc3-38e75b2d0eb1.png)

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch That's probably caused by your container being unable to resolve `central.azuracast.com` for external IP resolution. This resolution isn't particularly necessary if you already know your server's outward-facing IP, but it can be helpful in a lot of situations.

Let me see if I can make that a little more resilient to errors.

**Comment by SlvrEagle23** [comment]
I've modified how AzuraCast Central handles errors; now it will simply log them as minor errors and carry on as normal, instead of completely halting page execution. You won't see the separate "or you can connect to an IP" section on that page, but otherwise it'll work fine.
