### ISSUE TITLE
FTP/SFTP

### ISSUE THREAD

**Issue by Radio-Quergedacht** [AzuraCast/AzuraCast#2310]
Why is uploading via FTP no longer possible via SFTP Is bullshit and does not work very well I do not come with SFTP on the server To upload music

**Comment by webma5ter23** [comment]
Hi

for Docker installation? check https://www.azuracast.com/help/faq_docker.html#access-files-via-sftp

**Comment by SlvrEagle23** [comment]
@Radio-Quergedacht Please don't use that kind of language or tone when interacting with our team. Per our code of conduct, you should always remain professional in your interactions.

We had a number of very valid technical reasons to switch from FTP to SFTP, namely:
- FTP's passive connections require a huge range of IP addresses to be open and forwarded,
- Passive connections with FTP require that the server supply its own external IP address, which a Docker container can't do accurately, leading to a number of problems,
- Because of a lack of atomic writes, several stations had reported problems with files only partially uploading and then being processed, causing unreliability in upload integrity (this is fixed in our SFTP client), and
- SFTP is based on the more actively supported and widespread SSH protocol which not only requires a single port to be open for any number of connections, but also supports public key authentication for power users.
