### ISSUE TITLE
Next song functionality

### ISSUE THREAD

**Issue by dougllasvieira** [AzuraCast/AzuraCast#2313]
Hello
I noticed that the next song functionality is not always present after activating the "jingle mode". 
![azura2playlist](https://user-images.githubusercontent.com/49848275/72761784-db285c80-3bbb-11ea-96ec-cd372ea9d099.JPG)
is there any way to show the next one without being the next jingle? In this case, liquid soap should ignore the jingles but still show the next song.

![azura](https://user-images.githubusercontent.com/49848275/72761702-943a6700-3bbb-11ea-871d-f649614b0faf.JPG)

Thank you for time and your project.
v0.9.8, #c8110fc (2020-01-02 13:26) • Ansible • PHP 7.4

**Comment by Richard399** [comment]
Hi,

I see you're still waiting for a response and since I'm using the system thought to try and help during my 'earning curve'.

If your setting you playlists as 'sequential' this will not show the jingle mode in your dashboard when checking 'Hide Meta Data'.  Change to 'Random' or 'Shuffle' where you will then see the 'cueing' of Jingles in the dashboard but the listener will not see it.

Hope that made sense :-)

**Comment by dougllasvieira** [comment]
Up
