### ISSUE TITLE
Not able to get album info/artwork with KAST player on HTTPS website.

### ISSUE THREAD

**Issue by calegendre** [AzuraCast/AzuraCast#2314]
Depending on how I put host in or use DirectStreamURL option — I can get it to play from my port 8000 azuracast Shoutcast station, but I cannot get it to load the album information/artist info/artwork - just comes up as Unknown on my site, which is behind HTTPS as I’ve been moving all my sites for security purposes. 

All the information about KAST including its list of options are available here: https://codecanyon.net/item/kast-extraordinary-shoutcast-html5-radio-player-for-jquery-material-design/14396614 (scroll down to “Options” and it shows all the bits you can add to its config....

I hope someone is able to help as I would love to move away from CentovaCast and happily switch to AzuraCast which I do think is the future! Thank you!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SlvrEagle23** [comment]
@calegendre Have you tried contacting the manufacturer of the Kast plugin for support with your specific situation?

Given the plugin is over a hundred bucks, surely they would be providing some degree of support for this plugin; since we're volunteers by comparison I would argue the onus is definitely on them to help resolve the issue.

**Comment by calegendre** [comment]
@SlvrEagle23 They’re finicky, and to be honest, rude. The plugin was not always that expensive — they did raise the price and cut the length of support because they’re the type of developers that don’t like dealing with people.

**Comment by SlvrEagle23** [comment]
@calegendre If it were possible for the Kast plugin to use the nginx proxied version of the SHOUTcast broadcast (i.e. via our `/radio/8000/radio.mp3` style proxy that uses the web ports), that would resolve the HTTPS issue, but given the fact that each of those variables is separate, I'm not sure how you'd input that, and since I don't have the plugin myself it's difficult to test.

I do know that there are other station operators who have used that exact same plugin before, with AzuraCast, with success, so I'm hoping one of them can stumble upon this thread and provide some extra insight.

**Comment by calegendre** [comment]
I am sure hoping so as well and appreciate all the help and just willingness to communicate. If I have to use a player I do not care for as much or that doesn’t fit 100% properly in the place on the site for the time being, I will, but my end hope is to be able to return to the one that is nicely integrated and been tweaked to fit where it needs to go!
