### ISSUE TITLE
Error Space limit sftp

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#2315]
Hello,
Azuracast has a space limit, however when it reaches the limit it does not block by sftp.
Through the file manager on the panel you are unable to, connect via sftp and send azuracast does not block new space-based uploads. This problem only happens through sftp.

![Screenshot_1](https://user-images.githubusercontent.com/48635610/72857683-27979900-3c9d-11ea-8ecd-bfb02a82d3a3.png)

**Comment by SlvrEagle23** [comment]
@Marcioghiraldelli We now enforce station quotas for every SFTP user created for the station.

**Comment by aconitumnapellus** [comment]
This change is a bit unfortunate, because now it blocks any SFTP uploads when the docker drive is full / close to full, even when uploading to another drive with enough space.

**Comment by SlvrEagle23** [comment]
@aconitumnapellus If you mount the entire `/var/azuracast/stations` directory to a separate drive, it should still be properly registering the amount of free space on the other drive, rather than the free space on the Docker drive.

**Comment by aconitumnapellus** [comment]
> @aconitumnapellus If you mount the entire `/var/azuracast/stations` directory to a separate drive, it should still be properly registering the amount of free space on the other drive, rather than the free space on the Docker drive.

In the documention (https://www.azuracast.com/help/docker/#mounting-a-directory-into-a-station) it is mentioned to mount directories on seperate stations.
now, imagine a structure like this:

/media (on rootdisk like /bin /var, etc. has 2GB remaining)
/media/storage1 (FUSE mount with music on it, has 300GB remaining)
/media/storage2 (FUSE mount with music on it, has 300GB remaining)

/media/storage1 and /media/storage2 are not allowed to contain configuration data, only media.

mounted like this:

volumes:            
      - /media/storage1:/var/azuracast/stations/radio/media/storage1
      - /media/storage1:/var/azuracast/stations/radio/media/storage2

Theres an administration option for specify the quota, but thats not really what i need (Im talking about "Storage Quota" in the Station settings).
Theres also another option for manually specifying the media directory (Advanced Custom Media Directory), but that also does nothing because if even i would mount /media to /var/azuracast/stations/radio/media, it would still detect the hosts rootdisk remaining space, which would be wrong too.

Ideally, azuracast would detect the remaining space of each media folder mounted in the /var/azuracast/stations/radio/media directory, but that approach seems not a good idea.

I think, as a workaround, it should be sufficient to create another disk with like 10GB and mount /var/azuracast/stations on it to fool azuracast into thinking it has enough space so im able to upload stuff onto the FUSE mounts, which is basically what you recommended already, but i thought i should share my thought process and setup.
