### ISSUE TITLE
Ability to enable or hide a station of API results

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#236]
When I am about to launch or test a station, I would like it not to be listed in the API results (at least  /nowplaying and /stations ), as these are queried by my front office interface.

Same as the 'enable public page' switch, I would like to have a 'enable API' switch.

**Comment by SlvrEagle23** [comment]
@griffon56 Rather than add another switch that does something largely similar to the "Is Public" switch, I've just updated the system so that the API calls that return lists of all available stations (`/nowplaying` and `/stations`) won't return non-public stations in those lists. You can still directly get the station's API data by using the per-station lookup, but people looking for all stations on the server won't see them.

Hopefully this is sufficient to avoid unwanted exposure of the stations in question without affecting legitimate use of the API in your own applications.
