### ISSUE TITLE
Clone Station Many Times - After Latest Update

### ISSUE THREAD

**Issue by reans** [AzuraCast/AzuraCast#2360]
**Using Docker installation method**

NO

**Host Operating System**

Ubuntu 16.04 LTS

**Describe the bug**

After i update my azuracast this latest update the list of my station clone many times.  I tried to update again become more copy of station in the list. 

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

this is what happen after i update my azuracast installation. 

![image](https://user-images.githubusercontent.com/27730047/73422211-2c2a1480-4363-11ea-8444-79809c137982.png)

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by psduk1** [comment]
I have the same issue after running latest update to fix the sftp issues.

**Comment by miguelacjardim** [comment]
Same issue. keeps duplicating stations every 5 minutes 
Ubuntu 18-04 LTS
Docker Installation

**Comment by SC2Mitch** [comment]
Yeah this bricked our whole azuracast install, we had to roll back our VPS

**Comment by SC2Mitch** [comment]
Same on our instance, we had to roll back.

**Comment by SlvrEagle23** [comment]
@reans @psduk1 @SC2Mitch @miguelacjardim Thank you for the reports, and I'm very sorry for the inconvenience caused by the duplication of your stations.

This was caused by an odd quirk in our object relational manager (ORM); in order to make more efficient memory usage when processing thousands of records (as we do with media every 5 minutes), it clears the memory at the end of each station's processing. It was incorrectly then thinking that the next station it saw was a _new_ station and adding it to the database.

I admit I would've gotten to this issue faster if the subject hadn't suggested the problem was specifically with the "Clone Station" feature (something very few people use) and not "we have 40 copies of every station now and we didn't do anything". :P

I just pushed a release that should fix the issue; if you've updated in the last 24 hours it is strongly recommended that you update again.
