### ISSUE TITLE
Songs with unique/foreign characters break the Files page, resulting in infinitely loading pages and multiple errors

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#2385]
**Using Docker installation method**
Yes 
**Host Operating System**
CentOS7
**Describe the bug**
If a song has a unique character, such as an emoji or anything else AzuraCast cannot recognise, it'll result in a number of cascading errors across Azuracast, including errors in the logs, files and playlists. This file does indeed exist within our SFTP server, but the server refuses to recognize it. 
**To Reproduce**
Upload a song with a unique character, attempt to open your Files. 
**Expected behavior**
The song to be allowed, regardless of the broken character and Files to load accordingly. 

**Relevant Logs**
web_1       | [2020-02-05T01:45:02.032492+00:00] AzuraCast.ERROR: Exception when processing message type App\Message\AddNewMediaMessage: Media path "media://Mixed/600-800/81. Nio Garcia - Te Bot▒.mp3" not found. [] []

**Screenshots**
Video: https://streamable.com/wyp96
**Device(s):**
Desktop, win 10, Chrome, latest
**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch This isn't true of all Unicode characters...when you say "Unique" character are you referring to the `▒` character?

I'm not sure what kind of character that is. It's not one that's typically included in file paths.

You may need to manually delete that file from your system in order to restore normal operation of the system. From the host, you can run:
```
docker-compose exec --user=azuracast web bash
```
and then, within that container, delete the file as you would any standard Linux file (it'll be in `/var/azuracast/stations`).

**Comment by mikedorst** [comment]
Deleted the song, can access the media files again.

**Comment by SC2Mitch** [comment]
@SlvrEagle23 I believe that kind of character was a Emoji or something similar which threw Azura off? But this problem is resolved now.
