### ISSUE TITLE
Duplicate Songs not deleting the songs

### ISSUE THREAD

**Issue by mikedorst** [AzuraCast/AzuraCast#2396]
**Using Docker installation method**
Yes

**Host Operating System**
CentOS 7

**Describe the bug**
I've been trying to delete songs through the "Song Duplicates" page, however whenever the 5 minute sync runs the songs reappear into the list as they appear not to been deleted.

**To Reproduce**
1. Add a few duplicates songs.
2. Go to your station -> Reports -> Duplicated Songs
3. Delete a few duplicates.
4. Wait for the 5 minute sync (or manually run it)
5. Refresh the duplicated songs page

**Expected behavior**
Songs should be deleted.

**Relevant Logs**
Nothing gets pasted into the logs when you delete a song.

**Device(s):**
 - Device: Computer 
 - OS: Windows 10
 - Browser: Google  Chrome
 - Version: Version 79.0.3945.130 (Official Build) (64-bit)

**Comment by F-luxus** [comment]
I noticed the same problem with AzuraCast on docker. But in my case songs are not deleting from anywhere. I can see notification about deleted song, but when I log in to FTP all song still in folders and need to delete again directly from FTP client.

**Comment by SlvrEagle23** [comment]
@mikedorst I'm actually having trouble reproducing this locally...any files I delete locally remain deleted, and subsequent synchronizations don't have any effect on whether they're deleted or not.

I have no idea what would be causing this, especially since I can confirm that all of the relevant code lines are actually deleting files directly from the filesystem.

I wonder if this has something to do with CentOS as the host operating system, since we don't directly test with CentOS in our own development environments.

**Comment by mikedorst** [comment]
@SlvrEagle23 I've managed to figure out the issue, it actually isn't a bug, its just me being silly. I have root access to the server as I'm hosting it and I've uploaded all my songs and created all my folders under the root user. Azuracast has no permissions to delete the songs owned by root. I changed all my songs and folders away from root and now it works fine.
