### ISSUE TITLE
Error uploading files via SFTP

### ISSUE THREAD

**Issue by TrevorRoberts** [AzuraCast/AzuraCast#2423]
Hi Guys,

I recently installed AzuraCast on my server and was notified of an update the next day. After updating I just had a blank screen, so I re-installed from scratch.

Unfortunately, since the upgrade to the latest version, there is a problem with uploading files by SFTP. The files seem to upload okay, but in the music library an error is displayed for each file and the files do not play.

**Comment by SC2Mitch** [comment]
What error is displayed? And are your logs reporting back any errors? `docker-compose logs -f` (docker)

**Comment by TrevorRoberts** [comment]
Hi,

Is says something about the file not being processed. Here is some of the output from the log. 

[docker-log.txt](https://github.com/AzuraCast/AzuraCast/files/4219449/docker-log.txt)

**Comment by SC2Mitch** [comment]
@TrevorRoberts 

I'm seeing that you're having 
`redis_1     | 1:M 14 Feb 2020 07:20:51.082 * Asynchronous AOF fsync is taking too long (disk is busy?). Writing the AOF buffer without waiting for fsync to complete, this may slow down Redis.
`
This is because your VPS IO is being slammed by heavy usage and may cause obvious slow downs, can you check to see if it's calmed down and re-attempt FTP?
