### ISSUE TITLE
Watcher have high usage of CPU

### ISSUE THREAD

**Issue by ruLait** [AzuraCast/AzuraCast#244]
Specs of server: One core from Xeon E5-2630 (2.2 GHz), 512 MB of RAM.
I’ve installed clean Ubuntu 17.04, then git and AzuraCast via Docker.
Created three radio stations, each has one mount with 128 KB/s bitrate.

And all of it uses less CPU than AzuraCast's statistics updater (as I understand).
![](https://i.imgur.com/7HpMqCT.png)

**Comment by SlvrEagle23** [comment]
@ruLait I have been able to reproduce this on my local instances, specifically with newly created stations that don't have any music in their playlists yet. There was an error in both the python station watcher and the AzuraCast API that flooded the logs with errors instead of just doing its normal functionality (repeating the "error.mp3" file over and over).

The Docker container is rebuilding on the registry hub, so in about 10 minutes you should be able to update and get the newer image, and this should resolve the problem.

Let me know how the update works for you.

**Comment by ruLait** [comment]
@SlvrEagle23 Yes, problem is solved. Tnx!
