### ISSUE TITLE
MODULE WHMCS  AZURECAST

### ISSUE THREAD

**Issue by leowerbes** [AzuraCast/AzuraCast#2453]
Hello, how are you? Do you want to know if there is a module for whmcs to use in azuracast?

**Comment by SlvrEagle23** [comment]
@leowerbes We get this question quite often, so here's the answer as of the current date:

We have no official WHMCS module, and while we would love to develop one, we really don't have the knowledge or familiarity with WHMCS internal to our team to build one ourselves in a reasonable amount of time.

There are several resellers out there who have created their own WHMCS AzuraCast modules, but to current date I'm not aware of any who have shared their module with the public. To some extent, this makes sense, as almost every user of WHMCS would be a commercial reseller seeking to make a profit, so they don't have much incentive to share it with the general public.

Of course, this isn't how AzuraCast itself works, so it's a little unfortunate that there is an ecosystem building around AzuraCast that generates a profit, while I personally don't commercialize the software and instead give it away as a public good, yet these resellers often _do not_ actually contribute back to AzuraCast, either in the form of code (via pull requests) or donations.

It is completely okay to be a hosting provider who supplies AzuraCast to your customers, but all I ask is that you give back either to the ecosystem at large or to support our continued development on the software.

**Comment by RobinDev03** [comment]
hey,

I am currently considering making a module and making it available for free. I would then also make this available to you via pull request. Of course only if you are interested.

**Comment by cygnostik** [comment]
I for one, would like to offer the service as part of my web hosting services because I already use and enjoy it, plus hoping for the possibility of getting a WHMCS module I can afford eventually. The service wouldn't be so much for profit as to help offset the cost of the streaming service for users and the module would be particularly great to save my time manually managing users... Right now besides myself 2/3rds of my users are free, I just donate the service to be helpful. I'd be happy to increase my monthly contribution at least for a while to help get a good quality plugin, or even to support someone developing a module to sell, which I'd totally also buy to help out. I'm a server nerd & shocking as it may seem even this kind of basic webdev with premade examples (from WHMCS) are way outside the scope of my ability. I'd at LEAST double my patreon contribution to help find someone who can make a really good module and I'd totally put $100 or so (depending on finances any given month) into a pot toward someone taking up the job and putting a module out there.
