### ISSUE TITLE
YP Listing

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#2454]
I try to add and list my station to Icecast directory and Internet-radio.com using below code:
{
"directory": [
{ "yp-url-timeout": 15, "yp-url": "http://icecast-yp.internet-radio.com" },
{ "yp-url-timeout": 15, "yp-url": "http://dir.xiph.org/cgi-bin/yp-cgi" }
]
}
It works and my station get listed but Icecast config sends wrong URL format to the directories.
Instead of sending https://stream.domain.com/radio/8000/radio.mp3 (Correct URL format), it sends http://stream.domain.com:8000/radio.mp3  (Wrong URL format) so it cannot be played on directory page.
Please fix this bug.

**Comment by stardevelop** [comment]
Any plan to fix this bug?
YP listing feature is useless now.

**Comment by Vaalyn** [comment]
The problem here is that the YP listing is managed by IceCast which is totally unaware of the NGINX web proxy so it is sending the only URL that IceCast knows. On the [documentation](https://icecast.org/docs/icecast-trunk/yp/) of IceCasts YP listing feature I've not found any way to customize the URL to look like the proxy URL.

So the only way to change the URL that is send to the yp directory would be to either modify IceCast itself to work differently, which I think we shouldn't do in this case, or to write our own sync task for YP listing so that AzuraCast sends all the needed info for listing to a YP directory.

This would however be a more complicated new feature as the [documentation of the YP protocol](https://wiki.xiph.org/Icecast_Server/YP-protocol-v2) seems to be outdated ([GitLab issue](https://gitlab.xiph.org/xiph/icecast-server/issues/2094)), although I'm not sure to what degree it is outdated. We'd have to basically reverse engineer the code that IceCast is using to do that in order to correctly implement this or have someone from Xiph clarify which parts of the documentation are outdated. ([Link to the YP code from IceCast KH](https://github.com/karlheyes/icecast-kh/blob/aad507e140ad6ba2d7b05db3cd0718f6de3cf03d/src/yp.c))

@SlvrEagle23 what do you think about this?

**Comment by stardevelop** [comment]
Why Azuracast uses Icecast-kh instead of official Icecast release from Xiph?
