### ISSUE TITLE
Display the number of files (audios) in Music Files

### ISSUE THREAD

**Issue by JMultimidia** [AzuraCast/AzuraCast#2457]
**PLEASE!**

Please insert the function to display the number of files in "music files" as it already exists in the playlists.

**Comment by SlvrEagle23** [comment]
@JMultimidia Since this is a request to add new functionality to the system, would you mind posting it over at https://features.azuracast.com/ ?

Please also clarify in your feature request what you mean (i.e. showing the total number of files, showing the files in the current directory you're in, etc)
