### ISSUE TITLE
Add Album cover picture in Metadata

### ISSUE THREAD

**Issue by Algodrill** [AzuraCast/AzuraCast#246]
Hello,
It 's possible to add a picture in metadata returned by API from song metadata in mp3?
I make an application Android and i want to show picture of song.

Thanks you !

**Comment by Donokami** [comment]
It would be very useful to get this functionnality.

**Comment by SlvrEagle23** [comment]
Hello all! I've been working heavily on this much-requested item this week, since it has been widely requested and has also been the source of a few users forking the codebase for the sole purpose of adding it in!

I wanted to take the time to do it the "right way", where album art is scaled to a standardized size and format, and served using a heavily cache-friendly endpoint. I also wanted to make sure that the artwork could be edited from within the AzuraCast web UI, and that the changes would actually write back to the audio files themselves.

I'm pleased to say that the added support for album artwork (and song lyrics) is now ready for testing. Album artwork is automatically pulled from newly imported files, displayed *and editable* in the media manager, available via the nowplaying APIs, and shown in the public station page.

If you already have media files and you would like to retrieve the artwork from them, currently there's a CLI command you will need to execute to do this. This will automatically happen for all new files, and once the feature's more stable, I will automatically load album art and lyrics retroactively for existing media.

For *traditional installs*, the command to reprocess your existing media is:

```
php /var/azuracast/www/util/cli.php azuracast:media:reprocess
```

For *Docker installs*, the command to reprocess your existing media is:

```
docker-compose run --rm cli azuracast_cli azuracast:media:reprocess
```

Please join me in testing this exciting new feature out, and let me know what you think.

**Comment by rolradio** [comment]
Thank you for this beautiful feature.
I've updated the docker version this morning and reprocesed the existing mp3
 with the comando docker-compose run - rm cli azuracast_cli azuracast: media: reprocess

Sorry, I do not see any changes.
For review, I have looked at demo.azuracast.com.
There I see a picture in the media.
But the image is not displayed on the pubkic page. Very short, but then the image disappears behind "what is playing now".
On my own docker installation, no change is are visible.

**Comment by Donokami** [comment]
For me it's working.
I would have one more suggestion, to handle the https over the art if ssl is used and avoid having mixed content page.
But incredible work, thanks as always :) 👍

**Comment by Donokami** [comment]
I found one bug, in the API.
In the nowplaying handler, sometimes the art isn't included. Here is what i want to say:
```
"now_playing": {
    "is_live": true,
    "elapsed": 186,
    "remaining": 0,
    "sh_id": 3332,
    "played_at": 1510488436,
    "duration": 0,
    "is_request": false,
    "song": {
      "id": "49d7abe55cd5e8f36c6433f324ebb2a2",
      "text": "LORDSUN - 「手さぐりの B R E A K」",
      "artist": "LORDSUN",
      "title": "「手さぐりの B R E A K」",
      "album": "",
      "lyrics": "",
      "art": ""
    }
  },
  "playing_next": {
    "sh_id": 3333,
    "played_at": 0,
    "duration": 226,
    "is_request": false,
    "song": {
      "id": "49d7abe55cd5e8f36c6433f324ebb2a2",
      "text": "LORDSUN - 「手さぐりの B R E A K」",
      "artist": "LORDSUN",
      "title": "「手さぐりの B R E A K」",
      "album": "",
      "lyrics": "",
      "art": "http://bipe.bope/api/station/1/art/8bc08543b30d36fcd2598311"
    }
  },
```
This radio has 2 songs, and for the same song, the song played now is not showing art, but the playing next include the art url.

**Comment by SlvrEagle23** [comment]
@Donokami There's a known issue if a station has something like 2 or 3 songs in rotation...if the same song plays back-to-back, it thinks the next play wasn't driven by the AutoDJ and was random, therefore it must be a live DJ (which triggers different behavior than if it's the AutoDJ).

The issue doesn't exist with stations with rotations any larger than that, and the bug seems to just be an unfortunate consequence of the limitations of LiquidSoap/etc's metadata notifications.

**Comment by Donokami** [comment]
Ow, okay.
Thanks ! 👍

**Comment by SlvrEagle23** [comment]
@Donokami For your earlier post, #278 has been created to resolve that. :)

**Comment by SlvrEagle23** [comment]
Closing this issue as the album art feature has now been refined to the point that the synchronization is reprocessing existing media to add artwork where missing. If we have any issues related to the addition of album art from this point on, they can be reported as new Github issues.
