### ISSUE TITLE
HELP PLS!!!

### ISSUE THREAD

**Issue by nickloud** [AzuraCast/AzuraCast#2464]
https://ibb.co/zxTxhhJ
https://ibb.co/Kz9pFMm

Server is sleeping (cannot install azuracast

**Comment by SC2Mitch** [comment]
Have you tried restarting your server? To try and wake it up?

**Comment by tanotar** [comment]
Can it also be a problem with the operating system or its version? I have installed it on Ubuntu 18.04 64 bits and everything works correctly. Panel installation, updates and SSL installation

**Comment by Vaalyn** [comment]
To be able to further diagnose this issue please supply us with the information that we request from you in the bug issue template and what kind of hardware you are running AC on.
Timeouts generally can be caused by too much load on your machine so knowing what the specs are can help to figure this out.
