### ISSUE TITLE
Randomly switching to Live Broadcast???

### ISSUE THREAD

**Issue by adwinter** [AzuraCast/AzuraCast#2472]
Hey Guys,

So I've got a strange thing happening and I'm not sure how to troubleshoot it.
I've attached a snippet from the Song Playback Timeline, that shows it seemingly randomly switching to a LIVE BROADCAST. I scoured the Liquidsoap logs and it shows nothing of this activity, and also the IceCast logs show nothing out of the ordinary.

I'm running the Docker version of Azuracast on a CentOS Server.

I even tried to disable streamers completely, thinking I was being hacked or something -- but the error continues no matter what I seem to do -- and what makes matters worse it it seems to be becoming more frequent.

Any advice??

![error001](https://user-images.githubusercontent.com/20404986/75847610-8c620b00-5d94-11ea-943f-b6f2ca2a6a14.PNG)

**Comment by SlvrEagle23** [comment]
@adwinter This isn't actually a live broadcast...this is a logic situation where if we don't get the appropriate metadata from Icecast that corresponds to a media record we have internally in the system, we assume that it must have come from a live broadcast (which is normally the source of records that we don't have any internal metadata for).

This is a known issue and has caused us some trouble for quite a while, and we always struggle with it because the cycle of metadata (us -> Liquidsoap -> Icecast -> us polling Icecast) tends to very frequently yield slight inaccuracies that make it impossible for us to properly match tracks.

**Comment by adwinter** [comment]
@SlvrEagle23 Thanks for the update about this. I certainly hate errors like this - they seem so random. It doesn't always seem to be the same tracks either, so its not as simple as the track metadata being corrupt or something... Anyway, thanks again for getting back to me.
