### ISSUE TITLE
Song requests from playlists that don't have the Allow Requests from This Playlist button checked.

### ISSUE THREAD

**Issue by jdrodriguez** [AzuraCast/AzuraCast#2473]
This last week our station received hundreds of Song Requests from 2 different IP addresses. The interesting thing is that the request were from playlists that don't have the Allow Requests from This Playlist button checked.

**Comment by SlvrEagle23** [comment]
@jdrodriguez I'm having trouble verifying this from the code we have internally to handle request submissions.

One other way that requests could be submitted into the system is by selecting multiple files and then clicking "Queue" in the media manager. Currently, this is seen as a request and processed the same way. It's possible that somehow _this_ endpoint got used for that purpose, though it should be locked down to authenticated users, so that's also somewhat concerning.
