### ISSUE TITLE
Problems with cyrillic symbols

### ISSUE THREAD

**Issue by ruLait** [AzuraCast/AzuraCast#248]
There is might be some kind of issues with cyrillic symbols, could you please check it?

Here's samples:

_Track metadata of one song is duplicating to 3-5 which standing next in a playlist._
![](https://pp.userapi.com/c840733/v840733177/1342a/ItJDnOc5imA.jpg)
_Song name may be not showed at all and title place will be covered with artist name duplicate._
![](https://pp.userapi.com/c840138/v840138430/3324e/Fb7ZcityRcg.jpg)
_After uploading a cyrillic named song name transforming into a mess._
![](https://pp.userapi.com/c840138/v840138751/35022/aSNTGM0l3w0.jpg)
_While LIVE broadcasting if song have cyrillic symbols - it will destroy his character encoding._
![](https://pp.userapi.com/c841033/v841033443/2e37b/kG95mTkALao.jpg)

**Comment by SlvrEagle23** [comment]
@ruLait Would you mind sending me some of these MP3 files so I can test a few changes I have planned locally? My e-mail address is `loobalightdark@gmail.com`.

Also, for broadcasting, are you using Icecast or Shoutcast? Shoutcast has known issues with Unicode characters.

**Comment by ruLait** [comment]
@SlvrEagle23 Sent you an e-mail.

**Comment by SlvrEagle23** [comment]
@ruLait Thank you VERY much for sending me the Docker backup zipped files. That made the debugging process much, much, much easier. :+1: 

This issue seems to be mostly caused by my song unique ID hashing stripping out non-alphanumeric ASCII characters when determining song hashes (so that `Song Name` and `Song Name!` would be the same), which works fine for ASCII-heavy areas, but not so well for areas relying on UTF-8.

I've rewritten that part of the hashing method to be entirely UTF-8 friendly.

Update your code, and within about 5 minutes your station should reprocess the affected files and generate new hashes for each of them. Alternatively, you can also go into System Administration and manually run the "5-minute sync" process.

**Comment by ruLait** [comment]
@SlvrEagle23 "Now playing" data is still broken (unlike "Playing next") :(
![](https://pp.userapi.com/c841024/v841024124/2fad6/xt0n6r-lCwo.jpg)
![](https://pp.userapi.com/c841423/v841423113/2b9b8/kuMKB80ocw0.jpg)

**Comment by SlvrEagle23** [comment]
@ruLait The latest round of updates should fix this issue. Direct responses from IC2/SC2 always mangle UTF-8 data, but this should resolve the issue.

**Comment by ruLait** [comment]
@SlvrEagle23 Confirm, problem is solved.
Thank you for your work! <3
