### ISSUE TITLE
JSON nowplaying sometimes works, sometimes doesn't

### ISSUE THREAD

**Issue by HowardCrane** [AzuraCast/AzuraCast#2487]
I have the below javascript and html span tags. Some dynamic content in my station's JSON is screwing me up, leaving the vars empty maybe half the time.

`var url = 'http://111.90.150.133/api/nowplaying/evrn' fetch(url) .then(function (request) { return request.json()  }) .then(function (json) { var playlist = json.now_playing.playlist var live = json.live.is_live var streamer = json.live.streamer_name document.getElementById("evplaylist").innerHTML = playlist; document.getElementById("evdj").innerHTML = streamer; })`

`<span id="evdj"></span><span id="evplaylist"></span>`

Might there be certain special characters from an "artist", "title", or "album" string that would throw off the JSON?
Thanks

**Comment by PiR1** [comment]
Hello,
Can you send a problematic JSON file please ?
Because I've checked your API and didn't detect any problems with the JSON.

**Comment by r0nd0n** [comment]
I'm experiencing this as well, and it is seemingly random. Web dashboard and music stream are fine, but the https://mysite.com/api/live/nowplaying/station doesn't load.

**Comment by HowardCrane** [comment]
> Can you send a problematic JSON file please ?

No. At least not right now as the error isn't occurring. I believe it has something to do with the playlist "Talk Radio Classics" that kicks in at 1AM GMT. I'll try to be awake for that, as I'm not comfortable shifting playlists around. From CentovaCast and even AzuraCast, it usually riddled me with errors.
My mistake. Should have been proactive.

**Comment by HowardCrane** [comment]
r0nd0n, that issue appears to be different enough to require you to open your own issue. Try to include more information when you post, like your server's operating system etc.

**Comment by HowardCrane** [comment]
> Can you send a problematic JSON file please ?

`[Here you are on pastebin](https://pastebin.com/avpyJEmB)`

**Comment by PiR1** [comment]
> I'm experiencing this as well, and it is seemingly random. Web dashboard and music stream are fine, but the https://mysite.com/api/live/nowplaying/station doesn't load.

The requested url is not the right one, try with this one: https://mysite.com/api/nowplaying/1
If it doesn't load I recommend you to open a new issue with more information

**Comment by PiR1** [comment]
> 
> 
> > Can you send a problematic JSON file please ?
> 
> `[Here you are on pastebin](https://pastebin.com/avpyJEmB)`

Thank you,
Indeed, the current music does not have a playlist but this is not due to a JSON formatting error.
It looks like it's the first music of the new playlist: "Talk Radio Classics" which in addition has a duration of 0.
Can you please check the metadata of this music? Is it a jingle where you would have hidden the metadata?

**Comment by SlvrEagle23** [comment]
> > Can you send a problematic JSON file please ?
> 
> `[Here you are on pastebin](https://pastebin.com/avpyJEmB)`

@HowardCrane It's not immediately clear to me what the problem is with this NowPlaying API response. The JSON parses just fine and it's in line with our specifications.

There are times when, because of issues communicating metadata between us, Liquidsoap and your frontend (Icecast/SHOUTcast), we can't tie the currently playing song back to our internal library, which means that some rich metadata (i.e. playlist name, etc.) won't populate for that song in particular. We're always researching which tracks cause this problem and working to reduce this when possible, but any script that you write that handles NowPlaying data should be prepared for these values to not be set.
