### ISSUE TITLE
Fadein of AutoDJ when a live broadcast is interrupted

### ISSUE THREAD

**Issue by aniphreak** [AzuraCast/AzuraCast#2510]
It would be better if we hear a smooth Fadein of AutoDJ when a live broadcast ends.

As of now, when the broadcast is interrupted, liquidsoap suddenly plays at a middle of a song. It not doesn't sound good as is. 

In comparison, other platforms start at the beginning of a song when a broadcast ends.

**Comment by SlvrEagle23** [comment]
@aniphreak This is actually a known limitation of Liquidsoap's fading mechanism that was causing us some problem for quite some time.

**Comment by aniphreak** [comment]
Then if thats the case, it would be better if AzuraCast can just drop the previous song when restarting the AutoDJ from a live broadcast.

**Comment by gammaw** [comment]
@SlvrEagle23 this is working fine for us with Azura v0.9.8 and a custom Liquidsoap config but haven't checked for 0.9.9 yet.

**Comment by aniphreak** [comment]
@gammaw can you share your code on that custom config?

**Comment by gammaw** [comment]
This is it: https://github.com/mmmnmnm/lahmacun/blob/master/azuracast/liquidsoap_custom.liq
Note that this configuration assumes Liquidsoap 1.4.0 and that's why we manually have to include the fading script provided by the Liquidsoap developers (at [these](https://github.com/mmmnmnm/lahmacun/blob/4acc484a0ac25ef5b11182503afee80347262386/azuracast/liquidsoap_custom.liq#L304-L386) lines). It should not be needed with Liquidsoap 1.4.1. where the fading operators are fixed.
