### ISSUE TITLE
AzureCast Containers.

### ISSUE THREAD

**Issue by Richard399** [AzuraCast/AzuraCast#2516]
Hi,

It appears my server is running out of storage, most of it seems to be used by the AzureCast containers?

Not sure why this is and would appreciate suggestions in resolving the issue, please :-)

Many Thanks

**Comment by pascalla** [comment]
How much storage does your server have?

Have you enabled "Live Broadcast Recordings", these recordings can take up quite alot of space.

**Comment by SlvrEagle23** [comment]
@Richard399 We try to avoid this happening in excess, but it's possible that server logs can pile up and cause trouble. Simply spinning down, then restarting your containers should clear up that used space:

```bash
cd /var/azuracast
docker-compose down
docker-compose up -d
```

Updating your installation using `./docker.sh update` will also do those things (and take some other space-saving measures of cleaning some temporary folders, flushing caches and removing unused images) so that's usually the best way to save a lot of space at once.
