### ISSUE TITLE
Listener Report returns HTTP error 500

### ISSUE THREAD

**Issue by pascalla** [AzuraCast/AzuraCast#2518]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 16.04

**Describe the bug**
When downloading CSV or changing the time period on listeners report, it returns an HTTP 500 error code. 

**To Reproduce**
Change the time period for Azuracast on the "Listeners" page under report.

**Expected behavior**
Show data for the specified dates.

**Relevant Logs**
`2020/03/16 12:22:07 [error] 54#54: *361509 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (t                  ried to allocate 4096 bytes) in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 121" while reading response                   header from upstream, client: 86.11.****, server: localhost, request: "GET /api/station/1/listeners?start=2020-02-16&end=2020-03-16 HTTP/1.1", upst                  ream: "fastcgi://127.0.0.1:9000", host: "azura.****", referrer: "http://azura.****/station/1/reports/listeners"
2020/03/16 12:22:10`

**Screenshots**
![azura-api](https://user-images.githubusercontent.com/22846433/76758796-5f452d80-6782-11ea-9786-c4613b119413.png)

**Device(s):**
Chrome
Windows 10

**Additional context**
I have some assumptions that I need to increase some memory_limit within PHP due to the size of the listener report.

I'll have a play around with memory_limits on PHP and see if anything fixes.

**Comment by Vaalyn** [comment]
I can reproduce this problem on my station although it's running into a timeout for me instead of the memory limit:
```
FastCGI sent in stderr: "PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/azuracast/www/vendor/maxmind-db/reader/src/MaxMind/Db/Reader/Util.php on line 13" while reading response header from upstream, client: 37.24.72.33, server: localhost, request: "GET /api/station/1/listeners?start=2017-02-01&end=2020-03-31 HTTP/2.0"
```

You can increase the memory_limit (and if you also run into a timeout you can increase the timeout too) by editing the `azuracast.env` and changing the values of `PHP_MEMORY_LIMIT` and `PHP_MAX_EXECUTION_TIME`. For reference here is a link to the [azuracast.sample.env](https://github.com/AzuraCast/AzuraCast/blob/master/azuracast.sample.env#L85) file.
You also need to uncomment them in order for them to be applied (removing the `# ` in front of it.
