### ISSUE TITLE
Liquidsoap won't start after latest update

### ISSUE THREAD

**Issue by niallie** [AzuraCast/AzuraCast#2523]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 16.04.6 LTS

**Describe the bug**

After most recent update (March 17, 2020), LiquidSoap won't start.
**To Reproduce**

Boot server.
Start LiquidSoap
Following error is displayed for several seconds:
"Re-raised at file "lang/lang_errors.ml", line 155, characters 48-55
Called from file "lang/lang.ml", line 671, characters 8-163
Called from file "lang/lang.ml", line 678, characters 4-76
Called from file "main.ml", line 125, characters 34-40
Called from file "main.ml", line 668, characters 6-16
Called from file "runner.ml", line 30, characters 14-31"
**Expected behavior**

LiquidSoap expected to start normally.
**Relevant Logs**

https://pastebin.com/NtrEkZNK
**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Vaalyn** [comment]
This issue looks like #2495 can you tell us more about your setup?
Seeing as I wasn't able to reproduce the problem yet I'd like to know more about how the stations where this happens are configured.

**Comment by niallie** [comment]
There are 51 playlists - about 16 of these are music playlists with about 90 tracks in each playlist. Each music playlist has the default weight (3). The other playlists are station idents that run at certain times of the day and day of the week, to give the impression of live broadcasting.

I know that's a heavy load, but it was running flawlessly before the update.

Is there anything specific that you would like to know?

**Comment by niallie** [comment]
Tried updating again, setting "PREFER_RELEASE_BUILDS=true" and problem still exists.

**Comment by Vaalyn** [comment]
In both cases were this issue is happening this seems to be caused by a configuration that was previously working so I think this could be caused by one of the last changes to the Liquidsoap config generator.

Do you happen to know which version you were using before updating? This could narrow it down to a few commits.

In general it could help to also see the generated Liquidsoap configuration from your station (remember to remove any paswords and auth tokens from it before posting). You can find the config in the log viewer utility.

Can you increase the Liquidsoap log level by adding `set("log.level",5)` to the custom liquidsoap config? This will increase your log size a lot though so I wouldn't keep it on for too long (days).
This might give us some more insight on what operation LS is failing exactly.

**Comment by niallie** [comment]
I wasn't able to upload the liquidsoap config file, so here is a pastebin link:
https://pastebin.com/J3MbyiFv

I'm not sure of the version that I was running, but the azuracast instance was created October 3, 2019. It wasn't updated later than 2 weeks after the initial install, I estimate.

Is there sufficient detail in the config? I set the log.level to 5, but that setting doesn't appear in the generated config file.

**Comment by Vaalyn** [comment]
Thank you for uploading your LS config, but you've missed some places when redacting the auth tokens. Please remove the link and redact the rest of the tokens.

Make sure to restart the broadcasting in order to write the new config to disk.

This is how the config should look like after adding the log level and restarting the broadcasting:
![image](https://user-images.githubusercontent.com/13745863/76961834-5f7a3000-691e-11ea-84ec-3f691023c423.png)

This is where I put the log level statement:
![image](https://user-images.githubusercontent.com/13745863/76961901-833d7600-691e-11ea-9714-945be33d4464.png)

**Comment by niallie** [comment]
Bizarre. When I restarted the station to make the log level change that you suggested, the station came back up and now it's working.

I wonder whether making a small change such as this, updated the liquidsoap config and flushed out whatever syntax compatibility was causing the problem. I can't think of what else could have solved the problem. I had restarted the server several times, without success, so it seems that the minor config change was the only effective difference.

I'll monitor how the station gets on over the next 24 hours and then close this issue. Thanks very much for your help - much appreciated.

Other users who hit this problem - try making a minor change to the liquidsoap config and restarting the station. You can undo the configuration change when the station comes back up.
