### ISSUE TITLE
Bug: Liquidsoap connecting to Shoutcast

### ISSUE THREAD

**Issue by GerritS76** [AzuraCast/AzuraCast#2529]
Since the latest update of /var/azuracast/www/src/Radio/Backend/Liquidsoap.php some issues started where Liquidsoap (AutoDJ) has not been able to connect to the (older) ShoutCast v2 (SHOUTcast DNAS/posix(linux x64) v2.4.2.167 (Oct 30 2014)) server.

Error is known as: Wrong password 

> 2020/03/17 23:22:16 [xxxxxxxxxx_local_1:2] Connection failed: bad answer: Invalid Password
> 2020/03/17 23:22:16 [xxxxxxxxxx_local_1:3] Will try again in 3.00 sec.

liquidsoap.liq contained something like :#1 at the password, after replacing the Liquidsoap.php with an older one (which I had inside a back-up) the password shows correctly and Liquidsoap connects without issues. Possible cause on line 1089 (?);

`            $password .= ':#' . $id;`

**Comment by SlvrEagle23** [comment]
@GerritS76 The purpose of this change was to allow us to broadcast to the proper SID in newer SHOUTcast installations.

It's possible we may need to have "SHOUTcast 2.5.x" and "SHOUTcast 2.4 or older" option to appropriately handle this...thoughts @Vaalyn ?

**Comment by GerritS76** [comment]
I think it's best to support the older Shoutcasts as well. Reason? As I understand, newer Shoutcast releases are limited to 128 kbps in case people use the free variant. The older versions still allow higher bitrates that some people still like to use.

Isn't it a good idea to check (instead of, offer an option) which Shoutcast version is installed and make the changes to liquidsoap.liq according to the Shoutcast server which is used? sc_serv --version shows the version so I guess it would be possible to make the changes which are needed. Isn't it a matter by checking this with a preg_match ?

**Comment by Vaalyn** [comment]
I can't really find any information on which version it was when the 128kbps limit was added. Does someone know if 2.4.7 has that limit already or if it was added in 2.5?

The `:#<sid>` is only available since 2.4.7 so if this version does not have this limit then it could make sense to update to that one.

If 2.4.2 really is the last version that does not have this limit it could make sense to have a generator for this specific version.

@SlvrEagle23 In general I'd be against supporting 6 year old versions that are not supported anymore by the developer but in this case it could make sense. If 2.4.2 is really the last version where higher kbps streams are allowed in the free version we shouldn't unnecessarily force people who use SHOUTcast in this version to having to buy a license to use their existing streams. 

When thinking about how to implement a generator for different versions I'm not sure if it would be easier to maintain multiple Backends (Liquidsoap.php files) for the different versions or if using templates to generate the different parts would make that easier.

**Comment by SlvrEagle23** [comment]
@Vaalyn Nope, as far as I know the last fully-free version is 2.5.5, which does support the new syntax.

**Comment by GerritS76** [comment]
@Vaalyn  The last version with higher limits is 2.4.7 if i'm right, starting from the 2.5.x branch the limit has been introduced. However the 2.4.2 version is way easiër to find around the internet while the 2.4.7 isn't and in certain cases caused problems (connections dropping, random crashes etc.).

I dont think people need support on the old Shoutcast v2 branch as it's just working out-of-the-box - easiest one ever (after the v1 branch) ;-)

**Comment by SlvrEagle23** [comment]
@GerritS76 I have two copies locally, and 2.5.5 was the last one before they went "freemium", and 2.6.0 was the first release in the freemium series. I keep a copy of both locally just in case.

Sadly, we can't officially distribute those on account of their quite restrictive license, but I know our software works quite well with 2.5.5.

**Comment by GerritS76** [comment]
@SlvrEagle23  Didn't the 2.5.5 had a limit up to 128kbps as well ?

**Comment by Vaalyn** [comment]
@GerritS76 I've found [this blog post](https://www.mediacp.net/release-notes/mediacp-2-2-3-2-release-notes/) where it's mentioned that the 128kbps limit was introduced in dnas 2.6 so you should be able to use up to 2.5.5 without losing high bitrate streams.

**Comment by ogrenci01** [comment]
Hello Everyone:

Official SHOUTcast Server v2.5.5.733/posix(linux x64)
Download it: https://www.arkacadde.org/sc_serv2_linux_x64-latest.tar.gz

Shoutcast v2.5 is freeware and Shoutcast v2.6 is payment.
