### ISSUE TITLE
Swagger API endpoints not executing

### ISSUE THREAD

**Issue by alexhorner** [AzuraCast/AzuraCast#2534]
**Using Docker installation method**

Yes

**Host Operating System**

Ubuntu 18.04.4 using AzuraCast v0.9.8.1

**Describe the bug**

The Swagger API interface is not responding when clicking the blue Execute button

**To Reproduce**

1. Go to the Swagger API page
2. Open up an endpoint
3. Try it out
4. Execute

**Expected behavior**

Endpoint should execute clientside

**Relevant Logs**

Appears to be a clientside issue. If serverside logs required, tell me so.

**Screenshots**

![image](https://user-images.githubusercontent.com/33007665/77098685-a5acbd80-6a0a-11ea-9e9b-60809ca19838.png)

**Device(s):**
Windows 10 Home 1903 running Firefox 74.0 64-Bit

**Comment by Vaalyn** [comment]
Can also see this problem with the swagger page of the demo installation.

If I'm not mistaken this should be related to this [issue](https://github.com/swagger-api/swagger-ui/issues/4745) and it seems to be fixed in newer swagger-ui versions.

@SlvrEagle23 are the swagger-ui .js files manually updated? I couldn't find any reference to swagger-ui in the frontend build process and wanted to verify my assumption.

**Comment by SC2Mitch** [comment]
We was having a number of issues relating to the swagger ui, it simply wasn't sending out any requests nor did it log anything in our server files

**Comment by SlvrEagle23** [comment]
@Vaalyn Yeah, we don't automate pulling new versions of the Swagger UI file. I can pull a newer version and update it and see if it helps.
