### ISSUE TITLE
Live streamer's display name metadata in Icecast stream

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#2573]
We noticed that Internet radios/apps won't display the streamer's name. The client (Butt in our case) sends the song name but not the streamer's user name. I guess I could make our Liquidsoap config to do that but there's a problem: Liquidsoap doesn't now the display names. I could use some mapping in the Liquidsoap config but that would be duplication (every time we change display names in Azuaracast we would need to adapt the Liquidsoap config). What do you think? Do you think it's possible that Azuracast updates the stream info when a live streamer connects?

**Comment by SlvrEagle23** [comment]
@gammaw The streamer's name is a component of the richer metadata we maintain for our now-playing API; unfortunately, the only metadata that gets sent over between Liquidsoap and Icecast/SHOUTcast is the title and artist, and even that gets mangled from time to time.

The only way you can get that richer metadata is through our own API, because we keep track of the live streamer and other data; while Liquidsoap internally keeps track of the currently streaming DJ, that metadata never makes it out of that system unless through ours.

In theory, you could alter the metadata being sent out to Icecast/SHOUTcast to include the streamer's login username (not their display name, as Liquidsoap doesn't know that), but that's advanced LS configuration that I'm not 100% familiar with.
