### ISSUE TITLE
Song title does not update

### ISSUE THREAD

**Issue by alex8103** [AzuraCast/AzuraCast#2602]
Hello, my problem is that I have already restarted the instance several times, but this does not change anything. As can be seen in the screenshot, the title, the time, updates aso. Not. Have already looked for solutions on Google, but found nothing. I hope a helpful answer!
Thank you very much and have a nice week!
![loading](https://user-images.githubusercontent.com/53876259/78070337-e0fca400-739b-11ea-911b-7226e984ce5b.PNG)

**Comment by SlvrEagle23** [comment]
@alex8103 If you try to manually run the "Now Playing" synchronization task (from the System Administration homepage), do you encounter any errors?

**Comment by alex8103** [comment]
@SlvrEagle23 Hello, no, I don't get any errors.

**Comment by alex8103** [comment]
Still have the problem. Would be great if someone would help!

**Comment by pimseb** [comment]
Hello.
I reopen this thread because I have the same problem. When a song comes to its end the public page doesn't update itself. It still shows the old metadata (song name and cover). 
I've checked the admin synchronisation task but didn't see any error. 
Thank you 
![Screenshot_20210203-124129_Chrome](https://user-images.githubusercontent.com/23084628/106742940-fe367a80-661d-11eb-9c1d-8699b63d0201.jpg)
