### ISSUE TITLE
Trunate, or remove stats before a date ? 

### ISSUE THREAD

**Issue by CouinCouin** [AzuraCast/AzuraCast#2654]
Hi, 

Is there a way to  completely remove statistics before a choosen date ?  
I mean, we did some tests with adding relay  and we removed it , but it still displayed in the audience graph. 

I would for exemple something like that :
**DELETE FROM statistics WHERE date < '2020-04-06 00:00:00'** 

Thanks :) 
Couin

**Comment by SlvrEagle23** [comment]
@CouinCouin This is a valid question, and prior to this I didn't even have a way of doing this as a developer performing debug work, so I went ahead and created one, and you can use it for this purpose too if you want!

The syntax is as follows for Docker installations:

```bash
./docker.sh cli influx:query "DELETE WHERE time < '2020-04-01'"
```

For Ansible ones, it's the same except instead of `./docker.sh cli` it's `php /var/azuracast/www/bin/console`.
