### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by marvintvnet** [AzuraCast/AzuraCast#2657]
Hello
If i try to install Centovacast it stops do anything at the Liquidsoap install Screen.

Screen: https://prnt.sc/rwotkt

What i already did is:

- Testing on other System / OS.
- Checked logs

What System i have ?:

- 8GB Ram
- 200GB SSD
- 4vCores
- Ubuntu 18.04

**Comment by marvintvnet** [comment]
UPDATE: I got now followings error at install:

https://prnt.sc/rwovhg

**Comment by ogrenci01** [comment]
Hi @marvintvnet ;

I have been using Ansible setup for a long time. I do not know what caused this technically. I'm not a developer. Sorry.

After you have done the installation steps correctly, AzuraCast will be installed without any problems. Some operations may take a long time due to hardware changes. You should wait patiently. Installing on a clean operating system always minimizes problems.
