### ISSUE TITLE
API Authentication Error?

### ISSUE THREAD

**Issue by adwinter** [AzuraCast/AzuraCast#2660]
**Using Docker installation method**
Yes

**Host Operating System**
Ubuntu 18.04 LTS

**Describe the bug**
I'm trying to use the API to get song data, which requires authentication. I get an error when I set the header.

**To Reproduce**
From the command line run this:

```bash
curl -X GET "http://play.fusion109.com/api/admin/custom_fields" -H "accept: application/json" -H "X-API-Key: <hidden>"
```

I get a 500 error
_"Argument 1 passed to App\\Entity\\ApiKey::hashVerifier() must be of the type string, null given, called in /var/azuracast/www/src/Entity/ApiKey.php on line 120"_

**Expected behavior**

[
  {
    "id": 0,
    "name": "string",
    "short_name": "string",
    "auto_assign": "string"
  }
]

**Relevant Logs**
none

**Additional context**
this shows the same error when I use the /api website and authenticate there. Curiously though, if I login to Azuracast in my Chrome Browser, and don't log out.. I can put the API call right in the browser and it will show the right result.

**Comment by adwinter** [comment]
Anybody know what I'm doing wrong here??

**Comment by SlvrEagle23** [comment]
@adwinter That error suggests that the API key you're including in that request doesn't have a separating `:` character, and thus isn't a valid AzuraCast API key. You'd need the full length of the API key, which has a colon separating its two components.

I do need to update the error message provided to indicate that the problem is specifically that the key isn't in the valid API key format. That should be done as of the latest commit.

**Comment by adwinter** [comment]
@SlvrEagle23 Thanks so much! I'm a bit new at using APIs, and was going crazy trying to figure out what my mistake was. I was only using HALF the key!  Regenerated the key and copied the full one and it works like a charm. Appreciate your time helping with this...

**Comment by SlvrEagle23** [comment]
@adwinter Glad to help!
