### ISSUE TITLE
No listener statistics being generated when relaying

### ISSUE THREAD

**Issue by patrickvdhoek** [AzuraCast/AzuraCast#2667]
**Using Docker installation method**
Yes (and updated just 10 minutes ago)

**Host Operating System**
Ubuntu Server 

**Describe the bug**
Listener stats are not being generated when (temporary) only using the External Relay options. The listener count is seen in the panel though (External Relays -> Total listeners).
My installation is in Dutch, so I don't know how the labels are in English.

**To Reproduce**
Set-up an External Relay (we currently have 4).
Icecast 2.4
Port 80
Afterwards (Azuracast setup is running a day or 3 now) there are no statistics generated.

**Expected behavior**
On the entry page while being an admin, able to see the graphical statistics or at Reports.

**Additional comments**
So to be clear:
Listener Counts are being registered properly, but there are no statistics (history / graphs) are being generated for external relays. 

<img width="1133" alt="Schermafbeelding 2020-04-13 om 01 59 19" src="https://user-images.githubusercontent.com/48649868/79082872-7861df80-7d2a-11ea-8626-e141d3ccec78.png">

<img width="1094" alt="Schermafbeelding 2020-04-13 om 01 58 26" src="https://user-images.githubusercontent.com/48649868/79082870-75ff8580-7d2a-11ea-9aac-1f1acc32a4d1.png">

**Comment by patrickvdhoek** [comment]
I mean these statistics: 

<img width="1133" alt="Schermafbeelding 2020-04-13 om 01 59 19" src="https://user-images.githubusercontent.com/48649868/79082863-684a0000-7d2a-11ea-8aa3-cbb309c3fcd8.png">
<img width="1094" alt="Schermafbeelding 2020-04-13 om 01 58 26" src="https://user-images.githubusercontent.com/48649868/79082850-510b1280-7d2a-11ea-8fcb-8ebd1d14169e.png">

**Comment by SlvrEagle23** [comment]
@patrickvdhoek Very interesting bug indeed...are there any errors reported if you go to manually run the Now Playing sync task under System Administration?

**Comment by patrickvdhoek** [comment]
No errors, all runs fine. See attachment too.

It registers everything fine, only the 'unique' number stays at 0, maybe because there is an reversed proxy involved here. But it doesn't count the 819 on the graphical statistics (as seen in my earlier screenshots).

<img width="1133" alt="Schermafbeelding 2020-04-13 om 18 36 56" src="https://user-images.githubusercontent.com/48649868/79138988-c7a12200-7db5-11ea-94fc-9912146d6066.png">

**Comment by pascalla** [comment]
I have multiple remote relays and seem to be working well. Have you ensured you've entered the correct admin password on the remote relay section?

**Comment by patrickvdhoek** [comment]
All details are correct, and 2.4 and -kh10 are not different in terms of status pages.

**Comment by SlvrEagle23** [comment]
@patrickvdhoek I think there must be some sort of difference here, because it's not fetching the `clients`, which it would normally be getting from that secondary admin `/admin/listclients` endpoint.

Our general rule is that we don't list the unique listeners unless we can accurately compile them ourselves (since Icecast doesn't send us a "unique listener" count), and the only way we can accurately compile them is by having the client details that we're missing in this feed.

Since you're getting a HTTP 200 it implies a _successful_ hit of the listclients page, which makes it even more bizarre. Indeed there may be changes between the upstream 2.4.x and KH that we are depending on in this case.

**Comment by pascalla** [comment]
I've just tested and the issue is that Icecast 2.4.3 has a different XML structure to Icecast-KH

Icecast 2.4.3:
![image](https://user-images.githubusercontent.com/22846433/79560249-2b219d00-809f-11ea-8a0d-c5bdd48aca61.png)


Icecast-kh10
![image](https://user-images.githubusercontent.com/22846433/79560284-3d034000-809f-11ea-8e35-ef4d761ac430.png)

**Comment by Xara** [comment]
I have exactly same problem, local stations show, my relay is no more in statistics after recent update (I have moved to another server, now is running on Focal with 10.5 MariaDb)
