### ISSUE TITLE
Error: You have submitted a request too recently!

### ISSUE THREAD

**Issue by tiwale01** [AzuraCast/AzuraCast#2668]
Installation method
Docker
Host OS (for Docker installations)
Ubuntu 18.04

Request worked fine for yesterday. All of a sudden I am staring to get this error "Error: You have submitted a request too recently! Please wait before submitting another one." whenever you try to request a song. I made sure the song was not played recently. I tried after 15 minutes, same error.

There is no setting to change request frequency. 
How do I solve or change settings please ?

Thanks,

**Comment by Vaalyn** [comment]
Are you requesting via the public page or via the API?

**Comment by tiwale01** [comment]
Via public page. How does the API request work? Any docs ?

I did a temporary fix. I changed ($recent_requests) > 10
/var/lib/docker/volumes/azuracast_www_data/_data/src/Entity/Repository/stationrequestrepository.php change if (count($recent_requests) > 0)

Thsnks,

**Comment by Vaalyn** [comment]
Have you updated your installation right before this issue started happening for you?

We've recently added a minimum 15s threshold for requests per user/ip here: https://github.com/AzuraCast/AzuraCast/blob/master/src/Entity/Repository/StationRequestRepository.php#L53-L55
This was added to prevent users from flooding a station with requests.

There is a setting in the station profile called `Request Last Played Threshold (Minutes)` which will influence the wait time too. Can you check what value you have set there?

> Via public page. How does the API request work? Any docs ?

The [AzuraCast API](https://demo.azuracast.com/static/api/index.html) provides you with an endpoint that you can use to send requests to AzuraCast. This is useful if you have your own player implemented and want to also provide users with the ability to request songs via your own interface. I've asked if you are using this method because with authenticated users the threshold will not apply. Seeing as you are not using this the problem is most likely coming from something that influences the threshold.

**Comment by tiwale01** [comment]
Yes, I did update before letsencrypt

I have Minimum delay at 5 minutes, Request last played 60 minutes.  I will search google for authenticated users implementation. 

The funny thing is, I waited over 10 minutes before another request and still got the error.

Thanks for your help.
