### ISSUE TITLE
Advanced Playlist Error

### ISSUE THREAD

**Issue by sjradmin** [AzuraCast/AzuraCast#2675]
Hi 

When selecting playlist type as advanced and save getting this error:

An error occurred and your request could not be completed.

**Comment by SC2Mitch** [comment]
When this error shows, check out the docker container logs

**Comment by Vaalyn** [comment]
This is caused by a mismatch between the value for the playlist `type` property. The form sends the value `advanced` but the validation on the server checks for the value `custom`.

When looking at the commit history for the `TYPE_ADVANCED` constant in the [StationPlaylist](https://github.com/AzuraCast/AzuraCast/blob/master/src/Entity/StationPlaylist.php#L35) entity I saw that the value there has not changed I think this was an oversight when switching to the Vue based playlist editor.

The value of [this line](https://github.com/AzuraCast/AzuraCast/blob/master/frontend/vue/station_playlists/form/PlaylistFormBasicInfo.vue#L71) in the Vue template needs to be changed to `custom`.

I've created a PR to fix this issue.
