### ISSUE TITLE
Why do you have an editor feature that does not work?

### ISSUE THREAD

**Issue by Haywood-Jablowmey** [AzuraCast/AzuraCast#2678]
What is wrong with you people? Why would you set up an edit feature that may or may not work? Don't you think it defeats the purpose of having such a thing if it does not work? You know what I mean? If someone takes the time to deal with that issue and then it does not work, it is kind of weak. Its lame. It should work. The other thing is that it works for some music filers and it dosnt for others/ Its a crap shoot whether it works or not. It could work. Or it could not. It just depends on the way the wind is blowing outside. I do NOT know why you have that as part of the system when it clearly does not work. It makes no sense. Why Beta the thing in real time. that's not the function to do that with. It has to work or not work or better yet, if it does notwork, take it down. Or, get it to work. This is binary. How it plays jumping bean is beyond anyone. Its gotta work or not work.

**Comment by SlvrEagle23** [comment]
@Haywood-Jablowmey I'm assuming you're the same person who sent me a profanity-laden e-mail a few hours ago about this exact issue. I'll repeat what I sent back in the e-mail here as well:

The "Visual Cue Editor" feature is labeled as a beta because it is a very new feature that depends on a complex interworking of various software components. While you could help us improve the software by identifying the conditions in which it does not work properly, you've clearly taken a different approach of attempting to harass us into improving one small portion of our application. As has been mentioned here many times, we are a small team of volunteers providing free software.

Your e-mail insulted me, my team, and other users here on GitHub and violated several tenets of our Code of Conduct. You are no longer welcome in AzuraCast communities.
