### ISSUE TITLE
Discord webhooks not displaying album art?

### ISSUE THREAD

**Issue by JanieUwU** [AzuraCast/AzuraCast#2685]
**Using Docker installation method**
Yes

**Host Operating System**
Debian 10

**Describe the bug**
Discord webhook doesn't display the current song album art.

**To Reproduce**

1.Create discord webhook and leave settings to default.
2.Add to discord.
3.See no album art but song title and artist works.

**Expected behavior**

Expected album art to be displayed in the discord server with song title and artist.
**Relevant Logs**

No error messages.
**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**
Running on Azuracast v0.9.9

**Comment by SlvrEagle23** [comment]
@JanieUwU By default when creating a new Discord web hook, the thumbnail URL is set as `{{ now_playing.song.art }}`.

Is it still set to that in your web hook?

**Comment by JanieUwU** [comment]
@SlvrEagle23 Yeah, I didn't touch that. I also tried putting that into the URL section and the title became a link that linked to that song's thumbnail. It just does't appear in discord.

**Comment by SlvrEagle23** [comment]
@JanieUwU I've discovered the underlying cause of this issue: Discord attempts to fetch any images attached in webhooks via either "image" or "thumbnail" attributes, and if they're not over HTTPS connections it simply won't attempt to fetch them at all and just won't display them instead.

In order to ensure the highest possibility that thumbnails will show, I've updated the webhook so that it will default to using a HTTPS URL in _all_ cases (as it wouldn't display it anyway if it wasn't, so nothing is lost if HTTPS doesn't work or isn't set up). As long as you have LetsEncrypt or Cloudflare or some other HTTPS setup, this should work without any issues.
