### ISSUE TITLE
Docker installation method did not work on Arch Linux

### ISSUE THREAD

**Issue by user171** [AzuraCast/AzuraCast#2686]
**Using Docker installation method**

Yes
**Host Operating System**

Arch Linux
**Describe the bug**

After making sure the system requirements are met, I followed the docker installation method. After executing `./docker.sh install` I receive:
```
Docker does not appear to be installed. Install Docker now? [Y/n] 
# Executing docker install script, commit: 442e66405c304fa92af8aadaa1d9b31bf4b0ad94

ERROR: Unsupported distribution 'arch'

usermod: group 'docker' does not exist
You must log out or restart to apply necessary Docker permissions changes.
Restart, then continue installing using this script.
```
I have then logged out and in, rebooted the system, retried to execute the script and the same output re-appears again. 

**To Reproduce**

Execute the docker intall script on Arch Linux.
**Expected behavior**

I suppose the full installation of AzuraCast.
**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

I am using Arch Linux for convenience. But if as the error message points, this distribution is not supported then I don't mind using another distribution. Please let me know which distribution is commonly used.
If I did something wrong then please let me know.

**Comment by user171** [comment]
Just to complement, as a workaround, I have installed docker manually with the arch docker packages and then executing the script again did the rest of the installation.

**Comment by SlvrEagle23** [comment]
@user171 Unfortunately, it seems that the official Docker installer script (the one we actually use in our setup process to do the installation of the Docker Community Edition service) doesn't support Arch out of the box at all.

Since we don't maintain this script, and we would greatly prefer to continue using the official Docker installation script instead of writing our own that overrides it and would be more likely to fall out of date faster, I don't think we'll be able to support Arch ourselves until Docker do in their own script.

Your workaround should work absolutely fine and is indeed what we do on other unsupported platforms like Windows/MacOS: just run the docker installer ahead of the AzuraCast one and let it detect that it's already installed.
