### ISSUE TITLE
Azuracast Player Embed Code now workint

### ISSUE THREAD

**Issue by sjradmin** [AzuraCast/AzuraCast#2691]
Hi

I tried using the embed code of my station on a WordPress site but it does not work and showing an error that the page is permanently removed in the iframe area.

Isn't  it supposed to be working on external website?

Regards

**Comment by SlvrEagle23** [comment]
@sjradmin It's definitely supposed to be working...are you sure it's not an HTTP embed on an HTTPS web site (that isn't loading because it's considered "insecure" content), or trying to redirect to the HTTPS version of the same address? When you visit the embed URL directly, do you see the same error message?

**Comment by sjradmin** [comment]
It's still a test server and using only http and the embeded code is http showing ip address not a domain, is that an issue?

**Comment by SlvrEagle23** [comment]
@sjradmin As long as you can access that IP address, it shouldn't be a problem. I would need to see a screenshot of this issue to really know more...I'm not sure what would cause the page to show a "permanently removed" error.

**Comment by sjradmin** [comment]
This is the error showing:

the webpage at https://x.x.x.x/public/test_radio/embed might be temporarily down or it may have moved permanently to a new web address.

**Comment by SlvrEagle23** [comment]
@sjradmin Okay, but if you actually visit the link directly, it still works? Or is it down across the board?

I suspect this may be an HTTPS setting issue, but I don't really have enough information here to know one way or the other.

**Comment by sjradmin** [comment]
Yes https://x.x.x.x/public/test_radio/embed works if I use in browser.

**Comment by sjradmin** [comment]
I can install lets encrypt certificate and try but I don't have a domain assigned to this test server yet. Will that work?

**Comment by SlvrEagle23** [comment]
@sjradmin If you're using the IP address and trying to connect via HTTPS, it's very likely that the embed just isn't showing because it suspects there's no valid SSL certificate. SSL certificates are issued for domain names and not IP addresses. Once you get your domain name established and LetsEncrypt set up correctly, the issue shouldn't be there any more.

**Comment by Radio-Quergedacht** [comment]
Now playing for AzuraCast

https://de.wordpress.org/plugins/now-playing-widget-fuer-azuracast-stationen/
