### ISSUE TITLE
ICECAST SSL

### ISSUE THREAD

**Issue by gondp** [AzuraCast/AzuraCast#2692]
Hi we have generated a certificate and in icecast it gives us an error, with nginx it works perfectly.

[2020-04-16 20:08:38] WARN connection/get_ssl_certificate Invalid cert file /etc/nginx/ssl/ssl.crt (system lib)

The symbolic link to the letsencrypt certificate has been created

$ dir /etc/nginx/ssl# ls -la

lrwxrwxrwx 1 root root 56 Apr 16 19:44 server.crt -> /etc/letsencrypt/live/DOMAIN/fullchain.pem
lrwxrwxrwx 1 root root 54 Apr 16 19:44 server.key -> /etc/letsencrypt/live/DOMAIN/privkey.pem

lrwxrwxrwx 1 root root 56 Apr 16 20:07 ssl.crt -> /etc/letsencrypt/live/DOMAIN/fullchain.pem
lrwxrwxrwx 1 root root 54 Apr 16 20:07 ssl.key -> /etc/letsencrypt/live/DOMAIN/privkey.pem

**Comment by pascalla** [comment]
Icecast requires different layout of PEM file. You'll need to concat the fullchain the privkey.
https://mediarealm.com.au/articles/icecast-https-ssl-setup-lets-encrypt/

**Comment by gondp** [comment]
Hello thanks @pascalla, I have concatenated the file and it keeps giving the same error.

The file has been saved in the directory and the ssl.key file is a symbolic link.

**Comment by pascalla** [comment]
If you are trying to get the azuracast icecast stream using https, azuracast already provides this functionality. 

https://www.azuracast.com/developers/docker_sh.html#available-commands

This will create an nginx reverse proxy with https 
It will be something like this can be found on your station dashboard. 
https://radio.com/radio/8010/live

Otherwise make sure icecast has permission to actually read the pem file. This seems like a general issue rather than an issue with AzuraCast. Ensure your .pem file is correctly formatted.

cat /etc/letsencrypt/live/<YOUR ADDRESS>/fullchain.pem  /etc/letsencrypt/live/<YOUR ADDRESS>/privkey.pem >  /usr/share/icecast2/icecast2.pem

Make sure the "icecast2.pem" is owned by icecast and icecast2 group.

**Comment by gondp** [comment]
Yes, we know about the usefulness of Azuracast as a proxy, but we want streaming to be secure, not through a proxy. We will perform an installation from 0 to see if this solves the problem.

**Comment by YosefAdPro** [comment]
@gondp Maybe it will give you a thread:
https://github.com/AzuraCast/AzuraCast/issues/2462
