### ISSUE TITLE
"Skip song" doesn't always skip to the right song

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#2701]
**Using Docker installation method**
Yes
**Host Operating System**
Ubuntu 18.04

**Describe the bug**
Sometimes it skips to other song from the playlist but not to the "Playing Next" song.
Sometimes it skips and doesn't show the " Playing Next" song at all
I checked it also on the Azuracast demo site
**Screenshots**
![image](https://user-images.githubusercontent.com/2701228/79696570-0cc9c600-8286-11ea-97d4-04a6492ad0cc.png)

**Comment by SlvrEagle23** [comment]
@eranwo This is a known issue, and honestly we're doing about the best we can do with this as it is right now.

In order to have "skip song" not completely mess up the playback order, immediately before skipping the song, we queue up the one that's in the "playing next" column and then skip directly to that.

As a result of our new queue system, if the queue has "run out" because of multiple skips, or other similar problems, skipping will just revert to its previous behavior of picking a random song out of a standard playlist.

I'll continue to look into solutions for this, but this is a fairly "edge-case" scenario.

**Comment by eranwo** [comment]
@SlvrEagle23 The question is whether this might also happens in normal mode, where the station plays song after song without user intervention (i.e. the api shows the next song incorrectly) or only when using the skip song feature

**Comment by SlvrEagle23** [comment]
@eranwo Is there any evidence of it doing that in normal functionality? The "next song" functionality is specifically a little different from the normal way of handling the song queue, so it's entirely possible the issues could be isolated to it.

**Comment by eranwo** [comment]
@SlvrEagle23 I didn't see it in normal functionality only when skipping.

**Comment by SlvrEagle23** [comment]
@eranwo As part of a change on an unrelated issue, queues are now refilled at a higher rate, which will reduce the chance that the queue will be empty when a song is skipped, which should thus reduce the incidence of this happening as well.
