### ISSUE TITLE
aditional output format

### ISSUE THREAD

**Issue by voipworld** [AzuraCast/AzuraCast#271]
hello guys

is it pocible to have another format, like Opus?

the gui support Ogg, MP3, AAC but not opus

and is it pocible to change the config file, or am i obligated to use only the web ui?

i want to modify my AAC to use stereo mode not join stereo, and add another opus stream

thanks!

**Comment by SlvrEagle23** [comment]
@voipworld I have added support for OGG Opus when managing mount points on Icecast stations, and have updated the traditional and Docker installs to add support for Opus to Liquidsoap.

As for the joint stereo vs. stereo mode selection, right now there isn't a way of customizing that, and it would actually be a little difficult to add, since each encoder has a varied set of support for joint stereo, stereo and mono channels. Currently, all of the codecs just specify stereo as "true", not specifically specifying joint stereo.

**Comment by voipworld** [comment]
hey

thanks for the quickfix!


i see opus added, but cant make it up...

the setting saved, but when i restart i get a FXML error without any details at i know

it look like liquidsoap config issue, i am not sure

for the encoders i recomand you the following

for example each encoder have some specific settings, like mp3 can have CBR, VBR and ABR encoding

opus also can have lowband, widband, super widband, fullband quality

and all of them support resampling to 48khz

when selecting a specific encoder, its recomanded to expose a minimalistic configuration interface to customise it, like airtime (inusable for me & others, mostly comersial)

for the biterate, its recomanded to dont use radio buttons

use a combobox with pre-defined value and a text input

reason is that for example, opus recomand some values like 80kbit & 48khz  for live audio broadcast

**Comment by SlvrEagle23** [comment]
@voipworld The rebuild of the Docker image that adds support for Opus is being held up by the fact that Shoutcast's download server appears to be down at the moment. Until that build finishes, Opus won't be working on Docker instances and will cause errors like that.

As for the other issues, I will probably work to make these separate GitHub issues to avoid confusing them with the Opus support issue on this ticket.

**Comment by voipworld** [comment]
awesome, please notify me when the build is ready!

**Comment by SlvrEagle23** [comment]
@voipworld The Docker build should have just succeeded.

**Comment by voipworld** [comment]
Update:

Opus support is working 100%, 48khz wideband quality
thanks a lot ...!
