### ISSUE TITLE
Where I can add a html element to my station?

### ISSUE THREAD

**Issue by Npizza** [AzuraCast/AzuraCast#2730]
Hi I want to add a HTML element to my frontpage of my station. What file is responsible for that?
I want to add this service https://minnit.chat

Thank you

**Comment by CodeSteele** [comment]
You have two options:

1) Build your own webpage, and embed our player, this is probably the best because it's the least restrictive and you can do whatever you want around our player.
2) Try to use the Custom JS For Public Pages section in the admin ->branding section to try to hot-load your player, this will probably require custom code (I doubt that site will give you compatible code on its own), and will probably be pretty error-prone.
