### ISSUE TITLE
translation is not imported

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#2754]
Updated the station today, if Frontend translation was not imported before, today even Backend is not imported.
Perhaps there will be not indifferent people who can help me, before when there was one file with a translation everything worked fine, now import with a translation does not work at all.

>  ./docker.sh cli locale:import
Starting azuracast_redis_1 ...
Starting azuracast_mariadb_1 ...
Starting azuracast_influxdb_1 ... done
Starting azuracast_stations ... done
2020/04/26 18:56:06 Waiting for: tcp://mariadb:3306
2020/04/26 18:56:06 Waiting for: tcp://influxdb:8086
2020/04/26 18:56:06 Waiting for: tcp://redis:6379
2020/04/26 18:56:06 Connected to tcp://mariadb:3306
2020/04/26 18:56:06 Connected to tcp://redis:6379
2020/04/26 18:56:06 Connected to tcp://influxdb:8086
Locales imported.
2020/04/26 18:56:06 Command finished successfully.

**You can import the translation yourself and see that it is not imported.**

**Comment by SlvrEagle23** [comment]
@susl16c You might be missing some translation files. The normal success message for "Locales imported" will list out several locales that have been successfully imported.

It isn't that we're indifferent, it's that something about your setup has caused problems that we can't reproduce in our own, where we routinely generate and import new locales with every new version without any issues. Without being able to reproduce these problems, what else can we do?

**Comment by susl16c** [comment]
./docker.sh cli locale:generate
WARNING: The LETSENCRYPT_HOST variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_EMAIL variable is not set. Defaulting to a blank string.
Starting azuracast_redis_1 ...
Starting azuracast_influxdb_1 ... done
Starting azuracast_redis_1 ... done
2020/05/27 17:36:58 Waiting for: tcp://mariadb:3306
2020/05/27 17:36:58 Waiting for: tcp://influxdb:8086
2020/05/27 17:36:58 Waiting for: tcp://redis:6379
2020/05/27 17:36:58 Connected to tcp://redis:6379
2020/05/27 17:36:58 Connected to tcp://influxdb:8086
2020/05/27 17:36:58 Connected to tcp://mariadb:3306
Locales generated.
2020/05/27 17:36:58 Command finished successfully.
[root@web]# ./docker.sh cli locale:import
WARNING: The LETSENCRYPT_HOST variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_EMAIL variable is not set. Defaulting to a blank string.
Starting azuracast_redis_1 ... doneone
Starting azuracast_stations ...
Starting azuracast_stations ... done
2020/05/27 17:37:17 Waiting for: tcp://mariadb:3306
2020/05/27 17:37:17 Waiting for: tcp://influxdb:8086
2020/05/27 17:37:17 Waiting for: tcp://redis:6379
2020/05/27 17:37:17 Connected to tcp://influxdb:8086
2020/05/27 17:37:17 Connected to tcp://redis:6379
2020/05/27 17:37:17 Connected to tcp://mariadb:3306
Locales imported.
2020/05/27 17:37:18 Command finished successfully.

**AzuraCast/resources/locale/compiled** - Previously, when you do commands, all the files that were generated were listed, now they are not listed or compiled, I updated the entire file folder with git today and updated all the containers and still nothing changes, what can I do to make all translations generated as before ?
frontend - translations.json - the files that are there and the translation it just doesn’t apply and that’s all and if I don’t have enough files, how can I make up for it, if I download everything with git and everything else downloads automatically, do I need to install the whole project again so that everything works? Perhaps the containers do not have the necessary rights to the files and the generation does not go?

**Comment by SlvrEagle23** [comment]
@susl16c As I've said many times before now, I don't know what is wrong with your local development environment. Development environments aren't something we officially support the same way we support production ones, because they differ so greatly from one developer to the next. If you are going to work with a development environment, you should also be able to troubleshoot any problems that may arise within that environment; otherwise, you are creating an undue burden on our support infrastructure.

I will make a deal with you, though: I will look into ways for us to automatically pull down the very latest translations and incorporate them into every built Docker image without needing separate "import locales" commits all the time. That way it won't be dependent on me remembering to import the translations in a timely fashion, so you'll get almost instant translation updates once they occur. I suspect this will also solve the same problem you are looking to solve.

**Comment by susl16c** [comment]
I myself translate and generate everything because you don’t translate a lot in my language and it takes a long time to translate through your service, I’ve made corrections for more than a year and they aren’t in translation anyway, and when I myself generate problems with translation not.

**Comment by SlvrEagle23** [comment]
@susl16c We've continually made improvements to how our strings are processed for translation and included in the application. We now automatically both generate and import translations every time we build our Docker images. As long as you're using the (recommended) Docker installation, you should always have access to up-to-date strings in the image itself.

This isn't always the case if you're pulling the files directly for development; we only periodically update the translations in the repository itself due to that being a manual process on our end.
