### ISSUE TITLE
Prompt on update to BACK STUFF UP

### ISSUE THREAD

**Issue by CodeSteele** [AzuraCast/AzuraCast#2756]
OK, so a common issue we're having is people upgrading their systems with no backup, experiencing an issue (a bug, a problem, whatever), and coming here and causing panic attacks with our team.

So ideally:

- When we update, we want to reach into the container and check for a global variable on when the last backup was run (ponder how tight we want this to be, past 24 hours for a Y/N warning?)
- Maybe even require the user to basically consent via a message, not Y/N, eg "I KNOW WHAT I AM DOING AND HAVE NO BACKUP"
- Maybe add some kind of non-interactive mode that we don't put on the basic update page that people like me that:
  1) Have automatic updates
  2) Have automatic VM level backups
  Can use.

Ideally, we want to basically make it so we can turn away "emergency" support requests outside of very edge-case issues where we may ship something that _completely_ breaks a lot of installs.

May also include popup modals on login when backups haven't been run in so long, open for more input on this though.

**Comment by CodeSteele** [comment]
A note that popped into my head during #2708 is how _critical_ it is for backups to be in place because MySQL _CANNOT SAFELY RETURN FROM A FAILED MIGRATION_, right now our only option is to basically hand-migrate the system which is something we never ever ever ever want to do with the number of installs we have out there. A botched migration should _always_ have the support response of "restore from backup".

**Comment by CodeSteele** [comment]
@SlvrEagle23 had just suggested on chat to just backup the DB automatically and rollback to that during a migration error, it helps with MySQL rollback issues.

We do run into an issue though: having only an AzuraCast backup zip file doesn't save us from a bad upgrade, let's say we introduce a bug on master and it breaks say, playing music, just all of it. If you've upgraded you're images are new and can't be rolled back (easily), your backup is useless, you're still offline and everyone is screaming that their stations are down.

Hmm, is there an easy way for us to hot-swap tags for images we pull? Will discuss later today.

**Comment by SlvrEagle23** [comment]
@CodeSteele I have added two items to address this issue:
 - An alert message inside the application itself that warns if a backup has not been run in the last 2 weeks and appears on the dashboard of any user with the appropriate permission to view the "Backups" page inside the application itself; and
 - A confirmation message that says "Please make sure your AzuraCast installation is backed up before updating. Continue?" with a Y/N prompt during the update process. Unfortunately, because the information on the most recent backup is contained inside the database (and thus inside Docker itself), checking it at that point in the update process would break one of the core benefits of our existing update process, which is that it can repair a "broken" Docker installation in many cases.

Even with the added prompts, scripts wanting to automate the update process can still do so by running something akin to:
```bash
cd /var/azuracast
./docker.sh update-self
yes '' | ./docker.sh update
```
