### ISSUE TITLE
Installation failed because it tries to access the wrong server

### ISSUE THREAD

**Issue by ScorpionDevDE** [AzuraCast/AzuraCast#2782]
Hey there!

I've installed AzuraCast once on my Debian 9.4 VPS without any problems and had to reinstall my VPS due to Server Issues and wanted to install AzuraCast again after i've reinstalled the whole system.
I've tried it like i'd before where everything was fine and now it has an Problem with three dependencies wich seems to not comming available. The Setup Utility tries to connect to another IP address (172.x.x.4) wich seems to be an local address but my IP is like 138.x.x.228.  I use the docker self installation script so i dont know why this is now an issue and not when i'd installed this for the First time.

Here do you find the [Installation Log](https://pastebin.com/uV91KLbc)

I hope you can help me find an solution for this.

**Comment by SlvrEagle23** [comment]
@ScorpionDevDE When the Docker container initially spins up, it tries to connect to the 3 containers it needs to operate (MariaDB, Redis and InfluxDB)...since it's stuck waiting on port 3306, that suggests that your MariaDB container isn't working correctly.

Try running `docker-compose logs -f mariadb` and seeing if there's any additional information there.

**Comment by ScorpionDevDE** [comment]
It just fixed itself by waiting some time
