### ISSUE TITLE
Not a bug just a question really

### ISSUE THREAD

**Issue by XLRradio** [AzuraCast/AzuraCast#2784]
I have looked through and it looks like a great automation coming along here well done so far guys. just a quick question 
Does it support news feeds atall as we have news delivered via dropbox how can that  be inserted?

**Comment by SC2Mitch** [comment]
Nope, it only supports MP3 streams

**Comment by SlvrEagle23** [comment]
@XLRradio Do you mean you have a folder of audio clips somewhere out on the web that you're wanting to pull from as a source of a playlist?

Currently this isn't exactly possible due to some issues we're having with remote URL playlists, but it's something that we definitely endeavor to be able to do in the future. You may want to submit your request over on https://features.azuracast.com/ so it can be voted on alongside others.

**Comment by XLRradio** [comment]
No I am not meaning a mp3 out on the web I am meaning getting an mp3 from dropbox to azuracast every hour to play the news in  a playlist

**Comment by SlvrEagle23** [comment]
@XLRradio That would likely be something very similar to a Remote URL playlist, or you could set up a script to copy the file from Dropbox over to AzuraCast. We have an API that allows a significant number of file and playlist operations to be done completely by any program with an API token.
