### ISSUE TITLE
Encoding for Cyrillic symbols

### ISSUE THREAD

**Issue by garyanikin** [AzuraCast/AzuraCast#2798]
![czfSlPDnBpI](https://user-images.githubusercontent.com/8394041/80963777-508d0580-8e18-11ea-96dc-fb8136d998e8.jpg)

I am uploading mp3 files with Russian filename from mac OS.
Uploading with Safari from web panel.
Why it can be? Azuracast web UI woking on Russian language, problem only with uploading files (when tracks are playing they still have broken encoding)
Help me pls 🙏

I have installed russian language pack on server (Ubuntu 16.04)
https://gist.github.com/garyanikin/7e3adbd83ea34c6d1781dd81d3b1825d
It doesn't solve the problem

**Comment by Vaalyn** [comment]
All file names from uploaded files are automatically sanitized through [this method](https://github.com/AzuraCast/AzuraCast/blob/80e5f4efac4a5818825eb2b7179fff0dc1beed59/src/File.php#L35) in order to prevent exotic file names causing unexpected issues.

You can enable the `Title` and `Artist` column to better work with those files:
![image](https://user-images.githubusercontent.com/13745863/80976133-5805dc00-8e23-11ea-9a76-15a30201bf0f.png)

This will show you the Artist and Title as set in the ID3 tags of the file.

> when tracks are playing they still have broken encoding

Can you post a screenshot of what AzuraCast is showing when playing one of those files?
Is it showing the sanitized filename as the title? Have those songs a title and artist set in the ID3 tags?

**Comment by garyanikin** [comment]
![Снимок экрана 2020-05-09 в 19 53 29](https://user-images.githubusercontent.com/8394041/81479869-c6390d00-922e-11ea-9228-097d94265bd4.png)
still not wotking. I got fresh install on digitalocean (with one click app) and get same error.

this is file I trying to upload
https://dropmefiles.com/pd5A8

**Comment by petrix** [comment]
Hi guys, I'm also using this engine with only Cyrillic content, and was rename may be 20%-30% from uploaded files by copy/paste method in "edit metadata" window. Most cyr. meta-tags looks good.

**Comment by garyanikin** [comment]
I am using Russian songs and all Russian songs has problem with encoding. Like at screenshot I provided earlier.

**Comment by dubloid** [comment]
> Я использую русские песни, и все русские песни имеют проблемы с кодировкой. Как на скриншоте, который я предоставил ранее.

Если вы не хотите испытывать проблем с любым софтом - не используейте НИГДЕ кириллические символы. К сожалению большинство стандартов кодировок написаны под латиницу.

**Comment by garyanikin** [comment]
I found a workaround, uploading music tracks with FTP will not break Cyrillic characters.
