### ISSUE TITLE
New Version - how to use api to update now playing

### ISSUE THREAD

**Issue by seanbts** [AzuraCast/AzuraCast#2801]
Hi guys,

Can anyone tell me how to use the new feature of updating now playing via the api. When i look at the api, i only see an option to get now playing info and not post?

Thanks

**Comment by pascalla** [comment]
This was in the Github Issue that was raised #2249
----

The endpoint's URL is:

http://your-azuracast-install/api/station/(station_id)/nowplaying/update

This endpoint is excessively permissive since it's being used by automated software where you likely can't control the full nature of the request being submitted, so requests are accepted using either GET or POST HTTP methods.

You can, either via query string or POST form parameters, update the following metadata: 'title', 'artist', 'duration', 'song_id', 'media_id', 'liq_amplify', 'liq_cross_duration', 'liq_fade_in', 'liq_fade_out', 'liq_cue_in', 'liq_cue_out'.

You can also append the API key itself via a query parameter or form parameter named api-key. The user who executes this request must have the "Manage Station Broadcasting" permission, since it's able to basically control the entire metadata output of the station.
