### ISSUE TITLE
Mounting a directory into a station

### ISSUE THREAD

**Issue by Alias1975** [AzuraCast/AzuraCast#2826]
Hi i follow this https://www.azuracast.com/help/docker/#mounting-a-directory-into-a-station

when i try to up docker, it return this

**service must be mapping,  not a NoneType**

**Info**
Ubuntu 18.04
The share folder is a mounted path.
By terminal linux when i try to list the shared folder i see all (so it's work fine)

in the overide.yml file i change <stations_name> with  real name station.

it a bug?

**Comment by SlvrEagle23** [comment]
@Alias1975 It's likely a formatting error in your `docker-compose.override.yml` file. Can you paste its full contents here?

**Comment by Alias1975** [comment]
```
# docker-compose.override.yml
version: '2.2'
services:
web:
volumes:
- /home/liquidsoap/rep:/var/azuracast/stations/archivio/media/
stations:
volumes:
- /home/liquidsoap/rep:/var/azuracast/stations/archivio/media/
```


**archivio** is the name of station on azuracast

**Comment by Vaalyn** [comment]
Your docker-compose.override.yml is indeed wrongly formatted.

The spaces that you can see in front of the lines on the help page that you followed are not optional.

In order to fix this issue you need to make sure to add those spaces (when adding those spaces don't use tabs, those are not allowed in a docker-compose file).

The easiest way should be to just copy and paste the config from the help page and then modifying the parts that need to be modified.

**Comment by Alias1975** [comment]
Vaalyn thanks a lot!

**Comment by Alias1975** [comment]
Sorry if i reopen issue...

now docker stars but when I try to view the music files it remains in constant loading.
![loading1](https://user-images.githubusercontent.com/28431738/81669844-14285d80-9447-11ea-878d-f2582aa8edf2.png)

While if I try to log in with sftp I will be this error:
Unable to open .: permission denied

when i try open mount folder by command line:
**ls /home/liquidsoap/rep**
i see all files.

**Comment by Alias1975** [comment]
Solved it...
when you build the docker you must have administrator privileges to access the folders under the mount
