### ISSUE TITLE
Radiolize playlist download

### ISSUE THREAD

**Issue by Niphredil666** [AzuraCast/AzuraCast#2837]
hi there, I'm new to all this and i have an issue. I can't find anywhere on my profile where and how I disable the downloading of my playlist on my radio for any listener. Can you please help?
thank you

**Comment by Vaalyn** [comment]
What kind of playlist download do you mean, the downloading of the .pls file on the public player page or the new on-demand playlist download feature?

For the .pls file you could hide the button via custom CSS that you can add via the `Administration` -> `Custom Branding` -> `Custom CSS for Public Pages`.

The on-demand feature can be activated/deactivated in the station profile.

**Comment by Niphredil666** [comment]
Thank you for responding...
I just talked to an agent of radiolize and he told me that it's not possible to disable it and people can download my playlist if they like from my public page. It's not appearing however on the webdj platform. There's no "administration" option anywhere though... Sorry for the silly questions...I'm a noobie :P

________________________________

**Comment by Vaalyn** [comment]
That's essentially true, you can't really disable the downloading of the .pls file but the button on the player can be hidden via CSS.

Since you are using a reseller and have no access to the administration of your installation you'd need to talk with your reseller to get them to add Custom CSS for your public pages only (this is possible since every station has css class set on the body tag that is unique for your station).
