### ISSUE TITLE
Permission denied when deleting from waiting queue

### ISSUE THREAD

**Issue by TheRealMakkus** [AzuraCast/AzuraCast#2860]
**Using Docker installation method**

Yes

**AzuraCast version**

v0.10.2, #5102ce8 (2020-05-10 7:34)

**Host Operating System**

Debian

**Describe the bug**

I can't delete files in the waiting queue. If I try this, nothing happens. After that, the following error can be find in the Azuracast-log: 
Permission denied. {"file":"/var/azuracast/www/src/Middleware/Permissions.php","line":45,"code":0} []
**To Reproduce**

1. Click on "Tools", "Warteschlange" (i have the german translation)
2. Choose a track and click "Löschen" 
3. Confirm by click "Löschen" again
4. Nothing happens, error is added to the error-log

**Expected behavior**

The track should be deleted from queue. this worked before. i don't know when or with which update, but it does not work anymore.

**Relevant Logs**

Permission denied. {"file":"/var/azuracast/www/src/Middleware/Permissions.php","line":45,"code":0} []
**Screenshots**

**Device(s):**
 - Device:  Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version: Newest

**Additional context**

**Comment by SlvrEagle23** [comment]
@TheRealMakkus The permission required to manage the queue is "Manage Station Broadcasting". We had a minor error in which you could see the Queue management page even if you didn't have that permission, but none of the API actions would work because there is a second permission check that happens there. We've fixed that issue, so you should only be able to see the queue page now if you have the appropriate permissions to manage it.

**Comment by TheRealMakkus** [comment]
@SlvrEagle23 thank you for your reply. 

Could you explain, what i have to do, to have the permission? I thougt, it is included in the Super-Administrator.
