### ISSUE TITLE
500 Call to a member function getId() on null Liquidsoap.php : 114

### ISSUE THREAD

**Issue by tsisma** [AzuraCast/AzuraCast#2871]
When i'm trying to change autodj settings, for example to change thew crossfade time i get this result

**Comment by SlvrEagle23** [comment]
@tsisma Can you include the full error message, and also be sure to include the information you left out from the original GitHub issue template (i.e. your installed version of AzuraCast, whether you're using the Docker installation, etc)

**Comment by tsisma** [comment]
It was only on a specific station! another message when i tried to deactivate the liquidsoap from the main panel was "this service is not recognised". So i deleted the station and i create it again. everything is fine now

**Comment by WayOutt** [comment]
Debian 11.Docker version 19.03.11, build 42e35e61f3.
Azurcast is latest rolling version
 * Environment: Production
 * Installation Method: Docker

Restarting all radio stations...
--------------------------------

 0/1 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%[2020-06-13T11:42:55.965905+00:00] AzuraCast.INFO: Writing playlist file to disk... {"station":"Radio Waytt","playlist":"tech"} []
[2020-06-13T11:42:56.435813+00:00] AzuraCast.INFO: Writing playlist file to disk... {"station":"Radio Waytt","playlist":"random"} []
[2020-06-13T11:42:57.199087+00:00] AzuraCast.INFO: Writing playlist file to disk... {"station":"Radio Waytt","playlist":"prog"} []
[2020-06-13T11:42:57.950467+00:00] AzuraCast.INFO: Writing playlist file to disk... {"station":"Radio Waytt","playlist":"House Party"} []
[2020-06-13T11:42:57.983931+00:00] AzuraCast.INFO: Writing playlist file to disk... {"station":"Radio Waytt","playlist":"Mixes"} []
[13-Jun-2020 11:42:58 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /var/azuracast/www/src/Radio/Backend/Liquidsoap.php:114
Stack trace:
#0 /var/azuracast/www/src/Radio/Backend/Liquidsoap/ConfigWriter.php(494): App\Radio\Backend\Liquidsoap->annotateMedia()
#1 /var/azuracast/www/src/Radio/Backend/Liquidsoap/ConfigWriter.php(225): App\Radio\Backend\Liquidsoap\ConfigWriter->writePlaylistFile()
#2 /var/azuracast/www/src/DeferredCallable.php(45): App\Radio\Backend\Liquidsoap\ConfigWriter->writePlaylistConfiguration()
#3 /var/azuracast/www/vendor/symfony/event-dispatcher/EventDispatcher.php(251): App\DeferredCallable->__invoke()
#4 /var/azuracast/www/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#5 /var/azuracast/www/src/Radio/Backend/Liquidsoap.php(41): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#6 /var/azuracast/www/src/Radio/Configuration.php(90): App\Radio\Backend\Liquidsoap->write()
#7 /var/azuracast/www/src/Console/Comma in /var/azuracast/www/src/Radio/Backend/Liquidsoap.php on line 114
2020/06/13 11:42:58 Command exited with error: exit status 255

**Comment by SlvrEagle23** [comment]
@WayOutt The latest fix just pushed should resolve the null pointer error you're getting, but the more important question is why you're getting it in the first place...in our system all Media records should have corresponding Song records, no matter what. If your Media was processed without one, it would indicate an error in processing.

Did you clone your station from another station? That may be the only way I can think of that such a thing would happen.

**Comment by WayOutt** [comment]
> @WayOutt The latest fix just pushed should resolve the null pointer error you're getting, but the more important question is why you're getting it in the first place...in our system all Media records should have corresponding Song records, no matter what. If your Media was processed without one, it would indicate an error in processing.
> 
> Did you clone your station from another station? That may be the only way I can think of that such a thing would happen.

Station made it from scratch.working more than 6 month
The error appeared about a week ago.
WebUI is not available ---
Proxy error
The proxy server could not handle the request
Reason: Error during SSL Handshake with remote server ---
Reverse Proxy - Apache
But,if direct playing  in music players without ssl - work -- http://10.10.10.7:125/radio/8000/music.ogg
My .env ----
COMPOSE_PROJECT_NAME=azuracast
 
 AZURACAST_HTTP_PORT=125
 AZURACAST_HTTPS_PORT=500
 COMPOSE_HTTP_TIMEOUT=320
 AZURACAST_FTP_PORT=
 AZURACAST_HOSTNAME=radio.tld
 AZURACAST_VERSION=latest
 AZURACAST_SFTP_PORT=522
So, i starting from scratch,because latest update is not help.
P.S. Sorry for my English.

**Comment by SlvrEagle23** [comment]
@WayOutt Those are some interesting ports you're using...when you're using the WebDJ, you must use a HTTPS port, so we automatically append the "https://" prefix to the base URL to try to accomplish this, which for most cases it does.

The problem in this case is that your HTTPS URL isn't the standard 443. The reason we don't just automatically use the `AZURACAST_HTTPS_PORT` value when determining this URL is because many people set it to a nonstandard port with the intention of putting a reverse proxy in front of AzuraCast somewhere else on the host computer. In this case, we would be adding an incorrect port number that wouldn't correctly point to their public URL.

**Comment by WayOutt** [comment]
> 
> 
> @WayOutt Those are some interesting ports you're using...when you're using the WebDJ, you must use a HTTPS port, so we automatically append the "https://" prefix to the base URL to try to accomplish this, which for most cases it does.
> 
> The problem in this case is that your HTTPS URL isn't the standard 443. The reason we don't just automatically use the `AZURACAST_HTTPS_PORT` value when determining this URL is because many people set it to a nonstandard port with the intention of putting a reverse proxy in front of AzuraCast somewhere else on the host computer. In this case, we would be adding an incorrect port number that wouldn't correctly point to their public URL.

Unfortunally It's not standalone Azuracast server, so i must change standart ports.
Anyway,i starting from scratch,and now must all works :) 
Strange trouble with https,but i decide proxied  http port.
Thank you for your participation,and for this great product!
