### ISSUE TITLE
Song history It does not work properly

### ISSUE THREAD

**Issue by leoallvez** [AzuraCast/AzuraCast#2872]
**Using Docker installation method** Yes

**AzuraCast version** v0.10.2

**Host Operating System** Ubuntu 18.04

**Describe the bug**
When a request is made to the API at the end-point get: **/now_playing/{station_id}** the **song_history** field often does not bring all the music played, leaving minutes or even hours without updating this data. And even on the public page of the system, these data are also not updated. And even when there is an update, the songs played are omitted and only the last one played is recorded, that is, there is an inconsistency of data.

**To Reproduce**
Follow the update of  [the public page](https://geekghost.com.br/public/space42) to see that there is no consistency with what is touched with the history list, or make a request in the api at the same URL.

**Expected behavior**
When you make a request on the get: **/now_playing/{station_id}** endpoint to actually bring the songs played without omitting any.

**Relevant Logs**
I didn't find anything relevant in the logs.
![log](https://res.cloudinary.com/dtlzzjz1a/image/upload/v1590259132/log_xig5kj.png)

**Device(s):**
 - Device:  Desktop 
 - OS: Windows 10 
 - Browser: mozilla firefox

**Comment by SlvrEagle23** [comment]
@leoallvez Is the song history intact if you look at the Song Playback Timeline in your station's "Reports" page, or is it also missing large periods of time as well?

If so, this could be caused by something causing your Now Playing synchronization task to not run correctly during those periods. I would look at the System Administration page and look at the last run time of the Now Playing task, and make sure it's within 0-30 seconds of the current time; if not, manually running it may reveal an error being caused.

**Comment by leoallvez** [comment]
The music execution time line in "Report" is ok, in system administration the last performance is within the established time.

**Comment by leoallvez** [comment]
I decided to use another endpoint that brings the songs (GET: / station / {station_id} / history), so I am no longer interested in the one who presented the problem, anyway I appreciate the help.
