### ISSUE TITLE
Cloudflare IPs

### ISSUE THREAD

**Issue by Mrdevy** [AzuraCast/AzuraCast#2886]
Hello,

On our listeners its only showing cloudflare IPs and not the actual listeners IP. We moved to a new server and previously didn't have the same issue yet our configuration remains the same?

**Comment by zivanovicMilan** [comment]
You may use the CloudFlare caching, but it will not be stable enough and since the audio stream consumes a lot of bandwith, you are risking to be blocked.

The statement in AzuraCast help is probably incorrect:
> The nature of streaming radio means it's all but impossible for a service like CloudFlare to cache the radio signal itself using its servers; instead, it passes all of this traffic through to your server directly. 

It is cached actually. I've tried CloudFlare and StackPath. The stream works for a few hours, but then it stops. All traffic is going through CDN servers and it is logged in the bandwith report. And I was in contact with StackPath support, they claim that there is no way to use a CDN and to "force" audio stream to go directly from server to listener. It's impossible to stream to a client and show CDN's address at the same time.
