### ISSUE TITLE
The removed file plays a few hours after

### ISSUE THREAD

**Issue by bebjakub** [AzuraCast/AzuraCast#2892]
**Using Docker installation method** Yes

**AzuraCast version** v0.10.2, #ee997ef (2020-05-22 5:35)

**Host Operating System** Ubuntu 18.04

**Describe the bug**

When I removed a file, it still was played a few hours after in a scheduled playlist. For removal, I used AzuraCast's Music Files administration. The problem occurs just in the last few days. Thank you!

**Comment by RadiateTC** [comment]
I'm having this problem aswell, i've been manually removing my songs through FTP since a couple (days?week)

**Comment by SC2Mitch** [comment]
After removing a song did you restart the station?

**Comment by bebjakub** [comment]
@SC2Mitch no, I didn't restart. Is it required?

**Comment by SC2Mitch** [comment]
Generally yes, it fully clears the liquidsoap functions and should play as normal.

**Comment by SlvrEagle23** [comment]
@bebjakub Are they actually _playing_ after you delete them from the filesystem? That shouldn't be possible, since removing something via SFTP actually does remove it directly from the filesystem, which means even if AzuraCast isn't "caught up" with the media folder changes, Liquidsoap still wouldn't be able to locate the file or play it.

**Comment by bebjakub** [comment]
@SlvrEagle23 yes, they are playing after deletion. But I'm using `delete` button in the Music Files section. I thought that the file is removed from the filesystem also in this way...
