### ISSUE TITLE
Certbot Let's Encrypt SSL Certificate

### ISSUE THREAD

**Issue by esmondgh** [AzuraCast/AzuraCast#2902]
Using Docker installation method:
Yes

Host Operating System:
Ubuntu 18.04

AzuraCast Version:
0.10.2

Question:
How to make AzuraCast use Let's Encrypt SSL certificate generated with Certbot at this directory?.
etc/letsencrypt/live/example.com

**Comment by Vaalyn** [comment]
You can refer to [this issue](https://github.com/AzuraCast/AzuraCast/issues/2855), more specifically the `Using Custom Certificates` section.

Since you are already using Let's Encrypt in general you might just want to use the built-in Let's Encrypt support via `./docker.sh letsencrypt-create`.

**Comment by esmondgh** [comment]
I can't get this to work on my docker installation.
Can you explain further what to change in the below path?.

- /path/on/host/to/ssl.crt:/etc/nginx/certs/yourdomain.com.crt:ro
- /path/on/host/to/ssl.key:/etc/nginx/certs/yourdomain.com.key:ro

![custon_certificates](https://user-images.githubusercontent.com/42568091/83718436-8c3c0a80-a624-11ea-8edb-ba91cef524db.jpg)

**Comment by biguenique** [comment]
**I managed to get some positive results by replacing `yourdomain.com` by `default` (`default.crt` and `default.key`).**
____
I've set up a new AzuraCast instance alongside a CyberPanel install. Since I can't assign the default ports 80 and 443 for AzuraCast, that makes using the internal Let's Encrypt support complicated. Hence, the need to specify a certificate issued outside of AzuraCast.

I managed to [create a reverse proxy](https://blog.cyberpanel.net/2019/02/12/reverse-proxy-traffic-to-docker-container-on-cyberpanel/) in CyberPanel, which takes care of issuing and renewing the certificates.

For some obscure reason, I couldn't get the `nginx_proxy` (Web Proxy part) working properly with those certificates, but at least I can now specify the `default` certificates to the `stations` container, making Icecast render valid HTTPS streams (without the need to rely on AzuraCast's web proxy) !

So with the `web` interface proxied by CyberPanel, the Icecast stations serving valid HTTPS, and Azuracast's Web Proxy disabled, I got AzuraCast running properly. The streams are secure, websocket is working.

There are a few 'funny' things in AzuraCast : one is that it keeps generating proxied URLs (eg. a station's *Admin URL*) even when Web Proxy is disabled. I had to create some RewriteRule to redirect such URLs to their actual station's Icecast ports.

Note that my current workaround would probably not work with CloudFlare.

Sorry if this all sounds a tad confuse or too specific, but I thought my recent 'discovery' about the cert/key naming might help someone.
