### ISSUE TITLE
500 Error on Edit Station

### ISSUE THREAD

**Issue by aripisprecer** [AzuraCast/AzuraCast#2909]
**Using Docker installation method**
Yes

**AzuraCast version**
AzuraCast • v0.10.2, #c4e482c (2020-05-25 5:23) • Docker • PHP 7.4

**Host Operating System**
Ubuntu 20.04 x64 LTS

**Describe the bug**
I want to change a station config to activate auto dj and when i want to save the config, i get 500 error, complaining that the Field 'include_in_on_demand' doesn't have a default value
AbstractMySQLDriver.php

**To Reproduce**

**Expected behavior**
The config should be saved correctly

**Relevant Logs**
500

An exception occurred while executing 'INSERT INTO station_playlists (station_id, name, type, source, playback_order, remote_url, remote_type, remote_timeout, is_enabled, is_jingle, play_per_songs, play_per_minutes, play_per_hour_minute, weight, include_in_requests, include_in_automation, backend_options, played_at, queue) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [10, "default", "default", "songs", "shuffle", null, "stream", 0, 1, 0, 0, 0, 0, 3, 1, 0, "", 0, "N;"]: SQLSTATE[HY000]: General error: 1364 Field 'include_in_on_demand' doesn't have a default value
AbstractMySQLDriver.php : 103

**Comment by SlvrEagle23** [comment]
@aripisprecer Duplicate error to #2846, appears to be caused by installing the latest rolling-release version and then rolling back to a stable release version after it's already installed, which doesn't include that migration.

Per the instructions in that thread, you should only update to release versions either upon a brand new installation or when a new release version is tagged (one will be tagged shortly) to avoid this type of problem.
