### ISSUE TITLE
Errorlog Items

### ISSUE THREAD

**Issue by RemBdev** [AzuraCast/AzuraCast#292]
Hello,

I was looking in the errorlog and saw a few errors likely of the previous error. Everything is working fine.

**HTTP ERROR 500**
Url: _/admin/stations/edit/1_
When: _Onsave (Advanced: Custom Configuration), but the things are saving in the databse._
![image](https://user-images.githubusercontent.com/29834979/33212050-8d6f1d50-d121-11e7-834c-6aead3cd3cfb.png)

**Another error**
I don't know where it comes from (I guess media), but it works fine.
![image](https://user-images.githubusercontent.com/29834979/33212104-d34210b2-d121-11e7-8730-5e6131d387b6.png)

**Comment by SlvrEagle23** [comment]
@RemBdev It appears a majority of these errors are caused by large music collections with a substantial amount of album artwork; the memory consumption of all pages is _well_ within the normal memory constraints, but when attempting to load the artwork as well, it overloads the scripts easily.

I've pushed up an update that moves the album artwork into its own standalone database table, which significantly relieves the memory usage of the main table.
