### ISSUE TITLE
Create new playlist error: An error occurred and your request could not be completed.

### ISSUE THREAD

**Issue by dubloid** [AzuraCast/AzuraCast#2929]
Using Docker installation method
Yes

AzuraCast version
v0.10.2, #c4e482c (2020-05-25 5:23) • Docker • PHP 7.4

Host Operating System
Ubuntu 18.04

Hello!

I got this problem:
Can't add new playlist. When added, it displays the following message:

**An error occurred and your request could not be completed.**

The Azuracast Application Log file has this error:

`[2020-06-05T17: 57: 32.537488 + 00: 00] AzuraCast.ERROR: An exception occurred while executing 'INSERT INTO station_playlists (station_id, name, type, source, playback_order, remote_url, remote_type, remote_timeout, is_enabled, is_jingle, play_per_songs , play_per_minutes, play_per_hour_minute, weight, include_in_requests, include_in_automation, backend_options, played_at, queue) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,? ,?,?,?) 'with params [1, "test", "default", "songs", "shuffle", null, "stream", 0, 1, 0, 0, 0, 0, 3, 0 , 0, "", 0, "N;"]: SQLSTATE [HY000]: General error: 1364 Field 'include_in_on_demand' doesn't have a default value {"file": "/ var / azuracast / www / vendor / doctrine /dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php","line":103,"code"cript} []`

Please help me solve the problem.
Thank you very much!

**Comment by SlvrEagle23** [comment]
@dubloid I've been seeing several users have a similar issue, but our updater always tries to run database migrations during the updating process (which is the problem you're experiencing here, that database migrations haven't run)...

Can you tell me the steps you follow when updating? Can you try updating again to see if it fixes things?

**Comment by dubloid** [comment]
Hello!
I update the commands:
cd /var/azuracast
./docker.sh update-self
./docker.sh update

Before the upgrade, I deleted the problematic migration entry from the database.
During the update, there was no longer an error with magrading, but it’s still impossible to create a new playlist:

`AzuraCast.ERROR: An exception occurred while executing 'INSERT INTO station_playlists (station_id, name, type, source, playback_order, remote_url, remote_type, remote_timeout, is_enabled, is_jingle, play_per_songs, play_per_minutes, play_per_hour_minute, weight_options include, include, options, include queue) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,) 'with params [1, "test "," default "," songs "," shuffle ", null," stream ", 0, 1, 0, 0, 0, 0, 3, 0, 0," ", 0," N; "]: SQLSTATE [HY000]: General error: 1364 Field 'include_in_on_demand' doesn't have a default value {"file": "/ var / azuracast / www / vendor / doctrine / dbal / lib / Doctrine / DBAL / Driver / AbstractMySQLDriver.php" , "line": 103, "code": 0} []`

**Comment by gammaw** [comment]
I have the the same issue after upgrading to v0.10.2 on the last stable commit (c4e482c). We did the upgrade a week ago. I remember first forgetting to call `update-self` before `update`. I then called update-self and update again and everything seemed all right. 

I don't know what migrations are but since you mentioned them in your comments I noticed this after re-running update again: 

Can you help me understand what it is? 

![image](https://user-images.githubusercontent.com/28865986/84554893-64caf900-ad1a-11ea-91b0-3e5206c9eed6.png)

**Comment by gammaw** [comment]
Quick addition: on our test server we are on the same commit (last stable 0.10.2) without seeing those migration entries in the update logs and we can create new playlists. So apparently it's not an issue with 0.10.2 itself. Btw, we also tried to run update again (first update-self, then update, just like dubloid reported) but the issue is still there.

**Comment by gammaw** [comment]
Oh I see the duplicates (https://github.com/AzuraCast/AzuraCast/issues/2846, https://github.com/AzuraCast/AzuraCast/issues/2909) and that you managed to trace the root cause back to "downgrading" to the last stable commit. I can also see that for some users re-updating solved the issue, unfortunately not for us. @SlvrEagle23 do you have any suggestion or should we wait until you publish the next stable commit with the migration feature inside? That would fix the issue, if I understand the situation correctly.

**Comment by SlvrEagle23** [comment]
@gammaw I don't know what's causing the migrations to apparently not always run for all users. This is a sporadic issue that only a few folks are reporting, and it definitely isn't good, because the DB migrations should _always_ be checked and updated with every single run of the update command. The only thing that would stop migrations from running is an error earlier in the update process's steps.

We will be releasing a new stable version with the latest fixes included, but I don't have a timeline for that yet due to being overburdened at the moment. In any case, that should help to resolve the issue.

**Comment by dubloid** [comment]
> @gammaw Я не знаю, что вызывает миграцию, которая не всегда выполняется для всех пользователей. Это спорадическая проблема, о которой сообщают только несколько человек, и это определенно не очень хорошо, потому что миграции БД _всегда_ должны проверяться и обновляться при каждом запуске команды обновления. Единственное, что может остановить запуск миграций, - это ошибка на ранних этапах процесса обновления.
> 
> Мы выпустим новую стабильную версию с последними исправлениями, но у меня пока нет графика для этого из-за перегрузки в данный момент. В любом случае это должно помочь решить проблему.

Thanks, Buster!

**Comment by dubloid** [comment]
Solved the problem by completely removing all containers and reinstalling the last stable release. Thanks everyone!

**Comment by gammaw** [comment]
@dubloid is it possible without erasing radio data (songs, playlists etc.)? If yes, how exactly? I'm not super familiar with the lifecycle of docker images and I don't want to risk losing live radio data.

**Comment by SlvrEagle23** [comment]
@gammaw What are you seeing when you run the update process? The migration script should either be running or telling you there are no migrations to run during that process. I'd need to see its output to be able to do anything about it.

**Comment by gammaw** [comment]
@SlvrEagle23 thanks for helping! Does this screenshot in one of my previous comments help? I didn't notice anything else related to this issue during update. If I remember correctly there was some error when I first ran update without calling update-self (like I describe in my comment) but I didn't save the log. Now, I don't see any error when updating but I can re-update for the logs if you need them.

**Comment by SlvrEagle23** [comment]
@gammaw Are you still getting that same "you have 3 executed migrations that aren't registered" error? That suggests you've at some point run the updater on the latest rolling-release but now you're back on the stable channel.

You should definitely run the update again and see if it continues to show that; it's possible you aren't on the latest codebase even still after switching back (possibly you're changing the old `AZURACAST_PREFER_RELEASE_VERSIONS` flag in `azuracast.env`, not the new `AZURACAST_VERSION` in `.env`, which should be removed or set to "latest".

**Comment by gammaw** [comment]
@SlvrEagle23 the server is on the latest stable commit (this is what I see in the footer of the admin page: AzuraCast • v0.10.2, #c4e482c). Also, in `azuracast.env` the flag is removed and we have `AZURACAST_VERSION=stable` in `.env`. 

> Are you still getting that same "you have 3 executed migrations that aren't registered" error? 

Yes, we still have it, I can run update again but I'm not sure it would change anything. 

> That suggests you've at some point run the updater on the latest rolling-release but now you're back on the stable channel.

Yes, this is how it was. When I first ran update without update-self it updated to the latest commit on master. Then I ran update-self and update again, after which we landed on the latest stable commit but with this issue of unable to create new playlists.

**Comment by SlvrEagle23** [comment]
@gammaw Oh, what I meant before is that you have to switch to the _non-stable_ branch, then run the updater, and it should fix it, but after that point you shouldn't go back to the stable branch until we release a new tagged version.

**Comment by gammaw** [comment]
@SlvrEagle23 I see, thanks. I understand that that would fix the create playlist issue but wouldn't it potentially introduce new ones (since it's not a stable commit). We usually spend some time testing a stable commit before updating to it on our live site.  What is your assessment of the "healthiness" of the current head commit on the master?

**Comment by SlvrEagle23** [comment]
@gammaw It has been largely stable for several weeks now and we're about due to have another point release just to wrap up all the latest improvements.

**Comment by gammaw** [comment]
@SlvrEagle23 thanks. Looking forward to it. Maybe we'll wait until the next tagged release, if we can. Even if we test on a certain commit (e.g., tests take 1-2 days), the head commit may be a new one since then, so when we update on the live server it updates to a new commit. But you know how these things work :)

**Comment by SlvrEagle23** [comment]
@gammaw Just tagged a new release, version 0.10.3, since we've had no major infrastructural changes in several weeks now.

**Comment by gammaw** [comment]
@SlvrEagle23 just updated on our live site and all look good again. Thanks!
