### ISSUE TITLE
Fixing NGINX / IceCast proxying issue

### ISSUE THREAD

**Issue by voipworld** [AzuraCast/AzuraCast#293]
Hello Azura team
this is a small issue discovered while using NGINX as a proxy for the /radio/8000 path, to listen to the station through it without exposing the icecast service to the public
the issue is a follow
the client Public IP isnt exposed to the icecast server, so the Azura Panel list it as a private range and unable to localise it using gMap
the fix:
proxy_set_header        X-Real-IP       $remote_addr;
then, in every PHP location like /.php, do the following:
        fastcgi_param REMOTE_ADDR $http_x_real_ip;

at i dont know how to enter the fs of the docker images, i cant try it in my side only if you guide me through the solution to see the config of nginx in the Docker
any help or question?
please shoot ;)
thanks!

**Comment by SlvrEagle23** [comment]
@voipworld We actually already do forward the IP address over to Icecast/Shoutcast via the `X-Forwarded-For` header. In fact, that was a large reason why we switched to the Icecast-KH branch, because it supported reading that header to determine unique listeners, where upstream Icecast didn't.

If you're connecting from the same local network as AzuraCast, such as for local testing, you'll always see "Private Range" as your IP, because even nginx thinks your remote address is actually your LAN address.

**Comment by voipworld** [comment]
Hello @SlvrEagle23
no, i am not from LAN
i am using DigitalOcean droplets
if i do /radio/8000/128k, i see a local ip
but if i do hostname:8000/128k, i can see my public ip
that indicate its a proxying issue...

**Comment by SlvrEagle23** [comment]
@voipworld It seems the latest update to Icecast-KH has caused an issue in properly reflecting the proxied IP through to the Icecast API endpoints. I have created a ticket in the KH github repo, which you can follow at karlheyes/icecast-kh#195

**Comment by SlvrEagle23** [comment]
Update: I've been working on this issue, and it's now known and confirmed for IceCast on the Docker installation method. Shoutcast and traditional installations should not be affected.

To summarize the nature of the issue, IceCast-KH has a whitelist approach to respecting the `X-Forwarded-For` header, otherwise any listener could very well "spoof" the referring IP and possibly create inaccurate listener numbers for reports and royalty payments.

This is normally fine, and even in our traditional installations is fine, because we can just whitelist the single IP (127.0.0.1) where valid proxy requests should come from. With Docker, however, each container has its own internal assigned IP, and the range of IPs that could be used is very broad. Having to hand-code each of these IPs would result in an Icecast configuration file that has several KB just for every possible IP, and would possibly cause big delays in parsing the config file.

Ultimately, the solution to this will be for Icecast-KH to either allow wildcard IPs in its XML configuration (or subnet notation, or some other way of specifying a large range in a single configuration line), or to allow the configuration to say "0.0.0.0", thus allowing any IP to send the requisite header. The latter would match the current behavior of Shoutcast.

**Comment by MyTheValentinus** [comment]
Hello,
Do you have any news from icecast team ?
I tried with shoutcast and icecast, for the both the X-Real-Ip or X-Forward is not working.
I tried to make some configuration to have a correct listener ip but i failed.
I also try with `X-Forwarded-For $proxy_add_x_forwarded_for;` on nginx
Thanks

**Comment by MyTheValentinus** [comment]
Hello !
I don't know why, but from last pull of all images, real ip is good on azuracast !
Amazing

**Comment by MyTheValentinus** [comment]
Hello
I have make PR to fix this issue.
See https://github.com/AzuraCast/docker-azuracast-nginx/pull/1

Thanks

**Comment by SlvrEagle23** [comment]
Hello all!

After some deeper investigation and some help from fellow developer @CodeSteele, we have made a minor modification to the Icecast-KH codebase in order to allow the `X-Forwarded-For` header to be respected regardless of origin, which makes listener IP resolution function properly again when using Icecast with Docker.

This feature is currently being rolled out and should be available to users who are using the up-to-date Docker Compose file format. If you haven't updated your Docker Compose file in a while, it's strongly recommended to either manually apply the changes from the `docker-compose.sample.yml` file into your version, or to allow the Docker utility script to replace your `docker-compose.yml` file with the latest version.
