### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by pree** [AzuraCast/AzuraCast#294]
Hey everyone o/

I wanted to install AzuraCast inside a VM on my own dedicated root server.
Most of the dependencies are already installed in a different VM, like a MariaDB Server, NGINX Webserver, etc.
Is there any guide on how to install AzuraCast manually ?

Best Regards,
Pascal

**Comment by SlvrEagle23** [comment]
@pree AzuraCast has tight dependencies on a number of other pieces of software (Redis, Supervisord, Liquidsoap, Icecast and Shoutcast) and in the case of its radio software, its installer builds the software from source to allow for greater customization than the Ubuntu system packages offer.

Right now, there's no guide for how to install AzuraCast on top of existing infrastructure, because there's a practically infinite combination of existing software that you could be using and it would be very difficult to document every possible interaction. The project is limited in scope by the fact that it's almost entirely a sole-developer effort, so I tend to prefer installations that are less prone to unexpected bugs, hence why I heavily recommend the prebuilt Docker containers in the AzuraCast docs.

The traditional installation (`./install.sh`) uses Ansible under the hood, which you can find inside the `util/ansible` folder. If you have a general understanding of how Ansible works, you can always extrapolate what it's doing in those roles and apply those steps manually, or build a playbook that only runs the Ansible roles that aren't already covered in your infrastructure.
