### ISSUE TITLE
Time of AzuraCast Application Log and Liquidsoap Log are different (2 hours)

### ISSUE THREAD

**Issue by AmsterdamFM** [AzuraCast/AzuraCast#2951]
**Using Docker installation method**

Yes
**AzuraCast version**

AzuraCast • v0.10.2, #7a7fa9e (2020-06-10 22:38) • Docker • PHP 7.4
**Host Operating System**

Ubuntu 16.04
**Describe the bug**

This might not be a bug but now there is a two hour difference between the AzuraCast Application Log (2h behind) and the Liquidsoap Log (on time) of my only station.  Some time ago this difference was one hour. Probably because of daylight saving time.
We live in Central European Time and I think the AzuraCast Application Log is GMT. 

**To Reproduce**

Have a look at the time of the entries of AzuraCast Application Log and  Liquidsoap Log.
**Expected behavior**

The software might handle the difference but I expect these hours to be the same. On a system situated in one time zone and with one station or multiple stations in the same time zone looking at both log files can be confusing. 
**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

Situated in CET (Central European Time)

Should any more information be needed I will be happy to provide it!

**Comment by SlvrEagle23** [comment]
@AmsterdamFM I understand it's confusing, but there's nothing we can do about it at the moment. The logs for Liquidsoap and Icecast are stored on a per-station basis, and so because the entirety of the log will always be about a single station, we can set the station's timezone as the time it logs events in as well. The AzuraCast application log is global, and so we default to the standard for the server itself, which is (and should be) UTC to avoid conversion errors.

We've entertained the idea of splitting our logging out so it logs individual AzuraCast application logs for each station (which would allow us to timestamp those correctly as well), but this is a lot more work than it seems and isn't currently a high priority on our roadmap. You can definitely submit it as a feature request over at https://features.azuracast.com/ for further consideration, though.

**Comment by AmsterdamFM** [comment]
@SlvrEagle23 Thank you for the clear answer. I was totally confused when I first saw this time difference, Would a clear note/warning in the interface at the place where the log files are shown be a good and simpler solution?

**Comment by SlvrEagle23** [comment]
@AmsterdamFM At the moment, the AzuraCast application log is located only on the system-wide log viewer, and in a different place from the per-station logs, which should help separate them a little from an intuitive standpoint. When we implement per-station app logs, they'll be bunched up with the other per-station logs and will be localized to the station time zone.

**Comment by AmsterdamFM** [comment]
Thank you for the clear answer.  But it can be confusing. Maybe it is an idea to at least mention the used timezone in the interface at the log file display locations? Or use UTC internally but convert it to the time zone of the (only) station when displaying the log file? I am not a programmer so I have no idea how much work these last two solutions are,
