### ISSUE TITLE
Cannot upload file via API

### ISSUE THREAD

**Issue by gammaw** [AzuraCast/AzuraCast#2953]
We'd like to upload files and assign playlists to them from Python. This is what we tried:

```
req = requests.post(
            "https://https://myradio.url/api/station/1/files",
            data=dict(path="test.mp3",file="/abs/path/to/some/valid/file.mp3"),
            headers=dict(X-API-Key="valid-api-hash"),
        )
```

The result of the request is 200 and the response looks good too. Indeed, the file will be there in Azuracast but its size is a few bytes only. 

For the playlist assignment, we tried to use the `/station/{station_id}/file/{id}` API (with the ID returned in the previous call) but it didn't work either. 

Are we doing something wrong?

**Comment by gammaw** [comment]
Correction: the playlist update works now, it was a type mismatch in the API call. 

The almost-zero-byte upload result is still an open question.

**Comment by SlvrEagle23** [comment]
@gammaw I will look into this, but you list your URL as starting with `https://https://` which you should definitely fix if it looks like that on your client side.

**Comment by SlvrEagle23** [comment]
@gammaw So...this is marked as "bug" and "in progress" because it's terrible, but the current file upload endpoint is built entirely for use with the Flow plugin that we use to upload files via the web UI. It is possible for you to basically tell it to interpret your upload as a Flow file with a single "chunk" by sending these form parameters:

```
'file' => '',
'flowIdentifier' => 'upload',
'flowChunkNumber' => 1,
'flowCurrentChunkSize' => filesize($file_being_uploaded),
'flowFilename' => 'destination_filename.mp3',
'flowTotalSize' => filesize($file_being_uploaded),
'flowTotalChunks' => 1,
```

...along with a multipart form parameter called `file_data` with the actual contents of the file.

Obviously this makes no sense if you're just making routine API calls, but it's a leftover legacy thing that never got updated to reflect the popularity of the API.

I'm flagging this as a high priority addition.

**Comment by pvj** [comment]
Hi, 

No worries. I wondered something similar myself and even tried figuring out the payload for `/files/upload`. Thanks for the guidance! It worked. For reference, this works: 

```
>>>payload = {
            "file": "",
            "flowChunkNumber": 1,
            "flowCurrentChunkSize": self.play_file_size,
            "flowFilename": self.play_file_name,
            "flowIdentifier": "upload",
            "flowTotalChunks": 1,
            "flowTotalSize": self.play_file_size,
        }
{'file': '', 'flowChunkNumber': 1, 'flowCurrentChunkSize': 4752275, 'flowFilename': '01 Nightsoil.mp3', 'flowIdentifier': 'upload', 'flowTotalChunks': 1, 'flowTotalSize': 4752275}
>>>files = {"file_data": open(self.play_file_path, "rb").read()}
{'file_data': b'ID3\x03(...)'}
>>>req = requests.post(
            "https://our.rad.io/api/station/1/files/upload",
            data=payload,
            files=files,
            headers=self.config["headers"],
        )
>>>print(req.json())
{'success': True, 'message': 'Changes saved successfully.', 'formatted_message': 'Changes saved successfully.'}
```

Results in correctly uploaded file. 

One major benefit of the documented `POST /files` call was though the response which will be missing with this call. The workaround is to then finding `id` from `GET /files` and then use that to get the data needed to assign to playlist from `GET /file/<id>`.

Thanks for marking it w/ high priority let us know here if we should test it but meanwhile don't worry much as this should work reliably. Thanks again && cheers

**Comment by SlvrEagle23** [comment]
@pvj @gammaw I apologize, I actually misspoke when I originally said there was no API-friendly endpoint for file creation. In fact, there is, I just hadn't updated our functional tests to actually use it yet.

The intended API endpoint is actually _much_ easier to use than the Flow endpoint (which I've renamed internally to prevent confusion for future me), and consists of basically this:

```
$song = '/resources/error.mp3';
$I->sendPOST('/api/station/' . $station_id . '/files', [
    'path' => 'error.mp3',
    'file' => base64_encode(file_get_contents($test_song_orig)),
]);
```

I know it's a little weird to base64_encode the file contents like that, but it helps us keep the API from deviating from a RESTful JSON state and using multipart form encoding.

I did find an issue with leading slashes being a problem with the path provided there, and that's now resolved, but our functional tests now use this API endpoint and it appears to be working without issue.

**Comment by pvj** [comment]
Hiya there,

Thanks, this is basically the same request that we posted the Swagger documentation then just needs to updated to display that base64 encoded binaries are expected. Otherwise it's all the same as in your API docs. Which is great! Thanks!! 

For reference, the updated request to `POST /files` like this, works:

```
import base64 

req = requests.post(
            "https://https://myradio.url/api/station/1/files",
            data=dict(path="test.mp3",file=base64.b64encode(open("/abs/path/to/some/valid/file.mp3").read())),
            headers=dict(X-API-Key="valid-api-hash"),
        )
```

However, there still seems to be lingering issue. Posting to Az'Cast 100 MB+ audios seems to result in `32 Broken pipe` error. I've tried wrapping it in some retrys but it never seems to complete like it does when the Flow-based UI upload is used (that correctly continues from the chunk where the upload was dropped). 

It doesn't seem to be any configuration issue on our end. Here's from python interpreter through requests:

```
Python 3.7.7 (default, Mar 10 2020, 15:43:03) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> import os
>>> import base64
>>> p = os.path.join("/abs/path/to/", "test.mp3")
>>> payload={"path":"test.mp3","file":base64.b64encode(open(p, "rb").read())}
>>> headers={"X-API-Key": <valid_hash>}
>>> req = requests.post("https://our.rad.io/api/station/1/files", data=payload, headers=headers)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 987, in send
    self.sock.sendall(data)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe
(...)
(
.
.
.
)
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
```

and here's from curl: 

```
(echo -n '{"path": "t.mp3", "file": "'; base64 /abs/path/to/test.mp3; echo '"}') | curl -vv -H "Content-Type: application/json" -H "X-API-Key: <valid_hash>" -d @- https://our.rad.io/api/station/1/files

* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 413 
< server: nginx
< date: Tue, 16 Jun 2020 14:28:00 GMT
< content-type: text/html
< content-length: 176
* HTTP error before end of send, stop sending
< 
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host our.rad.io left intact
* Closing connection 0
```

Is there anything on our end we could do? Any suggestions? Thank you a bunch already for letting us know to use base64 for files.

**Comment by SlvrEagle23** [comment]
@pvj That's a limit we have in our system to prevent abnormally large files from being uploaded and causing major performance issues with the AzuraCast application. It may be triggering a little earlier than usual on account of the fact that base64-encoding file contents expands their size quite a bit for the sake of portability.

**Comment by pvj** [comment]
@SlvrEagle23 I understand and value that you are safeguarding AC from heavy load.

These past days I've been trying to work around this fact and played w/ both the documented upload API and the flow-related one. Both cases I ended up unsuccessfully trying to upload not medium-sized assets. These are about 90 MBs while we can and easily do upload 500+ MB files through admin interface yet it results in a broken pipe error.

I find this inconsistency weird. Would you consider looking into what could be done to bring these two interfaces closer to each other? Our expectation is not to remove these safeguards just that we can do through API what we can successfully do through the admin interface. 

We tried depending on the undocumented internal API but the results were similar broken pipes. So since it doesn't seem to make a difference we would prefer to and be happy to use the documented API since that returns the uploaded object w/ an `id` already and is much easier to work w/. 

But to be honest from my perspective it doesn't really matter I'm willing to use and work with whatever solution as long as it mirrors the admin behaviour. Thanks for your thoughts, cheers,

**Comment by SlvrEagle23** [comment]
@pvj This actually isn't an inconsistency in how our software is configured...we have the same file size limits everywhere across the system, and when users upload via our public web interface, they use a library called Flow that splits their upload into little chunks and uploads each of those separately. This bypasses size limits on the server side and also improves overall performance and "resumability".

The API that the Flow library connects to is indeed public, and is the other one that we've been referring to in this thread. Reverse-engineering the Flow library is reasonably trivial (it's all managed in a single file inside AzuraCast) if it's absolutely necessary to upload large size files to the system, though how you split those files into chunks is a matter of implementation on your connecting side.

It's my understanding that there isn't really a truly "RESTful" way of doing a chunked file upload that would be in any way unique from how the Flow library handles it.

If it would be helpful, we could implement the same chunking functionality into our `php-api-client` library so it would be easier to integrate into other applications, at least those using PHP and Composer.

**Comment by gammaw** [comment]
@SlvrEagle23 we're experiencing a mysterious issue. We've been successfully using the `/files/upload` API to upload large files. As discussed above, we use this API because the `/files` API doesn't support uploading chunks. 

The trouble is that sometimes the API returns a response 500 and we don't know why. The upload works fine for several files and then suddenly we cannot upload a file and the server keeps returning a 500 response on the first chunk. In this state, the client is stuck and cannot fix the upload, at least we don't know how. 

I checked the logs I know of, I even logged into the `web` container to check  (`app.log` etc.) but didn't find any trace of the error. Any idea what can cause this? 

We're on Azuracast v0.10.3, #9811fbb (2020-06-22 4:38).

**Comment by gammaw** [comment]
We have it! The answer was there in the body of the 500 response: the file could not be moved on the disk, which we found out was due to special characters in the file name. All good, smooth API.

**Comment by Vaalyn** [comment]
Closing as resolved

**Comment by quydox** [comment]
you can try this https://github.com/AzuraCast/AzuraCast/discussions/4853
