### ISSUE TITLE
iFrame player not showing listeners count

### ISSUE THREAD

**Issue by ImaCrea** [AzuraCast/AzuraCast#2965]
Hello there,
thank you very much for this amazing software. This is really a chance to see so much love in a FOSS project. This tool is enabling radios all over the world. We're a music collective and we'll use it this Sunday and without it, we wouldn't able able to throw our show. 

I don't know if it's a bug or more a feature request but is it normal the iFrame player doesn't shown the listeners count? Is there a way we could activate that? Or a way we could retrieve that number easily with some js so we can show it on our website while broadcasting please?

Peace,

**Comment by SlvrEagle23** [comment]
@ImaCrea Thank you for the kind words! Currently, the listener count isn't showed in the public radio player. It's not kept secret (and is visible through public API endpoints), but some stations don't want to advertise the number of listeners connected at the moment.

We have a larger project that's already been submitted via our [FeatureUpvote](https://features.azuracast.com/) to allow for building custom players with various components turned on and off, and we could definitely include listener count as one of those customizable components. We don't currently have a timeline for this feature due to personal issues, however.

**Comment by ImaCrea** [comment]
Thanks for your answer @SlvrEagle23 if you could point me to a codepen showing me how to retrieve counter from API endpoints and display it with js that'd be amazing :)

**Comment by SlvrEagle23** [comment]
@ImaCrea That's a lot of work to be asking me to do, but we do have an informational page for our Now Playing data APIs: https://www.azuracast.com/developers/nowplaying.html
