### ISSUE TITLE
azuracast_www_data folder is missing

### ISSUE THREAD

**Issue by esmondgh** [AzuraCast/AzuraCast#2977]
Using Docker installation method:
**Yes**

Host Operating System:
**Ubuntu 18.04**

AzuraCast Version:
**0.10.2**

**Description:**
In /var/lib/docker/volumes, **azuracast_www_data** folder is missing

Normally it looks like this:
![volumes](https://user-images.githubusercontent.com/42568091/85217386-b3fad480-b37f-11ea-8ace-48038611a4d6.jpg)
Now two folders with random letters and numbers are being generated anytime I do **docker-compose down** and **docker-compose up -d**
![volumes2](https://user-images.githubusercontent.com/42568091/85217414-1522a800-b380-11ea-8fb4-6d37d730046e.jpg)

**Comment by SlvrEagle23** [comment]
@esmondgh This is by design; we no longer consider the `www_data` volume to be necessary, as the AzuraCast image itself contains the latest version of the code, and having a volume override that simply causes unnecessary issues. If you need to modify portions of the application's code, you should create a `docker-compose.override.yml` file that mounts your modified files directly into the filesystem of the container.
