### ISSUE TITLE
Hide Download Button

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#2983]
How can I hide Download button on On-Demand Player?

**Comment by SlvrEagle23** [comment]
@stardevelop We don't currently offer a way to do that from our web interface. Since our streaming audio isn't protected via any type of DRM scheme, anyone who is able to stream it is likewise also able to download it (and really, to our application the two are nearly identical actions), so we display both buttons.

If you would like to see that as a future new feature, you can request it over on our FeatureUpvote site: https://features.azuracast.com/
