### ISSUE TITLE
forcing https on port 8000

### ISSUE THREAD

**Issue by hillbilly-mark** [AzuraCast/AzuraCast#2999]
why are you forcing https on port 8000?  it is not working and broken the public page as well as to any music players wanting the stream.  I guess i have to manually go inside the azuracast nginx proxy and fix that manually delete the redirect.  i just hope this is not something i have to fix after every update.  Can you please stop forcing https on music ports in future releases.  

I love azuracast the most when it is not broken!!!

thanks

**Comment by SlvrEagle23** [comment]
@hillbilly-mark The tone of this message isn't in keeping with our expectations here on GitHub that our users be professional, patient and respectful. We work very hard on this software and give it away for free, and we ask for these things as a bare minimum in response.

Nonetheless, we (AzuraCast) are not intentionally forcing HTTPS on the direct port connections for the stations. It's possible that if you have "Always Use HTTPS" enabled on your AzuraCast installation, then browsers will apply the HTTP Strict Transport Security (HSTS) rule to all ports, which your browser aggressively caches and is somewhat difficult to work around.

In any case, a recent update as of earlier today has made it so that the same SSL certificate that is automatically generated and assigned to your primary web instance is applied to all Icecast servers, so they should properly respond to both HTTP and HTTPS connections via their direct port access once again. This should render this largely a non-issue.

**Comment by ericmil87** [comment]
I have the same problem... commented here https://github.com/AzuraCast/AzuraCast/issues/2855

**Comment by hillbilly-mark** [comment]
@SlvrEagle23

I am sorry I fail to see where you think I was disrespectful.  

I asked the main question, why?  I stated the issues it was causing.  I told you my best workaround and why is did not feel to great.   I even said please with my only suggestion for your end in fixing the problem.  Then, I told you how I love Azuracast.  

So please, inform me just exactly how was my post so offensive to you?  And may I apologize in advance for whatever is in the reply that you find as offensive, as well.   And if you feel I have broken some GitHub expectations of conduct.  By all means, please feel free to report me.

**Comment by fast97** [comment]
> @ hillbilly-mark Le ton de ce message ne correspond pas à nos attentes ici sur GitHub que nos utilisateurs soient professionnels, patients et respectueux. Nous travaillons très dur sur ce logiciel et le distribuons gratuitement, et nous demandons ces choses au minimum en réponse.
> 
> Néanmoins, nous (AzuraCast) ne forçons pas intentionnellement HTTPS sur les connexions de port directes pour les stations. Il est possible que si vous avez "Toujours utiliser HTTPS" activé sur votre installation AzuraCast, les navigateurs appliqueront la règle HTTP Strict Transport Security (HSTS) à tous les ports, que votre navigateur met agressivement en cache et est quelque peu difficile à contourner.
> 
> Dans tous les cas, une mise à jour récente antérieure à la date d'aujourd'hui a fait en sorte que le même certificat SSL qui est automatiquement généré et attribué à votre instance Web principale soit appliqué à tous les serveurs Icecast, afin qu'ils répondent correctement aux connexions HTTP et HTTPS via leur accès direct au port une fois de plus. Cela devrait rendre cela largement non problématique.


> @hillbilly-mark The tone of this message isn't in keeping with our expectations here on GitHub that our users be professional, patient and respectful. We work very hard on this software and give it away for free, and we ask for these things as a bare minimum in response.
> 
> Nonetheless, we (AzuraCast) are not intentionally forcing HTTPS on the direct port connections for the stations. It's possible that if you have "Always Use HTTPS" enabled on your AzuraCast installation, then browsers will apply the HTTP Strict Transport Security (HSTS) rule to all ports, which your browser aggressively caches and is somewhat difficult to work around.
> 
> In any case, a recent update as of earlier today has made it so that the same SSL certificate that is automatically generated and assigned to your primary web instance is applied to all Icecast servers, so they should properly respond to both HTTP and HTTPS connections via their direct port access once again. This should render this largely a non-issue.

Hello by performing the update I have always done no. for ssl to take effect as cited if above I have to do yes? I have an error with (https://live.streamantille.com:8120/stream) but works in (https://live.streamantille.com/radio/8120/stream)
Thank you

*The docker-compose.yml file has changed since your version. Overwrite? This will overwrite any customizations you made to this file? [Y/n]

**Comment by dropthehate** [comment]
For those of you folks having issues with player not working (net::ERR_CERT_AUTHORITY_INVALID in console log) due to localhost self-signed certificate of the stream source url (e.g. domain.com:8000/somestream), you've got to enable "Use web-proxy for radio" in the system settings. 

If that does not work for you try to disable "Always Use HTTPS" in security settings too. 

Spent a couple hours trying to figure this server-side, regenerating certificates etc. and no one tells about this simple fix for some reason, even though there are so many complaints about this and this option even has a hint that says that if you're using SSL you must enable it. 

Why it's not getting enabled by default and why you are allowed to disable it after you generate Let's Encrypt certificates via  `./docker.sh letsencrypt-create` is a completely another topic that should be reconsidered imo. Just make the tickbox checked and don't allow users to disable it or even hide it when Azuracast is running in SSL mode.

**Comment by SmartGuyCodes** [comment]
> For those of you folks having issues with player not working (net::ERR_CERT_AUTHORITY_INVALID in console log) due to localhost self-signed certificate of the stream source url (e.g. domain.com:8000/somestream), you've got to enable "Use web-proxy for radio" in the system settings.
> 
> If that does not work for you try to disable "Always Use HTTPS" in security settings too.
> 
> Spent a couple hours trying to figure this server-side, regenerating certificates etc. and no one tells about this simple fix for some reason, even though there are so many complaints about this and this option even has a hint that says that if you're using SSL you must enable it.
> 
> Why it's not getting enabled by default and why you are allowed to disable it after you generate Let's Encrypt certificates via `./docker.sh letsencrypt-create` is a completely another topic that should be reconsidered imo. Just make the tickbox checked and don't allow users to disable it or even hide it when Azuracast is running in SSL mode.

Thank you. This really helped.
