### ISSUE TITLE
cookiebot in footer einbinden

### ISSUE THREAD

**Issue by Radio-Quergedacht** [AzuraCast/AzuraCast#3004]
cookiebot in footer einbinden

**Comment by Vaalyn** [comment]
In general those cookie banners are for GDPR compliance so I've checked what kind of cookies are created when visiting the public page of a station and there is only the session cookie and the selected volume in the local storage. Since there are no cookies whose purpose is tracking and all the cookies that are set are only used to enable the essential functionality of the page there isn't really a purpose for a cookie banner and under the GDPR essential cookies that are not used for tracking are not subject to the banner requirement.

If you include 3rd party tracking scripts via the `Custom Branding` -> `Custom JS for Public Pages` you can include cookie banner scripts like the one from cookiebot as the first one in that field so that it runs before all your custom scripts.
