### ISSUE TITLE
AzuraCast stops playing if one external relay is down

### ISSUE THREAD

**Issue by mcasviper** [AzuraCast/AzuraCast#3007]
**Using Docker installation method**

Yes
**AzuraCast version**

0.9.9
**Host Operating System**

Ubuntu 18.04
**Describe the bug**

We have external relays configured which are used for redundancy / load balancing purposes. If we restart one of them, azuracast stops playing and begins to play again if the host is up again. Is this a normal/planed behaviour? If all where down it is ok, but one out of three? If this is wanted, what should I do to workaround this?
**To Reproduce**

1. configure 2 or more external relays
2. reboot one of them
3. azuracast stops playing

**Expected behavior**

Azuracast streams as normal on the online relays.

**Comment by SlvrEagle23** [comment]
@mcasviper This question may be better directed at Liquidsoap, since it's an issue with Liquidsoap and not with AzuraCast. My current understanding is that any stream disconnecting will kick the other streams offline as you're describing, but I'm not sure of the specifics of that or how to counteract it.
