### ISSUE TITLE
Move advanced AutoDJ options out of Liquidsoap

### ISSUE THREAD

**Issue by oresot** [AzuraCast/AzuraCast#3015]
Hi AzuraCast team!

I am testing AzuraCast as a replacement of Radio BOSS for our radio. So far seems good, but I'm also facing the issue that scheduled playlist doesn't get played or they do that too late. 

I'm checking the code and trying to debug it, but I see a bit confusing the 2 methods of scheduling playlists: the internal Azura AutoDJ vs Liquidsoap and I think all the functions delegated to Liquidsoap can be served by Azura's AutoDJ.

Is there a reason why options like "Interrupt other songs at scheduled time" or "Only play one track at scheduled time" are not implemented in the internal AutoDJ? Basically I want to know if this idea was discarded because of a good reason or just no-one had time yet to implement it, so I can give it a try.

I've used Liquidsoap for a few years already and this shouldn't be too hard: just tell Liquidsoap the track to play via Telnet or Webhook.

One of my use cases is: our radio have a few sindicated shows or replays of previous live shows scheduled during the day (1h or 2h long), and we want them to always start at the scheduled time, interrupting the song that's being played. Also, we want to only play 1 episode, as sometimes they are a bit shorter, and a 2nd episode will start playing.

**Comment by arulvakku** [comment]
I face the same issue. I need to play some time sensitive programs and Azura DJ sometimes does not do that and waits for the previous program to end and sometimes it takes a lot of time. I am also unable to play just one program at a time. Sometime it repeats the same program again and again.  Options like "Interrupt other songs at scheduled time" or "Only play one track at scheduled time" are not implemented in the internal AutoDJ?

**Comment by SlvrEagle23** [comment]
@oresot @arulvakku Thank you for the questions, and I hope I can provide some insight into our development process thus far with regard to the AzuraCast AutoDJ.

Through the AzuraCast AutoDJ, we can build a look-ahead queue of upcoming songs, which helps us diagnose and debug issues and show the "Playing Next" track in our API responses. It's also possible for us to annotate rich metadata into the tracks that associates them with records in our database, which allows us to provide better API responses. We can also apply changes to playlist settings without needing to restart Liquidsoap, which is a huge convenience to users. This is why we implemented our own AutoDJ in the first place.

There is a fundamental limitation to how our AutoDJ interacts with Liquidsoap, though: Liquidsoap only occasionally polls us for the next track to play, and we provide it with a single annotated URI to play back. This only allows for a very linear process (so you can't layer multiple tracks on top of each other), and also makes some of the advanced functionality exceedingly difficult to implement.

Some of the settings, like "merge tracks to play as a single track" are programmatically possible, they just involve a lot of code that hasn't been a high priority for me to work on. Other settings, like "interrupt other tracks" are very difficult to implement, as this would require looking ahead in the queue to see what _next_ tracks are set to interrupt, and then intentionally shortening the playback length of the tracks before it so it properly does the interruption.

As you can imagine, this is both a lot of code complexity _and_ a lot of surface area for new bugs to pop up. Despite AzuraCast's large scale and overall complexity, it's all maintained primarily by a single developer (me) with occasional contributions from others. It's a lot for one developer to keep in their head. What's more, but the AutoDJ as it exists today has a number of people reporting that it sometimes simply ignores scheduling rules and plays things out of order, and despite a ton of debug information and having spent dozens of hours on that block of code I haven't been able to make any headway into why that's happening. I'm not eager to add more code to something that already prompts complaints about stability, especially if the existing code is apparently too complex for me to "get right" as it is.

If you wanted to dig deep into the AutoDJ functionality and see about making any improvements, I would be happy to collaborate on that process, but so far basically nobody has offered to contribute into that portion of the code. It's not because it's bad code (at least in my opinion, which is to say it isn't "tech debt" code, it's modern and up to our app's standards), it's just because it's complex enough to scare a lot of folks away.

**Comment by amarildoazura** [comment]
Friend I can imagine all this complexity for me it would be enough for me to just run a file of approximately 50 to 1 and a half minutes making an opening of a certain program, for example (that plays Italian music) unfortunately although I have enabled the function ENABLE_ADVANCED_FEATURES = true I still couldn't get this little playlist to run, the countdown appears on the screen, but nothing happens, it is simply ignored.
Pause other songs to play at the scheduled time.
Only play a track at the scheduled time
I checked these two options.
Thanks for the feedback.
Amarildo, Joinville-SC Brazil
