### ISSUE TITLE
Stream live Azuracast  to  facebook

### ISSUE THREAD

**Issue by Radio-Quergedacht** [AzuraCast/AzuraCast#3029]
Stream live Azuracast  to  facebook

**Comment by dxf** [comment]
I don't see this being impossible with some ffmpeg-gery.

See this code-bite from an old issue related to YT streaming.

https://gist.githubusercontent.com/SlvrEagle23/17b2b550f9340c9dd32f4bcd5b128442/raw/4dc9911cf2a82d38e855a68b7ff10a9b7f16db9f/broadcast.sh

Wrapping this into azura would be nice though

**Comment by SlvrEagle23** [comment]
@Radio-Quergedacht We have an example repository we set up with some code that we use to broadcast AzuraCast stations to RTMP live stream destinations, like YouTube (or Facebook Video): https://github.com/AzuraCast/radio-video-stream

We don't currently have any plans to incorporate this directly into AzuraCast due to complexity and difficulty of implementation, and the high resource drain it would produce.
