### ISSUE TITLE
Listeners on google map for restreaming stations

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#303]
A request, if you can make it  possible  also  to see the  listerners on the google maps when restreaming a station. Now it only shows the total listeners on the home page but not showing them on the map

**Comment by SlvrEagle23** [comment]
@surihost Closing for the moment as "not possible", because the detailed listener data that we're able to retrieve from Azuracast-hosted stations is very dependent on the fact that we run specific, controlled versions of both Icecast-KH and Shoutcast. Not only can we not guarantee that a remote restreamed station would be running the proper versions of said software, but gathering the detailed listener data involved would require administrative access, and that would require that we store credentials for someone else's radio server, which is something I'm always hesitant to do.
