### ISSUE TITLE
AzuraCast and WordPress Site on Same Server

### ISSUE THREAD

**Issue by Cstoneman99** [AzuraCast/AzuraCast#3032]
Hi,

I would like to host both AzuraCast and my station's website (WordPress) on the same server if possible. Could someone provide some instructions on how this can be done?

I have already followed [these instructions](https://www.azuracast.com/extending/multisite.html) but still not completely clear on how this can be set up. Do I install WordPress first, then follow the instructions on setting up the new Docker service? Or the other way around?

**Comment by andrewyv** [comment]
Check this out: https://www.azuracast.com/extending/multisite.html#how-it-works

**Comment by Radio-Quergedacht** [comment]
I advise from then on to host everything on the same server

**Comment by Thijmen** [comment]
I have Traefik in front of all my servers as a reverse proxy. Works as a charm! Maybe it's something you can use as well.

**Comment by pitsch** [comment]
got the wordpress official docker image working a while ago, still could need a few tweaks. YMMV. 

https://textb.org/r/g3dfjtpfdk/

**Comment by aldocano** [comment]
Do you guys have any tips on how to run on the same servers with SSL enabled on both, azuracast uses Lets Encrypt and it needs to use port 80/443 in order to install the cert. I tried installing the cert and then change the default ports and no luck in it.
I need WordPress on port 80/443 and Azura on 8000 etc.

**Comment by Thijmen** [comment]
@aldocano Take a look at Traefik.

**Comment by aldocano** [comment]
> @aldocano Take a look at Traefik.

do you have .yml file config for the azuracast? would be helpful.

**Comment by SlvrEagle23** [comment]
We have an example of how to use our multi-site setup to host other web sites on the same server here:
https://www.azuracast.com/extending/multisite.html#adding-other-sites

**Comment by aldocano** [comment]
@SlvrEagle23 i tried configuring both azura and wp with docker image and still having port overlaps. 
Can i set azuracast environment to a subdomain hosted on same server ? 
radio.domain.com and wp pointed to domain.com for example?

**Comment by aldocano** [comment]
For those who might need this, I used docker-compose.override.yml to override the environment for the web container only and placed WordPress environment link to domain.com.

**Comment by linareyne** [comment]
Can either of you share your docker-compose if you've got Azuracast running behind Traefik? I'd like to only expose the public page+webdj for a stream. Think I should be able to with Traefik's `addprefix` feature like this, but I'm just getting timeouts - even without the addprefix lines (with these labels on the azuracast-nginx container with non-standard port assignments). 

```
  labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radio.rule=Host(`radio.site.com`)"
      - "traefik.http.routers.radio.entrypoints=websecure"
      - "traefik.http.routers.radio.tls.certresolver=myresolver"
      - "traefik.http.middlewares.radio-addprefix.addprefix.prefix=/public/mystream"
      - "traefik.http.routers.radio.middlewares=radio-addprefix@docker"
```

**Comment by linareyne** [comment]
Got past the timeouts, but now I have a redirect that's occurring when I try to hit the root directory (which should have the path prefix added so that it points to my public page). The redirect is sending me to `radio.site.com/public/mystream`, which is then resolving as `radio.site.com/public/mystream/public/mystream` and returning a 404 because of the traefik path prefix addition.

Seems like Traefik's `addprefix` feature is triggering the azura nginx container (or something along those lines) to create a 301 redirect record for the root directory.

**Comment by thatnerdjack** [comment]
If anyone, specifically @linareyne or @aldocano has a solution (with or without Traefik) and wouldn't mind sharing their configuration file I would be extremely grateful! I'm currently in the process of migrating a station and their website.

**Comment by linareyne** [comment]
> If anyone, specifically @linareyne or @aldocano has a solution (with or without Traefik) and wouldn't mind sharing their configuration file I would be extremely grateful! I'm currently in the process of migrating a station and their website.

I ended up using the Traefik [ReplacePathRegex](https://doc.traefik.io/traefik/middlewares/replacepathregex/) and replaced the root path `/` with `/public/{my stream}` (along with a couple other path replacements to make it so the only other route exposed to the internet is the DJ interface).

The AddPrefix middleware creates a 301 redirect header when trying to replace the root path and I'm not sure how to make it stop. Didn't test too much tho to see if it occurs as well when exposing other nginx servers via traefik, since I found out the regex option exists. :P

**Comment by aldocano** [comment]
> If anyone, specifically @linareyne or @aldocano has a solution (with or without Traefik) and wouldn't mind sharing their configuration file I would be extremely grateful! I'm currently in the process of migrating a station and their website.

The way i fixed my case in which i needed the azuracast to be on the subdomain and the website to be on the main domain was by creating a docker.compose.override.yml just like the image below. 

<img width="577" alt="Screenshot 2021-03-29 at 11 30 14" src="https://user-images.githubusercontent.com/8085145/112818080-6f753580-9083-11eb-9653-8c805545eab0.png">
Hope this helps.

**Comment by aldocano** [comment]
> If anyone, specifically @linareyne or @aldocano has a solution (with or without Traefik) and wouldn't mind sharing their configuration file I would be extremely grateful! I'm currently in the process of migrating a station and their website.

The way i fixed my case in which i needed the azuracast to be on the subdomain and the website to be on the main domain was by creating a docker.compose.override.yml just like the image below. Hope it helps you out.

<img width="577" alt="Screenshot 2021-03-29 at 11 30 14 copy" src="https://user-images.githubusercontent.com/8085145/112818310-ad725980-9083-11eb-9db4-7eb0852d493e.png">

**Comment by alexxx0000** [comment]
It's [working](https://docs.azuracast.com/en/administration/docker/multi-site-installation)

**Comment by pwrj** [comment]
@aldocano I hope you're well. Do you mind sharing the steps to host your station on a subdomain.domain.com and your station's website on you domain.com on the same server? I would be grateful. Thank you!

**Comment by aldocano** [comment]
> @aldocano I hope you're well. Do you mind sharing the steps to host your station on a subdomain.domain.com and your station's website on you domain.com on the same server? I would be grateful. Thank you!

You can check the image i uploaded above, that was basically what i did and it worked as intended. I dont know if this is working again with this version.

**Comment by pwrj** [comment]
Thank you @aldocano - I will try it!
