### ISSUE TITLE
Fade

### ISSUE THREAD

**Issue by Richard399** [AzuraCast/AzuraCast#3039]
Firstly, my thanks for this wonderful system, love it!

Question :

My tunes finish, there's a delay, and then the next track or jingle plays?

Where may I set it so where the track is coming to an end, the next track/jingle comes in so as to remove silence or "dead air".

What would be the recommended setting for fade in / fade out, please?

Many Thanks

**Comment by SlvrEagle23** [comment]
@Richard399 This would be a good use of the Visual Cue Editor tool in the Media Manager page; if your track has "dead air" at the end of it, you can simply select the area where the song stops, and set that as the "Cue Out" point, at which point the software will assume that's where the song ends, instead of the actual end point of the audio file.

**Comment by Richard399** [comment]
Thank you for that,

Hmmm, if I had to do that for each song; would take forever? 

And what would be the recommended setting for fade in / fade out and how? please so as the track nears the end the jingle fade in?

Many Thanks
