### ISSUE TITLE
Stations Media in external directory?

### ISSUE THREAD

**Issue by voipworld** [AzuraCast/AzuraCast#3040]
Hello,
i am runing latest azuracast in a DigitalOcean Droplet
i have a 100GB volume atached to it.
i want to move the entire station medias to that volume,  but i dont see any way to specify the external media directory outside the docker container.
any help?

**Comment by Vaalyn** [comment]
The recommended way to make your volume available for AzuraCast is to mount it into the container via a `docker-compose.override.yaml`. We have an entry on our website on how to do this: https://www.azuracast.com/help/docker/#mounting-a-directory-into-a-station

This tutorial assumes that you want to replace the current media directory with the external volume but you can also add another directory after the `<STATION_NAME>/media/` to mount it to a sub directory of your media directory. Since you want to move completely to the new volume you could first mount it as a sub dir and move the file over to it and then change the mount to replace the media directory.
