### ISSUE TITLE
Default to Stream Offline instead of "Azuracast is Live"

### ISSUE THREAD

**Issue by samkitk** [AzuraCast/AzuraCast#3045]
When nothing is playing, can I default to taking the stream offline instead of the error.mp3 playing? How do I do this?

**Comment by SlvrEagle23** [comment]
This may be possible by overriding or removing the error.mp3 file from the system, but this is not currently officially supported.

**Comment by samkitk** [comment]
Okay, feel free to close the issue.
Thanks.

**Comment by bilalbox** [comment]
One thing that worked for me is to run this little script after every update to replace the stock error.mp3 with our preferred audio (calming birdsong):
```bash
replace-error-file() {
  if [[ -s error.mp3 ]]; then
    arrayname=($(find /var/lib/docker/overlay2 -type f -name "error.mp3"))
    for element in $(seq 0 $((${#arrayname[@]} - 1))); do
      echo "Replacing error.mp3 found at ${arrayname[$element]}"
      cp error.mp3 "${arrayname[$element]}"
    done
  fi
}
replace-error-file
```

I have to run it after every update, but it would be nice to insert this into the main `update()` function so that users could optionally have the error.mp3 replaced with their custom choice every time they update the spec. If they don't include a custom `error.mp3` file in `/var/azuracast` then there is no need to update. @SlvrEagle23 if such a PR came across your desk, would you consider merging?

**Comment by SlvrEagle23** [comment]
@bilalbox This really isn't necessary even as of the current latest Rolling Release version. We recently implemented support for a Custom Fallback File (which would replace the "This station is powered by AzuraCast") on a per-station basis, under the "Broadcasting" tab. This custom file will persist across any infrastructure changes we make.
