### ISSUE TITLE
Custom Fields on Edit Media becomes invisible, but content is saved

### ISSUE THREAD

**Issue by oliverneedham** [AzuraCast/AzuraCast#3075]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.3, #2093d49 (2020-06-22 4:36)

**Host Operating System**
Ubuntu 20.04 (via a Droplet on DigitalOcean)

**Describe the bug**
After adding content to a Custom Fields tab within the Edit Track dialog, if you go to another tab, then back to the Custom Fields tab, the content you've just added is not visible. It is however saved when you click 'Save changes'.

**To Reproduce**
Assumptions: You have at least one Custom Field setup on the admin side.
1. Go to the Music Files page.
2. Click Edit on a track.
3. Go to the Custom Fields tab.
4. Enter some text into a custom field.
5. Go to any other tab, e.g. Basic Information.
6. Go back to the Custom Fields tab. (Content isn't visible)
7. Click Save Changes.
8. Click Edit on the same track as in step 2.
9. Go to the Custom Fields tab. (The content is visible and saved)

**Expected behavior**
The content entered in step 4 should be visible at step 6.
The content *is saved* however when you click save changes.

**Device(s):**
 - Device: Desktop 
 - OS: Mac OS 10.15.6
 - Browser: Chrome
 - Version: 84.0.4147.105 (64-bit)

**Additional context**
I had initially thought that the content wasn't being saved, but when I went back to edit the same track, the changes had actually been made.

**Comment by SlvrEagle23** [comment]
@oliverneedham I realize the response is delayed here, but I just now had a chance to look into why this is happening and I figured it out: when we implemented the visual waveform editor, in order to improve performance we made it "lazy-loaded" onto the page, but we inadvertently made _every_ tab lazy-load, which means every time you switch to the tab it re-initializes it, which causes problems.

This should be fixed as of the latest commit just a few minutes ago.
