### ISSUE TITLE
Recording issue

### ISSUE THREAD

**Issue by joshms123** [AzuraCast/AzuraCast#3076]
**Using Docker installation method**
Yes

**AzuraCast version**
 • v0.10.3, #51a2292 (2020-08-02 17:32) Rolling • Docker • PHP 7.4

**Host Operating System**
Debian.

**Describe the bug**
Sometimes on handover, the last few seconds of the previous show are tacked on to the start of the recording. In almost all cases, the very last few seconds are trimmed from the end of the archive. This causes abrupt ends to archives of shows.

**To Reproduce**
Broadcast a show. For the previous seconds, have a show follow the last with no delay.

**Expected behavior**
The recording to include the show that was broadcast, start to finish.

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by joshms123** [comment]
I would like to check up on this.

**Comment by Vaalyn** [comment]
Just re-examined this issue and noticed that due to the update that moved the starting and stopping of the recording inside of Liquidsoap the recording is now starting exactly when the live input receives data and ends when it doesn't receive data anymore. In my tests this is now working as envisioned, only recording the live source. From start to end.

Closing as resolved
