### ISSUE TITLE
Display the current DJ in API results and public pages when they're streaming

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#308]
Can I do if I select autoDJ on the public page of streamers, as if they are broadcasting?

**Comment by SlvrEagle23** [comment]
@susl16c I don't understand this request. Please reword it.

You have recently flooded this repository's Github issues with several issues that are difficult to understand or that are out of our immediate control. Please stop creating new Github issues for a while.

**Comment by susl16c** [comment]
On the public page, output the DJ who sees this radio

**Comment by SlvrEagle23** [comment]
@susl16c Oh, you mean show who is the current DJ on the public page when they're streaming.

I'll add it as a possible enhancement.

**Comment by mantazzo** [comment]
I think, if possible, that could be a good suggestion. For now, if someone DJ's, you don't know neither what they're playing, nor even who might be playing/DJ'ing on the public page.

**Comment by SlvrEagle23** [comment]
@mantazzo @susl16c This has now been implemented in AzuraCast.

On the "Streamers/DJs" page, you can set a "Display Name" for each DJ username/password you supply; this will be the name that appears when they're connected and DJing in the NowPlaying API responses. By default, it just uses their DJ username.

The Now Playing API endpoint has been updated to have a new section, `live`, that looks like:
```
live: {
    is_live: true,
    streamer_name: "DJ Jazzy Jeff"
}
```

This live status is now properly determined by LiquidSoap actually reporting the start and stop of DJ stream connections, rather than guessing whether a stream is live or not based on whether the AutoDJ picked the currently playing song.

With the addition of the new section, the `is_live` property in the `currently_playing` song object has been removed in favor of the newer, more accurate variable.

Hopefully this helps people!
