### ISSUE TITLE
Metadata not transmitting when DJing via Shoutcast v1 legacy mode

### ISSUE THREAD

**Issue by jonikane** [AzuraCast/AzuraCast#310]
On the icecast server when I broadcast with shoutcast v1 the song name is not appearing on the icecast server

**Comment by susl16c** [comment]
At me too most, only at me behind a proxy there is a radio.

**Comment by SlvrEagle23** [comment]
@jonikane If you don't mind, can you provide me with an example station URL that you're using with AzuraCast? That would make it very easy for me to diagnose the issue and identify the problem. This is one of many reasons Shoutcast 1 is only supported with remote station syndication and not with broadcasting, as the data it provides to third parties is significantly less well-structured than its successor.

**Comment by jonikane** [comment]
Do you want the login data to log in and see what the error is?

**Comment by SlvrEagle23** [comment]
@jonikane If you want, you can e-mail that information to me at loobalightdark@gmail.com, or you can just send me the URL of the radio station you're connecting to remotely, so I can see how it would possibly work on my own setup and try to resolve the issue.

**Comment by susl16c** [comment]
I can give you access to the public page, if you need I can to the admin panel but not for long and provided that you will not be there to change.
https://radio.izones.ru/public/korea_freedom
Admin can give on request.

**Comment by SlvrEagle23** [comment]
Updated the title here to clarify what's actually being described, as it confused me quite a lot initially.

This will take some time for me to diagnose and look into, as I don't currently have my DJing software set up.

**Comment by susl16c** [comment]
You can use this as much as you like, I can access to let this go in while the test site, I look forward to these corrections, so I can not move on. Therefore, write if you need anything else.

**Comment by SlvrEagle23** [comment]
@jonikane @susl16c I have asked around for some advice on this issue, and found a possible solution: the older versions of ShoutCast (particularly 0.x and 1.x) do not support UTF-8 encoding for their metadata, but since LiquidSoap is expecting that, it fails to send any metadata at all.

To handle this, I've made the character set encoding used by LiquidSoap user-configurable between "UTF-8" and "ISO-8859-1" (the older character set used by SC1). If you switch your encoding, then restart broadcasting, this may resolve this issue for SC1-based DJs.
