### ISSUE TITLE
Replace LiquidSoap with sc_trans

### ISSUE THREAD

**Issue by tanotar** [AzuraCast/AzuraCast#3110]
Hello community. I would like to know if there is any way to replace "LiquidSoap" with "sc_trans" since LiquidSoap consume a lot of CPU when using AutoDJ. Whereas sc_trans which is the one that brings shoutcast consumes a lot less CPU.
I hope prompt responses. Regards!

**Comment by Vaalyn** [comment]
Right now regardless of using IceCast or SHOUTcast the AutoDJ is always running [LiquidSoap](https://www.liquidsoap.info/). (I think LS is what you are referring to when you say "Dokers", please correct me if I'm wrong here)

`sc_trans` might be consuming less CPU because it does not re-encode audio when the source already matches the desired stream output. LS always re-encodes the audio stream. See https://github.com/savonet/liquidsoap/issues/1053

In theory it should be possible to add another AutoDJ backend since the backend has been built with an [AbstractBackend](https://github.com/AzuraCast/AzuraCast/blob/master/src/Radio/Backend/AbstractBackend.php) concept. But at the moment I don't think that this will be done any time soon in the main project since there is already enough work going on to make the one backend we currently have work as good as possible. Another "construction area" would be too much (in my opinion).

If someone really needs this I would recommend to try adding it by writing a plugin although I can not testify on how good that works atm since no one (as far as I'm aware) has yet tried to add another backend nor do I know of any existing plugins.

**Comment by tanotar** [comment]
Yes. I realize that I have made a mistake and have already modified my ad. It was Replace "LiquidSoap" by "sc_trans" which is the one that brings shoutcast
