### ISSUE TITLE
How to add media folder outside docker

### ISSUE THREAD

**Issue by xifi-kif** [AzuraCast/AzuraCast#3131]
Hello,
standard fresh docker installation here, on Ubuntu 20.04.
According to [this](https://www.azuracast.com/help/docker/#mounting-a-directory-into-a-station) I should insert into the `docker-compose.override.yml` the path of the radio, however in my `/var/azuracast` dir I have no subdir named "**stations**", only docker files.

My basic need is to mount a volume where I'll keep the songs. 

Thanks for help

**Comment by Vaalyn** [comment]
The `volume` path `/path/on/host/computer:/var/azuracast/stations/<STATION_NAME>/media/` is read like this `<host>`:`<container>`. So the part on the right side of the `:` is not in that part of your host machine but inside of the container.

Change `/path/on/host/computer` to where you store your media on your host machine and change `<STATION_NAME>` to the name/code of your station. Take a look at the station profile in the web interface, there you can see the full path in the container under `Administration`.

**Comment by xifi-kif** [comment]
Thanks I see, I'm still learning docker. Did what you suggested and then `docker-compose down` `docker-compose up -d
Now I can't upload new files. 
Should the location I added have special permission/ownership?
How can I add the media files already present in the path I added?
Should I rebuild the database? How?

**Comment by Vaalyn** [comment]
Most likely permissions, you can enter the containers shell with `docker exec -it azuracast_web bash` and make sure that the directory in there has the user and group `azuracast`.

> How can I add the media files already present in the path I added?

I'd change the mount to a sub directory so that you have them both accessible and then copy/move them over when inside the container.

**Comment by xifi-kif** [comment]
> I'd change the mount to a sub directory

You mean like this 
`/mnt/volume_ams3_01_radio_data/songs/media:/var/azuracast/stations/loma/media/subdir/`
instead of this
`/mnt/volume_ams3_01_radio_data/songs/media:/var/azuracast/stations/loma/media/`

right?

**Comment by xifi-kif** [comment]
Another question: what if in the future I'd like to mount another volume? Is this possible?

**Comment by Vaalyn** [comment]
> You mean like this
> `/mnt/volume_ams3_01_radio_data/songs/media:/var/azuracast/stations/loma/media/subdir/`
> instead of this
> `/mnt/volume_ams3_01_radio_data/songs/media:/var/azuracast/stations/loma/media/`
> 
> right?

Yes

> Another question: what if in the future I'd like to mount another volume? Is this possible?

Sure, just add another line beneath the first mount with the other volume.

**Comment by robz0** [comment]
Hi hope it's ok to reply on this thread. 

Have searched 'everything' for what I want and this is the closest.  
This reply...

> I'd change the mount to a sub directory so that you have them both accessible and then copy/move them over when inside the container.

This sounds like a great idea but I can't achieve it. 

Using Docker install, 
successfully mounted Dropbox and 
can access files and even created directories in Dropbox via AZ (Brilliant!)

But... 
only when I change the Media Storage Location in Station/Edit/Administration.
In fact it works beautifully like that. so Great work Team AZ

However - 
I would also like to achieve what @Vaalyn suggests above and mount that Dropbox folder in a sub-directory so that I can access that folder AS WELL AS my local folder for media.

Since changing the Media Storage Location makes it Either / Or for local/dropbox,  I wonder.  Is this possible then?

it seems that I don't know how to find/refer to the Dropbox mount, in order to put the correct syntax in the docker-compose.yml for volumes:

After Adding Dropbox Storage successfuly, the mounts comes up in Storage Locations as something like - 
Remote: Dropbox 
dropbox://aaxaxaaxxx/   (where a is a letter and x is a number which I have replaced here), 

This number/path-name is automatically defined in the App set up and Authorisation process. 

I have tried using these insructions 
https://docs.azuracast.com/en/administration/docker#mounting-a-directory-into-a-station 
to mount the dropbox into the station (as an additional, not alternative source) - 
thus editing these values

```
services:
  web:
    volumes:
      - /path/on/host/computer:/var/azuracast/stations/<STATION_NAME>/media/subdir
```

I can get the /subdir to show up in the station ok. But it is empty and bears no relation to the Dropbox folder, which is only usable as a Media Storage Location in it's own right. 

Leaves me wondering how to form the left side of the : for recognition of the dropbox mount and therefore making it able to see the Dropbox AND Local files in the station.

I have tried a lot of combinations of that path name. 
`//aaxaxaaxxx/ ` - with one slash, no slases, using mnt/ etc (which just creates a new directories if they do not exist), using the host name dropbox without colon and with: (which docker-compose down rejects) so I wonder :- 

1) is it possible to mount Dropbox as a subdir, so that it can be accessed alongside Local Storage

2) where Dropbox mounts and how to refer to the dropbox mount as an additional storage volume - so it can be mapped to a subfolder 
- not as and alternative Media Storage Location for the station but an additional one.

After each try or changing the mount details -  i did also duly docker-compose down/up respectively. So it has been a long time testing. I've now given up and decided to ask you. 

Much Thanks in advance,
Rob
