### ISSUE TITLE
Modify the embedded player CSS

### ISSUE THREAD

**Issue by PUBDR** [AzuraCast/AzuraCast#3134]
I have a relatively simple question to ask. I want to include just the player of my stream on another site, but I have added a lot of my own CSS in the public pages css editor. When I embed the player off to another website, the styling of the player is just the default.

To my understanding, I cannot change the css of an iframe element, so is there a way that I can add custom CSS to the embedded player? This is what the player looks like on my public page w/ the CSS.

![What the player looks like on my public pages w/ CSS](https://user-images.githubusercontent.com/46715011/91848050-9a4ff600-ec28-11ea-983c-a1a08a4c74a8.PNG)

Thank you.

**Comment by Vaalyn** [comment]
You can use the custom CSS for public pages for the embed too. You might need to target different CSS classes though. Check with your browsers developer console what classes are used in the embed. For example I've added a different background color for the embed player like this:
```
.embed .stations  {
    background-color: #612d2d;
}
```

**Comment by PUBDR** [comment]
So I tested that exact styling you posted on my local static page, but unfortunately it didn't apply the styling. I went inside the developer console and saw that the player had the .page-minimal class and tried to add the styling for that class. Unfortunately, it looks like that styling wasn't applied either.

![why](https://user-images.githubusercontent.com/46715011/91884721-91751980-ec54-11ea-9dc0-beaf5d4e74d0.PNG)

From the looks of things, the CSS that I added was crossed out? This holds true for when I tried to modify the CSS from the console on the .embed class too.

**Comment by Vaalyn** [comment]
Here a screenshot from when I use the embed iFrame with my custom CSS (I'm not targeting the `body` element but the `stations` `div`):

![image](https://user-images.githubusercontent.com/13745863/91895533-b179fc80-ec97-11ea-93ba-efee4dea27e3.png)

The default CSS for the `body` has the background set with `!important` which will override any `background` declared without `!important`. Which is why your background image is not used there.

This is the default CSS on the body of the `embed` page:
```
body.embed {
    background: 0 0!important;
    min-height: auto;
}
```

**Comment by PUBDR** [comment]
Ahah, I was able to figure it out with this, thank you so much!

**Comment by PUBDR** [comment]
A
