### ISSUE TITLE
Song Repeating?

### ISSUE THREAD

**Issue by voipworld** [AzuraCast/AzuraCast#317]
Hello,
i set up several playlist in the station
but one of the playlist is repeating so much..., its a standard playlist like others, with same priority (1!) at the rest of the playlists
what to do to disable that song priority or something like this?
i think scheduling need lot of change...
thanks!

**Comment by susl16c** [comment]
if you want the playlist to be played less often, you should set it to priority (1) or set the priority higher in the other playlists (3). There are two options, I announced them.

**Comment by jonikane** [comment]
Hello

I connect through shoutcast v1 because of the port and password that I  
can set for each dj.

I sent a printscreen with that checked.

Thank you

**Comment by voipworld** [comment]
this issue is not about playlist priority, susl16c
this issue is about best performing song
some song keep repeating in a playlist
for example now a song 1 is playing from playlist A
playlist B come, then C, then D
if A come back, it will repeat just song 1
its not shufling it correctly according to my testing
maybe we can twick liquidsoap
thanks.

**Comment by voipworld** [comment]
@jonikane dont mix bethwan issues please.

**Comment by SlvrEagle23** [comment]
@voipworld Is there just one song in that one playlist?

Currently, there are two steps to the "find next song" process:
 - Figure out which playlist it will come from (using the weighted probability for each playlist), then
 - Find the least recently played song out of a random selection of songs on that playlist.

If a playlist has one or two songs in it, then the first step will mean that it is still selected roughly every x% of the time, but because there are only one or two songs, it'll seem to be playing those far more often.

**Comment by voipworld** [comment]
hey,
no, the playlist had allmost 30 songs
mostly the first 10 songs only play, while others rarly play...

**Comment by susl16c** [comment]
also join in the playlist of 250 songs, but according to reports it is clear that many songs I play several times, while others do not play at all, 0 players have been installed. Everything would be fine, but users complain that there are no songs on the radio, and there are plenty of them, and on the players it turns out that only the ones that are playing are playing.
