### ISSUE TITLE
Multiple Domain Names in One Azuracast Instance

### ISSUE THREAD

**Issue by blindgeek** [AzuraCast/AzuraCast#3189]
Let's say I have two existing domains: I installed Azuracast in radio.domain1.com. Now can I point another domain domain2.com to the same Azuracast installation but to a different radio station and use the login page radio.domain1.com/login through domain2.com/login? I am very specific with the examples because I'm really confused if this setup is possible. One more thing: is multi-site installation the correct approach for this? Or that's for another situation altogether. My question is about radio.domain1.com being the super admin and domain2.com is just a regular station.

Cheers,
Joey

**Comment by Vaalyn** [comment]
I haven't tested this but I'd assume that when you activate the `Prefer Browser URL` setting in the system settings you should be able to point multiple domains to the same installation and login via both domains. The multi-site stuff is for when you have something else that needs to be hosted on the same server on port 80/443 (and don't want to have AzuraCast running on other ports), like for example a blog.

**Comment by blindgeek** [comment]
@Vaalyn Prefer browser URL is checked already. How can I point the second domain to the installation? Regarding the multi-site, does that mean I can already activate SSL without having to change ports or anything?

**Comment by Vaalyn** [comment]
> How can I point the second domain to the installation?

Like you did with your first domain, you setup the DNS record for the domain to point to your servers IP address. Your hosting provider that manages your domain name should have a control panel where you can do this.

> does that mean I can already activate SSL without having to change ports or anything?

When you use the built-in command to setup SSL with Let's Encrypt via `./docker.sh letsencrypt-create` this will automatically create the certificate for the domain that you enter into the prompt that the command gives you. 

When you setup the Let's Encrypt certificate you should give the command both domains like this so that the cert is valid for both: `radio.domain1.com,domain2.com`.

You should first point the second domain to the server so that Let's Encrypt is able to verify the domain though.

More about AzuraCast's Let's Encrypt integration can be found here: https://www.azuracast.com/extending/letsencrypt.html#enabling-https-with-letsencrypt

Using 2 domains for an AzuraCast installtion and the Let's Encrypt SSL are not related to the Multi-Site stuff. Multi-Site is strictly for when you want to host other websites (that are not the AzuraCast web panel) on the same server on port 80/443 (the standard ports for websites).

**Comment by blindgeek** [comment]
Thank you for patiently answering my questions. Closing this issue now.
