### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by Richard399** [AzuraCast/AzuraCast#3229]
Hi,

I see I have a 200+updates on the dashboard and looked at this :

https://www.azuracast.com/administration/system/updating.html

I have limited experience or knowledge using a CMD line.

Is there a "step-by-step" azuracast video tutorial on how to do this, please?

Many Thanks

**Comment by Xara** [comment]
Well is  not that difficult to update but what about "Update" button in global administration panel?

**Comment by SlvrEagle23** [comment]
@Richard399 The update process really is as simple as logging into your server via SSH, then running:

```bash
cd /var/azuracast
./docker.sh update-self
./docker.sh update
```

@Xara Unfortunately we can't offer self-updating functionality because AzuraCast exists inside a Docker container, and can't control the container it itself is running in (as that would be a potential security hazard).

**Comment by Richard399** [comment]
Hi,

Thanks for that but sd I said, have little experience in using SSH which is why I was seeking a step-by-step tutorial.

As someone has suggested, how about adding an UPDATE button on the Admin Dashboard? :-)

**Comment by Vaalyn** [comment]
> Thanks for that but sd I said, have little experience in using SSH which is why I was seeking a step-by-step tutorial.

I'm assuming you are using Windows:

1. Download, install and open [`Putty`](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html)
2. Enter IP or Domain of your server into the `Host Name` field
3. Click on `Open`
4. Enter your login credentials for the server
5. Enter the commands that were posted above:

```
cd /var/azuracast
./docker.sh update-self
./docker.sh update
```

> As someone has suggested, how about adding an UPDATE button on the Admin Dashboard? :-)

That is not possible without adding huge security issues to the application.
A docker container is an isolated environment that has no access to the host machine itself. That means it can't access anything from the host machine that it does not have explicit access to. In order to have an `Update` button the container would need to be given `privileged` access to the host machine which is heavily discouraged by security experts.
