### ISSUE TITLE
Error sending files by ftp

### ISSUE THREAD

**Issue by roger-net** [AzuraCast/AzuraCast#3230]
**Using Docker installation method**

Yes

**AzuraCast version**

0.10.4

**Host Operating System**

Ubuntu 20.04

**Describe the bug**

When uploading songs via an ftp program, many of them, most of them, appear as "file not processed" and this message does not appear when the songs are sent by azuracast itself. I am using WinSCP to send via sftp.

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

https://prnt.sc/ut3qxm

**Device(s):**
 - Device:  Desktop
 - OS:  Windows 10
 - Browser:  Google Chrome
 - Version:  85

**Additional context**

**Comment by Vaalyn** [comment]
This is expected behaviour for media files that are not uploaded via the web interface. Since new media files need to be processed by AzuraCast to extract information about the content of those files they will be shown on the interface as "File Not Processed" until AzuraCast has processed them.

There is an automatic Sync Task "Check Media Folders" that runs every 5 minutes that is taking care of that (you can also manually run this from the Administration page).

**Comment by roger-net** [comment]
I understand. It just amazed me because previous versions did not.

**Comment by Vaalyn** [comment]
This message and the automatic processing of uploaded files is something that exists in AzuraCast for a long time already.

When I look at the [commit history](https://github.com/AzuraCast/AzuraCast/commits/400f4f60a441f637fb2cb1c02143f8512f0a621f/src/Controller/Api/Stations/Files/ListAction.php) of the controller for the files list I can see that the `File Not Processed` message was already present on the controller when it was renamed / moved to where it currently is in October 2019.

You might have missed it until now.
