### ISSUE TITLE
Can't disable playlist

### ISSUE THREAD

**Issue by shaksp** [AzuraCast/AzuraCast#3236]
First of all, apologies I am a first time Azuracast user.

I'd like to use the Stream/DJ Accounts functionality but not the AutoDJ functionality. I have no need for playlists. When Streamer/DJ is offline, the stream should be offline rather than using AutoDJ.

Also I'd like to use the functionality to record streamers which is part of AutoDJ.

Disabling AutoDJ disables the streamers. I only need one streamer account though. How can I use Streamers but have the station offline at all other times?

**Comment by SlvrEagle23** [comment]
@shaksp We use our AutoDJ to handle incoming DJ connections because it allows us to customize how DJs connect and support a broader range of software than using the broadcasting software directly.

If you disable the AutoDJ, you can still broadcast to the broadcasting frontend (i.e. Icecast) using the Source password we provide, but you won't be able to take advantage of individual DJ accounts.

The idea behind the AutoDJ is to always have something broadcasting on your station, even if it's just a single filler track. You could upload a few seconds of static noise and add it to a playlist and it would serve its intended purpose without any problems.

**Comment by shaksp** [comment]
@SlvrEagle23 Thanks for the explanation. I take it if we disable AutoDJ then we can't record the streams though?

**Comment by SlvrEagle23** [comment]
@shaksp Correct, since the AutoDJ also handles that component (since it's the only part of our system that can handle on-demand transcoding to multiple destinations, i.e. a stream and a file, at the same time)
