### ISSUE TITLE
Setting COMPOSE_HTTP_TIMEOUT to a higher value

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#3258]
During update, I get this error message:

ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a   higher value (current value: 60).

What is this message for and how can I set higher value for COMPOSE_HTTP_TIMEOUT?

**Comment by nickrobillard** [comment]
`COMPOSE_HTTP_TIMEOUT` is a docker compose environment variable. There are various ways to set it.
You will need to restart the docker stack, with the environment variable set. You can reference https://www.azuracast.com/extending/modifying-docker.html#how-azuracast-s-docker-installation-works for these commands. Under normal circumstances, this is how you would restart the AzuraCast docker stack:
```
docker-compose down
docker-compose up -d
```
In order to change the `COMPOSE_HTTP_TIMEOUT` value, you have 2 options. You can either set it via command line:
```
docker-compose down
COMPOSE_HTTP_TIMEOUT=120 docker-compose up -d
```
Or you can set it in the `.env` file (if you would rather not have to remember to add it every time you `docker-compose up`):
```
COMPOSE_PROJECT_NAME=azuracast
COMPOSE_HTTP_TIMEOUT=120

AZURACAST_HTTP_PORT=80
AZURACAST_HTTPS_PORT=443
...
```
In my examples I have used `120`, but you can use any value you want.

Keep in mind that this timeout can be caused by not having enough system resources. Without further details about your system (hardware specs, host os, AzuraCast version, etc), it is hard to know for sure.
