### ISSUE TITLE
Problem with OPUS

### ISSUE THREAD

**Issue by ruLait** [AzuraCast/AzuraCast#326]
If format of the mount point selected as "OGG Opus", the Now Playing field in Station Management becomes empty. API response is empty too (also field "song"->"text" somehow contains "Stream Offline").
With other formats it's all right.
![](https://pp.userapi.com/c840231/v840231820/58e99/wgkzYMjHlqA.jpg)
![](https://pp.userapi.com/c840231/v840231820/58ea0/XCCjgjBNqDs.jpg)

**Comment by SlvrEagle23** [comment]
@ruLait This is a known issue with the OGG Opus codec's interaction with Icecast; you should always have at least one mount point using a non-Opus codec for now playing data to sync properly.

**Comment by ruLait** [comment]
@SlvrEagle23 It's sounds like a kludge, but thanks anyway.

**Comment by SlvrEagle23** [comment]
@ruLait To be clear, the "kludge" is not on AzuraCast's part.

We originally did not offer Opus support because it couldn't send metadata through the stream in a way that Icecast could handle properly, but Opus is very useful for sending music directly into services that use it (i.e. Discord chat channels) without needing to transcode again. It's always meant to be secondary to a main radio stream, though.

There's nothing we can do about it on our end, unfortunately.
