### ISSUE TITLE
Help with json history.songs 

### ISSUE THREAD

**Issue by Radio-Quergedacht** [AzuraCast/AzuraCast#3283]
<script type="875ee89282003dc2e75edc01-text/javascript">
[jsoncontentimporter url="https://stream.cast-radio.de/api/nowplaying_static/cast_radio_mainstream.json"]
{subloop-array:song_history:-1}
{subloop:song_history.song:-1}
<div>{song_history.song.text}</div>
{/subloop:song_history.song}
{/subloop-array:song_history}
[/jsoncontentimporter]
</script>

What am I doing wrong does not work that way

**Comment by SlvrEagle23** [comment]
@Radio-Quergedacht What are you writing this in? That isn't standard JavaScript (at least as far as I can tell)...

**Comment by Radio-Quergedacht** [comment]
Yes, I tried json but unfortunately it doesn't work
And I don't know what I'm doing wrong

**Comment by Vaalyn** [comment]
This looks like an issue with the WordPress Plugin ([JSON Content Importer](https://wordpress.org/plugins/json-content-importer/)) you are using and not with the JSON API of AzuraCast.

Please contact their support for further assistance on how to use the plugin.

If there is a specific problem that is caused by the AzuraCast JSON API please let us know.
