### ISSUE TITLE
enabling my online radio to work with https

### ISSUE THREAD

**Issue by almsafras** [AzuraCast/AzuraCast#3294]
Hi All,

i am encountering an issue that my embed player which is hosted in AzuraCast is not working with any web browser. i guess that i need attach SSL certificate to my site. anybody please help me to sort it out.

further clarification 
https://thehiradio.com

Thanks,

**Comment by fast97** [comment]
Hello which reading link which script you use for this reader because the page seems to be in https. for https azuracast reader mode it is like this: https://domain.com/radio/8000/radio.mp3

**Comment by Vaalyn** [comment]
@almsafras You are using `https` with an IP address as the stream URL. Since the `https` connection is done via IP address this is only secured with a self-signed certificate which all browsers block.

You either need to change the stream URL that you are using on that site from `https` to `http` since you are not using a domain name for the stream URL or you need to register a domain name, use the [Let's Encrypt installer](https://www.azuracast.com/developers/docker-sh.html#available-commands) of AzuraCast to register a valid certificate and change the IP to the domain name for the stream URL.
