### ISSUE TITLE
Request songs not loading

### ISSUE THREAD

**Issue by onurk7** [AzuraCast/AzuraCast#3296]
Ubuntu, docker, latest rolling version.

Hello, the request songs are not loading on one of our instances. It was loading fine before but after update the issue is happening on one of our largest stations which has around 6500 audio files in request list. When you click to "All" the loading icon appears and it does not list the 6500 songs on most of the browsers we tried and the browser returns "A web page is slowing down your browser. What would you like to do?" on top of the screen as a bar and asks for wait or stop it.

**Comment by SC2Mitch** [comment]
Trying to load 6500 songs in one page will cause issues, and it'll slow everything down trying to load that much data.try and do 100 per page

**Comment by onurk7** [comment]
It was not happening before the update to the rolling release. was loading between 15-20 seconds.

**Comment by Vaalyn** [comment]
I think this is caused by switching the public radio player to being a Vue.js component and updating it from using jQuery Bootgrid (which itself hasn't been updated since 2015 which is why it's being replaced) to directly using the boostrap-vue table component.

The `A web page is slowing down your browser. What would you like to do?` message is shown by a browser when JavaScript is taking a long time with processing something. In this case it is most likely due to it rendering the 6500 lines of the table in the request modal. The speed of that is highly dependent on the machine running the browser.

The biggest station I currently have has around 3500 songs available for requests which is loading in around 10s on my mid 2014 MBP. 

I'm not sure if there is actually anything that we can do here to reduce the load for the rendering of that Vue.js component since it is basically just the standard bootstrap-vue table.
