### ISSUE TITLE
Problems sending songs via FTP

### ISSUE THREAD

**Issue by roger-net** [AzuraCast/AzuraCast#3298]
I have version 0.10.4 installed more when uploading songs via ftp software (example: Filezilla, WinSCP etc ...) it is taking too long for Azuracast to add and many songs get the message "file not processed" and I have waited even longer a day and is still in that status. The other songs that appear on Azuracast, many of them do not play on the autodj. In previous versions this did not happen. Use since version 0.10.2.

O.S. Ubuntu 20.04
Version: 0.10.4
Docker: Yes

**Comment by DJMike67** [comment]
Hi @roger-net I am just an end user trying to run a radio station but have experienced similar problems (see my Issue 3263). One of the guys at Azuracast ran my problematic MP3 through a file checker and it reports an invalid file header but the file plays OK off my computer and also via Centovacast ( a different radio system)

**Comment by roger-net** [comment]
> Hi @roger-net I am just an end user trying to run a radio station but have experienced similar problems (see my Issue 3263). One of the guys at Azuracast ran my problematic MP3 through a file checker and it reports an invalid file header but the file plays OK off my computer and also via Centovacast ( a different radio system)

Thanks DJMike67 for your contribution, I can check the files although they are the same ones I used in previous versions and I didn't have this problem. Thank you for your help. Greetings.

**Comment by roger-net** [comment]
> Hi @roger-net I am just an end user trying to run a radio station but have experienced similar problems (see my Issue 3263). One of the guys at Azuracast ran my problematic MP3 through a file checker and it reports an invalid file header but the file plays OK off my computer and also via Centovacast ( a different radio system)

Thank you DJMike67 for your contribution, I can check the files although they are the same ones I used in previous versions and I didn't have this problem. Thank you for your help. Greetings.

**Comment by SC2Mitch** [comment]
Going to look into this issue. How big was the files you uploaded?

**Comment by roger-net** [comment]
> Going to look into this issue. How big was the files you uploaded?

Between 3 to 6 MB each file. One question, how do I install a previous version on a clean vps?

**Comment by DJMike67** [comment]
@SC2Mitch I had several files between 1MB and 150MB. The file size was irrelevant. The problem was with 4 specific files. I had exactly the same problem as @roger-net. If you want to run your own tests here is a link to download 2 files

https://app.box.com/s/iwy1m1eywfdokmnw0a0tken2eeal6cc9

0001.MP3 is the one with the problem (I did not bother sending the other 3 files with the problem - if we can fix 0001 I assume the others will work too).     0005.MP3 uploads/processes OK
and as far as I know both files (which are audio podcast episodes) were processed in exactly the same way

**Comment by SC2Mitch** [comment]
Thank you for the help guys, I might of found the exact root of the issue, I'll be posting a detailed bug report in the coming moments with the findings, it might be related to ID3 headers, but it still requires further investigations.

**Comment by Xara** [comment]
If you create a playlist with fresh files they will been processed immediately, is how I do for massive uploads, check also if there is no a unsuported or not music file in your playlist, it affect all songs after that

**Comment by DJMike67** [comment]
@roger-net @SC2Mitch I have an update for you based on testing I did just now...

My hosting company is using Rolling Release #06808d0 (2020-10-19 11:00) • Docker • PHP 7.4

It looks like I have the same problem as @roger-net. 

Now I cannot get ANY files uploaded via FTP (MP3 or M4A) to process. Before the latest update that was applied 2 days ago I had problems with 4 specific MP3 files and it didn't matter if they were uploaded via FTP or web interface. They would not process. I think it is a problem with how those 4 files were encoded.

Now I just uploaded 5 MP3 files and 5 M4A files (NOT the ones with the problem. Ones I know are OK). They upload fine through the web interface. They process immediately and are displayed in the file list ready for me to assign to playlists

However, the same files, when uploaded via FTP, display in the file list with the message "File Not Processed"

I have waited 20 minutes and they have not processed.

I have found a workaround but it is not satisfactory...select a file in the list, click the big blue MOVE button, select the same folder that the file is in. The file magically gets processed. This is not a satisfactory workaround because even if I select more than 1 file, it only "processes" the first one in the list so I have to do them one by one

**Comment by DJMike67** [comment]
@Xara as you say..."If you create a playlist with fresh files they will been processed immediately". I have just tried that. It works even on an existing playlist (rather than create a new one) and you can select multiple files to add to the playlist

So yes a good workaround, thank you. But I don't understand how the FTP thing broke. Until 2 days ago you upload via FTP and files were processed immediately without any other action needed

**Comment by Xara** [comment]
Hello, the new one playlist, just in case if you don't want affect what station is playing, why? well or there is a bad file on what processing is stuck or simply you have now many files and it need time... I don't know, I did not searched for as I found how to do with that problem.

**Comment by SlvrEagle23** [comment]
An update on this issue: we've made some changes that improve the ability of our message queue worker (which handles media processing, among other tasks) to log errors to the same system-wide logs we use for other diagnostic purposes.

So we can figure this out, would those of you having this problem please update and let us know what you see in your logs after uploading files via SFTP? In particular, the log available by running:

```bash
cd /var/azuracast
docker-compose logs -f web
```

from the host computer would be the most useful.

**Comment by DJMike67** [comment]
@SlvrEagle23 Thanks for the update and the changes you made. If/when my hosting company updates I'll see what I can do in terms of asking for a copy of the log.

**Comment by roger-net** [comment]
> An update on this issue: we've made some changes that improve the ability of our message queue worker (which handles media processing, among other tasks) to log errors to the same system-wide logs we use for other diagnostic purposes.
> 
> So we can figure this out, would those of you having this problem please update and let us know what you see in your logs after uploading files via SFTP? In particular, the log available by running:
> 
> ```shell
> cd /var/azuracast
> docker-compose logs -f web
> ```
> 
> from the host computer would be the most useful.

**Comment by roger-net** [comment]
> An update on this issue: we've made some changes that improve the ability of our message queue worker (which handles media processing, among other tasks) to log errors to the same system-wide logs we use for other diagnostic purposes.
> 
> So we can figure this out, would those of you having this problem please update and let us know what you see in your logs after uploading files via SFTP? In particular, the log available by running:
> 
> ```shell
> cd /var/azuracast
> docker-compose logs -f web
> ```
> 
> from the host computer would be the most useful.

Thank you my friend for the work, I will update and report here what happened. Just confirm the command line to update, it would be:
cd / var / azuracast
./docker.sh update-self
./docker.sh update

**Comment by SC2Mitch** [comment]
@SlvrEagle23 I've done some testing of my own for you and here's my logs / findings. It appears to be file specific / files with bad metadata / MPEG Headers that throw off AzuraCast. Vaalyn did do some analysis in a different thread https://github.com/AzuraCast/AzuraCast/issues/3263#issuecomment-712295278
I've uploaded tonnes of song and only one file has threw a bad error like this. 
Upload Completed
```
web_1                      | {"level":"debug","time":"2020-10-23T23:35:51.739","sender":"sftpd","connection_id":"efb54f8cd5adbba4193b4179404517f2c91303472029b39c5da7297ab64e2614","message":"atomic upload completed, rename: \"/var/azuracast/stations/medz/media/.sftpgo-upload.bu9mhedpbcenuhukgp30.0001.mp3\" -> \"/var/azuracast/stations/medz/media/0001.mp3\", error: <nil>"}
web_1                      | {"level":"info","time":"2020-10-23T23:35:51.739","sender":"Upload","elapsed_ms":29786,"size_bytes":68273008,"username":"Mitch123","file_path":"/var/azuracast/stations/medz/media/0001.mp3","connection_id":"efb54f8cd5adbba4193b4179404517f2c91303472029b39c5da7297ab64e2614","protocol":"SFTP"}
web_1                      | {"level":"debug","time":"2020-10-23T23:35:51.740","sender":"dataprovider_bolt","connection_id":"","message":"quota updated for user \"Mitch123\", files increment: 1 size increment: 68273008 is reset? false"}
web_1                      | {"level":"debug","time":"2020-10-23T23:35:51.833","sender":"sftpd","connection_id":"efb54f8cd5adbba4193b4179404517f2c91303472029b39c5da7297ab64e2614","message":"requested list file for dir: \"/var/azuracast/stations/medz/media\""}
web_1                      | {"level":"debug","time":"2020-10-23T23:35:52.392","sender":"sftpd","connection_id":"","message":"executed command \"/usr/local/bin/azuracast_sftp_upload\" with arguments: \"upload\", \"Mitch123\", \"/var/azuracast/stations/medz/media/0001.mp3\", \"\", \"\", elapsed: 652.209485ms, error: <nil>"}
```
File Error
```
web_1                      | [2020-10-23T23:35:52.730194+00:00] AzuraCast.ERROR: Warning for uploaded media file "0001": ["Invalid MPEG audio header (ff f8 67 ff ) at offset 262426","Invalid MPEG audio header (00 00 00 08 ) at offset 262573","Invalid MPEG audio header (ff ff ff ef ) at offset 262448","Invalid MPEG audio header (ff ff ef 29 ) at offset 262449","Invalid MPEG audio header (ff ef 29 0f ) at offset 262450"] {"file":"/var/azuracast/www/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php","line":80,"code":0} []
```

**Comment by DJMike67** [comment]
@SC2Mitch @SlvrEagle23 Many thanks for doing more testing. There seems to be 2 issues here...

1. #3298 (i.e. this issue that I am commenting on where @roger-net nor I (and I'm sure others have the same problem) cannot get ANY files uploaded via FTP to process without manual intervention (clicking MOVE as suggested by me) or adding to a playlist (as suggested by @Xara). FYI I have tested this just now and I still have the same problem - but my host has not updated. They are still on Rolling Release #bc307d2 (2020-10-21 12:52)

2. #3263 which was the issue I opened because I have several files that will not process at all (clicking MOVE / adding them to a playlist doesn't work)

As you say, with this second issue it appears to be specific files that seem to have bad metadata (which can only be discovered when uploading them via the web interface and looking at the logs or as @Vaalyn did, running them through an MP3 checker. 

I have hundreds of MP3's which are podcast episodes that I am trying to upload to Azuracast. I haven't uploaded every single one but like @SC2Mitch I uploaded a large number of them for testing and only 4 failed to process (there could of course be others that I didn't upload that would fail too)

My questions are...
1. What could be causing these 4 files to fail? They were "processed/exported" from my audio editor using the same settings that were used to process/export the other files (that CAN be processed by Azuracast). I'm no audio expert and am looking for help here

2. Is there any way to get these files to be processed successfully by Azuracast so they can be added to a playlist?

Many thanks once again



and @Vaalyn have done testing and conclude that the

**Comment by SC2Mitch** [comment]
I think its in the best interest to split the seperate bug reports up into different reports. 

I can post a detailed bug report on the files not uploading / processing properly(not appearing until manual intervention) soon as I have detailed debug logs

If you guys need any further help, I think it'll be best for you to come into our [Discord ](azuracast.com/discord)to continue the discussions.

**Comment by graemetadata** [comment]
Hi - I am experiencing a similar problem with my station's news bulletin files (there are two mp3 files: a 30-second file of about 480kb and a 3-minute file of about 3.0mb). These are automatically uploaded to the media file by SFTP every hour; this has worked without problem for several months, but for about the past two weeks the files have not been processed and the playlists that use them show zero files allocated to them.

The AzuraCast server is managed by a third-party host. 

The files sit in the Media folder with the label "File not processed". If I download them using SFTP the files play as normal so are not "broken".

If I upload the files manually to the media folder via SFTP they also show as "File not processed". 

If I upload the files manually to the home folder (where my music mp3s are) via SFTP they again show as "File not processed". 

If I download the files manually from the news agency and drag-and-drop them into Azura Music Files page they are processed as expected. 

I checked the logs I have access to via Azuracast Utilities, but could not find anything showing upload errors. 

Is asking the developer who built the SFTP functionality to introduce code to "flush Redis cache during SFTP upload" - if it doesn't already do this - going to resolve this?

Many thanks

**Comment by Takumi86ES** [comment]
I just get these errors with Storage S3.

I have uploaded two files and they are not processed. Besides that, the files had spaces and signs () () and it is not processed.

![28746af37ee5f6c530e075848c54b8c5](https://user-images.githubusercontent.com/52046665/99192196-e9122400-2771-11eb-82eb-7e29ceadeb94.png)

**Comment by roger-net** [comment]
> I just get these errors with Storage S3.
> 
> I have uploaded two files and they are not processed. Besides that, the files had spaces and signs () () and it is not processed.
> 
> ![28746af37ee5f6c530e075848c54b8c5](https://user-images.githubusercontent.com/52046665/99192196-e9122400-2771-11eb-82eb-7e29ceadeb94.png)

A provisional solution and send by the panel itself, in this case this error does not happen until this bug is resolved.
