### ISSUE TITLE
Azuracast

### ISSUE THREAD

**Issue by verdantsquare** [AzuraCast/AzuraCast#3299]
Used Centova for many years. It's garbage, but you deal with it. Total garbage though. Hit by hard-sell by shoutca.st to switch to Azuracast cos it's SO MUCH better. That turned out to be a lie. Talk radio stations are the reviled stepchild of radio... and server hosts and software and platforms prove that every day. The only thing that worked was the webdj, so I broadcast live 24/7/365, that's my life. So last night, my host installs a mandatory azuracast update... that NUKES the webdj from providing metadata... death to a talk station... or ANY station where the perpetual Now Playing is "Stream Offline." I juryrigged the stream to operate live from my studio, but without stream info, without stats, without much of the functionality for which I paid in advance. Feeling like a dupe, feeling like I'm not allowed to complain (the host company essentially told me to shut up, the stream at least is working, but with a big "go away" sign in the form of "Stream Offline," is that a good thing? I don't know, can't know if anyone is even listening... Twitter is pumping out my Now Playing, but beyond that... there are still STREAM OFFLINE messages on all eight of our network sites where the stream player appears. This product needs serious work and consideration for radio stations of ALL types. We're not all music stations. And we're tired of being treated by the companies we PAY to serve as if we are nothing and to just sod off until they decide to fix the problem and listeners fly away. So frustrated. Azuracast is just horrible.

**Comment by SC2Mitch** [comment]
I welcome you to the AzuraCast Github first and foremost. 

It's disappointing that you feel this way, the Azuracast team is a tiny team that consists of 1 main developer and many other contributors to the service, the issues that you list are strange because I've yet to see any other bug reports from other people listing the infamous `stream offline`. Furthermore you have provided no logs of your issue so it's near impossible to debug and investigate this issue. Even on my test instance, my servers are spinning up properly. 

I see that you mention a hosting provider that hosts it for you. AzuraCast does not get a say in what _third party hosts_ do to their software nor their update schedules. Silver does his hardest to ensure AzuraCast is working and releases stable 'releases' which are indeed, stable after thorough testing by the community. 

>I feel like I'm not allowed to complain

You are allowed to complain about valid issues and submit support tickets should you find a issue, with the included format (which you have not followed) 

>And we're tired of being treated by the companies we PAY to serve as if we are nothing and to just sod off until they decide to fix the problem and listeners fly away

You pay a Hosting Provider for a service, AzuraCast's developers nor maintainers have no say in what a hosting company does with it's software. 

A lot of your post seems like a massive rant with nothing constructive inside of it nor any detailed logs, the final remark you made solidifies this point. We're all struggling in a global pandemic, you've provided no logs nor a single support ticket before, you can't just kick and scream that AzuraCast is horrible without asking for help. 

Have a great day.

**Comment by DJMike67** [comment]
@verdantsquare I too host with shoutca.st. I have recently switched from Centovacast to Azuracast. I'm not going to get into a public debate about the company. I have tonight experienced a similar issue to you. 

Most of the content we broadcast is pre-recorded shows, which we broadcast via the AutoDJ. 

However each night we broadcast a 1 hour live show. A month ago I reported a problem that the LIVE banner on the Azuracast player was missing and also that it wasn't displaying the correct show title in the player.

This was fixed but after yesterday's update it has broken again. 

The little blue LIVE banner/logo is missing. 

Also the player is not displaying Stream Offline but it is displaying the title of the pre-recorded show that was playing prior to us going live (from AutoDJ). 

I have checked the Liquid Soap Log file and it is displaying the correct metadata (which is being sent from the broadcast software on my computer) but the Azuracast player is not displaying it

**Comment by SlvrEagle23** [comment]
As this issue appears to be caused by a third-party reseller that we do not work directly with, please contact them for support. We do not sell this software, it is given away by our team for free, so anything you're paying to a host is for them, not for us.

If you can trace the issues you're having back to a specific problem with AzuraCast itself, and can provide logs and screenshots or other supporting information to document the issue further, feel free to create another issue here on this GitHub.

See #3301 for more information.
