### ISSUE TITLE
Correct Metadata and LIVE Banner not showing on Live Broadcast

### ISSUE THREAD

**Issue by DJMike67** [AzuraCast/AzuraCast#3306]
My hosting company updated to Rolling Release #06808d0 (2020-10-19 11:00) • Docker • PHP 7.4 a couple of days ago. 

Since then the Azuracast player is not displaying the correct metadata. This problem is only affecting live broadcasts

Most of the content we play is pre-recorded MP3s which are played via the AutoDJ. The metadata on these is correct

Each night we do a live 1 hour chat show. We broadcast live using Audio Hijack (a Mac application) which sends the audio to the server

A piece of metadata is added to Audio Hijack which is normally displayed on the player. Yesterday the metadata was not displaying on the player although, the Liquid Soap Log was showing it correctly (which tells me it was being received by the server but just not pulling through to the player). What was being displayed was the title of the pre recorded show that was playing just before we went live

Also missing was the little blue LIVE banner that appears next to the thumbnail on the player

I have attached 2 screenshots and a ZIP file containing the relevant part of the log file

Thank you
[Liquid Soap Log.txt.zip](https://github.com/AzuraCast/AzuraCast/files/5415090/Liquid.Soap.Log.txt.zip)
<img width="640" alt="MacBitesFM" src="https://user-images.githubusercontent.com/72672017/96706064-ff54dc00-138d-11eb-83c8-5bdd6f7f0ec4.png">
<img width="640" alt="Public Page" src="https://user-images.githubusercontent.com/72672017/96706076-02e86300-138e-11eb-9bf9-d6786f34ec9d.png">

**Comment by SlvrEagle23** [comment]
@DJMike67 Thank you for the detailed report and for including the screenshots and everything else.

I was able to retrace the steps locally and find the problem, a small code error that caused the "Now Playing" updater to fail to work in instances where a broadcast was live, due to a minor problem in some recent code changes we've made.

That bug has been fixed as of the latest rolling-release update, so once your host updates it should completely resolve the issue.

Thank you for your patience.
