### ISSUE TITLE
Public Page Displays Wrong Information

### ISSUE THREAD

**Issue by WillSykesDJ** [AzuraCast/AzuraCast#3308]
Hi guys, forgive me if this is posted in the wrong place, it's my first day. Set up our Azuracast yesterday and everything is playing fine, however, I now have a live DJ playing and the public page is just showing the details of the last AutoDJ track. Any way to remedy this? Mark Dodson is currently live but Gordon Skeggs was a recording that played from a playlist before Mark went live.

Thanks

![image](https://user-images.githubusercontent.com/73242938/96745474-13183680-13be-11eb-86da-1fcb1809d37d.png)

**Comment by DJMike67** [comment]
Hi @WillSykesDJ I reported this issue today (it happened to me last night) and I have been told it has been fixed. It could be you don't have the latest version installed. If you login to your Azuracast "control panel" and look at the bottom, what does it say?

Mine says "Rolling Release #bc307d2 (2020-10-21 12:52) • Docker • PHP 7.4"

**Comment by WillSykesDJ** [comment]
Hi,

Unfortunately I don't own the server that Azuracast is on but it says Powered by AzuraCast • v0.10.3, #9811fbb (2020-06-22 4:38) • Docker • PHP 7.4

**Comment by Vaalyn** [comment]
@WillSykesDJ v0.10.3 is quite an old version. You will have to contact the owner of your server and tell them to update to the newest rolling-release version.

I'll close this issue since the problem itself has been fixed in a recent commit.
If you experience the issue on the newest version after updating please let us know.
