### ISSUE TITLE
Question Port 80 et 443

### ISSUE THREAD

**Issue by fast97** [AzuraCast/AzuraCast#3340]
Hello, can azuracast work in HTTPS on a port other than port 80 and 443? example: 60 and 343
I am in virtualization and port 80 and 443 is being used by another vm on the system.
Thank you for your reply

**Comment by YosefAdPro** [comment]
To modify the port your web application runs on, modify the configuration file in /etc/nginx/sites-available/00-azuracast. Note that some updates may overwrite this file.

https://www.azuracast.com/help/ansible/#use-non-standard-ports

**Comment by fast97** [comment]
hello I have a docker installation, I modified the ports of the .env file its running in http mode. so https does not work.
Thank

**Comment by Vaalyn** [comment]
As far as I know there is nothing that would prevent using HTTPs on a non-standard port with AzuraCast.

The only restriction this brings with it is that you can't use Let's Encrypt anymore to create and manage SSL certificates for you since that has to run on port 80/443 according to the ACME protocol specification.
