### ISSUE TITLE
Swagger is broken in live

### ISSUE THREAD

**Issue by Madpeterz** [AzuraCast/AzuraCast#3345]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.4 Stable

**Host Operating System**
Ubuntu 20.04 (LTS) x64

**Describe the bug**
after clicking an api option a spinner appears and never goes away for some api items
```
Could not find component JsonSchema_integer_int64 index.js:19:6
Uncaught (in promise) TypeError: e.get(...).keySeq is not a function
    a get-parameter-schema.js:75
    t parameter-row.jsx:101
    t parameter-row.jsx:30
    React 8
get-parameter-schema.js:75:7
    Babel 5
    t _export.js:36
    exports Babel
    Lodash 6
    xe actions.js:243
    $/</</< utils.js:137
    P Redux
    t OperationContainer.jsx:155
    value OperationContainer.jsx:89
    React 7
    w self-hosted:1161
    React 7
    handleChange Redux
    <anonymous> self-hosted:1161
    f Redux
    $/</</< utils.js:140
    P Redux
    u wrap-actions.js:9
    r system.js:174
    z system.js:461
    updateJsonSpec index.js:22
    r system.js:174
    z system.js:461
    ge actions.js:77
    $/</</< utils.js:137
    P Redux
    s wrap-actions.js:5
    r system.js:174
    z system.js:461
    updateSpec index.js:11
    r system.js:174
    z system.js:461
    p download-url.js:37
    (Async: promise callback)
    download download-url.js:26
    $/</</< utils.js:137
    P Redux
    h index.js:153
    Hn index.js:180
    onload index.html:41
    (Async: EventHandlerNonNull)
    <anonymous> index.html:39
```

**To Reproduce**

1. login to your azuracast server
2. goto /api/
3. click a item "/station/{station_id}/backend/{action}"

**Expected behavior**
it to display the api example

**Device(s):**
 - Device: Desktop
 - OS: Windows
 - Browser: Firefox [82.0.1] , Edge [86.0.622.51]

**Additional context**
This might be related
https://github.com/AzuraCast/AzuraCast/issues/3344

**Comment by SC2Mitch** [comment]
This only appears to be happening for backend related things, everything else returns back.

**Comment by Vaalyn** [comment]
@SC2Mitch Here's some debugging info that I got from copy-pasting the content of our `openapi.yml` into https://editor.swagger.io/

```
Semantic error at paths./admin/roles.post.operationId
Operations must have unique operationIds.
Jump to line 189

Semantic error at paths./admin/role/{id}.get.operationId
Operations must have unique operationIds.
Jump to line 212

Semantic error at paths./admin/role/{id}.put.operationId
Operations must have unique operationIds.
Jump to line 238

Semantic error at paths./admin/role/{id}.delete.operationId
Operations must have unique operationIds.
Jump to line 269

Semantic error at paths./nowplaying/{station_id}.get.operationId
Operations must have unique operationIds.
Jump to line 623

Semantic error at paths./station/{station_id}/queue/{id}
Declared path parameter "station_id" needs to be defined as a path parameter at either the path or operation level
Jump to line 1180

Semantic error at paths./station/{station_id}/queue/{id}.delete.operationId
Operations must have unique operationIds.
Jump to line 1213

Structural error at paths./station/{station_id}/frontend/{action}.post.parameters.1
should have either a `schema` or `content` property
Jump to line 1490

Structural error at paths./station/{station_id}/frontend/{action}.post.parameters.1.required
should be equal to one of the allowed values
allowedValues: true
Jump to line 1493

Structural error at paths./station/{station_id}/frontend/{action}.post.parameters.1.content
should be object
Jump to line 1496

Structural error at paths./station/{station_id}/backend/{action}.post.parameters.1
should have either a `schema` or `content` property
Jump to line 1515

Structural error at paths./station/{station_id}/backend/{action}.post.parameters.1.required
should be equal to one of the allowed values
allowedValues: true
Jump to line 1518

Structural error at paths./station/{station_id}/backend/{action}.post.parameters.1.content
should be object
Jump to line 1521
```

The `Operations must have unique operationIds.` semantic errors seem to be the cause of opening all blocks with the same `operationId` (you can see this by going to the swagger page and clicking on the `/nowplaying` block, it will open both the `/nowplaying` and `/nowplaying/{station_id}` blocks.

The `Declared path parameter "station_id" needs to be defined as a path parameter at either the path or operation level` error means that the `parameters` for that paths is missing the following entry:
```
-
    $ref: '#/components/parameters/station_id_required'
```

The  `should have either a "schema" or "content" property` is caused because the declaration of that endpoints have both a `schema` and a `content` defined. The `content` should be removed and the schema should have a `default:` defined.

Currently:
```
schema:
    type: string
content: restart
```

Should be:
```
schema:
    type: string
    default: restart
```

And lastly the `... .required should be equal to one of the allowed values allowedValues: true`, the `required` option can not be set to `false`. They need to be either `true` or not there at all (if they are optional).

Do you want to take care of those things @SC2Mitch?

The `openapi.yml` is generated with the [GenerateApiDocsCommand](https://github.com/AzuraCast/AzuraCast/blob/master/src/Console/Command/GenerateApiDocsCommand.php) via `azuracast:api:docs` from the `OA` annotations.

**Comment by SC2Mitch** [comment]
Working on it now

**Comment by Madpeterz** [comment]
Closing the issue for now - I will retest later
