### ISSUE TITLE
Azuracast + Plesk

### ISSUE THREAD

**Issue by mrnapz** [AzuraCast/AzuraCast#3350]
Hello Guys,

I want to run azuracast on my server but i already have plesk running on it.

Apache part its simple fix cause i can just custom ports on azuracast install, is there a way to use my plesk mariadb instead of installing again with azuracast?
Or maybe customize the mariadb port from the installation, so i can run another mariadb on the port eg. 3307

**edit: im installing via docker.**

Best Regards.

**Comment by Vaalyn** [comment]
Since you are using the recommended Docker installation method there is no conflict regarding ports with MariaDB. The container with MariaDB does not expose ports outside of the internal Docker network so there is no need to change any ports for that service.

In general it is possible to use a non-included MariaDB server but this is not something that we will support since that would be a rather unique setup that we can't debug in case of any errors with the db. I can not recommend to do this.
