### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by AaronUnmuted** [AzuraCast/AzuraCast#3355]
**Using Docker installation method**
 Yes

**Describe the bug**
We are having difficulty accessing our AzuraCast web interface with the following error being shown "Slim Application Error". http://prntscr.com/va2681

On checking the docker-compose logs, we are seeing a large number of errors such as http://prntscr.com/va26pp

How can we resolve these errors, as presumably they are linked? Any assistance would be greatly appreciated.

**Comment by SC2Mitch** [comment]
Hi @AaronUnmuted 

Can you check the docker logs for any specific [error] flags? And is your instance being overworked or stressed?

**Comment by AaronUnmuted** [comment]
Hey @SC2Mitch, the only errors I can see in the logs after a period of watching are the ones pictured above, as well as a similar error thrown by the web container which looks to be related: http://prntscr.com/va7hki

It's a large installation but the server is coping well in terms of resource usage and we're nowhere near load/RAM/disk limits.

**Comment by Vaalyn** [comment]
@AaronUnmuted most likely the amount of concurrent users is so high that the amount of allowed connections to the MariaDB is reached. I've just checked to what value that is set on my test installation and it is set to 100 (which seems to be the default value since we do not have any value defined in our repository for the docker image).

Could you connect to the MariaDB container and manually adjust the max_connections setting to a higher value to see if that resolves the issue for you?

Enter it via `docker exec -it azuracast_mariadb_1 bash` then connect to the DB via `mysql -uazuracast -p` and enter the password from your `azuracast.env` file when it asks you for the password.

The SQL command for changing the setting would be `SET GLOBAL max_connections=200;`

**Comment by AaronUnmuted** [comment]
Hi @Vaalyn - looks like you're right. I'm actually unable to get into the database because of this, the error below is shown when logging into the database.
ERROR 1040 (08004): Too many connections

What would be the best way to get in to adjust this? Huge thanks for your help so far.

**Comment by Vaalyn** [comment]
@AaronUnmuted Oh yeah, I didn't think about that... connecting from the console is still a new connection...

I'm not really sure how you could connect to it without dropping existing connections. Your best bet would be to manually restart the database by restarting the container via `docker-compose restart mariadb`. That should make it possible to connect manually before all connections are saturated (hopefully).

**Comment by AaronUnmuted** [comment]
@Vaalyn Great that worked absolutely fine, though unable to run the command with error: `ERROR 1227 (42000): Access denied; you need (at least one of) the SUPER privilege(s) for this operation`

**Comment by Vaalyn** [comment]
Oh, yeah then please try with the user `root` and look in the output of `docker-compose logs mariadb` for this line `GENERATED ROOT PASSWORD: xxxxxxxx` to get the password of the root user since this is auto generated.

**Comment by Vaalyn** [comment]
@AaronUnmuted try this command to find it more easily: `docker-compose logs mariadb | grep "GENERATED ROOT PASSWORD:"`

**Comment by Vaalyn** [comment]
@AaronUnmuted I've added the possibility to increase the `max_connections` limit via the `MYSQL_MAX_CONNECTIONS` environment variable. Please add `MYSQL_MAX_CONNECTIONS=200` (or some other value higher than 100) to the `azuracast.env` file in `/var/azuracast` and update your installation.
