### ISSUE TITLE
Is there a Liquidsoap  alternative ?

### ISSUE THREAD

**Issue by Radio-Quergedacht** [AzuraCast/AzuraCast#3378]
Is there a Liquidsoap  alternative ?

**Comment by SC2Mitch** [comment]
If you mean a alternative that works natively with AzuraCast? I don't believe so, no. The options are IceCast / ShoutCast (frontend) and the AutoDJ / Liquidsoap backend. You can't change that so easily.

**Comment by SlvrEagle23** [comment]
@Radio-Quergedacht We have certainly looked into adding support for other backend software, since our software has modular support for various backends/frontends and it would be somewhat trivial to implement, but the only two other options out there right now are:
 - Shoutcast's transcoder (sc_trans) which is proprietary, or
 - ices, the source streaming tool from the group that makes Icecast, which only supports ogg vorbis unless you use ices_cc, the CentovaCast branch of it (which is, granted, open-source, unlike CentovaCast itself)

And both basically just take a single list of files and transcode them in order, or take the output of a program and output whatever file it supplies. The latter would be usable with our AutoDJ, though.

**Comment by Vaalyn** [comment]
Closing since the question was answered.

In regards to `ices_cc` I'd like to add that the last release for that was in 2012 so 8 years ago (and is based on ices0 which is unmaintained too since ices2 exists). Personally I'm against including / supporting unmaintained software in AzuraCast that we (most likely) can't maintain ourself.
