### ISSUE TITLE
QUESTION: SFTP upload issues

### ISSUE THREAD

**Issue by graemetadata** [AzuraCast/AzuraCast#3380]
Hi - I am experiencing a similar problems to other users with files beng uploaded by SFTP that are not being processed.

My station's news bulletin files (there are two mp3 files: a 30-second file of about 480kb and a 3-minute file of about 3.0mb) are automatically uploaded to the media folder by SFTP every hour; this has worked without problem for several months, but for about the past two weeks the files have not been processed and the playlists that use them show zero files allocated.

The AzuraCast server is managed by a third-party host so I have limited access to logs. I checked the logs via AzuraCast Utilities, but could not find anything showing upload errors..

The files sit in the Media folder with the label "File not processed". If I download them using SFTP the files play as normal so are not "broken".

If I upload the files manually to the media folder via SFTP they also show as "File not processed".

If I upload the files manually to the home folder (where my music mp3s are) via SFTP they again show as "File not processed".

If I download the files manually from the news agency and drag-and-drop them onto Azura Music Files page - or use the "select file" route o the page - they are processed as expected.

Is asking the developer who built the SFTP functionality to introduce code to "flush Redis cache during SFTP upload" - if it doesn't already do this - going to resolve this?

Many thanks

**Comment by SC2Mitch** [comment]
What version of azuracast is the host using?

**Comment by officialgamerfm** [comment]
yea ive had a few files show the same thing. Not sure why , i also need to  remove them before i can add them to a playlist otherwise nothing happens.

**Comment by graemetadata** [comment]
> What version of azuracast is the host using?

Hi - it's Rolling Release #1f79f86 (2020-10-30 19:10) • Docker • PHP 7.4 

I've seen a couple of similar issues mentioned in this forum, with "sending files by FTP problem" the most closely aligned. 

Thanks

**Comment by Vaalyn** [comment]
Please check if this problem still exists on the newest AzuraCast version as there have been quite a lot of updates regarding this problem and other users said that this problem was resolved through those updates.

Furthermore there might be files in your library that are not being processed due to `Invalid audio header` errors. You can see those in the `AzuraCast Application Log`. If you see those you need to re-encode these files as they contain invalid data that we can not fix from our side.

Since I'm assuming this problem to have been fixed (as seen per the other issues about this) I'm closing this issue. If you still have this issue on the newest version and there are none of those errors I mentioned, please let me know and I'll re-open this issue.

**Comment by graemetadata** [comment]
Hi - the host appears to have been advised that it was running too many incidences of AzuraCast on one server and has migrated some stations - including mine - to a new server with a limited number of stations. This, and perhaps the fact it is running Rolling Release #1604799, has resolved the file processing issue. Latterly the old server was running what was decsribed as a "stable release" - although the user experience was anything but stable.

**Comment by Vaalyn** [comment]
Good to hear that the issue has been resolved. 👍 

> Latterly the old server was running what was decsribed as a "stable release" - although the user experience was anything but stable.

The stable releases do not guarantee absolute stability since AzuraCast is still beta software (indicated by there being no 1.0 version, only 0.x versions). Those "stable" releases are reasonably stable as far as we are aware at the time were we release those. Also your hoster, following what you have said about them, has apparently cheaped out on their own servers in order to save money thus resulting in a bad experience in general for their users. This is nothing that we can influence though.

In general since you are paying a third party to host AzuraCast (which we are not affiliated with) you should contact them to resolve any issues you encounter with their hosting. They should be responsible for contacting us and not their customers since that is basically shifting their support responsibility onto us.
