### ISSUE TITLE
MIsleading http response codes

### ISSUE THREAD

**Issue by LordRampantHump** [AzuraCast/AzuraCast#3381]
Why is for example a duplicate song request returning a 400 error?

It should be a 200 http with an error message not an all out bad request!

**Comment by Vaalyn** [comment]
In general a status code `200` would only be correct if the request was successfully handled and accepted by the server.

Since the request is basically rejected due to a it being a duplicate song request it does not make sense to lie to the client by giving it a `200 OK` response with an error message.

Technically we should use the status code `409` to be more specific.

See the [Wikipedia entry](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#409):

> ### 409 Conflict
> Indicates that the request could not be processed because of conflict in the current state of the resource, such as an edit conflict between multiple simultaneous updates.

**Comment by LordRampantHump** [comment]
depends how you look at it i guess. I see "duplicate song request"as informative and not an error at all. Regardless, seems we both agree 400 is not the correct response

**Comment by SlvrEagle23** [comment]
It's quite common for REST APIs to return non-200 codes when the action you submitted and attempted to do failed in any way. In this case, the `HTTP 400 Bad Request` is a correct response when the request is made that we can't fulfill for technical reasons. 

Per @Vaalyn, since HTTP 409 is more accurate we can switch to that, but the use of a 400-class error code is not a problem given the design of our API.
