### ISSUE TITLE
Shuffle playlist doesn't play all songs

### ISSUE THREAD

**Issue by realmilandev** [AzuraCast/AzuraCast#3388]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.3, #2093d49

**Host Operating System**
Ubuntu? 

**Describe the bug**
Shuffle doesn't play all songs that it has in the playlist. 
I have all my songs assigned to a playlist (default) and it doesn't play all songs.
I have 200 songs, but only plays like 120 of them. (even tho they are all in the same playlist)

**To Reproduce**
1. Create playlist with shuffle 
2. Assign all songs to the playlist
3. Make it play all songs.

**Expected behavior**
Plays all songs in a shuffled order.

**Relevant Logs**
2020/11/09 09:07:55 [main_next_song:3] Prepared "/var/azuracast/stations/main/media/Music/24kgoldn_-_mood.mp3" (RID 8).
2020/11/09 09:07:55 [cross_7788:3] Analysis: -46.776897dB / -19.831558dB (2.99s / 3.01s)
2020/11/09 09:07:55 [crossfade:3] Simple transition: crossed, fade-in, fade-out.
2020/11/09 09:07:55 [lang:3] AzuraCast Feedback Response: OK

**Screenshots**
-

**Device(s):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Vivaldi (chrome based)
 - Version: -

**Additional context**
-

**Comment by RossFlys** [comment]
Hi @realmilandev,

I have tried to replicate the problem, and I was unable to do so. From my understanding of the log I am unable to see any errors there. It showed the **Feedback Response** as _okay_. 

Please can you make sure you do not have any rules setup, that may conflict with your (default) playlist. 

If you have not already, I'd suggest updating your version of the system to the latest version, and reply if you still continue to have problems. 

Thanks,

Ross

**Comment by realmilandev** [comment]
Its the latest version since i got it 3 days ago.
I listened for a while and i heard the same song twice in 15m. Even tho the playlist says it has 6.2h of music.
And the logs don't tell me anything but thought that was relevant.

**Comment by Vaalyn** [comment]
> Its the latest version since i got it 3 days ago.

That does not really match with what you wrote as your version (`v0.10.3, #2093d49`) since that version is ~5 months old now and we have been releasing quite a lot of fixes/updates since then. (Also the current "stable" release v0.10.4 is now also around 1 month old so I'd recommend going with the rolling-release update channel instead of the "stable" one.

If you are using an up to date version and you are seeing the same song being played multiple times in such a short time range please check if your playlist has the `Avoid Duplicate Artists/Titles` option activated and also configure the `Duplicate Prevention Time Range (Minutes)` in the `Station Profile` to the amount that you'd like it to take into account. By default this is set to 120 minutes.

**Comment by Vaalyn** [comment]
Closing as there has been no response for ~1 month.
