### ISSUE TITLE
how to remove default radiolize ads sound playing on my station

### ISSUE THREAD

**Issue by jingis2020** [AzuraCast/AzuraCast#3408]
how to remove default radiolize ads sound playing on my station

**Comment by Vaalyn** [comment]
In general you can change the default track that a station is playing when nothing else is playing by following [this tutorial](https://www.azuracast.com/help/docker/#using-a-custom-default-track).

Since you are not self-hosting though I doubt that you have access to the server your AzuraCast station is running on so this will most likely not help you.

We are not affiliated with your hoster so you'll have to contact them about this.
