### ISSUE TITLE
Storage S3 AWS

### ISSUE THREAD

**Issue by Takumi86ES** [AzuraCast/AzuraCast#3413]
Any tutorial on how to use this with Azuracast? I have tried to configure it but I always get errors.

A tutorial would do.

Help.

**Comment by Vaalyn** [comment]
What errors do you get?

**Comment by Takumi86ES** [comment]
> What errors do you get?

I don't understand what to endpoint. AWS does not explain well.

Help us understand each option and how to get it on AWS.

**Comment by Vaalyn** [comment]
Honestly, the AWS interface is crap and their documentation too convoluted for someone who has no prior experience with AWS. Here is their page for endpoints: https://docs.aws.amazon.com/general/latest/gr/s3.html

Building a whole tutorial on how to navigate the AWS interface is (in my opinion) out of scope for this project since this feature is not specific to AWS but rather the S3 protocol itself. Also there are a lot of tutorials out there already which should explain everything about AWS S3 including how to set it up and get the credentials.

I'd recommend you to go with something like [Digital Ocean Spaces](https://www.digitalocean.com/products/spaces/), [Wasabi](https://wasabi.com/), [OVH Object Storage](https://www.ovhcloud.com/en-ie/public-cloud/object-storage/) or any other S3 compatible storage provider. Most of them are a lot cheaper than AWS and most definitely have much better interfaces / documentation.

**Comment by Takumi86ES** [comment]
It would be nice if you can use dropbox, google drive or similar.

Thank you very much for your time.

Closed.
