### ISSUE TITLE
Limited kbps

### ISSUE THREAD

**Issue by AleeRobles** [AzuraCast/AzuraCast#3455]
Is there a way to limit which stations transmit up to 128 kbps? and in case of overcoming they are disconnected. They don't have the autodj

**Comment by Vaalyn** [comment]
This is currently not possible to restrict via AzuraCast.

If you can live with the restriction that anyone who is able to edit a mount being able to remove it you can try using the following config in the mount points `Advanced Custom Frontend Configuration`:
```
<limit-rate>128000</limit-rate>
```

There is already a feature request for this [here](https://features.azuracast.com/suggestions/48298/limits) and [here](https://features.azuracast.com/suggestions/113370/station-bitrate-limits) so I'll close this issue here.
