### ISSUE TITLE
Media editor failed saving data

### ISSUE THREAD

**Issue by PecceG2** [AzuraCast/AzuraCast#3463]
**Using Docker installation method**
No

**AzuraCast version**
Public demo

**Host Operating System**
Public demo

**Describe the bug**
Mysql return error on saving data on media editor:
Doctrine\DBAL\Exception\DriverException at /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php L128: An exception occurred while executing 'UPDATE station_media SET fade_out = ?, cue_in = ?, cue_out = ? WHERE id = ?' with params [137.7, 22.3, 24.7, 9]: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'fade_out' at row 1

**To Reproduce**
Go to "Music files" -> Select any song -> Edit -> Set fade out and save it.

**Expected behavior**
Save correctly fade out data.

**Relevant Logs**
None

**Screenshots**
![image](https://user-images.githubusercontent.com/31479677/100277820-95a68f80-2f42-11eb-95bb-41bbeee1305d.png)

**Device(s):**
Google Chrome | 87.0.4280.66 (Build oficial) (64 bits) (cohort: 87_66_Win)
OS | Windows 10 OS Version 2009 (Build 19042.630)
JavaScript | V8 8.7.220.2

**Additional context**
None

**Comment by SlvrEagle23** [comment]
@PecceG2 How long is that file?

**Comment by Vaalyn** [comment]
@SlvrEagle23 I've encountered this problem when playing around with the Visual Editor too.

This is due to the `fade_overlap`, `fade_in` and `fade_out` fields being defined with a `precision` of `3` and a `scale` of `1` which limits the values to a maximum of `99.9`.

I'm not sure how many valid cases there are of having such long fades so I don't know if those field definitions should be extended but we should make it clear that there is a maximum, prevent that from being exceeded in the Visual Editor as well as in the manual fields for those values and either prevent that from being send to the server or add a validation that shows a readable error message.

**Comment by SlvrEagle23** [comment]
@Vaalyn We could easily migrate that to a higher value, but the question is what precision level would be high enough?

5 in this case would allow up to 9999.9 seconds, which is just 2.7 hours. Lots of folks have longer tracks than that (for whatever reason).

6 would allow 27 hours, which seems like it lines up well with our upper limits of what we can tolerate in music files.

**Comment by Vaalyn** [comment]
> but the question is what precision level would be high enough?

Good question.
What I'm thinking is who wants 2 tracks to fade for longer than 2.7h?

So in general yeah lots of people have super long tracks and for the Cue points it definitely makes sense to be able to have a value that can span 27h. For fades I'm not sure if anyone would ever want to fade 2 tracks over 999s over each other...
Not that I mind having the ability to do so but logically I can't see a reason to ever to that.

**Comment by SlvrEagle23** [comment]
@Vaalyn I agree, I just really don't want to have to do another migration on `StationMedia` for a good long while, and honestly I don't think the added precision really makes a significant difference in the footprint of the table.
