### ISSUE TITLE
No metadata from "streamer"

### ISSUE THREAD

**Issue by HowardCrane** [AzuraCast/AzuraCast#3464]
_Edit:_ I've noticed that encoding the stream as mp3 instead of ogg remedies this. What do I not know about the ogg encoding? Maybe this issue needs closed. Sorry

Hi folks,
I'm using Mixxx to stream to my Icecast server. I would test out other clients, but I'm on Linux and can't seem to use anything else.
Once I connect, the now_playing metadata goes blank. I read something about that possibly being the case until the first song finishes playing through, so I tried that and loaded another track, with no change. I've exhausted searches on this issues board and web searches. What steps can I take to find the problem? Which logs should I look at, if any?
This is my connection settings below.

![Selection_196](https://user-images.githubusercontent.com/4707494/100287456-97854880-2f6c-11eb-99c0-f6baf295fa1d.png)

As a separate question. Is there any documentation on passing metadata values from a streamer to custom fields in the Azuracast metadata? If not, shall I make a feature request?

**Comment by HowardCrane** [comment]
Sorry for all the confused noise here, folks. My streaming metadata is just... crap.
Connecting Mixxx results in now_playing displaying the song last played in the previous setting (even after rebooting Mixxx). This isn't a problem, but a clue. The server isn't recognising my album art (which I set with Picard/MusicBrainz) nor the meta tag "URL Artist", which I associated with a custom field. 

How do I determine whether this is my streamer, my instance of Azuracast, or Azuracast itself?

Thanks

**Comment by Vaalyn** [comment]
If it hasn't changed since I last checked AzuraCast doesn't try to pull album artwork for the currently playing song from the live stream of a DJ.

Also Mixxx doesn't support sending album artwork in the metadata: https://github.com/mixxxdj/mixxx/wiki/cover_art_support

I'm also not sure if Mixxx sends the `url_artist` field. I'm reasonably sure that we don't read it from a live stream but I have no idea if it's even contained in the streamed data.

**Comment by SpeedyCharly** [comment]
According to the setting I see here on the Mixxx window, the artist & title data should stream properly through to Azuracast.

My question, are the file properties properly set and readable in your Linux storage media???

**Comment by HowardCrane** [comment]
Hi @SpeedyCharly,
Only today I got an instance of Windows 7 running and, indeed, it's pushing artist and title to Azuracast. What's missing on my Linux setup? Mixxx recognises the metadata exactly the same.
Thanks a lot

**Comment by SpeedyCharly** [comment]
If you have Win 7 on board, why are you streaming via Mixxx on Linux.  Mixxx works fine in windows

**Comment by Vaalyn** [comment]
> If you have Win 7 on board, why are you streaming via Mixxx on Linux. Mixxx works fine in windows

Could be because he's using Linux as his daily driver OS. Not everyone wants to use Windows, especially since W7 is now unsupported by MS since January and W10 is very intrusive in their data collection.

@HowardCrane Can you try connecting directly to the IceCast server via the `Source Password` from the station profile?

I'd like to check if this is a general problem with your Mixxx installation or something in the combination with using Mixxx with Ogg Vorbis on Linux and connecting to Liquidsoap via the DJ accounts.

**Comment by SpeedyCharly** [comment]
The last version of Mixxx that I personally tested did push the metadata through much in the same way most high end streaming apps do.  That version looked and operated like a "Sam Broadcaster Lite" alternative.  They have since moved on to emulating VirtualDJ and I have lost interest, but I presume that it still broadcasts the metadata to Azuracast in much the same manner as it did.  But then, I never attempted to use Ogg-Vorbis format... could that be the source of the issue?
