### ISSUE TITLE
corrupted files in overlay2

### ISSUE THREAD

**Issue by fast97** [AzuraCast/AzuraCast#3473]
Hello, for the last update I think azuracast keeps corrupted files. I launch a search and can't find a file.
Thanks

/var/lib/docker/overlay2/9102fac421e5c258328d26332a758e7ca97c0e04362dd89400b267375b1df693/diff/var/azuracast/

**Comment by Vaalyn** [comment]
I think this StackOverflow question and more specifically the answer from the user `BMitch` should answer your question: https://stackoverflow.com/questions/46672001/is-it-safe-to-clean-docker-overlay2

Those directories should **not** be removed and we already run `docker system prune` after each update.

Since it's quite important I'll cite a comment from that same SO question (I don't mean this in a bad way, I just want to highlight that this really shouldn't be touched manually):
> You're free to ignore this advice, but please don't ask me for advice on how to recover a failed system after you break it
