### ISSUE TITLE
DJ cannot connect

### ISSUE THREAD

**Issue by Rootinator** [AzuraCast/AzuraCast#3474]
Hello,

I would like to connect live to Azuracast with streaming software (Mixxx). Unfortunately the connection always fails because Mixxx reports "Socket is busy".

I've tried Icecast and Shoutcast in Mixxx, nothing works.

Port is activated in the firewall (DJ port 20123 / tcp).
The Azuracast server does not have its own IPv4, the ports are forwarded to the server via NAT.

_Azuracast web interface_
example.com:9123

_DJ port_
20123

**I'm trying to connect to Mixxx ↓**

_Streaming type_
Icecast2

_User_
test

_password_
abcdef123

_mountpoint_
/livestation

_Host_
example.com:20123
or
192.168.0.123:20123

I don't know what the problem is, why Mixxx cannot connect to Azuracast?

**Comment by officialgamerfm** [comment]
are you using the connection settings displayed on the Streamer/DJ accounts page?

**Comment by Rootinator** [comment]
I enter this data from the Azuracast web interface from the right side in my broadcast program ...

Settings Live DJ Azuracast:
![Unbenannt](https://user-images.githubusercontent.com/47688741/100523838-c80af380-31b3-11eb-907c-427dba572826.PNG)

Mixxx settings:
![mixxx](https://user-images.githubusercontent.com/47688741/100523947-7e6ed880-31b4-11eb-901f-e3d424df0dc2.PNG)

**Comment by Vaalyn** [comment]
Since you are using a port that is not included in the default port range from 8000-8499 I'm assuming that you have correctly changed the `AUTO_ASSIGN_PORT_MIN` and `AUTO_ASSIGN_PORT_MAX` environment variables as well as added a `docker-compose.override.yml` with the port forwarding for the container according to this page: https://www.azuracast.com/help/docker/#expand-the-docker-radio-station-port-range

I'd recommend you to check with a port scanner if the port is actually reachable.
