### ISSUE TITLE
Overlap not drawn in Visual CUE editor

### ISSUE THREAD

**Issue by walterdevos** [AzuraCast/AzuraCast#3476]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.10.4 Stable

**Host Operating System**
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"

**Describe the bug / And reproducing **

In the Visual CUE editor, SET OVERLAP will not color the region when the CUE IN is long. If you go the length of the CUE IN forward in the song, the OVERLAP is drawn.

long cue in:
image
![image](https://user-images.githubusercontent.com/3726763/100475664-ff11d400-30e3-11eb-9fb9-6fa689f40eb2.png)

click on OVERLAP, nothing shows:
![image](https://user-images.githubusercontent.com/3726763/100475675-0507b500-30e4-11eb-8649-4fddc7dda580.png)

click on OVERLAP ( aprox the CUE IN time back ) and it starts working.
![image](https://user-images.githubusercontent.com/3726763/100475697-1224a400-30e4-11eb-810b-ef050309f47d.png)

**Expected behavior**
Always draw the overlap region.

**Relevant Logs**
See screens

**Screenshots**
See screens

**Device(s):**
Web

This is linked to issue 3467 https://github.com/AzuraCast/AzuraCast/issues/3467
3467 was about the cue_out not send to Liquid.

Cheers!

**Comment by Vaalyn** [comment]
Copied from that other issue to keep track of what I found out so far:

The problem with the Overlap seems to be due to the assumption that the Overlap value is also a duration seen from the beginning of the file like the Cue In / Cue Out which is not the case as that is the duration as seen from the Cue Out point. See this part of the frontend code: https://github.com/AzuraCast/AzuraCast/blob/master/frontend/vue/station_media/form/MediaFormWaveformEditor.vue#L127

I'm currently researching what the Overlap exactly does behind the scenes and how it should be used so that I can correctly fix this without breaking anything.

**Comment by walterdevos** [comment]
For what it's worth:

In the "Advance Playback Settings" the overlap is also found in the "Custom Fading: Overlap Time (seconds)" field. 
![image](https://user-images.githubusercontent.com/3726763/100477006-65e4bc80-30e7-11eb-88d0-ef119abf01ce.png)
In the logs, it's value is found in the  liq_cross_duration="0.50"
![image](https://user-images.githubusercontent.com/3726763/100477104-b1976600-30e7-11eb-8696-58b72705c5ae.png)
( checked it for 1 jingle and 2 songs )

In
https://github.com/savonet/liquidsoap/blob/master/libs/fades.liq

liq_cross_duration overrides the duration of the crossfade ( line 218 ). The bigger the value is, the sooner the crossfade will start.

👍
