### ISSUE TITLE
[Question] How to add buffer to improve stream stability?

### ISSUE THREAD

**Issue by SwaXTech** [AzuraCast/AzuraCast#3486]
Hi. I am new using Azura Cast. I love it. My org has been using Centova Cast for years.
Congratulations for this project.

I want to keep a 20s buffer to improve stream stability.
Our listeners doesn't have a good connection. Sometimes they lost connection and the stream stops until connects again.
In our app we can use a 'buffer' but we don't want to load 20 seconds before start playing.

I found on Icecast Docs 'burst size' and 'queue size' options on icecast.xml file.
I have modified this file on /var/lib/docker/volumes/azuracast_station_data/myradio/config/
But there is no difference.
If I restart server, the icecast.xml file get back to default state.

Also I found an 'advanced option' DJ/Streamer Buffer Time but this is not that I want.

There is a way to do this?

Thank you!

PD: I don't speak english. If something in this post has no sense please tell me and I will to explain this again

**Comment by Vaalyn** [comment]
Hey, I've been using the `burst-size` setting of IceCast on my own radio station to increase the reliability when a user first connects to a stream.

You can set this by adding the following to the `Advanced Custom Configuration` in the `Station Profile` -> `Broadcasting` tab:

```
<limits>
    <burst-size>128000</burst-size>
</limits>
```

I haven't manually set the `queue-size` setting since this is by default set to 512k which is enough for my use-case but you can add that setting to the `Advanced Custom Configuration` like with the `burst-size`. So the block would look like this (you should experiment with the `queue-size` and `burst-size` until you have the buffer amount that you desire):

```
<limits>
    <queue-size>2048000</queue-size>
    <burst-size>128000</burst-size>
</limits>
```

**Comment by SwaXTech** [comment]
Thanks You! It works!.
