### ISSUE TITLE
Master Slave 

### ISSUE THREAD

**Issue by favergara** [AzuraCast/AzuraCast#351]
Hi,

We are trying to use master slave scenario. We already deploy azuracast like master and mutiple slave with icecast-kh but we discovered some problems. 
1. We have multipler users connected to slave but Stats shows 1 client connected  (slave client and ip)
2. If we use same port for multiple mountpoints stats are not divided per radio station. (master slave scenario)

Thanks

**Comment by SlvrEagle23** [comment]
@favergara Essentially, the issue you're running into here is that AzuraCast wasn't built to support either use-case in your current scenario. It's intended for simpler scenarios, where the entire radio "stack" is run on a single machine and each port corresponds to a unique radio station with a unique playlist.

The issue related to statistics only showing one listener may be related in part to #293.

Otherwise, for the sake of simplicity for a majority of our use cases, the software isn't configured to support multiple stations with different playlists occupying a single port range via multiple mount points.
