### ISSUE TITLE
How can I block the IP?

### ISSUE THREAD

**Issue by AleeRobles** [AzuraCast/AzuraCast#3511]
How can I block the IP?

**Comment by Vaalyn** [comment]
This is a pretty unclear question.

Please describe what you want to do exactly, what do you want to block "the IP" from doing and do you mean IPs of users in general with "the IP"?

**Comment by AleeRobles** [comment]
> This is a pretty unclear question.
> 
> Please describe what you want to do exactly, what do you want to block "the IP" from doing and do you mean IPs of users in general with "the IP"?

There are web pages that repeat the streaming of my radios, I have the IPs and I put them in the "list" of blocked IPs but they can still be reproduced, it is not understood how exactly this functionality works.

**Comment by Vaalyn** [comment]
Since the servers that those websites are hosted on are not proxying your stream your can't prevent them from just linking to your stream. It's not the server that connects to your stream and then pushes that to the users of that website. The users that visit the website are directly connecting to your stream so you'd have so basically ban every single user that visits those websites.

What you'd need to look into is adding CORS headers to the IceCast configuration to prevent the users browsers from allowing to load the stream on a website that's not the ones you have whitelisted.

See https://icecast.org/docs/icecast-2.4.1/config-file.html#global-headers

More specifically this header where instead of `*` there should be your website:
```
<header name="Access-Control-Allow-Origin" value="*" />
```

For more information look here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
