### ISSUE TITLE
Shoutcast not running in the https port

### ISSUE THREAD

**Issue by Gujalls** [AzuraCast/AzuraCast#3513]
**Using Docker installation method**
Yes

**AzuraCast version**
 AzuraCast • v0.9.8.1

**Host Operating System**
CentOs 7

**Describe the bug**
Shoutcast server not running in https port

**To Reproduce**
Dear Team,

I have set the AZURACAST_HTTPS_PORT=7443 in the .env file.
From the Dashboard : I have enabled "Always use HTTPS" under System Settings.
I access my dashboard at https://mydomain:7443/dashboard 

I Click -> Manage button under the Radio and go into the Radio Management Page.
Here I can find the streams box in the right where it shows my stream details running at 128kbps. Below is the stream url
https://mydomain:7443/radio/8010/radio.mp3

When I click it - I get 404 error
However the below url works correctly but it's in http rather than https
http://mydomain:8010/radio.mp3

Please can you let me know what is that i'm missing.

**Expected behavior**
I expect that the stream is running
https://mydomain:8010/radio.mp3 rather than in http.

Please can you help me know what is missing.

Many thanks

**Comment by Gujalls** [comment]
Is there something that I must be doing to get this work :(

I tried using an Icecast stream and has not helped. Shoutcast stream seem little better that at the least I was able to hear the stream but with Icecast I can't even trace to the right url that I should be using to hear. 

From the dashboard - the admin url is shown as 
https://mydomain:7443/radio/8000/admin.html - doesn't allow me to login and get 404 not found error
tried https://mydomain:8000/admin.html - didn't work.
I'm stuck and don't know what to do to listen to the stream. :(

Please can someone help.

**Comment by Vaalyn** [comment]
Accessing Shoutcast directly via HTTPS on the port that Shoutcast is running on is not possible since using SSL is a premium only feature according to the Shoutcast Wiki about the DNAS 2.6+ and their pricing plans: https://www.shoutcast.com/Pricing and we are not including any premium specific features for Shoutcast in AzuraCast.

I've just tested accessing the Shoutcast admin page via the nginx proxy via https://example.com:7443/radio/8000/admin.cgi after changing my HTTPS port to `7443` and see no error. I can also listen to the stream via `https://example.com:7443/radio/8000/radio.mp3`.

Since you are using AzuraCast in version `v0.9.8.1` which is now ~11 months old I'd recommend you to update to the newest version `v0.11.2`.

**Comment by Gujalls** [comment]
Hi,

1) I'm little bit scared to update my current version of Azuracast. I've 1 TB of data and have no space to backup.
Am I ok to just do a direct update? Will that delete my files? Will that change all the config that has been set, like port, radio stations, playlist etc? Please let me know.

2) When trying to access "https://example.com:7443/radio/8000/radio.mp3." - I keep getting 

> 404
> Not found.
> The requested resource could not be found. Please verify the URI and try again.

Please can you help me know what is the wrong I'm doing since I keep getting error.

3) I try accessing the public page of the radio.. like https://example.com:7443/public/my_station
I could see a player running but I don't hear any sound - tried to listen in different browsers, trying enabling/disabling the audio output of the browser settings but I'm not able to listen to it. Please can you help me know what is that I'm doing wrong.

Thanks very much for your help & support. Greatly apprecaited.

**Comment by Vaalyn** [comment]
> 1. I'm little bit scared to update my current version of Azuracast. I've 1 TB of data and have no space to backup.
>    Am I ok to just do a direct update? Will that delete my files? Will that change all the config that has been set, like port, radio stations, playlist etc? Please let me know.

(I'm assuming that you have a lot of media files of "normal" song length and not few files but really long)

I have never encountered a station with that much media files so I can't really say what will happen exactly. I can tell you that there have been some rather big changes to the database regarding the station media which can take a long time to process with decently sized stations. No idea how long that would take with this huge amount of media files.

If it's not the case that you have lots of files but just a few pretty big/long files then this is probably not as much of an issue.

> 2. When trying to access "https://example.com:7443/radio/8000/radio.mp3." - I keep getting
> 
> > 404
> > Not found.
> > The requested resource could not be found. Please verify the URI and try again.
> 
> Please can you help me know what is the wrong I'm doing since I keep getting error.

Your station is using port 8010 (as per your own comment) so you need to use `https://example.com:7443/radio/8010/radio.mp3` instead of `https://example.com:7443/radio/8000/radio.mp3`


> 3. I try accessing the public page of the radio.. like https://example.com:7443/public/my_station
>    I could see a player running but I don't hear any sound - tried to listen in different browsers, trying enabling/disabling the audio output of the browser settings but I'm not able to listen to it. Please can you help me know what is that I'm doing wrong.

Look into your browsers JS console for any errors. Without seeing any errors I can't say much.
