### ISSUE TITLE
Apache2 ports changed but : azuracast_nginx_proxy_1 ... error !

### ISSUE THREAD

**Issue by Keepshango** [AzuraCast/AzuraCast#3519]
Hello, 

HTTP port 80 and HTTPS port 443, being **default ports for both AzuraCast and Apache2** (in use on my server), is probably the reason why I get this error shown when instaklling the app : 

**azuracast_nginx_proxy_1 ... error**
Please see terminal attached image to view details  : https://i.imgur.com/cBDwyvG.png

**Then I did change these ports to new ones for Apach2 in every files listed below.** : the **new http port 8092** and **https port 442** were set **for apache2** in **, after having being **allowed in the firewall section of my Cpanel**.

I relaunched AzuraCast app installation, but the error remains !

**Apache2 ports were changed in files :**
/ect/apache2/ports.conf
/ect/apache2/sites-available/000-default.conf
/ect/apache2/sites-available/default-ssl.conf
/ect/apache2/sites-available/otherwebsite.mydomain.net.vhost

Could it be that I forgot files where ports for apache2 needs to be changed…?
Shall I uninstall and re-install AzuraCast, to insure it has logged such these changes, and to get the error solved ?
If not, I need help to get rid of this error !

Regards

**Comment by taiBsu** [comment]
Did you install AC via Docker or manually?

**Comment by Vaalyn** [comment]
We do not provide support for Apache2 or Cpanel issues. I recommend you to look for tutorials regarding changing ports with Apache2 on a Cpanel server.

In general you need to change the ports that Apache2 is using and restart Apache2 afterwards so that these changes apply. Then you should be able to install/start AzuraCast on the default ports.

You can use the `netstat -ltnup` command in the terminal to view which port is used by which program. This might be helpful.
