### ISSUE TITLE
Incorrect server name at Streamer/DJ Accounts page

### ISSUE THREAD

**Issue by pilovali** [AzuraCast/AzuraCast#3565]
**Using Docker installation method**

Yes

**AzuraCast version**
Rolling Release #c146166 (2020-12-13 13:59) 

**Host Operating System**

Ubuntu something. Probably 20.04, forgot.

**Describe the bug**

The server name has https:// in front of it. This wasn't in previous versions.

**To Reproduce**

Go to Streamer/DJ Accounts and look on the left.

**Expected behavior**

It should've have https:// in front of it.

**Relevant Logs**

**Screenshots**

Current: https://cdn.discordapp.com/attachments/647149735991443467/787744398934540338/unknown.png
Old: https://cdn.discordapp.com/attachments/647149735991443467/787744844944113684/TRwtPsb.png

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SC2Mitch** [comment]
From digging into the code it appears it pulls the $server_url and it doesn't specify if it pulls the `https` or `http` just the url, I don't believe this is a bug, because if I put in the `https` while attempting to connect via Mixxx or any other programs, it works fine. The old picture in question is fairly old and has gone under several revisions, I'll look into updating the documentation with the up to date pictures soon. 

Code in question: https://github.com/AzuraCast/AzuraCast/blob/c4279608e81aa9f4c55f071ab7f82590f3c3388a/templates/stations/streamers/index.phtml#L18-L24

**Comment by pilovali** [comment]
It's not a https protocol, right? So why would it show like that. It'll only confuse people imo.
It wasn't like that before, so I believe it should be the same.

**Comment by Vaalyn** [comment]
From what I can see in the code that fills that part of the info panel there has never been any code to explicitly make this show a schema-less URI. The URI is taken from the `Site Base URL` and will not contain the schema when that (http / https in front of the domain) is not set there.

> It's not a https protocol, right?

Actually the Shoutcast 1 and IceCast protocols are both using the HTTP protocol (and in extension HTTPS) as their transport layer protocol.

IceCast protocol: https://gist.github.com/ePirat/adc3b8ba00d85b7e3870
Shoutcast 1 protocol: https://www.radiotoolbox.com/community/forums/viewtopic.php?t=74


The Shoutcast 2 protocol seems to be using somethin proprietary but since we are not focusing on proprietary software that should in my opinion be neglected for the sake of this discussion.
http://wiki.shoutcast.com/wiki/SHOUTcast_2_%28Ultravox_2.1%29_Protocol_Details

**Comment by pilovali** [comment]
I thought it was always without the scheme.
If it's a feature and not a bug, this issue can be closed, I think?

**Comment by Vaalyn** [comment]
Not sure if I'd call it a feature but as far as I'm aware no client I know / have tested really cares if there is or isn't a schema in the URI so yeah I think this can be closed. The screenshot has probably been taken on an installation where not schema is set in the `Site Base URL` which is why it's not shown on the screenshot. If @SC2Mitch could update that screenshot that would be nice though.

**Comment by SC2Mitch** [comment]
> If @SC2Mitch could update that screenshot that would be nice though

Ill work on updating the screenshots tonight.

**Comment by SC2Mitch** [comment]
https://github.com/AzuraCast/azuracast.com/pull/60
All done, pull made.  @Vaalyn
