### ISSUE TITLE
Visual playing/pause bug at Profile page

### ISSUE THREAD

**Issue by pilovali** [AzuraCast/AzuraCast#3566]
**Using Docker installation method**

Yes

**AzuraCast version**

Rolling Release #c146166 (2020-12-13 13:59
**Host Operating System**

Ubuntu

**Describe the bug**

If you have multiple mountpoints available, and you press play on the first one, both will have a pause button.
If you press play on the 2nd mountpoint, only the 2nd player will have a pause button.

**To Reproduce**

- Create two mountpoints
- Go to the 'Profile' page
- Press play on either one of them and see.

**Expected behavior**

Only one should show the pause button, not all of them.

**Relevant Logs**

**Screenshots**

https://share.pilovali.nl/3i83mTcd1.gif

**Device(s):**
 - Device:  Laptop
 - OS:  Windows 10 20H1
 - Browser:  Edge
 - Version:  87.0.664.60

**Additional context**

**Comment by Vaalyn** [comment]
I'm unable to reproduce this problem on the demo installation as well as on my own test and dev installations.

I have tested this on Edge 87.0.664.60 on Windows 10 as well as on Firefox and Chrome both on W10 as well as on macOS Catalina.

Would you mind sharing the configuration of your mount points so I can try to re-create those and check again with that?

Also could you try reproducing this problem on the demo installation too?
I'd like to now if you are able to reproduce this on an installation that I'm unable to.

**Comment by pilovali** [comment]
Can't reproduce this on the demo installation as well (besides, demo is very very sluggish atm).
I think I found it:
Change the mountpoint URL to /radio instead of /radio.mp3. That should do the trick.

Can you try it?

**Comment by Vaalyn** [comment]
Thanks for the hint regarding the mountpoint URL. With that I can reproduce it and it seems like this is always happening when one mountpoint has a name that is the beginning of another mountpoint.

For example if I have 2 mounts `abc` and `abcdef` when I click play on `abc` it will automatically start `abcdef` too but not the other way.

![image](https://user-images.githubusercontent.com/13745863/102271883-3aa00100-3f20-11eb-8650-49fe45ba0196.png)
![image](https://user-images.githubusercontent.com/13745863/102271974-5a372980-3f20-11eb-8b5a-3253154914f9.png)

**Comment by SlvrEagle23** [comment]
@Vaalyn is correct in that this issue is caused entirely by our imprecise targeting of URL attributes for the play button, because of our automatically appended UNIX timestamp "cache-buster" suffixes for the radio URLs.

Given that those suffixes have generated several questions from users about why they exist and how to remove them, I would propose a simple solution for both issues: we remove the timestamp suffixes from the API response URLs and then append it directly within the radio player's internal controls for streams we know are radio streams. This will allow us to exacy target the URL listed for the play button (avoiding any conflicts between multiple stations having similar base paths), to produce cleaner URLs in API responses, and yet to achieve the same cache-busting functionality that we currently expect across all of our internal players.

The only drawback here will be that for users building their own player on top of our API data, the "cache-busting" aspect won't come baked in any more, and they'll need to make sure their application takes care of that. Many applications weren't updating the actual now-playing URL for the stream on-the-fly anyway, rendering this largely a moot point (not to mention, many player applications simply don't need this at all, it's only an issue with IE-class browsers).
