### ISSUE TITLE
 WebDJ is delayed

### ISSUE THREAD

**Issue by pde-system-integration** [AzuraCast/AzuraCast#3572]
Hi,
I use WebDj to play music. But it's been delayed about 15 seconds from when I click the "play" button. How can I minimize this delay?

**Comment by SlvrEagle23** [comment]
@pde-system-integration Usually this is a product of your DJ buffer setting on your station profile. Whatever it's set to will also be the delay between when a streamer connects and when a listener can first hear them (minus the delay in the streaming software itself), because it has to build up that much of a buffer in the event of a connection stability issue.

**Comment by pde-system-integration** [comment]
Can the delay time be adjusted down to about 5 seconds?

**Comment by SpeedyCharly** [comment]
Yes it can, but if you have remote dj's using Sam Broadcaster or other streaming software, they may have trouble connecting or maintaining a steady stream...  I've had to increase my buffer to 30 secs.  to accommodante some of my dj's streaming from remote regions with low upload bandwidth...
