### ISSUE TITLE
Metadata in wrong order on live broadcast

### ISSUE THREAD

**Issue by PB-SF** [AzuraCast/AzuraCast#3577]
Hi there.

I'm not sure if this is a Azuracast or Liquidsoap problem directly.

The normal order of metadata follows a principle:
`Artist - Title - (Album)`

If the playlist is played via Azuracast, the display on the profile page is correct. Example: `Robin Schulz - In Your Eyes`

When a modarator is connected, we use the `Album` metadata for the title of the program:
`Artist - Title - Show title`

Then the ad on the profile page is no longer in correct order. E.g:
`Show title - Artist - Title`

This means that internet-enabled radios that can automatically display the cover art of a song only work properly if the playlist is played via Azuracast. Unfortunately, this does not work with a live broadcast because the metadata order isnt correct.

Corresponding entries can be found in the Liquidsoap logs:

`New metadata chunk? - Lifehouse - First Time - Good morning Allgäu`

I hope this helps.

many Greetings

**Using Docker installation method**
No, Ansible method

**AzuraCast version**
Rolling Release #a12b655 (2020-12-19 5:07)

**Host Operating System**
Ubuntu 18.04

**Comment by Vaalyn** [comment]
This is caused be the [library](https://github.com/AzuraCast/nowplaying) that we use (and maintain) to fetch the metadata from IceCast / Shoutcast.

We are not anticipating the metadata to contain anything else than artist and title.

Since IceCast and Shoutcast are both handling this metadata as a single field we have to parse it from that field. Seeing as for example in Mixxx I can't even let it automatically send the album as part of the metadata I'm not sure how common this is (as far as I'm aware VirtualDJ also only sends artist and title).

**Comment by PB-SF** [comment]
Thank you for the fast answer.

I have now found out that it is not the case with all devices or apps that the covers are not displayed. Seems to vary depending on the manufacturer.

For our internal purposes, such as the display on our homepage, I will then use PHP scripts to adjust the metadata behind the Azuracast API.

Many Thanks
