### ISSUE TITLE
Autodj interrupts live stream

### ISSUE THREAD

**Issue by webma5ter23** [AzuraCast/AzuraCast#3585]
Docker installation
Ubuntu 20.04

I have this problem that has always happened to me on Azuracast again.

Listeners tell me that the live signal goes and comes back for 5 seconds, the radio loses listeners.

I have the latest version of Azuracast, the configuration is normal with liquidsoap activated. In itself, the music of the autodj is not very important to me because it is as a backup due to a power outage, but I don't want the live broadcast to have cuts.

Any help to configure correctly? or will it be broadcaster errors? use butt

Thanks

**Comment by Vaalyn** [comment]
Without seeing your `Liquidsoap Log` to check what is happening to the DJ connection I can only guess. I think this might be due to unstable connections from your DJs leading to the internal buffer of LS being exhausted until they automatically re-connect thus it using the autodj fallback.

See if increasing the `DJ/Streamer Buffer Time (Seconds)` in the `Station Profile` -> `AutoDJ` page helps.

**Comment by webma5ter23** [comment]
Ok thanks, I had 5 seconds and I put it in 15. In the log I did not see anything abnormal so I did not put it. I will test if it is solved with this change.

**Comment by adoboligh1** [comment]
same here, facing the same issue.

**Comment by SpeedyCharly** [comment]
My buffer already set at 30 sec and I am still getting that same issue.  At the dj end ( all using Sam Broadcaster)  there is no indication of problems, eg; disconnected encoder or error message - _Cannot send data fast enough, waiting for buffer to clear_ - that one might get from a slow or overloaded internet connection.  In the absence of these, I am assuming that the problem lies with LS/Autodj...

**Comment by arusi01** [comment]
2021/01/06 15:49:51 [lang:3] Authenticating DJ: 01test
2021/01/06 15:49:51 [lang:3] AzuraCast DJ Auth Response: true
2021/01/06 15:49:51 [decoder:3] Method "MAD" accepted "audio/mpeg".
2021/01/06 15:49:51 [lang:3] DJ Source connected! Last authenticated DJ: 01test - [("icy-name", "My Station name"), ("icy-genre", "Various"), ("icy-url", "http://www.test.com"), ("icy-irc", "#"), ("icy-icq", "NA"), ("icy-aim", "NA"), ("icy-pub", "0"), ("icy-br", "128"), ("Content-type", "audio/mpeg")]
2021/01/06 15:49:52 [lang:3] AzuraCast Live Connected Response: true
2021/01/06 15:49:52 [radio_input_streamer:3] Decoding...
2021/01/06 15:50:32 [radio_live_fallback:3] Switch to audio_to_stereo_7778 with transition.
2021/01/06 15:50:45 [radio_live_fallback:3] Switch to cross_7755 with forgetful transition.
2021/01/06 15:50:45 [dummy:3] Source failed (no more tracks) stopping output...
2021/01/06 15:51:23 [lang:3] AzuraCast Raw Response: annotate:title="zzzz",artist="zzzz",duration="105.27",song_id="2fb76eb55c0431aed9b57af81ca9b9fb",media_id="1253",liq_amplify="0.00dB",playlist_id="74":/var/azuracast/stations/radio/media/Daily/zzzz.mp3
2021/01/06 15:51:23 [decoder:3] Method "FFMPEG" accepted "/var/azuracast/stations/radio/media/Daily/zzzz.mp3".
2021/01/06 15:51:29 [radio_input_streamer:2] Feeding stopped: Mad.End_of_stream.
2021/01/06 15:51:29 [lang:3] DJ Source disconnected! Current live DJ: 01test
2021/01/06 15:51:29 [lang:3] AzuraCast Live Disconnected Response: true
