### ISSUE TITLE
Improvement of the playlists so that they also play properly

### ISSUE THREAD

**Issue by radio-schlauti** [AzuraCast/AzuraCast#3586]
.1 The remote URL playlist also works
.2 That the playlist also starts on time

The Libretime software demonstrates that it can work

**Comment by adoboligh1** [comment]
Same here my jingle worked only once.

**Comment by Vaalyn** [comment]
As this issue does not have any information about specific errors in it that we could debug I'm closing this.

GitHub issues are not there for general statements but for reporting specific errors, bugs and problems.
We supply users with 2 templates for creating GitHub issues that we expect you to use in order to describe those and to supply us with all the necessary information we need to start debugging/investigating.
Please make use of those templates instead of deleting the template and writing comments with no error messages, logs, problem descriptions, etc.
