### ISSUE TITLE
last week the update also deleted all other container that are not azuracast

### ISSUE THREAD

**Issue by kemecs** [AzuraCast/AzuraCast#3587]
last week the update deleted all other containers which are not azuracast!

**Using Docker installation method**
-- Yes. --

**AzuraCast version**
- Rolling Release #a253341 (2020-12-21 2:41) • Docker • PHP 7.4. 

Unbuntu 20TLS

update-self
update

.....
[OK] AzuraCast is now updated to the latest version!

azuracast_stations is up-to-date
azuracast_mariadb_1 is up-to-date
azuracast_redis_1 is up-to-date
Creating azuracast_web ... done
Creating azuracast_nginx_proxy_1 ... done
Creating azuracast_nginx_proxy_letsencrypt_1 ... done
Deleted Containers:
dc0871ac5eead173e2602c85048156d041edeb61d6c5fb13d0037e8b9899a8c5
c7bfddfd573d5f5b5c8082642d5841f46bbbc6a304424029e77425598b4915fa
d25d27dc806d2ed7ad934530164a84af05708cbc58ee986b6e316bd60c2be973
137796d5fc90eaed399b4ecb505d95cd828b7c269ab12e2a74a50e038245951f
5d50782507114ebfaa2a511b6a1b9ecc34e03c386e80a3849f16466831eac1e9
d8c15a52e137d097f5230a7026aadbcfbf85092f8de04ca9cb77edd16355a7d3

Deleted Networks:
bareos_default

Deleted Images:
untagged: azuracast/azuracast_web_v2@sha256:64c953e911d0aa72b96b148ec9352ee840e9f7b01c4415486cca385d63cdb9fc
deleted: sha256:16fd24a25d1f7771ddbd955ea0a01b3c03b35ca4b2a597eea04c8f3edb3df593
deleted: sha256:5d62ad1a456fef9812ed64a0695c79bd374d95f97a2d018c928ae1d75b7f0de0
deleted: sha256:6d033e42be378ff86777b27a36b4238631f9710549a67a75ab7e7d6ec9590ebf
deleted: sha256:2d684212bdccd6685d5e61e7236cd7aeb38eb12456f9df98cb7ccd5cac47261c
deleted: sha256:7aaae75a8be844e8bc68634c1164c94b45c1c84ad0a803171619a33253cd2b46
untagged: jrcs/letsencrypt-nginx-proxy-companion@sha256:872c30b28b7cee40c8920048f9a2fab42540dc45f8514cac9315ad20d952695b
deleted: sha256:ad41967a0157bfa4b3a999d6e524eb7fe89787dbc933615565c0ce9855bb0e93
deleted: sha256:0873f5a5fc1f95b793790e0efb69c317bb0be6b9b53c799df82e754ced32d5e0
deleted: sha256:b381c733612e7d87eb44e27733e08142bbde53821fa151816f3c99db16692b56
deleted: sha256:dd15b4c627502be636a9102b118385e4ada57a9225708643850a108e891ef966
deleted: sha256:729add30f2b2935de6837b7d8ef024306eb559d6f4d90ba073a24121fe13c772
deleted: sha256:b2044fee0d5919c073dafd3ad61236effe5b0dc63404c7a463bd4dc57004b398

Total reclaimed space: 126.9MB
Update complete!

**Comment by Vaalyn** [comment]
It is to be expected that the updater removes any unused containers, images and networks. Unused means any non-active ones (speaking those who don't have any running containers). This does not remove any persistent data like volumes though (just wanted to mention it for completeness sake).

The updater is using the `docker system prune -f` command to clean up after itself. See this Docker documentation page for reference: https://docs.docker.com/engine/reference/commandline/system_prune/

**Comment by kemecs** [comment]
but other non-azuracast containers were also removed by the updater

**Comment by SlvrEagle23** [comment]
@kemecs We're running the prune command because this is the only command we have available to remove non-running containers, images, etc. There is no corresponding `docker-compose prune` that only prunes images/containers related to AzuraCast, and this is a limitation of Docker that we have to work around on our end.

However, it should only ever be removing _stopped_ containers elsewhere in the system. It will never stop and remove containers that are already running elsewhere in the system.

**Comment by kemecs** [comment]
well that's pretty weird that way

I think at least one warning doesn't hurt

**Comment by SlvrEagle23** [comment]
@kemecs Valid point; I've added a prompt around the `system prune` command that you can answer `N` to in order to skip it if needed.

The default answer is `Y` to preserve compatibility with unattended update scripts that already exist.

**Comment by kemecs** [comment]
I tried

I don't think the question is clear yet

because the user does not notice that other temporarily stopped conatiners can be deleted

... I don't think it's a good idea to leave the cleaning to the upater

**Comment by SlvrEagle23** [comment]
@kemecs In a large number of cases, AzuraCast is the only thing running on a given VPS or server, and the users involved aren't familiar with Docker's internals enough to know to do the cleanup process on their own, which has led to a huge number of issues we've had with people reporting that their disk sizes are growing (due to older image versions) and that we aren't automatically cleaning that up.

Our decision to put the cleanup in the update script was motivated by the desire to ensure our users don't necessarily need to care about the "under the hood" setup of the Docker ecosystem, since just the idea of Docker (to some extent rightfully) intimidates folks who aren't well versed in tech.

**Comment by kemecs** [comment]
I understand you

i don't know which one is smaller bad


i was really terrified when i broke out my personal conatiners with the new updater

..I think the message is not eye-catching enough:

"Clean up all stopped Docker containers and images to save space? [Y / n]"

Do not take it the wrong way!

I just want to support you :)

I wish you a good job and happy holidays!

Regards Kemecs
Hungary
