### ISSUE TITLE
Storage Location

### ISSUE THREAD

**Issue by stardevelop** [AzuraCast/AzuraCast#3596]
I am using Dropbox Storage Location and it's already connected and see the content from Dropbox inside Music Files.
But when I switch from Local Storage to Drobox Storage and restart AutoDJ Service to get the change effective, I get this error:
League\Flysystem\FileNotFoundException at /var/azuracast/www/vendor/league/flysystem/src/Filesystem.php L389: File not found at path: 4.mp3

and station goes offline. When I switch back to Local it works fine.

**Comment by stardevelop** [comment]
I still have this problem:

League\Flysystem\FileNotFoundException at /var/azuracast/www/vendor/league/flysystem/src/Filesystem.php L389: File not found at path: 101.mp3

**Comment by Vaalyn** [comment]
I can see this error on my test installation when switching an existing station with media already playing to another storage location. My station however does not go offline from it as in Liquidsoap being stopped.

This seems to be caused by the `Upcoming Song Queue` still containing entries of songs that are from the previous `StorageLocation`. We should clear this queue when switching a storage location.
