### ISSUE TITLE
The "Now playing" info (song title and play time) doesn't update in time

### ISSUE THREAD

**Issue by eranwo** [AzuraCast/AzuraCast#3635]
**Using Docker installation method**
 Yes

**AzuraCast version**
Rolling Release #c424fe5 (2021-01-03 6:43)

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
When song is ending, the play time freezing for ~ 8 sec and then starts to display the next song time from ~ 00:08.

In some cases the play time just keeps running until it's end,  as if the previous song ended ahead of time and then skips to the next song at ~00:08.

The audio is playing well !
I've tried to to raise the php memory to 256M
and also tried with / without "WebSockets for Now Playing Updates"
but it not solved the issue.

**Comment by Vaalyn** [comment]
The `Now Playing` display on the station profile is not related to the `Use WebSockets for Now Playing Updates` setting.

This display updates itself from the internal station profile API at an interval of 15s which is why you are seeing this "inacurate" time display.

Seeing as this is not an issue on the public player we should take a look at this again some time in the future to improve this.

**Comment by eranwo** [comment]
@Vaalyn 
I'm getting the same issue via the API too (/api/nowplaying).

**Comment by asa767** [comment]
Up

**Comment by eranwo** [comment]
Up @Vaalyn
