### ISSUE TITLE
Show Custom Field in Player

### ISSUE THREAD

**Issue by dvoverlag** [AzuraCast/AzuraCast#3638]
Hello everyone,

I have created a custom field named "URL". This will store a link to the current title in our web store. 

I want to output the link in the player between "Title" and "Artist". In var/azuracast/www/frontend/vue/ I found the file RadioPlayer.vue. However, when I edit something here, this is not displayed in the player.

It would be great if someone could give me a tip on how to output a custom field in the player.

**Comment by Vaalyn** [comment]
Editing the frontend components directly is not supported and should not be done since they will be overwritten on each update. The vue components are also compiled to JS on install/update so editing them will not result in any changes without recompiling them.

I'd recommend you to use the `Custom JS for Public Pages` to add stuff to the radio player.

**Comment by gilfuser** [comment]
> Editing the frontend components directly is not supported and should not be done since they will be overwritten on each update. The vue components are also compiled to JS on install/update so editing them will not result in any changes without recompiling them.
> 
> I'd recommend you to use the `Custom JS for Public Pages` to add stuff to the radio player.

This will only change the player in the public page, not in the widget.
It would be really nice if the changes reflected in the widget player version.

**Comment by Vaalyn** [comment]
The custom js is being injected into the widgets too.
You might have to add additional code since the html / css classes might be different in the widget.
