### ISSUE TITLE
ssl not working on new installs

### ISSUE THREAD

**Issue by surihost** [AzuraCast/AzuraCast#364]
Hello,

I just installed it on a fresh centos7 with docker after that with debian 9 with docker,how ssl not working altough i select always use https

**Comment by surihost** [comment]
i see on the certificate error that it is issued by localhost to localhost.I have setup my hostname correctly but still

**Comment by amavarick** [comment]
Sounds like you're using a self-issued certificate instead of the Let's Encrypt certificate.
The instructions to setup a certificate are posted at:
https://github.com/AzuraCast/AzuraCast#setting-up-https-with-letsencrypt

These are the steps I took...
```
cd /opt/azuracast
docker-compose run --rm letsencrypt certonly --webroot -w /var/www/letsencrypt
docker-compose run --rm nginx letsencrypt_connect myazuracastdomain.tld
```

I use the commands above to create my let's encrypt certificate for my Azuracast installation.  You will need to change some things in the commands above specific to your installation...  There are the 2 changes below...

Replace:
/opt/azuracast
With:
the location you installed your docker instance of azuracast

Replace:
myazuracastdomain.tld
With:
The FQDN, Fully Qualified Domain Name you setup for your Azuracast instance.

Note that FQDN must be fully resolvable meaning DNS should properly route that name to your server.

**Comment by surihost** [comment]
Yes it works now:)

Thanks

**Comment by surihost** [comment]
what is the cronjob command to enter to make sure ssl is autorenewed after 90 days

**Comment by amavarick** [comment]
I think if you're asking this question, it may exceed your current technical capabilities.  Here's some good reading to learn on your own...  I'd recommend to run your cron to update let's encrypt every 30 or 60 days instead of waiting the full 90 days.  Both links below along with the original link provided will show you how to do this.

https://linuxconfig.org/bash-scripting-tutorial

https://help.ubuntu.com/community/CronHowto

High level steps:
1. Create a script that updates your certificates.  The command to update is in the same location as the instructions I provided above.
2.  Make the script executable
3.  Test the script by running it
4.  Create your cron job
5.  Test the cron job

**Comment by SlvrEagle23** [comment]
@surihost You have to create a cron task on the host itself, so this will depend heavily on what host you're using to run the Docker infrastructure.

In any case, the commands you'll want to schedule for routine renewal are:

```bash
cd /your/azuracast/directory/here
docker-compose run --rm letsencrypt renew --webroot -w /var/www/letsencrypt
docker-compose kill -s SIGHUP nginx
```

Since your original issue appears to be fixed, I'll close this ticket.
