### ISSUE TITLE
Service Cannot start nginx proxy error

### ISSUE THREAD

**Issue by radioutopia** [AzuraCast/AzuraCast#3649]
Hello
When i install with docker in a private vps, the service don´t start because apears this:

Creating azuracast_nginx_proxy_1 ... error

ERROR: for azuracast_nginx_proxy_1  Cannot start service nginx_proxy: driver failed programming external connectivity on endpoint azuracast_nginx_proxy_1 (14576dba40f81ead2688ce4ae631db17b133236c1ad4555f1ed5eb4969dd4030): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use

ERROR: for nginx_proxy  Cannot start service nginx_proxy: driver failed programm ing external connectivity on endpoint azuracast_nginx_proxy_1 (14576dba40f81ead2688ce4ae631db17b133236c1ad4555f1ed5eb4969dd4030): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.

What can i do?
Thanks

Using Docker installation method - Yes
Host Operating System - Ubuntu 20.04 LTS

**Comment by Vaalyn** [comment]
> Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use

You have something else already using port 80 on your server.

This is most likely an already running Apache 2.4 or NGINX web server (since you are using Ubuntu probably Apache 2.4). If you are not actively using this one just uninstall it from the server. If you are actually using it change the ports of AzuraCast is running on via `./docker.sh change-ports`
