### ISSUE TITLE
Edit a Azuracast file in docker ? 

### ISSUE THREAD

**Issue by psduk1** [AzuraCast/AzuraCast#3678]
Hi, 
I want to edit one of the Azuracast files 'src/Entity/Repository/StationStreamerRepository.php" but not sure how i can do this on a docker install.
Can anyone help or guide me please.

**Comment by Vaalyn** [comment]
We do not support editing file of AzuraCast installations directly since every change to the files will be overwritten on the next update.

You can theoretically use a volume mount to override single files in the container with your own versions but we don't recommend this and provide no tutorials for this (apart from special use cases such as replacing the default error.mp3, etc) since having parts of the code permanently overridden with a custom version can lead to issues in cases were we incorporate a change in such a file that is then not available due to it being overridden.

I'm guessing you want to incorporate the quick fix mentioned in #3588 regarding the DJ broadcasts.
This is something I'm going to look into today.

**Comment by psduk1** [comment]
Thanks for the reply, it was to try and address the quick fix mentioned in #3588 but if a fix is being worked on I will wait for that.
Thanks Again.

**Comment by Vaalyn** [comment]
I'm closing this issue now because I've submitted a fix for the problem in #3588
