### ISSUE TITLE
Content Security Policy directive

### ISSUE THREAD

**Issue by Sarrablo** [AzuraCast/AzuraCast#369]
Hi, i'm having a problem. I'm in a ubuntu 16.04 LTS server, in arubacloudvps. I have installed AzuraCast, an in both cases, it "deploy". But i cant use any functionality because this:

```Refused to load the script 'http://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js' because it violates the following Content Security Policy directive: "script-src https://maps.googleapis.com https://cdnjs.cloudflare.com 'self' 'unsafe-eval' 'nonce-i8NBCtbTJ+BMhiDVJ+pGsXRD'"```

I'm not using any domain, im asking directly to my vps IP. Do you know why can that happends?

Update: I have tried in two fresh Scaleway VPS, one tipe of installation in each, and I have the same error (but with different nonce)
Thanks.

**Comment by amavarick** [comment]
@SlvrEagle23

**Recommended changes to the CSP...**

**/login**
script-src
sha256-qsaTYeCGbgNfkYNDHFwJf3yQGeZH2dqJYX5lo8AF+f4=

**admin/api**
script-src
sha256-+EvrdbbwvLy+//l7CKzuuOOTLoRL3AU+ZPPjneGqgnc=

**/admin/branding**
script-src
sha256-KDm870gzbQtsfipYxDDsSCgwQZ3hZOPcOBmv48Wlj8k=


**There appear to be some other entries in the browser debugger that I don't remember seeing pre-patch**:

[Violation] Added non-passive event listener to a scroll-blocking '**touchstart**' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

[Violation] Added non-passive event listener to a scroll-blocking '**touchmove**' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

[Violation] Added non-passive event listener to a scroll-blocking '**wheel**' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

[Violation] 'DOMContentLoaded' handler took 196ms

[Violation] Forced reflow while executing JavaScript took 34ms

**Comment by SlvrEagle23** [comment]
@Sarrablo @amavarick Seems the issue is quite simple, really: I just needed to switch all the URIs from using the relative protocol of the browser (//cdnjs...) to absolute HTTPS (https://cdnjs...) to fall within the new CSP guidelines.

Sorry for the trouble there...update and it should be fixed.

**Comment by amavarick** [comment]
After updating, I have the following results:

**/admin/api**
Appears to be working now

**/login**
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src https://maps.googleapis.com https://cdnjs.cloudflare.com 'self' 'unsafe-eval' 'nonce-2DYngvMzLpVu1WDF9WyOLT01'". Either the 'unsafe-inline' keyword, a hash ('sha256-qsaTYeCGbgNfkYNDHFwJf3yQGeZH2dqJYX5lo8AF+f4='), or a nonce ('nonce-...') is required to enable inline execution.

**/admin/branding**
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src https://maps.googleapis.com https://cdnjs.cloudflare.com 'self' 'unsafe-eval' 'nonce-SUzQxmmhH5NbWfCBVXqfLct8'". Either the 'unsafe-inline' keyword, a hash ('sha256-KDm870gzbQtsfipYxDDsSCgwQZ3hZOPcOBmv48Wlj8k='), or a nonce ('nonce-...') is required to enable inline execution.

**/public/music**
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src https://maps.googleapis.com https://cdnjs.cloudflare.com 'self' 'unsafe-eval' 'nonce-8kIuwPcPAU9Mpu0DONuiExX5'". Either the 'unsafe-inline' keyword, a hash ('sha256-qsaTYeCGbgNfkYNDHFwJf3yQGeZH2dqJYX5lo8AF+f4='), or a nonce ('nonce-...') is required to enable inline execution.

There appear to be some other entries in the browser debugger that I don't remember seeing pre-patch:

[Violation] Added non-passive event listener to a scroll-blocking '**touchstart**' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

[Violation] Added non-passive event listener to a scroll-blocking '**touchmove**' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

[Violation] Added non-passive event listener to a scroll-blocking '**wheel**' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by SlvrEagle23** [comment]
@amavarick Remaining items should be fixed as of latest update. Not sure what's up with the other console warnings, as I'm not seeing them on any browser and they appear to be debug-based logging.

**Comment by amavarick** [comment]
Thank you for the changes.  I updated again and then tested and all of the CSP errors are gone.  :-)

I must have updated too soon so re-updated.  The CSP errors appear fully resolved.  Thank you.
```
Updating 4f76c56..6fa1719
Fast-forward
 app/modules/admin/views/branding/index.phtml | 2 +-
 app/templates/minimal.phtml                  | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)
```

**The only thing remaining are the following but I don't think they're CSP related**:
Do you think this should be a separate issue?

[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

**Comment by Sarrablo** [comment]
It works perfectly after the update! Lot's of thanks, have you donation option?

Lots of thanks

**Comment by SlvrEagle23** [comment]
@Sarrablo Happy to help. :)

Yes, I do have a donation option, via Ko-fi: https://ko-fi.com/A736ATQ

Donations are always greatly appreciated!

**Comment by marekdziem** [comment]
hey there - I've just recently fumbled across CSP in azuracast needing some modification to accommodate external javascript being loaded permissively - how does one do that with the docker config?

and all best for an astoundingly fruitful year fer  us all~!
