### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by shake85** [AzuraCast/AzuraCast#3692]
Hi, i'm trying to install Azuracast on a VPS. I did the installation with dockers and choosed the stable installation. While i was installing i get an error:

Error for azurcast_stations UnixHTTPConnection Pool (host='localhost', port-None): Read Time out. (read timeout=60)
Error: An HTTP request took too long to complete .....
 
and then it stoped. 

I don't know if this is a big fault or not. 

Is there something like a backend where i can log into ? I couldn't find something fimliar to this. 
Is there anywhere a startup guide? 

Would be great if someone could help 
thanks !

**Comment by Vaalyn** [comment]
In most cases I have seen this error is shown if the startup of the containers takes longer than the default 60s timeout due to "slow" hardware. You can check if all containers are running via `docker-compose ps` and you can increase the timeout via `COMPOSE_HTTP_TIMEOUT=300`, prepend the command you are running with this as follows `COMPOSE_HTTP_TIMEOUT=300 docker-compose up -d`.
