### ISSUE TITLE
Directly profiting from AzuraCast?

### ISSUE THREAD

**Issue by decretinate** [AzuraCast/AzuraCast#3697]
I understand AZ is completely open source which in some aspects is amazing but what's your opinion on people directly profiting from the project without:

1. A: Fixing issues / adding features
2. B: Donating to the project

Maybe start a name and shame section in the readme.md about it 👀

**Comment by SC2Mitch** [comment]
There's 'good' third party rehosters that actively contribute back to AZ and actually care about the FOSS ecosystem, but then there's the ones that simply don't care and send their users here to flood the support pages instead of attempting to resolve it themselves, they cause a high burden on the support team.

A name or shame while a 'ok' idea, it's not practical as it causes more tension in the community that simply isn't worth it. In the end, if people wanna support Silver then they can contribute back through the various methods (Sponsor, Kofe, Patreon, etc) but for the others that simply profit and not provide anything back, it's disappointing but we can't do anything about it, as that's the unfortunate 'joy' of open source software.

**Comment by decretinate** [comment]
Yeah, I totally agree with you there. It sucks but Open Source is the way of the future so expect the issue to get worse I guess.



[cid:image002.png@01D6F04F.7E9CDBA0]

Christian Clark
M: +61421044575

**Comment by Vaalyn** [comment]
Regard third parties AzuraCast hosters you can take a look at the pinned issue https://github.com/AzuraCast/AzuraCast/issues/3301

I'd recommend to have such discussions in the [GitHub Discussions](https://github.com/AzuraCast/AzuraCast/discussions) page of our repo. This allows us to keep our issue list dedicated to errors, bugs, etc. while providing a dedicated area for discussions.

I'll close this issue here now.
