### ISSUE TITLE
Backups under /var/azuracast/backup are not saved properly / inaccessable

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#3704]
**Using Docker installation method**
Yes

**AzuraCast version**
 Rolling Release #fe8beda (2021-01-21 20:12) •

**Host Operating System**
Ubuntu 20.04 

**Describe the bug**
I backup directly to the default folder which is `/var/azuracast/backup`, when I go into that folder it does not appear in there, the folder is empty. The backup runs daily and I'm unable to locate the said backup. 
**To Reproduce**
Run a backup
Go to `/var/azuracast/backup (/var/lib/docker/volumes/azuracast_backups) ` and check the data folder

**Expected behavior**
The backup to be ran properly and go to the /var/azuracast/backup location, it should not be hidden within a hashed container. 

**Relevant Logs**
N/A
**Screenshots**
https://puu.sh/H9u8R/92c24495b4.png

**Device(s):**
Windows 10, Edge in the latest version, desktop. 
**Additional context**

**Comment by SlvrEagle23** [comment]
@SC2Mitch If you updated within a specific window, our migrations mistakenly created a storage location at `/var/azuracast/backup` instead of `/var/azuracast/backups`, which is the actual directory that's mapped externally and is used for things like restoration.

You may want to fix that for your specific installation, and it should resolve the issues.

**Comment by SC2Mitch** [comment]
Ah I see, a fix was deployed for our installation and it works perfectly. 

Thanks for the help!
