### ISSUE TITLE
s3 amazon

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#3706]
I have doubts on how to configure the amazon s3, I searched and did not find a tutorial on.,

**Comment by SC2Mitch** [comment]
https://www.azuracast.com/extending/s3-configuration.html#amazon-simple-storage-service-s3

Here is our basic tutorial on setting up Amazon S3.

**Comment by Marcioghiraldelli** [comment]
thanks for showing.
I couldn't find the dropbox.
I think the dropbox price is much better.
Does anyone have any solution for dropbox?
THAT DOES NOT require a lot of space on the server.

**Comment by SC2Mitch** [comment]
Correct there is no dropbox in that page, I may consider adding it this week.

**Comment by Marcioghiraldelli** [comment]
It would be nice to be able to insert dropbox as well.
Because value and space are much more important.

**Comment by Catskill909** [comment]
I'm having trouble myself with s3 configuration.
The 2 fields I'm not sure how to fill out are
- Path/Suffix
- Endpoint
I see configuring Endpoints in s3 docs. Is this what I should pursue?
any help to get me on track appreciated

**Comment by Catskill909** [comment]
So I was finally able to work this out. There is a post that shows close to a working S3 mount configuration but the top folder still uses the default example, making it confusing. The "Endpoint" is just the s3 url to your bucket you want mounted but without the Bucket name in the URL
I had tried using a slash in the Path/Suffix and that was resulting in an error. It turns out that putting nothing there did the trick!

![Screen Shot 2021-01-30 at 4 16 12 PM](https://user-images.githubusercontent.com/36337311/106368431-608a3500-6317-11eb-8933-136337e1d9e6.png)
