### ISSUE TITLE
Its taking over both IPs on my server

### ISSUE THREAD

**Issue by UncleChip** [AzuraCast/AzuraCast#371]
Aafter I install it takes over both IPs on my server. I need one of them for my website. How can I fix this?
I used docker to install and pointed it to a dedicated URL but it still seems to take over both IPs.

Dean

**Comment by SlvrEagle23** [comment]
@UncleChip By default, Docker Compose forwards all ports from the host, since that's the only way to make an easily redistributable file for all possible hosting situations.

It's easy to modify the Compose file and create a version specific for your needs. Follow these steps:

- Copy the existing [docker-compose.yml](https://github.com/AzuraCast/AzuraCast/blob/master/docker-compose.yml) file somewhere outside the main AzuraCast folder, so updates don't overwrite it.
- Update the file so that any `volumes` subsections that start with `.:` (normally the same directory as the compose file) point to the new relative path of the base, i.e. if AzuraCast is one folder deep from the compose file, those lines would be `./azuracast:`
- Update any `ports` subsections that you don't want to bind to all IPs by adding `your-desired-ip:` before them, i.e. `"80:80"` becomes `"your-desired-ip:80:80"`. More about how to customize this section is available [on the Docker Compose documentation](https://docs.docker.com/compose/compose-file/compose-file-v2/#ports).
- Run `docker-compose down` in the AzuraCast directory, then `docker-compose up -d` in the directory where the new Docker Compose file is.

I know it's a little more complicated than it probably should be, but unfortunately that's a limitation of our current setup. Hopefully this helps!

**Comment by UncleChip** [comment]
So I did what you said but now I cannot see the website that is on that URL. Does this need to be on its own IP?

**Comment by UncleChip** [comment]
and when i add new files to the media page its not updating. I get this error...
Doctrine\DBAL\Exception\DriverException thrown with message "An exception occurred while executing 'INSERT INTO station_media (station_id, song_id, title, artist, album, lyrics, isrc, length, length_text, path, mtime, fade_overlap, fade_in, fade_out, cue_in, cue_out, unique_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [2, "bf27ae7f6a18c16b60b8058b82df53c5", "30 12hr", "2005 12", "Dec 2005", null, null, 42991, "716:31", "2005\/2005 12-30 12hr.mp3", 1515412676, null, null, null, null, null, "209e4ca93a56e7e5fb324353"]:

SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'length' at row 1"

Stacktrace:
#39 Doctrine\DBAL\Exception\DriverException in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:121
#38 Doctrine\DBAL\Driver\AbstractMySQLDriver:convertException in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:176
#37 Doctrine\DBAL\DBALException:wrapException in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:150
#36 Doctrine\DBAL\DBALException:driverExceptionDuringQuery in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:177
#35 Doctrine\DBAL\Driver\PDOException in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107
#34 PDOException in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105
#33 PDOStatement:execute in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105
#32 Doctrine\DBAL\Driver\PDOStatement:execute in /var/azuracast/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:168
#31 Doctrine\DBAL\Statement:execute in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:281
#30 Doctrine\ORM\Persisters\Entity\BasicEntityPersister:executeInserts in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1014
#29 Doctrine\ORM\UnitOfWork:executeInserts in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:378
#28 Doctrine\ORM\UnitOfWork:commit in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:356
#27 Doctrine\ORM\EntityManager:flush in /var/azuracast/www/app/src/AzuraCast/Sync/Media.php:114
#26 AzuraCast\Sync\Media:importMusic in /var/azuracast/www/app/src/AzuraCast/Sync/Media.php:15
#25 AzuraCast\Sync\Media:run in /var/azuracast/www/app/src/AzuraCast/Sync.php:105
#24 AzuraCast\Sync:AzuraCast\{closure} in /var/azuracast/www/app/src/App/Debug.php:174
#23 App\Debug:runTimer in /var/azuracast/www/app/src/AzuraCast/Sync.php:106
#22 AzuraCast\Sync:syncMedium in /var/azuracast/www/app/modules/admin/controllers/IndexController.php:41
#21 Controller\Admin\IndexController:syncAction in /var/azuracast/www/app/src/App/Mvc/Controller.php:100
#20 App\Mvc\Controller:dispatch in /var/azuracast/www/app/src/App/Mvc/Resolver.php:42
#19 App\Mvc\Resolver:App\Mvc\{closure} in /var/azuracast/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:41
#18 call_user_func in /var/azuracast/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:41
#17 Slim\Handlers\Strategies\RequestResponse:__invoke in /var/azuracast/www/vendor/slim/slim/Slim/Route.php:340
#16 Slim\Route:__invoke in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:117
#15 Slim\Route:callMiddlewareStack in /var/azuracast/www/vendor/slim/slim/Slim/Route.php:316
#14 Slim\Route:run in /var/azuracast/www/vendor/slim/slim/Slim/App.php:479
#13 Slim\App:__invoke in /var/azuracast/www/app/bootstrap/services.php:368
#12 Closure:{closure} in /var/azuracast/www/vendor/slim/slim/Slim/DeferredCallable.php:43
#11 call_user_func_array in /var/azuracast/www/vendor/slim/slim/Slim/DeferredCallable.php:43
#10 Slim\DeferredCallable:__invoke in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:70
#9 call_user_func in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:70
#8 Slim\App:Slim\{closure} in /var/azuracast/www/app/bootstrap/services.php:424
#7 Closure:{closure} in /var/azuracast/www/vendor/slim/slim/Slim/DeferredCallable.php:43
#6 call_user_func_array in /var/azuracast/www/vendor/slim/slim/Slim/DeferredCallable.php:43
#5 Slim\DeferredCallable:__invoke in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:70
#4 call_user_func in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:70
#3 Slim\App:Slim\{closure} in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:117
#2 Slim\App:callMiddlewareStack in /var/azuracast/www/vendor/slim/slim/Slim/App.php:370
#1 Slim\App:process in /var/azuracast/www/vendor/slim/slim/Slim/App.php:295
#0 Slim\App:run in /var/azuracast/www/web/index.php:9

i have rermoved the file(s) but still get errors

**Comment by UncleChip** [comment]
ok i got around the error by adding the folders 1 at a time

**Comment by SlvrEagle23** [comment]
@UncleChip Please keep Github issues to one subject matter, and create another issue if it's unrelated to the first one. In this case, it appears that the problem is that the music file you're uploading is 12 hours long. Due to the size limit on that field, songs are limited to 9.1 hours in length.

In reference to your original issue, however, yes, AzuraCast strongly prefers to be on its own IP address, as it occupies a number of ports besides just 80 and 443. You can also configure proxying to allow it to exist on the same IP as other web sites.
