### ISSUE TITLE
Unknown column 'password'

### ISSUE THREAD

**Issue by akosijomel** [AzuraCast/AzuraCast#373]
failed: [localhost] (item=DROP DATABASE test) => {"changed": false, "cmd": ["mysql", "--defaults-extra-file=/root/.my.cnf", "-ne", "DROP DATABASE test"], "delta": "0:00:00.008182", "end": "2018-01-12 09:55:42.675365", "item": "DROP DATABASE test", "msg": "non-zero return code", "rc": 1, "start": "2018-01-12 09:55:42.667183", "stderr": "ERROR 1008 (HY000) at line 1: Can't drop database 'test'; database doesn't exist", "stderr_lines": ["ERROR 1008 (HY000) at line 1: Can't drop database 'test'; database doesn't exist"], "stdout": "", "stdout_lines": []}
ok: [localhost] => (item=DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%')
...ignoring

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OperationalError: (1054, "Unknown column 'password' in 'field list'")
fatal: [localhost]: FAILED! => {"changed": false, "msg": "(1054, \"Unknown column 'password' in 'field list'\")"}

I'm experiencing this error. Any thoughts or suggestion?

**Comment by SlvrEagle23** [comment]
@akosijomel It appears you're installing AzuraCast using the traditional installation model. This issue may be caused by an existing configuration of MySQL/MariaDB existing on the server before AzuraCast was installed. This may not even have been set up yet (i.e. just packaged as part of a "LAMP" stack image from your host) but it can still interfere with the AzuraCast installation. All servers planning to use the traditional installer should ensure the system is clean, barebones Ubuntu 16.04 server before installing the software.

Furthermore, as the documentation suggests, issues like this one are avoided entirely by using the Docker-based configuration, which will increasingly become the only fully supported method of installing the software due to its significant ease of installation and compatibility with other software being installed on the same server. If at all possible, it's highly recommended to switch to that method of operation for any new stations.
