### ISSUE TITLE
Can´t change the order of mounting points / remote relays in embed player

### ISSUE THREAD

**Issue by AndreBlin** [AzuraCast/AzuraCast#3732]
Hi there,

I want to change the order of the streams in the embed player. I have 2 streams a mount point and a remote relay. I don't get the remote relay in the first place. No matter what I choose, the standard is always shown at the top. Is there a way to change this? It's important because the remote relay hoster charges the license fees for the music. Maybe I can hide the mount point and only show the remote relay.

Many Thanks!
System: Powered by AzuraCast • v0.11.2 Stable • Docker • PHP 7.4 

![change_the_order_in_embed_player](https://user-images.githubusercontent.com/78139850/106111571-7697ca00-614c-11eb-892f-3b1049ca6514.png)

**Comment by YosefAdPro** [comment]
Have you tried it?

![image](https://user-images.githubusercontent.com/11810187/106148989-67cc0a00-6182-11eb-83ff-e8da379b470f.png)

**Comment by Vaalyn** [comment]
In addition to what @YosefAdPro wrote you can also hide specific mounts with the following option:

![image](https://user-images.githubusercontent.com/13745863/106158911-88955f00-6184-11eb-91ae-8ea35d05a257.png)

**Comment by AndreBlin** [comment]
> 
> 
> In addition to what @YosefAdPro wrote you can also hide specific mounts with the following option:
> 
> ![image](https://user-images.githubusercontent.com/13745863/106158911-88955f00-6184-11eb-91ae-8ea35d05a257.png)

Thanks for the suggestion. Unfortunately, I've already tried all of this. A mounting point is always marked as standard. This changes automatically when I try it. Hiding on the public pages does not work with the last activated mounting point either.

**Comment by AndreBlin** [comment]
> 
> 
> @AndreBlin You are right, it seems like it's currently not possible to completely hide all AzuraCast mount points and only show remote relays.
> 
> I've created a [feature request](https://features.azuracast.com/suggestions/155962/make-it-possible-to-hide-all-mount-points-and-only-show-remote-relays-on-public-) for it (currently not public until approved).

Is there any chance to "edit" the code of the public player? Maybe changing (my picture) the position as an temporary fix.

Best regards

**Comment by Vaalyn** [comment]
Not that I know of.

It is not possible to edit the public player directly since it is a compiled vue.js component.

It might be possible to use the Custom JS for Public Pages to write some JS to automatically automatically select the relay when the page is opened. But I have not tested this and I don't have any code for that.

**Comment by AndreBlin** [comment]
Many thanks for your response. I fixed the problem with some gaffa tape. My solution:

1. Setup of new mount point

2. Name "choose"

3. choose default mount point

4. select stream from relay host

Not a perfect solution, but a workable one.

Best regards

![Einhängepunkt bearbeiten](https://user-images.githubusercontent.com/78139850/106421371-dea42400-645c-11eb-9f34-34b31a12db22.png)
![Netlabel org - Radioshow](https://user-images.githubusercontent.com/78139850/106421375-df3cba80-645c-11eb-95ce-dc1057c3495b.png)
![Netlabel org](https://user-images.githubusercontent.com/78139850/106421376-dfd55100-645c-11eb-9382-92acd7e13930.png)

**Comment by SlvrEagle23** [comment]
@AndreBlin I've been following this issue, and it was bugging me that you couldn't actually have _no_ local mount points and only list remote relays on our public API/player pages, since I consider that to be a problem, especially in situations like yours where you're wanting to use relays to handle large amounts of incoming traffic.

I've updated both our mount handling and our player page to allow for no local mount points to be listed publicly, and to list your first remote stream as the visible one in the stream selector even if there aren't any local mount points.

The secondary issue, of being able to order mount points and remotes as they're displayed, is indeed a separate feature request that you should submit via https://features.azuracast.com/ .
