### ISSUE TITLE
Share a media folder between 2 or more radios

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#375]
In order to save expensive strorage space, it would be great to have to possibilty to share a media folder to different radios, instead of duplicating them for each one of them. I have to say Azuracast is a great tool !

**Comment by amavarick** [comment]
This would be a nice feature.

**Comment by SlvrEagle23** [comment]
@griffon56 @amavarick While this isn't currently possible via the web interface, it should be entirely possible to create a symlink inside the media directories that accomplishes the same purpose.

On the traditional install, this can just be done via the bare filesystem; on Docker installs, you can access the shared stations volume by typing `docker-compose run --rm cli`, where inside the container the station media directories will be located at `/var/azuracast/stations`.

**Comment by griffon56** [comment]
many thanks @SlvrEagle23 for the docker file access command tool !

**Comment by SlvrEagle23** [comment]
Closing this issue, as there are two solutions already in place:

- If you're creating a new station, you can clone an existing station and indicate, on the clone form, that you want to share the media directory with another station. That will point both stations at the same media directory, then any updates to media in that folder will cascade out to both stations. You can do this with any number of stations you want.

- If you only want to share a subdirectory between two stations, you can do this in the command line by creating a symlink. The stations base directory is `/var/azuracast/stations`; if you're running Docker, you can get to it by running `docker-compose run --rm cli` first, then navigating to that folder inside the container. As a friendly reminder, the symlink syntax is `ln -s /path/to/file /path/to/symlink`.

I could implement a web-based version of the second item, but it would require some interesting permission checks and would only be enabled for users who are administrators of both of the shared stations. Since it's a somewhat advanced and/or risky operation in the first place, I don't mind it being the kind of thing that requires terminal access.
