### ISSUE TITLE
Album shown in song history / song requests

### ISSUE THREAD

**Issue by kieranlittle667** [AzuraCast/AzuraCast#3759]
**Using Docker installation method**
Yes

**AzuraCast version**
 (2021-02-03 4:17) • Docker • PHP 7.4

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
When using song history / song requests on public pages the album tab is exposed. There is no option to exclude this from showing.

**To Reproduce**
Provide an album for uploaded media 
Enable song history / song requests
Go to public page and click on either
See that album is listed in history and in the table for song requests.

**Expected behavior**
I wouldn't have expected to see this because the majority of people that will be requesting a song will most likely not care what album the track came from. I would have at least expected to see a setting for this somewhere in the interface.

**Comment by SC2Mitch** [comment]
Please use the full format provided, this is not helpful for us to diagnose or debug.

**Comment by kieranlittle667** [comment]
Hi,
I’m confused as to what extra info you could need. There’s nothing in the logs and if you want to see it in action either enable recently played songs and / or song requests on the public pages with media that has an album in the metadata or go to kieranl.me where you can see it. Apologies if I’ve put this in the wrong place.
Thanks for your help

**Comment by SlvrEagle23** [comment]
@kieranlittle667 It appears you left in a small formatting note from our template that caused your responses to be commented out. I've updated the original issue to remove that, which properly shows the full text of the issue now. We can investigate with the information you provided. Thank you!

**Comment by kieranlittle667** [comment]
Apologies, not sure what  that was, it all looked fine before I submitted.
Thank you for looking into it, I appreciate it

**Comment by SlvrEagle23** [comment]
@kieranlittle667 After looking at this issue further, it appears you would like the ability to hide the "Album" field from public view; we actually just added it rather recently due to popular request from multiple users who wanted it added to the system to improve the total amount of metadata they could show for each track.

If you want, you could submit a feature request to make this a configurable on/off setting at the per-station level. New feature requests are handled through our FeatureUpvote site here: https://features.azuracast.com/
