### ISSUE TITLE
Web server randomly fails and returns the 500 error

### ISSUE THREAD

**Issue by TheVingard** [AzuraCast/AzuraCast#376]
About after 12 hours of running fine, the web server dies and outputs a 500 error until it is restarted. The radio stream still continues to work. This consistently occurs every 12 hours or so.

Any idea how I can fix this?

**Comment by SlvrEagle23** [comment]
@TheVingard More often than not, we see this kind of error when someone's running AzuraCast on an economy server (i.e. the lower tiers of cloud hosting providers) and hasn't set up swap memory, which often isn't set up by default. When any component exceeds the memory for the server, Linux just OOM kills it, causing unpredictable problems like that.

The handy little snippet of code I use to set up a swap space on VPSes is here:

```bash
fallocate -l 2G /swapfile
chmod 600 /swapfile
mkswap /swapfile
swapon /swapfile
echo "/swapfile   none    swap    sw    0   0" >> /etc/fstab
```

Beyond that, the only way I can diagnose the issue is if I have more information on the context of the error being returned. If you're visiting the web site, this should be shown in the browser window, or on Docker containers, you can see the rolling error log for the application by running `docker-compose logs -f web`.

**Comment by TheVingard** [comment]
Thanks for the help here.
