### ISSUE TITLE
 Song Playback Timeline Report

### ISSUE THREAD

**Issue by olivic9** [AzuraCast/AzuraCast#3767]
**Using Docker installation method**

Yes

**AzuraCast version**

AzuraCast • v0.10.3, #9811fbb (2020-06-22 4:38) • Docker • PHP 7.4

**Host Operating System**

Ubuntu 18.4.4

**Describe the bug**

 It is not showing the history of the songs played in the channels

**To Reproduce**

1. Manage a station
2. Left Menu 
3. Reports 
4. Song Playback Timelime Report

**Expected behavior**

This view should display the songs report

**Relevant Logs**

**Screenshots**
![image](https://user-images.githubusercontent.com/25878666/106912122-7c0f8a00-66e1-11eb-89ad-3a3b9da9a488.png)

**Device(s):**
 - Device: Desktop  
 - OS: WIndows 10 
 - Browser: Chrome 
 - Version: 87.0.4280.141 

**Additional context**

**Comment by Vaalyn** [comment]
Hey, I've noticed you are using version  `v0.10.3 #9811fbb` from 2020-06-22 which is now over half a year old.
Please update to at least the current stable version and check if you still experience this problem.

We are not providing support for out of date versions since we do not backport updates to old versions.

**Comment by Vaalyn** [comment]
Since there have been no further replies here and we don't have any further information that we can use to debug I'm closing this issue.
