### ISSUE TITLE
The new version keeps locking the home screen

### ISSUE THREAD

**Issue by alencarwell** [AzuraCast/AzuraCast#3799]
**Using Docker installation method**
YES

**AzuraCast version**
Desenvolvido por AzuraCast • v0.12 Stable • Docker • PHP 7.4

**Host Operating System**
Ubuntu 20.04

**Describe the bug**
Is there any way to disable the update when we are on the main page listing all the radios?

This causes a major inconvenience and sometimes he tries to update and keeps updating and does not return to the radio list page.

**Comment by SC2Mitch** [comment]
Can you elaberate a bit more on the issue your having? Do you mean the update prompt?

**Comment by alencarwell** [comment]
I'm talking about the main screen, the screen that shows all the stations.

Before she was static, now she updates herself and that sometimes causes her to crash and just keep processing.

If you are monitoring any broadcaster, then the page will be updated and you will lose the broadcaster you were monitoring, in short, it bothered you a lot.

Can you disable this?

**Comment by Vaalyn** [comment]
Could you provide us with the error/s from your browsers javascript console when this crash happens?

I haven't seen this happening on my test installation so I'm not sure what exactly is causing this problem.

One other issue I have identified with the new dashboard table is that when you are on page 2/2 (or any other greater 1) and you switch to show "ALL" then it fails because it sends the current page still as that number. But this is probably something different than what you are experiencing but I just found this bug while trying to reproduce your issue.

**Comment by alencarwell** [comment]
So, it is difficult for me to show you this bug because it happens intermittently.

If you could just deactivate this update of the station list, it would be better, as it was in the previous version.

**Comment by Vaalyn** [comment]
Sure we could just deactivate it but that will not help us find the root cause of this issue and we want to fix issues instead of circumventing them by just removing the feature. Since you are currently the only person who has reported this happening and I haven't yet been able to reproduce it we need your help to figure this out.

When you encounter this happening, please do not reload the page or go to another page, right-click on the page, select "inspect" and switch to the "Console" tab (I'm assuming you are using Chrome, but FF or others are not much different).
Then you have the JavaScript console opened, there you should see any error messages that happened. Copy the error/s and paste them here.

**Comment by SlvrEagle23** [comment]
I'm aware of what may be causing this problem...as a workaround for an issue we had with the new dynamic tables not being able to live-reload contents without triggering a full refresh, I was periodically triggering a full refresh on that table; for most users, you'd barely notice it as a split second of load time, but if you lost connection, your session expired, etc. then it would reload and never repopulate the data, instead of just leaving it where the connection last successfully left off.

I've simplified the table in use on the dashboard to ensure it works as expected from previous versions (while still using our new API calls).
