### ISSUE TITLE
Advanced Custom Stream URL doesn't run.

### ISSUE THREAD

**Issue by Medyatr** [AzuraCast/AzuraCast#3812]
**Using Docker installation method**

**AzuraCast version**

**Host Operating System**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by Vaalyn** [comment]
First of all, please don't ignore the issue template. When you enquire our help with an issue please take a few minutes to actually fill out our template.

This setting is not for creating a custom URL. It can be used for example when you have a reverse proxy somewhere which proxies the stream to that URL and you want AzuraCast to show that URL instead of the "regular" URL in the AzuraCast interface.
