### ISSUE TITLE
Switch back to Icecast 2.4.x main branch once proxying is implemented

### ISSUE THREAD

**Issue by FAaBbiii** [AzuraCast/AzuraCast#383]
Hi, it is possible to update the icecast version to the current version 2.4.3?

Server: Icecast 2.4.0-kh7
Icecast Release 2.4.3

I need the "Global Headers" feature:
https://icecast.org/docs/icecast-2.4.1/config-file.html#global-headers

Thank You!

**Comment by SlvrEagle23** [comment]
@FAaBbiii The reason we're on the KH builds of Icecast is because they support the necessary customization for the "X-Forwarded-For" header that allows services like StreamLicensing to proxy your radio signal through their own service and provide licensing/royalties for webcasters.

Until and unless the main builds of Icecast add support for this feature, we have a number of users who depend on the KH branch's featureset (and moreover, its performance benefits).

**Comment by SlvrEagle23** [comment]
Update: I created a Github issue regarding the X-Forwarded-For header support in Icecast, and it appears there's already a long-standing issue to implement it, and it's expected to be included in an upcoming build of Icecast. You can follow the progress of this here:
https://gitlab.xiph.org/xiph/icecast-server/issues/1959

I will strongly reconsider moving back to the main Icecast branch once this is implemented. I have had an outstanding issue for quite some time with the KH branch that has caused significant frustration amongst the AzuraCast user base, and if Icecast beats him to the punch, that's ample incentive for us to switch back.

**Comment by SlvrEagle23** [comment]
I'm updating the status of this ticket to basically be "wontfix", as I've re-evaluated whether it's in our listeners' best interests to be using the main Icecast branch overall versus the more performant, more feature-filled KH branch.

One of the big influencers in that decision is how responsive Karl Heyes (the KH maintainer) is with his public GitHub repository, versus how the Xiph organization handles public requests. There is definitely a lack of transparency and ease-of-interaction with the latter.

I may revisit this issue later in the future, but for now, I don't see a major impetus to switch back.
