### ISSUE TITLE
Saving playlist assignment when filtering by playlist removes the media from all playlists

### ISSUE THREAD

**Issue by Ferz0id** [AzuraCast/AzuraCast#3841]
**Using Docker installation method**
 Yes 

**AzuraCast version**
v0.12 Stable

**Describe the bug**
![1](https://user-images.githubusercontent.com/44975254/108975021-19cdf780-7697-11eb-9881-183de6d5e3d3.JPG)
In the beginning I have seven playlists for a week, then I need to clear one of them - **playlist#3** for example.

![2](https://user-images.githubusercontent.com/44975254/108975378-7c26f800-7697-11eb-91bd-a0c9378e28da.JPG)
Then I do "Clear" operation and it clears all playlists, not just one of them. Same items from playlist#3 will be removed from all others.
![3](https://user-images.githubusercontent.com/44975254/108975562-ad072d00-7697-11eb-9740-4f519048eb6e.JPG)
Uncheck the check box on playlist#3 and cick "Save" button does the same

There is only one way: clear all of them and re-fill it, but in the future, it will be more and more annoying than now. Please help with that.
![4](https://user-images.githubusercontent.com/44975254/108975880-02433e80-7698-11eb-9671-c5420c61707c.png)

**Comment by Vaalyn** [comment]
The `Clear` button clears it from all assigned playlists hence the name "clear", what you need to do is select which playlists the selected songs should be in and then hit `Save`.

For example with you setup you select the songs that are assigned to playlist `03` then open the playlists dropdown, remove the check from the `03` playlist and then hit `Save`.

**Comment by Vaalyn** [comment]
The `playlist:` filter on the media files list causes an issue that leads to users clearing the files from all other playlists when they want to remove media in the filtered list from the playlists that they are currently looking at.

When the list is filtered by a playlist only this playlist is checked in the playlists dropdown which means if you do not realize this and you remove the check from the filtered playlist and hit save and it will remove the media from all playlists since they are not checked there.

For better understanding @Ferz0id has supplied a video showing this behaviour: https://www.youtube.com/watch?v=uNDAWaZvvDE

**Comment by SlvrEagle23** [comment]
This should be fixed in the latest Rolling Release, where viewing the contents of a single playlist will still show other playlists associated with the selected media.
