### ISSUE TITLE
Release #4cd090d  play button

### ISSUE THREAD

**Issue by radiobellissima** [AzuraCast/AzuraCast#3843]
![Test](https://user-images.githubusercontent.com/57127248/109073816-3568ea80-76f7-11eb-9312-74b69b16119e.png)
![Test](https://user-images.githubusercontent.com/57127248/109073939-592c3080-76f7-11eb-937f-decd19897974.png)

Hi I upgraded to this version, I found that the play button on the home page no longer works. Pressing the play on the 3rd and 5th stations presses on all of them and nothing is played. Furthermore, there is no longer the possibility to sort the stations with the buttons above.

Thanks
Marcello

**Comment by Vaalyn** [comment]
The play button issue seems quite similar to https://github.com/AzuraCast/AzuraCast/issues/3566

The gist of that is that this is happening when you have multiple entries in a list with a name starting with the same string. So for example `Station 01` and `Station 02` both start with `Station` so due to this bug both are shown as playing.

The sorting seems to be a regression due to the recent simplification of the dashboard table. I haven't yet looked at the new dashboard vue component though.

**Comment by SlvrEagle23** [comment]
I think these two are indeed the same issue; see the previous comment's tagged issue for updates.
