### ISSUE TITLE
with the ALL option, the last folder are not displayed

### ISSUE THREAD

**Issue by Psychoses** [AzuraCast/AzuraCast#385]
Hi,

**bug** : with the ALL option, the last folder are not displayed

> ![missfolder1](https://user-images.githubusercontent.com/11153449/35211571-59db4e1e-ff57-11e7-9bc2-15956602c9ee.jpg)
> ![missfolder2](https://user-images.githubusercontent.com/11153449/35211573-5c214aac-ff57-11e7-8675-b5457b4ef8b3.jpg)

**how reproduce**
go to a folder with subfolder
select the "all" gui option
the last folder is missing

**additional question**
There is a way for adding songs on playlist with command line ?
There is a way for get songs number with command line ?

> ![song number](https://user-images.githubusercontent.com/11153449/35211584-61356f28-ff57-11e7-823f-069d71d7e910.jpg)

**Comment by SlvrEagle23** [comment]
@Psychoses Good catch! Seems this one has existed in the system basically since it was built, and was missed until just now. The latest update should fix it.

As for your secondary questions, currently there are no CLI tools for retrieving or uploading song data. If you want, you're welcome to submit that as a separate issue for possible future enhancement.

**Comment by Psychoses** [comment]
Thx u a lot !
