### ISSUE TITLE
Artworks are not stored in the metadata of the songs

### ISSUE THREAD

**Issue by InstabilSpielt** [AzuraCast/AzuraCast#3862]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.12.1 Stable

**Host Operating System**
Debian 10

**Describe the bug**
I have the problem for a while now that the artwork is no longer saved in the metadata of the song, this was not the case in version v0.10.4 (stable) and before, is this wanted?

**Device(s):**

- Device: Desktop
- OS: Windows
- Browser: Chrome
- Version: 89

**Additional context**
In AzuraCast, the artwork is displayed and saved correctly, but when you try to download the song, for example, you notice that the artwork is not saved in the metadata of the song.

**Comment by SlvrEagle23** [comment]
@InstabilSpielt I have found and fixed the issue causing this; it turns out that unlike many tags, when writing the `APIC` (attached picture) tag, the metadata is expected to be one level up from how other metadata is written. It's a little weird and we never caught it until now, but it's fixed and rolling out in the next Rolling Release version.
