### ISSUE TITLE
No request and no random playing

### ISSUE THREAD

**Issue by projecterik** [AzuraCast/AzuraCast#3901]
Azuracast is not playing random.
Also you can not do any request.
It wont play the request.

**Comment by SlvrEagle23** [comment]
@projecterik Please follow the issue template when creating a new issue.

**Comment by Vaalyn** [comment]
Closing since there have been no replies and the issue template was not used so there is no information that we can use to debug.

**Comment by projecterik** [comment]
> Azuracast is not playing random.
> Also you can not do any request.
> It wont play the request.

Dont understand what you mean with template

**Comment by projecterik** [comment]
> @projecterik Please follow the issue template when creating a new issue.

Dont understand.

**Comment by Vaalyn** [comment]
@projecterik When you hit `New Issue` -> `Get started` you will see the text field where you type your text already being filled with text. This text is the `issue template`, read it and answer the questions asked there instead of completely deleting it and writing freeform.

![image](https://user-images.githubusercontent.com/13745863/115908729-d27f9f80-a46a-11eb-9d38-afbf9b8cb1a6.png)

**Comment by projecterik** [comment]
Stil Dont understand.
But nevermind
