### ISSUE TITLE
Jingles does not play every X songs.

### ISSUE THREAD

**Issue by roger-net** [AzuraCast/AzuraCast#3908]
**Using Docker installation method**

Yes

**AzuraCast version**

0.12.2

**Host Operating System**

Ubuntu 18.04

**Describe the bug**

When I set up the jingles to play every X song, it just doesn't work, it gets all random and doesn't follow the rules. Example: If I set myself to play every 2 songs, sometimes it will play every 1 song after every 3 songs, becoming random and not respecting the settings. If you set it up to play every X minutes, then it works perfectly.

**To Reproduce**

**Expected behavior**

**Relevant Logs**

**Screenshots**

**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context**

**Comment by graemetadata** [comment]
This is another frustrating issue that I'm also experiencing.

I have three song playlists (okay / good / best) and two ident playlists (weekdays / weekend). So, four are "live" at any time.

Setting them all to play every four songs - with the aim of achieving a run of three songs then an ident and then another three songs – didn't reliably work. With idents appearing randomly after two, three of four songs during the week.

Bizarely, it was worse at at weekends (with exactly the same settings, but a different set of idents) as it was common to regularly get two or three idents playing out in a row, with one, two or three songs between them!

Setting all the playlists to once every three songs works better during the week, but is still unpredictable at weekends (when duplicate songs are also a problem).

Perhaps part of the issue is the description of the settings: Does X = four mean the item is the "fourth played" or "fifth -  after four have been played"?
