### ISSUE TITLE
Re: storing your station data on the host machine

### ISSUE THREAD

**Issue by AshleyinSpain** [AzuraCast/AzuraCast#3914]
**Using Docker installation method**

Yes

**AzuraCast version**

v0.12.2 Stable

**Host Operating System**

Ubuntu v20.04

**Describe the bug**

Trying to open the music files pages for any station throws a 500 error with - ‘The given value "" does not represent a valid number. BigNumber.php : 74’

**To Reproduce**

I created a docker-compose.override.yml file with this content

```
version: '2.2'

services:
  web:
    volumes:
      - /var/station_data:/var/azuracast/stations

  stations:
    volumes:
      - /var/station_data:/var/azuracast/stations
```

**Expected behavior**

The stations music files pages would open and I could interact normally uploading music etc

**Relevant Logs**

```
web_1                      | [2021-03-12T21:26:01.817195+00:00] AzuraCast.ERROR: HTTP client GET call to http://stations:8000/admin/stats produced response NULL [] {"station":{"id":1,"name":"Lobby"}}
web_1                      | [2021-03-12T21:26:01.817312+00:00] AzuraCast.ERROR: NowPlaying adapter error: cURL error 7: Failed to connect to stations port 8000: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://stations:8000/admin/stats [] {"station":{"id":1,"name":"Lobby"}}
web_1                      | [2021-03-12T21:26:01.843317+00:00] AzuraCast.ERROR: HTTP client GET call to http://stations:8010/admin/stats produced response NULL [] {"station":{"id":2,"name":"Lounge"}}
web_1                      | [2021-03-12T21:26:01.843474+00:00] AzuraCast.ERROR: NowPlaying adapter error: cURL error 7: Failed to connect to stations port 8010: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://stations:8010/admin/stats [] {"station":{"id":2,"name":"Lounge"}}
web_1                      | [2021-03-12T21:26:01.856440+00:00] AzuraCast.ERROR: HTTP client GET call to http://stations:8020/admin/stats produced response NULL [] {"station":{"id":3,"name":"Summer Grooves"}}
web_1                      | [2021-03-12T21:26:01.856540+00:00] AzuraCast.ERROR: NowPlaying adapter error: cURL error 7: Failed to connect to stations port 8020: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://stations:8020/admin/stats [] {"station":{"id":3,"name":"Summer Grooves"}}
web_1                      | [2021-03-12T21:26:01.870527+00:00] AzuraCast.ERROR: HTTP client GET call to http://stations:8030/admin/stats produced response NULL [] {"station":{"id":4,"name":"Summer Grooves - Copy 01"}}
web_1                      | [2021-03-12T21:26:01.870630+00:00] AzuraCast.ERROR: NowPlaying adapter error: cURL error 7: Failed to connect to stations port 8030: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://stations:8030/admin/stats [] {"station":{"id":4,"name":"Summer Grooves - Copy 01"}}
web_1                      | [2021-03-12T21:26:01.883815+00:00] AzuraCast.ERROR: HTTP client GET call to http://stations:8040/admin/stats produced response NULL [] {"station":{"id":5,"name":"Summer Grooves - Copy 02"}}
web_1                      | [2021-03-12T21:26:01.883931+00:00] AzuraCast.ERROR: NowPlaying adapter error: cURL error 7: Failed to connect to stations port 8040: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://stations:8040/admin/stats [] {"station":{"id":5,"name":"Summer Grooves - Copy 02"}}
```

**Screenshots**

https://jmp.sh/ehpMEfu 

**Device(s):**

- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context**

The directory /station_data was created in /var and I can upload to it with Filezilla
I can't sftp to the individual station media anymore - which is expected

However I cannot open the station music files pages

**Comment by silvaalex2021** [comment]
any progress on this issue?

**Comment by Vaalyn** [comment]
Is this still happening on the newest rolling-release version?

**Comment by silvaalex2021** [comment]
@Vaalyn yes, i can confirm that it is happening on the latest version.

the log shows:

[2021-04-24T02:05:25.764368+00:00] AzuraCast.ERROR: The given value "" does not represent a valid number. {"file":"/var/azuracast/www/vendor/brick/math/src/BigNumber.php","line":74,"code":0} []

**Comment by SlvrEagle23** [comment]
@silvaalex2021 The latest rolling release version that's uploading currently (and should be available in about 10 minutes) should help with this issue.

**Comment by silvaalex2021** [comment]
@SlvrEagle23 I tried to update to see if it works, but I got an error when running the Update script.

Restarting all radio stations...
--------------------------------

0%[2021-04-24T13:32:40.381926+00:00] AzuraCast.ERROR: RuntimeException: Directory "/var/azuracast/stations/teste" was not created (uncaught exception) at /var/azuracast/www/src/Entity/Station.php line 690 while running console command `azuracast:setup` {"exception":"[object] (RuntimeException(code: 0): Directory \"/var/azuracast/stations/teste\" was not created at /var/azuracast/www/src/Entity/Station.php:690)"} []
[2021-04-24T13:32:40.382832+00:00] AzuraCast.WARNING: Console command `azuracast:setup` exited with error code 1. [] []

In Station.php line 690:

  Directory "/var/azuracast/stations/teste" was not created


azuracast:setup [--update] [--load-fixtures] [--release]

WARNING: The LETSENCRYPT_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_HOST variable is not set. Defaulting to a blank string.
azuracast_redis is up-to-date
azuracast_stations is up-to-date
azuracast_mariadb is up-to-date
Creating azuracast_web ... done
Creating nginx_proxy   ... done
Creating nginx_proxy_letsencrypt ... done


And my docker-compose.override.yml is as follows:

version: '2.2'

services:
  web:
    volumes:
      - /radio/media:/var/azuracast/stations

  stations:
    volumes:
      - /radio/media:/var/azuracast/stations


I think it has something to do with the permissions on the /radio/media folder, but I don't know who I should give these permissions to, since there is no users other than "Alex" and "root" on this testing instance.

**Comment by SlvrEagle23** [comment]
@silvaalex2021 This is part of why we don't do this by default; because the permissions outside the Docker container have to match the permissions inside it, all the way down to the owning user.

I believe the owning UID inside the container is user ID `1000`, so whatever user that corresponds to outside the container should have ownership of the folder.
