### ISSUE TITLE
"Save changes" button on /admin/settings doesnt work (anymore?!)

### ISSUE THREAD

**Issue by PB-SF** [AzuraCast/AzuraCast#3943]
**Using Docker installation method**
No

**AzuraCast version**
Rolling Release #92910d7 (2021-02-09 6:34) • Ansible • PHP 7.4 

**Host Operating System**
Ubuntu 18.04 LTS

Hi,

I just wanted to enter a LastFM API key under the settings. When I click the save changes button, nothing happens. It looks like the button has no function.

Had installed the current rolling release update shortly before. Unfortunately, I cannot say whether the button worked before.

![grafik](https://user-images.githubusercontent.com/45131983/111956757-6fa58c00-8aeb-11eb-93df-74a256a43315.png)

**Comment by SlvrEagle23** [comment]
@PB-SF This is often caused by a field that's not currently visible in the UI not validating correctly; you should switch around from tab to tab until you find the field that is preventing you from submitting correctly. I realize this is confusing and not intuitive and I'm looking into solutions within our UI framework to allow us to better handle this.

**Comment by PB-SF** [comment]
Hi @SlvrEagle23 

Thanks for the hint. It Worked. In my case, I didn't put https:// in front of the System URL on the "Settings" tab. Maybe that will help you with the improvement.

Many greetings
