### ISSUE TITLE
Unique listeners of the Mountpoints are wrong

### ISSUE THREAD

**Issue by InstabilSpielt** [AzuraCast/AzuraCast#3948]
**Using Docker installation method**
Yes

**AzuraCast version**
v0.12.1 Stable

**Host Operating System**
Debian 10 & Ubuntu 20.04

**Describe the bug**
Through the API, the unique listeners of the different mount points are exactly the same as the current listeners. Nevertheless, the overall listener statistics of a station are correct. This is also noticeable on the start page, where the listener numbers are correct, but not on the profile page of the respective station.

**Comment by InstabilSpielt** [comment]
I recently also noticed that remote relays completely missing the unique listeners, although AzuraCast asks regularly for the listeners at Icecast.

**Comment by SlvrEagle23** [comment]
@InstabilSpielt What type of remote relay are you connecting to? Also, are you supplying an administrator password for it to fetch the detailed client info?

**Comment by InstabilSpielt** [comment]
To a specific mountpoint and the password is given, there is also no error in the log and the requests also arrive at Icecast @SlvrEagle23.

**Comment by InstabilSpielt** [comment]
@Vaalyn,  I have recently updated to the latest rolling release version, the problem exists there too and what information are still missing?

**Comment by Vaalyn** [comment]
I think the logs of when AzuraCast fetches the IceCast listener details of the mount points / relays could help.
We need to somehow narrow down where the problem originates from.

If the listeners are correctly fetched from IceCast and they look correct in that data then we can reasonably assume that the problem comes from the processing of that data or any step after that.

**Comment by InstabilSpielt** [comment]
The problem with the remote relays somehow solved itself after an update, no idea what happened there. And with the normal mount points, AzuraCast recognises all listener numbers correctly, but they are displayed incorrectly.

**Comment by Vaalyn** [comment]
@InstabilSpielt would you mind explaining which listener number are incorrectly displayed, where and how different they exactly are?

From the conversation in Discord it seems like the problem is the `Listeners` number for each station on the Dashboard. I'm unsure however if it is just UX problem (showing unique instead of over all) or if the number itself is complete wrong.

**Comment by InstabilSpielt** [comment]
It's not a UX problem, under `/api/nowplaying/{station_id}` you can find the listener statistics for the station as a whole and everything is correct here and then again for each mountpoint individually and here's the problem, it takes the **listeners.unique** and sets them for **listeners.current** as well.
