### ISSUE TITLE
Schedule AutoDJ

### ISSUE THREAD

**Issue by Gaili** [AzuraCast/AzuraCast#396]
Hi!
First congratulation for this awesome piece of software! To my request, is it somehow possible to start and stop AutoDJ scheduled, propably with cron? I would like to relay my main stream and sometimes playing my playlists with AutoDJ. Azuracast is running traditional on Ubuntu 16.04.

Thanks for your help

**Comment by SlvrEagle23** [comment]
@Gaili Storytime! I saw this issue when it was first submitted just over two weeks ago, and I thought "hmm, you know, there really is no way of accomplishing that right now", but what happened after that was something of a "If you wish to make apple pie from scratch, you must first create the universe" type situation.

I wanted to just move the existing frontend/backend control functionality out to the API, but first:
 - I had to build a way to include more station functions in the API, which led to a full refactor of the whole application's middleware and routing to follow modern best practices, and
 - Users needed a secure way to authenticate API keys, so I had to build a brand new API key management system that allowed each individual user to create API keys that matched their own permissions, and then ways for administrators to manage the API keys for the whole system.

Basically, these two items resulted in dozens of _major_ commits to the codebase, which rewrote large parts of the application to be cleaner, faster and better. All in all, a major improvement!

Anyway, the long and short is, it's now possible to programmatically control your station's frontend or backend. The API endpoints look like:

`POST /api/station/{id}/backend/{start|stop|restart}` for the "backend" (Liquidsoap), and

`POST /api/station/{id}/frontend/{start|stop|restart}` for the "frontend" (Icecast/Shoutcast)

To authenticate, there is a new "My API Keys" section on the top right menu inside AzuraCast. This will create a new, secure API key that you can use to perform API calls that modify the system (like this one). You'll only see the API key show up once (immediately after it's created), so make sure you keep track of it; you can always just make a new one if you lose it, though.

To automate something like shutting down the AutoDJ, you'd want to use something like cURL, which could call the API like so:

```bash
curl -H "X-API-Key: {api_key}" -X POST http://localhost/api/station/{id}/backend/stop
```

This could be a cron task if you want.

You can also re-enable the AutoDJ by executing the same command, but with `/start` at the end instead of `/stop`.

Try it out and let me know if you have any questions!
