### ISSUE TITLE
Commercial playlist

### ISSUE THREAD

**Issue by radiobellissima** [AzuraCast/AzuraCast#3967]
I have tried in every way to have a sequential playlist made up of 3 files every 20 minutes or scheduled by time on the air. Is it possible that there is no way to do this?

**Comment by Jaadoo13** [comment]
Hello. If you make a new Playlist, then you have in the first Tab the "Playlist Type". There you can choose "play once each x minutes.." check to activate this list and save it. this works for me. As i use it for my Radio Jingles to be played every 25 Minutes.

**Comment by radiobellissima** [comment]
Sure it works. But I have to play an entire playlist not a single file. This doesn't work.

**Comment by Jaadoo13** [comment]
Okay, then im sorry. I dont know whats wrong on your install. For me, it play all the tracks in this playlist. Because i have also some ads to play. and this are 5 Files every 30mins. And it works great.

**Comment by radiobellissima** [comment]
Unfortunately I can not do it because the files are relatively short are the accesses to the advert and last a few seconds. In any case, even testing with longer files, everything is then not respected as an order so it is practically unusable.

**Comment by Jaadoo13** [comment]
Okay, what if you make one big File of all the short Files? Then you have only one File and this works. I mean as long there is no change of possibilities in azuracast....

**Comment by radiobellissima** [comment]
I can't do that, the commands are serving the separate tags.

**Comment by silvaalex2021** [comment]
@radiobellissima you can (almost) get what you want using the "merge playlist to play as a single track" option, which is present in the "advanced" tab of the playlist settings dialog.

although this is the only way, it will probably break the schedule, because azuracast's internal autoDJ will continue to feed Liquidsoap with new tracks, unaware that there is a programmed playlist on the way.

summary: your commercials will play, but only when liquidsoap finds an opportunity to do so, which can take a long time.

P.S .: I have been testing this for months with a replica of my station, and this is exactly the behavior I encountered in practice. my choices are to deactivate Azuracast's internal AutoDJ and rely only on LS, or accept that only one commercial will be played every X minutes...
