### ISSUE TITLE
Delay in playlist playback

### ISSUE THREAD

**Issue by fidegr** [AzuraCast/AzuraCast#3989]
v0.12.2 Stable • Docker • PHP 7.4 · Debian 10

Since the update to the latest stable version of Azuracast, an error that seemed resolved in previous updates repeats. This is the delay in the start of playlist playback. For example, a playlist that plays a program at 8 in the morning starts minutes late because a music song is always coming through. It is not placed at the beginning of the queue, but a musical theme is sneaked in that causes a delay of minutes and then that playlist sounds.

The strategy that we are following is to program the playlists of these programs with several minutes in advance. But if the previous content ends after the scheduled start time of that playlist, a music track is sneaked in and a delay is generated again.

What possible solution do you see for this error?

**Comment by silvaalex2021** [comment]
same problem here, and I’m testing some things to make it work on my side.

Currently, what (almost) always works for me is the following approach:

Scheduled playlists: must be scheduled to start 5 minutes before the originally planned time (example: for a show that starts at 8:00 am, the playlist must be scheduled to start at 7:55 am). In addition, the weight of scheduled playlists must be greater than the weight of standard playlists (i use 15 and my standard pls are using 3).

AutoDJ Queue: should be left at the default value.

using these settings, I have been able to avoid many delays during my daily schedule. I hope it works for you too, if you give it a try.

**Comment by fidegr** [comment]
Hi, that's the solution we use. The fact is that in a previous update, right now I could not tell you exactly which one, it started to queue the playlists well and it was not necessary to reduce the playlist time or you could reduce it to 1 or 2 min before the time. But now we suddenly have continuous delays. The worst is when a program ends a few minutes later than the hour.

**Comment by silvaalex2021** [comment]
what i also still haven't been able to figure out is why sometimes the show is in the AutoDJ queue, scheduled to play at exactly the right time, in my example at 8:00 am, and suddenly azuracast rebuild the queue, and the show is rescheduled for , say, 8:05 am, causing the delay. anyway, i changed the log level to debug and i will dig into the logs of both azuracast and liquidsoap so that i can then bring some more accurate information about what is going on.

maybe @SlvrEagle23 can help me figure out what I need to look for in the logs, since the debug loglevel produces huge amounts of information

**Comment by ismaelazanza** [comment]
It would be necessary to be able to find out the problem, I also experience the same problem, I program it at 9 AM and it sounds from 10 or 15 min. It would be great if it started on time, or I don't know if there is a possibility that the program will sound exactly at the scheduled time and the music that is playing at that time stops.

**Comment by silvaalex2021** [comment]
@ismaelazanza  although it is not recommended as it can lead to some unexpected results, one thing you can try is to switch to the "advanced" tab on the playlist editor. there is an option that can help you achieve what you want to du.

it is the very first option on this dialog.

![advanced-playlist](https://user-images.githubusercontent.com/77082907/115167432-f9665c00-a08d-11eb-8c6a-27fe576b412f.png)

please be careful when using it because the interrupt switch is "abrupt", for example if you set a playlist to play between 8:00 and 10:00 it will play exactly between 8:00 and 10:00, and it will stop exactly in the same way as it started, abruptly, without waiting for the show to end. also note that each time you modify a playlist with this option enabled, you must restart your station for the changes to take effect.
