### ISSUE TITLE
Unable to switch "Listener Analytics Collection" setting

### ISSUE THREAD

**Issue by pascalla** [AzuraCast/AzuraCast#3991]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #8c67b18 (2021-04-08 4:23) • Docker • PHP 7.4

**Host Operating System**
Ubuntu 18.04

**Describe the bug**
I am unable to save the setting after changing it from "Full" to "Limited"

**To Reproduce**
1. Open System Settings
2. Switch to Privacy tab
3. Switch from "Full" to "Limited"
4. Click "Save Changes"

When you click save changes it just hangs and there is an error in console. It does not make any network requests

**Expected behavior**
Save the settings, green toast.

**Relevant Logs**
![image](https://user-images.githubusercontent.com/22846433/114024090-8da11980-986b-11eb-9b5e-b22e21897a46.png)
![image](https://i.imgur.com/lAZUQDX.gif)

**Device(s):**

- Device: Desktop
- OS: Windows 10
- Browser: Chrome
- Version: 89

**Additional context**
Kind of a sidenote, does switchin this setting from "Full" to "Limited" delete all currently stored "IP Based statistics?"

**Comment by SlvrEagle23** [comment]
@pascalla That's because the browser is trying to validate the Base URL (which is in another tab) and that's preventing the form from submitting correctly. This is a known issue and we unfortunately haven't figured out a resolution to make it auto-switch tabs to show it; if you fix the base URL (usually it just needs prefixing with the `https://` scheme) it will let any other settings changes through.
