### ISSUE TITLE
Abnormal CPU usage after update

### ISSUE THREAD

**Issue by ncfernan** [AzuraCast/AzuraCast#4005]
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #5d14058 (2021-04-11 3:04) • Docker • PHP 7.4

**Host Operating System**
Ubuntu 20.04 LTS

**Describe the bug**
An abnormal peak of CPU usage occurred 20 minutes after the last update and the streaming stopped.

I moved my 2 stations (one listener, just me) to a bigger box with 2 cores + 4 GB + 80GB trying to avoid such problemas, but to no avail.

Please notice the "now playing" task. I've reported this issue some days ago (#3979) and it seems that it is not important. The "next song" is (null) for station 1 and repeats the "now playing" title on station 2.

I don't know if the "now playing" task error is related to this high CPU usage issue. What impresses me besides the CPU usage is the memory usage for only 2 stations. The error that occurs when the "now playing" task is forced to run is related to PHP memory limit. This should not happen for only 4309 songs.

There is something very wrong occurring here...

**To Reproduce**
I don't know if someone else is experiencing this problem. It just popped up from nowhere.

**Expected behavior**
I don't care much if the CPU and memory figures are high, but the streams must be on all the time.

**Relevant Logs**
Just tell me what to look for and I'll post them here.

**Screenshots**

High CPU and memory usage:

![image](https://user-images.githubusercontent.com/10008844/114305143-528e2880-9aad-11eb-9d7a-64cba82a1b8e.png)

Effects of "now playing" task being stuck on station 1:

![image](https://user-images.githubusercontent.com/10008844/114305619-53c05500-9aaf-11eb-8835-cde5fdb689be.png)

Effects of "now playing" task being stuck on station 2:

![image](https://user-images.githubusercontent.com/10008844/114305630-6175da80-9aaf-11eb-8c08-383dd72de76a.png)

**Device(s):**

- Device: Desktop
- OS: Win10
- Browser: Chrome
- Version: 89.0.4389.114 (Official Build) (64-bit)

**Additional context**

**Comment by SlvrEagle23** [comment]
@ncfernan If your process memory limit is set to 512MB, the `Now Playing` sync task really shouldn't be hitting a memory limit. It's not even a very intensive task in the first place, and it's almost never the one that gets limited by external memory limits.

I'm pretty convinced there's something else going wrong here that's causing a memory leak or some sort of recursive CPU overload in certain cases.

Can you join our [Discord](https://discord.gg/azuracast) and send me a direct message referencing this issue? I may need to take a look at your specific installation, because we've had a few reports of issues like this and yet we can't reproduce these issues locally, so we definitely need to look further into it.

**Comment by SlvrEagle23** [comment]
Thanks to the help of the station operator in this issue, I was able to profile their installation's memory usage and identify the problem, which was a query that was returning far more record data than was necessary, which was being repeatedly run and was filling up the available RAM used during the sync process. In some cases, the RAM usage got so high that it started swapping, which resulted in heavy IO and CPU usage as well and tended to run "out of control".

This issue has been significantly mitigated in the last few Rolling Release updates, and the installation in question in this issue is now operating fully within normal parameters again.

If you're experiencing a similar issue, I encourage you to update to the latest Rolling Release version (a version at least on or after Apr 12, 2021).
