### ISSUE TITLE
Audience measurement divergence in the stations profile when blank metadata sent by the encoder.

### ISSUE THREAD

**Issue by youngdesenv** [AzuraCast/AzuraCast#4022]
**Using Docker installation method**
Yes

**AzuraCast version**
0.12.2

**Host Operating System**
Ubuntu 20

**Describe the bug**
Audience measurement divergence in the stations profile when blank metadata sent by the encoder.

![image](https://user-images.githubusercontent.com/46824994/114880738-b4fe6600-9dd8-11eb-8633-8171887e33e1.png)

**Comment by SlvrEagle23** [comment]
@youngdesenv I've pushed an update to the Rolling Release channel that should make the software more predictable in terms of what it registers as an online stream and what it doesn't register as one (and how it sums up its totals).

**Comment by youngdesenv** [comment]
Thanks. I will wait for this correction to enter the stable version.

**Comment by youngdesenv** [comment]
After upgrading to the latest version (0.13.0), the problem continues to occur.

**Comment by SlvrEagle23** [comment]
@youngdesenv We specifically made changes that should prevent this kind of thing from happening. We've also made a number of changes since 0.13.0, so if you're interested in helping us build new features, you may want to have an installation that's on the Rolling Release branch that you can help us test with.
