### ISSUE TITLE
LiquidSoap frequent repetition of songs

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#406]
tell me please how to set up LiquidSoap so that the song does not repeat itself so often? If you turn it off then the radio stops working. Or how to reset the ratings of songs, perhaps this is the whole point. thank you very much.

**Comment by Bonjoveh** [comment]
Yea I have got the same issue, I tried alot, but it seems like it somehow 'reloads' the playlist so it starts over at the previous songs.
Is there any solution found yet?

Thanks for your time.

**Comment by SlvrEagle23** [comment]
@susl16c @Bonjoveh This issue is really hard for me to diagnose, as I don't have enough information to know what's causing the issue, and it would take a fair amount of testing and tweaking to identify the specific issue in your radio stations.

To start, it would be helpful to know:
- How many "standard" playlists you have, and what their weights are,
- How many songs are in each playlist,
- Whether the songs that are playing too often are always playing from one single heavily-weighted playlist,
and
- If you're on Docker, if `docker-compose logs -f stations` shows errors from AzuraCast instead of proper song names.
