### ISSUE TITLE
Webcast.js does not work with umlauts / special chars in username or password

### ISSUE THREAD

**Issue by Horstwursti** [AzuraCast/AzuraCast#4078]
**Using Docker installation method**
Yes

**AzuraCast version**
rolling Release #1c959dd (2021-04-25 14:52) • Docker • PHP 8.0 

**Host Operating System**
debian 10 buster

**Describe the bug**
start streaming from the Web-DJ panel is not possible when a password or username is set with umlauts/mutated vowels like Ä, Ü, Ö, etc.

**To Reproduce**
setup a Live-Streamer/DJ account and start streaming with the credentials you had setup from the Web-DJ panel. The AutoDJ plays further music from the music database and no live stream got set into the autoDJs cue.

**Expected behavior**
it would be nice when it's possible to setup credentials with umlauts to use auto generated passwords with these letters to get more password entropy and set usernames with umlauts like "Björn" f.E.

**Relevant Logs**
this behavior isn't logged by AzuraCast

**Screenshots**
no screenshots available

**Device(s):**

- Device: Notebook and Desktop machine
- OS: Notebook: Xubuntu 18, Desktop Machine: Ubuntu 20
- Browser: both with Firefox
- Version: 87

**Additional context**
i tested it with and without umlauts and every time i use umlauts, the livestream doesn't start

**Comment by Vaalyn** [comment]
I have been investigating the source of this issue.

I was initially thinking that the websocket connection to Liquidsoap was using the username and password as part of the `wss://` url which obviously would lead to umlauts being converted to their url encoded form.

After investigating how the `webcast.js` library works I found out that there is a rather questionable piece of code in there in regards to how the username and password are handled which causes this issue.

Here is an excerpt of the code that creates the websocket connection:
```js
Webcast.Socket = function(arg) {
    var hello, info, key, mime, parser, password, send, socket, url, user, value;
    url = arg.url, mime = arg.mime, info = arg.info;
    parser = document.createElement("a");
    parser.href = url;
    user = parser.username;
    password = parser.password;
    parser.username = parser.password = "";
    url = parser.href;
    socket = new WebSocket(url, "webcast");

...
```

As can be seen here the `Webcast.Socket` receives an object of arguments called `arg` which contains the `url`. The library expects the username and password as part of this URL in the form of `wss://username:password@www.example.com/`.

The library then creates a basic `a` element, sets the URL to it and uses the element to cut the username and password from the url before creating the `WebSocket` from this modified URL. The username and password that are cut from the URL are then used as part of the initial `hello` JSON message to Liquidsoap.

Due to this `a` element stuff umlauts are automatically url encoded leading to authentication failure in LS.

For me there is no logical reason for supplying the username and password as part of the URL to webcast apart from the library requiring it. It would be much more sensible to have a separate `username` and `password` argument for initialising the `Webcast.Socket`.

I have checked if the version `1.0.0` of webcast has been updated to do this differently but this part of the code has not been changed much and is still requiring a single URL argument and parsing the username and password from it:

https://github.com/webcast/webcast.js/blob/master/webcast.js#L2-L12

**Comment by Vaalyn** [comment]
We should investigate the effort for upgrading the WebDJ to use webcast.js `1.0.0` and modifying it to fix this issue by adding the username and password to the constructor parameters of the `Webcast.Socket` class.

If we do switch to webcast.js `1.0.0` we should think about contributing this modification back to the webcast.js repo.

**Comment by BusterNeece** [comment]
After updating our Webcaster implementation, the new webhook-based authentication doesn't suffer from this problem.
