### ISSUE TITLE
update AzuraCast docker

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#408]
I noticed that after every update there are not necessary components in the docker and they have to be deleted, I always execute these commands:

> docker rm $( docker ps -q -f status=exited)
docker rmi $( docker images -q -f dangling=true)
docker volume rm $(docker volume ls -f dangling=true -q)

How can I embed the updates in the script so that they run automatically after the update? To docker did not increase in size.

**Comment by SlvrEagle23** [comment]
@susl16c Since the update script isn't itself updated by the github repository any more, you can always just manually update your own `docker-update.sh` script to include those items.

The reason I don't include them by default is because they remove more than just images relating to AzuraCast; they may remove images relating to other projects that the user doesn't want removed.

**Comment by susl16c** [comment]
Yes, you are right about this, I did not think I had a docker, only your project, so I thought so
