### ISSUE TITLE
Server Not Reachable - CSF Misbehaviour after Recent update

### ISSUE THREAD

**Issue by MackPerfecto** [AzuraCast/AzuraCast#4089]
Docker - Yes

AzuraCast Version 0.12.4 (Apr 27, 2021)

Host Operating System: Ubuntu LTS 20.04.02

Expected Behaviour: Prior to 0.11.2 AzurCast used to play without issues under Config Server Firewall - CSF 14.09 now unless its disabled its not playing.

Relevant Logs: Every System restart Azura plays for a few seconds with CSF enabled. Then it shows the server not reachable screen.

Devices: Desktop, Android browsers. All recent stable updates.

Additional Text:Any other Firewall Setting which makes it work?

**Comment by SlvrEagle23** [comment]
@MackPerfecto Are you trying to use LetsEncrypt on the same device? The validation method the nginx proxy uses for LetsEncrypt involves publishing a HTML file in a known directory and then having the remote LetsEncrypt server check for that file, so if it can't reach that file (because it's blocked by the firewall), it's possible it could cause problems here.
