### ISSUE TITLE
icecast.xml not loading custom config

### ISSUE THREAD

**Issue by dturrina** [AzuraCast/AzuraCast#4091]
**Using Docker installation method**
Yes

**AzuraCast version**
#ccdee79

**Host Operating System**
Debian 10

**Describe the bug**
Even with the public database sharing flag ON on the mount point and yp config in Advanced configuration for the station, when I check the icecast.xml config in log view I can't see the yp config

**To Reproduce**
1. Under Mount point configuration, check the Public database sharing flag is on
2. Under Station configuration, add yp lines (mine is `<directory><yp-url-timeout>15</yp-url-timeout><yp-url>http://yp.simosnap.com/yp.php</yp-url></directory>`)
3. Restart station if needed and under Utilities -> Log viewer, check Icecast configuration

**Expected behavior**
I should see the yp config written above

**Comment by SC2Mitch** [comment]
I've used your code listed and I've been able to replicate this issue. 

I have found a workaround but it's not the most ideal however, instead of going through the mount points, do it through the station settings (Edit Profile) and it's under Broadcasting, use the Advanced Custom Configuration there. This is the best workaround I can offer at this time. With the workaround: https://puu.sh/HCUsx/371a48103d.png

**Comment by Vaalyn** [comment]
@SC2Mitch please correct me if I'm wrong but I think it makes sense that this config needs to be set on the station level instead of per mount point since the yp listing config is not mount point specific in IceCast: https://icecast.org/docs/icecast-2.4.1/config-file.html#yp

It is definitely weird to have the `Publish to "Yellow Pages" Directories` option on mount points due to that. As far as I can see that option value is only used in the config writer for Liquidsoap here https://github.com/AzuraCast/AzuraCast/blob/main/src/Radio/Backend/Liquidsoap/ConfigWriter.php#L1058

This only sets the `public` parameter for the LS `output.icecast` which I wasn't able to find an explanation for what it actually does and I can't see any obvious effects from having it on/off...

**Comment by SC2Mitch** [comment]
@Vaalyn You raise a good point, perhaps it would be good to change around the page, remove some outdated information from it then.

**Comment by dturrina** [comment]
The workaround runs -- though, I'm still not sure everything is OK as I can't see my radio in the public listing (radio.simosnap.org) while I can see yours

**Comment by SlvrEagle23** [comment]
> @SC2Mitch please correct me if I'm wrong but I think it makes sense that this config needs to be set on the station level instead of per mount point since the yp listing config is not mount point specific in IceCast: https://icecast.org/docs/icecast-2.4.1/config-file.html#yp
> 
> It is definitely weird to have the `Publish to "Yellow Pages" Directories` option on mount points due to that. As far as I can see that option value is only used in the config writer for Liquidsoap here https://github.com/AzuraCast/AzuraCast/blob/main/src/Radio/Backend/Liquidsoap/ConfigWriter.php#L1058
> 
> This only sets the `public` parameter for the LS `output.icecast` which I wasn't able to find an explanation for what it actually does and I can't see any obvious effects from having it on/off...

My understanding was that streams won't be advertised on the Yellow Pages directories unless their broadcast metadata indicates that they're public streams, otherwise even if the YP data is there, the streams won't show up as online there.

I haven't given much attention to the Yellow Pages directories, to be honest. I know in SHOUTcast's case, you can't even list on their YP directories unless you're on the newest "freemium" version, so I haven't bothered to mess with them in general at all.
