### ISSUE TITLE
Playlist song gets rescheduled for no apparant reason

### ISSUE THREAD

**Issue by emilio-pro** [AzuraCast/AzuraCast#4124]
**Using Docker installation method**

Yes

**AzuraCast version**

v.0.12.4 (but already present in v0.12.3)

**Host Operating System**

Linux DSM6.2

**Describe the bug**

I have several playlists that contain 1 track, with the duration of an hour or more. These playlists contain a rerun of a live show and they are scheduled to play at a designated time (ie 20:00 PM). After the rerun, a regular playlist kicks in which plays tracks at random - there are over 500 songs to choose from.
For some reason the scheduled track is queued up again approximately an hour and a half later (ie 21:30).
I have several 1-track playlists all with the same problem.

**To Reproduce**
Don't know....

**Expected behavior**
Queue honouring the schedule.

**Relevant Logs**
Can't find any errors in the usual logs. Is there a log that shows the (re)building of the queue?

**Screenshots**
<img width="556" alt="afbeelding" src="https://user-images.githubusercontent.com/26246547/117054076-089a0a80-ad1a-11eb-89ae-8a47d3d120b0.png">

<img width="544" alt="afbeelding" src="https://user-images.githubusercontent.com/26246547/117054137-18b1ea00-ad1a-11eb-9dc1-46252b7413a9.png">

<img width="544" alt="afbeelding" src="https://user-images.githubusercontent.com/26246547/117054221-29faf680-ad1a-11eb-8a63-9735d85071a6.png">

<img width="552" alt="afbeelding" src="https://user-images.githubusercontent.com/26246547/117054261-34b58b80-ad1a-11eb-84ad-3910d4d545c8.png">

But:
<img width="841" alt="Schermafbeelding 2021-05-04 om 20 42 11" src="https://user-images.githubusercontent.com/26246547/117054378-54e54a80-ad1a-11eb-95a3-d4fe735b5c30.png">

**Device(s):**
Not relevant
- Device: 
- OS: 
- Browser: 
- Version: 

**Additional context**

I'm under the impression that the problem arose with v0.12.3

**Comment by SlvrEagle23** [comment]
While I'm unsure of what's causing this exact error, I have a hunch that it has to do with the way the AutoDJ scheduler has been determining the "Now" timestamp (i.e. the time it's actually scheduling against when playing tracks). I've made a minor update to this that may improve this situation, and that's currently being deployed via the Rolling Release channel (and should be available within about 10 minutes).

Beyond that, there's nothing in the logs provided that suggest anything else unusual is happening.

**Comment by jjs999jjs** [comment]
Just a follow up..

Scheduled show for tonight 8pm is showing as going to play twice.

logs for the second play is --

[2021-05-10T19:00:32.036619+00:00] AzuraCast.WARNING: Playlist "Porridge Drawers Disco Show" did not return a playable track. {"playlist_id":36,"playlist_order":"random","allow_duplicates":false} {"station":{"id":1,"name":"webcomradio"}}
[2021-05-10T19:00:32.038072+00:00] AzuraCast.WARNING: No way to avoid same title OR same artist; using least recently played song. {"media_id":5000,"title":"Disco Classics Show 9","artist":"Porridge Drawers"} {"station":{"id":1,"name":"webcomradio"}}

Powered by AzuraCast • Rolling Release #fdc1c6a (2021-05-09 19:08)


It may simply be a glitch because it is the first issue since the update seemed to sort it.

![image](https://user-images.githubusercontent.com/65810290/117717433-b736c300-b1d2-11eb-91fe-591512904323.png)
![image](https://user-images.githubusercontent.com/65810290/117717468-c3228500-b1d2-11eb-8fdd-147e8acb356f.png)
