### ISSUE TITLE
mapping files to their directories

### ISSUE THREAD

**Issue by zloysystem** [AzuraCast/AzuraCast#4141]
Good day gentlemen!
Debian 10, Docker, Rolling Release # f32eebb
When a directory is uploaded to the server, all the files in it are extracted, the directory is left empty, which causes confusion when multiple directories are uploaded at the same time, which file and where is it from.
![TVy5rA4xXz](https://user-images.githubusercontent.com/26243386/117538713-19939600-b010-11eb-87a0-10f930596ad5.gif)

And the second problem, it extracts all files that are uploaded or loaded into the directory to the root directory
![5EYoLjpv444444444th](https://user-images.githubusercontent.com/26243386/117539153-100b2d80-b012-11eb-81a5-34e7cf31ce44.gif)

**Comment by Vaalyn** [comment]
This is most likely a bug caused by the new script for automatic file name sanitising for files uploaded via SFTP which was added in https://github.com/AzuraCast/AzuraCast/commit/f59fd8a9ba912440a04408eb4b3a35dee8ed01f7

**Comment by SlvrEagle23** [comment]
Indeed this is a bug introduced as a result of our recently added file sanitization in SFTPgo. I've also identified some other bugs in a number of SFTP clients caused by the fact that when sanitizing the file paths, the file name changes after the file is uploaded and some SFTP clients try to pull metadata about the original filename, which causes it to have trouble. I raised this issue directly with the SFTPGo folks directly, so we'll see if they have another way to approach this situation.

In the meantime, the file sanitization is being disabled for now as of the current Rolling Release version that's being uploaded currently.
