### ISSUE TITLE
Development vs Production

### ISSUE THREAD

**Issue by amavarick** [AzuraCast/AzuraCast#416]
Docker Installation
Host OS: Ubuntu 16.04.3 LTS

When updating my instance through the CLI, it states I am using a "production" install.
![image](https://user-images.githubusercontent.com/20918832/36047962-a945d55c-0dab-11e8-95fb-f2fa4ae27464.png)

However looking at the GUI it states, "Development."
![image](https://user-images.githubusercontent.com/20918832/36048007-cfbd0b60-0dab-11e8-8c09-c7cf73314772.png)

Is this as designed because the AzuraCast software itself is still in development?
I notice that even the public radio page shows development.
If I could be picky, I'd prefer that it not show development or only show that if I've selected the Development type of install.  At a minimum, if "Development" could be taken off of the public radio page, that'd be greatly appreciated.

**Comment by SlvrEagle23** [comment]
@amavarick The "(Development)" mode depends on the contents of `app/env.ini`; if you're running a production environment you should certainly remove the "development" setting in that file, as it also has greater error reporting that might not be appropriate for production.

The updater running in production/development mode is a different thing; development doesn't trigger the usual "git reset and git pull" functionality but otherwise runs other updates.

**Comment by amavarick** [comment]
Not sure I understand.  My env.ini shows production.  However the Internet Browser Tab shows "(Development)."

```
stream1:/opt/azuracast/app# cat env.ini
;
; AzuraCast Environment Settings
;
; This file is automatically generated by AzuraCast.
;
[configuration]
application_env="production"
stream1:/opt/azuracast/app#
```

**Comment by SlvrEagle23** [comment]
@amavarick It appears your env.ini file is misparsing for some unknown reason. By default, on Docker installations, the configuration file only contains that single directive, that it should be running in "production" mode.

In any case, it's probably wise from a risk-management standpoint to "fail safe" in this regard, and to assume that instances are production instances unless explicitly specified otherwise. The latest change does this.

**Comment by SlvrEagle23** [comment]
@amavarick I was just reading back on this and realized that you mentioned you were using the Docker installation, not the traditional installation. If you make a file `app/env.ini` in the host filesystem, that won't be read by the Docker install, which is now "self-contained" inside the Docker image. You'd have to update the code inside the Docker image itself, which you could do via `docker-compose run --rm cli`.

The Docker installer should be automatically generating that file and putting it in the right place, but if it isn't, just try putting it there yourself and it should fix it. Let me know how it goes.

**Comment by amavarick** [comment]
I should have realized that myself and gone into the docker instance instead of the azuracast directory on the docker host machine.  Thank you for catching that for me.  Notice line annotating production or development is missing below.
```
stream1:/opt/azuracast# docker-compose run --rm cli
Starting azuracast_stations ...
Starting azuracast_mariadb_1 ... done
Starting azuracast_web_1 ... done
azuracast@cf4a03a910e2:~/www$ cd app
azuracast@cf4a03a910e2:~/www/app$ cat env.ini
;
; AzuraCast Environment Settings
;
; This file is automatically generated by AzuraCast.
;
[configuration]
```

Made the change to annotate production and then performed a docker-update to update and restart services.
```
azuracast@cf4a03a910e2:~/www/app$ cat env.ini
;
; AzuraCast Environment Settings
;
; This file is automatically generated by AzuraCast.
;
[configuration]
application_env="production"
azuracast@cf4a03a910e2:~/www/app$ exit
exit
cd /opt/azuracast/
./docker-update.sh
```

The steps above worked.  No more "development" appearing on my browser site title and tab.  One slight deviation in my documentation, nano, pico and vi didn't work so I had to sudo apt install nano to modify env.ini from within docker.  Will that cause any problem for me moving forward?  If not, please consider this issue gladly resolved!

**Comment by SlvrEagle23** [comment]
@amavarick Since the instance of the CLI you connect to when running `docker-compose run` is ephemeral, it only exists for the time you're connected to it; once you disconnect, the only changes that persist are to the shared parts of the filesystem (i.e. the AzuraCast code itself). You're perfectly free to install vim or whatever other tools you want in there.
