### ISSUE TITLE
changing the front end will reset all mount points to the default

### ISSUE THREAD

**Issue by silvaalex2021** [AzuraCast/AzuraCast#4166]
**Using Docker installation method?**
Yes

**AzuraCast version:**
Rolling Release #5271957 (2021-05-11 21:16) 

**Host Operating System:**
ubuntu 20.04

**Describe the bug:**
I don't know if it's a bug or a feature, but every time the front end is changed (icecast to shoutcast or vice versa), all mount points are erased and a new one is created, with the default settings. Server change is also done on the fly when you click on the "save settings" button, without having to restart the station as usual.

**Steps to reproduce:**
1: create one or more mount points and configure them;
2: change the broadcast server, from Icecast to shoutcast or from shoutcast to icecast;
3: change will be made immediately after clicking "save";
4: See that all mount points are gone and a new one has been created, with the default configuration.

**Expected behavior:**
mount points shouldn't disappear

**Comment by SlvrEagle23** [comment]
@silvaalex2021 This is by design, as both of the frontends have different support for mount point formats, so out of an abundance of caution and to avoid broadcasting via an unsupported mount point format we simply reset the mount points to their defaults any time the broadcasting frontend is switched, which should be exceedingly rarely (if at all) for most stations.

**Comment by silvaalex2021** [comment]
thank you!

closed as clarified
