### ISSUE TITLE
Songs don't get added after upload completes

### ISSUE THREAD

**Issue by semyonsh** [AzuraCast/AzuraCast#421]
- **Installation Method:** Traditional on Ubuntu 16.04

Hi, first of all thanks for this great piece of software, i've set it up for a web-based radiostation for the foundation i work for but i'm running into a problem: 

- If me or other users add new music it doesn't show up in the web interface anymore, we added around 250~ song the last few days but it just stopped working/adding them now. 
- Creating a folder doesn't make it show up in the web interface. 
- Size seems to increase in the top right but files don't show up on the server itself (checking the /media folder). Doesn't show up after running the media sync. So it must be going somewhere? 
- Tried updating with update.sh but didn't show any improvement either. 

Not sure how to provide more info, or logs, i will happily show it. Now i'm just thinking about saving the media files and nuking the install and start over but maybe there is a simple fix? Thanks in advance!

**Comment by SlvrEagle23** [comment]
@semyonaut The best way for us to diagnose this issue will be to run the web inspector console on the Music Files page. You can reach that by pressing `Ctrl+Shift+I` or `F12` on the page, then trying to upload the files again.

The first area you'll want to check is the "Console" section. If you see any errors pop up in red, take a screenshot or copy/paste those here and let me know.

Otherwise, you'll want to switch over to the "Network" tab, then try uploading the file again. At the bottom of the list, you should see new requests popping up as the system tries to upload each part of the file. Click each request, and see if its "Response" section is returning any sort of error, or just a generic success message.

As for where the files are living on the server, they do upload to the system temp directory (likely `/tmp`), specifically inside a folder there called `/tmp/uploads`. One other debugging strategy you can try is to wipe that uploads folder out entirely (it won't hurt anything), then reuploading the files.

**Comment by semyonaut** [comment]
@SlvrEagle23 Thanks for your reply. I have good news and bad news, the good news is that i've sort of fixed the issue myself, the bad news is I can't reproduce the bug now for future reference. So we will have to wait in case this happens again, it might have been caused by a misconfiguration by myself or otherwise, we won't know for now, but i'll be sure to open up another issue if this happens again in the future.

What happened was that i tried to run the update.sh once again after testing the upload which broke my nginx installation, it couldn't start anymore because of nchan failing. DPKG couldn't remove nginx the normal way so I purged nginx and nginx-extras from my system and ran ./update.sh --full in the azuracast folder. This restored everything back to normal. I've checked the uploading with web inspector and POST goes through fine, no abnormalities so far. Cleared out the /tmp/ folder too, it contained the uploads that weren't added. 

Anyways thanks for your response, if it happens again i'll let you guys know.
