### ISSUE TITLE
Custom IceCast alias via XML throwing Exception in XML\Writer

### ISSUE THREAD

**Issue by PB-SF** [AzuraCast/AzuraCast#4223]
**Using Docker installation method?**
No, Ansible

**AzuraCast version:**
Rolling Releases

**Host Operating System:**
Ubuntu 18.04 LTS

Hi, I wanted to update my Ansible installation to the latest version.

I received the following error message.

![grafik](https://user-images.githubusercontent.com/45131983/119891462-47963700-bf39-11eb-8972-bdd638356dba.png)

Since then, Azuracast has run into a `502 Bad Gateway` error when called. I don't have access to the settings.

What can I do?

**Comment by Vaalyn** [comment]
Sorry about the confusion with the labels, I misread some other errors description.

Do you have any custom IceCast / MountPoint configs?

As far as I can see from the error it is trying to mix `numeric` and `string` keys in the XML it generates for stations IceCast config and I'm not aware of any config included in AzuraCast that uses a `numeric` as a key somewhere.

**Comment by PB-SF** [comment]
Hi @Vaalyn 

I use some settings for the mount points. All of them are written after the Icecast Docs and have worked well so far.

Could it be using of 

```
<paths>
    <alias source="/foo" dest="/bar"/>
</paths>
```

https://icecast.org/docs/icecast-2.4.0/config-file.html#path

Greetz

**Comment by Vaalyn** [comment]
Could you tell me which AzuraCast version you were running before the update?

I have investigated this problem a bit and found this related issue: https://github.com/AzuraCast/AzuraCast/issues/4125

When I use the JSON version of the custom config it is correctly working (as far as I can see) and it's only throwing an error when using XML. It might be that the fix for the issue I linked above caused the XML to not work correctly anymore but I'm not actually sure about that since the user in that issue reported that the XML version was also not working for him before the fix.

**Comment by PB-SF** [comment]
Hi @Vaalyn 

I'm not entirely sure, but it should `Rolling Release #92910d7 (2021-02-09 6:34) • Ansible • PHP 7.4` to be.

Thanks for the hint with JSON and XML, I'll try to write the config with JSON in the next two days and then I'll get back to you.

Greetz

**Comment by SlvrEagle23** [comment]
@PB-SF @Vaalyn My apologies for the confusion on this one. It turns out that in fixing one problem we inadvertently created another.

Several users had reported that they were unable to configure more than one alias properly, which was because our original configuration didn't list "alias" as an array but instead as a single item; we fixed this by making it an array and making new aliases merge into that array. Unbeknownst to me, there were folks relying on the singular format (which would look exactly as your configuration does) and that broke things for them.

We want to support both and in an intuitive way, so I've made some changes to the code that will allow your code to work exactly as it previously did while also supporting multiple aliases in array format for users who prefer that. This is currently deploying to the rolling release branch and should be available shortly, at which point your stations will continue to operate as they were with no configuration changes needed.
