### ISSUE TITLE
Issue during update

### ISSUE THREAD

**Issue by ttodua** [AzuraCast/AzuraCast#4242]
@vaalyn, a minute ago I've made :
```
./docker.sh update-self
./docker.sh update
```
and during update it shows:

ERROR: In file /var/azuracast/azuracast.env: environment variable name 'catch_workers_output ' may not contain whitespace.

I've never touched .env file myself, so latest azura image might have bug there.
(using Docker installation | latest stable | ubuntu 18.04 )

**Comment by Vaalyn** [comment]
There is no environment variable in the [`azuracast.env`](https://github.com/AzuraCast/AzuraCast/blob/main/azuracast.sample.env) called `catch_workers_output` (which is in itself 
a strangely named env var, since env vars are always written in caps in AzuraCasts env files).

The only place in the repository mentioning `catch_workers_output` is the [php-fpm config file](https://github.com/AzuraCast/AzuraCast/search?q=catch_workers_output) and that one is hard-coded and not using an env var. According to the history of the file it has never used an env var: https://github.com/AzuraCast/AzuraCast/commits/8f900af32feaac426faaf37a6831f50a0ecbfd89/util/docker/web/php/www.conf.tmpl

For whatever reason you have an `azuracast.env` file that contains an env var with the name `catch_workers_output` it's not an issue on the repository since we do not have an env var like that anywhere.

Please open your `azuracast.env` file and remove this env var from the file.

**Comment by ttodua** [comment]
Thank you @Vaalyn  !  
Seems it is not bug of Azura.
strange...
