### ISSUE TITLE
Backups are non-functional

### ISSUE THREAD

**Issue by AaronUnmuted** [AzuraCast/AzuraCast#4250]
**Using Docker installation method?**
Yes / No 

**AzuraCast version:**
Rolling Release #a665c80

**Host Operating System:**
Ubuntu 20.04

**Describe the bug:**
Enabling Automatic Backups via the dashboard does not actually enable automatic backups. Once changes are saved, the tickbox is automatically unticked. Running the backup manually via the dashboard does not create the backup file in the location specified. Running from the command line DOES backup as normal.

**Steps to reproduce:**
1. Access backup management page at /admin/backups.
2. Configure automatic backups.
3. Tick "Run Automatic Nightly Backups" and set other configuration as desired.
4. Click "Save Changes".
5. Reaccess the configure automatic backups page, box is unticked.

**Expected behavior:**

Backups should be able to be enabled/disabled at will.

**Relevant logs:**
N/A - Backup runs as expected via terminal.

**Device(s):**

- Device: Desktop
- OS:  Windows
- Browser: Chrome
- Version: 90.0.4430.212 

Thank you in advance for any help or assistance!

**Comment by SC2Mitch** [comment]
Taking a quick look now!

**Comment by Vaalyn** [comment]
After some investigation I found that the setting is correctly set and (at least on my test installation) the backups them self are correctly created but in the configure page the `backup_enabled` setting is not correctly being displayed.

This seems to be caused by the [`DoctrineEntityNormalizer`](https://github.com/AzuraCast/AzuraCast/blob/main/src/Normalizer/DoctrineEntityNormalizer.php) not returning that setting in the normalized record. This has probably something to do with the recent switch from Annotation to Attributes for Doctrine entities.

Further investigation as to where exactly the normalizer fails is needed.

**Comment by SlvrEagle23** [comment]
@AaronUnmuted @Vaalyn Figured out why the normalizer is flopping on that one particular setting: while we look for property getters named like `getPropertyName` and `propertyName` (the latter being for converting `is_asdf` to `isAsdf()` boolean functions), but `isBackupEnabled()` doesn't exactly match either of those patterns, because the field name doesn't start with `is`.

Renaming the getter function to `getBackupEnabled()` fixes the issue entirely.
