### ISSUE TITLE
Space after folder name

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#427]
If you make a space after the folder name, there will be such an error

> Error: 11. Orange Marmalade - Someone.mp3{"error":{"code":404,"msg":"File or Directory Not Found"}}

**Comment by SlvrEagle23** [comment]
@susl16c This issue isn't very clear on what the actual problem here is, but I'm working locally and testing out creating folders with spaces in the folder names _and_ spaces at the end of the folder name, and both appear to work just fine, including allowing uploads into those exact folders.

In general, it's not a great idea to create folders with spaces at the end of their names, but if you're so inclined to do so, it should still work.

**Comment by susl16c** [comment]
I write the name of the folders in my language and I get such a mistake, but I do not put a space specifically, I just sometimes do not see it when the name is copied. But I did not invent the error in my docker, and I checked it several times, if the gap is all wrong.

**Comment by SlvrEagle23** [comment]
@susl16c I sincerely have no idea what's triggering this error in your case, or how to resolve it. I'm not very clear on the details of your explanation.
