### ISSUE TITLE
TuneIn support

### ISSUE THREAD

**Issue by voipworld** [AzuraCast/AzuraCast#429]
Hello Dev
if you remember i asked last time on how to use- **Installation Method:**  TuneIn with LiquidSoap
till now no luck to make it work
can you please do a config in the station profile to integrate the TuneIn API, connected to the default station mountpoint?
thanks a lot.
- **Host OS (if using Docker):** 

**Describe the issue in full detail, including screenshots if possible:**

**Comment by SlvrEagle23** [comment]
@voipworld Yes indeed, I do remember you request #270 and I've actually been working very recently on building out the necessary features to make it a possibility.

It sounds straightforward to just add the TuneIn support by itself, but I want to build out a system that's much more flexible and powerful than that; that can trigger a webhook to any remote URL, or push to Discord/Slack/etc, or post messages on social media when songs change. This webhook system is now nearly ready to start having connectors added to it, and since your request has been pending for so long I'm planning on implementing that as one of the first ones.

Feel free to follow issue #270 for progress updates, since it's still open and pending.
