### ISSUE TITLE
Unable to open the setup URL/IP

### ISSUE THREAD

**Issue by afkcodes** [AzuraCast/AzuraCast#4339]
**Using Docker installation method?**
YES

**AzuraCast version:**

**Host Operating System:**
Ubuntu 20.10

**Describe the bug:**
New to azuracast : 
I did the installation process and it went well without any errors and got this ip http://49.207.208.191/ to open but its not loading and keeps on loading and gives an error 

**Steps to reproduce:**
Just installed i dont know what to expect and was unable to open the url.

**Expected behavior:**
Just installed i dont know what to expect

**Relevant logs:**
Got no logs as  mentioned in the logs page.

**Screenshots:**
[Screenshot](https://imgur.com/a/Hkc3itd)

**Device(s):**

- Device: Desktop
- OS: Ubuntu 20.10
- Browser: Chrome/Brave
- Version: Latest

**Additional context:**

**Comment by SC2Mitch** [comment]
check the docker logs for the errors.

**Comment by Vaalyn** [comment]
Did you install AzuraCast on a hosted server that is open to the internet or have you installed it on a PC in your home network?

If you installed it on a PC in your home network the IP you are seeing is most likely the public IP of your router.
In that case you'll need to access the IP of the PC in your network instead of the one the installer is showing to you.

**Comment by afkcodes** [comment]
got it @Vaalyn i installed on my PC, so according to you i need to go to my local ip  ?

**Comment by Vaalyn** [comment]
yes, either `http://localhost` if you are using the same PC where AzuraCast is installed on for accessing the website or if you have it installed on one PC and are using a different one you should use the local IP of the AzuraCast PC.

**Comment by afkcodes** [comment]
understood, thanks @Vaalyn  & also i wanted to know how can i map it with my domain so that others can also access it ?

**Comment by Vaalyn** [comment]
You'll need a static IP address for that or a `DynDNS` service as well as opening and mapping ports on your router to make your local PC available to the internet. When using the "Web Proxy" of AzuraCast for listening to the radio you'll only need to make it available on port `80` and `443`.

It's not something that we offer support for since it is a network / server admin topic where the specific details depend on your network setup and ISP.

**Comment by afkcodes** [comment]
will try to setup on linode or digitalOcean than thanks for the help i am completely new to azuracast.
