### ISSUE TITLE
Station backend won't start

### ISSUE THREAD

**Issue by ShizzleNL** [AzuraCast/AzuraCast#437]
- **Installation Method:** Traditional @  Ubuntu 16.04 LTS

**Describe the issue in full detail, including screenshots if possible:**

Reinstalled it multiple times, I just don't know what I'm doing wrong. When I click Manage I get the following error:

`500
Named route does not exist for name: stations:util:restart
Router.php : 279`

Tried update.sh as well, didn't fix the issue.

**Comment by SlvrEagle23** [comment]
@ShizzleNL You're not doing anything wrong at all. I apologize for the error; it was something I missed in my last refactoring, where I was moving around some functionality to allow it to be called by API users.

The latest update should help with it; let me know if it fixes things.

**Comment by ShizzleNL** [comment]
Cool that fixed the error. But I'm having another error now when using a remote mountpoint (icecast).

`2018-02-17 16:52:11,754 INFO spawned: 'station_1_backend' with pid 23518
2018-02-17 16:52:11,980 INFO exited: station_1_backend (exit status 1; not expected)
2018-02-17 16:52:12,986 INFO spawned: 'station_1_backend' with pid 23519
2018-02-17 16:52:13,210 INFO exited: station_1_backend (exit status 1; not expected)
2018-02-17 16:52:15,232 INFO spawned: 'station_1_backend' with pid 23520
2018-02-17 16:52:15,459 INFO exited: station_1_backend (exit status 1; not expected)`

Couldn't find this error on any of the issues on this page, seems like I'm having some bad luck.

**Comment by SlvrEagle23** [comment]
@ShizzleNL Check the logs in `/var/azuracast/stations/{your_station_name}/config/liquidsoap.log` and see what it's saying about that error.

**Comment by SlvrEagle23** [comment]
I haven't heard any follow-up on this issue, so I don't know if the issue has been fixed or if further action is required on my end. If you don't mind, could you please update me on the status of this issue?

If I don't hear any updates for a while, I'll close the issue as resolved.

**Comment by Usalabs** [comment]
Sorry but I'm reopening it,,,, this error:- SPAWN_ERROR: station_1:station_1_backend still isn't fixed, and I've don't absolutely nothing else other than follow the install and setup instructions to the letter, oh and the instructions only show how to get it started from install to accessing the admin page, and no further.

This error appears after I have added music to folders and added them to playlists, then I clicked on the 'Ready to broadcast? Click to start station'

Actually, personally, I find all this posting, try this try that, and nothing happens, a waste of time,, it's better to run icecast2 on the server and in a windows environment, just run SAM broadcaster, connect the encoder to icecast2 and done,,, no hassles of posting this and that and trying this and that and more other stuff, that probably won't get fixed for months.

I found azuracast by searching for a streaming alternative to SAM, but after installing and reinstalling and wiping setups and configuration files, then searching for this and that when reading the instructions it should work from the git go, but it doesn't, so after 4 days of attempting to fix something that should have worked, I've decided to pay $300 for SAM and use that instead.

**Comment by SlvrEagle23** [comment]
@Usalabs After waking up this morning and seeing your post in my inbox, I was admittedly both upset and disappointed in both its message and tone. I could've just left it alone, but I feel compelled to post a small response in defense of not only myself as a developer but the entire free and open-source software process itself.

1. Above all else, it's worth noting that AzuraCast, despite all the branding, having its own GitHub organization, homepage, etc...is just me. I'm a solo developer working on this project entirely in my own free time, as a labor of love and a many-years-long pursuit of something I was personally passionate about. I think it's important for everyone to remember that, especially with a project like this one, the person on the other end of the keyboard is just that, another human being, not some corporate entity with a customer service department.

2. The back-and-forth debugging, follow-up, and replies via GitHub issues is, in fact, both a healthy and necessary part of building software like AzuraCast. There are two things that make this software especially hard to diagnose and triage problems on, one being that it's self-hosted on other people's servers (which I don't get any sort of access to as a result of the installation), and the other being that it's composed of many pieces of third-party FOSS software that I don't directly maintain, each of which may have their own eccentricities or bugs.

3. Despite the difficulty in resolving some issues, it is _never_ my goal to leave issues unfixed for any significant amount of time. I've even been working heavily this week on this exact issue, rebuilding and refining the way that AzuraCast handles these error messages under the hood, so that it can provide a precise, clear response as to what's gone wrong under the hood. I want this to be done right, and to be resolved to everyone's satisfaction, and I'm willing to put in a lot of work to make this happen, despite not only not being financially compensated for this work but fighting uphill against my own disabilities and medical conditions along the way.

4. Looking through the project's history, my records show that this is the first message that has been posted from your account, and that there is no prior GitHub issue related to your specific problem. It would thus have been impossible for me to know specifically what's going wrong in your case and on your server. While it isn't always fun to go through these long, frustrating troubleshooting processes, I still always appreciate the people who are willing to do so, as together we're making better software for everyone who follows us.

In the end, if AzuraCast doesn't work well for you and you would prefer to use commercial software, that's absolutely fine. For many years before building AzuraCast, I myself used a commercial, closed-source tool called CentovaCast to handle my broadcasting, and it was my frustration with that tool's limitations and lack of transparency that led me to build this in the first place.

I just hope that this type of message doesn't set a precedent or create unrealistic expectations in anyone who may stumble upon it. AzuraCast is a free (both as in beer and as in freedom) self-hosted option for some small to medium-scale radio stations, built by a single unemployed and disabled web developer as a labor of love, mostly to give others something useful to use but partly to give myself a continuing sense of purpose and value in the world.

If you do decide in the future that you'd like to keep trying out AzuraCast, I can promise you that if you create a new issue and follow through with the troubleshooting steps, I'll put a full effort toward resolving your issues and making the software work for you. I can't promise that you'll end up loving the software in the end, but that's okay. Open-source is about freedom of choice and we're just one of many choices out there.

**Comment by Usalabs** [comment]
OK, so I'll give it one more chance.

I understand that bugs can creep in now and again as not all computers are the same, bit, imho, the instructions could take it a bit further than just getting it up and running,,, anyway,,, here's my liquidsoap.log from my docker installation, and it says the address in use. but don't say which one,,, if it's referring to 5000, then yes it will be in use, it's the port that icecast2 uses, which does work, I tested it with a trial copy of SAM, but if it's attempting to use a hard coded port of 8000 (normal default icecast2), then it's out of luck, as ports 7000-7100, 8000-8100, and 9000-9100 is used by a virtual worlds simulation software I'm helping to develop.
[liquidsoap.log](https://github.com/AzuraCast/AzuraCast/files/2088134/liquidsoap.log)

Also, as I can login to my web access page, the station profile says it's running, but liquidsoap isn't, but the liquidsoap section says 115 songs being shuffled, but the section is in red.

**Comment by SlvrEagle23** [comment]
@Usalabs The error Liquidsoap is reporting there is that the port it's trying to listen on is already being actively used by something else on your system.

You can either try modifying the port used or check to see what else may be listening on that same range (for the initial station, that'll be 8000-8009) and change its configuration.

**Comment by SlvrEagle23** [comment]
@Usalabs Several notes here:

 - If you edit an existing post instead of making a new post, I don't get notified of the changes, so I can't respond to them; I only happened to return to this page to check up on it and saw your changes.
 - You appear to not have a base URL set, which is why the station URLs aren't working correctly. You can set this from the "Settings" page inside the system administration.
 - AzuraCast builds and runs its own instance of Icecast (specifically, Icecast-KH) and automatically starts it on the port specified in the web interface. The documentation is clear in multiple places that AzuraCast installs and "comes with" the full suite of radio software.
 - The series of random numbers after the `?` in the stream URL are the current UNIX timestamp; this is appended to the URL as a "cache busting" mechanism, as some browsers don't correctly detect that the URL is a streaming web radio source and instead try to pull an older, cached version of the audio, and this prevents that.

Seeing as how none of this has anything whatsoever to do with the issue in which these posts appear, I'm closing this issue again.

If you have any further questions, feel free to create them as new issues. Remember to keep topics to one per issue, rather than piling multiple topics into one post.

**Comment by efeefe** [comment]
Hi @SlvrEagle23 thanks for the effort, I've been looking for a webradio solution for some time now. I have installed Azura in a digitalocean droplet, and am also having the same "SPAWN ERROR" message in the web interface. My liquidsoap.log is attached. Any clues?

[liquidsoap.log](https://github.com/AzuraCast/AzuraCast/files/2157606/liquidsoap.log)

**Comment by DocTator2281** [comment]
This thread helped me as well, was working with an ansible installation where the backend didn't want to start for whatever reason. According to liquidsoap logs the master_me compression was the culprit. Turned that off and everything was swell.
