### ISSUE TITLE
Why restoring takes twice the storage space of the backup file

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraCast#4407]
**Using Docker installation method?**
Yes
**AzuraCast version:**
Latest

**Host Operating System:**
Ubuntu 20.04

**Describe the bug:**
I am wondering why it takes twice the amount of space to restore a backup.zip file. And it would even be triple the size if the backup file is strored on the server where we restore it from

To my understanding, the backup file is decompressed to a cli_backup.zip and then this cli_backup.zip is decompressed to the destination folders. at the end of the process the cli_backup.zip is deleted to free up some space.

In my case, I have a 450GB HDD
A 216GB backup file is located on another server folder which I mount on my Azuracast server. I fire the backup restore command and after few hours the installation failes with (no storage space error).

is there a workaround I could do ?

**Comment by SlvrEagle23** [comment]
@griffon56 Originally, the fact that we did that first copy into the Docker filesystem was a permissions issue, but we've since refined things in that regard by implementing PUID/PGID support...it may be worth re-evaluating how we're doing the backup restores by removing one level of abstraction.

It would still mean that backups temporarily use _twice_ the space (for the extracted content and then the backup itself), but I'm not aware of any way to extract a file while simultaneously whittling down its contents to zero for space-constrained setups.

**Comment by griffon56** [comment]
@SlvrEagle23 many thanks for your fast feedback - for me your proposition would indeed solve my problem - and since my backup file is stored on another server I would need just the space of the extracted content if I understand correctly

**Comment by SlvrEagle23** [comment]
@griffon56 I've had a chance to look into how we do the backup/restore process and I was able to identify a way we could "shuffle" the same backup file around, basically moving it into and out of the Docker volume ecosystem, without duplicating the file size.

This should significantly expand the number of stations that can use the backup feature without worrying about space constraints, and the number of backup restores that aren't hampered by a disk space issue.

In my own testing, everything works perfectly with this new script, though I'd encourage you and others to test it out and help verify that it works as expected.
