### ISSUE TITLE
Problem when installing Azuracast

### ISSUE THREAD

**Issue by PinguiFabgeeklab** [AzuraCast/AzuraCast#4411]
**Using Docker installation method?**  Yes

**AzuraCast version:** Last version (release)

**Host Operating System:** Ubutnu 18.04

**Describe the bug:** When i'm trying to install Azuracast, I got this error : "ERROR for redis : Cannot start service redis : OCI runtime create failed container_linux.go:380: starting container process caused: process_linux.go:5                                                        45: container init caused: write sysctl key net.core.somaxconn: open /proc/sys/net/core/somaxconn: no such file or directory: unknown

**Steps to reproduce:** When running the command "./docker.sh install"

**Additional context:**

**Comment by Vaalyn** [comment]
It looks like you are trying to install AzuraCast in an unprivileged LXC container which is not supported as it is not directly compatible with Docker.

See our docs entry about [known incompatibilities](https://docs.azuracast.com/en/getting-started/requirements#known-incompatibilities).

You'll need to make sure to use a real VM instead of a LXC container.

**Comment by PinguiFabgeeklab** [comment]
Resolved. I deleted the line that referred to "Somaxconn" in docker-compose.yml
I could then install AzuraCast. Thanks you for help.
