### ISSUE TITLE
[Bug]: Paused/resumed stream doesn't jump to live stream

### ISSUE THREAD

**Issue by clutch4caroline** [AzuraCast/AzuraCast#4438]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#ec88ed7

### What happened?

When resuming a paused stream, it will play from the paused point, instead of live playback. The only way to jump to a live feed is by refreshing the source.

**Comment by SlvrEagle23** [comment]
@clutch4caroline Using what player? The public player? We've done quite a lot of work with our own player to ensure that doesn't happen, but it may happen with other player implementations.

**Comment by clutch4caroline** [comment]
@SlvrEagle23 The player this issue is present on is a *relay stream*.
The public page is indeed working correctly, we're using the relay stream on a third party site.
[](https://radio.upyourweb.co.uk/radio/8060/live)

**Comment by SlvrEagle23** [comment]
@clutch4caroline It's likely the error is in the implementation of the player on the other site, then. With streaming MP3s, you can't just embed a regular audio element, because then pausing/playing does exactly what you're seeing, where it resumes from the point when you paused and there's no way to get back to "live" state. Our implementation deletes the audio element entirely when it's stopped, which forces the browser to recreate it on the next playback.

**Comment by clutch4caroline** [comment]
I'll look into it with our dev, thank you so much for the speedy and helpful response :)
