### ISSUE TITLE
DJ Account, wrong password every time

### ISSUE THREAD

**Issue by TorchwoodPL** [AzuraCast/AzuraCast#444]
- **Installation Method:** Traditional
- **Host OS:** Ubuntu 16.04

**Describe the issue in full detail, including screenshots if possible:**

I try to use Mixx for live brodcast, but every time I try to connect to my radio I get wrong username/password. Port 8005 is open, I use Icecast on my server.

**Comment by SlvrEagle23** [comment]
@TorchwoodPL Try
```
tail -f /var/azuracast/stations/{{your_station_folder}}/config/liquidsoap.log
```

while logging in to see what it says the error message might be. It may be possible to determine the fix just by looking at that, or you can paste it here and I can take a look.

**Comment by TorchwoodPL** [comment]
There is no any error message in file :(

**Comment by SlvrEagle23** [comment]
@TorchwoodPL Make sure your "Streamer/DJ Port" on the station's profile matches the one you're trying to connect to, or if you're using Shoutcast 1, connect to that port number +1. If it's not showing anything in the log, then it's not getting any request to connect at all.

**Comment by TorchwoodPL** [comment]
@SlvrEagle23 
http://img.hyeah.pl/pic/121519666250.png and http://img.hyeah.pl/pic/171519666274.png

And event that there is no entry in log file...

**Comment by TorchwoodPL** [comment]
@SlvrEagle23 any more idea whats wrong?

**Comment by SlvrEagle23** [comment]
@TorchwoodPL Unfortunately I can't figure anything else out without looking at the installation itself. I believe you had contacted me before via Keybase, so feel free to contact me again there with updated information for the install.

**Comment by RemBdev** [comment]
Maybe you have illegal characters in your password.

**Comment by TorchwoodPL** [comment]
@RemBdev password have only capitals normaln leters and numbers, nothing more.

**Comment by SlvrEagle23** [comment]
Detailed explanation of the issue here, for the curious:

This user was using the traditional installation method (bare metal install on Ubuntu 16.04). Rather than running AzuraCast as the sole web site hosted on the server, they opted instead to host multiple sites with varying virtual hosts, with AzuraCast importantly _not_ the default domain served by nginx.

For Liquidsoap to communicate with AzuraCast, it has to make internal API calls back and forth to the service, and previous to this, it relied on the fact that `http://localhost` would route correctly to the AzuraCast instance as long as the "don't install anything else on this server" rule was adhered to. In this case, it wasn't, and there was no other hosting option, so alternatives in the code were evaluated.

In the end, the older CLI-based Liquidsoap<->AzuraCast communication protocol was pulled back into use, and aligned such that the same API commands could be called either via the URL-based API (used by Docker installations, as AzuraCast and Liquidsoap run on different containers there) or the CLI-based one, which was restored into service for traditional installs.

Normally I wouldn't make such sweeping exceptions in the code to a single user's problems, but I had actually had some reservations about relying on `localhost` to be a reliable pointer toward AzuraCast in the first place, and I had suspected that this might have caused other hard-to-diagnose errors for other users. In this case, many of the CLI commands already existed and were in use prior to the switchover, so bringing them back was rather simple overall.

**Comment by BartManX** [comment]
> Detailed explanation of the issue here, for the curious:

This user was using the traditional installation method (bare metal install on Ubuntu 16.04). Rather than running AzuraCast as the sole web site hosted on the server, they opted instead to host multiple sites with varying virtual hosts, with AzuraCast importantly not the default domain served by nginx.

For Liquidsoap to communicate with AzuraCast, it has to make internal API calls back and forth to the service, and previous to this, it relied on the fact that http://localhost would route correctly to the AzuraCast instance as long as the "don't install anything else on this server" rule was adhered to. In this case, it wasn't, and there was no other hosting option, so alternatives in the code were evaluated.

In the end, the older CLI-based Liquidsoap<->AzuraCast communication protocol was pulled back into use, and aligned such that the same API commands could be called either via the URL-based API (used by Docker installations, as AzuraCast and Liquidsoap run on different containers there) or the CLI-based one, which was restored into service for traditional installs.

Normally I wouldn't make such sweeping exceptions in the code to a single user's problems, but I had actually had some reservations about relying on localhost to be a reliable pointer toward AzuraCast in the first place, and I had suspected that this might have caused other hard-to-diagnose errors for other users. In this case, many of the CLI commands already existed and were in use prior to the switchover, so bringing them back was rather simple overall.


so what about those of us that have only
AzuraCast v0.8.1-2018.02 Beta (Traditional)
PHP 7.2.2-3+ubuntu16.04.1+deb.sury.org+1, SlimPHP 3 installed on a fresh VPS .. i cant connect with any broadcast software but i have no problem streaming playlist from the AzuraCast web interface?

**Comment by SlvrEagle23** [comment]
@BartManX This is likely a different, unrelated issue to this ticket, and should be created as a new issue, since this one's already been resolved and closed.
