### ISSUE TITLE
Add Email and Author support for RSS pages

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#4447]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

N/A

### What happened?

A user reported in discord that they was unable to link their RSS feed on Google Podcast and Spotify due to missing Author and Email headers. 
![image](https://user-images.githubusercontent.com/29955942/128099305-359dbc50-59ab-4536-8d69-d977bca7c51c.png)

**Comment by balancedwolf** [comment]
It still does not work with latest rolling release, is it possible that this change hasn't been released yet?

**Comment by Vaalyn** [comment]
> It still does not work with latest rolling release, is it possible that this change hasn't been released yet?

Thank you for reporting that it is still not working with Spotify.
I have checked why this is since the previous fix added the `itunes:owner` fields to the feed and I found that there is a `itunes:author` field that iTunes doesn't require but that Spotify does require.

I have created a fix for this (see the PR above).
When this is merged and the docker image built would you mind checking out if you notice any further issues?
