### ISSUE TITLE
Playlist stops playing after a minute when start and end time are equal and "Interrupt other songs to play at scheduled time" is on

### ISSUE THREAD

**Issue by leonardder** [AzuraCast/AzuraCast#4477]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #6c39311 (2021-08-10 16:14)

### What happened?

I had a playlist planned for 19.00 which I intended to play fully once. The end time was set to 19.00 as well. The GUI indicates that this is necessary to make a playlist play only once. However, at 19.01, the playlist instantly ceased to play. I also had the `Interrupt other songs to play at scheduled time` option enabled`. Could this be related and an unexpected side effect of the latter option??

**Comment by leonardder** [comment]
Nope, I don't. Here are my settings:

* Basic info
    * Type: General rotation
* Schedule
    * Start time: 19.00
    * End time: 19.00
    * Loop once: enabled
    * Days: Wednesday
* Advanced
    * Interrupt other songs to play at scheduled time: Enabled
    * Only loop through playlist once: enabled

**Comment by Abqehebter** [comment]
```
Advanced
Interrupt other songs to play at scheduled time: Enabled
Only loop through playlist once: enabled
```

These are the Liquidsoap settings that are not supported. Try it without. So deactivate them as a test.

**Comment by Vaalyn** [comment]
> The GUI indicates that this is necessary to make a playlist play only once

This is only true when using the AzuraCast AutoDJ. When using any of the options in the `Advanced` tab you will be using Liquidsoap itself for the scheduling. This can lead to it automatically transitioning to the next schedule / playlist when the configured end time has been exceeded.

If you can live with the possibility of a slight delay for the start time (for example at 18:58 a 3 min track starts playing your scheduled one for 19:00 will start at 19:01) you should deactivate these 2 Advanced options:

- Advanced
  - Interrupt other songs to play at scheduled time
  - Only loop through playlist once

Since using Liquidsoap itself for the scheduling gets complex fast and and can be tricky to get right we don't offer much support for it and are working on implementing those advanced options into the AzuraCast AutoDJ when possible.
The "Loop Once" option for example was a recent addition that functionally replicates what the "Only loop through playlist once" is doing so that it's not necessary to use the advanced option for this anymore.

**Comment by leonardder** [comment]
I'll have a look, thanks for the ideas.

**Comment by leonardder** [comment]
I tested this with the advanced settings disabled and it wors like a charm now.
