### ISSUE TITLE
Unable to upload files, returns permission error

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#4529]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

Currently on the latest rolling release  https://github.com/AzuraCast/AzuraCast/commit/e23158f270801fd7121fb8d2e46cf58e6de4ba3c, I tried to upload some files to my station and it returned a permission error, my account has the Super Admin permission. I created a test account which had the station only permissions and that still returned a error.

**Comment by Vaalyn** [comment]
Most likely caused by the new requirement for every API call to have an active session as well as a CSRF token.
From a cursory glance I think the Flow File Upload does not send a CSRF token in the chunked requests headers (not sure if single chunk would be any different, but doubt it).

For other API requests this seems to be working since the integration of the default `X-API-CSRF` header on the Vue Axios.
My guess is that the FlowUpload component does not use the same Axios and thus does not know about the CSRF token.
