### ISSUE TITLE
Access denied for user 'azuracast'

### ISSUE THREAD

**Issue by uoziod** [AzuraCast/AzuraCast#4571]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling release #0.14.1

### What happened?

For some reason DB isn't accepting connections. Neither when I try to connect via cli directly in the container. 

### Relevant log output

```shell
2021-09-14 20:11:28 337 [Warning] Access denied for user 'azuracast'@'172.19.0.6' (using password: YES)
```

**Comment by uoziod** [comment]
Clean reinstall with all containers and volumes removal seems to be fixed the problem

**Comment by bilalbox** [comment]
Sorry to reopen this, but I experienced the same thing upon performing a simple update. However, I think the reason was because I accidentally performed the update from ~ using:
```
root@iq-azuracast:~#
root@iq-azuracast:~# /var/azuracast/docker.sh update-self
New Docker utility script downloaded.
root@iq-azuracast:~# /var/azuracast/docker.sh update
```

INSTEAD OF

```
root@iq-azuracast:~# cd /var/azuracast
root@iq-azuracast:/var/azuracast#./docker.sh update-self
New Docker utility script downloaded.
root@iq-azuracast:/var/azuracast#./docker.sh update
```

After new install and being completely non-functional, I just reran the `docker` commands from the correct directory and the update went smoothly and DB access appears to be resolved.

### Installation Method
Docker Installation

### AzuraCast Release Channel
Stable Channel

### Current AzuraCast Version
`Rolling Release #8954be6 (2022-01-30 20:07)`!! <--- running update from ~ appears to have switched my release channel.

### What happened?
I saw the same logs as @uoziod when running `docker logs MARIADB_CID`

**Comment by SlvrEagle23** [comment]
@bilalbox Mind making a new issue for this? I believe this is something we can correct for in our Bash script to ensure that wherever it's run from, it'll jump to the correct directory.

**Comment by bilalbox** [comment]
@SlvrEagle23 as an alternative, what do you think about minimizing the opportunity for user error by sticking this behind a button in the UI as suggested in [this feature request](https://features.azuracast.com/suggestions/50468/easyupdating)? I was thinking that perhaps an extra container with limited write privileges to the /var/azuracast directory could be enabled with a tiny node/php API tied to the `update` and `setup-release` ops that could be called by a button/menu in the Vue app. It could be triggered to refresh the page every 30-60 seconds to confirm when the update completed. Does that make sense? If so I can put together an issue on that, otherwise I can proceed with creating the simpler feature request for a modification to the bash script.

**Comment by SlvrEagle23** [comment]
@bilalbox I don't consider that an alternative to this issue...yes, we could rewrite our entire update procedure to have it be web-based, but that undertaking is a lot larger of a project than simply fixing the current working directory on our existing utility script. Also, given the way Docker permissions are, it's not clear that this would be a simple process at all, and it may be impossible for us to do unless we give ourselves full Docker socket access, which exposes us to security risks we're thankfully able to avoid in our current setup.

**Comment by bilalbox** [comment]
Totally understandable regarding scope and security concerns. I've opened new issue #5058 for enhancing the bash script.
