### ISSUE TITLE
log delete paste

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#4573]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #e408420 (2021-09-14 16:41) • Docker • PHP 8.0

### What happened?

Some folders are missing from my music files.
Some folders are missing from my music files.
I tried to get the azuracast log and the station's own log and I didn't find any information in the log that says I ran a command to delete folders from the music files. How can I search the system for something that indicates that a command to delete folders was run?

### Relevant log output

```shell
not
```

**Comment by Vaalyn** [comment]
Changes to a `StationMedia` entity are not logged in the `Audit Log` in the Administration so there is probably no way to find out who deleted something from the music files. It might be a good idea to make those auditable so that this can be done in the future. I've created a feature request to keep track of this: https://features.azuracast.com/suggestions/214420/log-station-media-changes-in-the-audit-log

**Comment by Marcioghiraldelli** [comment]
Thanks.
