### ISSUE TITLE
Play music from youtube

### ISSUE THREAD

**Issue by efsysefsys** [AzuraCast/AzuraCast#462]
Hello :) It is a pleasure that the project was developed.Maby u can add option to play / stream music from youtube links? :) or play youtube channel playlist etc.Something like that.

**Comment by susl16c** [comment]
Yes, parsing music is a very interesting idea

**Comment by mkody** [comment]
Doing this would be against YouTube's ToS and AzuraCast can't say fetching the content directly from YT would be for "personal use". This is a big problem for music licenses and won't support creators and labels.

If you want to get content from YouTube, you should download them __yourself__ at your own discretion (i.e. with [`youtube-dl`](https://rg3.github.io/youtube-dl/)) and upload the files.

**Comment by SlvrEagle23** [comment]
@efsysefsys @susl16c I was planning on fishing up the relevant policy articles on YouTube's site, but @mkody beat me to the punch of the essential rundown on why we can't/shouldn't be in the business of doing this:

1) It's very likely against YouTube's TOS, especially since we can't demonstrate that the intended use is noncommercial and, for many radio stations, may even involve royalty payments for music downloaded from YT, which is a big nope

2) There's a basic principle at play here that radio stations are nothing without the musicians that produce the content that goes on them, so you should always be making your best effort to support those musicians by buying their albums. Not only does this help ensure the content for your station keeps flowing, but it often also entitles you to far better downloads, like lossless FLAC files or very high-rate MP3/AAC/Ogg files, which play a lot better on the radio anyway.

AzuraCast is meant to do one thing, and do it well: let you spin up and manage what plays on radio stations. We don't want to muddy the waters of the project by introducing music acquisition as part of that.

**Comment by tropimega** [comment]
estoy tratando de insertar audios en azuracast y no se puede, por mas que arrastro o cargo desde mi pc, no se adhieren, alguien me de una respuesta, muchas gracias

**Comment by SlvrEagle23** [comment]
@tropimega Support for AzuraCast is provided in English, so you should translate your request into English. Also, the issue you're responding to has been closed, so you should create a new one.
