### ISSUE TITLE
Playlist (sequential order vs shuffle)

### ISSUE THREAD

**Issue by amavarick** [AzuraCast/AzuraCast#465]
Docker
Ubuntu 16.04.4 LTS

1.  Would you consider adding an option to your list for sequential playlist.
2.  If not, would you assist me with the custom command necessary to set mode="normal" to my playlist using the custom playlist option?

I'm not sure if this would be associated with #455 if so, please advise and I'll close this.  I just recently created a radio that plays an audio book of sorts that has multiple tracks.  It requires playing sequentially.  I don't see the option in the GUI playlist choices.  I have experience using Liquidsoap and Icecast together and creating liq files.  My understanding is that adding
`mode="normal"`
or in its simplist form:
`playlist(mode="normal", "/my/pl.m3u")`
to my Liquidsoap configuration file would make it sequential instead of shuffling.

I see the custom playlist option at the bottom but don't know the rules regarding its use to integrate custom commands.

![image](https://user-images.githubusercontent.com/20918832/36940374-b0d69624-1f0f-11e8-9bb8-acbca275e2ed.png)

Example Liquidsoap configuration file I've used for non-Azuracast deployments...

```
#!/usr/bin/liquidsoap
# Log dir
set("log.file.path","/tmp/liquidsoap_default.log")

# Music
myplaylist = playlist(mode="normal","/home/default.m3u")
myplaylist = audio_to_stereo(myplaylist)
# Some jingles
jingles = playlist("/home/jingles")
# If something goes wrong, we'll play this
security = single("say:We're currently experiencing technical difficulties.  Please try again later.")

# Start building the feed with music
radio = myplaylist
# Now add some jingles
radio = random(weights = [1, 4],[jingles, radio])
# And finally the security
radio = fallback(track_sensitive = false, [radio, security])

 # Stream it out
output.icecast(%mp3(bitrate=24),
  host = "localhost", port = 8000,
  password = "xxxxxxxxxxxxxx", mount = "default_autodj.mp3", public=false, name="default", description="Default Radio", genre="Default Genre",url="http://stream.mydomain.tld", radio)
```

**Comment by SlvrEagle23** [comment]
@amavarick Your question is certainly valid, but unfortunately AzuraCast is really not set up for sequential playlists at all. It would require a whole new development project to redesign the playlist management tools such that they allowed for easy sequential editing.

Nonetheless, if you want to implement your own custom playlist, you're on the right track. Creating a "Custom Playlist" type writes a playlist file to the disk with any changes that are made to a playlist, but doesn't automatically integrate it into LiquidSoap or into AzuraCast's "playing next" functionality.

Basically, it works like this: if your playlist is named `My Favorites`, then AzuraCast will write the playlist's contents to `/var/azuracast/stations/your_station_name/playlists/playlist_my_favorites.m3u` and will register a variable in liquidsoap called `playlist_my_favorites`.

In your case, since this default variable doesn't have the "normal" mode you need, it _should_ be a matter of redefining the variable yourself in the custom Liquidsoap config, like so:

```
seq = playlist(mode="normal",reload_mode="watch","/var/azuracast/stations/your_station_name/playlists/playlist_sequential.m3u")
radio = random(weights=[4, 1], [radio,seq])
```

Custom LiquidSoap configuration always falls after the rest of the radio station is built, but before the broadcast is sent out to the frontends, so you'll always have a `radio` variable with the rest of the station defined and ready to use.

Hopefully you can produce a working solution out of these bits of information. Let me know if you have any other questions.

**Comment by SlvrEagle23** [comment]
@amavarick I'm consolidating a number of playlist-related enhancements into a more technical-oriented project management issue where I can track the progress on the changes, so feel free to follow that: #480
