### ISSUE TITLE
error update

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#4702]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

very old version

### What happened?

error 1
when it appears
status up azuracast service
is waiting and after error1 and the update does not end

### Relevant log output

```shell
when it appears
status up azuracast service
is waiting and after error1 and the update does not end
```

**Comment by Marcioghiraldelli** [comment]
but can you tell me what kind of problem might occur that might prevent reboot?

**Comment by Marcioghiraldelli** [comment]
Can someone help me ?

**Comment by Vaalyn** [comment]
Was resolved through Discord.

Due to a MariaDB crash log from an older version the newer MariaDB version could not start since it couldn't process the old format of the crash log. We've added a note to our docs on how to resolve this: https://docs.azuracast.com/en/user-guide/troubleshooting#innodb-upgrade-after-a-crash-is-not-supported

Closing issue as fixed.
