### ISSUE TITLE
Override Preffered Port and Password on Creating neew stream

### ISSUE THREAD

**Issue by Yusadolat** [AzuraCast/AzuraCast#471]
- **Installation Method:** 
- **Host OS (if using Docker):** 

**Describe the issue in full detail, including screenshots if possible:**
Azuracast override ports and password for shoutcast stream

 

After all deep research to know if i was the one that did something wrong i finally detected that the system override  the password, Port I choosed to use when creating the stream, Is there a way to work around it?

**Comment by SlvrEagle23** [comment]
@Yusadolat Thank you for the report. It turns out this is a widespread issue that would've affected any newly created station on the system. The radio frontends generate some "default" configuration (i.e. they will automatically make a new password for you, if one isn't specified), but that default configuration was overwriting the one users actually specified in the station creation process.

While I'm surprised this wasn't reported sooner, it's fully resolved now, and newly created stations should retain any custom port information or passwords you provide in the creation form.
