### ISSUE TITLE
The public player shows the wrong time

### ISSUE THREAD

**Issue by nktfh100** [AzuraCast/AzuraCast#4721]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #1b426c2 (2021-10-21 15:25) • Docker • PHP 8.0

### What happened?

While making my own player for my website I tried getting the actual time of the current song (using the 'played_at" from the api)
And I noticed the player was showing the wrong time
I am not sure what's causing this, but it appears this is also happening in the demo page
Another thing - most of the time the player just shows 00:00 for the current song in my radio and the demo (even inside the admin page)

Here I am just using the 'elapsed' time from the api
You can see it shows the actual time for the song which is very different compared to what's shown in the player
![image](https://user-images.githubusercontent.com/23655815/138550471-3e48faeb-68a4-457d-8d40-d6881dce0883.png)

Here you can see the song changing (notice that the player gets stuck on 00:00 after that)
https://imgur.com/UVb28BP

**Comment by fnfzlznddzn** [comment]
> It seems that my computer was a few minutes late and that was causing it

thank you so much for finding the cause of this issue and writing it here... such a weird and unexpected thing, i was going mad trying to understand why every song was starting at 1:30 on my radio... turns out my windows was 1:30 late, I needed to sync the time

**Comment by BusterNeece** [comment]
So, for all these years we've based the "elapsed time" counter on the player display on the client time, under the assumption that most folks' time would be accurate "enough" for this purpose. This was partly skewed by my tendency to test from my own machine, where the time will of course always match, so I never noticed much of an issue.

I've made some changes in the latest, currently-deploying Rolling Release version so we pull the current time from the AzuraCast server itself, so even if either the server or the client time are wrong, since the source of time truth comes from the same place in both cases, the elapsed time is relative to the server time, which means they line up much more closely. If you use the high-performance EventSource service for Now Playing updates (can be enabled via System Settings), it's almost _exact_, down to the millisecond, in my testing.
