### ISSUE TITLE
Many dashboard vue-errors

### ISSUE THREAD

**Issue by Abqehebter** [AzuraCast/AzuraCast#4738]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #3c8e7c4 (2021-10-27 15:37) • Docker • PHP 8.0

### What happened?

Hi,
I noticed that the developer console gives quite a few error messages. Also, I'm missing the Now-Playing display of the respective station under "various":
![image](https://user-images.githubusercontent.com/42640247/139108199-727c3856-57c0-4a22-a5bc-09c82ef0d971.png)

**Comment by MrXeflo** [comment]
It seems to be something within the translation system that's causing these errors and that's also why the now playing widget and the autodj widget are missing.

I updated to the latest rolling release today and the same errors appeared after the update. The temporary workaround for this is to change your language to English till it's fixed. Once set to English, everything works fine and no errors appear in the dev console.

**Comment by Abqehebter** [comment]
@MrXeflo Thank you for the workaround! ;)

**Comment by SlvrEagle23** [comment]
Thank you @Abqehebter and others for the reports; this one was a little trickier to pin down, so it took a few days to figure out, but I was able to track it down to the fact (that I didn't realize at the time) that the JavaScript side of the application expects singular/plural translations to be in an array assigned to the singular translation, not with the plural translation as is typical of, say, gettext translation files.

This has been fixed in the latest rolling release version that's currently deploying, and I can confirm in my local tests that this fixes the multitude of Vue errors for users of other languages.
