### ISSUE TITLE
Shoutcast Port range (81 - above) not working

### ISSUE THREAD

**Issue by Yusadolat** [AzuraCast/AzuraCast#475]
- **Installation Method:** 
- **Host OS (if using Docker):** 

**Describe the issue in full detail, including screenshots if possible:**
I started testing out Azuracast this week and decided to test all features before using for production, So I started creating multiple streams. The system started picking ports from 8000 with ten interval but on getting to port 8100 above the stream couldn't connect. I'm I doing anything wrong?
please help look at it.
Thanks

**Comment by SlvrEagle23** [comment]
@Yusadolat The answer to your question can be found in the sample `docker-compose.yml` file's comments:

https://github.com/AzuraCast/AzuraCast/blob/84c5d1c8b02ceb762b83b3d4167075e3d4e7d050/docker-compose.sample.yml#L119-L121

Because Docker consumes a small amount of RAM for every single port you forward, by default AzuraCast only forwards the ports that would be needed for the first 10 stations, assuming that most installations on Docker reasonably won't exceed this limit.

It's no problem if you do, though; you can either just keep adding ports to that list in exactly the same format as the existing ones (so, make sure you add xxx0, xxx5 and xxx6 for broadcast, modern DJ connections and legacy DJ connections, respectively), or you can uncomment the line that's commented in the code to expose the whole range all at once. Be warned, though: at about 1MB per port forwarded, this will consume a large amount of RAM. This is due to a long-standing issue with the Docker userland proxy, and once that's fixed we won't have to worry about these types of problems.

**Comment by Yusadolat** [comment]
And after modifying the port , I got this error on running docker compose up -d 

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 12] Cannot allocate memory
fatal: [localhost]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

**Comment by Yusadolat** [comment]
And after modifying the port , I got this error on running docker compose up -d 

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 12] Cannot allocate memory
fatal: [localhost]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
