### ISSUE TITLE
Letter case of song names

### ISSUE THREAD

**Issue by zloysystem** [AzuraCast/AzuraCast#4760]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #fc8a2ae (2021-11-07 8:20)

### What happened?

Good day gentlemen!
When loading tracks through the web interface, I noticed that the case of letters changes to small, through sftp everything is ok, I filled in 2 identical files and you can see the difference)
![IMG_20211109_024640](https://user-images.githubusercontent.com/26243386/140836235-9a31c224-5d87-48ec-96d7-4bdbeb94a297.jpg)
![IMG_20211109_025023](https://user-images.githubusercontent.com/26243386/140836468-31f161bf-ae9b-4052-b4c3-8ed137ae3cc7.jpg)

**Comment by SC2Mitch** [comment]
checking this out today thanks for the report

**Comment by SlvrEagle23** [comment]
I can confirm locally that as part of our filesystem sanitization process, we do convert all file names to their lowercase equivalents, to avoid issues with case-sensitive filesystems.

Most users aren't using case-sensitive filesystems, though, so the question exists as to whether this is a worthwhile optimization for us to be doing, or whether it causes more trouble than it's preventing, especially since we already allow direct SFTP uploads in any case and don't filter those paths currently.

I have no strong opinion on this either way. @Vaalyn, thoughts?

**Comment by Vaalyn** [comment]
> I have no strong opinion on this either way. @Vaalyn, thoughts?

I don't think we get much value out of converting the file names to lowercase, it's not a security measure, when using SFTP this is not done at all and having them change to lowercase can be confusing for users. I think we should remove this part of the filesystem sanitization.

> Most users aren't using case-sensitive filesystems
I think you meant most users aren't using case-insensitive filesystems since most distributions of linux are by default using case-sensitive filesystems. Example from my test server Ubuntu 20.04:

![image](https://user-images.githubusercontent.com/13745863/143516675-e5c966c4-13c3-4e9c-895d-fd178d6ccae0.png)

As far as I know S3 Object Storage Keys (which are the file names) are also case-sensitive.

**Comment by SlvrEagle23** [comment]
@Vaalyn Sorry, yes, that's what I mean. And correct, the casing isn't to do with security at all. Will likely publish an update shortly removing it.
