### ISSUE TITLE
Silence on the stream (Buffer)

### ISSUE THREAD

**Issue by RemBdev** [AzuraCast/AzuraCast#482]
- **Installation Method:** Traditional
- **Host OS (if using Docker):** Ubuntu 16.04

Hi,

I'm using Azuracast with live DJ's. If a DJ connects to the stream the first 10 seconds are silent. In this 10 seconds the server is buffering the Live DJ-stream (I guess).

My questions:
1. Is it possible we hear hear the AutoDJ when the stream buffers the live-dj?
2. Is it possible to decrease the time of the silence on the stream?

Greetings!!

**Comment by SlvrEagle23** [comment]
@RemBdev Some streaming software seems to need the 10-second buffer to keep from dropping out all the time...but I have no problem making it user-configurable in the station profile settings.

**Comment by RemBdev** [comment]
Well with an older version of AzuraCast i was using a 320kbps stream and i had a delay of 2 seconds. (Now i am on 128kbps)

**Comment by SlvrEagle23** [comment]
@RemBdev I've updated the station profile page to have the DJ buffer be user-configurable, so you can set it to the lowest value that still allows your DJs to connect and have smooth broadcasts while minimizing the delay when a DJ first connects. There's not much I can do about that trade-off otherwise, though.

**Comment by RemBdev** [comment]
Thanks!

**Comment by zarankumar** [comment]
@SlvrEagle23 when we create DJ and Stations via API , how we configure DJ/Streamer Buffer Time (Seconds).? May i know the field name.
