### ISSUE TITLE
Error in public pages with Firefox

### ISSUE THREAD

**Issue by fidegr** [AzuraCast/AzuraCast#4901]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

Public page player stops after a few seconds of playback in firefox browsers. In Chrome and other browsers it seems that everything works correctly. Where can the failure come from?

**Comment by stathismor** [comment]
I am having that issue as well, seems to be the same with #4731

**Comment by hcbd** [comment]
I have also noticed this issue, 

This has something to do with the firefox <audio> tag and buffering
If you open a direct link to your stream in a new tab, for example: yourradio.com/radio/8000/radio.mp3
hit play, it should work fine (you would see the total duration of the file going up). 

If you now reload the page (hit F5 or crtl+F5), the stream behaves as a file in your mediaplayer starting the audio at 0 and the total duration of the song is now the duration it had when hitting refresh; Firefox plays the stream from it's cache or buffer and then just stops when it reaches the end of the song in it's buffer. Sometimes this just overwrites parts of the audiobuffer, makes you hear the current song for 2 sec and then the buffer for 2 sec. 

This seems like a Bug in Firefox

I'm also guessing this can be mitigated by javascript on the playerpages, clearing/resetting the buffer and reloading the source on each init of the player.

It gets better if you disable the networkbuffer in Firefox
within the page on Firefox rightclick => inspect => goto networktab => find a small checkmark called "disable buffer"

**Comment by SlvrEagle23** [comment]
I was under the impression that, in the latest generation of browsers, this issue was fixed across the board and they were well aware of the concept of streaming MP3s and could handle them without issue (as Chromium and its derivatives can).

That's part of the reason why we took the appended timestamp off of all of our stream URLs in the system: partly because they caused confusion for our users, but also partly because they were believed to no longer be necessary.

I'll look into this issue and see about possibly bringing that functionality back in some form for Firefox users.
