### ISSUE TITLE
Place all the backend services in a dedicated network

### ISSUE THREAD

**Issue by Julien00859** [AzuraCast/AzuraCast#493]
I don't really like having 20th ports open on my host, from a security perspective it would be better to place the databases (influxdb, mariadb, redis) and the backend (stations) in dedicated networks isolated from the host, leaving the frontend (nginx) the only service running accessible from the host and so the internet.

[Networking in Compose](https://docs.docker.com/compose/networking/)

When #491 will be solved and I succeeded to run AzuraCast, I'll look around to do it and send a pull request :wink:

**Comment by SlvrEagle23** [comment]
By default, even with the current setup, all of the internal services used by AzuraCast are not exposed to the web explicitly unless this is configured in the `docker-compose.yml` file. Only ports 80/443 for nginx and select ports in the 8000-9000 range are forwarded to the external network. Creating distinct internal networks would not aid in reducing the external surface area of the application, as it's already reduced to only the essential ports by its current design.

Furthermore, since the same Docker Compose structure is used by developers for local testing and staging, we _want_ it to be possible to forward a MariaDB, Redis or InfluxDB connection through to the local host for testing and debugging purposes. Isolating them in a separate network would make this process more difficult, again without actually improving the sensible default port forwarding security of the application.

I've also ensured that even if a user decides to uncomment my "for developers only" lines in `docker-compose.yml`, they're actually only having those services listen to connections coming from the host computer itself, rather than the web at large. This allows debugging via SSH terminal or tunneling to the host computer, which is typically all that is needed for these scenarios. Considering the lengths that AzuraCast goes to to ensure the underlying database services are protected by default, and still protected even when using developer customizations, I think this is largely a non-issue.
