### ISSUE TITLE
ON UTF-8 and ISO-8859-1

### ISSUE THREAD

**Issue by SpeedyCharly** [AzuraCast/AzuraCast#4937]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#6838ddf (2021-12-29 22:47)

### What happened?

Reported before on difficulties with UTF-8 and LS supporting French custom characters. At the time, I also noted that the very same metadata was transcribed correctly in ShoutCast.  Yes, we're on Shout, not Ice; this to accommodate our djs.

Thus, I thought that switching autoDJ from UTF-8 to ISO-8859-1 (going full Legacy) would solve the problem, as AzuraCast documentation seems to indicate. 
![Image4](https://user-images.githubusercontent.com/66107794/147845378-a139de01-8f20-405a-b177-7499908f6ccc.jpg)

But, lo and behold, nothing happens quite as expected in the IT world! After doing the restart to apply the change, I immediately noticed something strange; the 'Profile' page modules were no longer reporting properly;
![Image1](https://user-images.githubusercontent.com/66107794/147845485-4e406218-622c-43df-8de1-aeeeded242a4.jpg)

Public page display was also frozen but songs were still playing through normally;
![Image1 1](https://user-images.githubusercontent.com/66107794/147845673-a7c96cba-cf3b-4b74-827f-0de00d1dedd3.jpg)

Song queue was also weirding out; 
![Image5](https://user-images.githubusercontent.com/66107794/147845692-3a446567-fe4f-49a7-b54c-1b3e1da4f420.jpg)

But LS and the server were still running correctly as evidenced by ShoutCast page and our chatroom ;
![Image3](https://user-images.githubusercontent.com/66107794/147845748-157acbc9-ed19-49bc-9f5c-e6497fdc6e7c.jpg)

Neither rebooting the server nor restarting the broadcast helped with this.  The only way out of this mess was to reset back to UTF-8, restart AzuraCast, then clear the song queue. Normal operation resumed fine after that.

I'm assuming this bug was never reported on before because we're probably one of the rare stations working both in French and on ShoutCast...

### Relevant log output

```shell
Scanned logs which showed nothing untoward in the relevant time frame... all operations normal
```

**Comment by SpeedyCharly** [comment]
Why isn't this issue being answered?

**Comment by SC2Mitch** [comment]
we are currently trying our hardest to focus on higher priority issues that impact a large amount of users i.e liquid soap, functionality and more, just be patient and don't post "why isn't this being answered". 

we too are humans and have priorities and remarks like this simply aren't need.

regards

**Comment by SC2Mitch** [comment]
We **very much would welcome** contributions to resolve this issue, at the moment we have higher priority issues to resolve, namely with liquid soap and usages. 

I'm not here to argue because I don't have the energy anymore. We're tired, we have literally zero other contributors apart from the two core development team members. 

Just stop fighting against us and complaining stuff isn't fixed yet, please help us instead fix the issue

**Comment by Vaalyn** [comment]
Tested this on a SHOUTcast DNAS v2.6 station with AutoDJ set to use the `Character Set Encoding` setting `UTF-8` as well as `ISO-8859-1` and both times it worked without any problems and the upcoming song queue did not freeze. See screenshots below for tests with a song with a French and Japanese title / artist.

If you can upload a song that shows these problems on your installation I can check with those again.
Without a file that causes this behaviour there is nothing I can do at the moment.

### French
<img width="97" alt="image" src="https://user-images.githubusercontent.com/13745863/155141009-b19e6e4f-fc92-4058-8229-ab95a550596d.png">
<img width="190" alt="image" src="https://user-images.githubusercontent.com/13745863/155141054-e0a098b4-7fe0-4756-a14b-35c73c4b3e78.png">


### Japanese
<img width="103" alt="image" src="https://user-images.githubusercontent.com/13745863/155139986-1f14f9ee-c8f3-46c9-bc64-e6930b22d6f5.png">
<img width="187" alt="image" src="https://user-images.githubusercontent.com/13745863/155140083-542c1a4f-444a-4064-8552-04d1f0c45089.png">

**Comment by SpeedyCharly** [comment]
Ok it seems you haven't read my earlier posts on the problem... I stated earlier that these error codes are seen in Azuracast and displayed on the pubic page player but the ShoutCast server and the bot of our chatroom reading the same metadata were both displaying correctly...

**Comment by Vaalyn** [comment]
I have, as well as the thread on the LS repo and instead of trying to lecture me you could have just uploaded the file I asked for so I can try to reproduce it with that since as you can see in my screenshots umlauts as well as completely non-ascii character do work correctly with AzuraCast + SHOUTcast so this is 99.9% down to the metadata in the files you are playing.

Not gonna try helping you again in the future, not worth my time trying to get the information I ask for.

Have fun figuring it out by yourself then.

**Comment by SpeedyCharly** [comment]
I can't provide the file I mentioned in the post because it was part of a live stream by a dj and I don't have access to his puter.  All I can do is observe autodj operations and provide you with files I actually have access too when they are identified.  Don't quite understand your testiness with this...

**Comment by SlvrEagle23** [comment]
@SpeedyCharly The only way we can really reproduce this file is if we have the test files ourselves to play with. We have lots of examples of other Unicode files working without any issue, which is why we suspect it may be some other part of the stack that isn't working correctly in this case.

We're all just a little at the end of our ropes because it doesn't appear that you've been very patient with us.

**Comment by SpeedyCharly** [comment]
@SlvrEagle23 I can understand you would need some of the problem files to investigate the problem but I fail to understand Vaalin's expectation that I could provide him, in no time flat, with a file that sits in a third party's puter and accusing me of lecturing him in the same pronouncement when he's the one citing 'proof' that was earlier discussed as irrelevant; waste of his and my time...

**Comment by SpeedyCharly** [comment]
Just finished scanning 3 days of logs and the camomile transcoding errors only happened during live broadcast, so I would be hard pressed to provide you with problem files as I can't force operators to provide them...

**Comment by SpeedyCharly** [comment]
Was finally able to ident 4 typical files that I can provide you with.  What is the best way to upload them to you?

**Comment by SpeedyCharly** [comment]
Lack of activity wasn't from my end....

**Comment by SlvrEagle23** [comment]
@SpeedyCharly Again, unnecessary tone of voice in your message.

**Comment by SpeedyCharly** [comment]
Simple statement of fact... I spent considerable time trying to find files suitable for testing and last comment remained unanswered...

**Comment by SlvrEagle23** [comment]
@SpeedyCharly It worries me that you sincerely don't realize when you're being condescending or abusive toward people.

I will not debate this with you. You have spent so much of me and my team's time already, so much more than you could've ever paid for.

**Comment by SC2Mitch** [comment]
Going to close this, your attitude towards our team has been nothing but disgusting, we've spent more than enough time on you and all we've gotten back is attitude, snarky posts, if you want this issue fixing, make a pull request, have a good one. 

Not going to debate, since I can't be bothered with it, I believe the others share the same remarks.
