### ISSUE TITLE
Numeric URL stubs for stations are treated as IDs leading to 500 station not found errors

### ISSUE THREAD

**Issue by zloysystem** [AzuraCast/AzuraCast#4943]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #0cc3008 (2021-12-30 19:56)

### What happened?

Good day gentlemen!
The public page and embedding of widgets do not work on newly created stations.(Slim Application Error)

### Relevant log output

```shell
Failed to load resource: the server responded with a status of 500 ()
```

**Comment by SlvrEagle23** [comment]
@zloysystem We need the details of the error. You should be able to pull it from the AzuraCast Application Log in the `Log Viewer` from system administration.

**Comment by ivellios1988** [comment]
Did you activate public pages?

**Comment by zloysystem** [comment]
@SlvrEagle23 I kind of understand that the whole point is in the url stub, it does not change and, accordingly, the public page and all other widgets become inaccessible

**Comment by zloysystem** [comment]
@ivellios1988 Yes, sure

**Comment by SlvrEagle23** [comment]
@zloysystem Can you please explain in greater detail? I don't know what to look for or what to fix.

**Comment by zloysystem** [comment]
@SlvrEagle23 https://gifyu.com/image/SSGTl
and tails from remote stations remain somewhere

**Comment by Vaalyn** [comment]
This issue is caused by the differentiation between numeric and alphanumeric station identifiers here: https://github.com/AzuraCast/AzuraCast/blob/main/src/Entity/Repository/StationRepository.php#L36-L41

A station that is using a completely numeric url stub is treated as if you are trying to access the station with the database ID `666` (taken from the example in your gif).

@SlvrEagle23 we should think about if it makes sense to allow the URL stub of a station to be comprised of only numerics since differentiating them from database IDs is pretty much impossible. I mean, how are we supposed to know if the user wants to access for example station id `10` or the station with the stub `10`.

**Comment by SlvrEagle23** [comment]
@Vaalyn I'd propose that if someone sets a short name that's entirely numeric, that we prefix it with something like `station_` to ensure that it always parses as a string and doesn't collide with auto-increment IDs.

Personally, I'd love if we didn't allow using numeric IDs in public-facing APIs _at all_ since it allows folks to "brute-force guess" the public stations (not that this is entirely valuable, but possible all the same), but that would be a back-compatibility break.
