### ISSUE TITLE
.wma files are "semi-ignored" ?

### ISSUE THREAD

**Issue by LazosPlaying** [AzuraCast/AzuraCast#495]
- **Installation Method:**
Docker

- **Host OS (if using Docker):**
Ubuntu 16.04

**Describe the issue in full detail, including screenshots if possible:**
.wma files are being ignored ?? 😭 
They are shown on "Playing Next" (profile page), but are just ignored and another song from the playlist directory is picked, which is in .mp3

**Comment by SlvrEagle23** [comment]
@LazosPlaying WMA is Windows Media Audio, a proprietary audio format owned and built by Microsoft. Since AzuraCast is built on free and open-source software (in this case, most importantly Liquidsoap), there are no libraries available to decode that audio format.

A broad variety of music file formats are supported by our software stack, including MP3, Ogg Vorbis, AAC, and FLAC. Using WMA files is neither recommended nor supported.

**Comment by LazosPlaying** [comment]
alright.

**Comment by frecuencialibre** [comment]
it would be great to somehow indicate this during the file upload process. currently files appear to upload and be available, but then surprisingly don't play.

**Comment by aljaxus** [comment]
Well yeah, they are actually uploaded, but as explained above, the system can not decode them. but... This is GitHub, so you can simply contribute with your piece of code ^-^
