### ISSUE TITLE
My station streams won't speak.

### ISSUE THREAD

**Issue by nkcho** [AzuraCast/AzuraCast#4960]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

Rolling Release #abaa4a0 (2022-01-06 2:29)

### What happened?

I have 2 installs: 1 on an IP address linked to a domain name but without SSL enabled and the other has SSL enabled.
I have linked the stream from winamp via the shoutcast plugin.
The public pages on both show-up, but when played, no sound is heard, though they are constantly being updated by the stream from my PC.

Any fix please???

**Comment by SC2Mitch** [comment]
Can you link your public page and some liquid soap logs? Might be helpful for us.

**Comment by nkcho** [comment]
Greetings, sorry for the late response.
Here is the link: https://azuracast.checkam.info/public/miya_academy 
I will like to give you access to the project admin page, can I get an email, or you can request here: chonkarimbi@gmail.com

**Comment by SC2Mitch** [comment]
@nkcho 

I have since checked your API and done some checks myself. 

It appears that your instance is using a IP address and a domain, the IP address uses the `listen_url` field and the domain is the `public_player_url`. Can you double-check your server is using the domain, instead of the IP address? This can be configured in the system settings.

**Comment by nkcho** [comment]
Yes I linked the IP address to a domain name and enabled SSL to the server so as to broadcast and stream safely as per the requirements in my country.
So how do I go about resolving this issue in settings.

**Comment by nkcho** [comment]
Please how can I proceed to fix this?
Any suggestions or I can grant access to the account for fixing.

**Comment by SlvrEagle23** [comment]
@nkcho There are two options:
 - You can try to get your SSL certificate up to date on the :8000 port, which would involve going to your station, then `Utilities`, then clicking `Restart Broadcasting`; or
 - You can go to `System Settings` and check the box that says `Use Web Proxy`, which will update all your stream URLs to use the main web service instead of their direct ports.

Either should fix this problem.

**Comment by nkcho** [comment]
I did both and now it works like charm!
So cool, big thanks.
I will definitely support the project
