### ISSUE TITLE
Scheduled Playlist never plays

### ISSUE THREAD

**Issue by orllewin** [AzuraCast/AzuraCast#4962]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #abaa4a0 (2022-01-06 2:29) • Docker • PHP 8.1 

### What happened?

I've not managed to schedule a playlist to play at a specified time successfully, I've tried with all possible variations.

The current setup which seems as simple as can be:

A `default` playlist to play random files when no other playlist is scheduled, type is `General Rotation` and `Include in Automated Assignment` is checked, this happily plays audio all day long.

A sequential playlist with the name `orrs001` and type 'General Rotation', it has a schedule setup with start time and end time of the same time and the current date for start and end date. It has `Loop once` checked.

`orrs001` has never kicked in, every time it fails I change the start and end time to now + say 10 mins, and wait, and the general rotation tracks just play instead, nothing ever happens. So currently I have `orrs001` scheduled to play at 14:30 and the station profile has the 'Scheduled' card displaying with `Playlist orrs001 2:30 PM - 2:30 PM  in 7 minutes` - so the web interface is correct and is expecting the playlist to jump in - but it just never happens.

I've scoured the docs but can't see anything I'm doing wrong. There's no advanced playlists settings used. My expectation would be that at the specified time the scheduled playlist would fade in and whatever general rotation track playing at the time would fade out.

**Comment by Abqehebter** [comment]
See: https://github.com/AzuraCast/AzuraCast/issues/4952 & https://github.com/AzuraCast/AzuraCast/issues/4938
Seems like several have this problem.

**Comment by orllewin** [comment]
I restarted via docker.sh then went to /admin/debug the clicked 'Clear cache' and 'Clear all message queues', then rescheduled the playlist and it kinda worked, it's only playing one of the 3 tracks in the playlist, odd, but I'll experiment and see if I can find out more.

One more problematic thing is the existing general rotation track played out before this scheduled playlist started, is that correct behaviour? Ideally it should fade out any general rotation tracks so the schedule playlist plays at an accurate time, I have some 10+ minute tracks in the general rotation pool, so if a ten minute track happens to start at 13:59 and my playlist is scheduled for 14:00 it won't actually start until 14:09 - that can't be right?

**Comment by orllewin** [comment]
hmm, no, there's something really broken here. I created a new playlist with 8 tracks in marked as sequential and loop once, and scheduled it for 19:10, it came in early at 19:08 when a general rotation track finished, but it played the _second_ track only, now a default playlist track is up next... so wrong time, wrong track, and it's missed 7 other tracks!

**Comment by Abqehebter** [comment]
Yep. I'm together with @SC2Mitch figuring out what exactly is going on. But yes: I have your error also on the latest rolling release.

**Comment by SC2Mitch** [comment]
Ill provide some detailed debug logs either today or tomorrow to help review this situation. Thanks for your patience.

**Comment by SC2Mitch** [comment]
I'm currently unable to replicate this anymore on my local nor production machine, here's my full summary of logs and explanations. 

A few things that must be noted. 

If a playlist is scheduled for 12:00 PM and a song is currently playing from 11:59 to 12:01 it may cause some overlap and cause a minor overlap but it should queue the playlist accordingly. These things are incredibly hard to debug and it involves multiple stations which I must crawl through thousands of logs to review, this is painstakingly difficult and involves an enormous amount of time reviewing. Time is limited on my hand. 

While I'm unable to reproduce this on my own machines, this does not devalue the bug report you've provided. I'm confident its indeed valid, but it comes back to us trying to narrow down the issue which leads us to bashing our heads against a brick wall to resolve it. We've remade the AutoDJ more times than I can count and it works for us in testing and on production machines. We get extremely limited amounts of reports of Scheduled Playlists. 


**Machine Specifications**
Ubuntu 20.04 LTS (Docker Stable) 
Windows 11 (Docker Latest) 
Stations tested 4 on local, 15 on development. 

**Playlist Information**
Playlist Weight - 3 (Default)
Avoid Duplicate Artist (ENABLED) 
Playlist Type (GENERAL ROTATION) 
Gneration Rotation (DISABLED)
Schedule time `#1` START TIME: 12:00 AM - 12:59 PM (UTC) 
Source: Song Based
Song Based Playback (SEQUENTIAL - ALLOW REQUESTS FROM THIS PLAYLIST) (HIDE METADATA FROM LISTENERS DISABLED)
Advanced Settings (NONE) 

**Playlist Queue Order**
![image](https://user-images.githubusercontent.com/29955942/148666198-a76d6df6-e3eb-471e-bb43-c5c2e24e6cc9.png) 

**Upcoming Song Queue** (CHECKED AT 01:50 AM) 
![image](https://user-images.githubusercontent.com/29955942/148666193-3a84550d-a8fe-4418-b26a-0a716acc3456.png)
Mountain of logs
https://gist.github.com/SC2Mitch/16122632a8cbb280edd636888f2c8a77

**Comment by Abqehebter** [comment]
We had already written about it.
This really makes the whole thing more difficult. You can see the deviations of the actual Sequential playlist in the screenshots.

The song queue is really swallowed up by me, there is a song from the "default" playlist in it and some songs repeat themselves here unfortunately.

It is planned to run from 02:57 AM GMT+1 to 03:57 AM GMT+1 and it should loop once.

![image](https://user-images.githubusercontent.com/42640247/148667595-18739d65-07cd-4820-9dcd-8981af9a0b24.png)

**Song Playback Timeline**
![image](https://user-images.githubusercontent.com/42640247/148667343-95c43d36-e62b-4c33-8353-5165cd57dd29.png)

**Playlist Queue Order**
![image](https://user-images.githubusercontent.com/42640247/148667504-09ecd289-11e1-40b7-96b2-aefcc5ebcc4c.png)
![image](https://user-images.githubusercontent.com/42640247/148667520-09eef747-616f-4edb-8b92-692b4dcfa66d.png)

**Comment by Abqehebter** [comment]
I'm doing a little more debugging on this time-controlled one right now, and I've noticed a little something.

In the first screenshot here you can see the normal control of the song queue. But even here it already starts to queue a song again that is currently playing.

I suppose the song queue shoots itself out of line. That would also explain where the duplicate artists come from (See Issue: https://github.com/AzuraCast/AzuraCast/issues/4948)
That's why you can't reproduce the whole thing so cleanly, because you don't have a log button for these "not fixed scheduled songs" either.

I hope I can help a bit more with this.

---

I added the current Now Playing display to the respective Song Queue screenshots above, so you know what was played during that time.

**Måneskin - Beggin'**
![Screenshot_1](https://user-images.githubusercontent.com/42640247/148686280-07efcd29-f480-4728-8881-2fa63b9ceef7.jpg)
**The Weeknd - Save Your Tears**
![Screenshot_2](https://user-images.githubusercontent.com/42640247/148686453-0f6ee53d-730a-4cb5-a9c3-a6dfbfd83b8b.jpg)
Furthermore **The Weeknd - Save Your Tears** and after that the START_AD_BREAK should come.
![Screenshot_3](https://user-images.githubusercontent.com/42640247/148686456-d2d030f5-983c-4e55-94d3-aa56b616aae9.jpg)

After the START_AD_BREAK came the song **Wellerman** which was already played once according to the Song Playback Timeline (see below).
**Now Playing Display on Station-Profile at 3:14 PM**
![Screenshot_4](https://user-images.githubusercontent.com/42640247/148686436-916de190-739b-462a-a153-f895dfd45bfe.jpg)

**Song Playback Timeline**
![Screenshot_5](https://user-images.githubusercontent.com/42640247/148686417-78769a85-bcce-4f26-9896-8d2751cb553c.jpg)
