### ISSUE TITLE
Unable to play the preview of a song

### ISSUE THREAD

**Issue by PinguiFabgeeklab** [AzuraCast/AzuraCast#4976]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #2fabeed

### What happened?

I'm unable to play a preview of all the songs who are in my files.

We can see the stop button but not the duration bar and there is no sound.

https://i.imgur.com/2uNiXRt.png

**Comment by SC2Mitch** [comment]
Confirming as of the latest stable version, browser logs indicate this error
`Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().`

**Comment by SC2Mitch** [comment]
Confirming as of the latest stable version, browser logs indicate this error
`Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().`

Can you check if your server is using an IP address and domain at the same time? I believe this may be somehow related.

**Comment by PinguiFabgeeklab** [comment]
I have this error with Firefox : Uncaught (in promise) DOMException: The media resource indicated by the src attribute or assigned media provider object was not suitable.

How I Can check this ?

**Comment by SlvrEagle23** [comment]
I'm unable to reproduce this locally as of the latest Rolling Release version.

**Comment by PinguiFabgeeklab** [comment]
Problem persists with the lastest Rolling Release version when I access to AzuraCast with the IP Adress of my server.

**Comment by SC2Mitch** [comment]
Here's a video repro, might be useful to debug what's going wrong here. (The IP is my local IP) *It has since changed dont worry about it*

**Comment by PinguiFabgeeklab** [comment]
> Here's a video repro, might be useful to debug what's going wrong here. (The IP is my local IP) _It has since changed dont worry about it_ https://streamable.com/ryswfi

Same problem.

**Comment by SlvrEagle23** [comment]
This may be due to a host mismatch, which may be caused by the Base URL not being the same URL as the one you're visiting right now.

@SC2Mitch Does enabling "Prefer Browser URL" in system settings resolve the issue? Also, if you set it to the IP, then visit the AzuraCast installation using the IP, does it still fail to play?

**Comment by SlvrEagle23** [comment]
In my local tests, this is exactly why it happens: you're logged in on `localhost`, but not `127.0.0.1` or whatever your IP is, and since that session login cookie only transfers over between same-site origins, if you look at the "Network" tab for that request, you basically see it's just redirecting the media playback command to the login page on that IP.

The "Prefer Browser URL" setting fixes all of this by ensuring the two always line up. Lately, it's been a default _enabled_ setting for a while, because having it disabled caused a whole mess of problems just like this one.

**Comment by SC2Mitch** [comment]
Has this been resolved for you @PinguiFabgeeklab ? Mine is sorted.

**Comment by PinguiFabgeeklab** [comment]
Yeah, has been resolved when "Prefer Browser URL" setting is activated. Thanks you
