### ISSUE TITLE
download backup

### ISSUE THREAD

**Issue by fast97** [AzuraCast/AzuraCast#5041]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

download backup
my question is not great but where is the backup zip file generated by azuracast? can't find it in /var/azuracast/backup/ folder as shown. trying to download it after 5 minutes the download stops. Thank you

**Comment by SC2Mitch** [comment]
Hi there

When you configure your backups, you can pick a location, the default is `/var/azuracast/backups`, can you try here? 

If the download is failing, make sure the connection to the server is stable, or download it via an FTP client connected to your server, also things to note that the `/var/azuracast/backups` isn't the path. It's within the Docker Volume containers in `/var/lib/docker/volumes/azuracast_backups/_data)

Otherwise you can check this for your file storage location: 
![image](https://user-images.githubusercontent.com/29955942/151634889-ccf105d7-54f2-4315-a241-4e27a8063a15.png)

**Comment by fast97** [comment]
hello thank you for the answer but I did not find anything on the server even a find command does not find me my backup and yet it is there .. the path leads /var/lib/docker/volumes/azuracast_backups/_data 
me to an empty folder
![az2](https://user-images.githubusercontent.com/51033222/151635666-c54d829f-e2f7-45bf-a2a3-d98ad38d1090.png)


![az1](https://user-images.githubusercontent.com/51033222/151635663-b88e60fc-1a6f-4214-837a-d72337967bca.png)

**Comment by SC2Mitch** [comment]
Can you check your storage location, click on Backups and see where it's pointed at?

**Comment by fast97** [comment]
![cap25](https://user-images.githubusercontent.com/51033222/151636189-44fbe1e3-ffd1-42c4-981e-739fc87dc39d.png)
![cap26](https://user-images.githubusercontent.com/51033222/151636191-dd46b648-5b94-4895-87ed-42625c9ff60f.png)
while writing the path I have a message of non authorization

**Comment by SC2Mitch** [comment]
Can you try and edit the path in `backups` in the Storage Location and change it to `/var/azuracast/backups` and try to run a backup? 

To find your files, run this command in your terminal, make sure you have the required permissions (sudo) `find / -name "automatic_backup_20220127_033806.zip"` or whatever your backup name is.

**Comment by fast97** [comment]
Ok it's good I found my 2 files. Thank you for your help, I close this dialog.
