### ISSUE TITLE
Announce new update doesn't show in dashboard

### ISSUE THREAD

**Issue by FleuryK** [AzuraCast/AzuraCast#5048]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #aecf6c9 (2022-01-29 20:39)

### What happened?

Hello.

For some updates on rolling release, an announcement indicated that an update is available in dashboard.
But now this update announcement is no longer displayed.
Obliged to go to Github to check if there are updates.

Can you look at why it does not work anymore?

### Relevant log output

```shell
N/A
```

**Comment by SC2Mitch** [comment]
Valid issue, tested on local machine and production one, update checks aren't being completed properly

**Comment by zloysystem** [comment]
for a week or a little more I have been following updates only here, the panel is also not displayed)))

**Comment by SpeedyCharly** [comment]
Same issue on my install...

**Comment by Vaalyn** [comment]
@SlvrEagle23  the central update service thinks my test installation which is on `Rolling Release #aecf6c9 (2022-01-29 20:39)` doesn't need to be updated and it looks like the central service doesn't even know about the 0.15.0 release:

```
{
    "needs_rolling_update": false,
    "rolling_updates_available": 0,
    "rolling_updates_list": [],
    "needs_release_update": false,
    "current_release": "0.14.1",
    "latest_release": "0.14.1"
}
```

Looks like something on the central service is borked in regards to the list of commits / releases.

**Comment by SlvrEagle23** [comment]
@Vaalyn That one was fun! Turns out there's a difference between an "Annotated" and a "Lightweight" tag in Git; GitKraken historically created lightweight ones without ever presenting the option for an annotated one, but VSCode uses Annotated ones by default. Annotated tags point to their own SHA hash with extra metadata attached, and then _that_ SHA hash points to the parent commit, so it's just one more lookup step.
