### ISSUE TITLE
DJ password not recognized

### ISSUE THREAD

**Issue by SpeedyCharly** [AzuraCast/AzuraCast#5049]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #2bdc261 (2022-01-28 1:33)

### What happened?

DJ's password was refused on first login attempt, which is odd because such passwords are pre-programmed into the SAM encoder module and not entered manually.  In the log below, the pw is refused on first attempt, but readily accepted seconds later on second attempt.

As you well know, DJs are also authenticated on every metadata switch calls (which I scratch my head at) and the system will sometimes return a 401 error on the pw which obviously the operator hasn't changed on the fly.  On such occasions, the DJ gets booted from the stream and has to login again... Is there a means to do away with such annoyances?

### Relevant log output

```shell
022/01/30 18:01:03 [harbor:4] New client on port 8006: 23.233.186.249
2022/01/30 18:01:04 [lang:3] dj_auth: Sending AzuraCast API DJ Auth command for user: TiDan
2022/01/30 18:01:04 [lang:3] API auth - Sending POST request to 'http://web/api/internal/1/auth' with body: { "password": "EDITED", "user": "TiDan" }
2022/01/30 18:01:06 [lang:3] API auth - Response (522): 
2022/01/30 18:01:06 [harbor:4] ICY error: invalid password
-----------------------------------
	<< Invalid password???? >>
-----------------------------------
2022/01/30 18:01:19 [harbor:4] New client on port 8006: 23.233.186.249
2022/01/30 18:01:20 [lang:3] dj_auth: Sending AzuraCast API DJ Auth command for user: TiDan
2022/01/30 18:01:20 [lang:3] API auth - Sending POST request to 'http://web/api/internal/1/auth' with body: { "password": "EDITED", "user": "TiDan" }
2022/01/30 18:01:21 [lang:3] API auth - Response (200): true
-----------------------------------
	<< Same durn PW acccepted this time... >>
-----------------------------------
2022/01/30 18:01:21 [harbor:4] Method: ICY, uri: /, protocol: ICY
2022/01/30 18:01:21 [harbor:4] Header: icy-name, value: La Radio des Festivals.
2022/01/30 18:01:21 [harbor:4] Header: icy-genre, value: Various.
2022/01/30 18:01:21 [harbor:4] Header: icy-url, value: http://www.festivalstlouis.ca.
2022/01/30 18:01:21 [harbor:4] Header: icy-irc, value: #audiorealm.
2022/01/30 18:01:21 [harbor:4] Header: icy-icq, value: NA.
2022/01/30 18:01:21 [harbor:4] Header: icy-aim, value: NA.
2022/01/30 18:01:21 [harbor:4] Header: icy-pub, value: 1.
2022/01/30 18:01:21 [harbor:4] Header: icy-br, value: 128.
2022/01/30 18:01:21 [harbor:4] Header: content-type, value: audio/mpeg.
-----------------------------------
```

**Comment by Vaalyn** [comment]
The error message from Liquidsoap is quite confusing. According to the `API auth - Response (522)` the actual reason was a connection timeout when Liquidsoap was asking the internal AzuraCast API if the user / pw is valid.

@SlvrEagle23 maybe we should increase the timeout for the DJ auth API call from 2s to like 5s to prevent a badly timed auth attempt from failing (for example when at that moment a background task is consuming a lot of resources or a lot of media is being processed.

For Devs here a [link](https://github.com/savonet/liquidsoap/blob/499befcaf6296b9f65fe74bd0f573db8c798dc83/src/builtins/builtins_http.ml#L170) to the 522 error response from the LS http module.
