### ISSUE TITLE
System Debugger not able to force sync tasks to run

### ISSUE THREAD

**Issue by Vaalyn** [AzuraCast/AzuraCast#5050]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #aecf6c9 (2022-01-29 20:39)

### What happened?

When running a sync task from the System Debugger page (for example the `CheckUpdatesTask` before the time threshold has passed) it will not be run since the task is not called with the `$force` parameter set to `true`.

We should add a parameter `bool $force = false` to the `runTask` method here: https://github.com/AzuraCast/AzuraCast/blob/8954be61a201d0b62e70206880f773566c9854ce/src/Console/Command/Sync/SingleTaskCommand.php#L57

Use the parameter in the call to `$taskClass->run()` here:
https://github.com/AzuraCast/AzuraCast/blob/8954be61a201d0b62e70206880f773566c9854ce/src/Console/Command/Sync/SingleTaskCommand.php#L81

And finally supply a `true` to the `$taskCommand->runTask()` call here:
https://github.com/AzuraCast/AzuraCast/blob/main/src/Controller/Admin/DebugController.php#L106

as well as here:
https://github.com/AzuraCast/AzuraCast/blob/main/src/Controller/Admin/DebugController.php#L110

### Relevant log output

```shell
-
```

**Comment by SlvrEagle23** [comment]
@Vaalyn When I rewrote the task manager, I specifically made it so if you directly call the `SingleTaskCommand` it executes without any lock checks, as though "force" mode was set to `true` in the previous sync setup. The lock management is handled by the worker class, not the individual tasks (which isn't invoked at all during the manual debugger task runs), so that it can extend the locks as needed.
