### ISSUE TITLE
HD filling up fast

### ISSUE THREAD

**Issue by Marcioghiraldelli** [AzuraCast/AzuraCast#5051]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #8954be6 (2022-01-30 20:07) • Docker • PHP 8.1

### What happened?

hello, I have a 500gb HD using azuracast and for some time now it has filled up quickly.
Looking for the reason today, I realized that there is an azuracast container in which each one takes more than 100 gb.
would be container/diff/tmp and container /merged/tmp

My doubt is if I can clean this folder without causing problems to azuracast.

https://cdn.discordapp.com/attachments/647149735991443467/937705248431149126/Screenshot_742.png

### Relevant log output

```shell
hello, I have a 500gb HD using azuracast and for some time now it has filled up quickly.
Looking for the reason today, I realized that there is an azuracast container in which each one takes more than 100 gb.
would be container/diff/tmp and container /merged/tmp

My doubt is if I can clean this folder without causing problems to azuracast.

https://cdn.discordapp.com/attachments/647149735991443467/937705248431149126/Screenshot_742.png
```

**Comment by SlvrEagle23** [comment]
@Marcioghiraldelli Where exactly is this folder, and is its entire contents these `metadata` strings?

Do you have any custom Liquidsoap configuration you're using?

I haven't seen any examples of a file like this filling up the temp directory, but if we can figure out why that's happening we can correct for it.

**Comment by SC2Mitch** [comment]
I believe it was discussed in detail on our Discord, the paths was something like `/var/lib/docker/overlay2/4eb7fecae1970c0330897740db0b1a5c980a3cdf6783c6236e899f8d15ab857d` then within the `diff/tmp` and `merged/tmp` respectively

**Comment by Vaalyn** [comment]
I think we had traced it down to the `/tmp` directory inside the `web` container which contained lots of files with a naming scheme like this: `metadata_xxxxxxx`. They should be removed after a reboot of the container via `docker-compose down && docker-compose up -d` but I wasn't able to find out were those would be coming from since I couldn't see anything in our code that creates temp files like this.

**Comment by SlvrEagle23** [comment]
@Vaalyn @SC2Mitch @Marcioghiraldelli Any idea what the contents are of any one of these files? That may give us some idea what's creating them...

**Comment by Vaalyn** [comment]
@SlvrEagle23 Sorry, since I haven't seen them on my test server yet I'm not exactly sure about this.

The only parts that are sounding at least somewhat similar are the calls to the following function in our code but this doesn't explain why they have no file extension after the filename so this is like a veeeeery uncertain guess from my side.

```php
$jsonOutput = File::generateTempPath('metadata.json');
$artOutput = File::generateTempPath('metadata.jpg');
```

@Marcioghiraldelli if you haven't rebooted your containers yet, would you mind copying some of those files and provide them to us so we can take a look at them? I forgot to ask about this when I looked at this with you in Discord =/

**Comment by Marcioghiraldelli** [comment]
so, going back to this problem, I did what you asked, it cleared the space, but it filled up again with the same problem, the cpu is on top and it only fills the HD space.
It took me a while to answer you because I was doing other tests.
the problem of filling up the space on the HD remains.

**Comment by Marcioghiraldelli** [comment]
I ran the requested commands, and even ran a ./docker.sh update and nothing worked, it cleaned the HD but within 2hrs it filled up again.

**Comment by SlvrEagle23** [comment]
@Marcioghiraldelli You're on the latest rolling-release, right, not the latest stable?

Are you certain that it's these little metadata files that are filling up your hard drive? The system should only generate an incredibly small amount of them (and delete them automatically when it's done), and the files should be empty, so the notion that they're filling up your hard drive quickly doesn't make as much sense.

**Comment by Marcioghiraldelli** [comment]
I'm using Powered by AzuraCast • Rolling Release #7870205 (2022-02-04 2:30) • Docker • PHP 8.1

so I saw together with ItsMitch and Vaalyn the folder, we looked inside linux and we saw together that the folder that fills inside the container are two.

/diff/tmp and container /merged/tmp

but I didn't see the contents of the files, if you want I can check.;
Remembering that when I run docker-compose down it doesn't even complete and gives an error.

Then I can reupload the azuracast when I run a docker.sh update

**Comment by Vaalyn** [comment]
@SlvrEagle23 since the `/tmp` directory is not a volume or mount I suspect that each of those little files is causing docker to create a "diff" from the `/tmp` of the original docker image. Which might be bigger than the small files themself. Haven't verified this assumption yet but I read something in that direction while researching this issue back when we looked at his servers directories.

**Comment by SlvrEagle23** [comment]
@Vaalyn In any case, we shouldn't be creating those `metadata` files any more (the ones that get created but never used and never removed), so the filesystem should just be immediately cleaning those up.

**Comment by Marcioghiraldelli** [comment]
another thing that I notice in this version the queue part still has problems, it starts to fill the queue and I limit it to mount with only 3 files.

And don't let me clean.
https://prnt.sc/26oy3op

**Comment by Marcioghiraldelli** [comment]
if you need some log or copy of something I try to do here,.
