### ISSUE TITLE
azuracast install aws

### ISSUE THREAD

**Issue by zloysystem** [AzuraCast/AzuraCast#5082]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

Good day gentlemen, I can't install azracast on amazon aws ec2 for test work in any way, I opened all outgoing and incoming ports using all protocols, up static ip addresses, the installation goes without errors, but after that I can't get into the panel via the web or to the server via ssh for reasons unknown to me, I ping on all ports, but there is no access to it, maybe there is experience installing on amazon, please tell me, I've already broken my whole head, also tried to install on oracle and also unsuccessfully)
ubuntu 20.04.3 LTS

**Comment by SC2Mitch** [comment]
This seems to be a issue with Amazon's web services and not one with us if you cannot gain access via SSH. Reach out to Amazon to see what assistance you can get.

**Comment by SC2Mitch** [comment]
Generally we've had people complain and have filed issues in the past, while we do support Ubuntu 20 and 18 series, we can't possibly guarantee it'll work out of the box with Amazon Web Services

I understand its frustrating but since we don't have any logs, and the fact you mention you can't access the SSH to provide some logs this will be very hard to diagnose the root issue, this is why I refer you to Amazon Web services support who can possibly assist you on accessing the SSH.

Perhaps when the team has more time we can look to offer a dedicated Amazon marketplace offering that'll work out of the box, but that's for the future.
