### ISSUE TITLE
How to install stable version 14?  Updating to stable version 15 damaged all my previous install

### ISSUE THREAD

**Issue by hecgua** [AzuraCast/AzuraCast#5089]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

15

### What happened?

Updated to version 15 and when restarting, all the liquidsoap instances went crazy, started to consume a lot of CPU and provoked a lot of audio interruptions.

Please help, need to go back to stable14 version ASAP.

**Comment by hecgua** [comment]
@SC2Mitch I wanted to do a OS reinstall on my server, then install version 14 because that version was working very well for me. Whats the procedure to install version 14?

**Comment by Vaalyn** [comment]
We don't have any documentation regarding this since we don't want people to go "I remember I used version x from 3 years ago without any issues, so I'll just install that one instead and will complain about anything I find wrong in that version".

(Seriously, you don't want to know how often something like this happens were people are complaining that something doesn't work for them and we then go on to find out that they were using a version so old that their "bug" has been fixed for x versions already)

Anyways, try downloading the https://github.com/AzuraCast/AzuraCast/blob/main/sample.env into the empty `/var/azuracast` directory, rename it to just `.env` and add `AZURACAST_VERSION=0.14.1`, then run the install process. Should work, can't guarantee it though since we don't support this officially. This is originally meant for keeping an installed version on that one, not for freshly installing it but I think it should work.
