### ISSUE TITLE
Smart Crossfade not working after docker upgrade.

### ISSUE THREAD

**Issue by djwoefgithub** [AzuraCast/AzuraCast#5109]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 Rolling Release #76e4810 (2022-02-15 5:21) • Docker • PHP 8.1 

### What happened?

After upgrade with ./docker.sh update 2 weeks ago the smart crossfade mode does not work anymore. Its driving me nuts. I did not change a thing except doing the upgrade. It is the same situation on all my radio stations. The old song is played all way to the end without fade out and the new song starts with the first 5 or 6 seconds missing. Just like someone flips a switch from one audio source to the other. Sounds very unprofessional so I hope this bug  can be solved soon. I dont see any errors on in the liquidsoap log assuming that this is the place where the problem lies. I do see some lines in the liquidsoap log  with "No transition: using default." See below.

### Relevant log output

```shell
2022/02/15 22:34:23 [decoder:2] Decoding "/var/azuracast/stations/test/media/movedanceradio-take_back_the_house.wav" ended: Ffmpeg_decoder.End_of_file.
2022/02/15 22:34:23 [next_song:3] Prepared "/var/azuracast/stations/test/media/movedanceradio-more_music_in_the_mix.wav" (RID 45).
2022/02/15 22:34:23 [cue_next_song:3] Cueing in...
2022/02/15 22:34:23 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/5/nextsong' with body: 
2022/02/15 22:34:23 [crossfade_0:3] Analysis: -27.495689dB / -8.270054dB (2.96s / 2.96s)
2022/02/15 22:34:23 [crossfade_0:3] No transition: using default.
2022/02/15 22:34:23 [lang:3] API feedback - Sending POST request to 'http://web/api/internal/5/feedback' with body: {
2022/02/15 22:34:23 [lang:3]   "song_id": "30922aa00f03c3e91b1548aa6094d7c0",
2022/02/15 22:34:23 [lang:3]   "playlist_id": "36",
2022/02/15 22:34:23 [lang:3]   "media_id": "2932"
2022/02/15 22:34:23 [lang:3] }
2022/02/15 22:34:23 [lang:3] API nextsong - Response (200): annotate:title="playing the best music",artist="movedanceradio",duration="13.00",song_id="f619ff28e5421590422dfb7ea37428db",media_id="2931",liq_amplify="0.00dB",playlist_id="36":/var/azuracast/stations/test/media/movedanceradio-playing_the_best_music.wav
2022/02/15 22:34:23 [lang:3] API feedback - Response (200): OK
2022/02/15 22:34:28 [decoder:2] Decoding "/var/azuracast/stations/test/media/movedanceradio-more_music_in_the_mix.wav" ended: Ffmpeg_decoder.End_of_file.
2022/02/15 22:34:29 [next_song:3] Prepared "/var/azuracast/stations/test/media/movedanceradio-playing_the_best_music.wav" (RID 46).
2022/02/15 22:34:29 [cue_next_song:3] Cueing in...
2022/02/15 22:34:29 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/5/nextsong' with body: 
2022/02/15 22:34:29 [crossfade_0:3] Analysis: -16.053220dB / -11.027970dB (2.96s / 2.96s)
2022/02/15 22:34:29 [crossfade_0:3] No transition: using default.
2022/02/15 22:34:29 [lang:3] API feedback - Sending POST request to 'http://web/api/internal/5/feedback' with body: {
2022/02/15 22:34:29 [lang:3]   "song_id": "bc506a635e5a918014ea3256335720da",
2022/02/15 22:34:29 [lang:3]   "playlist_id": "36",
2022/02/15 22:34:29 [lang:3]   "media_id": "2929"
2022/02/15 22:34:29 [lang:3] }
2022/02/15 22:34:29 [lang:3] API nextsong - Response (200): annotate:title="playing back to back",artist="movedanceradio",duration="14.00",song_id="497a2a3f47630f8d088bff3f6e24e6c1",media_id="2930",liq_amplify="0.00dB",playlist_id="36":/var/azuracast/stations/test/media/movedanceradio-playing_back_to_back.wav
2022/02/15 22:34:29 [lang:3] API feedback - Response (200): OK
```

**Comment by hecgua** [comment]
Hello. 

Same situation for me. I did a totally fresh install yesterday (rolling release) and some songs on all radios are doing it and, like djwoefgithub wrote, a few seconds of the begining of the songs are truncated. It should be said that it is only in some songs, the issue is not continuous for me.

Here's the Liquidsoap log for a truncated song (Thompson Twins - Lies). 

2022/02/15 17:24:46 [lang:3] API feedback - Response (200): OK
2022/02/15 17:30:55 [decoder:2] Decoding "/var/azuracast/stations/80s_online_radio/media/2/Evelyn Champagne King - Love Come Down.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/02/15 17:30:56 [next_song:3] Prepared "/var/azuracast/stations/80s_online_radio/media/PM/80sOR PM.mp3" (RID 4).
[mp3float @ 0x7f87f42c5980] Could not update timestamps for skipped samples.
2022/02/15 17:30:56 [cue_next_song:3] Cueing in...
2022/02/15 17:30:56 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/8/nextsong' with body: 
2022/02/15 17:30:56 [lang:3] API nextsong - Response (200): annotate:title="Lies",artist="Thompson Twins",duration="320.00",song_id="961a7151087f8b335e19e7e88cf208b4",media_id="5259",liq_amplify="0.00dB",playlist_id="39":/var/azuracast/stations/80s_online_radio/media/5/Thompson Twins - Lies.mp3
[mp3 @ 0x7f87e8029e40] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f87e8029e40] Estimating duration from bitrate, this may be inaccurate
2022/02/15 17:30:56 [crossfade_0:3] Analysis: -infdB / -18.487323dB (4.44s / 4.44s)
2022/02/15 17:30:56 [crossfade_0:3] new >= old + margin, old <= medium and new <= high.
2022/02/15 17:30:56 [crossfade_0:3] Do not fade if it's already very low.
2022/02/15 17:30:56 [crossfade_0:3] Transition: crossed, no fade.
2022/02/15 17:30:56 [lang:3] API feedback - Sending POST request to 'http://web/api/internal/8/feedback' with body: {
2022/02/15 17:30:56 [lang:3]   "song_id": "83cc65640138e144cc157b391ec7cd82",
2022/02/15 17:30:56 [lang:3]   "playlist_id": "",
2022/02/15 17:30:56 [lang:3]   "media_id": ""
2022/02/15 17:30:56 [lang:3] }
2022/02/15 17:30:56 [lang:3] API feedback - Response (200): OK
[mp3float @ 0x7f87f42c5980] Could not update timestamps for discarded samples.
2022/02/15 17:31:00 [decoder:2] Decoding "/var/azuracast/stations/80s_online_radio/media/PM/80sOR PM.mp3" ended: Ffmpeg_decoder.End_of_file.
[mp3 @ 0x7f87f48e4880] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f87f48e4880] Estimating duration from bitrate, this may be inaccurate
2022/02/15 17:31:01 [next_song:3] Prepared "/var/azuracast/stations/80s_online_radio/media/5/Thompson Twins - Lies.mp3" (RID 3).
2022/02/15 17:31:01 [cue_next_song:3] Cueing in...
2022/02/15 17:31:01 [lang:3] API nextsong - Sending POST request to 'http://web/api/internal/8/nextsong' with body: 
2022/02/15 17:31:01 [lang:3] API nextsong - Response (200): annotate:title="C'est La Vie",artist="Robbie Nevil",duration="218.00",song_id="4929d6164bcfae197b96971ba5886b41",media_id="5130",liq_amplify="0.00dB",playlist_id="38":/var/azuracast/stations/80s_online_radio/media/4/Robbie Nevil - C'est La Vie.mp3
[mp3 @ 0x7f87e8019d00] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f87e8029e40] Estimating duration from bitrate, this may be inaccurate
2022/02/15 17:31:01 [crossfade_0:3] Analysis: -22.543871dB / -25.679802dB (4.48s / 4.48s)
2022/02/15 17:31:01 [crossfade_0:3] No transition: using default.
2022/02/15 17:31:01 [lang:3] API feedback - Sending POST request to 'http://web/api/internal/8/feedback' with body: {
2022/02/15 17:31:01 [lang:3]   "song_id": "83cc65640138e144cc157b391ec7cd82",
2022/02/15 17:31:01 [lang:3]   "playlist_id": "",
2022/02/15 17:31:01 [lang:3]   "media_id": ""
2022/02/15 17:31:01 [lang:3] }
2022/02/15 17:31:01 [lang:3] API feedback - Response (200): OK

**Comment by SC2Mitch** [comment]
Thanks for the reports guys, will check this out in the coming days!

**Comment by djwoefgithub** [comment]
Damn,

I was really irritated by this so backed everything up and moved my music to the stable release V0.15.0 yesterday and it ran smooth again with a nice crossfade. Just a few minutes ago I got the message that I should upgrade to V0.15.1. I did this and now the crossfade problem is back! Dont install this update!

**Comment by SC2Mitch** [comment]
Please don't leave comments advising users not to install the update, not only is it incredibly disrespectful to the team that poured hundreds of hours into this project, I understand this is probably the first open source project you've dealt with but show some respect to the team that tries to keep up with regular updates and bug fixes. 

This'll be locked until a bug fix is deployed.

**Comment by SC2Mitch** [comment]
Fixed, closed
