### ISSUE TITLE
Media deleted after deleting station.

### ISSUE THREAD

**Issue by muhepd** [AzuraCast/AzuraCast#5179]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.15.2 Stable

### What happened?

I had an station with the media mounted in a directory through NFS in another server.

I deleted the station (for reasons outside of this report), when I deleted the station, the media files in my server (not Azuracast) were also deleted.

Why would Azuracast delete the media files when deleting the station? Specially if the files were a mounted directory.

Deleting an station should never delete the media.

**Comment by iplayradionetworks** [comment]
that happened to me as well... this is not right

**Comment by SlvrEagle23** [comment]
@muhepd I looked into this, and actually it turns out it's a bug with how we were handling deleting stations. The code was _supposed_ to be checking if a storage location (i.e. station media) was used by any other stations, and only deleting it if it _wasn't_, but it turns out the code was just deleting the entire station directory regardless of that fact, which is certainly not intended.

In the latest Rolling Release version, only the directories actually created for the specific station (the config, temp and playlists directories) will be removed when a station is deleted, and the actual media/recordings/etc. directories will remain in place and will not be deleted.
