### ISSUE TITLE
Listeners page - Internal/Reserve IP location

### ISSUE THREAD

**Issue by simpsss** [AzuraCast/AzuraCast#5180]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #c25b50c (2022-03-09 1:52)

### What happened?

Good Morning!

After the last update (Rolling Release #c25b50c (2022-03-09 1:52)) the Listeners page is showing users with local/internal IP again (in version #59e17bf it worked normally)

![image](https://user-images.githubusercontent.com/51731449/157433422-3dc4337d-b72f-429c-bb3f-22912ffce230.png)

**Comment by LordHelmchen666** [comment]
Try restarting docker service. Sometimes these happens to me when docker was updated.

```
 sudo systemctl daemon-reload
 sudo systemctl restart docker
```

Mostly it is ok after i do this.

**Comment by LordHelmchen666** [comment]
updated my install to latest version. I believe this is related to this commit 27260729bc432fe761f8cd62a7ba6cddd1ed22e2
Maybe port forwarding is now incorrect?

**Comment by Vaalyn** [comment]
Info for dev purposes:

This issue is caused by the requests now being forwarded by `127.0.0.1` (localhost) instead of the IP of a different container so the Icecast configuration which is currently only allowing proxied IPs to be used when the proxy is either `192.*.*.*` or `172.*.*.*` needs to be changed to allow proxied IPs from `127.0.0.1`.

https://github.com/AzuraCast/AzuraCast/blob/main/src/Radio/Frontend/Icecast.php#L119-L121
