### ISSUE TITLE
webdj link in manage page sends you to https:// url insted of http://

### ISSUE THREAD

**Issue by sebadamus** [AzuraCast/AzuraCast#5200]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 v0.15.2 Stable

### What happened?

Might be mistaken but cant figure out where to change this, I access AzuraCast with http://myipaddress:82, everything seems to access normally and working.

When I access Manage menu of my station, there is a link to Web Dj on the left menu that opens a new browser window with
https://myipaddress:82/public/puppetmaster/dj
I dont have https enabled, but the link opens in https anyway and gives "SSL_ERROR_RX_RECORD_TOO_LONG".

If I change the https to http in the url, Web DJ opens just fine.

The expected behaviour would be that the new browser window open as http and not https.

**Comment by SlvrEagle23** [comment]
@sebadamus This is actually on purpose, because the WebDJ feature doesn't work at all on most modern browsers _unless_ you're using a HTTPS connection, because it's asking for permission to use your local microphone and that's a HTTPS-only feature. That's why, regardless of the HTTP settings elsewhere on the system, we always force HTTPS on that connection, to avoid users running into problems on that page because they're on an insecure connection.

**Comment by sebadamus** [comment]
> @sebadamus This is actually on purpose, because the WebDJ feature doesn't work at all on most modern browsers _unless_ you're using a HTTPS connection, because it's asking for permission to use your local microphone and that's a HTTPS-only feature. That's why, regardless of the HTTP settings elsewhere on the system, we always force HTTPS on that connection, to avoid users running into problems on that page because they're on an insecure connection.

Thank you very much! will close the issue.
