### ISSUE TITLE
Cannot reset "fadeoverlap" value once it has been set ( mediafile -> advanced)

### ISSUE THREAD

**Issue by Cedric-NET** [AzuraCast/AzuraCast#5215]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

  latest rolling release, - it is impossible to remove a value assigned to that field once it has been set  

this is is Media (file)->advanced panel, default are blank.
Once set, impossible to get back to blank

<img width="830" alt="Capture d’écran 2022-03-22 à 13 10 02" src="https://user-images.githubusercontent.com/22983184/159484221-b0efe37e-63c5-43f1-8b7f-c5a0b6c2f5a4.png">

**Comment by SlvrEagle23** [comment]
@Cedric-NET I am aware of this issue, and it is certainly a valid one, but fixing it is going to require a lot deeper of a dive into the application code. It's basically going to mean rewriting how we handle transferring data from API calls back into entities, so it'll be a bit of work.

For some of these fields, in the meantime, the workaround would be to set the values to 0.

**Comment by SlvrEagle23** [comment]
@Cedric-NET Well, it turns out it wasn't as particularly complicated as I expected it would be. I've pushed a new update (that is currently deploying, per the commit above) to the Rolling Release channel that should resolve this and allow you to empty those fields and return them to their default null values.
