### ISSUE TITLE
Accentuated characters sent thru SFTP end up as "wxrong UTF8" in the web gui

### ISSUE THREAD

**Issue by ghost** [AzuraCast/AzuraCast#5216]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

When you upload file names with accents ( éèà for example ) thru SFTP, they end up as i-dont-know-what encoding on the filesystem, but the Azuracast web gui can't read the filenames anymore

In this case I uploaded them inside a folder (with no accents) but I think this is irrelevant to reproduce,

(very short popup saying
![chrome_44IgK7wnNa](https://user-images.githubusercontent.com/22983184/159507564-e6c89cd7-5f4b-4beb-adcf-fa66a0b28f4b.png)

**Comment by Cedric-NET** [comment]
this also seems to completely hang up the file processing

Azura doesn't see new files, processing is stuck, etc

**Comment by Cedric-NET** [comment]
the "check media" taks is completely broken.

Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.

[Go Back](https://SSSSSS/admin/debug/sync/App%5CSync%5CTask%5CCheckMediaTask#)

Can I do smth about this ?

**Comment by SC2Mitch** [comment]
you can check your docker logs to see what errors it's returning to help us look into this

**Comment by SlvrEagle23** [comment]
Having trouble reproducing this on the latest Rolling Release version...just uploaded a file via SFTP that has accents in the filename and it not only processed properly, but also can be edited, added to playlists, etc. via the web UI without any issues.

![2022-03-27 01_40_20-(Development) Music Files - AzuraCast](https://user-images.githubusercontent.com/6744885/160269919-f929bea3-8b08-4308-b218-274bb6f5a8db.png)

**Comment by Cedric-NET** [comment]
well at first Valynn has toruble reproducing as well,
the valynn opened le an account on his azuracast
and i successufuylly crashed it by uploading a file

it sees to be linked to using windows to upload (are you) and valynn has the dertails + a file that creates the bug

**Comment by SlvrEagle23** [comment]
Ah okay, @Vaalyn if you could share some details about this, maybe we can reproduce it?

I am indeed using Windows, in particular Filezilla via Windows, to do SFTP uploads.

**Comment by Cedric-NET** [comment]
the bug is vicious in the sense the server seems to be stuck forever in a loop, and it won't process anything anymore

also the file can't be deleted by the gui when this happens

**Comment by Vaalyn** [comment]
@SlvrEagle23 this issue is caused by files that have a filename that is using something else than UTF-8 while containing non-ascii chars. In this specific case I suspect UTF-16 as that is the default encoding for filenames on Windows.

The file that @Cedric-NET provided me with to reproduce this is shown like this to me on my macOS 12.3 machine which is using a UTF-8 filesystem:
![image](https://user-images.githubusercontent.com/13745863/160279356-8b5de3e5-6624-4307-a841-97f903429bb1.png)

The strange thing to me at least is that I have uploaded files with non-ascii chars from Windows in the past without issues (like for example `äüöáà` and even Japanese characters).

When I upload this example file from the screenshot via `Cyberduck` on my mac the server does not get stuck though but when @Cedric-NET uploaded it directly from his PC vis a tool called `SecureFX` it does get stuck on the file. So I think some clients re-encode the filename while uploading and some send it raw as-is.

**Comment by Cedric-NET** [comment]
t I wish to say that SecureCRT is prbably the most used tool for doing SSH connections for IT pros ( SecureFX beeing the file transfer module)
And that on this specific file, the ö appears correctly in both windows and on the target linux operating system.


If I can given you more details just tell me what to do :)

**Comment by Vaalyn** [comment]
> t I wish to say that SecureCRT is prbably the most used tool for doing SSH connections for IT pros ( SecureFX beeing the file transfer module) 

I don't think this is true.
For most IT professionals that are using Linux as their OS they most likely use the built in native SSH client (in most cases OpenSSH) and the respective distributions file manager client for it to access SFTP. For people using macOS they mostly use Cyberduck or Commander One for SFTP and also the native SSH client and on Windows this widely varies between companies and people. Some use good old putty, some use newer apps like Termius and W10 even has a built-in ssh client that is most likely also using OpenSSH.

> And that on this specific file, the ö appears correctly in both windows and on the target linux operating system.

On Windows this is true but at least on my AzuraCast server where you uploaded the file this was not the case.
There it showed up like this in SSH:

![image](https://user-images.githubusercontent.com/13745863/160281305-1598ed9b-43ee-4ddd-bf4b-9831102e387e.png)

**Comment by Moonbase59** [comment]
I’ve never seen that between Linux systems (mostly because almost all use UTF-8 nowadays) but between Windows and Linux, due to Windows’ odd encodings—they seem to use UTF-16 with NTFS but sometimes present filenames on odd encodings like "cp-1252" or the like. Using (S)FTP clients like FileZilla, this can often be corrected by setting "Server Type" to "Unix" and forcing the character set to UTF-8 (within FileZilla, rightmost tab).

In some cases (depending on Windows version), it can help setting Windows’ code page to 65001 (UTF-8), but that usually rips open another bunch of problems… and will mostly only work for the Unicode base plane.
