### ISSUE TITLE
500 PublicController.php : 38

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#522]
500
Station not found!
PublicController.php : 38

> [2018-03-26 10:06:58] AzuraCast.ERROR: Station not found! {"file":"/var/azuracast/www/app/src/Controller/Frontend/PublicController.php","line":38,"code":0} []
[2018-03-26 10:07:01] AzuraCast.ERROR:  {"file":"/var/azuracast/www/app/src/AzuraCast/Middleware/RequireLogin.php","line":24,"code":0} []

**Comment by javikore** [comment]
Hello, I have the same problem with some solution?
I have Ubuntu LTS 16.04 install with docker installation.
Thanks!

**Comment by SlvrEagle23** [comment]
@susl16c @javikore Do you mean the problem of having those items logged in your log history? I'm working to fix that currently, as a number of those issues aren't actually loggable issues.

**Comment by SlvrEagle23** [comment]
@susl16c Looking at your public nowplaying API response: https://radio.izones.ru/api/nowplaying

It appears you've set all of your stations on this AzuraCast instance to be hidden from public view. As the description on that option says, this _also_ hides their public pages, as this would otherwise be a fairly easy way to tell which stations are hosted on that particular instance.

If you want to continue with the "Hide from Public Pages" setting turned on, you should implement your own player page for the station.

**Comment by susl16c** [comment]
Yes, but I did not do any settings, before everything worked just refreshed and the page stopped working.
