### ISSUE TITLE
Web hook for twitter

### ISSUE THREAD

**Issue by radiopulsar** [AzuraCast/AzuraCast#5228]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.15.0 Stable • Docker • PHP 8.1

### What happened?

How can i put the Now Playing run on twitter, for my station.
I trie everything, but, what Variables {{ var.name }} do i have to put, to run this on the web hook?
In older versions, we see the example of  variables to put in
I dont see what variable is in the api, and i trie many of them.

Thanks

**Comment by SlvrEagle23** [comment]
@radiopulsar Thank you for pointing out that the default messages on webhooks were no longer showing up when you create a new one. We definitely intended for them to show up, but because of a minor error, they weren't showing up correctly. In the latest Rolling Release version that's currently deploying, this issue should be fixed, and there should be a default message again.
