### ISSUE TITLE
Auto Dj not running and public page sound error

### ISSUE THREAD

**Issue by DINUHOST** [AzuraCast/AzuraCast#5254]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #870b4e6 (2022-04-02 5:34) • Docker • PHP 8.1 

### What happened?

![2022-04-02](https://user-images.githubusercontent.com/96260181/161384338-171d375b-cc09-4eaa-b189-3c32342519bc.png)

when i skip the song shown some error. and then public page song was playing but sound not came.
![2022-04-02 (1)](https://user-images.githubusercontent.com/96260181/161384368-4b4f5c79-c406-43aa-99d0-71c4abef1105.png)
 

### Relevant log output

```shell
http://129.154.35.158/public/localfmin
```

**Comment by SlvrEagle23** [comment]
@DINUHOST It looks like you never clicked "Start Station" on this station once it was ready to broadcast...try clicking that and letting it reload broadcasting and see if that helps at all.

**Comment by DINUHOST** [comment]
> @DINUHOST It looks like you never clicked "Start Station" on this station once it was ready to broadcast...try clicking that and letting it reload broadcasting and see if that helps at all.

When I'm clicking start station they are no response again come to same location...

**Comment by SlvrEagle23** [comment]
@DINUHOST It doesn't show any response? No error message on the screen? If you open the inspector console and the "Network" tab, do you see any errors?

**Comment by SlvrEagle23** [comment]
@DINUHOST We found and fixed a major issue with how our AutoDJ interacts with AzuraCast in the latest Rolling Release version; the fix for this was just released a few minutes ago, so if you don't mind updating and trying the new version out to see if it resolves your issues, it would be much appreciated! The latest version also improves how we log errors related to the AutoDJ, so even if there are still errors, we will have more information about them moving forward. Sorry for the inconvenience and thank you for your patience.

**Comment by DINUHOST** [comment]
Hi AzuraCast Team,

    That issue has been resolved but another one facing domain name is
not working..
