### ISSUE TITLE
play and volume icons not displaying in public page

### ISSUE THREAD

**Issue by freqmand** [AzuraCast/AzuraCast#5267]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.15.2 

### What happened?

play and volume icons not showing in public page, sometimes they are displaying after some time (1-2 minutes), and sometimes not.

![station](https://user-images.githubusercontent.com/81921578/162488872-2196b721-db89-4730-9e3a-2c08ae0e4915.png)

### Relevant log output

```shell
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:1:143374
downloadable font: download failed (font-family: "Roboto" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://mystation/static/dist/lib/roboto-fontface/fonts/roboto/Roboto-Regular.woff2
downloadable font: download failed (font-family: "Roboto" style:normal weight:700 stretch:100 src index:0): status=2147746065 source: https://mystation/static/dist/lib/roboto-fontface/fonts/roboto/Roboto-Bold.woff2
downloadable font: download failed (font-family: "Roboto" style:normal weight:500 stretch:100 src index:0): status=2147746065 source: https://mystation/static/dist/lib/roboto-fontface/fonts/roboto/Roboto-Medium.woff2
downloadable font: download failed (font-family: "Material Icons Outlined" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://mystation/static/dist/lib/material-icons/material-icons-outlined.woff2
downloadable font: download failed (font-family: "Material Icons" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://mystation/static/dist/lib/material-icons/material-icons.woff2
```
```

**Comment by SC2Mitch** [comment]
Are you using CloudFlare by any chance.

**Comment by freqmand** [comment]
@SC2Mitch yes cloudflare

**Comment by SC2Mitch** [comment]
https://docs.azuracast.com/en/administration/cloudflare
Follow our guide here on disabling the Cloudflare Rocket.

**Comment by freqmand** [comment]
@SC2Mitch Cloudflare Rocket Loader is disabled, and the problem still persist

**Comment by Vaalyn** [comment]
Are you using a browser plugin / extension that injects custom css / js into websites?

I'm asking because of this line at the top where it is saying `moz-extension` at the end:
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:1:143374
```

If not please post the exact version number of the Firefox version you are using.

What would also help to debug this is a link to the public page of your station so we can check if this is a general issue with this specific installation or with your client.

**Comment by freqmand** [comment]
@Vaalyn 
I'm using Tor Browser(Latest version), I think some exit nodes blocks the loading of fonts.
when I tried with google chrome there is no issue,
with firefox the icons works great, and I'm getting this error in console 
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).
```

does azura is tested with tor ? and do you have any idea how to fix this issue ?

**Comment by SC2Mitch** [comment]
Most likely a thing with how Tor handles JavaScript or its CSP, I can have a look to see if there's no settings, but unlikely.

**Comment by freqmand** [comment]
I tried with the different tor settings, but no difference. tested with other devices with tor, same issue. I think the problem is related to azura js scripts somehow tor does not like them

**Comment by SC2Mitch** [comment]
Again, this is entirely a Tor problem as to how it interacts with AzuraCast, we don't control Tor nor operate so we cannot give assistance on this issue. 

I've tested across various browsers, the Javascript seems to work fine.

**Comment by freqmand** [comment]
tor is a network, and million of people across the world are using it,  so Azura should be able to operate through it ! and not the other way around

**Comment by Vaalyn** [comment]
I have just looked at my own test servers public player page as well as the one of the demo installation via the Tor Browser and everything showed up fine, no errors in the JS console nor in the network tab.

Could it be that the installation you are looking at does not have a SSL certificate set up?
The Tor Browser includes the "HTTPS Everywhere" extension so it might be caused by this extension redirecting the fonts download to https and failing to load them correctly because of that.

Alternatively please post a link to the installation where you are seeing this.
As it stands I can't see this happening with Tor Browser `Version 91.8.0esr (64-bit)`.
