### ISSUE TITLE
Player delay 1:30 minutes in updating metadata, image and title. unbalanced autodj volume.

### ISSUE THREAD

**Issue by kokomolo** [AzuraCast/AzuraCast#5271]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

Rolling Release #5d52ff4 (2022-04-09 2:37)

### What happened?

Hello, there is a lot of CPU and RAM consumption above 90% with many peaks, but there is a mismatch between the consumption indicated by the Azura meter and the vps meter (4 vcores, 8 GB of RAM, 160 SSD).
The player does not update the metadata of the theme image and the title at the same time it is played, it takes more than 1:30 minutes to update.
The volume when changing from one musical theme to another of the autodj shoots from being lower than normal to saturation until it reaches 100%

**Comment by SlvrEagle23** [comment]
@kokomolo In our newer Rolling Release versions, we've been able to fix a significant number of issues relating to CPU consumption, memory usage, and overall bugs. If it's possible for your installation, could you update to the latest Rolling Release version and verify if the issue is fixed?

If you want to stay on Stable releases, that's fine as one will likely be coming soon in the next few days.
