### ISSUE TITLE
what is the advanced playlist for liquidsoap?

### ISSUE THREAD

**Issue by dreinn** [AzuraCast/AzuraCast#528]
- **Installation Method:** 
- **Host debian jessie

Hello,
if I want to create a playlist I see the last option that is the advanced custom playlist that seems to be used with liquidsoap for advanced users.
The playlist has no edit field and is empty.
What is the meaning and how does it work?
Thank you.

**Comment by cjuniorfox** [comment]
I'll like to know too. I found no information how to be a advanced user and how to edit list for advanced users.

**Comment by SlvrEagle23** [comment]
@dreinn @cjuniorfox This is definitely a valid question, since I created advanced playlists for one specific use case (though it's very useful for many others) and hadn't gotten around to documenting it very well since then.

I've created a wiki article explaining what it is and how to use it here:
https://github.com/AzuraCast/AzuraCast/wiki/Using-Advanced-Playlists

I also added a link inside the software itself to that same wiki page to help answer anyone's questions.
