### ISSUE TITLE
Songs don't have covers when livestreaming

### ISSUE THREAD

**Issue by wegGehamstert** [AzuraCast/AzuraCast#5292]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.15.2

### What happened?

When I go live, regardless of the WEBDJ or an external program, no cover is transmitted

### Relevant log output

```shell
There is no output log
```

**Comment by Vaalyn** [comment]
DJ broadcast tools do not support sending album art when streaming to a Icecast or Shoutcast server.
(This includes: Mixxx, VirtualDJ, Butt, Lunarcaster, PlayItLive, SamCAST, RadioBoss)

As far as I'm aware this is because the protocols for streaming to Icecast/Shoutcast do not support sending album art.

If you have trouble with getting the album art shown via MusicBrainz / LastFM, there is an open bug report for that over here: https://github.com/AzuraCast/AzuraCast/issues/5103
