### ISSUE TITLE
Uploading files doesn't include album art in some edge cases. 

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#5459]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

f648491

### What happened?

When attempting to upload some music files that have album art embeded, AzuraCast does not always collect that data and returns a default image. 

Example track - https://cdn.discordapp.com/attachments/982617967953076244/982618037859532880/DVRST_-_YOUR_NAME.mp3
Viewing the file in MP3Tag - https://puu.sh/J41RK/abbcdc6024.png

Uploading to AzuraCast
![image](https://user-images.githubusercontent.com/29955942/172010152-41dbfe4e-9d6f-42f8-bee4-22d529772e30.png)

I stripped the album art from the image and replaced it, it resolved the issue but unsure why this edge case can happen.

**Comment by Vaalyn** [comment]
This is caused by how we are looking for the album art via FFmpeg:

We are iterating over all video streams of a file [here](https://github.com/AzuraCast/AzuraCast/blob/main/src/Media/Metadata/Reader.php#L51-L52) and we are looking specifically for the `mjpeg` (motion jpeg) to identify which video stream of a file is the cover art [here](https://github.com/AzuraCast/AzuraCast/blob/main/src/Media/Metadata/Reader.php#L53-L56).

When I look at the file linked above via FFprobe I can see that the only video stream of that file is a png:
```
Stream #0:1: Video: png, rgb24(pc), 1280x720, 90k tbr, 90k tbn (attached pic)
    Metadata:
      title           : "Album cover"
      comment         : Other
```

Here an example from a CD rip of mine which contains a motion jpeg:
```
Stream #0:1: Video: mjpeg (Baseline), yuvj444p(pc, bt470bg/unknown/unknown), 1456x1376, 90k tbr, 90k tbn (attached pic)
    Metadata:
      title           : IMG_20160715_0001.jpg
      comment         : Cover (front)
```

We'll probably need to expand the list of formats to look for in the video streams of files.

**Comment by SlvrEagle23** [comment]
@Vaalyn @SC2Mitch I noticed in the lines above that both of the album art things had "attached pic" next to them, and I looked up how this is represented in ffprobe...turns out any album art for any media file will have the "attached pic" disposition set to 1, which we can check for instead of the individual codecs. Testing locally, this makes the test file work alongside all others.
