### ISSUE TITLE
Can't play external URL in a playlist

### ISSUE THREAD

**Issue by dusdjkip** [AzuraCast/AzuraCast#5472]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.0

### What happened?

Since AzuraCast 0.17.0 I've experienced that playing external URLs doesn't work. This has always worked in an earlier version.

Here I used in the liquidsoap config
`output.dummy(id="DUMMY_STREAM_OUTPUT", fallible=true, playlist_live)` from the issue [https://github.com/AzuraCast/AzuraCast/issues/3701](https://github.com/AzuraCast/AzuraCast/issues/3701)
Which unfortunately no longer works.

Am I doing something wrong or is this being worked on?

### Relevant log output

```shell
[mp3float @ 0x7f1cc4722bc0] Could not update timestamps for discarded samples.
2022/06/08 11:17:09 [decoder:2] Decoding "/usr/local/share/icecast/web/error.mp3" ended: Ffmpeg_decoder.End_of_file.
2022/06/08 11:17:10 [error_jingle:3] Prepared "/usr/local/share/icecast/web/error.mp3" (RID 0).
[mp3float @ 0x7f1cc4297040] Could not update timestamps for skipped samples.
2022/06/08 11:17:17 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2022/06/08 11:17:17 [lang:3] API nextsong - Response (200): false
2022/06/08 11:17:17 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2022/06/08 11:17:17 [lang:3] API nextsong - Response (200): false
```

**Comment by AyatoOvision** [comment]
Same issue here

**Comment by Catskill909** [comment]
same issue here after update to 0.17.0

**Comment by SC2Mitch** [comment]
Can you guys provide your external URLs you're attempting to play? If you don't want to share publicly, you can DM me on the AzuraCast discord.

**Comment by Catskill909** [comment]
https://stream.pacificaservice.org:9000/wjff_128

**Comment by Catskill909** [comment]
https://stream.pacificaservice.org:9000/wjff_128

**Comment by SlvrEagle23** [comment]
Remote URL playlists have not ever worked quite as our users would expect them to, and as we have moved additional duties over to our own AutoDJ scheduler and away from Liquidsoap, they have become more and more difficult for us to maintain.

In the latest version, we limit remote URL playlists to only work if they're scheduled, i.e. set to start at a given time and end at another.

Otherwise, they basically take over the entire stream and prevent our own AutoDJ from working properly at all.

I am curious what your intended use-cases are for using remote URL playlists. I'm unsure why they're quite so popular amongst our users. If you intend them just as fallbacks for when there is nothing for your station to broadcast (or no live DJ broadcast), then we could consider reinstating the previous functionality where they override the entire AutoDJ if set.

**Comment by dusdjkip** [comment]
Hey @SlvrEagle23,

It's nice of you to think about this problem. Let me explain our situation. And basically what you said last is also true for us.

We use 2 streams. Own AutoDJ Stream which streams continuously to AzuraCast through a windows vps. And a main stream server.

The main stream server our deejays can connect to if they want to go live. In this way we actually have the same effect as liquidsoap did, but then we have our own non-stop.

I hope this provides more clarity and hope that this functionality can come back. We were happy with it!

**Comment by stardevelop** [comment]
There is a Wowza streaming server that generates m3u8 stream and I really need to use Remote URL Playlist feature to play the stream through Azuracast.

**Comment by SlvrEagle23** [comment]
Hey all, just pushed an update to the Rolling Release channel that will make Remote URL playlists work as a fallback URL in the event they aren't scheduled. I've also updated how the Playlists edit modal shows remote URL playlists to remove options that aren't actually relevant to them (you can't have a remote URL play "once per x songs", for example, because that's not how remote URLs work), which should hopefully clear up any confusion about how they work.

**Comment by stardevelop** [comment]
Updated to the latest Rolling Release. Still can't play my m3u8 Remote Playlist. Station goes offline.
I can send you my URL in discord.

**Comment by stardevelop** [comment]
I've just tested and my m3u8 Remote URL plays fine on my station. Thank you.
There is a few small issues:
1) Metadata of Remote Playlist are not displayed (shows Unknown).
2) The stream only plays on Local Streams (i.e. https://radio.com/listen/radio/radio.mp3) and HTTP Live Streaming (HLS) plays only Stream Offline song.

**Comment by stardevelop** [comment]
I've just tested and my m3u8 Remote URL plays fine on my station. Thank you.
There are few small issues:

1) Metadata of Remote Playlist are not retrieved and displayed (shows Unknown).
2) The stream only plays on Local Streams (i.e. https://radio.com/listen/radio/radio.mp3) and HTTP Live Streaming (HLS) plays only Stream Offline song.

**Comment by dusdjkip** [comment]
The problem has been solved! Thanks for solving @SlvrEagle23! We are very happy!

**Comment by dusdjkip** [comment]
Hello!

Suddenly after the latest updates, whatever stardevelop has indicated, the metadata is not going through properly. The song title is well announced in the Schoutcast log.

After the solution was implemented by SlvrEagle23 on June 9, it was fine at first!

Has anything changed?

![image](https://user-images.githubusercontent.com/20664281/175818169-8dc0d204-05f6-446f-8ec2-66fedc1086e7.png)

**Comment by Catskill909** [comment]
Same here. The last update fixed the broken remote url bug but metadata stopped working. 
Says "Stream offline" even though remote url stream is working

<img width="273" alt="Screen Shot 2022-06-26 at 11 11 47 AM" src="https://user-images.githubusercontent.com/36337311/175820980-3016f3e4-5f4b-4c37-ab1b-224ac3b469a5.png">
