### ISSUE TITLE
Backing up to remote SFTP includes media files when Exclude Media is enabled. 

### ISSUE THREAD

**Issue by SC2Mitch** [AzuraCast/AzuraCast#5475]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17

### What happened?

A user reported this bug to us on Discord link to the post - https://canary.discord.com/channels/647143522054701075/647149735991443467/984165021594574948

The user reported that he had backups set to Remote SFTP with the media excluded option enabled. He noticed on the 25th of May to the 26th of May the backup pages was getting flooded with .mp3 files from his media directories. 

![image](https://user-images.githubusercontent.com/29955942/172707703-880313c9-b288-4ad6-b095-7122b27871d5.png)

He concludes this only happened twice, something for us to review possibly?

**Comment by AshleyinSpain** [comment]
Hi 
I have some additional notes:
When I select to download the mp3 file it throws a 'Slim Application Error'
When I click delete it takes 7.5 minutes to do so and a further 8 minutes to reload the page
Regards
Ashley

**Comment by SC2Mitch** [comment]
Hi @AshleyinSpain 

Can you go to your AzuraCast.env and look for `SHOW_DETAILED_ERRORS`, if this does not exist then create this line and try clicking on the link again, it'll give you a debug output, DM it to me on Discord after as it may contain sensitive information
`SHOW_DETAILED_ERRORS=true`

**Comment by AshleyinSpain** [comment]
@SC2Mitch 
Where do I find the debug output

**Comment by SC2Mitch** [comment]
Click on the file you was attempting to download before which shown the Slim Application Error.

**Comment by AshleyinSpain** [comment]
@SC2Mitch 
After clicking on the download link
A new browser Tab opens and after a short while this appears
https://jmp.sh/avetAU2
No change after enabling the slim application debugging

**Comment by SC2Mitch** [comment]
Thanks for letting me know, one thing I forgot is when you changed the setting, you'll need to restart your instance, run this command then re-attempt the idea.
`docker-compose down && docker-compose up -d`

**Comment by SlvrEagle23** [comment]
@AshleyinSpain It kind of looks like the same storage location is being used for backups that is being used for something else, like media storage. Our backup engine doesn't just dump the MP3 files into the backup folder, it would include them into the actual zip/tar.gz/etc files.

**Comment by AshleyinSpain** [comment]
@SC2Mitch 
> Thanks for letting me know, one thing I forgot is when you changed the setting, you'll need to restart your instance, run this command then re-attempt the idea. `docker-compose down && docker-compose up -d`

I didn't think of that - have restarted Azuracast and 
Here is the error log from the download file button

Slim Application Error
The application could not run because of the following error:

Details
Type: League\Flysystem\UnableToRetrieveMetadata
Code: 0
Message: Unable to retrieve the mime_type for file at location: Music/Canales 2022/20-Fitness-Dia-Completo/Spiller, Purple Disco Machine, Lorenz Rhode, Sophie Ellis-Bextor - Groovejet (If This Ain't Love) [Feat. Sophie Ellis-Bextor] - Purple Disco Machine & Lorenz Rhode Remix.mp3.
File: /var/azuracast/www/vendor/league/flysystem/src/UnableToRetrieveMetadata.php
Line: 49
Trace
#0 /var/azuracast/www/vendor/league/flysystem/src/UnableToRetrieveMetadata.php(44): League\Flysystem\UnableToRetrieveMetadata::create()
#1 /var/azuracast/www/vendor/azuracast/flysystem-v2-extensions/src/Attributes/FileAttributes.php(61): League\Flysystem\UnableToRetrieveMetadata::mimeType()
#2 /var/azuracast/www/src/Http/Response.php(146): Azura\Files\Attributes\FileAttributes->mimeType()
#3 /var/azuracast/www/src/Controller/Api/Admin/Backups/DownloadAction.php(24): App\Http\Response->streamFilesystemFile()
#4 /var/azuracast/www/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponseNamedArgs.php(47): App\Controller\Api\Admin\Backups\DownloadAction->__invoke()
#5 /var/azuracast/www/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponseNamedArgs->__invoke()
#6 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#7 /var/azuracast/www/src/Middleware/Permissions.php(48): Slim\MiddlewareDispatcher->handle()
#8 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): App\Middleware\Permissions->__invoke()
#9 /var/azuracast/www/src/Middleware/Module/Api.php(53): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#10 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\Module\Api->__invoke()
#11 /var/azuracast/www/src/Middleware/Auth/AbstractAuth.php(46): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#12 /var/azuracast/www/src/Middleware/Auth/ApiAuth.php(40): App\Middleware\Auth\AbstractAuth->process()
#13 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\Auth\ApiAuth->process()
#14 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#15 /var/azuracast/www/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#16 /var/azuracast/www/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#17 /var/azuracast/www/src/Middleware/WrapExceptionsWithRequestData.php(26): Slim\Routing\RouteRunner->handle()
#18 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\WrapExceptionsWithRequestData->process()
#19 /var/azuracast/www/src/Middleware/EnforceSecurity.php(47): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#20 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\EnforceSecurity->process()
#21 /var/azuracast/www/src/Middleware/InjectRouter.php(34): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#22 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\InjectRouter->process()
#23 /var/azuracast/www/src/Middleware/InjectRateLimit.php(32): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#24 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\InjectRateLimit->process()
#25 /var/azuracast/www/src/Middleware/ReopenEntityManagerMiddleware.php(27): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#26 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\ReopenEntityManagerMiddleware->process()
#27 /var/azuracast/www/vendor/slim/slim/Slim/Middleware/BodyParsingMiddleware.php(68): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#28 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\BodyParsingMiddleware->process()
#29 /var/azuracast/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#30 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#31 /var/azuracast/www/src/Middleware/RemoveSlashes.php(38): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#32 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): App\Middleware\RemoveSlashes->process()
#33 /var/azuracast/www/src/Middleware/ApplyXForwardedProto.php(29): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#34 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): App\Middleware\ApplyXForwardedProto->process()
#35 /var/azuracast/www/src/Middleware/InjectSession.php(79): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#36 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(209): App\Middleware\InjectSession->process()
#37 /var/azuracast/www/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#38 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#39 /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#40 /var/azuracast/www/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#41 /var/azuracast/www/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#42 /var/azuracast/www/web/index.php(16): Slim\App->run()
#43 {main}
[Go Back](https://canales.musicologic.es/api/admin/backups/download/NXxNdXNpYy9DYW5hbGVzIDIwMjIvMjAtRml0bmVzcy1EaWEtQ29tcGxldG8vU3BpbGxlciwgUHVycGxlIERpc2NvIE1hY2hpbmUsIExvcmVueiBSaG9kZSwgU29waGllIEVsbGlzLUJleHRvciAtIEdyb292ZWpldCAoSWYgVGhpcyBBaW4ndCBMb3ZlKSBbRmVhdC4gU29waGllIEVsbGlzLUJleHRvcl0gLSBQdXJwbGUgRGlzY28gTWFjaGluZSAmIExvcmVueiBSaG9kZSBSZW1peC5tcDM=#)

Hope this helps focus the issue

Best regards
Ashley

**Comment by AshleyinSpain** [comment]
@SlvrEagle23  - Thanks for your insight I looked into it and

Sorry guys - I did it - my fault
Embarrassed - eats humble pie

I failed to set a folder prefix for the remote storage - so Azuracast naturally dumped the backups in the root of the file server
However I had another directory with a copy of all the media files in it
Azuracast was doing it's best to read from that directory as well - ooppps

I set a remote storage backup folder in Azuracast then created it on the server and moved all the backups to it

Hey presto it is all working as it should

Thanks for you help

Best regards
Ashley

**Comment by SC2Mitch** [comment]
Hey Ashley, 

Glad to hear you've resolved the issue! Your suggestion is noted

Thanks for being patient and fixing the bug,

Closed
