### ISSUE TITLE
Schedule View is Blank

### ISSUE THREAD

**Issue by parkerj** [AzuraCast/AzuraCast#548]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Ubuntu 17.10

**Describe the issue in full detail, including screenshots if possible:**

For some strange reason, schedule view is blank. I've tried different time variations to figure out what the problem is, but no luck. I am attaching the console's error as well as a screenshot of my playlists.

<img width="1017" alt="screen shot 2018-04-09 at 4 06 41 pm" src="https://user-images.githubusercontent.com/2042176/38520290-6006753e-3c10-11e8-8d43-1612d96c0f69.png">
<img width="1338" alt="screen shot 2018-04-09 at 4 06 01 pm" src="https://user-images.githubusercontent.com/2042176/38520291-601dd94a-3c10-11e8-924f-d16eb29c9ea4.png">

**Comment by SlvrEagle23** [comment]
@parkerj It appears this is because you have a number of playlists that are scheduled to play from one time to the exact same time. Currently, the system doesn't consider that to be an indicator to play that scheduled item all day long.

However, since this is the only way to achieve the "play on certain days" functionality for playlists that play for the entirety of a given day, there's definitely an enhancement to be made there that would allow that.

I'll look into this error and see if there's an immediate resolution, but without a doubt playlists are still in need of a bigger overhaul to separate the scheduling aspect from the other descriptors of the playlist.

**Comment by parkerj** [comment]
Ok, thanks.

**Comment by SlvrEagle23** [comment]
@parkerj I've made some updates to how the scheduled playlists work, in particular the Schedule View display, and implemented a new calendar view that properly takes into account "all-day" events (that start and end at the same time) and that can adjust correctly for timezone variations.

This should resolve the issues you were seeing, and also provide for much-needed flexibility for future playlist updates. :)
