### ISSUE TITLE
AUDIO LINK NOT SUPPORTING OTHER BROWSERS

### ISSUE THREAD

**Issue by nobertamooti** [AzuraCast/AzuraCast#5505]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### What happened?

I have an issue of audio link not supporting other browsers on my website like chrome and mobile phone. 
https://kkcr.urdt.net/  on this website audio link supports only Firefox but others and mobile view not. 
i have tried to use audio streamer links failed but on external websites it working 
were could be the problem
need help
here is an audio link http://45.33.27.209/public/kkcr91.7

**Comment by Vaalyn** [comment]
Your website is `https` which means all the content that you include from third parties (other domains) needs to be served via `https` too. When I look at your website it already tries to load the radio via https but this fails since you have no domain on your radio, just an IP address, and as such the radio server only serves a self-signed SSL certificate.

Solution: Add a domain to the radio server then setup `https` via our built-in Let's Encrypt support and include the stream via the domain with https.
