### ISSUE TITLE
One Local Stream no longer works after the last stable update

### ISSUE THREAD

**Issue by Ferz0id** [AzuraCast/AzuraCast#5511]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.0 Stable 

### What happened?

Everything worked flawlessly, but after last update one Local Stream no longer plays. I haven’t changed anything, just addHLS for the test and now I have:

https://edmdnb.com:448/listen/dnb_edm/radio.mp3 **not working**

https://edmdnb.com:448/hls/dnb_edm/live.m3u8 but this works
https://edmdnb.com:448/listen/v2/radio.mp3 This one works too
https://edmdnb.com:448/listen/dnb/radio.mp3 and this one too

Tried to remove broken Mount Point and add it again, but still got the same error.

In Embed Widget and Public Pages not working too:
https://edmdnb.com/
https://edmdnb.com:448/public/dnb_edm

**Comment by Ferz0id** [comment]
Working stream is https://edmdnb.com:8000/radio.mp3 but everywhere (Admin Panel, Embed Widget, Public Page) persist broken link https://edmdnb.com:448/listen/dnb_edm/radio.mp3
![Снимок](https://user-images.githubusercontent.com/44975254/174470150-17812046-2ebf-405e-8326-3bc6267efb36.JPG)

**Comment by Ferz0id** [comment]
In version 0.17.1 everything is the same. I created several mount points for the test - none of them work:

![Снимок](https://user-images.githubusercontent.com/44975254/174537810-02f5b7d6-e428-4e67-9a02-e3d416a1987b.JPG)

**Comment by ItsMitchh** [comment]
Can you provide some Liquidsoap logs please?

**Comment by ItsMitchh** [comment]
These errors appear to be related to liquidsoap, I'll reach out to them and see what we can do.

**Comment by Ferz0id** [comment]
Any news or solution? Maybe completely reinstall it?

**Comment by Ferz0id** [comment]
v0.17.2 all the same

**Comment by Ferz0id** [comment]
no

**Comment by JRB-Prod** [comment]
Holy smokes! Didn't know this was already reported as an issue.

When I click this link [https://edmdnb.com:448/listen/dnb_edm/radio.mp3](https://edmdnb.com:448/listen/dnb_edm/radio.mp3):

> The file you requested could not be found

 ^ This is an important signal of what is going on. This is because this is a message from one of the icecast servers that indicates that a certain page does not exist. It is not a Liquidsoap or Azuracast error. I had the same problem a while ago. Here's what's going on:

You have several stations, one is named 'dnb' and another 'dnb_edm'.
Check the nginx config file for the 'dnb' station. You can find this in the Azuracast admin log info page. Then you need to search for the specific nginx config of your 'dnb' station.
It should contain a line that looks like this:
> location ~ ^(/listen/dnb|/radio/8xxx)(**/?**)(.*)$

As you can see the '/' is optional. So this reverse proxy instance for your 'dnb' station will also catch the web requests for your 'dnb_edm' station and will send among other things '_edm' as an argument (to the wrong Icecast server). One solution is to edit your station profile for your 'dnb' radio. Then you should change the 'URL-Friendly Name' to something like 'dnb_main' or 'dnb_1'. Your 'dnb_edm' station should be fully reachable again.

I think the Azuracast development team should come up with a solution that automatically detects and resolves these kinds of URL name collisions. Should this be seen as a bug?

**Comment by BusterNeece** [comment]
@JRB-Prod Thank you for the detailed report. That made it very easy to identify and fix the issue.

In the latest Rolling Release update that's deploying right now, I've tweaked that regex to be much more specific to the station it's targeting. This should avoid any collision issues with similarly shortcoded stations, and there's no need to modify any stations to work around this issue.

**Comment by Ferz0id** [comment]
Many thanks! All good now.
