### ISSUE TITLE
Problem with non-default stream port. This one is no longer https

### ISSUE THREAD

**Issue by rolradio** [AzuraCast/AzuraCast#5586]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #64e2a48 (2022-07-07 2:30) 

### What happened?

Problem with non-default stream port. This one is no longer https

I have a radio station on my azuracast with a non-standard stream port namely 8443
I modified these in the docker-compose.yml and it has always worked fine.

I now have the problem that when upgrading to Rolling Release #64e2a48 (2022-07-07 2:30)

This non-default stream port no longer becomes https.
both for icecast and shoutcast.

The azuracast proxy links do work.

Example:

https://stream.domain.com/radio/8443/radio.mp3
https://stream.domain.com/listen/myradio/radio.mp3
So these work well.

But the problem now is that both shoutcast and icecast are no longer creating https with a non-default port.

https://stream.domain.com:8443/radio.mp3 is not working
but
http://stream.domain.com:8443/radio.mp3

does work.

Is there another setting I can change to make it work like before?
Or possibly make an adjustment directly in the icecast.xml?

Can someone give me a tip, so that the icecast server works again like: https://stream.domain.com:8443/radio.mp3

Thanks in advance

**Comment by SlvrEagle23** [comment]
@rolradio In recent versions, we switched to using LetsEncrypt directly through the System Settings panel of the web interface instead of through the command line; in most cases, we were able to automatically migrate settings over, but in some cases we weren't. Can you verify that LetsEncrypt is set up correctly via the web interface (i.e. that if you visit the System Settings page, the settings there look correct), and/or try saving that page and clicking the "Generate/Renew Certificate" button?

If the SSL certificates have already properly generated for the main installation, then they should automatically be applying to the Icecast/Shoutcast instances of every station. You may also need to manually restart broadcasting for those instances in the event that doesn't happen automatically for some reason, but once that's done, it should remain in effect for the future.
