### ISSUE TITLE
Songs "Doubling up" in embedded Song History widget.

### ISSUE THREAD

**Issue by Countryman98** [AzuraCast/AzuraCast#5589]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 #64e2a48

### What happened?

90% of songs in the "History" widget have been doubling and sometime tripling up since my upgrade to #[64e2a48].

Songs appear to be playing the once, just showing incorrectly randomly.

![Capture](https://user-images.githubusercontent.com/65417549/178183602-6555b3eb-5346-4f60-a035-34b52f985efa.PNG)

.

**Comment by Countryman98** [comment]
Anyone? Probably an easy fix for someone who knows what they are doing?

**Comment by Countryman98** [comment]
![Capture](https://user-images.githubusercontent.com/65417549/182847916-bf62d6ac-c287-46ce-8ce4-35964be02370.PNG)

Still happening.. Anyone else having this issue? Azuracast: Rolling Release #[2e4ed8e](https://github.com/AzuraCast/AzuraCast/commit/2e4ed8e029cf6dd0add0d9ae10c0a74d336652cc) (2022-07-27 19:00) • Docker • PHP 8.1

**Comment by Countryman98** [comment]
Just to add to this issue: the history widget doubling up doesn't happen when a live connection dj..

**Comment by Countryman98** [comment]
More investigation seems to reveal that the Doubling up in the History widget is happening after a "Hidden Jingle" is Played.

So, Song plays, Jingle Plays, Widget displays previous song again:
![Capture](https://user-images.githubusercontent.com/65417549/185746614-64bad312-e0c8-4e1d-ad65-0f045565be6a.PNG)

Is anyone else seeing this issue with the History widget?

**Comment by BusterNeece** [comment]
@Countryman98 I looked into the current situation with how we're handling and logging jingles, and I did find a few areas that needed fixing, but I wasn't able originally to reproduce this issue on my machine, nor have I seen it since those fixes. It may be worthwhile to update to the latest Rolling Release version and see if it offers any improvement on this front.

**Comment by BusterNeece** [comment]
@Countryman98 We received another report of this same issue, and I was able to take a look at the installation directly. It appears that this is caused by a bug in the "Smart Crossfade" function, which causes it to replay old metadata in situations when it falls back to its "no fade" setting (which just happens to almost always be when a jingle is playing, as they're shorter and thus don't have enough data to calculate smart fades).

On that installation, we confirmed that if you disable crossfading, that it resolves the issue.

I've raised this issue with Liquidsoap directly, as it's up to them to be able to resolve it: https://github.com/savonet/liquidsoap/issues/2611

**Comment by Countryman98** [comment]
> @Countryman98 We received another report of this same issue, and I was able to take a look at the installation directly. It appears that this is caused by a bug in the "Smart Crossfade" function, which causes it to replay old metadata in situations when it falls back to its "no fade" setting (which just happens to almost always be when a jingle is playing, as they're shorter and thus don't have enough data to calculate smart fades).
> 
> On that installation, we confirmed that if you disable crossfading, that it resolves the issue.
> 
> I've raised this issue with Liquidsoap directly, as it's up to them to be able to resolve it: [savonet/liquidsoap#2611](https://github.com/savonet/liquidsoap/issues/2611)

Hey Buster, thanks for the "heads up". 
I can too confirm that the above method does appear to have remedied the issue.
