### ISSUE TITLE
Some features if I allowed to post here

### ISSUE THREAD

**Issue by Roforum** [AzuraCast/AzuraCast#560]
Some features if I allowed to post here.
1. Each radio station admin can edit its own homepage from the admin panel.
2. Each radio station admin has the ability to set up their own custom domain from the admin panel.
3. admin server can set up space/storage for each radio station.

**Comment by SlvrEagle23** [comment]
@Roforum You're definitely allowed to post here!

A few thoughts on your requests:

1. Each station already can specify the station's homepage as part of their profile. If you mean a custom redirect from the AzuraCast homepage, that isn't possible, as a visitor seeing the AzuraCast main page doesn't know which station they're visiting. There's the possibility of doing per-host redirection rules, but that's quite complicated for something that is meant to be a simple feature.
2. You can already point multiple domains to a single AzuraCast instance. If you want the "base URL" setting to automatically switch if you're using a different domain, the setting "Prefer Browser URL (If Available)" will do that for you.
3. This is already an existing issue, #368.

Since item number 3 is the only one that is practical in the immediate term, I'd recommend just following the existing ticket for progress on that.

**Comment by Roforum** [comment]
I apologize for not explaining well.
1. Each radio station admin can edit its own homepage from the admin panel.
 I mean, he can add link, ads, share button and whatever he wants, all from the admin panel.
2. Each radio station admin has the ability to set up their own custom domain from the admin panel.
That is, he can add his own domain to his own radio station. The method can work by adding ns or by registering cname at the register provider, after the domain is added / set from the admin panel.

**Comment by SlvrEagle23** [comment]
@Roforum Forgive me for not understanding, but it seems those items are still answered by the above response.
