### ISSUE TITLE
Any way to ban IP address from song requests?

### ISSUE THREAD

**Issue by Zanarkin** [AzuraCast/AzuraCast#563]
I have a few trolls who make it their mission to request the same song every time the cool down on their request happens. I have it set to 15 minutes and any longer feels like I'm punishing the majority for the sake of stopping the few.

Anyway to add certain IPs to a list that cannot use the request song feature?

**Comment by multi023** [comment]
Hi, 

I would also be interested in knowing how to ban an ip, because in the admin panel, when you click on "Ban List", nothing appears. Neither in other functions like "Help & Documentation", "Bandwidth Usage", "Reserved List" ... When clicking on any option, it always remains in the "Summary" window.

Any idea how I can solve this?

Thank you very much. Greetings,

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/38914/ban-individual-ip-addresses-from-submitting-requests
