### ISSUE TITLE
Playlists does not play forced at scheduled time anymore after update

### ISSUE THREAD

**Issue by wizard-devcenter** [AzuraCast/AzuraCast#5632]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release

### What happened?

I updated azuracast 2 days ago and after update it doesn't force play the playlists at the scheduled time. It worked before. Running Shoutcast with Liquidsoap. I have the option Interrupt other songs to play at scheduled time enabled at every playlist. Like I said, it worked until the update.

**Comment by gmhz** [comment]
- v0.17.1 Stable
- Docker

Same here, at a specific time it does not move to the next playlist files,
but only after a couple of playlist files are played in the current playlist.

- Interrupt other songs to play at scheduled time. - is enabled on all playlists.

**Comment by s7ntax** [comment]
My work around for this.

I created a playlist with a 15 second silent audio file named offair.mp3 that loops indefinitely.

I disable all other playlists other than the one containing the off air silent audio file and restart broadcasting.

Then i enable the playlist I wish to schedule and set the schedule times.

When the playlist is due to play it doesn't interrupt the other songs, but as this is only a 15 second clip of silence it plays the playlist at the end of playing the offair.mp3 file and it continues to play the whole scheduled playlist in order. When I reach the last track of the scheduled playlist I disable the offair playlist and re-enable the main autoplay list that plays music when nothing is being broadcast.

I know it's not ideal but it's how I've got it to work. I tend to broadcast DJ sets in a scheduled playlist on Saturday nights and the rest of the time it plays through old recordings of shows in my big autoplaylist unless someone broadcasts live, in which case there is no problem with interrupting the autoplay. So this kinda works for me, until a solution can be found by the team.

I love this software, even with it's little quirks and bugs, there is always a logical work around and I appreciate the teams hard work on this, best to SilverEagle and i hope things work out for you my friend.

**Comment by wizard-devcenter** [comment]
This isnt a fix, its a complicated work aroud, I am not able to stay and watch and do things all the time at the station. Any fix until now? It worked great before, why doesnt it anymore?

**Comment by s7ntax** [comment]
I have worked out the problem. The playlist priority was the issue I believe.

Make the playlist you wish to schedule higher priority than the playlist that is playing 24/7.

So make the standard autoplay priority 3 and the scheduled playlist priority 5.

I tried this last weekend on the latest version of Azuracast - Docker - Ubuntu 20.04. 

It worked perfectly.

**Comment by LordFader** [comment]
Powered by [AzuraCast](https://www.azuracast.com/) • Rolling Release #[791396f](https://github.com/AzuraCast/AzuraCast/commit/791396fc45df5aee77b7e8ce59d5bdfd16984855) (2022-12-02 15:27) • Docker • PHP 8.1

Interrupt other songs to play at scheduled time. (Edit Playlist>Advanced)
Isn't doing the job...
In my case today it plays 2 more songs until it changed for the next playlist...
This option isn't forcing and the "program/playlist" don't go onAir in the scheduled time.

If this INTERRUPT option is on, it need to override everything what is playing... (eg: the Playlist Weight)
