### ISSUE TITLE
Playlists: Add "Once per hour" scheduling option

### ISSUE THREAD

**Issue by ikedus** [AzuraCast/AzuraCast#565]
heey,

whats the easiest method to setup top of the hour jingles?
i tried this with LOTS of daily playlist.
kinda works but this can be improved.
not the easiest method if you ask me.

**Comment by preterive** [comment]
Close?

**Comment by SlvrEagle23** [comment]
@preterive What does this comment mean?

**Comment by Wishdream** [comment]
Isn't this once per 60 minutes already though?

**Comment by ikedus** [comment]
@Wishdream No, the every x minutes isn't reliable when you want the jingle at time xx:00.

**Comment by SlvrEagle23** [comment]
@ikedus A new "once per hour" playlist would have the exact same playback rules by default as the "once per x minutes" playlists do; that is, it would wait until the end of playback of any current song, then play at the earliest possible scheduled time.

Overriding this to use the stricter mode would currently require enabling Manual AutoDJ (as the AzuraCast AutoDJ won't work in this scenario, since it's only asked what to play next at the end of a song and not partway through) and then configuring the playlist as advanced and setting a specific switch time.

**Comment by SlvrEagle23** [comment]
@ikedus Upon further review, I realized that "once per 60 minutes" may not always run at the exact same minute every hour, so there is indeed value for having a "once per hour at minute x" playlist.

I've created the new "once per hour" playlist type along with recent playlist changes.
