### ISSUE TITLE
docker-compose.override.yml file missing in our latest installation

### ISSUE THREAD

**Issue by ucartz** [AzuraCast/AzuraCast#5667]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

 v0.17.3 Stable • Docker • PHP 8.1

### What happened?

Hello,

We installed azuracast latest stable release ( v0.17.3 Stable )  on Ubuntu . When we trying to setup few streams with custom ports, it wouldn't work and Shoutcast page not loading with " IP:port " 
So we went to look for the docker compose file and not able to locate docker-compose.override.yml . 

while looking into here: https://github.com/AzuraCast/AzuraCast/issues/5191 , It asked us to open a new thread , since its a another issue.

Our other issue is , we need to setup Shoutcast with IP, means IP:8000 or IP:8001 

currently this is what happened, 
port 8000 works
port 8002 don't work
port 8004 don't work
port 8020 works
port 8050 works
port 8052 don't work
port 8054 don't work
port 9090 don't work

### Relevant log output

```shell
root@stream:/var/azuracast# ls
azuracast.env              docker-compose.yml  get-docker.sh
docker-compose.backup.yml  docker.sh
```

**Comment by SlvrEagle23** [comment]
@ucartz That file doesn't exist by default; if you need to add an override, you'll have to create the file in that directory.

Also, by default, AzuraCast assigns stations in a range of 10 ports, i.e. one station uses ports 8000-8009, the next uses 8010-8019, etc. This is due to having to use separate ports for incoming DJ connections and also to reserve other ports for internal station communications.

It's possible to align your stations so they use 8000, 8001, 8002, etc. but as you've discovered, that requires manual Docker configuration and also manual configuration of the stations in the web interface.

**Comment by ucartz** [comment]
//It's possible to align your stations so they use 8000, 8001, 8002, etc. but as you've discovered, that requires manual Docker configuration and also manual configuration of the stations in the web interface.//

can you suggest some article or give the steps to do those . and the file to change.
If you are able to share , we will try to do the same in our end and create a video tutorial or KB article for future use.

**Comment by ucartz** [comment]
Can anyone give some advice ?
