### ISSUE TITLE
Playlists: Allow more granular selection of schedule times than 15-minute increments

### ISSUE THREAD

**Issue by SlvrEagle23** [AzuraCast/AzuraCast#568]

**Comment by Lukahhh** [comment]
Hi there! Just noticed this issue. I recently asked a developer to assist me in building a Node.js scheduler for Liquidsoap. The scheduled items are stored in a redis database, and can be scheduled for any date, including to the minute scheduling.  At the scheduled time, a cronjob runs a telnet command (could also use websocket) to push the file into Liquidsoap's request.queue, which schedules that file to play after the currently playing file ends (think of it as inserting files into the playlist). I use this because I need to insert certain files at certain times during my streams. It can schedule individual files but may be able to trigger playlists with a bit of work.

Would it help with this issue if I made the codebase for the above available for the Azuracast project? :)

**Comment by SlvrEagle23** [comment]
Moved to https://azuracast.featureupvote.com/suggestions/38910/allow-more-granular-selection-of-schedule-times-than-15minute-increments
