### ISSUE TITLE
Cover Display via external HTML5 Player or Winamp

### ISSUE THREAD

**Issue by karndt84** [AzuraCast/AzuraCast#572]
- **Installation Method:** Docker
- **Host OS (if using Docker):** Debian 9
- **Stream: Shoutcast2**

Hello,

I would like to integrate the audio-stream (http://blabla:8000/radio.mp3) to an HTML5 player.
It works wonderfully, but unfortunately only the album-cover is not displayed.
On the "public Page" with your internal Player, it is displayed.
Can you help me?

**Comment by xewl** [comment]
Depending on which libraries you use to create the external audio player, you will have to scour the API-endpoint for that station, and load in the correct parameter.

This is manual work, outside of the scope of this project.

**Comment by SlvrEagle23** [comment]
@karndt84 One of the big reasons the AzuraCast public page exists is so that it can provide you with a working example of how to pull detailed "now playing" data (including playback time, album artwork, etc) from AzuraCast's own API and integrate it with a working player. The code is fairly minimal, and can serve as an example for you to implement your own frontend player.

You can see the full details of the AzuraCast API endpoints [here](http://azuracast.com/api/).
