### ISSUE TITLE
Songs in playlist are playing twice instead of once at specific time

### ISSUE THREAD

**Issue by pawelzet** [AzuraCast/AzuraCast#5734]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.2 Stable 

### What happened?

Sometimes, when my playlist is set to start and end time eg. 13:59 and 13:59, auto dj plays two songs form that playlist instead of one. Could it be sth like this - my autodj queue is too short (sometimes jingles are 7-8sec) and azura autodj isn't able to schedule next songs? My AutoDJ Queue Length is set to: 2. Other thing that I suspect is that autodj has too slow resources. This is my playlist configuration and my server status:
![Screenshot 2022-09-14 at 14 31 18](https://user-images.githubusercontent.com/46452256/190154576-13f6093c-da0b-4930-8ca2-c9a4d7adeeaf.png)
![Screenshot 2022-09-14 at 14 31 29](https://user-images.githubusercontent.com/46452256/190154599-9f46def8-3714-43fb-8ad0-f419b7797939.png)
![Screenshot 2022-09-14 at 14 31 36](https://user-images.githubusercontent.com/46452256/190154600-9158dffb-b866-463d-b133-6604fb4ccb7e.png)
![Screenshot 2022-09-14 at 14 32 02](https://user-images.githubusercontent.com/46452256/190154618-fcbac8c3-2b54-4826-bcb0-cc22f9c66338.png)

**Comment by N4444VX** [comment]
My station plays the National Anthem at noon every day. Worked great until I upgraded to v0.17.3 Stable (Docker/PHP 8.1) and now it has multiple playback of a song from a scheduled playlist containing only that single song. Scheduled time is 11:59/11:59 so it's expected behavior would be one play and then back to AutoDJ. It plays anywhere from 2-5 times and sometimes plays regular AutoDJ tracks and then back to the Scheduled Playlist song a few times.

The Report>Song Playback Timeline shows only one play but it definitely looped 4 times today.

Liquidsoap Config relevant lines:

> playlist_national_anthem = playlist(id="playlist_national_anthem",mime_type="audio/x-mpegurl",mode="random",reload_mode="watch","/var/azuracast/stations/my_mix/playlists/playlist_national_anthem.m3u")
playlist_national_anthem = cue_cut(id="cue_playlist_national_anthem", playlist_national_anthem)
radio = switch(id="schedule_switch", track_sensitive=true, [ ({ 11h58m }, playlist_national_anthem), ({ (6w) and 11h0m-19h0m }, playlist_bluegrass), ({true}, radio) ])




Today's Liquidsoap Log:

> 2022/09/15 11:45:30 [cue_next_song:3] Cueing out...
2022/09/15 11:45:30 [next_song:3] Prepared "/var/azuracast/stations/my_mix/media/gorillaz_-_feel_good_inc._(official_video)-hyhnuvazj-k.mp3" (RID 4370).
[mp3float @ 0x7f62bc474180] Could not update timestamps for skipped samples.
2022/09/15 11:45:30 [cue_next_song:3] Cueing in...
2022/09/15 11:45:30 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2022/09/15 11:45:30 [lang:3] API nextsong - Response (200): annotate:title="Child In Time",artist="Deep Purple",duration="617.00",song_id="7499b163da1be213165213355447b235",media_id="322",liq_amplify="0.00dB",liq_cross_duration="3.00",liq_fade_in="2.00",liq_fade_out="2.00",liq_cue_out="610.40",playlist_id="3":media:deep_purple_-_child_in_time_(1970)-7ujl5rco06g.mp3
2022/09/15 11:45:30 [cross_0:3] Analysis: -39.415589dB / -28.781904dB (2.96s / 2.96s)
2022/09/15 11:45:30 [cross.smart:3] new >= old + margin, old <= medium and new <= high.
2022/09/15 11:45:30 [cross.smart:3] Do not fade if it's already very low.
2022/09/15 11:45:30 [cross.smart:3] Transition: crossed, no fade.
2022/09/15 11:45:30 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {
2022/09/15 11:45:30 [lang:3]   "song_id": "311907069e05676f43a39f59ccec7ef9",
2022/09/15 11:45:30 [lang:3]   "playlist_id": "4",
2022/09/15 11:45:30 [lang:3]   "media_id": "444"
2022/09/15 11:45:30 [lang:3] }
2022/09/15 11:45:30 [lang:3] API feedback - Response (200): true
2022/09/15 11:49:08 [cue_next_song:3] Cueing out...
2022/09/15 11:49:08 [next_song:3] Prepared "/var/azuracast/stations/my_mix/media/deep_purple_-_child_in_time_(1970)-7ujl5rco06g.mp3" (RID 4371).
[mp3float @ 0x7f62bc3b5340] Could not update timestamps for skipped samples.
2022/09/15 11:49:08 [cue_next_song:3] Cueing in...
2022/09/15 11:49:08 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2022/09/15 11:49:08 [lang:3] API nextsong - Response (200): annotate:title="United States National Anthem (Live)",artist="Carrie Underwood",duration="121.00",song_id="4c15cc132cc1c728efb399a79acddeb2",media_id="785",liq_amplify="0.00dB",liq_cross_duration="3.00",liq_fade_in="2.00",liq_fade_out="3.70",liq_cue_out="113.10",playlist_id="12":media:carrie_underwood_sings_national_anthem_before_nashville_predators_playoff_game.mp3
2022/09/15 11:49:08 [cross_0:3] Analysis: -35.002512dB / -32.369452dB (2.96s / 2.96s)
2022/09/15 11:49:08 [cross.smart:3] Old <= medium, new <= medium and |old-new| <= margin.
2022/09/15 11:49:08 [cross.smart:3] Old and new source are not too loud and close.
2022/09/15 11:49:08 [cross.smart:3] Transition: crossed, fade-in, fade-out.
2022/09/15 11:49:08 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {
2022/09/15 11:49:08 [lang:3]   "song_id": "7499b163da1be213165213355447b235",
2022/09/15 11:49:08 [lang:3]   "playlist_id": "3",
2022/09/15 11:49:08 [lang:3]   "media_id": "322"
2022/09/15 11:49:08 [lang:3] }
2022/09/15 11:49:08 [lang:3] API feedback - Response (200): true
2022/09/15 11:59:15 [cue_next_song:3] Cueing out...
2022/09/15 11:59:15 [next_song:3] Prepared "/var/azuracast/stations/my_mix/media/carrie_underwood_sings_national_anthem_before_nashville_predators_playoff_game.mp3" (RID 4372).
[mp3float @ 0x7f62bc154d80] Could not update timestamps for skipped samples.
2022/09/15 11:59:15 [cue_next_song:3] Cueing in...
2022/09/15 11:59:15 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2022/09/15 11:59:15 [lang:3] API nextsong - Response (200): annotate:title="United States National Anthem (Live)",artist="Carrie Underwood",duration="121.00",song_id="4c15cc132cc1c728efb399a79acddeb2",media_id="785",liq_amplify="0.00dB",liq_cross_duration="3.00",liq_fade_in="2.00",liq_fade_out="3.70",liq_cue_out="113.10",playlist_id="12":media:carrie_underwood_sings_national_anthem_before_nashville_predators_playoff_game.mp3
2022/09/15 11:59:16 [cross_0:3] Analysis: -24.662234dB / -16.169455dB (2.96s / 2.96s)
2022/09/15 11:59:16 [cross.smart:3] new >= old + margin, old >= medium and new <= high.
2022/09/15 11:59:16 [cross.smart:3] New source is significantly louder than old one.
2022/09/15 11:59:16 [cross.smart:3] Transition: crossed, fade-out.
2022/09/15 11:59:16 [lang:3] API feedback - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/feedback' with body: {
2022/09/15 11:59:16 [lang:3]   "song_id": "4c15cc132cc1c728efb399a79acddeb2",
2022/09/15 11:59:16 [lang:3]   "playlist_id": "12",
2022/09/15 11:59:16 [lang:3]   "media_id": "785"
2022/09/15 11:59:16 [lang:3] }
2022/09/15 11:59:16 [lang:3] API feedback - Response (200): true
2022/09/15 12:01:05 [cue_next_song:3] Cueing out...
2022/09/15 12:01:05 [next_song:3] Prepared "/var/azuracast/stations/my_mix/media/carrie_underwood_sings_national_anthem_before_nashville_predators_playoff_game.mp3" (RID 4373).
[mp3float @ 0x7f62bc108380] Could not update timestamps for skipped samples.
2022/09/15 12:01:05 [cue_next_song:3] Cueing in...
2022/09/15 12:01:05 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2022/09/15 12:01:06 [lang:3] API nextsong - Response (200): annotate:title="United States National Anthem (Live)",artist="Carrie Underwood",duration="121.00",song_id="4c15cc132cc1c728efb399a79acddeb2",media_id="785",liq_amplify="0.00dB",liq_cross_duration="3.00",liq_fade_in="2.00",liq_fade_out="3.70",liq_cue_out="113.10",playlist_id="12":media:carrie_underwood_sings_national_anthem_before_nashville_predators_playoff_game.mp3
2022/09/15 12:01:06 [cross_0:3] Analysis: -12.838319dB / -16.169455dB (2.96s / 2.96s)
2022/09/15 12:01:06 [cross.smart:3] No transition: using default.
2022/09/15 12:02:58 [cue_next_song:3] Cueing out...
2022/09/15 12:02:58 [next_song:3] Prepared "/var/azuracast/stations/my_mix/media/carrie_underwood_sings_national_anthem_before_nashville_predators_playoff_game.mp3" (RID 4374).
[mp3float @ 0x7f62bc154d80] Could not update timestamps for skipped samples.
2022/09/15 12:02:59 [cue_next_song:3] Cueing in...
2022/09/15 12:02:59 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2022/09/15 12:02:59 [lang:3] API nextsong - Response (200): annotate:title="United States National Anthem (Live)",artist="Carrie Underwood",duration="121.00",song_id="4c15cc132cc1c728efb399a79acddeb2",media_id="785",liq_amplify="0.00dB",liq_cross_duration="3.00",liq_fade_in="2.00",liq_fade_out="3.70",liq_cue_out="113.10",playlist_id="12":media:carrie_underwood_sings_national_anthem_before_nashville_predators_playoff_game.mp3
2022/09/15 12:02:59 [cross_0:3] Analysis: -12.838319dB / -16.169455dB (2.96s / 2.96s)
2022/09/15 12:02:59 [cross.smart:3] No transition: using default.
2022/09/15 12:04:51 [cue_next_song:3] Cueing out...
2022/09/15 12:04:52 [next_song:3] Prepared "/var/azuracast/stations/my_mix/media/carrie_underwood_sings_national_anthem_before_nashville_predators_playoff_game.mp3" (RID 4375).
[mp3float @ 0x7f62bc3f3fc0] Could not update timestamps for skipped samples.
2022/09/15 12:04:52 [cue_next_song:3] Cueing in...
2022/09/15 12:04:52 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2022/09/15 12:04:52 [lang:3] API nextsong - Response (200): annotate:title="United States National Anthem (Live)",artist="Carrie Underwood",duration="121.00",song_id="4c15cc132cc1c728efb399a79acddeb2",media_id="785",liq_amplify="0.00dB",liq_cross_duration="3.00",liq_fade_in="2.00",liq_fade_out="3.70",liq_cue_out="113.10",playlist_id="12":media:carrie_underwood_sings_national_anthem_before_nashville_predators_playoff_game.mp3
2022/09/15 12:04:52 [cross_0:3] Analysis: -12.838319dB / -16.169455dB (2.96s / 2.96s)
2022/09/15 12:04:52 [cross.smart:3] No transition: using default.
2022/09/15 12:06:45 [cue_next_song:3] Cueing out...
2022/09/15 12:06:45 [next_song:3] Prepared "/var/azuracast/stations/my_mix/media/carrie_underwood_sings_national_anthem_before_nashville_predators_playoff_game.mp3" (RID 4376).
[mp3float @ 0x7f62bc2aae00] Could not update timestamps for skipped samples.
2022/09/15 12:06:45 [cue_next_song:3] Cueing in...
2022/09/15 12:06:45 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2022/09/15 12:06:45 [cross_0:3] Analysis: -12.838319dB / -16.169455dB (2.96s / 2.96s)
2022/09/15 12:06:45 [cross.smart:3] No transition: using default.
2022/09/15 12:06:45 [lang:3] API nextsong - Response (200): annotate:title="United States National Anthem (Live)",artist="Carrie Underwood",duration="121.00",song_id="4c15cc132cc1c728efb399a79acddeb2",media_id="785",liq_amplify="0.00dB",liq_cross_duration="3.00",liq_fade_in="2.00",liq_fade_out="3.70",liq_cue_out="113.10",playlist_id="12":media:carrie_underwood_sings_national_anthem_before_nashville_predators_playoff_game.mp3
2022/09/15 12:08:38 [cue_next_song:3] Cueing out...
2022/09/15 12:08:38 [next_song:3] Prepared "/var/azuracast/stations/my_mix/media/carrie_underwood_sings_national_anthem_before_nashville_predators_playoff_game.mp3" (RID 4377).
[mp3float @ 0x7f62bc3f3fc0] Could not update timestamps for skipped samples.
2022/09/15 12:08:38 [cue_next_song:3] Cueing in...
2022/09/15 12:08:38 [lang:3] API nextsong - Sending POST request to 'http://127.0.0.1:6010/api/internal/1/liquidsoap/nextsong' with body: 
2022/09/15 12:08:38 [lang:3] API nextsong - Response (200): annotate:title="#1 Zero",artist="Audioslave",duration="298.00",song_id="f0bbf679a6e2cc2060a0f469bd81c559",media_id="201",liq_amplify="0.00dB",liq_cross_duration="3.00",liq_fade_in="2.00",liq_fade_out="2.00",liq_cue_out="290.70",playlist_id="3":media:11_1_zero.mp3
[mp3 @ 0x7f62b80ee240] Estimating duration from bitrate, this may be inaccurate
[mp3 @ 0x7f62b80ee240] Estimating duration from bitrate, this may be inaccurate
2022/09/15 12:08:38 [cross_0:3] Analysis: -12.838319dB / -16.169455dB (2.96s / 2.96s)
2022/09/15 12:08:38 [cross.smart:3] No transition: using default.
2022/09/15 12:10:31 [cue_next_song:3] Cueing out...

What the Song Playback Timeline shows:

![image](https://user-images.githubusercontent.com/11199861/190457043-5d962a87-3c71-4578-8b62-5741289a2a2f.png)

**Comment by pawelzet** [comment]
I think I have managed to fix this issue - I've upgraded azuracast to the newest stable version 0.17.3 and ticked the option Loop once in scheduling window, and set azuracast autodj queue to 5. It only happened with short tracks on playlist. playlist containing short tracks.
