### ISSUE TITLE
Clone functionality is broken for a station that has media files

### ISSUE THREAD

**Issue by alexey-v-paramonov** [AzuraCast/AzuraCast#5796]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.3 Stable

### What happened?

"Clone" functionality with "Share Media Storage Location" is not working for a station that has media files (it was workign while it had 0 files in it).
Steps to reproduce:
1. Create station.
2. Upload a file, start streaming. All good, icecast is working, I can hear my file playing.
3. Go to station administration and try to "clone" that station with "Share Media Storage Location" option enabled.

Screenshot:
https://ibb.co/4VFHhXd 

### Relevant log output

```shell
ORMInvalidArgumentException at /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php L100: A new entity was found through the relationship 'App\Entity\Station#current_song' that was not configured to cascade persist operations for entity: StationMedia 1f92319c9aeef1d4c64852c5: DJ Mike Llama - Llama Whippin' Intro. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}).
```

**Comment by julianborghuis** [comment]
Same problem!

**Comment by BlueRooz** [comment]
I am having the same issue. Stopped me in my tracks. PLEASE FIX! Thanks!!!

**Comment by BusterNeece** [comment]
If you all are new to AzuraCast and unfamiliar with our release channels, let me explain: we have two channels, the "Stable" channel (which has much fewer updates, but only publishes periodically, once we've had a long period of stable operation on our rolling branch) and the "Rolling Release" channel, where we actually work on fixing bugs and push updates quite a lot more often.

This specific issue was already fixed on Rolling Release quite some time ago. You can tell by reading the `CHANGELOG.md` file in the base of our repo, as it's listed as a fixed bug there.

If you have an urgent need for a feature that isn't quite working in Stable but is fixed in Rolling, it's strongly recommended that you switch over to the Rolling Release channel at least until the next stable release.

In this case, since we've had enough time since our last stable release, I'm tagging a new 0.17.4 stable release, which is deploying this morning, so you can stay on the stable channel and update to benefit from this fix among many others.

**Comment by BlueRooz** [comment]
Thank you, Buster! I’m brand new. Really appreciate the detailed response. Impressive!

**Comment by BlueRooz** [comment]
@BusterNeece Thank you, Buster! I’m brand new. Really appreciate the detailed response. Impressive!

**Comment by alexey-v-paramonov** [comment]
@BusterNeece sure, I understand the difference between those types of releases. I was using the stable one, as reported in my initial report. Glad new stable is out, appreciate that!
