### ISSUE TITLE
ngnix on different port

### ISSUE THREAD

**Issue by athensguy** [AzuraCast/AzuraCast#581]
I have tried to assign custom port for  azuracast-nginx container by modifying the port value at the docker-compose.yml as  while it did not work. Should I change the ngnix config file inside container as well?

I need to run Azuracast but as container on a host already uses port 80

**Comment by SlvrEagle23** [comment]
@athensguy Did you make sure to only modify the first part of the port pair, i.e. `81:80` instead of `81:81`? The second number should always stay the same.

Also, you have to restart the `nginx` container for the changes to take effect, via `docker-compose kill nginx && docker-compose up -d nginx`.
