### ISSUE TITLE
Playlist "Schedule View" showing playlist in wrong slot after switch to winter time

### ISSUE THREAD

**Issue by guiltlab** [AzuraCast/AzuraCast#5824]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #53080b1 (2022-08-23 4:36)

### What happened?

I have a problem since we switched to winter time a few days ago: my public schedule did not make the change correctly. This problem is only present on Firefox, out of the 3 browsers I tried (Chrome and Edge display the correct schedule).

I'm on europe/paris, gmt+1, azuracast shows the correct time (12:53 at the time of screenshot). The public schedule time indicator (red line) also shows the correct time (12:53). But the japanese music playlist is supposed to end at 13:30 (and it does), yet the slot on the schedule shows it as ending at 12:30. Basically everything is correct in the way it works, but the visual slots are wrong (yet the current time indicator is correct).
![unknown 1](https://user-images.githubusercontent.com/45518224/199491959-feadc5e2-2f57-4314-9692-f1c6d73d7219.png)

Firefox knows my correct timezone (console output of new Date().toString() => GMT+0100 (Central European Standard Time) , same result by using https://everytimezone.com/ ) yet the problem persists, even after clearing cache & trying in private browsing window.

Vaalyn confirmed on Discord that it seems to be a bug, as they see the same thing on one of their test stations.

Thanks in advance :)

**Comment by Vaalyn** [comment]
I have noticed that this is somehow caused by the user accounts language setting.

When setting the users language to German the playlists are shown in the correct slots:

![image](https://user-images.githubusercontent.com/13745863/199495136-ce31ff2f-ada6-43a7-8502-f50b639b4dc6.png)

But when changing the language to English they are shown in a slot too early:

![image](https://user-images.githubusercontent.com/13745863/199495263-f1f9fb67-e9ab-4b49-b559-d49e9a74ad16.png)

**Comment by fnfzlznddzn** [comment]
Somehow this problem fixed itself for me... I did not do anything particular AFAIK, did not restart Docker/azuracast/my server.
