### ISSUE TITLE
AzuraCast Error Time Remaining

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#588]
- **Installation Method:** Traditional

The REST API sometime responds with incorrect data to do with Times such as 'Remaining, Elapsed and Played_at'

https://imgur.com/a/hEqriQO

**Comment by SlvrEagle23** [comment]
@Ilario42 Unfortunately, at the moment I don't have enough information about this problem to be able to effectively diagnose or remedy it. Some songs may play a second or two longer than their stated duration, and sometimes the remaining time will show as zero briefly due to the gap between the end of a track and the next scheduled "synchronization" task, where AzuraCast checks what's playing. This part of the system is rather complex and may vary significantly depending on how your station is set up, so without much more detailed information it isn't possible for me to resolve this issue at the moment.
