### ISSUE TITLE
Requested songs are not playing after the current one finishes

### ISSUE THREAD

**Issue by rursache** [AzuraCast/AzuraCast#5941]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.6 Stable

### What happened?

With AutoDJ enabled, request a song.
Instead of being played after the current one finishes, it will actually play after the current + another 2 songs finishes.

Shouldn't the requested song play the moment the current one finishes? 
I can reproduce this everytime.

Current relevant settings:
Request Minimum Delay (Minutes): 0
Request Last Played Threshold (Minutes): 0
AutoDJ Queue Length: 2

### Relevant log output

```shell
Not sure which are the relevant logs here
```

**Comment by fnfzlznddzn** [comment]
This is more a feature request than a bug report tbh. I also wish it was possible to have the requested song immediately after the current one, but this is not how it works currently. I suppose it would be reasonably feasible to queue the requested song as n+2 (after the current and next one) instead of n+3 (current minimum possible, with AutoDJ queue length of 2), as this is what happens if you queue it yourself from the azuracast internal dashboard. On the other hand, I think queuing the requested song as the *immediate* next one would be more complicated, as the next one is already loaded by Liquidsoap and you can't delete if from the queue in https://your.site/station/id/queue .

**Comment by rursache** [comment]
I understand the reasoning but it's pretty illogical to work as it does now. 
It would be better if the requested song will play after the next one in queue (the one that cannot be removed). 

Is there a reason why the minimum AutoDJ queue length is 2 instead of 1? It seems like 1 is the minimum because of the "next song" feature but why it's 2?
