### ISSUE TITLE
Radio Relay Icecast

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#598]
I opened a radio with the icecast system in relay mode. Even on the [demo site](https://demo.azuracast.com/) it doesn't work.

**Comment by SlvrEagle23** [comment]
@ckeurk I don't have nearly enough information here to be able to diagnose the issue or to begin to troubleshoot what's causing the problem, or even if it has anything to do with AzuraCast and not Icecast itself.

Please provide the specific steps you're using to set up a relay station, including (if possible) an example URL that isn't working properly, so I can test things on my end and see what the problem is.

**Comment by ckeurk** [comment]
Creating a new radio using the icecast system
![edit profile - azuracast 2018-06-06 07-22-18](https://user-images.githubusercontent.com/379099/41018674-43d307ce-695b-11e8-9741-f88be2f8aa51.png)

Creating the radio mounting point in relay mode
![edit mount point - azuracast 2018-06-06 07-22-45](https://user-images.githubusercontent.com/379099/41018610-ec35cc54-695a-11e8-8b54-e9a58fd6b3b8.png)

No stream is playing
![profile - azuracast 2018-06-06 07-23-25](https://user-images.githubusercontent.com/379099/41018733-99364dd4-695b-11e8-9fe5-ce563d276fa0.png)

I tried on the demo site, and the result is the same [demo.azuracast.com](https://demo.azuracast.com/)

**Comment by ckeurk** [comment]
[icecast_error.log.zip](https://github.com/AzuraCast/AzuraCast/files/2074890/icecast_error.log.zip)

**Comment by xewl** [comment]
The relay URL can't be set to the `/radio/{port}/endpoint` URL as they're proxied by nginx.
Please try: http://217.182.128.137:8000/rdu.mp3

**Comment by ckeurk** [comment]
It's cool. It works. Thank you
