### ISSUE TITLE
Custom http-headers in Icecast

### ISSUE THREAD

**Issue by gunsar** [AzuraCast/AzuraCast#6001]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.6

### What happened?

Custom xml (in Custom Frontend Configuration menu) for Main header for verification of owner of a stream at https://www.radio-browser.info/owners was not successful

### Relevant log output

```shell
[2022-12-23  06:33:57] WARN xml/parsing warning: 
[2022-12-23  06:33:57] WARN xml/parsing unknown element "http-headers" parsing "mount" at line 31
```

**Comment by Vaalyn** [comment]
AzuraCast uses the Icecast-KH fork of Icecast in version kh15.

The `http-headers` element was first introduced in Icecast 2.4.1 and is not yet available in the [releases](https://github.com/karlheyes/icecast-kh/tags) of Icecast-KH.

As far as I'm aware it will be available in kh17 going by [this thread](https://github.com/karlheyes/icecast-kh/issues/373) on the Icecast-KH repository.

**Comment by gunsar** [comment]
@Vaalyn 
if we look at https://www.radio-browser.info/owners
Apart from setting the header in icecast.xml, we can also set it in the Nginx config. maybe there is another way using the settings in the nginx. But I don't understand for custom nginx on azuracast.

**Comment by BusterNeece** [comment]
We've updated the Icecast-KH version we use in our Docker images to be the latest dev branch from Icecast-KH itself (rather than our fork, as they've incorporated all the code changes we need into the main repo).

Support for custom HTTP headers should now be possible via custom Icecast configuration in the latest AzuraCast rolling releases.
