### ISSUE TITLE
when https port changes, and halways https is enabled, azuracast doesnt make proper redirect.

### ISSUE THREAD

**Issue by nunotfc** [AzuraCast/AzuraCast#6024]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

6ef72c6 (2023-01-14 8:04) • Docker • PHP 8.2

### What happened?

when you enable the halways use https, and you change the https port to for example 8443, the browsers give ssl protocol error, because automatically is redirecting to https, even with you use alternate http port, that is correct. but doesnt pass the new https port as a paramether. for example, https://stream.mydomain.com:8443, and the server understands to search in 443 port.

**Comment by BusterNeece** [comment]
@nunotfc Hmm, well the problem is that most of the time when someone puts AzuraCast on a different port than 80/443, it's because they have a proxy in front of it, and they actually intend to use AzuraCast on the main web ports. It's likely that the best way to fix an installation that _always_ uses a custom port would be to put that port number in the base URL itself in the System Settings.

**Comment by nunotfc** [comment]
hello, i really understand what you are saying. bbut, let me ask, i have to put 8443 or 8080 in the base url? it's because at the moment i have 8443 in the base url, the problem is when i use http://mydomain.com:8080, chomre gives error.

**Comment by Moonbase59** [comment]
If you want to use http: besides https:, did you check that _System Maintenance → System Settings → Security & Privacy → [_] Always use HTTPS_ is unchecked?

Then again, if the HTTPS port is in the base URL, it might use that _always_. At least it _seems_ to, in my installation where I currently use an appended `:8080` in the base URL because of the "getting a cert on non-standard ports" problem.
