### ISSUE TITLE
Metadata live broadcast

### ISSUE THREAD

**Issue by radiopiraat** [AzuraCast/AzuraCast#6034]
When i connect with breakaway one this is sending the metadata automaticly, the text live broadcast appears instead of the metadata from the stream program.
A few updates ago it was working good.

Is it an option to create a check box in the menu, if you want this text wanna be displayed?

      https://user-images.githubusercontent.com/122891217/212922912-7267f525-b71e-4c36-b999-c3b5b5d5a6f7.mp4

_Originally posted by @DJEclypse in https://github.com/AzuraCast/AzuraCast/discussions/6030_

**Comment by Moonbase59** [comment]
Did you try waiting for the first stream metadata change?

Due to an upstream problem, AzuraCast might not be able to pick up the metadata of the first song played, and displays "Live Broadcast" instead.

In my test installation (rolling, latest) it usually updates (at latest) with the next song change, or if the metadata is re-sent after a few seconds.
