### ISSUE TITLE
Shoutcast password

### ISSUE THREAD

**Issue by amingomezd** [AzuraCast/AzuraCast#606]
- **Installation Method: Traditional
- **Host OS (if using Docker):Ubuntu 14.04

**Describe the issue in full detail, including screenshots if possible:**

Where do i have to put the shoutcast password?
<img width="873" alt="captura de pantalla 2018-06-06 a la s 2 50 41 p m" src="https://user-images.githubusercontent.com/24884401/41061816-81b61e9e-6999-11e8-91ca-173870db787f.png">

in the radio mountpoint there is an option for:
Remote Station Base URL
Remote Station Mountpoint/SID

But not for the password, i've tried putting the password in the sid (abcde:#123456) but it won't work, i've tried using BUTT and it connects the the shoutcast server, but i cannot connect azuracast to them, can you please help me?

**Comment by jrsarath** [comment]
Can you repeat what are actually trying to achieve using azuracast and original problem related to azuracast ?

**Comment by amingomezd** [comment]
i have a ec2 nano instance (512 ram, 8gb), i don't want that the radio listeners connect directly to my server, instead i created a shoutcast account, and i want to stream my station to shoutcast and then to the radio listeners. The problem is that azuracast cannot connect to shoutcast with the password, or i don't know how to do it.

**Comment by jrsarath** [comment]
I think thats why Author gives user a option on station settings page weather you want to use local streaming server (icecast/Shoutcast) or a remote server.. 
for your case i think you should go with remote streaming server.. if im wrong then author will help you out for sure

**Comment by amingomezd** [comment]
yes, i select remote server but, in the remote shoutcast settings there is no option for stream password, only for autodj password

**Comment by jrsarath** [comment]
Possible to share your screen ? here is my email id jrsarath@outlook.com

**Comment by jrsarath** [comment]
as i saw the settings for remote streaming server 
i assume that you can connect to remote icecast or a remote Shoutcast server with valid settings.

**Comment by SlvrEagle23** [comment]
@amingomezd In order to broadcast from an AzuraCast instance to a remote server, you should visit the "Mount Points" page and create a new mount point once your station has been set to broadcast to a remote server.

On the new mount point settings, you will see "Source username" and "Source password"; these correspond to your Stream ID and stream password from the screenshot above.

This should allow you to use AzuraCast to control your media, but to broadcast to the Shoutcast online streaming service.

Let me know if you have any further questions or encounter any issues.
