### ISSUE TITLE
fix the crossfades

### ISSUE THREAD

**Issue by radiobellissima** [AzuraCast/AzuraCast#6117]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #768d577

### What happened?

Hi, I've been using the software for my stations for a long time. Since liquidsoap was updated I've been forced to drop it as an auto dj and use it as a relay to keep my current broadcast addresses. All this because of the crossfades that are no longer customizable and become very ugly. Months later I tried again with a test radio to see if anything had changed but unfortunately I still see that nothing works as it should. I would like to be able to use this autodj complete again to avoid double passes and keep 2 software active. So I'm wondering if anyone has come up with a workaround or setup to be able to fix the crossfades.

Thanks
Marcello

**Comment by Moonbase59** [comment]
No offence, but it is hard to know what you mean with "fix the crossfades". What _exactly_ should be fixed? The sudden volume jump at the crossing point (at least on replaygained material)? The "not-so-radio-like fading"? Something else?

I don’t want to mess up my evaluation station, but it’s probably the best to set up a separate LiquidSoap instance locally, devise a minimum working example to reproduce the problem, try to find the fault, and report back to the LS devs.

I suspect the "volume jump at crossing point" a bug with the latest LS, maybe to do with replaygain. I programmed several rather complicated stations with LiquidSoap 1.4 in the past, and never had that problem. Unfortunately I currently don’t have the spare time to investigate this.

**Comment by radiobellissima** [comment]
For me, like the majority, it would be enough for it to work like the old liquisoap version that set it as you wanted with 2 settings. If you don't succeed, at least get rid of the ugly fade-in.

**Comment by Moonbase59** [comment]
Still not clear to me what you mean by "the ugly fade-in".

To avoid the fade-in, I use a brute-force ugly workaround and modify the LiquidSoap using the UI tools. Just before the crossfade section I have:

```
def live_aware_crossfade(old, new) =
    if !to_live then
        # If going to the live show, play a simple sequence
        sequence([fade.out(old.source),fade.in(new.source)])
    else
        # Otherwise, use the smart transition
        cross.simple(old.source, new.source, fade_in=0.00, fade_out=2.00)
    end
end

radio = cross(minimum=0.0, duration=3.0, live_aware_crossfade, radio)
```

Note I currently use `cross.simple`, not `cross.smart`, since it produces less volume jumps at the crossing point, but the code above is easily adapted. It provides for a 2s fade-out and no fade-in. You’ll have to edit the fade points for jingles, of course (set to 0).

**Comment by radiobellissima** [comment]
I tried this solution but unfortunately the fade in remains the same. Instead in the old version before updating LS it worked perfectly.

**Comment by Moonbase59** [comment]
@gunsar Yep, LS 1.4 was really rock-solid. Ran several stations off it over many years.

@radiobellissima I almost don’ŧ dare to ask, but you _did_ restart broadcasting after making the change in the LiquidSoap configuration? I just verified above change again on Rolling Release #[5cbf9c9](https://github.com/AzuraCast/AzuraCast/commit/5cbf9c91cae1a234c428cf43d769fe2349e05bd9) (2023-02-28 8:15) and it works here. Even recorded the stream and opened the recording in Audacity to visually check. (Because I also can’t stand the non-radio-like fade-ins…)

**Comment by radiobellissima** [comment]
Rolling Release #[25e3b93] (2023-02-27 20:47)
This is my version and if they haven't fixed it tonight it won't work on any of the stations. Of course restarted. Only working solution is to use advanced mix points on each file

**Comment by Moonbase59** [comment]
Still experimenting, but it seems I’m at a loss: `cross.simple` seems not to respect `fade_in`, and `cross.smart` _does_ but often produces unbearable volume jumps at the crossing point. Wanted to show a screenshot, but of course the demonstration effect hits in and it didn’t happen (yet)…

My gut feeling says maybe the volume jumps are due to applying replay gain on "new" too late, or maybe the power computing window isn’t large enough… Who knows, except maybe the LS devs…

Here’s my current experiment, if anyone cares to follow:

```
def live_aware_crossfade(old, new) =
    if !to_live then
        # If going to the live show, play a simple sequence
        sequence([fade.out(old.source),fade.in(new.source)])
    else
        # Otherwise, use the smart transition
        cross.smart(old, new, fade_in=0.00, fade_out=2.00)
    end
end

radio = cross(minimum=2.0, duration=5.0, live_aware_crossfade, radio)
```

Maybe we’ll have to wait for LS 2.2.0, or talk to [toots](https://github.com/toots)…

**Comment by radiobellissima** [comment]
There must be a way to make it work because actually setting fade-in 0 in the advanced options this is respected. The problem is inserting 0 in 5000 or more files. If you could figure out where to put that 0 I think everything will be fine. Let's hope for some updates from LS or from the Azuracast team. :-)

**Comment by amacleod457** [comment]
If you set the crossfade to smart, rather than normal, the annoying fade-ins don't occur. Although it still is a pretty bad solution. Very inconsistent and uneven.

**Comment by guiltlab** [comment]
> Still experimenting...
Thank you for trying. I'm definitely following your comments on the matter. I also use Replaygain with normal crossfade mode, and I also experience jumps in volume sometimes, which is very annoying. I'd expect ReplayGain to precisely prevent this from happening, but it does not. If you find a good solution, please do post it somewhere (in a Discussion perhaps)... Although this is not precisely the matter of this issue. I'm also interested in disabling fade-in entirely, however.

**Comment by radiobellissima** [comment]
> > Still experimenting...
> 
> Thank you for trying. I'm definitely following your comments on the matter. I also use Replaygain with normal crossfade mode, and I also experience jumps in volume sometimes, which is very annoying. I'd expect ReplayGain to precisely prevent this from happening, but it does not. If you find a good solution, please do post it somewhere (in a Discussion perhaps)... Although this is not precisely the matter of this issue. I'm also interested in disabling fade-in entirely, however.
> 
> I have an automated way to set fade values to zero for all files in advanced options, using the API (tested on jingles files, seems to work fine) but it's definitely not an ideal solution.

It would already be something to set 0 on all files and then edit the rest calmly later. Could you publish your solution via API let's see if I can use it.

Grazie

**Comment by guiltlab** [comment]
> It would already be something to set 0 on all files and then edit the rest calmly later. Could you publish your solution via API let's see if I can use it.
> 
> Grazie

I'm afraid it's not optimal, since I wrote it as a command for my (currently private) fork of https://github.com/TwixGamer00/Azuri


Constants (replace with your infos) and variable to declare
```
const api = process.env.API_URL
const apikey = process.env.API_KEY
const stationId = process.env.STATION_ID
var jinglesArray
```

The details to update, maybe you only want fade_in and not the others.
```
const disableCrossfade = {
    "fade_overlap": 0,
    "fade_in": 0,
    "fade_out": 0,
}
```

Function to get info for all the files in the playlist
```
async function getJingles() {
    return await axios.get(`${api}/station/${stationId}/files/list?searchPhrase=playlist:${jinglePlaylist}`,
        {
            headers: {
                "X-Api-Key": apikey
            },
        })
        .then((response) => {
            return jinglesArray = response.data
        }, (error) => {
            console.log(error)
        })
}
```
Function to apply the crossfade details to a file
```
async function noCrossfade(jingleID) {
    return await axios.put(`${api}/station/${stationId}/file/${jingleID}`, disableCrossfade,
        {
            headers: {
                "X-Api-Key": apikey
            },
        })
        .then((response) => {
            console.log("Command sent. Response: " + response.data.success);
        }, (error) => {
            console.log(error)
        })
}
```

and the executing part of the code:

```
                    await getJingles();
                    console.log(jinglesArray.length + " items will be processed")
                    if (jinglesArray && jinglesArray.length > 0) {
                        let jingleID
                        for (let i = 0; jinglesArray.length > i; i++) {
                            jingleID = jinglesArray[i].media.media_id
                            await noCrossfade(jingleID)
                            console.log("Finished " + jingleID + " - Waiting 20 sec until next jingle.")
                            // wait 20 seconds before continuing loop.
                            await new Promise(resolve => setTimeout(resolve, 20000));
                        }
                    }
                    message.react("👍")
                    console.log("Job finished. Crossfade disabled for all jingles.");
```
Hopefully you can adapt this to your needs even if it's not ready for consumption...

**Comment by Moonbase59** [comment]
@guiltlab I somehow suspect they overlooked something at LS. In theory, nothing should be easier than `amplify` a song stream by the replaygain value and THEN xfade it. Instead they look a few seconds to the "left" and the "right", try to calculate volumes based on a power calculation window … and fail. Resulting in horrible loudness jumps at the crossing point.

But maybe _I’m_ overlooking something and it’s required for some other purpose.

**Comment by Moonbase59** [comment]
I filed an issue over at LiquidSoap. Hopefully someone from over there can chime in and help.

**Comment by Moonbase59** [comment]
@gunsar Yep, 2.1.4 looks a lot better. Still volume jumps sometimes, but overall much more often the decision to "not fase", or fade correctly. Not perfect yet, but better.

**Comment by manueldev** [comment]
Considering that there is no solution yet, how can I install a previous version of azuracast with docker?

**Comment by radiobellissima** [comment]
> Considering that there is no solution yet, how can I install a previous version of azuracast with docker?

This would be wonderful news if someone could explain how. Many things worked better in the old version.

**Comment by manueldev** [comment]
> > Considering that there is no solution yet, how can I install a previous version of azuracast with docker?
> 
> This would be wonderful news if someone could explain how. Many things worked better in the old version.

For now I am using the "Rolling Release" version with "normal mode" crossfade in 0.1 seconds duration. It doesn't sound perfect but it's better than nothing.

**Comment by radiobellissima** [comment]
We say that we are trying the most disparate solutions, unfortunately there is no solution. We are trying to edit all mix points with fade to 0 in normal mode. It is not always respected but better than nothing given the non-solutions available. Among other things we ran into a big problem that playlist 1 per song is absolutely not respected and this is an even more serious problem for programming. Unfortunately I believe that we will soon resume with live useless to insist if there are no solutions.

**Comment by BusterNeece** [comment]
@radiobellissima The folks here are trying to help out with workarounds. I'd encourage you to try them out if you can, to see if they help with anything.

As for the original problem here, as has been mentioned on here before, the issue is very, very likely "upstream" from us, with Liquidsoap itself. I would recommend taking this issue up on their GitHub (https://github.com/savonet/liquidsoap).

If they issue any recommendations for how we can change our auto-generated Liquidsoap code, we'll be happy to apply those changes. Likewise, if they update Liquidsoap itself to incorporate new fixes, we can update our own version to match that. That is all we're able to do on the AzuraCast side.

**Comment by radiobellissima** [comment]
@BusterNeece In fact I suggested inserting the cross fade in to 0 directly on the single file editor and not using smart mode. It is a good compromise even if it is not always respected.
