### ISSUE TITLE
File storage locations

### ISSUE THREAD

**Issue by wmfinck** [AzuraCast/AzuraCast#6123]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.17.7 Stable • Docker • PHP 8.2

### What happened?

Media file storage locations are not those seen in the station profile. I have attached a screenshot. 

The station profile has: /var/azuracast/stations/{BASE STATION DIRECTORY}

But the data is actually stored in: /var/lib/docker/volumes/azuracast_station_data/_data/{BASE STATION DIRECTORY} 

Of course, I understand that not all users may have root access. But I had to upload a file, go to an SSH shell, and run a "find" command for the filename in order to discover the actual location of the files. This was necessary so that I could use rsync to transfer my media from another server, as FTP from my desk is far too slow.

This is not a problem going forward, but only because I was able to figure out the actual location and should not need to change it in the station profile.

**Comment by wmfinck** [comment]
This is the screenshot:

![Screenshot 2023-02-28 at 13-05-11 Edit Profile](https://user-images.githubusercontent.com/26745722/221944028-010dfbca-9fc4-4207-a674-65a43b3c18c1.png)

**Comment by wmfinck** [comment]
Here is a screenshot of the Filezilla window logged in as root.

![Untitled](https://user-images.githubusercontent.com/26745722/221945010-f0a3327b-945f-44d2-b502-f31e0b490fc7.jpg)

**Comment by BusterNeece** [comment]
@wmfinck This is not a bug at all, but rather just how Docker works fundamentally.

In order to ensure Docker can properly manage permissions of its own files, we use Docker's own "virtualized" filesystem inside the container where AzuraCast runs. Generally, you can indeed find those files on the "host" operating system at the location you specified, but it's not advised to directly manipulate those files there. Instead, we offer a built-in SFTP server that exposes your files from within the virtualized Docker filesystem, ensuring permissions remain intact. I'd recommend using that if possible.
