### ISSUE TITLE
Azuracast fades between live broadcast and auto dj

### ISSUE THREAD

**Issue by Chrisx84** [AzuraCast/AzuraCast#6156]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.17.7

### What happened?

Every time a friend streams on my station, their stream fades in and out with the auto dj till i go reboot the server. They stay stable for afew hours then happens again.

**Comment by stickbear2015** [comment]
Hello,
In order to diagnose weather this is a server/installation issue or an issue on the broadcaster's end the developers need log output to make this determination.
I know I'm not a developer, but this issue provides little to no actionable information to even begin to diagnose where the issue lies.
Can you provide relevant log output per the instructions on the
[logs](https://docs.azuracast.com/en/user-guide/logs) page that's referenced from the [reporting a bug](https://docs.azuracast.com/en/contribute/report-a-bug) page?
This information will greatly assist us fellow users and the developers in helping determine where the issue lies.
Also, if you've yet to check the [troubleshooting](https://docs.azuracast.com/en/user-guide/troubleshooting) page, this may be a good place to start. I suspect nothing on that page will help you, but the previous links to the log page, and the reporting a bug page will greatly assist us.

**Comment by Chrisx84** [comment]
2023/04/05 16:59:56 [clock.main:2] We must catchup 10.08 seconds!
2023/04/05 16:59:56 [input.http_0:2] Feeding failed: Avutil.Error(Connection timed out)
2023/04/05 16:59:56 [buffer.consumer_0:3] Source failed (no more tracks) stopping output...
2023/04/05 16:59:57 [clock.main:2] We must catchup 0.96 seconds (we've been late for 100 rounds)!

Thats all i could find after it did it again yesterday

**Comment by Chrisx84** [comment]
2023/06/14 18:09:44 [input_streamer:3] Buffer overrun: Dropping 0.03s. Consider increasing the max buffer size!
still having the issue with 6 listeners and a live dj
