### ISSUE TITLE
webhook now playing to twitter and tunein out of sync

### ISSUE THREAD

**Issue by gunsar** [AzuraCast/AzuraCast#6159]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #4cd3f65 (2023-03-17 23:05)

### What happened?

webhook now playing is out of sync

I have 3 mountpoints

1 /stream (main mountpoint - no autodj)
1 /flac (select mountpoint - no autodj)
1 /mp3 (selected mountpoint - with autodj)

when mounting the mountpoint for /stream to twitter & tunien, the metadata doesn't match. metadata sent instead from mountpoint /mp3

how to solve this?

**Comment by BusterNeece** [comment]
I expect that this is by design, at least in the newest versions of AzuraCast. If you're using the AutoDJ, then we expect the AutoDJ to be the authoritative source of "what's now playing" (as DJs should be connecting through it as well, not directly to Icecast, in our recommended setup), overriding whatever information we get from the actual broadcasting frontend. The only information we use from Icecast in these situations is listener totals and the online/offline status of the streams.

**Comment by BusterNeece** [comment]
Maybe, but I'd rather not complicate things like that, as the whole idea with AzuraCast is that each "station" has one single thing "playing". If you want stations with potentially different things playing, the best bet might be to just have two stations, one broadcasting to the other, and the other with no AutoDJ set up.
