### ISSUE TITLE
See more than one next song

### ISSUE THREAD

**Issue by Developpeur** [AzuraCast/AzuraCast#621]
It would be interesting to have in the now playing API, several nextsong. Because show on our site the songs broadcast, it's good but show the next songs is better

**Comment by SlvrEagle23** [comment]
@Developpeur I will add this as a possible future enhancement, but in the interest of full transparency it isn't very likely in the current system, for two reasons:

 - Having only the very next song calculated at any given moment allows changes to playlists to take effect immediately after the next song, rather than having a longer delay;

 - Some royalties boards explicitly prohibit showing "next song" at all, because this would allow listeners to predict what songs will play when, and this shifts the classification of the station from "live streaming radio" to "on-demand". It doesn't make much sense, as the station is obviously not "on demand", but that's the way the royalties boards think of it.

**Comment by Developpeur** [comment]
@SlvrEagle23 Okay but if the two reasons do not concern us, it would be interesting to be able to activate this feature

**Comment by SlvrEagle23** [comment]
We have a new report called "Queue" which lets you view any upcoming songs that are scheduled to play on the station. As a technical limitation, AzuraCast can't currently determine farther ahead than the next song.
