### ISSUE TITLE
API: station/{station_id}/schedule?now=(datetime) doesn’t set "is_now" to true

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6231]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #c0e9752 (2023-04-22 9:11)

### What happened?

In order to [help someone](https://github.com/AzuraCast/AzuraCast/discussions/6196#discussioncomment-5699288), I played with the schedule API (`/station/{station_id}/schedule?now=2023-04-23T00%3A00%3A00&rows=10`) and found that

```
station/{station_id}/schedule
```
sets `is_now` in the returned JSON correctly (`true` if a schedule entry is "now" playing), but giving it a start time as in

```
station/{station_id}/schedule?now=2023-04-23T00%3A00%3A00&rows=10
```
does _not_ set `is_now` correctly—it always stays `false`.

For instance we have now (roughly) epoch 1682246869 (2023-04-23T12:47:49+02:00) and my "Easy Listening" playlist plays (also shows as "now" in "Schedule" view of station profile).

The JSON returned from above call looks like this:

![Auswahl_205](https://user-images.githubusercontent.com/3706922/233836027-116c1e8d-6c66-4863-8a96-be60e7d30026.png)

As you can see, `is_now` should be `true` because epoch 1682246869 clearly lies in between 1682244000 and 1682254800 (the "Easy Listening" playing time).

**Comment by Moonbase59** [comment]
P.S.: VM and station run on timezone "Europe/Berlin" (UTC+0200), and using

```
station/{station_id}/schedule?now=2023-04-23T00%3A00%3A00%2B02%3A00&rows=10
```
didn’t work either. It got me a HTPP error 500 instead:
```
Could not parse 'schedule?now=2023-04-23T00:00:00+02:00': Failed to parse time string (schedule?now=2023-04-23T00:00:00+02:00) at position 0 (s): The timezone could not be found in the database
Creator.php : 190
```

**Comment by BusterNeece** [comment]
Can't seem to reproduce this one locally. It functions exactly as expected in my local instance.

**Comment by Moonbase59** [comment]
Maybe it’s a misunderstanding on my side as on how it’s _supposed_ to work. I was assuming I could set an arbitrary start datetime to get the schedule for that day, and if it happened to be today, it showing the `is_now: true` for the _current time_, not the _requested time_. I.e., requesting a datetime of `2023-04-24T00:00:00` would show me the schedule for today, starting at 0:00, and it being 7:38 now, have `is_now: true` on the playlist that plays from 6:00 to 12:00.

As I see now, this seems not to be its intended function. If I request a datetime of `2023-04-24T07:39:40` (=now), it’ll start listing with the playlist that’s running _now_, and also set that playlist’s `is_now: true`. Which is, of course, enough for the station’s profile page.

**Comment by BusterNeece** [comment]
@Moonbase59 Well, the `now` parameter is supposed to be supported, and the `is_now` return _should_ reflect the `now` parameter you give it. It's similar to what we do for unit testing, setting a known "now" value and testing against it.

I think the problem is that I assumed that if we received a date/time, that our parser would convert it into the timezone used by the station. It seems that's actually not what it does, and instead it renders all the timezones relative to the timezone of the "now" you give it, even if that's different. Our caching isn't prepared for that, instead just storing the date/time as the cache key, not the date/time/timezone, since we expected it to lock to the station timezone.

So now, the question is...which way do we fix it? Do we accept any arbitrary timezone in the parameter, and then have it cache by the full ISO-8601 datetime including offset, or do we force conversion into the station's timezone, regardless of what format `now` is specified in?

**Comment by BusterNeece** [comment]
@Moonbase59 Update on this...actually, we _have_ to do the "shift the time to the station's timezone" option, regardless of what timezone is parsed, because, well, the "time code" changes based on what timezone you pass it, which is likely causing an issue not only here, but...possibly other places.

Working on this.

**Comment by Moonbase59** [comment]
Hm. Sorry for the extra work… I originally _thought_ using the station’s timezone might be enough, but one can have listeners all over the place. You’re right, better check early… I also stumbled over that in the past.

Fortunately we have the _epoch_. Maybe it’s enough to use that internally, and generally process input/output to/from that, taking into account
- the OS’s timezone,
- the station’s timezone,
- and the API/web user’s timezone (possibly).

**Comment by BusterNeece** [comment]
@Moonbase59 Eh, it's not all _that_ complicated. I mistakenly thought that the `$now` we were getting would always be in the station's timezone, and yet it's not, because the timezone in the parsed string takes precedence over the timezone we pass that function. Should be improved by enforcing that better.

**Comment by BusterNeece** [comment]
@Moonbase59 It doesn't silently ignore it, it'll parse it and then "shift" the time to the station's timezone offset, whichever direction that may be. So it should ideally represent the same time that you entered.

Also, I don't mind "tested and confirmed working" posts. Always good to have confirmation.

**Comment by Moonbase59** [comment]
But wait… Shouldn’t `2023-04-24T16:58:54+06:00` be `2023-04-24T10:58:54+00:00` in UTC and thus `2023-04-24T12:58:54+02:00` in my local timezone (CEST)?

See the Swagger output (which indicates it was `2023-04-24T16:58:54+02:00` now):

![Swagger UI – Mozilla Firefox_001](https://user-images.githubusercontent.com/3706922/234047346-8f2ffcff-cd8e-46d8-ac16-abf5a5cd44aa.png)

**Comment by BusterNeece** [comment]
@Moonbase59 Got my wires crossed a little. I thought `shiftTimezone` set the timezone _and_ shifted the time to adjust for the offset, but it's the opposite, `shiftTimezone` sets the exact same time with the offset "shifted" over, and `setTimezone` does what I'm wanting.

**Comment by Moonbase59** [comment]
NOW we’re talking! Tried with positive, negative and no offsets, all good now! Cheers!
