### ISSUE TITLE
unable to install with docker compose build , please help

### ISSUE THREAD

**Issue by IVEN2022** [AzuraCast/AzuraCast#6290]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

downloaded from github  , unable to install with docker compose build , please help

**Comment by stickbear2015** [comment]
might I suggest you visit the installation guide? Available at
[the installation page](https://docs.azuracast.com/en/getting-started/installation)
if after following this guide you still have trouble, please provide appropriate log output and someone will be happy to assist you.
Thank you.

**Comment by IVEN2022** [comment]
Yes Hello , we have followed the instructions , as we need to install it on our school server , but our server is offline server , only allowed on local network , so we downloaded the zip and then we try to  build using docker compose , but it is not working.
please advice , thank you

**Comment by stickbear2015** [comment]
In order to perform the installation the install script connects to the internet to pull the docker images, install dependancies on fresh installs, etc. so a server not connected to the internet will not be able to install azuracast.
I am not experienced with how the docker images are built or deployed from the source tree to help further except to say that I suspect @BusterNeece, @Vaalyn  @ItsMitchh  and other developers may tell you that installing from the zip file you downloaded from github is not supported, but I'm  not a developer so I may be totally wrong and they may have something to tell both of us.

**Comment by IVEN2022** [comment]
thank you  stickbar2015   , the school server is a rack mount one , in the server room and it is for the internal local network use , no way the administation will allow this server to be contectted to the internet , but we can login to it locally and deploy  software / scripts or docker images
