### ISSUE TITLE
All in one request

### ISSUE THREAD

**Issue by chourmovs** [AzuraCast/AzuraCast#634]
First of all thank you for your fantastic job, I really enjoyed trying docker and setup azuracast and I'm about to realize an old dream of running my own radio station
This past evening has been very exciting and instructive

that being said, I encountered some difficulties, bug and incomprehension in the polishing of my running station

1) shoutcast issue (the radio I run today) 
I can access admin page via 2 url : url:8000/admin.cgi and via azuracast provided link url/radio/8000/admin.cgi but only first path give me access to clickable menu, with second one, nothing is responsive

2) Icecast issue, ( the initial radio I abandoned)
- Already reported, announce to icecast YP looks to be out of order, even with correct header fixed/parsed
- icecast admin page doesn't work and point to xml of the station

3) Better wiki, explanations need some enhancement and completion (I m pretty sure you know that)

4) Feature request
 - more theming of public page, song requester...etc, more exportable widget/iframe
 - Normalize track (spotify like) to avoid use of very destructive mp3gain :)
 - The ability to set a maximum track duration per playlist

5) Finally and most of all, I need help for using API because I'M lost
 I'm actually trying to setup a wordpress live and community page including API calls with the plugin "json-content-importer" https://wordpress.org/plugins/json-content-importer/
 I'm quite new to it and I can't success in making proper call
I've tried some variant like this
[jsoncontentimporter url=http://url/static/api/swagger.json basenode=station debug=10]
now : {song_history} and {song}
[/jsoncontentimporter] but it doens't work

Maybe more example of how to use json API and swagger would be very helpfull, the same for web hooks...

Feel free to give me some advise and point out interesting reading

Thank you by advance

Vincent

**Comment by SlvrEagle23** [comment]
Hello @chourmovs, and thank you for trying out AzuraCast.

As a friendly reminder, GitHub issues are only built to categorize and track the progress/status of one item at a time, so you should always follow a "one issue per Issue" rule, rather than submitting lists of items that don't necessarily relate to one another.

Nonetheless, I'll try to answer the questions above in order:

1. The radio proxy is intended to provide an alternate way for listeners to connect to the stream for listening, not for administrators to manage the Shoutcast or Icecast streams. The software itself expects to be at the base directory of its URL (because it's normally running on a non-standard port), and proxying can only do so much in this regard.

2. If the Icecast issue is already reported, there's no need to mention it again here; just follow the original issue for updates. I'm unaware of the specific issue you're referring to, however, so it would be helpful if you annotated that with the actual issue number.

3. This is not helpful. Just saying "you need better documentation" is not only not helpful to me as a developer, because it doesn't provide me with any guidance as to what you're looking for extra documentation _for_, but it's basically just saying "I know you already volunteer huge sums of time toward this project, but you need to do that more", without being specific. I am struggling to pay rent this month; suggesting that I do more non-paying work for your benefit is something I'm not going to be particularly happy about right now.

4. These are all different feature requests and should be submitted independently, though many of them already exist in some form or another.

5. I think you're misreading the API documentation. Each of the headers of the [API documentation](http://azuracast.com/api/) are the actual URL where you can find that data; for example, `/status` shows you what to expect when you call `http://your-azuracast-site/api/status`, and so on. You shouldn't pass the actual Swagger API URL to Wordpress, as that just describes the overall API and doesn't actually provide the data you're looking for. 99% of the time, the data you're looking for will be at `http://your-azuracast-site/api/nowplaying`.

**Comment by chourmovs** [comment]
First of all sorry for having frustrating and sorry for my poor "noob" level
Regarding the style and content of my post, I apologize for such exaggerated willingness, just comparable to my enthusiasm, I should have follow the rules
Regarding topic
1 ok I'm proxified it make sense
2 yes bug [550](https://github.com/AzuraCast/AzuraCast/issues/550) but i didn't catch t that you already precisely answered to the request...
3 Sorry for the pour quality of my feedback, I was meaning that installation instruction is quite comprehensive but post installation, setup, managing station, using API and hooks need more digest/video/explanation for (bad) basic user like me. No offense I've developped and shared 3000 lines program by the past and I know setting-up documentation can be painfull and boring
Regarding your personal situation, I sympathize and suggest you to provide paypal link and call for help, people can be generous sometimes...
4 I'll check and will do it the right way
5 I've already try parsing http://your-azuracast-site/api/status and  http://your-azuracast-site/api/nowplaying in the jsoncontentimporter but without success, that was the first reason of my post, I should have focus on it and been more comprehensive, if i find a solution I will share

keep it up !

**Comment by SlvrEagle23** [comment]
@chourmovs I do have links to both my [Ko-fi donation page](https://ko-fi.com/A736ATQ) and the project's [Patreon](https://www.patreon.com/bePatron?u=232463), which supports me directly, on the homepage of the GitHub repository here.

I'm not sure why that module isn't correctly parsing the Now Playing API data, as it's structured in a predictable way and should be parsing properly. I would need more information about specifically how you're using it and what variables you're using before I could troubleshoot that further; if you still need help with that, feel free to create another issue.

**Comment by BartManX** [comment]
did you ever get this figured out?

**Comment by SlvrEagle23** [comment]
@BartManX Which issue?

**Comment by macbroadcast** [comment]
Would be interested in how to enable the yp-directory listening in azuracast/Icecast aswell :smile:

**Comment by chourmovs** [comment]
![image](https://user-images.githubusercontent.com/40670708/55802331-4b0ba180-5ad8-11e9-83e5-1348d1ba637b.png)

**Comment by chourmovs** [comment]
in station profil / advanced personal configuration  add this
<directory>
    <yp-url-timeout>15</yp-url-timeout>
    <yp-url>http://dir.xiph.org/cgi-bin/yp-cgi</yp-url>
</directory>
