### ISSUE TITLE
problem with icecast, only HLS stats are shown, not from mount points, can't login to icecast admin page

### ISSUE THREAD

**Issue by gasguti** [AzuraCast/AzuraCast#6385]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.18.5 stable

### What happened?

Only HLS statistics are shown, not the mount points.
In station statistics, the statistics of the mount points listeners do not appear. I already tried creating new mount points and restarting the station. Statistics of my mount points don't exist. Unique listeners always show 0.

![image](https://github.com/AzuraCast/AzuraCast/assets/57552531/27b9d2a1-88b0-403f-948e-88b09cd7dc30)
![image](https://github.com/AzuraCast/AzuraCast/assets/57552531/5eab87c2-4aa6-41c3-9f86-bee443f39436)

This is the now playing debug
![image](https://github.com/AzuraCast/AzuraCast/assets/57552531/7d2ab803-04ce-4dda-a73f-eedc55e78be1)

**Comment by Moonbase59** [comment]
HLS _has_ no mountpoints (and is not streamed via Icecast or Shoutcast). The whole idea is to break the stream into little file fragments and playlists, that are then transported by a web server via HTTP or HTTPS.

**Comment by gasguti** [comment]
> HLS _has_ no mountpoints (and is not streamed via Icecast or Shoutcast). The whole idea is to break the stream into little file fragments, that are then transported by a web server via HTTP or HTTPS. Everything is "held together" by `.m3u8` playlists.
> 
> See also: https://en.wikipedia.org/wiki/HTTP_Live_Streaming

ok, thank you. The problem is the statistics of mount points don't exist.

**Comment by Moonbase59** [comment]
@gasguti Sorry, it seems I misunderstood you!

Have you ever had _listeners_ on your mountpoints, for the time period displayed? AzuraCast will _only_ list them when at least _one listener_ connection has happened.

**Comment by gasguti** [comment]
yes I have listeners in the mount points, also the problem appears in live listeners statistics. I have other stations in the same server without this problem
![image](https://github.com/AzuraCast/AzuraCast/assets/57552531/d7784108-384a-4172-83b6-160234f1fb42)

**Comment by Moonbase59** [comment]
I fear I can only guess from here on. In order to help the developers pinpoint this issue, you might want to:

- Only set _one_ stream as the default mount point (you show two as being default). (I tested that on my station but it didn’t seem to confuse AzuraCast.)
- Check if there is any difference in your mount point setup, comparing to the stations that work.
- Double-check you’re indeed watching statistics for the right time & date range.
- Answer these questions:
  - Operating system you run this (and the other) station on.
  - Are you using Icecast or Shoutcast?
  - Is it actually running?
  - Can you see the listeners on your mountpoints connect when you check the Icecast (or Shoucast) page?
  - Are the working stations using the same AzuraCast version (0.18.5 stable)?

It might also be something that has been fixed in the rolling release, that is currently [70 commits ahead](https://github.com/AzuraCast/AzuraCast/compare/stable...main). But I doubt that, because you’re saying the other stations work.

**Comment by gasguti** [comment]
> I fear I can only guess from here on. In order to help the developers pinpoint this issue, you might want to:
> 
> * Only set _one_ stream as the default mount point (you show two as being default). (I tested that on my station but it didn’t seem to confuse AzuraCast.)
> * Check if there is any difference in your mount point setup, comparing to the stations that work.
> * Double-check you’re indeed watching statistics for the right time & date range.
> * Answer these questions:
>   
>   * Operating system you run this (and the other) station on.
>   * Are you using Icecast or Shoutcast?
>   * Is it actually running?
>   * Can you see the listeners on your mountpoints connect when you check the Icecast (or Shoucast) page?
>   * Are the working stations using the same AzuraCast version (0.18.5 stable)?
> 
> It might also be something that has been fixed in the rolling release, that is currently [70 commits ahead](https://github.com/AzuraCast/AzuraCast/compare/stable...main). But I doubt that, because you’re saying the other stations work.

Thank you Moonbase59. I think the problem is in the Icecast server, I can't login in the icecast page with the "admin" username and the given password, I tried restarting the Icecast server but doesn't work, this must be the problem with the statistics that are not shown, but I don't know how to restart or reinstall Icecast.

**Comment by BusterNeece** [comment]
@gasguti Do you have another Icecast instance listening on that same port on the "host" server running AzuraCast? If your administrator credentials from AzuraCast aren't working either, I'd think perhaps that's actually a different instance of Icecast entirely than one managed by our software. That would also cause the statistic data to be failing to retrieve.
