### ISSUE TITLE
Stereo Tool integration crash sometimes

### ISSUE THREAD

**Issue by rgriep** [AzuraCast/AzuraCast#6393]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#f5f9dfb (2023-07-03 14:26)

### What happened?

Hi,

A few times a day, the stream crash. Only with using Stereo Tool. The server has no problems, 6 CPU's, 16GB memory. The load is maximum 0.5. Processor total a maximum of 14%. 

Stereo Tool is version 10 with a STS file with only audio settings. 

It starts up well, running for hours and then stops. Never know when or how :(

I can;t find information about the crash in the log files. What can be the issue?

Best regards,
Robert

**Comment by BusterNeece** [comment]
It's something we want to do, but it's made difficult by the fact that we can't ship StereoTool as part of our Docker image since it's not free and open-source software, so we have to build an "installer" tool for it similar to how we do the current Stereo Tool integration, and it's not immediately clear to me how we'd orchestrate some of the specifics with the latest drop-in module that Liquidsoap is using in 2.2.x.

**Comment by rgriep** [comment]
Hi BusterNeece,

I get your answer but it has not to do with "not free". Everybody can download and use Stereo Tool but without license, you get beep tones and jingles from Stereo Tool, till you buy a license. Great for testing. I use a license btw.

The only thing to change in Azuracast is the possibility to upload the libStereoTool_64.so library instead of de CMD version (stereo_tool_cmd_64) of Stereo Tool. The rest like license and presets can be kept the same as now in the current version of Azuracast.

And with generating the liquidsoap file is to change the line :

radio = pipe(process='/usr/bin/stereo_tool_cmd_64 - - -s /<mypreset.sts> -q -k "<3faxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxee>"', radio)

to

radio = stereotool(
library_file="/var/stereotool/libStereoTool_64.so",
license_key="<3f...................................................7c>",
preset="/var/stereotool/presets/mypreset.sts",
radio
)

Stereo Tool is then not an external tool running by piping, but intergrated in Liquidsoap 2.2.0+. Liquidsoap has it as new function to do it this way.

Of course, this is for the Rolling Release of Azuracast.

Best regards,
Rob

**Comment by BusterNeece** [comment]
@rgriep To be clear, Stereo Tool is **not** "Free and Open-Source" software. It is proprietary software that is licensed under a different license than what would be an officially open-source license, like GPL or Apache or something like that.

From our perspective, this makes it proprietary software, and we can't bundle it into our otherwise free and open-source images. We'll have to continue with our installer process. There is more to it than just switching out the upload to the new format on our end.

**Comment by rgriep** [comment]
I didn't write that you have to integrate Stereo Tool in the Azuracast installation. Ofcourse, I understand it with open source etc. The way the user can add Stereotool  to Azuracast  at the moment have not to change but needs the correct method so It is not crashing.

The way of calling Stereotool at the generated liquidsoap script in Azuracast  is not the correct method. See also the manual of Liquidsoap https://www.liquidsoap.info/doc-dev/stereotool.html

**Comment by BusterNeece** [comment]
@rgriep I am aware of their new method. We don't support it yet. We may support it in the future. Please be patient.
