### ISSUE TITLE
openvz

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#640]
**Installation method**
Indicate whether you are using the "Docker" or "Traditional" installation method.
Traditional
**Host OS (for Docker installations)**
Indicate what your host operating system is (i.e. Ubuntu 16.04, MacOS High Sierra, Windows 10), if you're using the Docker installation method.
Ubuntu 16.04 Kernel 2.6
**Describe the bug**
I can't install gcc6 on openvz because the kernel it too old.

**Comment by SlvrEagle23** [comment]
If AzuraCast won't install on your setup because the kernel is too old, then there is very little I can do as a developer to address that issue. For the sake of not only having newer features, but also ensuring that we have the latest security patches, AzuraCast uses the very latest stable version of almost every piece of software it uses.

If you're unable to install AzuraCast on any environment that will suitably run it (which includes a vast majority of VPS providers and almost any host that will run the latest Docker and Docker Compose), you are welcome to fork the project and modify the Ansible deployment (found in `/util/ansible`) to fit your needs. Bear in mind that this is unsupported, though, and it's highly recommended to host the software on a supported platform.
