### ISSUE TITLE
Player doesn't run on iPad Air ( iOS 12.5.7)

### ISSUE THREAD

**Issue by Abbienew** [AzuraCast/AzuraCast#6444]
### Installation Method

Ansible Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Version 0.17.7OS Ubuntu 22.04

### What happened?

Player doesn't run on iPad Air ( iOS 12.5.7)

**Comment by Vaalyn** [comment]
Since you are on a version before Icecast included a [specific cache busting redirect](https://github.com/AzuraCast/AzuraCast/issues/6304#issuecomment-1611783938) for Safari users this is probably not related to that.

We'd need more information about your setup:
- what kind of stream are you using (mp3, opus, vorbis, aac, flac)?
- Icecast or ShoutCast?
- can you post a link to your station?

**Comment by Abbienew** [comment]
Thank you for your reply, following are the details of my setup

- what kind of stream are you using (mp3, opus, vorbis, aac, flac)?
streaming DJ with Blackhole - for routing web based generative content from other products
- Icecast or ShoutCast?
Icecast
- can you post a link to your station?
yes, http://165.232.33.108/public/factwave_fm (but the station is offline)
