### ISSUE TITLE
Even with MaxMind account & key, amost all German listeners listed at "Hesse, Frankfurt am Main, DE"

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6471]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #4078c70 (2023-08-03 3:37)

### What happened?

Almost all German listeners appear to be located at "Hesse, Frankfurt am Main, DE", even when using full IPs, which renders the listener stats rather useless. Stations might target local regions within a country, and wish to check if their target audience is reached.

I hoped for the GeoLite database to be more exact and got a MaxMind account and a license key and let AzuraCast download the database, but still nearly all German listeners are shown as being located in "Hesse, Frankfurt am Main, DE".

**I wonder if we could have an alternative**, for instance [ipinfo.io](https://ipinfo.io/developers). I currently use them to manually fetch locations, as in
```
https://ipinfo.io/178.24.235.197/json
```
since they seem to always show much more exact results.

As far as I understood, one can do 1k requests/day without signing in, and 50k/month using their free tier. This might be enough for small stations just starting out.

**Or did I make some silly mistake** and AzuraCast keeps and shows the (old) IP locations somewhere in the database without ever updating them with new GeoLite data?

I intentionally waited about an hour for the next `UpdateGeoLiteTask` to run, and also ran it manually (success) but nothing changed in the listener reports.

**Comment by Vaalyn** [comment]
If I'm not mistaken the GeoIP resolution from IP to Location only happens once when they are processed from the now playing data.

So if you are looking at historical data or a current listener that was already processed with the old dataset it won't resolve the GeoIP Location again for that listener. This was done since the GeoIP resolution was computationally rather expensive and caused unnecessary CPU load.

Fetching of existing data about current listeners: https://github.com/AzuraCast/AzuraCast/blob/092c7c270846dd937834baa554eefe25ad2b4476/src/Entity/Repository/ListenerRepository.php#L112-L131

Updating if not existing already: https://github.com/AzuraCast/AzuraCast/blob/092c7c270846dd937834baa554eefe25ad2b4476/src/Entity/Repository/ListenerRepository.php#L176-L188

**Comment by Moonbase59** [comment]
Thanks @Vaalyn, that explains it—and makes sense since the # requests using third-party APIs is usually limited.

Would there be an easy way to erase & rebuild that dataset from the new GeoLite data? It could be a good improvement being able to refresh historical data, especially when switching geolocation providers/databases.

**Comment by Moonbase59** [comment]
Thanks. I just realized that it _will_ use the new GeoLite data on _new connections_, so things will eventually even out and only the new location data being used. Fair enough.
