### ISSUE TITLE
Icecast status-json.xsl in http, 10 seconds to get it with php, after AzuraCast update

### ISSUE THREAD

**Issue by CouinCouin** [AzuraCast/AzuraCast#6479]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.18.5

### What happened?

Hi, 

Previoulsy in 0.17.7 Stable, I was using _http://domain.name:station_port/status-json.xsl_ of an "offline" station (just used as icecast server for animators that RadioDJ listen when animator do a live), to get active mount points ("listenurl" key), to allow animator to enqueue its live track in RadioDJ only if he sends its stream.

I use php _file_get_contents_ and parse the array. With some other code lines, I create an array with some datas. This php page is called from an AJAX request. 

This night, I decided to update AzuraCast. 
Since, the _file_get_contents_ takes around 10 seconds to get the _xsl_ file . 
If I open the file directly with the link in the browser, it generates the file.json file without delay.
If I replace http or https, the _file_get_contents_ function gets the file without delay.

In my case, changing http for https should be the workaround, but it could be a problem for who is using http only.

Couin :)

**Comment by BusterNeece** [comment]
We really haven't changed anything of our infrastructure that would result in a longer timeout when trying to fetch the Icecast status file. I suspect there may be something in your setup that was causing that timeout, but if it's fixed by switching the relevant protocol, then that's even more unusual, since our stack for serving both HTTP and HTTPS route through all the same code.
