### ISSUE TITLE
Database Migration Error

### ISSUE THREAD

**Issue by Blat4** [AzuraCast/AzuraCast#6489]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #631dda9 (2023-08-08 17:23)

### What happened?

Updating via SSH this morning and I notice this error as web updater couldn't resolve host.

![Screenshot 2023-08-09 at 05 07 34](https://github.com/AzuraCast/AzuraCast/assets/106454822/03ef91c0-8e82-46fb-acb9-7ed2fd9f9a76)

Server is up and stations do seem to be working

**Comment by chrisulloa** [comment]
I get this issue too, only latest rolling release.

**Comment by Blat4** [comment]
Should I be concerned about the above error, is there any feedback to help explain what's happened or is it possibly a result to something I've done?

**Comment by BusterNeece** [comment]
@Blat4 @chrisulloa As our [documentation mentions](https://docs.azuracast.com/en/getting-started/updates/release-channels), you can only switch from the "Rolling Release" channel to the "Stable" channel when your Rolling Release version locally is _older_ than the current Stable version. This is because of this exact problem: newer Rolling Release versions will have database migrations that the Stable version has no idea exist, and it will be unable to handle the database in the state it's in.

Fortunately, in a vast majority of cases your installation isn't at all ruined. You can just switch right back to the latest Rolling Release version and your database will once again be in a workable state for the version you're running. You'll just have to wait until we tag a new Stable release version to switch release channels properly.

**Comment by Blat4** [comment]
Hi Buster and thank you for the reply, I'm a little confused as I'm currently on the rolling release Chanel, and I have never attempted to switch to stable on my current server installation?

**Comment by BusterNeece** [comment]
@Blat4 Sorry, I misread the report as we've had a bunch of reports very recently about this specific issue coming from people switching from Rolling to Stable.

Unfortunately, and very frustratingly, sometimes if an update is interrupted by something, it leaves the database in a weird state like this, where the migration actually went through, but the database didn't log that it went through.

Right now, there's no automatic way for us to recover from this situation. The manual intervention is also a bit of a pain, to be honest: it involves going into the database console and adding any missing "migration" records to the `app_migrations` table.

The best thing would be to either restore from a backup or export your station's media/playlists and reimport them on a fresh installation.

**Comment by Blat4** [comment]
Unfortunately my last automatic backup will contain this same problem. I'd like to not have to start from scratch regarding my server, is there a simple way to completely uninstall azuracast?

**Comment by BusterNeece** [comment]
@Blat4 Yep, `./docker.sh uninstall` will pull it, then `./docker.sh install` can reinstall it.

**Comment by Blat4** [comment]
Hi Buster and thank you for your help. I will backup media from all stations, and then do the uninstall - then reinstall. Shouldn't take me too long to do, hopefully I can remember all the little tweaks stations have in there settings.

**Comment by Blat4** [comment]
Well I proceeded with the uninstall then reinstallation. But seems that Shoutcast won't install now. There must be something else going on.
