### ISSUE TITLE
The iframe cannot show up on iPhone and iPad ( safari and chrome )

### ISSUE THREAD

**Issue by Abbienew** [AzuraCast/AzuraCast#6493]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.18.5

### What happened?

I put the iframe on the web but it cannot show up on iPhone and iPad ( safari and Chrome) - it works on mac. How can I solve this issue? Thank you.

**Comment by thackmaster** [comment]
I've got iframes scattered across the web, hosted on a Wordpress installation and another built with Jekyll, and I can see all of them with both Safari and Firefox on my iPhone running iOS 17 Beta 3. You can check mine at [thackerbroadcasting.com/radio-broadcasting](https://thackerbroadcasting.com/radio-broadcasting)(Wordpress) or [thackerbroadcasting.github.io/homepage](https://thackerbroadcasting.github.io/homepage) (Jekyll, In progress). If you can see mine, it might be something with your installation.

**Comment by Abbienew** [comment]
Thank you! I can see the difference css style from the iframe. I am new to the Jekyll - how do you figure it out? And why it works in the Jekyll framework? Thanks!

**Comment by Abbienew** [comment]
Thank you! I can see the difference css style from the iframe. I am new to the Jekyll - how do you figure it out? And why it works in the Jekyll framework? Thanks!

**Comment by thackmaster** [comment]
@Abbienew Personally, the way I've begun to explore Jekyll is by seeing it in action and figuring out what exactly is going on behind the scenes. So what I've done is I found a couple of projects on Github that are built with Jekyll and can be forked (such as [https://github.com/raviriley/agency-jekyll-theme](https://github.com/raviriley/agency-jekyll-theme)), forked it, enabled Github Pages, and began changing stuff to see what would happen. I'm more of a visual and tactile learner, so that works best for me but you can always reference the Jekyll documentation at [http://jekyllrb.com/](http://jekyllrb.com/) or peruse Reddit for tips on it. If you have more questions specifically about Jekyll and all of that, feel free to hit me up Twitter (now X) @realthackmaster so we can keep the comments on this as clean as possible.

Additionally, it works in the Jekyll framework because that particular site is wrapped in HTML and parsed with Jekyll so it can be hosted on Github (more on how to do that at [https://jekyllrb.com/tutorials/convert-site-to-jekyll/](https://jekyllrb.com/tutorials/convert-site-to-jekyll/)). Reddit, Stack Overflow, and simply looking at someone else's code can be immense help when trying to build your own or forking someone else's Jekyll code.
