### ISSUE TITLE
No song metadata is being pulled from mp3 stream on ios apps

### ISSUE THREAD

**Issue by jpcastberg** [AzuraCast/AzuraCast#6529]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.0

### What happened?

Using 0.19.0, on (at least) iOS apps reading the mp3 stream, no metadata is being read from the stream. I tried with azuracast version 0.18.5, and metadata is being picked up as expected.

I noticed on my Sonos desktop application, when streaming from azuracast 0.19.0, the metadata is present, so the metadata is _there_, but something about it has changed that is confusing some clients.

Examples in [iOS Broadcasts app](https://apps.apple.com/us/app/broadcasts/id1469995354):
Expected (running azuracast 0.18.5):
<img src="https://github.com/AzuraCast/AzuraCast/assets/37011196/c0ad5880-7dce-4164-b5b1-bcbabf45d97b" width="300" />

Actual (running azuracast 0.19.0):
<img src="https://github.com/AzuraCast/AzuraCast/assets/37011196/21ec873f-7c2f-4d30-9448-fb4440ed62ed" width="300" />

I am also seeing this behavior on a custom client I use to listen to my stream, so it's not just the Broadcasts app. I realize this might be an upstream issue, please lmk if that is the case and I'll open an issue in the appropriate place.

I LOVE azuracast and thank you all in advance for your time and attention!!

**Comment by BusterNeece** [comment]
Tagging @Vaalyn as he's more familiar with the iOS issues we've been having. We have indeed run into some other issues with iOS clients in the recent versions of Icecast-KH, so that may have something to do with it.

**Comment by Vaalyn** [comment]
For reference I tried this with the apple music app on macOS Ventura 13.4.1 and also checked VLC player using an AzuraCast installation on `Rolling Release #d2ca5eb (2023-08-22 1:05)` 

As always VLC won't display metadata from streams served via SSL but on non-ssl http streams (like `http://example.com:8000/stream`) it shows the streams metadata so it is available and can be used.

When open the stream in the apple music app it's showing me the following (regardless of with or without ssl, and regardless of if I'm using nginx proxy or direct connection to Icecast):
![image](https://github.com/AzuraCast/AzuraCast/assets/13745863/f30acd40-f26e-41bb-9257-d71add1bb7b1)

So on that front nothing seems different to the checks I did back in 2019 [here](https://github.com/AzuraCast/AzuraCast/issues/1598#issuecomment-518002693)

(When I do the same with the demo installations public stream it doesn't show any metadata in the apple music app, probably something with CloudFlare 🤷)

On iOS when I play the stream directly in Safari (not the web player, directly opening the stream url) and look at the player on the lock screen it doesn't show any metadata.
But this was already like this in `Rolling Release #a28072d (2023-06-01 7:17)` which is on `icecast-2.4.0-kh21.6` (this is from another server of mine that is running on that older version). Not sure about older versions though.

I can't test the linked app since it requires an in-app purchase to allow adding streams manually via URL.

**Comment by UKSparkle** [comment]
Greetings, we have bene using Azuracast to also stream music to iOS and Android apps. We have noticed that timed metadata seems to to be able to load at all on iOS while Android is unaffected.

I do have an Apple Dev account and I wish to help in anyway I can.
I have ran a few experiments of my own such as using Apple's new 'load()' function.

```
            let assetdata = try await asset.load(.availableMetadataFormats)
            let trk1 = try await asset.loadTrack(withTrackID: 1)
            let qtmd = try await trk1?.load(.formatDescriptions)
```

while format description seems to return some data, the availableMetadataFormats returns an empty array. I would like to note that the server is using HTTPS.

```
mediaType:'soun' 
	mediaSubType:'.mp3' 
	mediaSpecific: {
		ASBD: {
			mSampleRate: 44100.000000 
			mFormatID: '.mp3' 
			mFormatFlags: 0x0 
			mBytesPerPacket: 0 
			mFramesPerPacket: 1152 
			mBytesPerFrame: 0 
			mChannelsPerFrame: 2 
			mBitsPerChannel: 0 	} 
		cookie: {(null)} 
		ACL: {(null)}
		FormatList Array: {
			Index: 0 
			ChannelLayoutTag: 0x650002 
			ASBD: {
			mSampleRate: 44100.000000 
			mFormatID: '.mp3' 
			mFormatFlags: 0x0 
			mBytesPerPacket: 0 
			mFramesPerPacket: 1152 
			mBytesPerFrame: 0 
			mChannelsPerFrame: 2 
			mBitsPerChannel: 0 	}} 
	} 
	extensions: {(null)}
}])
```

**Comment by BusterNeece** [comment]
@UKSparkle Hello /)

Are you trying to pull the metadata from inside the MP3 stream directly? I know recent versions of Icecast have done some really unusual things to maintain compatibility with newer iOS versions, and it's entirely possible that's what's causing the problem here.

You shouldn't encounter any issues hitting our rich NowPlaying metadata endpoints https://docs.azuracast.com/en/developers/apis/now-playing-data either via SSE or regular polling.

**Comment by UKSparkle** [comment]
@BusterNeece Hello /)

The HTTPS I'm using is indeed from the MP3 directly (https://stream.radio/listen/clubradio/stream.mp3).

When calling the NowPlaying (http://stream.radio/api/nowplaying) I do get a json file with all the metadata present. (woot)
However, it seems I can't automatically update the metadata when a new track is loaded unless I poll the json file again.

I used to be able to let AVPlayer output the metadata to AVPlayerMetadataOutputDelegate which would detect the change in tracks.

**Comment by Vaalyn** [comment]
@UKSparkle hey, could you provide me with a simple xCode project or just swift code where I can put a stream URL into which dumps the metadata info from the stream into the console?

I could then use that to test around with different LS / Icecast settings & versions to see if I can find something that works.

**Comment by BusterNeece** [comment]
> When calling the NowPlaying (https://stream.radio/api/nowplaying) I do get a json file with all the metadata present. (woot) However, it seems I can't automatically update the metadata when a new track is loaded unless I poll the json file again.

Yeah, that's the standard Now Playing API, which you have to periodically poll for updates. We also have the "high-performance" Now Playing API, which uses Server Sent Events (SSE) to let you establish one connection, then get pinged any time something changes. It uses a lot less resources on the server side and gives you updates so fast that people often complain they're _too fast_.

If you can use some library that can hook into SSE and listen to those, that's really the best way to go. Alternatively, if the only way you could do it is via Websockets, that's possible for us to do too; we just have that turned that off right now because SSE meets all of our needs, and our Websocket would be a "one-way" websocket (which is what SSE is).

**Comment by UKSparkle** [comment]
@Vaalyn Hello, and sure thing.

File: MediaTest.swift

import Foundation
import AVFoundation

```
class RadioMain: ObservableObject {
    let stationurl = URL(string: "STATION_URL_HERE")!
    var player: AVPlayer!
    var playerItem: AVPlayerItem!
    
    func inspectProbs() async throws {
        let asset = AVAsset(url: stationurl)
        let duration = try await asset.load(.duration)
        switch asset.status(of: .duration) {
        case .notYetLoaded:
            print("Not yet")
        case .loading:
            print("Loading")
        case .loaded(let duration):
            print("Loaded! \(duration)")
            let assetdata = try await asset.load(.availableMetadataFormats)
            let trk1 = try await asset.loadTrack(withTrackID: 1)
            let qtmd = try await trk1?.load(.formatDescriptions)
            print(qtmd as Any)
            print(assetdata)
        case .failed(let error):
            print("ERROR! \(error)")
        }
    }
}

```
File: ContentView

import SwiftUI

```
struct ContentView: View {
    @ObservedObject var Radio: RadioMain
    var body: some View {
        VStack {
            Button {
                Task {
                    try await RadioMain().inspectProbs()
                }
            } label: {
                Text("Check Stream Probs")
            }
        }
        .padding()
    }
}

```

**Comment by Vaalyn** [comment]
> @Vaalyn Hello, and sure thing.
> 
> File: MediaTest.swift
> ...
> 
> File: ContentView
> ...

Thanks, gonna be installing xCode and when I have some time in between I'm gonna check if I'm able to find something out 👍

**Comment by UKSparkle** [comment]
@BusterNeece 

Hi again, so I'm testing out the SSE and I'm trying out the https://your-azuracast-url/api/live/nowplaying/http_stream?cf_connect=TOKEN

but I'm unsure of the cf_connect instruction.

**Comment by BusterNeece** [comment]
> @BusterNeece
> 
> Hi again, so I'm testing out the SSE and I'm trying out the https://your-azuracast-url/api/live/nowplaying/http_stream?cf_connect=TOKEN
> 
> but I'm unsure of the cf_connect instruction.

It's a bit of a pain, to be honest, but it's a JSON-encoded set of channels to join. Our code for generating this in PHP looks like:

```php
return '/api/live/nowplaying/sse?' . http_build_query(
            [
                    'cf_connect' => json_encode(
                        [
                            'subs' => [
                                $this->getChannelName($station) => [],
                                self::GLOBAL_TIME_CHANNEL => [],
                            ],
                        ],
                        JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR | JSON_FORCE_OBJECT
                    ),
                ]
        );
```

This joins the client with both the station's specific nowplaying channel (which will be `station:station_short_code`) and the global time channel (which is `global:time`) which sends occasional pings of what the server time is, so the UI can sync up playback and remaining times.

**Comment by UKSparkle** [comment]
Hi all,

So it seems that enabling HLS on the server sends metadata and works fully.
I've also used websocket idea which works by looping an async function.

@Vaalyn I'm not sure if you've tried my code, but I'm having issues with getting to work at all with stream in general. Have you had any luck?

**Comment by Vaalyn** [comment]
> @Vaalyn I'm not sure if you've tried my code, but I'm having issues with getting to work at all with stream in general. Have you had any luck?

Hey, I haven't yet had time for a testing session due to deadlines at work. 😅

**Comment by jpcastberg** [comment]
Heya - I worked around this by switching to the HLS stream. Here is an example of the swift code change that I had to do in order to appropriately pull the data in my app: https://github.com/jpcastberg/ios_molten_death.exe/commit/de438593ac1758110e098b674f10ceb33158be9a

I had version pinned before to continue using the old version of icecast - Now I can use latest azuracast! <3 <3 <3
