### ISSUE TITLE
404 on Public Pages and No Audio Coming Out from Profile Page or Dashboard

### ISSUE THREAD

**Issue by techbp** [AzuraCast/AzuraCast#654]
- Traditional Install
- Ubuntu 16.04

**Describe the bug**
After deploying https to my server, no audio is coming out already if played anywhere in the admin as well as in the front-end (if public page is enabled). Also the public url (example: https://audio.storemote.net/radio/1024/radio.mp3?1531075515) is returning 404. I have configured my SSL cert and deployed successfully. By the way, my stations (different custom ports) are all working before https... the problem started when https is deployed in my server.
Please help

**Comment by SlvrEagle23** [comment]
@techbp By default, if you've enabled HTTPS, AzuraCast will attempt to proxy your radio connection through the nginx server, so that it maintains the secure status when playing audio, which it wouldn't do if you were serving radio directly from the normal port.

You can still access the radio manually from the normal port, but in your case, you've specified a custom port that's outside the normal 8000-8999 port range that AzuraCast expects radio stations to be in.

You should look in `/etc/nginx/sites-enabled/default` and modify this line here, which specifies the ports to proxy: https://github.com/AzuraCast/AzuraCast/blob/master/util/ansible/roles/nginx/templates/default.j2#L44
