### ISSUE TITLE
See who is Live on the Panel

### ISSUE THREAD

**Issue by NeddyPlays** [AzuraCast/AzuraCast#658]
Hi,

I miss the feature that i can see on the Panel who is live broadcasting at the moment. It would be helpfull to check who did a show the moment he/she booked one. And also let Azuracast keep track to who connected when.

**Comment by SlvrEagle23** [comment]
@NeddyPlays Definitely a good idea, and an easy implementation, since the API already has this live data now.

I've updated the station profile so that instead of showing the next song when a live DJ is connected (which isn't accurate, as "Next song" only applies to the AutoDJ anyway), it shows the streamer's name in that section.
