### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#660]
Well, what can you do to assemble the release, then go to the errors and make their corrections to release at least one stable version, you can build up the functionality infinitely, but at the same time not achieve stability. 
Missing a long update time, the radio becomes more and more difficult to update, because there are more and more errors.

**Comment by SlvrEagle23** [comment]
@susl16c My release schedule is set the way it's set because I'm the only person maintaining the software, and I don't want to create any expectations that the software is "bug-free" until I'm confident that the feature set isn't making any possible significant changes between revisions.

At this point, you should always just be staying up-to-date with the latest copy from the repository, regardless of release numbers.

Considering I already have a significant number of entitled folks in my GitHub issues expecting this software to be mature and stable (and mistakenly assuming it's backed by some large corporation, instead of just me), I don't want to invite more to the party. I can't handle it.
