### ISSUE TITLE
No Sound on Public Pages - JS Error is that it can't set the volume to a non-finite double

### ISSUE THREAD

**Issue by FendleTruck** [AzuraCast/AzuraCast#6601]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Version 0.19.1 Stable

### What happened?

Updated to 0.19.1, and everything works fine, except that public pages are generating this error after clicking the play button:

Failed to set the 'volume' property on 'HTMLMediaElement': The provided double value is non-finite. 
at usePlayerVolume-2750b148.js:1:1595

**Comment by BusterNeece** [comment]
@FendleTruck If you change the volume on the volume slider, it should fix this across the whole app.

**Comment by BusterNeece** [comment]
@FendleTruck The key word that tipped me off there was "updated", as in you were on a previous version before. In some older versions, it was possible to set the LocalStorage volume value to a value the player doesn't like. The fix is to just reset the value, which thus resets the LocalStorage, permanently fixing the problem for you.

Most users shouldn't need to do this, as they wouldn't have the stored volume from the older version, but if they do, that's an easy fix!

**Comment by FendleTruck** [comment]
Wow, amazing deduction!

Unfortunately, the only reason I even realized there was a problem was users reporting it to me.
So, they seem to be having an issue. I'll have to just tell them to try changing the volume.

It's actually not as simple as changing the volume though, they have to change the volume before pressing play. At least in my case.

**Comment by BusterNeece** [comment]
Interesting...will flag it for further review.
