### ISSUE TITLE
Customized Redis Host not Updating in Synfony Connection String

### ISSUE THREAD

**Issue by infraimusica** [AzuraCast/AzuraCast#6646]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #0791831 (2023-10-01 5:33)

### What happened?

I've been using a custom Redis and MariaDB server decoupled from AzuraCast Docker installation.

This file: /var/azuracast/www/vendor/symfony/redis-messenger/Transport/Connection.php is not updating the string with the custom endpoint from environment var causing an error to start PHP-WORKER.

class Connection
{
    private const DEFAULT_OPTIONS = [
        'host' => '127.0.0.1', 
        'port' => 6379,
        'stream' => 'messages',
        'group' => 'symfony',
        'consumer' => 'consumer',
        'auto_setup' => true,
        'delete_after_ack' => true,
        'delete_after_reject' => true,
        'stream_max_entries' => 0, // any value higher than 0 defines an approximate maximum number of stream entries
        'dbindex' => 0,
        'redeliver_timeout' => 3600, // Timeout before redeliver messages still in pending state (seconds)
        'claim_interval' => 60000, // Interval by which pending/abandoned messages should be checked
        'lazy' => false,
        'auth' => null,
        'serializer' => 1, // see \Redis::SERIALIZER_PHP,
        'sentinel_master' => null, // String, master to look for (optional, default is NULL meaning Sentinel support is disabled)
        'timeout' => 0.0, // Float, value in seconds (optional, default is 0 meaning unlimited)
        'read_timeout' => 0.0, //  Float, value in seconds (optional, default is 0 meaning unlimited)
        'retry_interval' => 0, //  Int, value in milliseconds (optional, default is 0)
        'persistent_id' => null, // String, persistent connection id (optional, default is NULL meaning not persistent)
        'ssl' => null, // see https://php.net/context.ssl
    ];

I have to edit the redis host manually everytime that I update or fresh install AzuraCast.

### Relevant log output

```shell
/var/azuracast/www_tmp/service_cron.log:time="2023-10-03T12:31:01Z" level=info msg="[2023-10-03T12:31:01.809790+00:00] AzuraCast.ERROR: RedisException: Connection refused (uncaught exception) at /var/azuracast/www/vendor/symfony/redis-messenger/Transport/Connection.php line 137 while running console command `azuracast:sync:task` {\"exception\":\"[object] (RedisException(code: 0): Connection refused at /var/azuracast/www/vendor/symfony/redis-messenger/Transport/Connection.php:137)\"} {\"task\":\"CheckMediaTask\"}" channel=stderr iteration=3 job.command="azuracast_cli azuracast:sync:run" job.position=0 job.schedule="0 * * * * * *"
```

**Comment by BusterNeece** [comment]
@infraimusica Thank you for the detailed report.

I believe what we have here is actually an upstream bug with Symfony (symfony/symfony#45057) which was closed as no PR was submitted to fix it. So I submitted a PR to fix it (symfony/symfony#52811) and hopefully that fixes our specific use-case.

In the meantime, I've updated the code in how we initialize the transport to use our Redis connection settings so it can reconnect internally using those same settings. It's a bit of a waste of resources to be honest, since it's basically running a few concurrent connections to Redis for each transport (currently 6 separate ones), but it was gonna do that anyway, and at least now we can avoid it connecting each time _twice_.
