### ISSUE TITLE
High Ram Usage

### ISSUE THREAD

**Issue by Lauras-Universe** [AzuraCast/AzuraCast#6649]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.1

### What happened?

Very high ram usage. I get a VM on Proxmox with 12GB Ram, and the ram usage is 10 GB always. Its very high for 2 stations.
![Bildschirmfoto 2023-10-06 um 17 49 05](https://github.com/AzuraCast/AzuraCast/assets/145849998/3c6b27b6-c236-4a06-b367-3244a75d12c8)

**Comment by Vaalyn** [comment]
Look at the RAM usage on the VM via `htop` instead of the display in Proxmox.

Proxmox includes memory used for file caching as "used memory" which is not very informative of the real RAM usage since RAM that is used for file caching by the OS will be freed if a process actually needs that RAM.

Here an example from my Proxmox VM:
<img width="580" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/3ca2ca0a-dcb1-411e-ae53-5e8a068c2b17">


Compared to the output of `htop` where you can see that most of the RAM "used" is yellow which means it's used for caching. So the actual usage is not 7.5GB as Proxmox says but rather just 2.7GB:
<img width="524" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/61213a37-19d6-42f5-a0ef-8dd3daf4fcee">
