### ISSUE TITLE
GNU C Library bug.

### ISSUE THREAD

**Issue by stickbear2015** [AzuraCast/AzuraCast#6650]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #f39059d (2023-10-07 15:32) • Docker • PHP 8.2

### What happened?

We originally were running 0.18.5 and for reasons unknown to us azuracast was crashing and running out of memory, 
requiring a complete reinstall and restore of the database.
IN exploring the logs during the last crash this is where we found things were running out of memory and locks weren’t being grabbed appropriately.
Further research indicated an exploit in the GNU C Library, and this may have been the cause of the issues present.
I’m attaching the log file, and I’m wondering if this exploit was the cause of what you’ll see in the logs.
We’ve adjusted the PHP memory limit to 2GB, this before all this happen, and we don’t understand why we were getting out of memory errors.
I do note that we’ve upgraded to latest rolling release, but we’re not sure if this will have solved the underlying issues you’ll see in the logs
Any advice or insight would be appreciated.

### Relevant log output

```shell
See attached log file.
```
[app-2023-10-07.log](https://github.com/AzuraCast/AzuraCast/files/12838468/app-2023-10-07.log)

**Comment by BusterNeece** [comment]
I'm really not sure how we'd incorporate a fix from the GNU C library. It's likely that such a thing would affect how the PHP binaries are built themselves, which would require an update at the level of the Ubuntu PPA that we use. If there are specific updated builds of binaries that we're using that we should be updating to, by all means let me know, but otherwise I'm not sure this is anything we can do anything about on our end.
