### ISSUE TITLE
Liquidsoap Errors

### ISSUE THREAD

**Issue by rowansc1** [AzuraCast/AzuraCast#6716]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.1 Stable • Docker • PHP 8.2

### What happened?

I am experiencing liquidsoap error messages in both of the stations on my AzuraCast installation.

In station 1, liquidsoap.log is reporting the below error:
```
[input.http:2] Decoding failed: Avutil.Error(Server returned 404 Not Found)
[https @ 0x7f66320290c0] HTTP error 404 File Not Found
```

In station 2, liquidsoap.log is reporting the below error:
```
[input.http.3:2] Decoding failed: Avutil.Error(Server returned 403 Forbidden (access denied))
[http @ 0x7f9ed92252c0] HTTP error 403 Stream not available
```

According to some listeners, songs are cutting out early. 

### Relevant log output

```shell
[input.http:2] Decoding failed: Avutil.Error(Server returned 404 Not Found)
[https @ 0x7f66320290c0] HTTP error 404 File Not Found

[input.http.3:2] Decoding failed: Avutil.Error(Server returned 403 Forbidden (access denied))
[http @ 0x7f9ed92252c0] HTTP error 403 Stream not available
```

**Comment by rowansc1** [comment]
Thank you anyone who helps me resolve this issue, it is greatly appreciated as always!

**Comment by rowansc1** [comment]
Will do, heres the issue: https://github.com/savonet/liquidsoap/issues/3505

**Comment by rowansc1** [comment]
Please let me know if there is anything I can do in the meantime which could potentially solve the issue. If it is a bug with liquidsoap, that's no worries. Cheers!

**Comment by Vaalyn** [comment]
Do you have any `Remote URL` playlists on those stations?

The errors look to me like it's trying to fetch something from an URL (so not a local file) and fails to do that due to the following:

- On station 1 it gets a `404 Not Found`
  - So the remote URL it is looking for cannot be found
- On station 2 it gets a `403 Forbidden (access denied)`
  - So the remote URL seems to exist but doesn't allow you to access it
