### ISSUE TITLE
Question: how do i disable song and artist title in Liquidsoap ?

### ISSUE THREAD

**Issue by frozenplaya** [AzuraCast/AzuraCast#672]
Hello and congratulations for this project 

i`m using the Docker installation method on Ubuntu

Thanks

**Comment by Lukahhh** [comment]
Hi there!

I know a function within Liquidsoap that will achieve this.

Navigate to Manage Station -> Profile -> Edit Profile -> Advanced: Custom Configuration

This area lets you add custom liquidsoap configuration lines that will be inserted before the connection is made to Icecast.

If you'd like to drop the metadata, you'll need to add:

`radio = drop_metadata(radio)`

Save the changes and restart your station and the metadata should no longer appear on the Profile page or the Icecast mount point. It definitely appears to break the "On the Air" section on the Station Profile page, where it will be stuck with 'Now Playing' as blank and the 'Playing Next' as the same song no matter what song is actually playing next.

I tested the Song Playback Timeline for about an hour and it looks like since I'm dropping the metadata, that no songs are being recorded in the timeline - that sounds like normal behaviour to me.

**Comment by frozenplaya** [comment]
Hi Lukahhh,
thanks for the reply, but unfortunately dosen`t work for me :(

**Comment by frozenplaya** [comment]
i reboot the server and now the metadata is gone . Thanks Lukahhh

**Comment by SlvrEagle23** [comment]
@frozenplaya Glad @Lukahhh was able to provide a solution. Keep in mind, as they mentioned, that not having any metadata served by Liquidsoap will indeed result in AzuraCast being unable to track what's now playing, listener statistics per song, duration of the song played, or any of a number of other items.

**Comment by ttodua** [comment]
Can anyone say, does it still apply? 
**Profile > Edit Profile > Broadcasting > Advanced Custom Configuration** field has notice: " You can use either JSON  or XML"
So, can we still just paste this `radio = drop_metadata(radio)`  as a new line in that field?

**Comment by ttodua** [comment]
Question, related to this:

I want to change (not `drop_metadata`) title of song. I have [found this](https://www.liquidsoap.info/doc-1.4.2/metadata.html), and tried putting it manually in `liquidsoap.liq` after directly creation of playlists:


playlist_all = playlist(id="pl...
playlist_all = map_metadata(append_title, playlist_all)

and restarted stations several times, and accidentally it once worked. however, on next restarts, i coudlnt get it back to the state I had... So, i assume, it might be good if you can tell me, how to add fields in `Edit Liquidsoap configuration` page, to insert config which will be directly applied to all playlists (after the next line when they are created by ` .. = playlist ()` function.
