### ISSUE TITLE
Custom Branding Media Uploads fail

### ISSUE THREAD

**Issue by keeganwhite** [AzuraCast/AzuraCast#6750]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #b5ef6ea

### What happened?

When navigating to the custom branding section in both the admin and station options I am unable to upload an image. I thought this may be a permissions error with the docker volume but I adjusted the volumes to be readable and writeable by all (777) and this still didn't work. I was able to override the background image etc. by manually copying the file into the docker's file system and replacing the original image.

**Comment by BusterNeece** [comment]
Having trouble reproducing this. Seems to work fine on my end. Make sure, if you're using a nontraditional way of installing AzuraCast (i.e. a one-click app), that you've mapped the volume to `/var/azuracast/storage/uploads` instead of `/var/azuracast/uploads`, though both should work just the same in the application.
