### ISSUE TITLE
Oops! Playing a scheduled remote stream suddenly plays on ALL stations!

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6769]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #155f66e (2023-11-05 17:46)

### What happened?

I have 3 stations, and one of them has a scheduled remote stream on Saturdays, which just started.

Works fine on the station it’s _intended_ for, but suddenly ALL my 3 stations interrupted and play that remote stream! All three stations work from the same media folder (two were originally cloned from the first station), but they _do_ have different schedules:

- Station "Nite Radio" should play the remote stream
- ditto for "Nite Radio Rock"
- "Nite Radio Berlin" has nothing on schedule, only general rotation but ALSO plays that stream.

![Auswahl_307](https://github.com/AzuraCast/AzuraCast/assets/3706922/24904230-1420-42e2-b120-ba134cf04216)

Nothing odd to see in the logs, except a LOT of nowplaying updates at 18:00 (when the stream started).

Could there be some "leftovers" in the cloning process that lead to this?
Possibly related? → #6702

**Comment by Moonbase59** [comment]
I disabled the remote stream playlist on station "Nite Radio Rock", but it kept playing.

I then restarted broadcasting on _both_ "Nite Radio Rock" and "Nite Radio Berlin", and that finally brought things back to normal.

I wonder if this is an error when scheduled remote streams start, or a leftover cloning problem. Any idea how to diagnose this?

**Comment by Vaalyn** [comment]
Have you cloned the station before or after setting up the remote playlist on the original station?
If you have set it up before cloning then I'd expect it to be cloned into the clone.

Generally remote playlists are generated hard-coded in the Liquidsoap configuration since we don't have an easy way to push remote streams via annotations. So when you need to disable/remove a remote stream playlist you have to restart the station or it wont know about the change.

**Comment by Moonbase59** [comment]
Yes, I cloned it _after_ the remote playlist was set up. And yes, the playlist _was_ cloned into the other stations, but:

- is _disabled_ on "Nite Radio Rock"
- and actually _all_ cloned playlists were deleted on "Nite Radio Berlin"

**Comment by Vaalyn** [comment]
To preface this, I haven't done much with the station cloning feature for quite some time so don't trust my ramblings 100% 😉 

Generally since you cloned the station with the remote playlist existing I'd expect it to end up on the clone too.
Then after cloning I think it should start the station, thus it generating a LS config where this remote playlist exists too.

When you then disable or delete the remote playlist you have to restart Liquidsoap so it generates a new config and actually loads the new config or it will still think it exists, because it's still in the config it has previously loaded.

> I’m sure I have at least restarted broadcasting (maybe not the whole station though) a few times since cloning. Then again I did a few updates since, that should stop and start the whole bunch, right?

It should, at least I think so though haven't looked into the part for some time and I'm not sure if it re-generates the config on an update although I'd expect it to do that.

In order to debug if the cloning & disabling works as expected you could clone the station where the remote is active, then check what the LS config of the clone contains after cloning, then disable/delete the playlist from the clone, restart, then check the config again to see if it correctly generated the new config file without the disabled/deleted playlist.

**Comment by Moonbase59** [comment]
Okay, I could try that, but the last clones had problems, see #6702. I’m currently on RR #[155f66e](https://github.com/AzuraCast/AzuraCast/commit/155f66e0a31d045dff5cfd087bc952e058067af0) (2023-11-05 17:46), should I upgrade first?

**Comment by Moonbase59** [comment]
So I updated and use "Restart Broadcasting" on every remote stream change.
Let’s close this in favour of more important issues.
