### ISSUE TITLE
Web players too tightly coupled? Cannot make request on other station.

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6779]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #ee11476 (2023-12-04 7:10)

### What happened?

I have 3 stations, one is my "base" station, the other two clones thereof (for testing some things).

Using the public player pages, when I request a song on station \#3, it works.
I then try to request a song on station \#1 and it tells me "Du hast in letzter Zeit zu oft einen Wunsch eingereicht! Bitte warte, bevor du einen weiteren einreichst." _in German_ although the player displays English buttons.

I also noticed one player stops the other(s) when I open multiple players (on different stations), so I suspect they are somehow talking to each other, albeit I’m addressing _different stations_.

**Comment by Sella-3DX** [comment]
Based on this explanation I'd guess it checks and saves the IP address globally to prevent flooding the server with too many requests on all stations.

For myself I'd call it a security feature.

**Comment by Moonbase59** [comment]
Well, I call it _a bug_. Limiting requests is fine, but please _per station_.

**Comment by Sella-3DX** [comment]
I guess this is personal preference if this could be called a bug or a security feature 🙂
But I'd say we should wait what Buster says about this - I'm still with the idea that this thing is a feature to prevent flooding the server (which sometimes makes sense).

**Comment by RadioHerzblut** [comment]
I have the following case with the song request. 

- 
- The time until the integration into the rotation is set to 5 min. 

- Next request possible after 15 minutes.

The request only comes after about 50 minutes.

**Comment by BusterNeece** [comment]
> Using the public player pages, when I request a song on station #3, it works. I then try to request a song on station #1 and it tells me "Du hast in letzter Zeit zu oft einen Wunsch eingereicht! Bitte warte, bevor du einen weiteren einreichst." _in German_ although the player displays English buttons.

Not sure what's up with the translation thing there, _that_ may be a bug...

...but the thing with rate-limiting requests globally across the AzuraCast installation is definitely not a bug, that's its intended functionality. I don't personally think AzuraCast stations are "separate enough" to avoid a determined person flooding _every_ station on a given installation with possibly automated requests, and since we don't have things like ReCAPTCHA involved in that process, the only thing we can really do is to share a common rate-limiting cache across the stations on a single installation.

> I also noticed one player stops the other(s) when I open multiple players (on different stations), so I suspect they are somehow talking to each other, albeit I’m addressing _different stations_.

That's unrelated to the request rate-limiting but is indeed a new feature and is intentional to avoid overlapping playback.

**Comment by Moonbase59** [comment]
Guess resellers or independent stations operating a stream server together won’t be too happy…

**Comment by BusterNeece** [comment]
It's been this way for years and honestly I haven't seen any complaints about it. To the contrary, when a server gets flooded, it tends to be _all_ the stations on a server that get hit, and flooded with requests, and this specifically helps to mitigate that issue.
