### ISSUE TITLE
Upload Track with Web Interface problem. 

### ISSUE THREAD

**Issue by Ignacio1972** [AzuraCast/AzuraCast#6790]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.3 Stable • Docker • PHP 8.2

### What happened?

Everytime I upload a track through the web interface, it adds an underscore before the artist and changes every thing to lowercase. This doesnt happend when I upload with FTP. Please help.

**Comment by BusterNeece** [comment]
@Ignacio1972 It's supposed to do this while uploading via the web interface (this is because spaces in paths can cause issues in some environments, so this is done for compatibility), though if you're seeing the artist/title metadata as having dashes/underscores in it, then that's an error that may be caused by your ID3 metadata not being set correctly. You can always update the metadata directly inside the media editor, though.

**Comment by Ignacio1972** [comment]
All fine. Thank you Buster. You are the best.
