### ISSUE TITLE
Livestream volume much lower then playlist

### ISSUE THREAD

**Issue by El-Magyar** [AzuraCast/AzuraCast#6803]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

I have a problem with my radio station that when I play live stream, it has much lower volume on public player, then when it's just playing playlist music. I tried with several setups and programs, and always coming with the same results. Main problem is that when I finish livestream, then the broadcast goes to setup playlist, which is quite louder, and it's just bother for the listeners.
Is there any way that I can volume up my live stream? To somehow level it up with playlist volume.

**Comment by Moonbase59** [comment]
I simply _force_ my DJ’s to have all material replaygained with a -18 LUFS target, and stream at correct levels, otherwise _they’re not allowed on stream_. Basta.

My video streams are at -23 LUFS as recommended by the EBU.

You _could_, of course, use Liquidsoap’s `amplify()` to correct the stream volume, but it won’t better quality. Garbage in, garbage out.

A quick-n-dirty solution would be to use the `master_me` post processing and allow it to also handle live strems. It’s in the docs.

**Comment by RadioHerzblut** [comment]
Use the StereoTool for this. I am at my desired -16 LUFS.

**Comment by El-Magyar** [comment]
great, thank you guys
