### ISSUE TITLE
Better message for "This station has no qualifying playlists for this feature"?

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#6804]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #14a1513 (2023-12-15 22:45)

### What happened?

I use the embed widget for "Song request", and the message

```
RuntimeException at /var/azuracast/www/src/Controller/Api/Stations/AbastractSearchableListAction.php L35:
This station has no qualifying playlists for this feature.
```

totally confuses users.

Could this be made something simpler (and translatable) like maybe `Song requests are currently not enabled.`, `Sorry, song requests are not enabled in the currently running program.`, or the like?

![Musikwunsch | Nite Radio – Mozilla Firefox_001](https://github.com/AzuraCast/AzuraCast/assets/3706922/6513904e-2671-4d77-93e6-87940374dbb5)

**Comment by Sella-3DX** [comment]
I agree with this. I also would like to suggest a change to the message when the Song Requests are disabled in the Stations Properties (Enable Requests).

We have some kind of automatism which automatically changes playlists to some kind of "Closed" playlist and then disables song requests for a specific amount of time so that Liquidsoap can totally focus on getting the correct titles inside the queue next. But if you then click on the song requests embed you get an exception message saying the station doesn't support this feature right now.

**Comment by BusterNeece** [comment]
> We have some kind of automatism which automatically changes playlists to some kind of "Closed" playlist and then disables song requests for a specific amount of time so that Liquidsoap can totally focus on getting the correct titles inside the queue next. But if you then click on the song requests embed you get an exception message saying the station doesn't support this feature right now.

I mean...that message is correct, though, the station _doesn't_ support using that feature right then.

I'll look into making those error messages more user-friendly all the same, though.

**Comment by Moonbase59** [comment]
No doubt it is correct (and probably helpful for a programmer), but we’re here to make the _listener_ happy… ;-) Thanks for considering!

**Comment by Sella-3DX** [comment]
> I mean...that message is correct, though, the station _doesn't_ support using that feature right then.

In my case I'd just suggest to remove the part of the message which refers to the exception (so the path to the file and the line) - the rest of it is totally fine and appropriate for it.
I just don't want that people coming to us and then ask what this message means because it looks so cryptic and more like a bug than a response message (We had one such case already...). 🙂

**Comment by BusterNeece** [comment]
Updated several things across the board, including ensuring that public-facing exceptions are always translated and that the text of the exception is shown without the "Exception X on Y LZZ" stuff around it. You can still view the exception details in the console log if you're debugging things but users won't see them on the popups.

**Comment by Moonbase59** [comment]
Perfect, thanks for that!

**Comment by Sella-3DX** [comment]
The embeds of Song Requests now show this though:

![image](https://github.com/AzuraCast/AzuraCast/assets/147769367/aa6e3054-8d4a-4d32-b319-5d257e392c32)

Not sure if this is intended as it has a button to the home page which redirects to our login page currently...

**Comment by BusterNeece** [comment]
@Sella-3DX I tweaked that a little in the last commit.

**Comment by Sella-3DX** [comment]
@BusterNeece Maybe we should ask @Moonbase59 now.
IMHO I'd remove the comment about the exception file and the line but I'm not sure what you both think about this.

The page should not look like an empty field though but I'd say it should not look like it's "too techie" for the regular visitors too...

**Comment by BusterNeece** [comment]
I really don't want to "bikeshed" this whole thing. We've already made a great deal of progress in user-friendlifying these error messages, and I'm not intent on stripping the entire application of evidence that it's based on code and uses code to function just because users don't get it, because at some point it will have an adverse effect on our ability to debug things, and that page is one of them. Users will have to just read the message.
