### ISSUE TITLE
Bind IP for Azuracast?

### ISSUE THREAD

**Issue by Zethrus** [AzuraCast/AzuraCast#681]
Hey there,

I would like to know if it possible to bind an external IP address to my Azuracast instance? I have multiple IPs on my dedicated server, but I would like to have Azuracast run off of say "167.4.21.213" rather than 0.0.0.0 like it is currently (which is causing issues with other software on my box). 

I am using the Docker installation method, which I am new to Docker so I've been trying to figure this out all day with no luck :(

Thanks for your time.

**Comment by frozenplaya** [comment]
Hi Zethrus,
use this command from terminal : sudo nano /etc/netplan/50-cloud-init.yaml 
and edit your network ip details. Save and reboot

**Comment by Zethrus** [comment]
I'm on Docker... that's an empty file if ran from the host machine.

**Comment by SlvrEagle23** [comment]
@frozenplaya This may not necessarily be good advice. I'd ask you to hold off on providing advice in threads if it involves editing the system in a way that may be harmful.

@Zethrus Since you're on Docker, having the web server bind to a specific IP is actually very easy. Just find your `docker-compose.yml` file, and inside the `nginx` service, where you see:

```yaml
  ports:
    - 80:80
    - 443:443
```

Update that to add the IP you want to bind to before the first port, then separated with a colon, like:

```yaml
  ports:
    - 127.0.0.1:80:80
    - 127.0.0.1:443:443
```

**Comment by SlvrEagle23** [comment]
@Zethrus You'll want to run `docker-compose down` and `docker-compose up -d` after that to have the changes take effect.

**Comment by Zethrus** [comment]
Figured that was how, but I tried that earlier with no luck. I'm trying to bind a public facing external IP address, not local internal IP.
What could I be doing wrong?

**Comment by Zethrus** [comment]
Nevermind, my mistake. Typo'd.

**Comment by MyTheValentinus** [comment]
Hello @Zethrus,
Like your nginx you can specify your ip interface to bind only on this with specified ports.
This issue is not due to azuracast but is docker general purpose.
See https://docs.docker.com/v17.09/engine/userguide/networking/default_network/binding/ and others documentation from docker.
Thanks

**Comment by Zethrus** [comment]
Yeah, I ended up figuring it out and now I'm using Docker for literally EVERYTHING. Hahaha. 👍 
Thanks!

**Comment by SlvrEagle23** [comment]
@Zethrus Yeah, that's kinda what everyone I know does once they get the whole Docker mindset figured out for the first time...they just want to use it everywhere.

It's so nice for a project like this, too. :)
