### ISSUE TITLE
"Request Last Played Threshold" is being ignored

### ISSUE THREAD

**Issue by Sella-GH** [AzuraCast/AzuraCast#6815]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #8b15a55 (2023-12-21 23:00)

### What happened?

At the very beginning we set the threshold of songs from being requested again after they have been played to 0 but I don't really know if this thing worked all the time or it stopped working recently.
However we're unable to request the same song again if it was requested in the last 10 minutes since it was initially requested.

For example:
If you request a song at 9:10 PM and then try to request it again at 9:15 PM you get the error "Song can't be requested because already in queue" inside the embed. Inside the API you just get a 500 "Internal Server Error" response.
Both events occur even if the song was played in the last 5 minutes already.
If you request it again at 9:20 PM or 9:21 PM it works fine without issues.

Now I'm asking if this behavior is intended like this or if this is a bug? It just occurred while playing with the API a bit and there I requested the same song over and over again... (not sure if it's my fault in the end, lol).

**Comment by Sella-3DX** [comment]
Not stale but still waiting for confirmation or a solution

**Comment by BusterNeece** [comment]
@Sella-GH Sorry for this issue falling off the radar a few times...is this still something that's going on in the latest versions of AzuraCast?

Looking into it, and it certainly should be avoiding throwing the "This song or artist has been played too recently." error if that threshold is set to zero.

However, the "item is already in queue" error is a different error entirely, since we want to avoid users flooding the request system with the same track before the first one even has a chance to queue up. Currently there's no way to override whether a track can be requested while the same track is already pending in the queue.

**Comment by Sella-GH** [comment]
Sorry for not answering in this issue for a few days, currently busy with reworking the app a little bit. 😃

I'm gonna test this soon I guess and then reply back with the results. I worked-around this issue with hard-blocks inside my app so it doesn't approach the threshold at all. Have to disable this whole stuff and then I can test it again.

**Comment by Sella-GH** [comment]
So finally tested it again. The issue occurs right away, even when threshold is set 0 and the song was already played by the AutoDJ.

Each time I request it during the last 10 mins I get the following JSON result via API:
```json
{
  "code": 500,
  "type": "CannotCompleteActionException",
  "message": "Cannot submit request: This song was already requested and will play soon.",
  "formatted_message": "Cannot submit request: This song was already requested and will play soon.",
  "extra_data": {
    "class": "CannotCompleteActionException",
    "file": "/var/azuracast/www/backend/src/Exception/Http/CannotCompleteActionException.php",
    "line": 26
  },
  "success": false
}
```

**Comment by BusterNeece** [comment]
@Sella-GH Well, like I mentioned, the "already requested and will play soon" error is specifically because it's still showing up as _in the queue_. The queue is usually a few songs long, just due to limitations in how we work with Liquidsoap. If it's anywhere in that queue, including playing _right now_, then it won't let you request the same track over again. Once it finishes playing and something else starts, though, it should allow it.

This setting is entirely independent of the request timeout threshold.

**Comment by Sella-GH** [comment]
Duh, okay seems like I underestimated the slowlyness of my server. Somehow the API didn't updated fast enough as soon as the song ended / was skipped so my request was too fast and created the exception...

This can be closed now.
