### ISSUE TITLE
Custom favicon is not set on the song art page

### ISSUE THREAD

**Issue by Sella-3DX** [AzuraCast/AzuraCast#6816]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #8b15a55 (2023-12-21 23:00)

### What happened?

The custom favicon set under Administration -> Custom branding -> Browser Icon is not added to the art page of a song. (https://blabla.com/api/station/key/art/xxxxxxxxxx.jpg)

![image](https://github.com/AzuraCast/AzuraCast/assets/147769367/2ed48cf0-3c57-4239-abeb-9237076b5ced)
![image](https://github.com/AzuraCast/AzuraCast/assets/147769367/97db2717-7cda-4c67-9ce8-ed5b35c648ec)

**Comment by BusterNeece** [comment]
*sigh* Really?

The custom favicon exists because we're able to pass HTML on the HTML pages. Album art responses are, of course, not HTML, and thus can't contain the necessary code to specify a custom favicon.

While we could override the route for `/favicon.ico`, the "default" favicon that browsers look for when there is none in the HTML response, that would not be useful for per-station branding and would thus have limited benefit, and we also don't store custom favicons in that same format.

I appreciate the effort in reporting bugs, but this one is just so absolutely tiny and miniscule. Closing as won't fix.
