### ISSUE TITLE
Invalid media .csv file is being created when a song contains lyrics with line breaks

### ISSUE THREAD

**Issue by Sella-GH** [AzuraCast/AzuraCast#6823]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #803c108 (2023-12-25 19:30)

### What happened?

Test-wise we wanted to try out if it's a good possible solution if we can backup our metadata of the songs via the export to .csv feature of AzuraCast.
We also added some lyrics to songs which are all correctly exported but since they contain line breaks the .csv file gets corrupted.

Here an example of a song which metadata was cut in half through the export function in Notepad++:
![image](https://github.com/AzuraCast/AzuraCast/assets/147769367/8be5231c-6efe-49e6-9d32-2cdf5b2e51ac)

If you import that .csv data inside Excel you get the following result:
![image](https://github.com/AzuraCast/AzuraCast/assets/147769367/3265bb92-1eb0-41ad-aefd-78ae36b7f086)

**Comment by BusterNeece** [comment]
@Sella-GH Interestingly, when I test this on my local installation by putting newlines in song lyrics, it actually is handled by Excel perfectly. It understands that the newline is limited to that cell specifically and doesn't try to wrap around and create a new row like that.

I'm wondering if there's something else in the formatting of those lyrics. Maybe the newline is a different type of newline (i.e. `\r\n` instead of `\n`?). It would be handy to get a test file to test things out with that experiences this issue.

**Comment by Sella-GH** [comment]
@BusterNeece Weird... tested it with another file and there it works flawlessly too.

I am not sure if some dependency was updated and therefore something changed in generating the CSV file but I can use the same lyrics (and name the song the same like in the screenshot) - Excel recognizes it correctly without issues.

Tried it with some other songs too to double check but somehow it works.

**Comment by BusterNeece** [comment]
@Sella-GH We routinely do update our dependencies and it's entirely possible that the CSV writer library got an update at some point. I'll close this for now but let me know if it pops up again.
