### ISSUE TITLE
Audio process

### ISSUE THREAD

**Issue by Developpeur** [AzuraCast/AzuraCast#683]
Is it possible to apply this in an AzuraCast radio?
[Audio Process Liquidsoap](https://github.com/mkpascal/mk_liquidsoap_processing/blob/master/process.liq)

**Comment by SlvrEagle23** [comment]
@Developpeur A number of these things are indeed possible by specifying them in the "Advanced: Custom Liquidsoap Configuration" field in a station's profile. The variable name for the composed radio signal will be `radio`, and any modifications should end up writing to that variable in the end before being output.

Currently, LADSPA plugins aren't supported in AzuraCast, because my experience has shown them to be somewhat unpredictable across different instances, and even installing the LADSPA extension via OPAM does not fully expose the functions you're looking to run in this example. Basic compression, limiting, equalization etc. are all entirely possible, though.

**Comment by stemvantwente** [comment]
Would love to see this working in Azuracast, so all the mp3s what are playing are at the same audio level constantly with a nice sound boost.

**Comment by tonimad** [comment]
@SlvrEagle23 Is this correct to include in the section "Advanced: Custom Liquidsoap Configuration"?

```
'radio = ladspa.gate(default, threshold = -60.0, attack = 0.15, hold = 1.0, decay = 200.0, range = -25.0, radio)',
'radio = sky(default, radio)',
'radio = normalize(default, target = -1.0, threshold = -65.0, radio)',
'radio = ladspa.tap_limiter(default, limit_level = -0.5, radio)',
'radio = limit(default, threshold = -0.2, attack = 2.0, release = 25.0, rms_window = 0.02, radio)',
```

**Comment by SlvrEagle23** [comment]
@tonimad It shouldn't have the `'` and `',` around it (that's only if you're writing to the Liquidsoap configuration inside the PHP like we are), but beyond that, the Liquidsoap advanced configuration is unsupported, so you should experiment to find what works well with our available software components.

**Comment by tropimega** [comment]
no puedo cargar nuevos audios, a que se debe, gracias

**Comment by SlvrEagle23** [comment]
@tropimega Our support is provided in English. Please translate your request into English when using our support tickets. Thank you.

**Comment by sander816** [comment]
has this been updated, or did anyone manage to get this to work?
