### ISSUE TITLE
Unable to browse music files and add new stations

### ISSUE THREAD

**Issue by gromano00** [AzuraCast/AzuraCast#6837]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.3 stable

### What happened?

When I try to access the music files which are connected via SFTP to my Synology, I get the following error:

UnableToRetrieveMetadata at /var/azuracast/www/vendor/league/flysystem/src/UnableToRetrieveMetadata.php L49 to retrieve the file_size for the file at location: music-file.mp3.  I have updated AzuraCast and the Docker engine.  The stations all work, I just cannot see or browse the music files from the admin console and am unable to add any new stations.  I have about 15 stations. This started happening prior to updating to the latest version as of Jan 2, 2024. Any assistance would be very much appreciated.  Thanks in advance!

**Comment by BusterNeece** [comment]
@gromano00 This sounds like a permissions issue. Do you have custom file systems mounted into the directory, or are you using something like an S3 bucket?

**Comment by gromano00** [comment]
Buster - Thank you very much for the response, I apologize for the long delay in my response.  Yes, I have a music directory on a Synology NAS and have that attached to this instance using NFS.  This is running on Ubuntu server which is housed on ProxMox (if that matters).  I have other stations configured the same way with no issue.  For any new stations I add I am now unable to see the music files share when I am configuring the playlist.  I recently bumped the memory from 4 to 8 to see if that makes a difference.  Thanks again for your response. - Greg

**Comment by BusterNeece** [comment]
@gromano00 If you're bind-mounting in another filesystem into AzuraCast, this can sometimes cause permission issues because the user/group ID that owns the files on the filesystem doesn't match the one inside the container that's trying to actually access/update them.

We have environment variables `PUID` and `PGID` specifically for this purpose, to let you change what user the internal `azuracast` user appears to be when doing file operations. The instructions for how to set these values are listed as part of our [Synology NAS installation instructions](https://www.azuracast.com/docs/getting-started/installation/synology/#2-optional-specify-media-directory-for-station). I'd make sure those values are set correctly, that might fix any permissions issues.

**Comment by gromano00** [comment]
Thanks Buster, I will look at that.
Your app is masterpiece!

From: Buster Neece ***@***.***>
Date: Sunday, May 5, 2024 at 8:58 PM
To: AzuraCast/AzuraCast ***@***.***>
Cc: gromano00 ***@***.***>, Mention ***@***.***>
Subject: Re: [AzuraCast/AzuraCast] Unable to browse music files and add new stations (Issue #6837)

@gromano00<https://github.com/gromano00> If you're bind-mounting in another filesystem into AzuraCast, this can sometimes cause permission issues because the user/group ID that owns the files on the filesystem doesn't match the one inside the container that's trying to actually access/update them.

We have environment variables PUID and PGID specifically for this purpose, to let you change what user the internal azuracast user appears to be when doing file operations. The instructions for how to set these values are listed as part of our Synology NAS installation instructions<https://www.azuracast.com/docs/getting-started/installation/synology/#2-optional-specify-media-directory-for-station>. I'd make sure those values are set correctly, that might fix any permissions issues.
