### ISSUE TITLE
Cue sheet

### ISSUE THREAD

**Issue by preterive** [AzuraCast/AzuraCast#684]
Hello,
i wish a cue sheet Function for track namens. Example Here: https://github.com/savonet/liquidsoap/blob/master/doc/content/split-cue.txt

**Comment by preterive** [comment]
i really need this feature for the gema (Germany music licensing)

**Comment by SlvrEagle23** [comment]
Specifics of our interactions nonwithstanding, let me explain why this is a very difficult issue for us to resolve.

When Liquidsoap asks us for the next song to play, it doesn't allow us to specify a full playlist of multiple metadata items for a single song. It basically asks for an annotated version of a single song to play back with title, artist, beginning and end time, etc.

In order to work around this, there are two possible routes of approach:

 - Add in native support, which would include the following steps:
    - Detect if a file has a corresponding .cue file (with a similar filename or somehow attached to the media item itself),
    - Implement Cue file parsing to convert the Cue file's format into something we can understand
    - Treat the single file as if it's multiple files within the parent playlist and shuffle them individually
    - When each individual cued sub-song is played, set the proper cue_in and cue_out values such that only the cued portion of the song plays with the metadata specified

 - Build a "cue converter" that does something very similar to what Liquidsoap does in that example, taking an input file and it's corresponding CUE file and splitting it into constituent MP3s at the time of upload.

Both of these are very complex and might require multiple dozens of hours. The reason it isn't a high priority for us to implement already is because a workaround exists for stations in the form of splitting the CUE'd file prior to uploading, and uploading the individual audio files instead. One recommended piece of software to accomplish this is [Flacon](https://flacon.github.io/), a FOSS tool specifically built for this job.

**Comment by preterive** [comment]
Thanks for your answer! I relly like the Project.
okay, but if i convert it as individual audio files i can't use the shuffle mode anymore, because there are idividual Transitions between the Songs in the Mixes.
I think this would be an issue for Liquidsoap, not? I would open an issue in the next days if there is no issue related to this Topic already.

**Comment by SlvrEagle23** [comment]
@preterive LibreTime is built very differently from AzuraCast and has different priorities for their development. In particular, they're very heavy on the strict show scheduling, and we're more about the "always-playing" playlists.

In your case, you may be better suited using LibreTime at the moment. Their software is excellent as well, and we're both working toward making web radio free and open.

**Comment by preterive** [comment]
No, i still use Azuracast :)
I miss the complete Playlist automation like by your software at LibreTime, that makes Azuracast better!
The problem is not so big for me, it only could make problems wit the german licensing, because i can't sent the artist.

**Comment by SlvrEagle23** [comment]
We're migrating our feature requests over to FeatureUpvote, which allows users to vote on what they would like to see the most, and helps clear our GitHub issues page up for bugs and error reports.

Your enhancement request has been migrated over to FeatureUpvote and can be found here:
https://azuracast.featureupvote.com/suggestions/39020/support-cue-sheets
