### ISSUE TITLE
Blank page with default url

### ISSUE THREAD

**Issue by fidegr** [AzuraCast/AzuraCast#6844]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

We have detected that using the default Azuracast access address shows a blank page. To enter correctly we have to add /login

What could be causing the error?

**Comment by BusterNeece** [comment]
@fidegr The default page should always automatically bounce you over to the login page, unless you have a "Custom Homepage Redirect URL" set on the System Branding page. You may want to check that and ensure that that field is empty (and that there isn't some errant character in it causing it to think it's set).

**Comment by fidegr** [comment]
Hello, thanks for the answer. Well, that field was blank, and I don't think there were any strange characters. Even so, I filled it in with the url+/login and everything works normally.

Greetings.

**Comment by Challado** [comment]
Same here. When I try to access azuracast.mydomain.com on Chrome the page appears blank, but firefox indicates a redirection error: "The page isn’t redirecting properly Firefox has detected that the server is redirecting the request for this address in a way that will never complete. This problem can sometimes be caused by disabling or refusing to accept cookies"

**Comment by BusterNeece** [comment]
Thank y'all for the reports. This should be fixed in the latest Rolling Release.
