### ISSUE TITLE
Unable to retrieve the mime_type for file at location: stereo-tool.sts

### ISSUE THREAD

**Issue by ryangontv** [AzuraCast/AzuraCast#6889]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#a5fb310

### What happened?

Trying to download Stereo Tool config and get the following error when I click download:

Error
Unable to retrieve the mime_type for file at location: stereo-tool.sts.
vendor/league/flysystem/src/UnableToRetrieveMetadata.php : L49

**Comment by Sella-3DX** [comment]
Same happens when you want to download a created backup:
![image](https://github.com/AzuraCast/AzuraCast/assets/147769367/ec844048-2e96-4d98-817e-90fd9c72b819)

**Comment by Moonbase59** [comment]
Can’t repro here. Does this still happen using the latest RR #[609d94a](https://github.com/AzuraCast/AzuraCast/commit/609d94a0bb9fb379c89ab8c3203ed4ee6833b7cc) (2024-01-22 23:25)?

(My AzuraCast runs on an Ubuntu 22.04.3 LTS VM, backups are on the local SSD, media folders are remote NFS mounts.)

**Comment by Sella-3DX** [comment]
Using latest RR on Debian 12 VM but backups are stored via SFTP on an external storage

**Comment by Moonbase59** [comment]
Seeing that we lately get more reports about SFTP problems, I’m beginning to suspect that sshfs (filesystem over SFTP) isn’t a good choice, due to different implementations and often the impossibility to seek within files… Just a gut feeling, though. Many use it without problems.

**Comment by ryangontv** [comment]
Haven't had the SFTP issue here, using latest rolling release or latest stable release. I still get that issue trying to get the stereo tool file using the latest rolling release.

**Comment by BusterNeece** [comment]
> Seeing that we lately get more reports about SFTP problems, I’m beginning to suspect that SFTP/sshfs (filesystem over SFTP) isn’t the best choice, due to different implementations and often the impossibility to seek within or append to files… Just a gut feeling, though. Many use it without problems.


I'm beginning to think this is the case...SFTP just involves a lot of setup and tear-down with each connection and request, and since we're dealing with PHP, that has to happen with basically every single request, which can absolutely hammer a SFTP server expecting a reasonably small number of requests. Sure, we do cache things like album art in multiple locations (and we cache media locally for Liquidsoap to play when it's time for it to play it), but I can definitely see how there'd be issues with timeouts and other things.

**Comment by marekdziem** [comment]
I just connected remote sftp storage and moved over some station media files successfully  - ie, the mp3 files show up in the station ...media....files page, initially flagged "File Processing" until done, and then the duration, play icon and album art show.

Clicking a files play icon pops up the mediacontrol with stop & volume bar  - but no audio plays.

When I click to access a file the link opens ina new tab eg.
https://radio.eclipse-streaming.co.za/api/station/2/files/download?file=bob_marley__the_wailers_-_no_woman_no_cry.mp3

and shows a similar error: 
Unable to retrieve the mime_type for file at location: bob_marley__the_wailers_-_no_woman_no_cry.mp3.
vendor/league/flysystem/src/UnableToRetrieveMetadata.php : L49

Uploading a new mp3 file to the sftp media store gives the same result.

Reason I'm moving files off local server is because the azuracast docker volumes  - overlay / tmp / diif / merged - have suddenly gobbled up ALL the server drive space and I cant find a way to successfully prune / delete the doubled-up docker volumes! 

really dunno what I can do now...

Am on v0.19.4 Stable • Docker • PHP 8.2

**Comment by marekdziem** [comment]
wondering if any have some practical suggestions for:
