### ISSUE TITLE
Total number of songs in library

### ISSUE THREAD

**Issue by ivanpotylitcyn** [AzuraCast/AzuraCast#689]
**Is your feature request related to a problem? Please describe.**
I need to control total amount of unique traks in media library. I need it to reach my oun goal of 1200 songs for internet-radio. I can approximately estimate number of songs using playlists table. It's enough, but sharp index will be really nice.

**Describe the solution you'd like**
I want to see the number of songs in library near the used volume progressbar on Music Files page.

**Describe alternatives you've considered**
I don't see any alternatives. The used volume progressbar is the place from where I've started to search.

**Additional context**
This is not a critical feature. But useful index of an internet radio-station. Thank you for your great product!

**Comment by ohld** [comment]
And please show the user who have uploaded the file! It may be very useful for large team management.

**Comment by Likeandfeel** [comment]
Hi 

@ivanpotylitcyn We suppose you have only one radio right
So if you go to "Music Files" at right bottom you have how many media you have inside your radio. By exemple >> Showing 1 to 10 of 237 entries

For your asking i didnt see solution inside system for now. I suggest you to open ticket as Evolution instead of bug.

@ohld nativly system dont do it, but you can change report we spoke early, and add inside SQL query one field regarding this. I suggest open as well Evolution ticket :P
 
Bests regards

**Comment by ohld** [comment]
@Likeandfeel Ivan and I are hosting the same radio. We have all our sound being separated into folders, that's why "1 to 10 of 237 entries" is 237 folders in our case.

**Comment by Likeandfeel** [comment]
Hi

Its file no folders

**Comment by ohld** [comment]
@Likeandfeel Hi. No, you are wrong. I've just checked. We have exactly 172 folders in the root folder.
<img width="253" alt="image" src="https://user-images.githubusercontent.com/5613295/44523248-e2ef8300-a6e1-11e8-805d-c9d694afe7cf.png">

**Comment by SlvrEagle23** [comment]
@ivanpotylitcyn @ohld Total file count is implemented now on the music files page, thanks to a contribution from @Vaalyn.

The request for tracking the uploader of a file should be a separate enhancement request, and it should be noted this won't always be possible due to SFTP uploads.
