### ISSUE TITLE
Change the station timezone

### ISSUE THREAD

**Issue by ohld** [AzuraCast/AzuraCast#690]
**Is your feature request related to a problem? Please describe.**
I'm missed the thing where I should select the right timezone of the Azuracast. I found a solution to change the timezone for a each created user - that is not very handy. Wrong timezone ruins the scheduled playlist creation. 

**Describe the solution you'd like**
Add the timezone fiend in System Settings. 

**Describe alternatives you've considered**
Docker.sh command to change timezone 

**Additional context**
Let's add more customisation!

**Comment by SlvrEagle23** [comment]
@ohld You can now set a global system default timezone which all users who do not have customized time zones will see. It's far more complicated to set up a per-station timezone, especially since there are some areas of the site that show multiple stations and it would be undefined which timezone they would show, but this should hopefully improve the experience out of the box for users who haven't customized their timezone.

I've also modified the time zone configuration to properly list every individual time zone area, rather than just listing UTC offsets, so you can now properly select the area you're in and have DST adjust correctly.
