### ISSUE TITLE
Azuracast in docker reports the wrong location for media files

### ISSUE THREAD

**Issue by rogercreagh** [AzuraCast/AzuraCast#6902]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #f2c5050 (2024-01-30 17:51) • Docker • PHP 8.2

### What happened?

Under Storage Locations it gives the local location as `/var/azuracast/stations/main_mix/media`

This is a lie.

In a docker install it is actually  at `/var/lib/docker/volumes/azuracast_station_data/_data/station_name/media`

The info on the screen should reflect the true location, and should also carry a warning that this is no accessible outside docker, and that an new file locations added will be within the docker space - azuracast can't access locations like `\home\user\music\` even if the are chmod 777.

### Relevant log output

```shell
n/a
```

**Comment by DocTator2281** [comment]
This isn't a bug - it's the nature of what a Docker installation is. The only thing I use that external directory for is for taking quick backups of my media if the built in backup method times out (sometimes it does with a lot of media)

As I advised in the other discussion, your best bet if you absolutely needed your media to be in regular filespace is an Ansible installation, but keep in mind it's not supported, more than likely due to too many external variables affecting people's environments.

**Comment by rogercreagh** [comment]
> This isn't a bug - it's the nature of what a Docker installation is. The only thing I use that external directory for is for taking quick backups of my media if the built in backup method times out (sometimes it does with a lot of media)

To me its a bug, albeit a trivial one from a purely functional point of view. Azurcast is telling a lie - the files are not where it says they are. That is extremely poor practice and misleading. At the very least it should say "The local media files are hidden within the docker container and not accessible outside."

**Comment by Moonbase59** [comment]
»Oh help! My Linux is telling a lie – the files are not where it says they are.« (They are actually on another _machine_ even—just mounted into the file system.)

Same argument. AzuraCast doesn’t _lie_, it just tells you what it sees. Since it runs in the Docker environment, it sees exactly that. Or whatever you mount into it. See https://github.com/AzuraCast/AzuraCast/discussions/6901#discussioncomment-8328413

**Comment by BusterNeece** [comment]
This is by design in AzuraCast as others have said above, though if you're unfamiliar with Docker I can see how it would be confusing. I would strongly recommend sticking with the Docker ecosystem, as it's where we offer our greatest degree of reliability and stability and can deliver updates rapidly.

We have instructions here for how to mount a physical directory from your host into the Docker ecosystem so that AzuraCast will "see" it and be able to manage the media within it: https://www.azuracast.com/docs/administration/docker/#mounting-a-directory-into-a-station

**Comment by rogercreagh** [comment]
Thanks @BusterNeece that's really helpful and exactly what I need. I can't think how I missed that when checking the docs - but I did. Mea culpa.

I still think the text given for the location is just plain wrong (and very unhelpful) though, and should be tidied up - a pretty trivial change needed.
