### ISSUE TITLE
URGENT | Error 500 after creating a 3 * station

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#693]
Hi everyone, I created a third station. After creating it / api / nowplaying it does not work anymore, giving an error. The song titles are not shown in the new channel and it's all buggy. I urgently need help for my listeners!
![image](https://user-images.githubusercontent.com/22561729/43642875-775256c6-9729-11e8-829f-03a71cfccce6.png)

**Comment by Ilario42** [comment]
Warning: file_get_contents(http://IP:81/api/nowplaying/3): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in D:\Applicazioni\Xamp\htdocs\directory\station.php on line 22

**Comment by SlvrEagle23** [comment]
@Ilario42 You haven't provided enough information for me to be able to diagnose this issue.

What is the ID number of your third station? Did you select to hide it from public pages? Have you provided a "short name" so that the public URL of `/public/short_name` would work?

Please provide additional information so I can continue debugging the issue.

**Comment by djmarcoleiva** [comment]
@Ilario42  are you running under vps ? what configuration you got ? i'm thinking maybe could be problem of resources (need more cpu)

**Comment by Ilario42** [comment]
Solved
