### ISSUE TITLE
How do you define "Best performing songs"?

### ISSUE THREAD

**Issue by ohld** [AzuraCast/AzuraCast#694]
![image](https://user-images.githubusercontent.com/5613295/43647085-472d4800-973f-11e8-90f0-285bcf972014.png)

How do you define "Best performing songs"?

**Comment by SlvrEagle23** [comment]
@ohld Good question. This isn't really defined anywhere else, so I'll let this question serve as the answer for what "highest performing songs" means in this context.

With the automated song assignment tool, each song is assigned a "ratio" based on the "impact" it had on the listener count of your station. This ratio is calculated as so:

```php
<?php
$delta_total = $delta_positive - $delta_negative;
$ratio_points[] = ($listeners_start == 0) ? 0 : ($delta_total / $listeners_start) * 100;
```

Basically, the "delta" is the change in listeners gained or lost since the song started playing. The ratio is how big that delta was relative to the original number of listeners the station had. So, if a station only had 2 listeners, but it lost both of them during one song, this would be much more significant than if 2 listeners were lost out of, say, 250.

All of this is based on the assumption that listeners will immediately disconnect from any radio station that's currently playing a song they *don't* like, and may reconnect later if they see a song is currently playing that they *do* like. This is admittedly a vast oversimplification of the actual dynamics of what makes listeners come and go on a station, but given our lack of detailed analytics to work with, it's about the best we can do in this situation.

**Comment by ohld** [comment]
The information about the songs that forced a user to disconnect is a very valuable: we can, for example, remove that songs from our playlist or play this song in a different daytime. 

But the information in which exact song a user connected to the stream is **useless**: users usually start to listen the radio at a random time. 

The proposed improvement: we can track songs that forced a user to listen to the next song. In other words, increased the user's retention. 

For example, you can give a score point to the song if a listener starts to listen **the next** song.

**Comment by SlvrEagle23** [comment]
@ohld To be entirely honest with you, the "radio automation" feature was built originally for one single station, which was the initial pilot test station for AzuraCast back when it was being originally developed.

It's frankly quite complicated under the hood, and in my vision for what AzuraCast is, is too hard to test, explain and use to line up well with the simplicity of AzuraCast in general.

The feature's more likely to be retired entirely than refined.

**Comment by ohld** [comment]
So lets just define more metrics to value songs performance! The new analytics tab will be very useful for all Azuracast users.

**Comment by ohld** [comment]
Being a business person, I can help you to define the proper metrics.

**Comment by SlvrEagle23** [comment]
@ohld I caution any user against talking about me and my development work like it's a paid position when it very much isn't one. If you're interested in paying for prioritized development in certain areas, then I'm happy to focus on those, but otherwise it's a matter of my own schedule availability.

**Comment by ohld** [comment]
@SlvrEagle23 
I respect your priorities and desire to develop this software for free. I am not asking for this analytical dashboard as a matter of urgency. I just want to help you identify Analytics metrics that are useful to business and help you make your product stronger.
