### ISSUE TITLE
Stations Offline

### ISSUE THREAD

**Issue by dekakast** [AzuraCast/AzuraCast#6954]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.4

### What happened?

In System Settings, I checked the box to "Use High-Performance Now Playing Updates" but it took all my stations offline. I turned it off and the stations came back online. 

The Standard Now Playing API still works with box unchecked. I am guessing I have to check the box again to turn on SSE, but it will just take my stations offline again, and I still won't get any SSE now playing info.

**Comment by jpcastberg** [comment]
I had a very similar problem to this - station showed as offline, though would start showing as online after about 30s. I found that the wait was due to the page not having received the first server side event.

I tracked the problem down to nginx, I had to add `proxy_buffering off;` to the location block for azuracast, then reload the config.

I hope this helps with your problem! Please lmk if you have any questions.
