### ISSUE TITLE
Cache key can contain invalid chars

### ISSUE THREAD

**Issue by marekdziem** [AzuraCast/AzuraCast#6963]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.5 Stable

### What happened?

updated to latrest stable realease
now there are no stations found

error: Cache key "now_playing.station_the_better_(dot)_fm" contains reserved characters "{}()/\@:".

server is broken - help urgently!

### Relevant log output

```shell
Cache key "now_playing.station_the_better_(dot)_fm" contains reserved characters "{}()/\@:".
```

**Comment by marekdziem** [comment]
managed to figure it out..
station name had brackets in it

**Comment by BusterNeece** [comment]
Thank you for your report. This is fixed in the latest Rolling Release, so you can now use special characters in station short names again without issue.

**Comment by druff99** [comment]
I just updaded today and have the same issue. 
Cache key "now_playing.station_general_(events)" contains reserved characters "{}()/\@:".

All streams are playing,but it keeps showing this error and all streams are not visible in the main page

**Comment by BusterNeece** [comment]
@druff99 Are you on the latest Stable version? This has been fixed in the latest Rolling Release but may not be in Stable yet.

**Comment by marekdziem** [comment]
We��re on stable release

 �

 �

**Comment by druff99** [comment]
> @druff99 Are you on the latest Stable version? This has been fixed in the latest Rolling Release but may not be in Stable yet.

yes, we are in  • v0.19.5 Stable • Docker • PHP 8.3 and i dont see any stream in my front page (even though we have several) and i also keep seeing the folllowing error : Cache key "now_playing.station_(station-name)" contains reserved characters "{}()/\@:".

**Comment by BusterNeece** [comment]
@druff99 To be clear, this bug has been fixed in the Rolling Release version, but the fix hasn't made it into the Stable version just yet. You'll want to either remove special characters from your station names or update to the latest Rolling Release: https://www.azuracast.com/docs/getting-started/updates/release-channels/#switching-from-stable-to-rolling-release

**Comment by druff99** [comment]
From the error, it’s not special characters in the stations name, but the songs. Ok, good hint. About the rolling release. What about the “empty list” of stations in the front page? Is this also fixed with this bug?On 21 Apr 2024, at 03:20, Buster Neece ***@***.***> wrote:﻿
@druff99 To be clear, this bug has been fixed in the Rolling Release version, but the fix hasn't made it into the Stable version just yet. You'll want to either remove special characters from your station names or update to the latest Rolling Release: https://www.azuracast.com/docs/getting-started/updates/release-channels/#switching-from-stable-to-rolling-release
