### ISSUE TITLE
MUTED SONG

### ISSUE THREAD

**Issue by cosmaboz** [AzuraCast/AzuraCast#7005]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

I uploaded the songs but once uploaded they are silent.
they leave but nothing is heard.
the wafeform in the song editing settings is blank, as if nothing was loaded.
It didn't give me any problems loading files and the songs sound good outside the program.
they are all mp3 files.
you can't even hear anything on the radio.
how can I do?

**Comment by cosmaboz** [comment]
first problem I managed to solve: now I can add the songs correctly.
the problem was that I had the radio and the server on two different addresses.
I can open and edit the songs: therefore they have been imported into the program correctly.
the radio however remains silent. the songs flow but you can't hear anything.
anyone have the same problem?

**Comment by thackmaster** [comment]
You mentioned that the radio and server were on separate servers, but you've since moved them. I'm going to assume the files are directly uploaded to AzuraCast, which puts them in a local folder. My instance uses an S3 bucket and I've never had any silence issues. If you could post some logs from the affected station, that might help us narrow down where the issue might be stemming from.
