### ISSUE TITLE
Scheduled playlists do not start on time

### ISSUE THREAD

**Issue by bo2008** [AzuraCast/AzuraCast#703]
Is it possible to have scheduled playlist interrupt the autodj (general rotation)? That is, if a playlist is scheduled to start at 10:30, and a 10 minute track starts at 10:25, the scheduled playlist will cut the general rotation and start the scheduled time.

**Comment by SlvrEagle23** [comment]
@bo2008 This isn't actually so much a bug as a quirk with how Liquidsoap and AzuraCast interact with one another.

By default, Liquidsoap requests the next song to play a second or two before it cues up using an AzuraCast API under the hood. This lets Azura keep track of the scheduling and avoid duplicate playback, which also allows us to have much richer metadata about now-playing songs (including duration, remaining time, and the next song). This prevents AzuraCast from forcibly interrupting a song playing on the AutoDJ, though.

There is a "manual AutoDJ mode" that you can enable for your station which will put playback control back in Liquidsoap's hands. Even then, though, by default it won't just cut off a song in mid-playback as this would likely not be desirable to the majority of users.

To do what you're wanting to do, you'd likely have to go one step further and make the interrupting playlist an "advanced" playlist, which would allow you full control over how it's integrated into Liquidsoap; you could then add something like the line below to your Advanced Liquidsoap Configuration in the station's profile:

```
radio = fallback(track_sensitive = true, [switch([({12h0m-14h0m},playlist_my_playlist_name)]), radio])
```

Sorry it's not more straightforward than that, but it's a fairly uncommon condition for music to need to interrupt other music, rather than a live DJ interrupting the AutoDJ, for example. Hopefully this answers your questions or at least gives you somewhere to start experimenting for the right experience.

**Comment by bo2008** [comment]
Though I don’t know much about coding but I’ll give it a try as per your advise. Thanks for your speedy response.

**Comment by bo2008** [comment]
Thank for your feedback @SlvrEagle23 this has really helped, much appreciated. However, how would I go about scheduling for a specific day of the week and time?

**Comment by isaiaswebnet** [comment]
How can I have a correct time list with AzuraCast?
