### ISSUE TITLE
some songs get titles duplicated

### ISSUE THREAD

**Issue by ofsaleem** [AzuraCast/AzuraCast#7040]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.19.5 stable

### What happened?

![image](https://github.com/AzuraCast/AzuraCast/assets/7631554/9000114d-35d0-446b-9b19-298bc87ae63f)

occasionally some songs get their title added to the song twice. this doesnt exist in the tags on the mp3 file itself, and this seems to happen like...over time? as the station runs? last time it got so bad every song that played was like this until i removed all media and re-added it. it seems to be added to the database tho as if i edit the file in azuracast the title field does show the junk data. reprocessing the files and restarting the containers doesn't fix the 'corrupted' files

**Comment by RM-FM** [comment]
@ofsaleem I know that this has been discussed already once in the past. It is somehow related to the ID3v1 and ID3v2 tags of the mp3 files. As far as I remember, you should not use ID3v1 anymore but ID3v2 only.

**Comment by shamu450** [comment]
@ofsaleem I ran into the same issue recently. Your files are probably tagged with lyrics3 tags or other additional tag as well. Mine were and I removed this tag and double titles went away after I reprocessed the files in Azuracast.

I was able to use [mp3tag](https://www.mp3tag.de/en/index.html) to see that my files had id3v1, id3v2 and lyrics3v2 tags. The lyrics3 tag depends on id3v1, so removing id3v1 tag will also remove the lyrics3 tag. ID3v1 is very eazy to get back if you need it.

To remove the lyrics3 tag open mp3tag and: 
- go File > Options > Tags > Mpeg:
- under write choose the tags you want your file to have. I kept id3v1 and id3v2.3
- under remove choose only id3v1 (very easy to get back if needed, don't worry. keep reading)
- OK to close options
- next load up some songs

Look in the tag column and see what tags your songs have, if you see some with lyrics3v2 tag you can look in Azuracast and confirm that file has double titles. 

Right-click on the file and choose remove tag. This will remove the tags you choose in the options under remove tag. So it will remove the id3v1tag and because lyrics3 tag cannot be unless there is id3v1tag, it also is removed.

Now if you want the id3v1 tag, click the undo button. This will put the id3v1tag back minus the lyrics3 tag.

You should now have a file that has id3v1 and id3v2 tags, save the changes.

Choose the file you changed in Azuracast and reprocess. Once done they should now have one title.

I did find another script to do this via the command line by Moonbase59 [rmlyrics3 - A Lyrics3 tag remover for MP3 files, written in Python.](https://github.com/Moonbase59/rmlyrics3) but it failed when I ran it, I have messaged Moonbase59 with the error, hopefully an easy fix or possibly user error and it will work for you.

I hope this helps you and any other future users that may come across double titles because of multiple tags.
