### ISSUE TITLE
Slow search in latest versions compared to in the past

### ISSUE THREAD

**Issue by Fridgemagnet** [AzuraCast/AzuraCast#7041]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #5fe95f4 (2024-04-02 15:53)

### What happened?

Hello there,
not sure if this is known but the search for music in the "Media->Music Files" menu takes upwards of 15 seconds for me when it seemed instantaneous in the past. I unfortunately can't pinpoint when this behaviour started as searching for media that way is not something I do often. There are no errors to be seen in the logs.
Nothing has changed with my setup of late (of note: media is presented through a docker smb volume).
Azuracast is updated through a periodic cronjob:
`/home/serveradmin/docker/azuracast/docker.sh update-self`
followed by
`yes "" | /home/serveradmin/docker/azuracast/docker.sh update`

**Comment by keybrdist** [comment]
confirmed happening also on Rolling Release #e9255d2 (2024-03-28 17:37)

**Comment by BusterNeece** [comment]
We were experimenting with a new search technology called FusePHP (based on FuseJS) that allows for very complex searches (and also searching things like custom fields), but it seems that it results in significantly slower searches in a lot of real-world use cases, even ones that don't actually use the "extended search" functionality it offers.

We'll revisit this in the future, since we want those powerful search technologies to be available to us, but not at a big performance deficit and not with the problems that were inherit in solutions like Meilisearch (which was a quite nice option, but which used more memory than most installations wanted to use, and which we never quite figured indexing out on).

Someday I'll get this stuff figured out!

**Comment by Fridgemagnet** [comment]
Much appreciated. Thank you.
