### ISSUE TITLE
Azuracast devours CPU, a big failure compared to the rest of the panels.

### ISSUE THREAD

**Issue by alerickert** [AzuraCast/AzuraCast#7043]
### Installation Method

One-Click Installation (Docker)

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#5fe95f4

### What happened?

Hello everyone,

I'm an entrepreneur with 19 years of experience in the streaming industry. Recently, I've been testing AzuraCast with the intention of using it for production with large radio stations with over 10,000 real listeners.

Unfortunately, the results of my tests have been very poor in terms of CPU performance.

We're using servers with 32 cores and 128GB of RAM. As soon as we conduct stress tests, the CPU usage spikes above 90% and eventually crashes with a maximum of 20,000 listeners, causing interruptions. Even without AutoDJ, it can handle a bit more, but still encounters CPU issues. The CPU consumption is alarmingly high.

In comparison, with other panels like SonicPanel, 20,000 listeners consume about 3 CPUs and 20GB of RAM, whereas AzuraCast consumes 32 CPUs.

I would like to know if anyone is aware of this serious problem, as it unfortunately prevents us from using AzuraCast for large-scale operations.

**Comment by Vaalyn** [comment]
First of all: Coming into an open source projects repo (that is 99% maintained by one guy barely scraping by) and declaring it a "big failure" compared commercial projects who have dedicated paid engineers and an incentive to cater to big businesses due to paid support contracts is disingenuous at best and generally outright rude. I don't expect people to not complain about issues they encounter (otherwise those issues couldn't be discovered and fixed) but I do expect them to have a modicum of respect for other peoples work / live and not casually 💩 on it.

Apart from that, if you want to use this software for such high volume operations and there is an issue with the CPU usage it would be mighty helpful if we can get more than a "uses too much / all cpu", like actually information about:
- Which processes are using the cpu the most?
- How are you connecting the listeners?
  - Directly to the IceCast/ShoutCast ports?
  - Through the NGINX proxy?
  - Or through HLS?
- Which streaming formats are you using?
- Are the listeners only using the stream or the public page?

**Comment by BusterNeece** [comment]
To be fair, the title of this issue is:

> a big failure compared to the rest of the panels

So...we have every right to insist that users be more respectful and polite than that.

If listeners are connecting directly to the Icecast stream, then there are two possible explanations for excessive CPU consumption: it could be a result of the initial connection calling a PHP script to determine if the user is geographically banned in the panel (which would mean that the CPU consumption only spikes briefly during connection, and wouldn't be sustainably high, so as long as your listeners don't connect *all at once* like that, it won't be a problem) or it could be an optimization issue upstream with the Icecast-KH fork that we use for broadcasting.

It would be important in this case to determine whether the CPU spike is just upon initial connection of new listeners or whether it's sustained across their listening time, which it absolutely shouldn't be as Icecast is quite well optimized for that purpose.

**Comment by RM-FM** [comment]
@alerickert We also did some load tests in the past, albeit not with that many connections. However, such a test should build up the connections in stages. E.g. 50 per second until the target connection number is reached.

**Comment by BusterNeece** [comment]
@alerickert It's not useful to us to just tell us that other panels (especially closed-source, commercial ones) do something better than we do. I would avoid trying to put us up against the "competition" when asking volunteers to work toward your issue for free.

If you can dig deeper and find some information (like via `htop`) to see what is actually consuming the excessive CPU in this case, then we can investigate further. But please don't just tell us that other panels do it better.

**Comment by Vaalyn** [comment]
@alerickert just to be sure, was this test directly connected to the IceCast port like this `https://<domain>:<port>` or to the listen URL that looks like this `https://<domain>/listen/<station>/<mount>.mp3`?

Also do you have any of these settings enabled on your installation?

<img width="1255" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/dc358eb4-a73f-4fd4-a847-d407c66c394a">

**Comment by Vaalyn** [comment]
🤔 @BusterNeece do we have any other connection between IceCast and the PHP processes apart from the access callback for the above mentioned settings?

I've checked this on my test server and the respective authentication config in IceCast that would do the callbacks for those are not being put into the IceCast config file when they are disabled so if those are not enabled in this case here there has to be some other part that is getting flooded by the IceCast listeners.

**Comment by BusterNeece** [comment]
@Vaalyn I don't think there's any other explanation on our end, this might very well be something going on with Icecast-KH itself.

**Comment by Moonbase59** [comment]
I’ve not been testing with 200,000 listeners, but 5,000 max. per station, and the icecasts never took more than a few % CPU. It _is_ known, though, that Icecast doesn’t like to connect/disconnect thousands of connections _at exactly the same time_. Testing scripts should take care of that. Mine uses a 0.1s delay between each connect, for example. Plus, of course you _have_ to have enough bandwidth!

I’m wondering why _all your three Icecasts refer to the exact same config file:_
```
/var/azuracast/stations/server_test/config/icecast.pid
```
In my setup, one Icecast per station runs, and refers to a per-station icecast config.
Could that be the problem?

![matthias@radio: ~_005](https://github.com/AzuraCast/AzuraCast/assets/3706922/4f606d4c-2ecd-457d-bbe7-e8f6e2e288fd)
(About 300 listeners at the time of screenshot)
