### ISSUE TITLE
Song history not showing

### ISSUE THREAD

**Issue by JustIrinel** [AzuraCast/AzuraCast#707]
**Installation method**
Docker
**Host OS (for Docker installations)**

Centos 7

**Describe the bug**

Song history doesen't show on public page http://radio.edmromania.ro/public/edm_romania

**To Reproduce**

Access public page and press song history button.

**Expected behavior**
I expect to see a list with all tracks played

**Screenshots**

-

**Desktop (please complete the following information):**

OS: Windows 10 x64
Browser : Any...

Thanks !

**Comment by SlvrEagle23** [comment]
@JustIrinel It appears this station isn't actually playing anything at the moment. At least AzuraCast's "Now Playing" data is showing no results. This could be due to:

 - An error in the Now Playing sync task (which you can check for by visiting the system's administration, then running the "now playing sync" at the bottom)
 - A misconfigured station mount point (i.e. one named "/listen.mp3") which uses a reserved URL that the radio software won't allow, or
 - Something preventing the station services from starting up entirely, which you can view from the station's profile page.

**Comment by SlvrEagle23** [comment]
@JustIrinel It looks like your station's up and running now, with history resolving properly. Let me know if you have any further issues!
