### ISSUE TITLE
Issue building the url for the <audio> tag on the public page.

### ISSUE THREAD

**Issue by poingg** [AzuraCast/AzuraCast#7075]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #1c290a9 (2024-04-28 19:21) • Docker • PHP 8.3

### Steps to reproduce:
 * Create new radio station
 * Add media and playlists using defaults where possible
 * The public page will use this url for the audio tag:

`<audio title="Whatever" src="//:9010/radio.mp3"></audio>`

If click the play button I get this error on the console of Chrome browser (latest Mac)
`Uncaught (in promise) DOMException: Failed to load because no supported source was found.`

### Workaround that I had to use:
  * Edit the mount point created and under the "Advanced" section, fill in the full mount point url
`http://myradiohost.local:9000/radio.mp3`

And now, on the public page, the audio tag src field shows
`<audio title="Whatever" src="http://myradiohost.local:9000/radio.mp3"></audio>`

And the play button works. Am I missing something? Oddly enough, If I add a second mount point (without filling the advanced section), the rendered public page shows the full URI for the second mount point.

**Comment by poingg** [comment]
### Update

I tracked the issue to the setting under "System Settings". The reported behaviour happens only when you turn on the option "Use High-Performance Now Playing Updates"

As soon as I unchecked it, everything works as expected.

**Comment by carlojou** [comment]
This bug I have seen even with that "High performance" setting off.  It has been happening for quite some time, probably since mid last year I started noticing it.

When that "High performance" option is enabled initially and you disable it, it does fix it. But if it happens again when it is now disabled theres no real way to fix it but to just to wait or restart AzuraCast entirely.

A quick fix on the audio element to just include the mountpoints URL regardless if its included in the advanced setting of the mountpoint could fix this entirely.
