### ISSUE TITLE
Uploading Welcome Message Broke Station

### ISSUE THREAD

**Issue by TrevorRoberts** [AzuraCast/AzuraCast#7080]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #996fe4e (2024-04-28 22:30)

### What happened?

Before I updated, I uploaded an MP3 to play when users connect and ever since then I just get static on the station. Also, Now Playing shows the audio that was playing  when I uploaded the file. I later deleted the file, but no change. I do a live broadcast and connect and it shows as the next song coming up.

**Comment by netbladenl** [comment]
Same problem, and also when I upload a custom fallback file the autoqueue breaks after a few hours.

**Comment by blindndangerous** [comment]
Same here after uploading media, liquidsoap just says it's shuffling from num songs and num playlists and won't start.

**Comment by BusterNeece** [comment]
It appears people are having this issue fairly often, but I'm not able to reproduce it at all on my end.

One thing I'd recommend doing is, if this is happening, using the "Restart Broadcasting" feature instead of "Reload Broadcasting" on the restart page. That will fully shut down and restart all radio services, and may be better suited for fixing issues like this.

Otherwise, I'd need to see logs to know what's causing this. I'd recommend looking at the Icecast logs to see if they're reporting any errors.
