### ISSUE TITLE
LetsEncrypt: ACME Error: Certificate does not need renewal

### ISSUE THREAD

**Issue by niall-ofiz** [AzuraCast/AzuraCast#7081]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.19.5

### What happened?

I'm getting email notifications that the LetsEncrypt cert is due to expire in 7 days. The message is correct and I can see that the certificate is due to expire in 7 days.

When I try to renew the cert in the dashboard, I get the message:

ACME Error: Certificate does not need renewal. {"exception":"[object] (RuntimeException(code: 0): Certificate does not need renewal. at /var/azuracast/www/src/Service/Acme.php:136)"

So the cert cannot be renewed via the dashboard and the auto-renew is not working.

The Azuracast installation is using default ports.

**Comment by BusterNeece** [comment]
Our threshold in the code is 30 days, so if it's still saying "doesn't need renewal" 7 days out, then there's definitely something up with that.

Unfortunately, the logs don't tell us much on this particular situation. I'm really not sure how to diagnose it further short of actually looking at the installation in question.

I'll look into making the Rolling Release version actually force registration when you do it via the Settings page, since otherwise there's basically no way to force a renewal of an SSL cert if it says it doesn't need renewal.

**Comment by BusterNeece** [comment]
@niall-ofiz After looking at your installation, I discovered that the issue was that the certificate _had_ renewed (so the message about not needing renewal was correct, as far as the Acme service was concerned), but that the renewed certificate hadn't applied to the public-facing nginx and icecast servers. Upon a reboot, they picked up the correct certificate.

This should be fixed as of the latest Rolling Release, and shouldn't be an issue in the future.

**Comment by inetactief** [comment]
I know it is fix..
But is there a way to reload the nginx for the webinterface and icecast ssl cert?
