### ISSUE TITLE
Twitter WebHook

### ISSUE THREAD

**Issue by Likeandfeel** [AzuraCast/AzuraCast#714]
Hi Team

Some issue regarding Twitter WebHook.
If we use this format 
#Now playing on @MySuperRadio : #{{ now_playing.song.title }} by #{{ now_playing.song.artist }}! Tune in now and enjoy sound of #Wonderfull_Music

We get only part of Title and Artist name as you can see

#Now playing on @MySuperRadio : **#So** Freakin' Tight by **#Tough** Love! Tune in now and enjoy sound of #Wonderfull_Music

Exist a way to get this expectative 

**#Now** playing on **@MySuperRadio** : ****#So** Freakin' Tight** by ****#Tough** Love**! Tune in now and enjoy sound of #Wonderfull_Music

Its mean to get in hashtag all the variable {{ now_playing.song.title }} and {{ now_playing.song.artist }}

**Installation method**
Traditionnal Install 

**Host OS (for Docker installations)**
Ubuntu 16.04

Thanks a lot

**Comment by SlvrEagle23** [comment]
@Likeandfeel This is just a property of how Twitter hashtags work. They only apply until the next whitespace detected, so if your song or artist names have whitespace, it'll break up the hashtag accordingly.

The variable replacement we use to send webhooks is meant to be quick and simple, since there can be any number of web hooks and they should all dispatch in a fairly short time. If we were to add things like whitespace removal or other string modification functions, this could significantly increase the processing time for the message variables, especially for webhooks like the Discord hook that have multiple variable-supported sections.

At the moment, I'd recommend sticking to known strings for your hashtags to avoid any issues like this.
