### ISSUE TITLE
Slim Application Error - Cannot access AzuraCast after web update

### ISSUE THREAD

**Issue by BornKillaz** [AzuraCast/AzuraCast#7154]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

AzuraCast • v0.19.5 Stable • Docker • PHP 8.3

### What happened?

I try to update to the new Stable versions, run web update. Gave me an error and now I cannot access Azuracast. 
I know I have backups, how can I access and restore from my daily Azuracast backups?

**Comment by BornKillaz** [comment]
I manage to restore a backup but I get this error:


 [ERROR] The command "mariadb-dump --user=$DB_USERNAME --password=$DB_PASSWORD --socket=$DB_SOCKET --add-drop-table
         --default-character-set=UTF8MB4 $DB_DATABASE > $DB_DEST" failed.

         Exit Code: 2(Misuse of shell builtins)

         Working directory: /var/azuracast/backups

         Output:
         ================


         Error Output:
         ================
         sh: 1: cannot create /var/azuracast/backups/pre_migration_db.sql: Permission denied
         
         How to solve this?

**Comment by ajeje989** [comment]
how to fix ? same error

**Comment by ChrisMuc** [comment]
This seems to be an issue caused by the permissions of the folders for the volume-mounts and the azuracast user (uid 1000), used inside of the container. You can kind of "solve" this issue by granting write permissions to everyone for the volume-mount directories; at least the folders used for volume mounts "/var/azuracast/backups" and "/var/lib/mysql". 
There are other options to solve this, like providing UID and/or GID of a local user. But this should give you a clue how to solve it.
