### ISSUE TITLE
No sound when playing songs or streams from the web dashboard

### ISSUE THREAD

**Issue by Kkspike** [AzuraCast/AzuraCast#7161]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

v0.20.0 Stable

### What happened?

Since the update to v0.20.0 Stable, we can't hear a sound when trying to play a Stream or a song directly from the Profile page (using the "play" triangle button on the left of any stream or any song. The button turns to the squared stop button (like something is playing), but no sound can be heard. The stop button turns to a play button after the lenght of the playback (if it's a file). In the upper right part of the interface, the playback tool pops up, where we can stop the playback and wiggle the sound level. Even at max level, no sound can be heard. The sound works great when listening to the stream from the Public page. 

This behavior is present on any number of browsers and devices we've tried. Windows, MacOS, iPad with Chrome, Firefox and Safari.

**Comment by poingg** [comment]
The new docker-compose.yml file is much smaller and has no references to ports 9000 and up like the one before
I edited the new docker-compose to include the 9000 and up ports as well as the environment references and it's working again. Some bad docker-compose is being distributed with the updates I guess

**Comment by poingg** [comment]
Thank you for the clarification. I simply ran the instructions as specified here https://www.azuracast.com/docs/getting-started/updates/

Shouldn't this `yes "" | ./docker.sh update` have taken care of that step?
Cheers.

**Comment by BusterNeece** [comment]
@poingg It would take care of that step in the sense of automatically answering "no" to "do you want to customize your installation", when if you're using custom ports you actually do. I'd recommend just going through the installer normally at least once to let it generate things correctly.

**Comment by poingg** [comment]
Thank you @Vaalyn for the clarification. I would suggest that the documentation on the update page should reflect the info you just gave me.
Cheers.

**Comment by Vaalyn** [comment]
The introduction of the installer/updater was such a long time ago that most users that have been running even conservatively recent version should be familiar with it existing since it explicitly asks for any customization needs on each update and directly editing the docker-compose.yml was always advised against. 

I'm not sure what exactly we could put on the update docs page to help users on old versions to notice the installer more.
(If you have any suggestions please let us know, I'm just unsure about what would help exactly which is also not too explicitly meant for a single specific use-case but broadly applies to all possible customizations that could be affected)

The section about automated updates already says that:
> By default, the updater will prompt you to update your docker-compose.yml file. If you aren’t making any changes to this file and want to automate the update process, you can use the command below to automatically answer “yes” to this question:

I mean, if you have made changes to the docker-compose.yml this should tell you that you probably want to not say "yes" here automatically but rather look at it at least once manually 😅 

And in the documentation for extending the stations port range the installer/updater is explicitly prominently mentioned: https://www.azuracast.com/docs/administration/docker/#using-non-standard-ports

<img width="1013" alt="image" src="https://github.com/AzuraCast/AzuraCast/assets/13745863/2ac6b2da-295a-4bdb-86dc-5230eeffd50b">
