### ISSUE TITLE
Autocue with high cpu consumption

### ISSUE THREAD

**Issue by roger-net** [AzuraCast/AzuraCast#7172]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.20.1

### What happened?

When enabling autocue leads to an exaggerated increase in cpu consumption, my question is? This is normal?

**Comment by BusterNeece** [comment]
@roger-net You'll see an initial CPU spike, especially after initially enabling AutoCue and when first starting up a station. This is because it has to analyze every possible "fallback" track it could play, which piles up a fairly large queue of things to analyze. However, this should rapidly stabilize to a lower CPU load. AutoCue does still take up more CPU than a standard radio station just because of its design.

**Comment by Moonbase59** [comment]
Yes, exactly.

See:
- [Initial Startup (presentation slide)](https://moonbase59.github.io/autocue/presentation/autocue.html#/initial-startup)
- [A few words of advice](https://github.com/AzuraCast/AzuraCast/discussions/7168#discussioncomment-9673575)
- https://github.com/AzuraCast/AzuraCast/issues/7174#issuecomment-2149208437

So, in short: Yes normal, especially after a station restart, but it will return to normal after a few minutes. Complex analysis can’t be had for free…

_But_ you can _pre-tag_ your files, and CPU usage will almost be nil, since Autocue can than simply read tags and skip the CPU-intensive calculations.

**Comment by t0mtaylor** [comment]
@roger-net @Moonbase59  @BusterNeece this is related to my ticket i raised today:

https://github.com/AzuraCast/AzuraCast/issues/7185

Surley Azuracast should have this info stored in the DB, or constantly updated in another `emergency/recovery` table, which could be used as a `turbo mode` upon a restart/startup of the Azuracast docker container?

That way, the immediate CPU spike and lag which slows down the starting of the station stream (which should always be the highest priority before anything else) should then dissapear and no longer be an issue

In ticket 7185 i propose a `turbo mode` option, but It would require more work due to the current limitation with autocue
