### ISSUE TITLE
CPU usage spike caused by liquidsoap(?)

### ISSUE THREAD

**Issue by KristofferHjortland** [AzuraCast/AzuraCast#7173]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.20.1

### What happened?

I've been having this issue for a while where my stations will pause or hiccup at random intervals. I've been looking for answers both here and over at liquidsoap, but I can't seem to find a solution or even a reason for why this is happening. When googling the "We must catchup x.xx seconds!" errors from my liquidsoap log I keep seeing others with similar issues but no answers other than "Your CPU is overloaded" etc.. I've seen others running a far greater number of stations on lesser hardware, so there must be a bug in my installation somewhere right? 

I can obviously see the spikes in CPU usage in the Azura dashboard:
[spike](https://github.com/AzuraCast/AzuraCast/assets/81263371/8c67ba3f-32df-4445-ae83-1c408865febf)
[normal](https://github.com/AzuraCast/AzuraCast/assets/81263371/6670575c-27bd-4979-b341-7833a4b9977e)

And when I checked with _top_ it seems liquidsoap is the culprit. 
![top screenshot](https://github.com/AzuraCast/AzuraCast/assets/81263371/49ca60f5-3dc8-4a0a-b843-9980f247f798)

I just updated to the latest release (0.20.1) but these issues have been persistent since 0.15 or 0.16 if my memory is correct. I also had the issue where I couldn't update from the web interface that I managed to fix following [this](https://github.com/AzuraCast/AzuraCast/issues/6218) thread, but the issue seems to have made a comeback as I now had to do the latest update via the CLI once again.

Below are gists of the liquidsoap log and config for 1 of 4 currently running stations. I really hope we can find a solution for this issue. Let me know if you need anything else from me in order for us to figure this out. 

### Relevant log output

Log:
https://gist.github.com/KristofferHjortland/caec7542a730760975e06cfffb06193e

Config:
https://gist.github.com/KristofferHjortland/259545e0e471ee4a0ea3bc641b682390

---

Edit: I wanted to add that I have tried tweaking post-processing, queue length, performance tuning etc, and none of that seem to have an effect on the spikes.

**Comment by rfigueroa9** [comment]
Estoy presentando el mismo problema. Actualicé a la versión más reciente y el problema persiste. Por favor pronta solución a este inconveniente.

**Comment by gAlleb** [comment]
@rfigueroa9, no todos saben espanol. Al final, esto es solo una falta de respeto a la comunidad. Por favor escriba en ingles, traduzca a traves de un servicio de traduccion o duplique el texto en ingles.

Not everyone knows Spanish. In the end, this is just disrespectful to the community. Please write in English, translate through a translation service or duplicate the text in English.

Thank you.

**Comment by rfigueroa9** [comment]
I am presenting the same problem. I updated to the latest version and the problem persists. Please provide a prompt solution to this problem.

**Comment by PeWe79** [comment]
Same problem here. After update last version (Rolling Release) with 8 CPU report Steal 2.4% of CPU/Core, so station several time is goes down!.

**Comment by PeWe79** [comment]
I think after last update release (https://github.com/AzuraCast/AzuraCast/commit/117f4cb92bbe9d4dcadde3a9bca01efbd7344a19) high CPU consumption was solved. Tks.

**Comment by asa767** [comment]
Same issue. Updated to #b1e3b0e nothing changed.

**Comment by asa767** [comment]
I am running 18 stations on 6cpu 16gb vps. I've disabled "Always Write Playlists to Liquidsoap" for all my stations but cpu usage is still very high. 5 min avarage is 7 on a 6 Cpu vps. Before it was 4 with all stations enabled. Now this score is for only 8 stations.

**Comment by asa767** [comment]
> I am running 18 stations on 6cpu 16gb vps. I've disabled "Always Write Playlists to Liquidsoap" for all my stations but cpu usage is still very high. 5 min avarage is 7 on a 6 Cpu vps. Before it was 4 with all stations enabled. Now this score is for only 8 stations. 

I cloned my server from Contabo to Digital Ocean and performance issues had gone. Now 18 stations are working on 4 core vps at about 4.3 load.

**Comment by Kristoffer123456** [comment]
> > I am running 18 stations on 6cpu 16gb vps. I've disabled "Always Write Playlists to Liquidsoap" for all my stations but cpu usage is still very high. 5 min avarage is 7 on a 6 Cpu vps. Before it was 4 with all stations enabled. Now this score is for only 8 stations.
> 
> I cloned my server from Contabo to Digital Ocean and performance issues had gone. Now 18 stations are working on 4 core vps at about 4.3 load.

I'm running mine on a 4 core vps with 8 gigs of ram on Digital Ocean as well, but it's struggling..

**Comment by andyshephard** [comment]
I figured I'd post here rather than creating a new post as it's CPU & RAM related. I'm running my AzuraCast instance on a Digital Ocean basic droplet, which is 1 virtual CPU, 2GB RAM, 50GB HDD and 2TB transfer.

My graphs show the CPU & RAM running at ~90% consistently when idle (zero streams), and when performing load testing just now, I managed just over 100 streams running at 192kbps before the CPU & RAM max out.

I was originally thinking that there might well be a config and/or software problem, but after seeing this thread I'm not so sure.

In your opinions, if I'm running 4 radio stations, each with 3 mount points (32kbps, 96kbps, 192kbps), should I be expecting a lower CPU/RAM rate than 90% idle?

<img width="993" alt="Screenshot 2024-07-10 at 10 07 36" src="https://github.com/AzuraCast/AzuraCast/assets/3307650/c057ac61-eceb-44b2-91af-a68450451452">
<img width="921" alt="Screenshot 2024-07-10 at 10 09 33" src="https://github.com/AzuraCast/AzuraCast/assets/3307650/e0f90223-50b5-46d4-b42d-39fb90c29924">

Thanks

**Comment by Vaalyn** [comment]
If you are on a shared cpu plan on DO they might be throttling your cpu due to the constant load that audio transcoding causes.

Regarding the RAM, please check via `htop` or in the admin of AzuraCast if DO might be showing RAM that's actually just cached as used. Lot's of management panels do this although it's very unintuitive.

**Comment by Vaalyn** [comment]
The audio transcoding cpu usage on that screenshot looks quite normal to me. Depending on the format/s used on a station this can vary from ~10-30% of a core (some formats are much harder on the cpu than others). My stations average around 20-22%, with spikes to 40-50% due to things like AutoCue and MasterMe processing.

Generally we recommend running AzuraCast on a machine with 4 cores and 4GB RAM and the bare minimum should be 2 cores and 2GB (maybe with SWAP to prevent OOM errors, although swap can then also cause CPU load to increase if swap must be used due to IO wait time).

If I sum up an average cpu usage of the stations of your installation assuming ~17% load per station that would be 4*17 = 68% average usage from the stations, which I'd more likely bump up to an assumed 80% due to fluctuations. Add to that the 10-20% of the PHP processes (maybe more depending on which sync tasks are currently running) as well as the database, icecast (mabye redis)...

Listeners themself don't really cause any noticeable CPU usage increase with Icecast (see their benchmark https://icecast.org/loadtest/1/ for example) so that doesn't factor in here when we talk about the resource usage in most cases as that only becomes relevant with thousands of listeners.

Your machine is simply underpowered for what you ask of it.

When I plan servers for AzuraCast I calculate with a max. of 3 stations per core and never go below 2 cores on a machine simply because multi-tasking on a single core is very much not ideal, especially for something with constant load like audio transcoding 😅

**Comment by andyshephard** [comment]
Yeah, I was thinking it'd likely be an underpowered server but wanted to make absolutely sure before ramping up the resources. Did a test of restarting the droplet and saw the graphs drop for a while before returning towards the 90% CPU mark & 85% RAM mark.

Thanks for the help on this, and lastly, thanks for making an excellent product!

**Comment by Kristoffer123456** [comment]
> EDIT: Just as a brief update, I've spun up a VPS on Hetzner (2 vCPU, 4GB RAM) for €4/month and with the same setup (4 stations, 12 mount points total) it's near to 50% on both CPU and RAM. I'll be monitoring the graphs during the next couple of days to ensure there's no dropouts but this could be a great alternative to DigiOcean.

I too ended up moving to Hetzner on a VPS with dedicated CPU resources and it seems to have fixed my issues, will update original post if I can.
