### ISSUE TITLE
AzuraCast 0.20.1 Update Issues: ReplayGain and AutoCue Problems

### ISSUE THREAD

**Issue by BornKillaz** [AzuraCast/AzuraCast#7175]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

AzuraCast • v0.20.1 Stable • Docker • PHP 8.3

### What happened?

Ok, so today I update Azuracast to versions 0.20.1... What a disaster!

I come across similar issues I encountered on the previous update, my station haven't start, it just keep playing the fallback mp3 file. 

After a few restarts, including Liquidsoap reload, full station restart and docker restart I was able to put the station online again but only by disabling ReplayGain in the Auto DJ tab.

Then I went to activate autocue, added my settings (bellow) to liquidsoap, disabled ReplayGain and reload / restart / did everything again, with no luck the station kept offline.

```
settings.autocue.cue_file.noclip := true 
settings.autocue.cue_file.write_tags := true
settings.autocue.cue_file.target := -17.0
```

So the only way I could get my station stream back again, was to disable ReplayGain, then reload and it worked, at least it produced some sound from playlists....

So this latest version it a totally disaster for me, at first caused by ReplayGain as far as I could figure it. Now I have the station running without ReplayGain, nor autocue. And on top of that,  my playlist is constantly failing and falling back to the default playlist, and suddenly back to the correct playlist... What a mess...

### Relevant log output

```shell
https://pastebin.com/VfyQfCXR
```

**Comment by BornKillaz** [comment]
On top of the described above, even when I have Smart Mode active and autocue disabled, Most of the times I get no transition at all:
2024/06/04 23:18:33 [cross.smart:3] No transition: using default.

I'm going back to previous version v20.0. Hopefully I can download with an existent backup.

**Comment by BusterNeece** [comment]
This isn't a very good GitHub issue report. It's not very helpful to us to just say "this update was a disaster!" and other "the old version was better" type sentiments.

If you enabled AutoCue for the first time in 0.20.1 and that caused problems, then it's possible that it was the _enabling of AutoCue_ that caused the problems, not the actual 0.20.1 update itself, which not only doesn't require that you use AutoCue but doesn't enable it by default.

Replaygain is also known to cause issues with high CPU load. With both Replaygain and AutoCue, you'll see an initial CPU spike as the station is first restarting and getting started; this should settle down to a much more consistent load once the station's operational. We're working on ways to improve this, in particular by writing a lot of that data back to the files as we determine it.

In order for us to be able to help resolve this, we'd need a lot more information about how your station is set up, what your resource situation looks like and what the bottleneck is, and what logs are being produced by Liquidsoap, etc. with those features turned on.

There are more bug fixes and further improvements to be had on the Rolling Release, but honestly I really don't want more people on the Rolling Release who aren't going to be patient and thorough in their issue reporting.

You may be able to use `./docker.sh rollback 0.20.0` to actually roll back to that version if it's absolutely necessary.

**Comment by BornKillaz** [comment]
Sorry Buster, please don't misinterpret my words, it's was a disaster **on my side** and got me some headaches. So, I'm not saying that version 20.1 itself is a disaster, as it's working perfectly fine for others as far as I know. 

I truly appreciate all your hard work on AzuraCast and I'm thankful that it exists. And I'm also more than happy to provide more valuable information on these issues. Tomorrow I will try to activate Replay Gain again and will como back with some more logs and details.

Thank you and sorry for any misunderstood.

**Comment by Moonbase59** [comment]
Sorry you ran into problems. I should have mentioned that Liquidsoap’s ReplayGain feature (which AzuraCast _can_ use) eats lots of CPU and **_should be disabled when using Autocue_**, because Autocue provides exactly the same ReplayGain values LS would calculate. So that would be an unnecessary double calculation.

Hint: If you really want to use
```
settings.autocue.cue_file.write_tags := true
```
for getting the tags stored into your files, let me make a suggestion: As talked about [here](https://github.com/AzuraCast/AzuraCast/discussions/7168#discussioncomment-9673575), it’s maybe not the best idea to store ReplayGain data for anything else than a  **-18 LUFS** target loudness.

But you still want that data saved, right? _Plus_ broadcast at a -17 LUFS target, right?

A wild suggestion for that use case:
- Use -18 LUFS and store _both_ Autocue and ReplayGain tags. Saved files will have a loudness reference of -18 LUFS, all good.
- "Fake" playout at -17 LUFS by later adjusting Liquidsoap’s `amplify`.
- **Best of both worlds!**

So how do we do it?

Autocue settings (2nd input box):

```
settings.autocue.cue_file.noclip := true 
settings.autocue.cue_file.write_tags := true
settings.autocue.cue_file.write_replaygain := true  # add RG (track) tags
# settings.autocue.cue_file.target := -17.0  # comment out, default is -18
```

"Fake" -17 LUFS (3rd input box):

```
# "Fake" -17 LUFS playout
# +1 dB amplification from the default -18 LUFS → -17 LUFS
radio = amplify(lin_of_dB(1.0), override=null(), radio)
```

**Best of both worlds!** Files tagged at -18 LUFS, playout at -17 LUFS. :-)

**Comment by gAlleb** [comment]
Oh, that's nice -> `radio = amplify(lin_of_dB(1.0), override=null(), radio)`

_writing down..._

:-)

**Comment by Moonbase59** [comment]
Just don’t forget to null the override string, otherwise awful loudness things will happen! (Because it’ll use `liq_amplify` _twice_, resulting in very low volume.)

**Comment by Moonbase59** [comment]
@gunsar Should I now say _Autocue doesn’t support the Loudness Wars_? Just kidding…

If using _master_me_, it comes into the playout chain at the end (or should), so you could safely leave autocue running at the **-18 LUFS** target it has set as default, because you would set the final loudness in _master_me_.

If _not_ using any post-processing, you can just use something like
```
settings.autocue.cue_file.target := -14.0  # not recommended
```

The Autocue settings go in the _second_ input box of AzuraCast’s Liquidsoap Configuration Editor.

**Comment by BusterNeece** [comment]
@BornKillaz Are you in a working state with your installation at this point?

If you didn't see it, you may want to follow @Moonbase59's advice on the discussion (#7168) of checking to make sure you don't have any residual AutoCue stuff from back when it required manual work to add to AzuraCast. Those will override our "official" AutoCue binaries with older, outdated ones and will cause problems.

**Comment by BusterNeece** [comment]
Also, you mentioned that ReplayGain also isn't working with your installation as of 0.20.1, but it _was_ working with 0.20.0, but we didn't actually change anything relating to ReplayGain between those two versions.

I'd want to make sure you're not confusing the initial post-restart CPU load (which is inevitable if you don't have this metadata written and saved to every file already) as a failure of the system to operate entirely and giving up on it and switching settings before it's had a chance to "settle in" to normal operating values.

**Comment by BornKillaz** [comment]
@BusterNeece , unfortunately no, my station is not working properly. already reply in that [topic](https://github.com/AzuraCast/AzuraCast/discussions/7168#discussioncomment-9681585)

Situation is, AutoCue does not work for me, the old ReplayGain doesn't work (station does not come online) and Smart Crossfade also stopped working.

I'm on Debian, latest version, and AzuraCast Stable version 20.1, Docker install. 

Thank you for your concern.

**Comment by BusterNeece** [comment]
@BornKillaz If you're willing to e-mail me with info on your station to investigate, I'd take a look at it, but otherwise I don't think we have really enough information to know what's causing these issues for your specific station. I want to help, but I don't have anything to go off right now.

**Comment by BornKillaz** [comment]
> Also, you mentioned that ReplayGain also isn't working with your installation as of 0.20.1, but it _was_ working with 0.20.0, but we didn't actually change anything relating to ReplayGain between those two versions.
> 
> I'd want to make sure you're not confusing the initial post-restart CPU load (which is inevitable if you don't have this metadata written and saved to every file already) as a failure of the system to operate entirely and giving up on it and switching settings before it's had a chance to "settle in" to normal operating values.

@BusterNeece, no in my tests I waited a good time for AutoCue do it's job. I saw the CPU increase, but no stress, I know this is normal.

And yes, I'm referring to the old ReplyGain, not the one recently added into AutoCue to write those tags.

So basically, with AutoCue off, the ReplayGain  should behave as before and work as it worked for the last months. But not a chance. Station just stays on that fallback file and after a while the white noise kicks in.

And I can figure out that must be strange if you did not do any change to the original ReplayGain.. But for the crossfade you do something, becouse when autocue is on, crossfade options are deactivated... And my Smart Crossfade also stopped working, so, can the crossfade thing be somehow related or be the cause for my issues?

Thank you.

**Comment by BornKillaz** [comment]
> @BornKillaz If you're willing to e-mail me with info on your station to investigate, I'd take a look at it, but otherwise I don't think we have really enough information to know what's causing these issues for your specific station. I want to help, but I don't have anything to go off right now.

Sent. Thank you.

**Comment by Moonbase59** [comment]
I’ve never actually been on any of the stable releases, I used the Rolling from the start and just upgraded through all these version for many month. Turned out this always worked (only _very_ minor glitches), and no problems with autocue. Never used the builtin Replaygain though.

I’m on Rolling Release #[4cc26c5](https://github.com/AzuraCast/AzuraCast/commit/4cc26c544ce6a59f19d196a262962eb3bc98de42) (2024-06-04 20:10) currently.

**Comment by BusterNeece** [comment]
After looking into @BornKillaz's installation, I can confirm that both AutoCue and ReplayGain are causing CPU spikes on their installation significant enough to actually knock out broadcasting, from which it seems very difficult for Liquidsoap to recover, for some reason.

I suspect the causative factor is a combination of multiple large playlists (since each playlist has to load at least one file from it on the initial startup, each new playlist represents a linear addition to the upfront CPU load, and the total just topples the system) and larger files (i.e. full hour-long sets) that task either AutoCue or ReplayGain quite hard.

I can verify in the code that, between 0.20.0 and 0.20.1, we did not update Liquidsoap, nor did we change any of the non-AutoCue code that we generate. If this was all working as intended in 0.20.0, it may have been that the station wasn't set up fully at that point or was otherwise configured differently.

For installations that meet this characteristic (many playlists of large files), then pre-running `cue_file` on the tracks is highly recommended. In the future, AzuraCast will have a facility to do this directly inside the app, but right now we don't currently have that.

As for the Smart crossfade not fading correctly...I also observed something like that, but I'm also not sure why that's the case.

**Comment by BornKillaz** [comment]
@BusterNeece, now that you mention you did not do any changes to ReplayGain recently, it come to my mind that before updating to version 20.1 one or two times I've noticed that there was sometimes some slight changes on the stream volume, but I didn't take that into account. The function was active on the panel, so I haven't detected any more issues. 

Also, I have a bad experience upgrading to version 20.0, when the station totally stopped working. I couldn't even access the web panel. At that time I had to recover from the last azuracast backup. I know that the problem was related to an error that occurred on the Maria database.

Also another problema I've experienced since   the latest version 19 is that scheduled playlists never kicks in on time. Most of the times, it plays two more songs from the previous playlist before changing into the new playlist. This happens on those playlists that have on it 1 hour pre recorded shows, which I of course assume that's related to the size of such files and the server and Liquidsoap struggle to process them.

For the Smart Crossfade, I only notice it was not properly working since version 20.1.

I'm glad that you could finally witness  these issues by yourself and I hope that these can get solved so also others won't run into similar troubles.

Thank you very much.

**Comment by BusterNeece** [comment]
@BornKillaz Please try to avoid just piling issue reports on us in one big issue like that. It's impossible for us to keep track of every one of the issues you reported with a single "done/not done" status for this issue.

As I mentioned in my reply...I'm not confident that there *is* a solution for your issues within the context of regular AzuraCast operation. ReplayGain and AutoCue will both take excessive CPU for you because of your large number of playlists and large size of files. This may always be a problem when initially starting up your station and for a few minutes afterward; if you pre-process your media, it will resolve this issue.

I feel like this has probably been explained in about ten different ways at this point, so I won't belabor the point any further. Suffice it to say, this isn't really something AzuraCast itself is doing *wrong* per se.

**Comment by BornKillaz** [comment]
Just a small update on this issue... read on and find out why I endorse it as a small update. 

I have just updated to the Rolling Release (I was on Stable 20.1), and station is now working perfectly fine. I now have the Smart Crossfade working as it was before (it was not working anymore on the Stable version). 

Also, this is amazing: the station starts right away after restart or reload, no waiting time whatsoever... This didn't happen to me in a long time. It doesn't even fall back to the fallback audio, and I found that absolutely fantastic. 

But... I haven't yet tested the new autocue nor turned on the Replay Gain on this Rolling Release version, I'm just happy for the fact that the station is now working as before and that's the reason I call this post a small update.

Yes, I do plan to of course, to test the autocue feature, but for now I'm just enjoying the fact that this station become usable again. 

I will come back after I test the autocue, but by  experiencing the performance improvement at this point, I'm convinced that it will work out of the box. 

Thank you guys for your efforts and all the time you put to fix this one and other similar reported issues.

**Comment by BornKillaz** [comment]
Hi!

As promised, here is an update on this situation....

So, I was able to get AutoCue to work on my station. 

Just adding ReplayGain to all tracks was not enough as I always get stuck on station startup with AutoCue timeouts on my DJ's/hosts  pre-recorded shows. 

**The solution**: As suggested, just parse your bigger files with [cue_file](https://github.com/Moonbase59/autocue) before add them to the station. Also turn off the function "Always Write Playlists to Liquidsoap" in AzuraCast.

This is the command I currently use: 
`$ cue_file MyBigFile.mp3  -f -r -w -b 10.0`

I force the analysis, write the tags, add ReplayGain (track only), and skip silences over 10 seconds.

With these changes, my station started in a blink of an eye and the transitions sound amazing!

Thank you!

**Comment by Moonbase59** [comment]
@BornKillaz Wonderful! Happy we could get you up & running! Enjoy!
