### ISSUE TITLE
ShoutCast "Now Playing" Problem

### ISSUE THREAD

**Issue by djmuratb** [AzuraCast/AzuraCast#718]
Traditional Installation
Ubuntu 18.04.1 LTS
Installation Time: Today

**Describe the bug**
ShoutCast does not seem to be playing songs and past songs on the station.
http://test.alltimeworldhits.live/public/test2_shoutcast

![test1](https://user-images.githubusercontent.com/25807005/44104745-4f099f26-9ff8-11e8-94f1-d3e74abf9774.png)
![test2](https://user-images.githubusercontent.com/25807005/44104751-52b81a08-9ff8-11e8-9544-da695e18fb75.png)

You can see the error by logging in.
http://test.alltimeworldhits.live/login
User Login: test@alltimeworldhits.live / Pass: test1234

**Comment by SlvrEagle23** [comment]
@djmuratb The test account you set up doesn't have mount point configuration permissions, but it's possible that this is caused by your default mount point having an empty path ("/"), instead of something like "/radio.mp3" that would distinctly identify it.

**Comment by djmuratb** [comment]
I set permissions for the test account. You can log in.

**Comment by djmuratb** [comment]
Statistics do not appear in the report section. I think it is related to this problem.

**Comment by SlvrEagle23** [comment]
@djmuratb Something is wrong with your ShoutCast configuration; it's not writing the configuration correctly to shoutcast, so the mount point names don't match and thus it isn't aware of anything that's playing.

Are you on Docker or Traditional? You may need to e-mail me details to look into the server itself.

**Comment by djmuratb** [comment]
@SlvrEagle23 I experienced this problem on the server I had set up before. So I did a clean, a traditional install. But I had the same problem again and decided to write here.

I will send you an email for server information.

**Comment by SlvrEagle23** [comment]
@djmuratb Update on the research yielded by looking into this:

Shoutcast will automatically ignore any mount point names that contain "reserved" paths, which correspond to the paths that Shoutcast itself uses (`/admin`, `/listen.pls`, `/7.html`, `/statistics`, etc) and will instead just ignore the stream path entirely. Unfortunately, AzuraCast depends on Shoutcast _not_ ignoring the stream path in order to match up the default mount point in its system with the one returned in Shoutcast's data.

I've updated the Shoutcast mount point editor to automatically check for the most popular "reserved" paths; it will now fail to validate those names and will only allow names that don't contain them.
