### ISSUE TITLE
Listener numbers double

### ISSUE THREAD

**Issue by HitMaxi** [AzuraCast/AzuraCast#7181]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

Hello, I have a question and I hope you can answer it for me.

Why in my Azuracast, the listeners are counted twice at 2 mounting points in every program....

With a hanging point, I have the local server at a mounting point, I have stored a streaming URL under advanced settings....

So e.g. Stream 1. 2 listener. Stream 2 2 listener

= 4 listener but only 1 program 2 attachment points

**Comment by HitMaxi** [comment]
??

**Comment by BusterNeece** [comment]
Hey, so what you're doing here isn't really okay, just so you know.

I got *four* e-mails from you about this issue in quick succession, and now you're posting for updates even though the issue's only been open for two days.

Do you think that because we make a piece of software that we give away *for free*, that we owe you a 24-hour turnaround on every issue reported?

It seems like a lot of people do. Please don't.

**Comment by HitMaxi** [comment]
Sorry, I didn't mean anything bad, I'm just desperate why it doesn't work..

**Comment by bombelman** [comment]
I see this happening as well. 
What I do know is that the Dashboard shows the the total connections to your mountpoint, not from the perspective of a unique ip.
For example, I know some players pull 1 stream for the audio and another for the metadata.
This then shows up as 2 connections in Shoutcast DNAS, but 1 unique connection.
(not just in AzuraCast)
This could differ with player or website script source.
Try different players and see if this is the case.

A possible solution would be to have AzuraCast list only the unique connections instead of the total connections.

![Screenshot 2024-06-12 at 9 42 58 AM](https://github.com/AzuraCast/AzuraCast/assets/107536852/964dfa38-05b9-43ad-8cea-ed701f50cf6d)
