### ISSUE TITLE
MediaSession control does not support playing/resuming, only pausing

### ISSUE THREAD

**Issue by iflossahedron** [AzuraCast/AzuraCast#7228]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### Current AzuraCast Version

0.20.1

### What happened?

Many platforms use the [mediasession api](https://developer.mozilla.org/en-US/docs/Web/API/MediaSession) to give users control of whatever media is currently playing, so e.g. in firefox you can play/pause/skip from the gnome notification or in android you can play/pause/skip from the lockscreen. 
This support appears to only be [half-implemented](https://github.com/AzuraCast/AzuraCast/blob/35eca3778888fe853296ebd763b9824136b6e919/frontend/components/Common/AudioPlayer.vue#L188) in azuracast -- you can pause a stream but can't play it.

This creates an inconvenient and confusing user experience. For example, while listening with earbuds via my phone, I can pause the stream with my earbuds' play/pause toggle, but pressing it again does not resume playback as I'd expect. Instead I need to pull out my phone, unlock the lock screen (the "play" widget also does not work), navigate to the playing window, and press "play". 

Is this the intended functionality? Is there a rationale for half-supporting the mediasession api?
If not I'm open to contributing a fix upstream. 

Thank you for your hard work, I'm quite happy with azuracast <3

**Comment by Vaalyn** [comment]
🤔 I don't think there is a reason for it to not be there apart from it just not having been added yet. I do remember noticing that a few times but never got around to writing it down in a GH issue.

If you could send in a PR to add those event handlers that would awesome 😄

**Comment by Moonbase59** [comment]
It is already supported if you use my [AzuraCast HPNP (High-Performance Now Playing) example for station websites](https://gist.github.com/Moonbase59/d42f411e10aff6dc58694699010307aa?permalink_comment_id=4786603#gistcomment-4786603).

You could pick up the (little) code from there.

https://github.com/AzuraCast/AzuraCast/assets/3706922/12864aa8-0160-463b-bdb9-0a5ca10dcded

**Comment by Moonbase59** [comment]
The problem with mediaSession (and audio elements) is that you typically only get mediaSession controls _while it’s running_. That’s also the reason why the HTML `<audio>` _shows_ Play & Stop, but Stop typically only _pauses_ while the browser continues to consume the stream in the background, eating up memory until eventually the browser crashes.

A bad design, they probably never anticipated streaming audio, just files being played. With _streams_, you typically _don’t_ want to pause (and keep all the missed parts of the stream in memory), but _stop_ the stream and _reconnect_ to hear what’s _currently_ playing on a radio station.

That may well be the reason the AzuraCast devs implemented Pause actually being a Stop, and I’m also considering that. The unfortunate end of that of course is that the mediaControls will vanish, since nothing "is playing".

Pros and Cons… as always.
