### ISSUE TITLE
HSTS max-age is (possibly) too short

### ISSUE THREAD

**Issue by Sella-GH** [AzuraCast/AzuraCast#7238]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#f70c987 (2024-06-23 18:50)

### What happened?

According to scan results on [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=demo.azuracast.com&hideResults=on&latest) (just click on one of the results) the current max-age setting of HSTS (3600) is too short (less than 180 days) and does not meet the recommended age of 31536000 (1 year).
If using the preload option (currently not enabled), the [recommended age](https://hstspreload.org) is even longer with 63072000 (2 years).

I'd recommend to increase this to at least 180 days but I'm not sure if everyone agrees with that.

**Comment by Moonbase59** [comment]
Good you remind us of checking our servers from time to time. SSL Labs are one of the good tests.

Got "Grade A", and also

```
Strict Transport Security (HSTS) 	Yes   TOO SHORT (less than 180 days)
max-age=3600
```

Considering what a pain HSTS _removal_ can be, and being on a rolling release, I personally don’t see a reason to follow Google’s dictatorship in this case. Maybe for the stable releases…

**Comment by BusterNeece** [comment]
Yeah, the purpose of HSTS for us isn't necessarily to have such long durations that we wind up on official browser preload lists. HSTS is a constant tradeoff between the increased security it offers and the total disaster it represents if no browser can access your installation and you're having a problem with, let's say, renewing your LetsEncrypt certificates. No doubt, if we set the HSTS limit longer than it is, we'd have people filling up our GitHub issues saying that they can't turn it off.

My only purpose for providing the HSTS header is just so that repeat visits by the same users will be forced into HTTPS mode by default even if users don't type the HTTPS URL, so it'll let them spend more time in a secure environment by default.
