### ISSUE TITLE
station either hisses or plays the azuracast loop.

### ISSUE THREAD

**Issue by stickbear2015** [AzuraCast/AzuraCast#7262]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

 • v0.20.1 Stable • Docker • PHP 8.3

### What happened?

I'm copying my other station administrator, @blindman75 so he sees this as we're both working on this together.
after upgrading the core VPS OS, from debian 12.5 to debian 12.6, and upgrading azuracast to the latest stable release, from 0.20.0 to 0.20.1 without any issues, I reboot, and I either get a hissing sound, or the azuracast fallback loop.
I restarted both liquidsoap and icecast via their appropriate restart buttons, and sometimes it plays one thing then goes back to hissing or the azuracast loop. Broadcasters can't connect either, (well they connect, but azuracast doesn't shuttle listeners accordingly.)
Note: The second station on the exact same VPS, exact same azuracast install (the stations test station for broadcasters to use as a test point to test their live stuff before going live) performs properly, no issues, broadcasters can connect, and disconnect appropriate and the proper auto loop plays as configured without issues.
note: I tried restoring the database and re-running the /var/azuracast/docker.sh update-self && /var/azuracast/docker.sh update commands just to make sure a migration didn't hit the floor with know significant changes.
Both of us have done everything we can think of, short of the sledge hammer approach of ripping the entire thing out and re-installing it, and restoring the database from an automatic backup, and we'd like to avoid that, if we can.
Thanks for any help.
[azuracast.log](https://github.com/user-attachments/files/16043465/azuracast.log)

### Relevant log output

```shell
see attached file.
```

**Comment by stickbear2015** [comment]
note: I'm available via discord, and if necessary can provide access to a developer or system administrator to the web interface and the backend shell of the VPS in question if necessary.

**Comment by Moonbase59** [comment]
Have you checked there is at least one playlist that contains playable tracks?
Your logs say that nothing playable was found.

**Comment by stickbear2015** [comment]
@Moonbase59  their are 54000 some odd tracks and 21 playlists so says the proper place in the station profile. This is accurate. I checked playlists, etc. and things, look fine and configured, 0 things have changed except upgrading the underlying OS of the VPS, and of course the stable release to 0.20.2. Again, as I mentioned in my initial response here, the other station on the EXACT same VPS, on the exact same azuracast instance is just fine, no issues at all. I did see 400 errors cropping up through the log file I attached if that's any help.

**Comment by Moonbase59** [comment]
That’s odd. I’ve only ever seen such effects
- when no playlists with playable tracks available,
- when permission or network problems won’t allow accessing tracks,
- after cloning stations (with much older rolling releases, it might work now).

Sorry not to be more helpful.

**Comment by stickbear2015** [comment]
and I forgot to note, that the errors about no playable tracks are in relation to the test station, but that station (number 2) is working just fine. It's just looping through a fallback file that I replaced on that station.

**Comment by stickbear2015** [comment]
so, just because I could, I ran 
cd /var/azuracast
./docker.sh cli azuracast:media:reprocess
once that completed, I restarted both auto DJ and broadcasting service on station 1 (the effected station), it played a song, then went back to the azuracast loop for a few cycles, then went back to hissing.

I checked the second station on that instance, and it's working fine, it's working as expected.
So this seems to only be station 1, on this azuracast instance.
What other logs can I provide to help troubleshoot this very strange issue?

**Comment by stickbear2015** [comment]
So as a test,I restarted liquidsoap again, but it simply refused  to even play a single song. When I got it to play the fallback azuracast loop I tried to connect to 8005 to stream, I'm connected, said my software but liquidsoap never, or whatever handles this, never shuffled things over to my stream.
So as another test, I pressed stop on the liquidsoap auto DJ for that station, and reconfigured my software to connect directly to 8000 on mount /radio.mp3 and what do you know, it worked without an issue, so I suspect an issue with liquidsoap, but I have no clue what.
[liquidsoap.log](https://github.com/user-attachments/files/16045938/liquidsoap.log)
I'm attaching liquidsoap.log from that specific station to this comment.

**Comment by Moonbase59** [comment]
From the last log, it looks like your files might be large, and not pre-tagged, and you have Autocue enabled.

If you have not disabled _Always Write Playlists to Liquidsoap_, poor Autocue will have to analyze _two files per existing playlist_ on startup, which can take large amounts of CPU and willtake some time (on my system, with 4 stations, 4 CPUs, 4 GB RAM, 160,000 songs and ~70 playlists/station, this takes about 5–8 minutes until CPU load goes down again). Liquidsoap does this in order to always have the next file available for _immediate playout_
in case of errors, switches or fallbacks.

![Auswahl_459](https://github.com/AzuraCast/AzuraCast/assets/3706922/f4846192-888f-4a23-bbd8-bc36659ba315)

We consider this not being a show-stopper, since radio stations typically run over months or even years without being restarted. It can hit you a little if developing or changing things often, that’s true.

This behaviour is documented
- in the [AzuraCast docs](https://www.azuracast.com/docs/help/optimizing/),
- the [Autocue Presentation](https://moonbase59.github.io/autocue/presentation/autocue.html#/initial-startup), and
- the [Autocue FAQ](https://github.com/Moonbase59/autocue/blob/master/FAQ.md#how-to-avoid-long-station-startup-time)

I’d suggest _pre-tagging_ such files using the commandline `cue_file` tool. This can speed up things enormously, especially when the station hasn’t too many resources:

![matthias@e6510: ~-Dokumente-autocue presentation_001](https://github.com/AzuraCast/AzuraCast/assets/3706922/1081243c-eaa3-4810-93fd-651de7d88bb0)

Should your files also have no ReplayGain2 tags, when preparing them for broadcasting, you can also use `cue_file` to add such tags, albeit for track data only (no album values). Other tools like [`loudgain`](https://github.com/Moonbase59/loudgain) can also be used in preparing your files and tagging ReplayGain data.

**Comment by stickbear2015** [comment]
@Moonbase59 I totally forgot I had that enabled, This is why a second, third and forth pair of eyes  helps on logs. I'm going to disable this feature, and see if it behaves.
More when I nkow it.

**Comment by stickbear2015** [comment]
@Moonbase59 Thank you for helping me find the underlying issue. This is why communities help and why having someone else not you look at logs and go, yo dude? you broke it. :-)
I've gone ahead and disabled AutoCue Automatic Detection for that station, and restarted things, and everything's back online with no issues.
Again thank you kindly for your help.
I'll go ahead and mark this issue resolved.
