### ISSUE TITLE
Www.wlcp-db.com is down.  I cannot log in to determine what is going on.

### ISSUE THREAD

**Issue by ghost** [AzuraCast/AzuraCast#7287]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Stable Channel

### What happened?

I had one station that was down.  I tried to stop and restart station.  Not sure what happened but shortly after trying to start the one station that was down, I could not login into www.wlcp-db.com/login.  I have 12 stations and cannot afford to be down much longer

### Relevant log output

```shell
Don't know how to view logs when I can't get into stations admin
```

**Comment by daveterry195310** [comment]
I used linode for installation.  I tried shutdown and reboot in linode, still not working

**Comment by BusterNeece** [comment]
>  I have 12 stations and cannot afford to be down much longer

With all due respect here, the fact that we make and give away a piece of software you end up using does not in any way obligate us to be your direct support staff, or create any urgency for us to respond to your issues out of our normal order of responding to issues. In fact, *no* support is guaranteed as part of our open-source software, and the support we do provide is done so entirely voluntarily.

I think you may have a warped conception of what open-source owes you for using it, and I want to nip that in the bud before we wind up with 30 GitHub issues about this just because we aren't responding in a timeline that meets your satisfaction.

**Comment by bombelman** [comment]
@daveterry195310 I've sent you an email.
