### ISSUE TITLE
Services not restarting

### ISSUE THREAD

**Issue by Eyecu** [AzuraCast/AzuraCast#7312]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#536b5f6 

### What happened?

After a server reboot or update or docker restart some services don't start. namely cron php-nowplaying php-worker sftpgo centrifugo. Attached is the log out from docker web as per @BusterNeece 
Think this started after the July 7th update. but it could have been one before that not positive on the day but pretty sure it was july 7th

Wont let me paste the log so https://www.csnode.com/radio/putty.log

**Comment by Eyecu** [comment]
Never left it that long to see, I will the next time I update or restart and see.

**Comment by Sella-GH** [comment]
I got the same issue and it might be related to https://github.com/AzuraCast/AzuraCast/commit/48500fd83400c1569c3ac07c93b28d71185a275f.
However they *do start* after a minute passed or so (at least that's what I am seeing on my instance) so it does seem to be wanted from the dev.

**Comment by BusterNeece** [comment]
@Eyecu Ah, I found the problem in your case. When waiting for nginx to be available, we're pinging `http://localhost:6010/api/status`, basically our status endpoint but via our internal port for service requests. This was erroneously enforcing the "Always Use HTTPS" setting, which is intended for _external_ requests, and because there's no SSL endpoint for internal requests, it was breaking things.

The update I'm pushing to the Rolling Release right now should resolve this in your case.

**Comment by Eyecu** [comment]
@BusterNeece you rock. I'll be remembering to make a donation to the project very soon. thank you for all your hard work

**Comment by BusterNeece** [comment]
Good to hear! Closing this issue.
