### ISSUE TITLE
Check media not picking up new files?

### ISSUE THREAD

**Issue by Moonbase59** [AzuraCast/AzuraCast#7314]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #ad9c362 (2024-07-11 6:55)

### What happened?

After having deleted a (news) file, I’m waiting for the media checker to pick up its data, but it seems not to. It’s supposed to run every 5 minutes and indicates it _has_ run but doesn’t pick up the new data.

File has been available at 09:59, now it’s 10:13. No permissions issues, file playable, tags ok, and all.

Screenshots:

![Auswahl_472](https://github.com/AzuraCast/AzuraCast/assets/3706922/5fcbbac1-de3b-477c-9370-0c2c677bf9db)

![Screenshot 2024-07-11 at 10-13-11 Nite Radio](https://github.com/AzuraCast/AzuraCast/assets/3706922/0df13cf7-cd88-41e1-976f-d984898b5399)

I moved between the "Home" and "time" folders a few times, since the refresh button on this page never seems to update a file when it’s "File processing" and then the data _is_ there. Changing folders and coming back usually helps.

Related: https://github.com/AzuraCast/AzuraCast/issues/7310

**Comment by Moonbase59** [comment]
Also tried manual "Reprocess" from UI at around 10:20, nothing happened. It’s now 10:50, and file still shown as "File Processing".

**Comment by Vaalyn** [comment]
Anything in the application logs? 🙂

**Comment by BusterNeece** [comment]
@Moonbase59 Should be fixed in latest RR.

**Comment by LordHelmchen666** [comment]
I updated to latest Rolling Release #[5dc00dd](https://github.com/AzuraCast/AzuraCast/commit/5dc00dd98508faa5b41a70f623f49e3dad7d0263) (2024-07-12 7:58) but Azuracast won't update with new meta tags. After your fix it looked like everything was working, but today I noticed that the meta data are not filled with new values. No big problem to me because i send new values via API as i already wrote here https://github.com/AzuraCast/AzuraCast/issues/7310#issuecomment-2220983828
Just want to let you know if someone else has such a problem.

For information. I download the file lautfm-news.mp3 at 52 every hour and overwrite the old one. Running _cue_file_ to tag it with new values. Azuracast seems to recognize  that the file is modified.
![Screenshot_20240712_181127](https://github.com/user-attachments/assets/c3df3812-b83d-4b29-8d86-5a399a0a8c94)

**Comment by LordHelmchen666** [comment]
Hell, what is that? Did a quick test and changed one tag with kid3. Waited 4 minutes and it was updated! So i guess i have to observe this.

**Comment by LordHelmchen666** [comment]
In System-Debugger _CheckMediaTask_  shows sometimes "Last run 5 minutes ago - Next run in 4 minutes". Is this intended behavior or a problem on my system? How often should it run? Normally i have "Last run 1 minutes ago - Next run in 3 minutes"
