### ISSUE TITLE
Access-Control-Allow-Origin denying API access

### ISSUE THREAD

**Issue by LazosPlaying** [AzuraCast/AzuraCast#739]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 18 server

**Describe the bug**
When using the following jQuery code, the request is denied by `Access-Control-Allow-Origin` 405 response code
```
$.post(
	'https://host.tld/api/nowplaying/1',
    {},
	function(data, textStatus, xhr){
})
.done(function(data) {
	console.log("success");
})
.fail(function(data) {
	console.log("error");
})
.always(function(data) {
	console.log(data);
	console.log("complete");
});
```

**To Reproduce**
1. Try to query the public API from any remote host

**Expected behavior**
The query would be accepted

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera
 - Version 54.0.2952.71 stable

**Solution**
Set in NGINX host config the following rule in the host
```
add_header 'Access-Control-Allow-Origin' '*';
```

**Comment by SlvrEagle23** [comment]
@LazosPlaying Because POST actions have the possibility of negatively affecting the stations, they're expressly forbidden by the CORS headers. This is in keeping with the RESTful API philosophy that GET requests are solely for retrieving data, while POST/PUT/DELETE requests are for modifying it.

The easy solution here is to `GET` the nowplaying data, at which point it will be fully accessible across multiple hosts.

**Comment by LazosPlaying** [comment]
Awh, shame on me for not thinking about that... Time to re-read the restful api docs and this time actually pay attention ... 😂 

Thanks 👍
