### ISSUE TITLE
Less private information in Public API

### ISSUE THREAD

**Issue by ohld** [AzuraCast/AzuraCast#742]
Hi @SlvrEagle23 again!

I've noticed that we can find some private information in public API available to everyone. 

API Example: https://phystech.tv/api/nowplaying/1
Information I think is private:
* Frontend and Backend types (icecast, liquidsoap), 
* The information about listeners amount (!!!)

What do you think about it? Should this information be removed from this publicly available API?

**Comment by SlvrEagle23** [comment]
@ohld I can see the case for hiding the frontend and backend types (which are only on there in the event that third-party services need to know this to adapt how they connect to the station), but even if AzuraCast didn't show the listener counts, the respective broadcasting software itself (Icecast/Shoutcast) _does_. Since the counts in AzuraCast's API reflect information that would already be public, I don't consider that as much of a problem at all.

**Comment by ohld** [comment]
So in other words there is no possibility to hide the listeners count, right?

**Comment by SlvrEagle23** [comment]
@ohld Let me put it this way. I intend that for every instance of AzuraCast, you can generally assume that you can hit that service's API and basically get the same structured response back. I want the response to be predictable and consistent across installed instances, so the same third party software written to hit one AzuraCast instance can work on another.

While I'm okay with varying the number of things that return an array response (i.e. the amount of song history items), because almost anything reading that section expects that to be a collection of 0 to n items, outright removing sections that people should reasonably expect will be present in an API response could cause a great deal of confusion, particularly if the responses differ between stations on the same server.

The one exception I'm willing to make to this is in the case that royalty boards specifically require it for webcasters, such as some European countries requiring that the "playing_next" field not be supplied. I'm not inclined to make an exception for data that is already made public by Shoutcast and Icecast, and that constitutes one of the most essential pieces of metadata one can retrieve about a station.

**Comment by ohld** [comment]
Ok. Thanks

**Comment by ohld** [comment]
But the checkbox "send the information about listeners count" like "send playing next info" would be nice anyway.
