### ISSUE TITLE
Addition of playlistlog

### ISSUE THREAD

**Issue by zagnu** [AzuraCast/AzuraCast#745]
**Is your feature request related to a problem? Please describe.**
The DJ's at the station I work on only provide a "Title" as it comes across, and yet none of that gets logged into the main system so curious if the playlistlog could be added when I do it it is overwritten.

**Describe the solution you'd like**
I would like the logs to have:
<playlistlog>playlist.log</playlistlog>
Style configuration added, then I can run metrics on it myself for reports for licensing audio.

**Describe alternatives you've considered**
I'd love the built in reports to handle this something super generic like title (in their case it covers Title + Artist) they are looking to revamp over the next 2 years with new tech, new transmitter, etc. but not something changing anytime soon.

**Additional context**
playlistlog could be downloaded, reivewed and rotated on a quarterly basis for easy reporting, primary thing reporting they need is more in the realm of songs by the artists, so any help is appreciated! Even if it's a simple way to add in the playlist log somewhere I'm just missing.

Thanks!

**Comment by SlvrEagle23** [comment]
@zagnu So, I think we can boil this request down to two items:

- An issue with DJs sending only the Title metadata instead of "Artist - Title", and this causing problems with statistics and analytics, and
- Expansion of the existing history reporting tools to allow exporting for longer periods for royalty purposes.

The second item has been resolved through a series of very recent updates, where a new Station History API was created, which replaces the existing "Song Playback History" report with a new one with a custom date selector, and the ability to export whatever date range you specify to a CSV.

The first item may be more of an issue with the upstream radio software itself. I've noticed before that if I just send "Title" as a streamer through to Liquidsoap, it'll throw an error indicating that Shoutcast has rejected the metadata update, as it tries to split the title metadata by the " - " separator.

There may be something we can do to counteract this problem, such as appending " - " to any metadata that is missing one already, but I'll have to look into the logistics of doing this inside Liquidsoap.

**Comment by zagnu** [comment]
Here's an example of what they are sending over as the title:

Crowder - Run Devil Run

So it is separated, works well with our new HTML5 player so we can then pull it apart and get album artwork, so quite nice to have that functionality. 

We are using Icecast as everything was configured around it with their previous Streaming Service, for ease of transition we kept things Icecast. I found a way to append and have the playlist.log file working using the Advanced: Custom Configuration section and just re-created the log section again so it created it - thus have at least a file I can rotate in and out and glean from that for now, already just running in standby mode giving me some clean info to work with! 

Appreciate this software for sure! I'm trying to work on the DJ's to input the full meta data if possible but anything you can do to help would be appreciated!

**Comment by SlvrEagle23** [comment]
@zagnu I'm not entirely clear on what it is I can do to help from AzuraCast's side here. If there's something specific you would like me to be implementing, let me know.

**Comment by zagnu** [comment]
Is there any way for the logs in the front end to include easy to pull stats of songs even if the meta data provided is just a title? I guess I’m just hoping for a setup I can hand off to the station manager for her reports which include play count of songs, vs. me crunching them from time to time.

**Comment by SlvrEagle23** [comment]
@zagnu Does the station playback timeline not work just fine for this? You can download CSV exports of the timeline history for any custom period using the latest updates.

**Comment by zagnu** [comment]
Shows nothing at all. Simply says no results found.

**Comment by SlvrEagle23** [comment]
@zagnu From the Administration panel, if you manually run the "Now Playing" sync, it should pop up some debug information about what it sees coming directly from the radio server. This is probably the first step in debugging this, as it sounds more like a bug in how metadata's making it through.

**Comment by zagnu** [comment]
`Array
(
    [current_song] => Array
        (
            [text] => Stream Offline
            [title] => 
            [artist] => 
        )

    [listeners] => Array
        (
            [current] => 0
            [unique] => 0
            [total] => 0
            [clients] => Array
                (
                )

        )

    [meta] => Array
        (
            [status] => offline
            [bitrate] => 0
            [format] => 
        )

)`

However in the area above that shows the source and playing information too, so it thinks I’m offline?

**Comment by SlvrEagle23** [comment]
@zagnu What does the area above that say? Seems to be mis-parsing it.

**Comment by zagnu** [comment]
Array
(
    [admin] => icemaster@localhost
    [banned_IPs] => 0
    [build] => 20180717095727
    [client_connections] => 80612
    [clients] => 2
    [connections] => 20198
    [file_connections] => 2
    [host] => listen.kaxl.com
    [listener_connections] => 11
    [listeners] => 0
    [location] => AzuraCast
    [outgoing_kbitrate] => 9
    [server_id] => Icecast 2.4.0-kh7
    [server_start] => 24/Aug/2018:22:53:46 +0000
    [source_client_connections] => 5
    [source_relay_connections] => 0
    [source_total_connections] => 5
    [sources] => 1
    [stats] => 0
    [stats_connections] => 0
    [stream_kbytes_read] => 2043559
    [stream_kbytes_sent] => 48710
    [source] => Array
        (
            [audio_codecid] => 10
            [audio_info] => ice-samplerate=44100;ice-bitrate=128;ice-channels=2
            [bitrate] => 128
            [connected] => 13538
            [genre] => Christian
            [ice-bitrate] => 128
            [ice-channels] => 2
            [ice-samplerate] => 44100
            [incoming_bitrate] => 128120
            [listener_connections] => 1
            [listener_peak] => 1
            [listeners] => 0
            [listenurl] => http://listen.kaxl.com:8000/kaxl_live
            [max_listeners] => unlimited
            [metadata_updated] => 26/Aug/2018:11:16:19 +0000
            [mpeg_channels] => 2
            [mpeg_samplerate] => 22050
            [outgoing_kbitrate] => 0
            [public] => 1
            [queue_size] => 65334
            [server_description] => Listen to KAXL Online!
            [server_name] => LifeFM (KAXL)
            [server_type] => audio/aacp
            [server_url] => http://www.kaxl.com
            [slow_listeners] => 0
            [source_ip] =>  xxx.xxx.xxx.xxx
            [stream_start] => 26/Aug/2018:07:31:59 +0000
            [title] => Aaron Cole - Right On Time (feat. TobyMac)
            [total_bytes_read] => 216591595
            [total_bytes_sent] => 19411968
            [total_mbytes_sent] => 18
            [yp_currently_playing] => Aaron Cole - Right On Time (feat. TobyMac)
            [@mount] => /kaxl_live
        )

)

**Comment by SlvrEagle23** [comment]
@zagnu Is the `/kaxl_live` mount point listed on AzuraCast? It looks like it's having trouble figuring out the "default" mount point to use.

**Comment by zagnu** [comment]
Only mount point I see in mount points is /radio.mp3 however that doesn’t actually work, did I do something wrong? The 
Advanced: Station URL Stub is what is set to kaxl_live, that is functional though

**Comment by SlvrEagle23** [comment]
@zagnu Is it possible to have your DJs connecting through Liquidsoap using the Icecast connection method, instead of actually logging directly into Icecast itself? It's the fact that they're doing the latter that is causing AzuraCast to have trouble reading what song is playing, as it isn't aware of the mount point that the live broadcast is using.

**Comment by zagnu** [comment]
By chance can you suggest docs on how to do that? It works streaming wise, so if there is an adjustment any help you can provide to adjusting their side is appreciated.

**Comment by SlvrEagle23** [comment]
@zagnu It's just a matter of instructing the DJs to change where they're connecting from the Icecast server's port to the port shown on the "Streamers/DJs" panel inside AzuraCast (which may need to be enabled first). This will also let you use AzuraCast to provision and manage individual DJ accounts from within the web interface, instead of having to pass around shared credentials.

**Comment by zagnu** [comment]
Ah! That required a little bit of a tweak from the current config in edcast & what TRE was kicking out - but with some tweaks, and a minor re-write of a small PHP script which decodes RCS file on the server, tada! I have a working stream + metadata! Thanks a million for sticking with me on this! Much appreciated!

**Comment by SlvrEagle23** [comment]
@zagnu Happy to help! :)
