### ISSUE TITLE
Temp files not being cleaned up, or cleanup now has different params

### ISSUE THREAD

**Issue by troykelly** [AzuraCast/AzuraCast#7460]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

Rolling Release #93aa38c (2024-09-20 8:46)

### What happened?

After a recent rolling release update, we seem to be filling disks.
We use `S3` (minio) for media storage.
I've created a tool to very heavy-handily clean up so we don't fill the disk. [clean-old-files](https://gist.github.com/troykelly/353f99a8206d49e6a6aae5f6bb4e35b5)
With the tool running, we aren't filling the disk - but I don't know if deleting old files from the stations temp dir is upsetting the rest of the system somehow.

This has not been an issue until very recently.

**Comment by BusterNeece** [comment]
@troykelly Should be fixed in the latest Rolling Release. We're trying to implement some "common runtime code" basically with AzuraCast that reduces the amount of custom code in each Liquidsoap file and allows the system to better cache our more commonly used functions, and in the process we had to remove the distinction between local and remote filesystems in the `media:` protocol. This meant that remote filesystems didn't clean up their temp files like normal, but was fixed on the flipside by explicitly tagging those paths as "temporary" so they get cleaned up properly.
