### ISSUE TITLE
Failed backup leaves file dangling in unknown location

### ISSUE THREAD

**Issue by marekdziem** [AzuraCast/AzuraCast#7523]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### What happened?

Running a manual backup failed leaving several Gb unfinished backup file somewhere on the filesystem.
where is the tmp folder used to build the backup file so I can go manually delete the failed backup files?

**Comment by amacleod457** [comment]
Yeah, the backup system leaves a fair bit to be desired. E.G. more robust error checking and cleanup on failure, as in your case. as well as including per-station backups on a multi-tenant installation, a multi-year open feature request on my part.
And I really would love to know why a backup requires not twice, but three times the disk space.
However, at any rate, the path is:
/var/lib/docker/volumes/azuracast_backups/_data

**Comment by BusterNeece** [comment]
I've done some work to improve the backup system, including more robust cleanup and error handling, better logging of disk space changes, and most importantly a change so that if you're backing up to a local (on-disk) storage location, the initial backup will directly write to the destination path instead of writing to a temp file and then copying over. This removes one whole step for a vast majority of installations, and means that at most twice the disk space is needed during the backup process. It also means that if you have a custom backup directory mounted (i.e. using VPS block storage), it will take advantage of that larger space without throwing out-of-space errors.
