### ISSUE TITLE
Statistics not working for Podcasts

### ISSUE THREAD

**Issue by mcassisa** [AzuraCast/AzuraCast#7527]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

#3de1908 

### What happened?

The statistics page doesn't work for podcasts: no listener logged, no playing time... nothing

**Comment by BusterNeece** [comment]
@mcassisa Is this a bug report or just a thing you noticed? Because we've yet to implement robust statistics for podcast listeners entirely at the moment. You may be looking to make a feature request instead, which you can do at https://features.azuracast.com/

**Comment by mcassisa** [comment]
I felt entitled to think that "Statistics" covered all the listeners to azuracast, but I should have not. This would be a very useful feature in my opinion, which completely fit to azuracast and to the concept of statistics

**Comment by mcassisa** [comment]
Can anyone kindly point to the specific place in the code where usually statistics are saved for radio stream? Maybe it can be not so hard to log them for podcast

**Comment by BusterNeece** [comment]
To answer your question, a majority of our statistic logging is done in this file, specifically this function:

https://github.com/AzuraCast/AzuraCast/blob/2cc9a58532148e372bb589b0471dcea085a3c49e/backend/src/Entity/Repository/ListenerRepository.php#L102-L147

Pull requests are always welcome, though I suspect it'll be quite a different task to log podcast listeners than it is to log radio ones, just because one is being served via a PHP download service and the other is being served directly via either nginx or icecast.
