### ISSUE TITLE
Some music files not being processed

### ISSUE THREAD

**Issue by Donokami** [AzuraCast/AzuraCast#76]
https://gist.github.com/Donokami/c538fd2073a44d693287f7f93bbeea52

When i try to access to Profile or to the Restart page, i have this error.

Also, my music files are not treated, i don't know why (have ID3 tags, and are mp3).

**Comment by Donokami** [comment]
I resolved the transport exception issue by restarting supervisor.
But my files ae always taking a lot of time to be treated !

**Comment by SlvrEagle23** [comment]
@Donokami Sorry for the delay in getting back to you, it's been a busy week for me.

I'm glad you discovered the solution (and it's exactly the one I would suggest, just restarting supervisord).

As for the delays in processing your media files, depending on how large the files are, processing might take a little longer, but it shouldn't take so long that it becomes a problem. If you have one file in particular that is causing a very large processing time, feel free to send a link to the file and I can take a closer look.

**Comment by Donokami** [comment]
No problem.
The problem is that I put more than 700 songs online and it takes a lot of time. Is there a way to handle files faster, or manually?

Thanks.

**Comment by SlvrEagle23** [comment]
@Donokami Each file should only be processed once, then it won't be reprocessed again unless the modified date on the file changes.

There is a way to manually trigger file processing, by visiting the System Administration page and clicking the "5-minute Sync" task near the bottom, which is specifically intended to run in the background to process files.

**Comment by Donokami** [comment]
Thanks ! :)

**Comment by Donokami** [comment]
I tried this, but when i access to the web page /admin/sync/medium/, i have this following error
![image](https://cloud.githubusercontent.com/assets/5563277/21472702/b3cfe850-cae5-11e6-8f28-d8828467bbde.png)

**Comment by SlvrEagle23** [comment]
@Donokami It seems you're encountering some issue with the ID3 processor not being able to handle your files. I've fixed the part of the code that was causing the error you saw before, so you may want to reattempt to upload those same files and let me know if it shows you a more specific error.

If it's something that can't be resolved on your end, feel free to send me one example MP3 file so I can take a look and work on it. :)

**Comment by Donokami** [comment]
Thank you very much for your help, but it seems that it does not do anything on my side.
Indeed, my tracks are all moved in "not-processed", except for 3 tracks.
In theory all the ID3 tags are unified because I used [scdl](https://github.com/flyingrub/scdl) in order to get my music, but [here in case the different tracks involved.](https://github.com/SlvrEagle23/AzuraCast/files/680055/tracks.zip)

Also, when i try the '5-minute Sync", i have an error, with cloudflare it's "web server isn't responding", without i have this:
![image](https://cloud.githubusercontent.com/assets/5563277/21581828/aaedbb5c-d041-11e6-9289-0cdfa1cb1a16.png)

Isn't because i try to process 500 tracks at the same time?

**Comment by Donokami** [comment]
After multiple tests, it seems that it comes either from the name of the files or ID3 tags that do not seem to work.
Here is for example [this track](http://fs.ht/0ca6873e-d067-11e6-b44a-06a321be14fb), which does not work at all with Azuracast!

**Comment by SlvrEagle23** [comment]
@Donokami I always love it when people send me tracks that I actually really end up enjoying. :D

In this case, I think I found the problem. I was able to upload it on my local AzuraCast instance just fine, but I can see how it would pose a problem on some systems, as the name is entirely composed of nonstandard unicode characters:
https://i.imgur.com/fUY6h9G.png

**Comment by SlvrEagle23** [comment]
@Donokami I just pushed an update to resolve the "EntityManager has closed" issue. It likely won't resolve your issue, however, it will show the correct error message that is causing it.

Would you mind trying to import your media again and letting me know what error it gives you?

**Comment by Donokami** [comment]
![Here is the error.](https://cloud.githubusercontent.com/assets/5563277/21583200/36b698fa-d076-11e6-9b11-b812cc819a60.png)

**Comment by SlvrEagle23** [comment]
@Donokami Unfortunately I can't reproduce this issue locally at all...on every instance of AzuraCast that I have available to test with, the file imports correctly without any issue.

Can you tell me what architecture and Ubuntu distribution you're running?

**Comment by Donokami** [comment]
Ubuntu 16.04.1 x86_64
MariaDB server version: 10.0.28-MariaDB-0ubuntu0.16.04.1 

I have this error with several files !

**Comment by shaundewberry** [comment]
I have experienced a similar issue, where the majority of my files are dumped into the "not-processed" directory in an unstructured fashion.

I picked up a Warning in /var/azuracast/www_tmp/php_errors.log saying the stat call on the mp3 file failed.

Digging further, /var/azuracast/www/src/AzuraCast/Sync/Media.php throws the exception on line 62, This exception is in loadFromFile which is defined in /var/azuracast/www/src/Entity/StationMedia.php.
The exception trigger appears to be the filemtime() call that runs without first checking for file existence on the $media_path in the loadFromFile function on line 117.

The stat call could be failing due to permissions, a file lock, or some other issue. I'm testing the permissions theory first by including a quick hacky file existence check in the loadFromFile in StationMedia.php before the filemtime(). Will revert with more when I have it.

**Comment by SlvrEagle23** [comment]
If anyone is having this issue still, please let me know and I'll work to fix it.

**Comment by Donokami** [comment]
Well, it works for me when i wait for the auto 5 min sync, but if i force it (by using the button in the System Administration), all of my non treated files are going to "not-processed".

**Comment by shaundewberry** [comment]
I can confirm I updated to latest Azuracast yesterday and copied 64GB of mp3s directly into the media folder with none of them being moved to not-processed. Thanks for the fix.

**Comment by SlvrEagle23** [comment]
There have been a broad set of changes between the time this ticket was originally created and now; if anyone else has further issues with files being incorrectly moved in bulk to "not processed" despite being valid MP3/OGG/FLAC/etc files with ID3 metadata, please make a new ticket and include (if possible) an example file that the system isn't processing. Also indicate whether the issue is being caused only by direct SFTP uploading, by drag-and-drop web uploading, or both.
