### ISSUE TITLE
160_zeichen_-_filip_(offizielles_musikvideo).m4a: An ID was not generated for this object.

### ISSUE THREAD

**Issue by lolhd22** [AzuraCast/AzuraCast#7605]
### Installation Method

Docker Installation

### AzuraCast Release Channel

Rolling Release Channel

### Current AzuraCast Version

v0.20.4 Stable

### What happened?

i cant play aa song with the button play now

it show me this error: v0.20.4 Stable

**Comment by LordHelmchen666** [comment]
I can confirm that behavior also occurs on latest Rolling Release #[cd70097](https://github.com/AzuraCast/AzuraCast/commit/cd7009736c20a4b76779856a934edee389d7ca46) (2024-12-05 0:22) . I think this happens since `StationQueue ID` (sq_id) was introduced.
To reproduce go to Media Manager - Choose a track - More - Play now.
 Error Modal pops up 
_"Error queueing files:
Helmut/Ballads/Feelings 02/01-Albert Morris Feelings.mp3: An ID was not generated for this object."_
