### ISSUE TITLE
Memory leak, clean Ubuntu, 450m > ~900mb in 2-3 hours.

### ISSUE THREAD

**Issue by AdamDaze** [AzuraCast/AzuraCast#769]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 18.04.1 on Windows 2012 HyperV

**Describe the bug**
Over several hours ram usage increases/doubles till streams interrupt (stuttering).

**To Reproduce**
Start server. Wait. 

**Additional context**
Running 4x playlist stations with transcoding mp3 > ogg vorbis, and re-streaming one live stream.

Anyone seeing similair behaviour? It's a stock/clean ubuntu install with nothing but Azuracast bolted on top. Should I have modified any configuration to handle multiple stations? It's initially at 25% on a 2core VCPU, and 450m of ram, but balloons up to ~900meg of ram in a couple of hours.  CPU usage remains the same, but starts spiking up to ~80% of song changes.

**Comment by SlvrEagle23** [comment]
@AdamDaze For one, I think your issue headline may be a bit misleading, as it's from 450mb to 900mb, not 900gb!

Also, it would be helpful to look through the processes (i.e. with `htop`) and see what's actually occupying the increased slice of memory.

It's worth noting that between MariaDB and PHP's FPM workers, it's not unusual for memory usage to grow a bit as the opcode cache and query caches are built during normal station operation. If the total usage of the system is still under 1GB, that may indeed be completely normal.

**Comment by SlvrEagle23** [comment]
@amavarick I think the issue you encountered is different from the one being reported here, namely that this issue is about a RAM leaking issue and yours was caused by excessive CPU consumption.

In your case, the answer is somewhat cynical but simple: hosting providers often overcrowd their VPS infrastructure and count on the fact that generally, one VPS will only need CPU power in small bursts, the remainder of the time being redistributed out to the other customers. Since transcoding media is an almost constant CPU load all day every day, this displeases those VPS providers.

The safe bet is to look for a VPS provider that allocates your system resources that it can use fully without concern for overage like that.

(As a side note, I'm hoping the VPS provider that did this to you wasn't DigitalOcean, as I'd probably want to have a word with them if so!)

**Comment by AdamDaze** [comment]
@SlvrEagle23 HTOP reveals all azuracast processes using cpu at the time, I'll go back and have a gander at mem usage. IIRC it was all azuracast in the top memory slots but I'll double check this.

**Comment by SlvrEagle23** [comment]
@AdamDaze It's important to narrow this down as there is no process named "azuracast" that runs as part of AzuraCast, it's a composition of MariaDB, Redis, InfluxDB, Nginx, PHP-FPM, Liquidsoap, Icecast and Shoutcast. Any of those constituent pieces of software could be responsible and it's impossible to narrow down without knowing more information.

**Comment by amavarick** [comment]
@SlvrEagle23  I want to be mindful of not hijacking a post and defer to your direction.  At the time I was just worried about not getting banned so I wiped the instance rather than risk the time taken to troubleshoot so to my knowledge, my issue is resolved as I've not encountered the issue since June.

Regarding resourcing though, I use turnkeyinternet.net and am using their cloud VPS T40 plan which uses KVM.  They actually dinged me for going over 700% of the CPU usage allotted for that instance for a consistent period of time and not just a burst.  There are other budget VPS companies that only offer an OpenVZ solution and upsell their stuff such as vpsdime.com.  I have another instance with turnkeyinternet also T40 using https://github.com/radiorabe/centos-rpm-liquidsoap with icecast and have the same radio stations and selection of music on them.  Granted no docker, nginx and all of the extras needed for such a seamless beautifully designed software such as yours which come at an added resource cost but haven't had any issues with the same company and same VPS size.

**Comment by SlvrEagle23** [comment]
@amavarick We may want to move this discussion to its own issue if you feel it merits further investigation on my end. Typically, the CPU overhead of the full AzuraCast stack is only marginally higher than the raw overhead that transcoding itself would represent, as AzuraCast isn't (or, at least, shouldn't be) constantly bursting the CPU any more than a typical web application would.

**Comment by AdamDaze** [comment]
Honestly I'm relatively new to linux in general, but here's some screenshots of htop sorted by cpu, mem %, and virt mem.  

![sharex_2018-09-04_15-00-49](https://user-images.githubusercontent.com/13102694/45010980-854d2600-b053-11e8-956d-044375ac2bbd.png)
![mstsc_2018-09-04_14-59-10](https://user-images.githubusercontent.com/13102694/45010982-854d2600-b053-11e8-9b00-7bb7ce02e0bd.png)
![mstsc_2018-09-04_15-01-34](https://user-images.githubusercontent.com/13102694/45010983-85e5bc80-b053-11e8-8737-9fbc29245235.png)

**Comment by xewl** [comment]
@SlvrEagle23 Sidenote: no, DigitalOcean does not abide such CPU-limiting policies. Neither does Hetzner. Your VPS' resources are allocated even though its turned off.

**Comment by SlvrEagle23** [comment]
@AdamDaze It seems like InfluxDB is taking up a little more memory than I'd expect it to be taking up given the circumstances. I went ahead and updated the Docker container AzuraCast uses to point to the newest version of InfluxDB (1.6) rather than 1.4, so hopefully that will improve the performance and memory characteristics.

Beyond that, I think the memory usage is really quite normal for the application. It isn't necessarily that any one component is "ballooning" in size as much as the sum total of all of the applications running tends to settle in around 1GB of RAM. While AzuraCast can run on less than this (and should indeed run fine, given proper swap space setup), 1GB is a pretty reasonable starting point for any production instance.

**Comment by AdamDaze** [comment]
Thanks. That should be as simple as running ./docker.sh update yeah?

**Comment by AdamDaze** [comment]
Or not. After restart docker has no conatiners but I still a bunch of stuff in /var/lib/docker/volumes . Argh.

**Comment by SlvrEagle23** [comment]
@AdamDaze Did you get any kind of error message? The docker images shouldn't have changed in a significant enough way to stop them from booting up properly.

**Comment by AdamDaze** [comment]
Didn't see one, no. But don't know where to check logs. On restart nothing came up. No azuracast services working, none showing in htop. Docker ps -a says no containers exist. I can see various folders in the above directory but being a ubunutu newbie I may just be f***** back to "start at scratch* here.

**Comment by SlvrEagle23** [comment]
@AdamDaze Are you in the directory where you first ran the AzuraCast installer? If the docker-compose.yml file is missing, you can just run the update script again and select "yes" to regenerating it.

**Comment by AdamDaze** [comment]
Okay, that's worked, thank lord. I had no idea where it was first installed, so I had to search for docker-compose.yml , went to that directory, ran the docker-compose up -d and now we're back up and running. So much appreciation with your patience for a "ubuntu as a distant third langauge" newbie here, by the way. 

So restarted and sitting on 504mb now. Interestingly all the top memory instances are all mysqld now, and no influxd listed, though it does show up in mem shared now, but not where it used to in mem %.  Go fish. Seeing about the same ram usage as before, but it takes a few hours to replicate the growth and stuttering so will report back. 

![mempercent](https://user-images.githubusercontent.com/13102694/45026753-95302e80-b082-11e8-85e5-1a1110ca971a.JPG)

**Comment by CodeSteele** [comment]
Going to close this being as we haven't heard anything, feel free to reopen @AdamDaze if the issue persists.
