### ISSUE TITLE
Tip: Format m3u8 for IPTV List and ios

### ISSUE THREAD

**Issue by JMultimidia** [AzuraCast/AzuraCast#775]
**List m3u8 (Not equal to m3u).**
In order for me to play my radio on some IPTV or ios applications, the m3u8 format is required.
Currently I use Wowza to repeat the shoutcast, but it would be more practical to azura with m3u8 instead of generating only pls and m3u.

**Comment by SlvrEagle23** [comment]
@JMultimidia It appears the only difference between .m3u and .m3u8 playlists is that .m3u8 playlists are encoded using UTF-8, which AzuraCast already uses for all filenames and URLs. This playlist format should work without any issue in whatever software you want to use it in.

If it isn't working correctly, there is likely a reason other than the difference between .m3u and .m3u8. Let me know specifically what the problem is and I may be able to work on improving it.

**Comment by JMultimidia** [comment]
A file with the m3u8 extension is an audio playlist file encoded with UTF-8. They are simple text files that can be used by audio and video players. They can describe where the multimedia files are located.

For example, an m3u8 file can provide references to online files from an Internet radio station. You can create another one on your computer to create a playlist for your own music or a series of videos.

In an m3u8 file you can use absolute, relative, and URL paths to refer to specific multimedia files or complete folders of multimedia files. These files can also host comments describing their content.

These files have a format similar to m3u files. They can use UTF-8 encoding, but may also include other character encodings.

The m3u8 format I use in all the applications I develop to make sure it will play on any smartphone or smartv.
