### ISSUE TITLE
Remote relay not working

### ISSUE THREAD

**Issue by guiscaranse** [AzuraCast/AzuraCast#803]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 16.04

**Describe the bug**
So, I've enabled the remote relay option as I described in #781, added the AutoDJ information, but no connection is made to the remote server. In fact, I can see the log from the remote Shoutcast server, but no connection is in fact made to the remote server. I don't think it is a firewall related issue since if I add the relay manually as a relay of the station I can see that a connection is made through the Azuracast image (not for transmission)

**To Reproduce**
1. Go to your station
2. Click on manage
3. Click on remote relays
4. Add remote relay information
5. Enable autodj and complete with transmission information
6. Click save
7. No transmission is sent to the remote relay

**Expected behavior**
The remote relay should stream what the local azuracast is streaming.

**Comment by SlvrEagle23** [comment]
@guiscaranse Any information in the logs, by running `docker-compose logs -f stations`?

**Comment by guiscaranse** [comment]
I've checked the log and can see the error:
```
stations_1     | 2018/09/21 10:38:47 [radio_out_2:3] Connecting mount sid#1 for @srv1.guiscaranse.ml...
stations_1     | 2018/09/21 10:38:47 [radio_out_2:2] Connection failed: Failure("inet_addr_of_string")
stations_1     | 2018/09/21 10:38:47 [radio_out_2:3] Will try again in 3.00 sec.
stations_1     | strange error flushing buffer ... 
stations_1     | strange error flushing buffer ... 

```

**Comment by guiscaranse** [comment]
So, I've figured it out based on the log: replacing the host address with the IP address did the trick. I think there is a problem with Azura when resolving domains.

**Comment by SlvrEagle23** [comment]
@guiscaranse In both the Docker and Traditional install cases, DNS resolution depends on the host operating system's configuration; in Docker's case, if the internal DNS resolution fails, Docker automatically adds the Google public DNS servers (8.8.8.8, 8.8.4.4) to the resolving chain. Those are pretty reliable for resolving lookups.

At least from my end, I was able to retrieve an IP address for your host. This suggests DNS resolution might not be the problem, and it may have something to do with whether your radio is configured to handle incoming connections using that hostname rather than just the IP. That may be worth looking into, but if the IP-based connection works, then there's nothing wrong with just continuing to use that.
