### ISSUE TITLE
Picker "ALL" Option Error

### ISSUE THREAD

**Issue by djmuratb** [AzuraCast/AzuraCast#806]
Installation method
Traditional installation method.
Ubuntu 18.04.1 LTS

Page : Song Playback Timeline
When you select "ALL" with selector, only 1 song in the list.

![all](https://user-images.githubusercontent.com/25807005/45890479-beafc080-bdcb-11e8-8b64-50a95a4f36b6.png)

**Comment by SlvrEagle23** [comment]
@djmuratb I did identify an issue with the "ALL" response on the timeline, but the reason "ALL" originally wasn't allowed on this request is because it would likely consume too much memory in the process of iterating through thousands of requests.

I've updated the bootgrid on that page to reflect that the "ALL" option isn't available. Sorry for any confusion.
