### ISSUE TITLE
path issue file not found

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#812]
hello all, 
i set up azuracast the traditional way, because i could not get along with docker, so created 2 playlists one for the autodj and one for the butt-DJ-live-stream, but when i click on the m3u or XSPF is show file not found https://stream.bayrad.io/public/bayradio  maybe a config issue or it has todo with a special cloudflare setting , i am clueless , i need the json file for parsing the information into a player on the website. Thanks in advance

**Comment by SlvrEagle23** [comment]
@macbroadcast It looks to me like both the PLS and M3U downloads are working properly, and they represent playable files that work fine both in-browser and in VLC.

One possible issue would be the file naming convention; for some reason they're just downloading as "pls" and "m3u" instead of the filename specified. I'll take a look at that.

**Comment by SlvrEagle23** [comment]
@macbroadcast The download filenames should be fixed now, corresponding properly to the station's name with the ".pls" or ".m3u" extension, which should make them playable by default.

**Comment by macbroadcast** [comment]
Sorry my fault i posted the wrong reference page, could you check again

**Comment by SlvrEagle23** [comment]
@macbroadcast Oh, that's the radio software itself, which is having trouble because the software itself isn't aware of the proxying going on in front of it. Your users should be using the public PLS/M3U links from your public page on AzuraCast, as those are aware of the proxying and update their URLs accordingly.

**Comment by macbroadcast** [comment]
@SlvrEagle23 Ahh great , thanks for the info, can you give me the json.xlm path ?

**Comment by SlvrEagle23** [comment]
@macbroadcast What? The original public page you linked has the links to download the PLS/M3U files.

**Comment by macbroadcast** [comment]
I am using a wordpress theme, which requires a json.xsl or stats-json.xsl url for capturing the meta data :r http://www.qantumthemes.com/manuals/onair2/knowledge-base/2-5-radio-station-channels/

**Comment by SlvrEagle23** [comment]
@macbroadcast That should still be https://stream.bayrad.io/radio/8000/status-json.xsl

**Comment by macbroadcast** [comment]
@SlvrEagle23 you made my day , now i can open http://jsonviewer.stack.hu/#http://stream.bayrad.io/radio/8000/status-json.xsl  but you see the url is wrong, why is there any port specified when i use the proxy cloudflare function ?

**Comment by SlvrEagle23** [comment]
@macbroadcast Again, this is because the radio software itself is unaware of the proxying going on. It expects to occupy its own dedicated port, and it's only listening on that port, not a subfolder on the main server.

In this situation, you can either make the port it's on publicly available and actually let users connect directly to 8000, or modify your Wordpress script to update the stream URL accordingly.

**Comment by macbroadcast** [comment]
@SlvrEagle23 Thanks a lot, because i wasnt able to connect with butt to my server at all using the subdomain stream.bayrad.io and i was wondering how other achieve this, with having port 8005 set inside butt, its not that i dont trust our DJ but i wanna prevent using IP adresses at all.
