### ISSUE TITLE
Error: xxxx.mp3{"error":{"code":403,"msg":"CSRF Failure: This CSRF token has expired."}

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#824]
Currently uploading files thru web interface, just curious what this means?

Any other way to upload the files via sFTP into a traditional installation?

Thanks

**Comment by SlvrEagle23** [comment]
@macbroadcast SFTP just takes advantage of SSH, which already exists in your host system. The only reason SFTP needs to be set up specially for Docker is because Docker typically doesn't expose SSH access direct to the outside world.

For traditional installs, you can just connect to your server via the SSH port (by default, 22) using software like Filezilla or Cyberduck. When you ran the traditional installer, it should have produced a random password for the `azuracast` user; if you've lost this, you can always reset it by running `passwd azuracast` (the web application doesn't depend on that password). You can then use `azuracast` and your user account password to connect via SFTP, then upload files directly to `/var/azuracast/stations/(station_name)/media`, where they will be processed within the next few minutes.

To answer your original question, this is typically caused by leaving the same page up too long. CSRF (cross-site request forgery) tokens expire after a set period, so that a bad actor can't send you a link to a page that would do something negative to your station without confirmation, as it would require a unique CSRF token that they can't access.

**Comment by macbroadcast** [comment]
hello @SlvrEagle23  i am not 100% clear about this > When you ran the traditional installer, it should have produced a random password for the azuracast user; if you've lost this, you can always reset it by running passwd azuracast (the web application doesn't depend on that password). 

So you are talking about user accounts not DJ/Streamers, ok i currently i have just one superuser and his password seems not the one my filezilla wants 🤓   `Connecting to 142.93.35.0...
Response: 	fzSftp started, protocol_version=8
Command:	open "marc@baybroadcast.uk@142.93.35.0" 22
Command:	Pass: ************
Error:        	Authentication failed.
Error:        	Critical error: Could not connect to server`

**Comment by SlvrEagle23** [comment]
@macbroadcast Correct, I'm not talking about a DJ/Streamer. I'm talking about a Linux user. AzuraCast's traditional installer automatically makes one with the username `azuracast`. The installer should have given you the password for it at the end of the installation, but if you lost it, you can just reset it with `passwd azuracast`. Then, you use `azuracast` as your username and that password as your password when connecting via SFTP.
