### ISSUE TITLE
API endpoints / server selector

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#825]
I just figured out you're using swagger for API description, which is awesome, so I generated an API key and authorized the endpoints, but why I just see just _demo.azurecast.com/api_ in my list. 🤓 
and is the _domain.tld/api/_  exposed to everyone or just accessible with the bearer token? 
Thanks 😍

**Comment by SlvrEagle23** [comment]
@macbroadcast Most of the general data is available to anyone with or without an API key, but any intensive actions that would modify the station (restarting it, etc) do require an API key. If you're implementing something for users on the frontend, you shouldn't include that API key.

As for the Swagger documentation, it needs a base URL specified, which is why the testing happens against the demo server. Any AzuraCast instance has the same API exposed at its `/api` endpoint (with its own authentication).
