### ISSUE TITLE
Wrong Listener Stats

### ISSUE THREAD

**Issue by LordHelmchen666** [AzuraCast/AzuraCast#829]
I have two mountpoints. /radio.mp3 and /radio.aac
Listeners on /radio.aac will not be shown/counted. On Icecast Admin Page "List Mountpoints" it is correct.

**Comment by CodeSteele** [comment]
Reproduced on the demo instance using VLC as a client If I move the default mount point it'll list listeners on the new default mount point, with the old default mount point no longer showing listener counts.

**Comment by CodeSteele** [comment]
Yep, this is a behavior restriction for how the NowPlaying adapter works -- it allows you to grab client statistics _per mount point_.

https://github.com/AzuraCast/nowplaying/blob/master/src/Adapter/Icecast.php#L11

And the default one is used to get now playing statistics:
https://github.com/AzuraCast/AzuraCast/blob/ec9533db4f65a40e025918e341d2ab676e474e2b/src/Radio/Frontend/Icecast.php#L41

IceCast _does_ make this available but AzuraCast will basically have to query all mount points.

**Comment by SlvrEagle23** [comment]
@LordHelmchen666 @CodeSteele I can verify that this was an unintended side effect of moving the AzuraCast NowPlaying library to being its own standalone codebase: one of the necessary restrictions at that point was to require a single mount point be named in order to retrieve detailed information about that mount point in a way that was portable across the different radio frontends.

I've updated the AzuraCast-side code to properly aggregate statistics (including clients) between all of the available mount points for a station. This issue should be resolved if you update your installations.
