### ISSUE TITLE
Error Installing ShoutCast

### ISSUE THREAD

**Issue by reans** [AzuraCast/AzuraCast#834]
**Installation method**
"Traditional" installation method.

**Host OS (Traditional )**
Ubuntu 18.04

**Describe the bug**
I tried installing shoutcast via azucast panel by uploading the sc_serv2_linux_x64-latest.tar.gz which i got from shoutcast website but when i hit upload it shows File is invalid.

![image](https://user-images.githubusercontent.com/27730047/46493899-11658f80-c844-11e8-977e-bcbf7ea7b249.png)

![image](https://user-images.githubusercontent.com/27730047/46493934-2e01c780-c844-11e8-8d01-69d4af3b33f6.png)

what will i do to install this shoutcast binary?

any help is high appreciated 

thank you

**Comment by SlvrEagle23** [comment]
@reans What browser are you on?

**Comment by SlvrEagle23** [comment]
Update to @reans and anyone else updating their installation:

SHOUTcast has officially released version 2.6.0, the version that is split into "Freemium" and premium (monthly subscription) versions. The download from the SHOUTcast Radio Manager now downloads 2.6.0 instead of 2.5.5. This is the reason we have been rapidly in the process of removing support for SHOUTcast, as this new "freemium" offering has a more restrictive license and is fundamentally opposed to our principles of open and free software.

Please bear with us as we evaluate the new version to determine whether we can work with it in any capacity.

**Comment by reans** [comment]
thank you for the hard work @SlvrEagle23. always waiting for new update..

**Comment by SlvrEagle23** [comment]
@reans I've tested a copy of the newest SHOUTcast, and it appears to work just fine with AzuraCast. The authhash system, which you use to list your station on the public directory, only allows 128kbps MP3 served over HTTP without paying extra money, but that doesn't affect the AzuraCast instance itself.

So, this issue instead appears to be something to do with your browser and how it's uploading the file. What browser are you using?

**Comment by SlvrEagle23** [comment]
@reans I've expanded the supported MIME types that can be uploaded via the "Install SHOUTcast" page. Update and let me know if it's still a problem. If it is, please **let me know what browser you are using.**

**Comment by reans** [comment]
@SlvrEagle23 it is ok right now. I used firefox and eveything working good. thank you somuch.. more power to azuracast.
