### ISSUE TITLE
Question : Broadcasting

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#838]
Hello,
Currently my main radio is going through Shoutcast, if I change to Icecast I will delete the metadata of the mp3 ?

**Comment by SlvrEagle23** [comment]
@ckeurk Not at all. The only thing you will lose is your mount points, since Shoutcast and Icecast have different ways of handling mount points. You can just go back in and recreate your previous ones in Icecast.

None of your media, playlists, reports, requests, DJs, etc are affected by switching from Shoutcast to Icecast.
