### ISSUE TITLE
Icecast admin page is blank

### ISSUE THREAD

**Issue by suricloud** [AzuraCast/AzuraCast#846]
**Installation method**
Docker

**Host OS (for Docker installations)**
Centos 7

**Describe the bug**
Icecast admin page is blank

I have update to the latest  v0.9.0-2018.10 Beta • Docker • PHP 7.2 version
I connect my live streams trough icecast wit butt stream app.
The administration url isnt working,just a blank page when i go to the link like:
https://my.radio.com/radio/8060/admin.html

**Comment by LordHelmchen666** [comment]
Can confirm this behaviour.
http://my.radio.com:8060/admin.html works for me. Maybe a redirect problem with nginx?

**Comment by CodeSteele** [comment]
The problem comes from the fact that Icecast doesn't _technically_ fully support being behind a reverse proxy.

These admin pages are hard-coded HTML pages, so nothing we can patch Icecast to dynamically change the URLs for (at least not without a ton of work).

Still going to see if there is anything we can do to rewrite the URLs in a reasonable way.

**Comment by CodeSteele** [comment]
Probably have a fix for Icecast, PR is out for review, once that gets pulled in updating Icecast should fix it.
