### ISSUE TITLE
API exposed to public by default

### ISSUE THREAD

**Issue by MyTheValentinus** [AzuraCast/AzuraCast#848]
**Installation method**
Docker install

**Describe the bug**
By default some API calls are exposed to public. API send sensitive data like server params:
icecast/shoutcast, liquidsoap, all mounts points, listeners count, song internal details. For `/api/nowplaying`
Request songs call too

I thinks solution is to limite api access to specific ip lists (whitelist)

**Comment by MyTheValentinus** [comment]
To temporary patch this, i have edit my nginx configuratioon and block /api to world and allow administrators IP.

**Comment by CodeSteele** [comment]
Hmm I guess there is a larger question as to what is considered "sensitive", normally this is all okay to be public information (and it is used by players to populate metadata showing the now playing information), and quite a bit of it can be derived from any web player connecting. Is there a reason you consider any of this to be sensitive?

**Comment by MyTheValentinus** [comment]
Hello @CodeSteele,
I think that's not information to be revealed to the public. If you publish your listeners count, any people would be able to create stats. Another example, if CVE will be released in icecast attackers have possibilities to determine directly that the radio use icecast
That is some examples

**Comment by CodeSteele** [comment]
> If you publish your listeners count, any people would be able to create stats.

Yeah I had kind of pondered if this kind of information disclosure was a big deal, it's about the best you can do with that data is track a station's popularity.

> Another example, if CVE will be released in icecast attackers have possibilities to determine directly that the radio use icecast

The Icecast server also responds with `Server: IceCast 2.4.2` in the headers, so you need to block all direct access to Icecast (Azuracast supports proxing pretty much everything) to not be _painfully_ easy to scan.

---

You can also pull both of these directly from Icecast from `/radio/8000/index.html` which is public. You do need access to `/radio/8000/(mountpoint)` though for people to listen to streams from Icecast too so it's not like we can just block the entire path (plus those paths are managed by Nginx, not AzuraCast).

I'll see about discussing with @SlvrEagle23 later about any _additional_ holes and practicality of basically trying to _hide_ Icecast behind AzuraCast.

**Comment by SlvrEagle23** [comment]
@MyTheValentinus @CodeSteele I have a few thoughts on this, but to summarize, I frankly don't think the AzuraCast API's public endpoints are exposing anything that is of any legitimate security concern for any of our station operators.

For one, if you're hitting the AzuraCast API, then you're already aware that you're connecting to a server that uses AzuraCast. It's then entirely possible to assume (since the only backend software we use is Liquidsoap) that you're using Liquidsoap under the hood. The API doesn't return the internal ports used for command handling or DJ/streamer input. Granted, you could extrapolate this from the actual stream's port number (as it's usually xxx5 and xxx6 of the same port), but this is no different from running a stock Icecast server, and is in fact better, since the stock Icecast server's connections are accepted directly on the broadcasting port, so there's no guesswork required. Authentication of DJs handles any spurious DJ input.

Second, both SHOUTcast and Icecast expose their own public metadata pages, and we do not attempt to suppress this, because this metadata is well established as being safe information the public can have. If your stream URL is `mysite:8000`, just visiting `mysite:8000/status-json.xsl` would indicate both whether you're using Icecast or not and would also return very significant metadata to what we're returning. Just like Icecast and SHOUTcast, listener-specific information like IP address and User Agent aren't available via our APIs without authentication.

The reason we include the backend and frontend in our statistics is expressly for the purpose of _allowing_ third-party applications that want to interface with AzuraCast to know everything they need to know about the station to do their jobs, without releasing any private information about the station. For example, if a third-party software wanted to directly ping the frontend for some specific metric, it could either just try to hammer away at both SHOUTcast and Icecast endpoints and use whichever one works, or it could reference the value in the API and not have to waste traffic doing that.

With regard to listener count, I strongly maintain that this is public information (and the frontend software agrees). I have seen many stations develop an unhealthy obsession over their listener numbers, making attempts to artificially inflate the numbers to the public or obscure them altogether. In my opinion, it is not the radio software's job to address what is fundamentally an insecurity in the station operator's mind. YouTube, Twitch, and countless other streaming services do not obscure viewership or current live listener totals, and neither do we.

AzuraCast is an extension of my own personal belief that tools and information should be as freely accessible to the public as possible. AzuraCast's API carries on that mentality and tries to be as transparent and forthcoming about its stations as possible, so that it "plays well" with any possible third-party software.

With regard to the question of whether this is a security issue, it absolutely is not, and I'm closing this issue and referencing it any time this comes up in the future.

With regard to the personal preference of hiding this information, I would strongly recommend looking at AzuraCast's new [plugin architecture](https://github.com/AzuraCast/example-plugin), as it already has event hooks for the Now Playing process that will let you manipulate that data however you see fit.

**Comment by MyTheValentinus** [comment]
Hello @SlvrEagle23,
Thanks for this amazing reply.
I understand all what you say, and i'm happy to ear that the new plugin architecture is able to modify this hook to match possibly stations data privacy.
Thanks
