### ISSUE TITLE
Requesting a song via API without knowing the Song ID

### ISSUE THREAD

**Issue by NeddyPlays** [AzuraCast/AzuraCast#856]
Hi,

Is there something possible to request a song via API without needing to know the Song ID. So for example somebody requests a song while the AutoDJ is on it sent the request to AzuraCast and finds/plays the closed song that comes to what the person put into the request.

**Comment by JDBlackman** [comment]
From the API you can get a list of songs with there ID's. 

/station/{station_id}/requests

**Comment by SlvrEagle23** [comment]
@NeddyPlays You can append `?searchPhrase=(phrase)` to the main requests API endpoint in order to search for the specified term. You could then show the results to the user or presumably just submit the first item that is returned from this URL:

http://your-azuracast-instance/api/station/(station_id)/requests?searchPhrase=(query)
