### ISSUE TITLE
Access Files via SFTP 

### ISSUE THREAD

**Issue by ckeurk** [AzuraCast/AzuraCast#857]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 18.04

I can no longer connect in SFTP mode, is it possible to do a complete reset ?

Thank you

**Comment by SlvrEagle23** [comment]
@ckeurk What do you mean? Your SFTP docker container may have stopped, but you can just run the same SFTP command again to create and run a new one. No reset required.

**Comment by ErnestPH** [comment]
It still works but there's a bug I found…

When changing the password, it works. 
But when changing the username, azuracast - you can still connect but here's the bug

BUG:
You can't see anymore your station under /stations - meaning /stations is empty

**Comment by SlvrEagle23** [comment]
@ErnestPH I don't believe that's a bug; the `azuracast` username is also the default owner of all files inside the stations directory, and it may be important that this username and the one listed as the file owner by the Linux filesystem be the same.

**Comment by ErnestPH** [comment]
Yes, thank you. I get it now.

**Comment by br0kenlink** [comment]
HI,
I tried to use SFTP connection to upload files. While it worked just fine with the command from your WIKI.
Every mp3 file i tried to upload to the station has been denied due to Denied Access.
I have used exact command you shown and no go. Tried to upload from same host and from different one. Both got same Access Denied on any file in any station.
Help would be appreciated

**Comment by SlvrEagle23** [comment]
@CodeSteele Yep, that's my mistake. The UID for the `azuracast` user is 1000 and it should be matching that.

**Comment by StrangeWill** [comment]
@br0kenlink if you open another shell you can run `docker ps` to get the docker instance ID then `docker stop [instance id]` to stop it.
