### ISSUE TITLE
Display "Now playing " Metadata in external Player

### ISSUE THREAD

**Issue by macbroadcast** [AzuraCast/AzuraCast#863]
Hello,
First of all, i like to say, I love this project and even if I was a bit confused about the playlists in the beginning, everything runs smoothly since 4 weeks on a traditional installation on ubuntu 18.04 Droplet on DO, beside a little thing that bothers me extremely. I am using a wp-theme with a built-in radio player, this player needs the Icecast metadata to display the current artist, song and such information, the recommended solutions at [http://www.qantumthemes.com/manuals/onair2/knowledge-base/9-0-radio-player/](http://www.qantumthemes.com/manuals/onair2/knowledge-base/9-0-radio-player/) using Icecast integration, to provide the meta information for example: 
[https://stream.bayrad.io/api/nowplaying/1](https://stream.bayrad.io/api/nowplaying/1)
My goal would be to display this information in our web-player.

**Comment by SlvrEagle23** [comment]
@macbroadcast Since this is maybe the third or fourth issue I've seen related to this one specific Wordpress plugin, I'll be entirely honest with you here: it's not the responsibility of AzuraCast's developer to add compatibility for our software or API to third party commercial theme software. It's theirs.

Considering they're apparently charging $60 per site license of this Wordpress theme, it's clear that they've probably made more money in the last week than AzuraCast has made in its entire lifetime as a software product.

Since they are the software you paid for and we aren't, you should be petitioning them to add support for AzuraCast's [well-documented API](https://www.azuracast.com/api/index.html) to the theme you paid for. Adopting the theme to support AzuraCast's API should be remarkably simple.

If you would like me to assist in adding this support to the OnAir Wordpress theme, I'd be happy to assist as an independent contractor; however, this is not at all within the scope of the free support I provide for AzuraCast.

**Comment by BartManX** [comment]
> @macbroadcast Since this is maybe the third or fourth issue I've seen related to this one specific Wordpress plugin, I'll be entirely honest with you here: it's not the responsibility of AzuraCast's developer to add compatibility for our software or API to third party commercial theme software. It's theirs.
> 
> Considering they're apparently charging $60 per site license of this Wordpress theme, it's clear that they've probably made more money in the last week than AzuraCast has made in its entire lifetime as a software product.
> 
> Since they are the software you paid for and we aren't, you should be petitioning them to add support for AzuraCast's [well-documented API](https://www.azuracast.com/api/index.html) to the theme you paid for. Adopting the theme to support AzuraCast's API should be remarkably simple.
> 
> If you would like me to assist in adding this support to the OnAir Wordpress theme, I'd be happy to assist as an independent contractor; however, this is not at all within the scope of the free support I provide for AzuraCast.

i agree that it is not the responsibility of the developer .. but maybe point our way to some tutorials that give details on API usage and how to include them in a site ..  ive googled .. ive looked at the [well-documented API] .. im kinda stuck...  ive got the HTML version of that wordpress theme and i can add stream ip and port but i would rather use the API .. if i could figure out how to code it to the page

**Comment by macbroadcast** [comment]
Well  figured it out https://iradio.guru  :+1:

**Comment by Vaalyn** [comment]
@BartManX Our API documentation is done with one of the most popular and easy to use API documentation tools, Swagger. In this documentation everything that is needed to use the API is shown. All you need to know in order to use the API on your own website or application would be how to code AJAX calls in JavaScript, which is a very basic thing that is taught in nearly every "learn JavaScript" tutorial, or how to make requests to URLs in the language you are using for your application. There is nothing special about the AzuraCast API in regards to how to use it. If you are not comfortable enough with programming languages like JS or PHP to do this yourself then you are better off paying a developer to do this for you, learn how to do these things in general or use the player embed code we already provide.

**Comment by kikoto79** [comment]
macbroadcast Can you describe a little in detail about your solution to the problem. I also have a similar problem? I use Icecast V2 and wordpress them onair2.

**Comment by macbroadcast** [comment]
@kikoto79 I posted my solution above , but there is a onair2 support forum https://www.qantumthemes.com/helpdesk/forums/forum/onair2-theme-support/

**Comment by kikoto79** [comment]
To know this forum I am registered.Maintenance does not work in the right direction and there is no real solution.
