### ISSUE TITLE
Question: How to set the default volume to 100% in iFrames

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#870]
This could be a newbie question but I tried researching already and found none.

How can we add a default 100% volume for iframe codes? Currently, it's not 100%

**Comment by ErnestPH** [comment]
Can I modify the files for my server installation? So that the volume is 100%? If yes, where is it located? :) Thanks!

**Comment by ErnestPH** [comment]
Can I just try it on my end? For changes in the updates…  I will just backup the specific file. If that's ok… Should I create this as an enhancement? Thank you very much!

**Comment by ErnestPH** [comment]
Just in case, for someone like me who wants loud music by default, we can customize the default sound by editing radio-bf97216194.js. 

change volume to volume=100 from volume=55.

after every update, you can just edit it back manually

**Comment by SlvrEagle23** [comment]
@ErnestPH Editing the compiled static assets is **especially** not recommended, as every time our system rebuilds the assets, it does so under a new name for the purposes of "cache busting" the browser cache.

For the sake of avoiding what is a very dirty fix to your AzuraCast installation, I've implemented official support for the `?volume=[0-100]` query parameter. If you specify this on any page with a player, it will override the default volume.

If anyone is reading this issue later on, please know that I don't _ever_ encourage the "just overwrite this file and then reapply it after every update" method of updating AzuraCast. We have early support for plugins, custom JS and CSS support for public pages, and most importantly, any contributions that may be of value to everyone should be submitted as Pull Requests. The goal here is to have as many people on "stock" AzuraCast as possible, so that updates that include bug fixes, security updates and new features can be applied without any problems.
