### ISSUE TITLE
After updating, the scroll bar is now visible and dark

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#875]
Is there a way, that the song request can back as it was before?

http://www.radioscristianas.com

It was much better…

Thanks!
ErnestPH

**Comment by ErnestPH** [comment]
The transparent background for the embedded web player by the way is not working anymore...

**Comment by ErnestPH** [comment]
Hi SlvrEagle23,

Is this because of the update? Some of us really likes the transparency feature. Hope it will be back. Thanks!

ErnestPH

**Comment by SlvrEagle23** [comment]
@ErnestPH Losing transparency on the embed mode is a bug from the new theme that I'm looking into fixing. I've been busy over the last few days but I definitely plan to get back to it.

**Comment by ErnestPH** [comment]
I see. no rush. You've been great. thanks!

**Comment by ErnestPH** [comment]
I believe the player is ok. Sorry for the misrepresentation. I am talking about the song request embed [](https://prnt.sc/la5a0o)

**Comment by SlvrEagle23** [comment]
@ErnestPH I updated the table striping backgrounds to be alpha-transparent based just as they were in the previous theme, in order to work better with embedded pages. This should help resolve the issue you're seeing.

**Comment by ErnestPH** [comment]
> @ErnestPH I updated the table striping backgrounds to be alpha-transparent based just as they were in the previous theme, in order to work better with embedded pages. This should help resolve the issue you're seeing.

Thank you, you are the best! but you forgot something. The pagination below and the dropdown settings beside the search field is still not tranparent. :) [https://prnt.sc/la71il](url)

**Comment by ErnestPH** [comment]
Hi SlvrEagle23

Is there a way to restore a previous version? so I can still retain the old theme? Thanks!

Just thinking…

ErnestPH

**Comment by SlvrEagle23** [comment]
@ErnestPH I would strongly recommend against it, because the updates include not only bug fixes but feature additions and other enhancements. Throwing all that out the window for the sake of having the theme look a little better on one single page out of the entire application seems shortsighted at best.

If you're so concerned with the way the embedded page looks, you can do one of a few things:

1) Copy the code used in AzuraCast's embed requests page and load it directly onto your own site, which will let you fully customize the stylesheet associated with it,

2) Take advantage of AzuraCast's "custom branding" feature and apply custom CSS for the embed page that restyles things to look how you want them to, or

3) Directly fork the AzuraCast codebase, make the necessary changes to the underlying SCSS and actually contribute those changes back via Pull Request to the project itself.

I don't consider this a high enough priority to continue spending many hours on it myself, especially since it appears the version of AzuraCast you're running on is resold to users at a profit. While you are free to host AzuraCast commercially, you should not insist upon me doing large amounts of development for free without contributing back in either code or monetary form.

**Comment by ErnestPH** [comment]
I fully understand your point. Thanks. consider this as case closed :)

**Comment by ErnestPH** [comment]
How could I not research it myself. Once again thank you for this and I apology on keeping on asking when I can just do it :)

I did custom branding just in case someone like's full transparent…. here's the css code

> .pagination {
    background-color: #392d3305 !important;
}
.btn-group, .btn-group-vertical {
    background-color: #392d3305 !important;
}
