### ISSUE TITLE
Don't Pipe Docker Install to Shell

### ISSUE THREAD

**Issue by CodeSteele** [AzuraCast/AzuraCast#888]
Our install process does a lot of: `wget -qO- https://get.docker.com/ | sh`

When we should probably be doing some of this: https://docs.docker.com/install/linux/docker-ce/ubuntu/ (signed, can't be MITM'd by TLS gateways companies run, more secure, etc.)

**Comment by SlvrEagle23** [comment]
@CodeSteele It's more secure to do it that way, no doubt, but that script is meant to run on just about any environment you can imagine. Docker's installer script will do that out of the box.

I'm not sure that there's a verifiable way of replicating that short of actually lifting the entire script and putting it as a dependency.

Then again...do we gain any security by telling people to pull that installer script from us rather than Docker, when _our own_ Docker utility script is a curl get operation from Github?

**Comment by CodeSteele** [comment]
> when our own Docker utility script is a curl get operation from Github

Yeah I was wondering how deep _that_ rabbit hole goes.

**Comment by CodeSteele** [comment]
Discussed it briefly with @SlvrEagle23 about how basically adding a ton of support around distro discovery is out-of-scope for our project and a lot more overhead for something that Docker themselves push as a valid install method.

So a small security improvement but likely not worth the additional effort with our limited resources.
