### ISSUE TITLE
Just a question - How to check what version of Azuracast is installed

### ISSUE THREAD

**Issue by ErnestPH** [AzuraCast/AzuraCast#909]
Hi Guys,

This good be a dumb question but I haven't seen any document for it.
How can we check, what version is the installed Azuracast in my instance?
Additionally, can you provide a link of the latest Azuracast documentation that states the latest version?

Thanks!
ErnestPH

**Comment by RemBdev** [comment]
In the bottom of your webportal you can see a versionnumber.
![image](https://user-images.githubusercontent.com/29834979/47708815-3674d480-dc2f-11e8-9505-4e7a48717cb2.png)

**Comment by ErnestPH** [comment]
Thank you! How could I overlooked it :)

**Comment by SlvrEagle23** [comment]
@ErnestPH AzuraCast is on a "rolling release" schedule, which currently means most people are following the master branch directly for updates. While users should be always using the most up-to-date installation possible, the version numbers for AzuraCast only change periodically, mostly as an indicator of large functionality changes.

The next release will be 0.9.1 and it will be tagged soon on account of the addition of several new features and bug fixes since 0.9.0's release.

Currently there is no way to tell exactly which commit version you're on short of just updating.

**Comment by ErnestPH** [comment]
ok thanks! completely understood

**Comment by CodeSteele** [comment]
@SlvrEagle23 question -- how hard would it be to append the hash of the deployment to the version or something? It'll allow us to pin exact commits for rolling releases (or in the future if we move away from them -- if someone is running a dev copy which commit they're on).

**Comment by SlvrEagle23** [comment]
@CodeSteele This will need to be a thing before we can do any sort of accurate version analytics. Will reopen and upgrade this to enhancement to get a fully accurate hashed version (and corresponding commit date) stored in the filesystem somewhere along with each update.

**Comment by CodeSteele** [comment]
Versions are now reported as `Powered by AzuraCast • v0.9.0-2018.10, #027d571 (2018-11-02 5:25) • Docker • PHP 7.2`, handy for rolling releases.

**Comment by ErnestPH** [comment]
Thanks guys for the dedication!
