### ISSUE TITLE
The songs are repeated too many close

### ISSUE THREAD

**Issue by Ilario42** [AzuraCast/AzuraCast#912]
Traditional

Hi, I noticed that the songs in this new version are repeated too recently. I've loaded 300 songs, and he's always going to put the same songs next to me. In the old version it was not like that.

Why?

![image](https://user-images.githubusercontent.com/22561729/47803493-eb43ea00-dd32-11e8-9f9a-656419245339.png)

**Comment by SlvrEagle23** [comment]
I feel like I need a canned response specifically for the "songs are played too close to one another" issue, as it's probably been created 15 separate times at this point.

@Ilario42 This issue is immensely hard to diagnose. In order to even begin to fix it, I basically need to know everything about your installation: I need to be able to see your playback logs, to examine your playlists and how they're weighted, and to see how your AutoDJ is handling shuffling.

If you're okay with me taking a look at your AzuraCast installation itself, let me know at help@azuracast.com . Otherwise, there likely isn't much I can do to resolve the issue.

**Comment by afonsosantos** [comment]
Installation method: Docker (Ubuntu Server 18.04 VM)
I'm having the same trouble now. Can you please help me? I can give access to my AzuraCast server if you need it.

Thanks!
