### ISSUE TITLE
Bulk Adding Songs To Playlist Is Database Intensive

### ISSUE THREAD

**Issue by CodeSteele** [AzuraCast/AzuraCast#919]
While trying to add some 1500+ songs to my default playlist I watched MariaDB bury a core and add maybe 3-5 songs a second. It also appears that between that and cron jobs, a query will eventually exceed the maximum execution time of 30 seconds.

If I had to wager a _guess_ without looking at it, the system is adding each song independently and re-generating the playlist with every song.

Ideally for multi-select we should do it all in one pass.

**Comment by CodeSteele** [comment]
-- This may be a docker4win issue...

**Comment by Vaalyn** [comment]
I had the same problem with the docker install on a Debian 9. Tried it with ~2-3k songs and also got some max execution timeouts after ~30s. One part of the problem was the reshuffling of the playlist where each song of the playlist was updated for each new addition to the playlist. This was fixed in PR #902. I tried adding 2336 songs to an empty general rotation playlist right now and it took around 15s to complete. To test if it makes any difference I moved the shuffling to after all songs were added to the playlist and before a new .pls is generated but that didn't have any noticeable impact.

Are you using the newest version of AzuraCast?

You mentioned that it could be a problem with docker on windows. This could be true. Last year I had some performance issues with symfony in a docker container that was originating from the overhead that translation of the different filesystem operations had/have when using docker for mac. Maybe this is also a problem in docker for windows.

**Comment by SlvrEagle23** [comment]
@CodeSteele @Vaalyn After looking through the way batch transactions are handled, I think it's likely that Docker for Windows is just demonstrating the problem more clearly since it already has a bit of a performance deficit and is running in limited confines on a host computer.

I've reworked how batch uploads to playlists work altogether so that not only will reshuffling only take place once, after all batch operations are completed, but the entity manager will smartly write all batch operations in one single push, further helping performance. I also fixed an unrelated issue where deleting a non-processed file could incur a delay of the time it takes to actually process it.
