### ISSUE TITLE
 Stream Disconnecting

### ISSUE THREAD

**Issue by JMultimidia** [AzuraCast/AzuraCast#922]
**Installation method**
"Docker" and "Traditional"

**Host OS (for Docker installations)**
Ubuntu 18.04 and Docker.

When I install azura on the latest version I have problems. The encoder starts and after 3 seconds it disconnects. The problem happens in traditional mode and also with docker.
I've already tried Digital Ocean and Vultr and Google Cloud and even with the firewall turned off I can not succeed.

The version I used on another server was commit bbde33cd1b7346dc086c963387b63a481f22dbf7. Is it possible to install a version from git using the old version? 
![capturar](https://user-images.githubusercontent.com/20319612/47957092-b3d17980-df8e-11e8-88bc-f5e099dd79ce.PNG)
![capturar2](https://user-images.githubusercontent.com/20319612/47957093-b46a1000-df8e-11e8-847c-1a66375dcb6e.PNG)
![capturar3](https://user-images.githubusercontent.com/20319612/47957094-b46a1000-df8e-11e8-99a1-f75090143d33.PNG)

**Comment by Vaalyn** [comment]
To be able to diagnose why the disconnects happen we need to see if there are specific error messages in the logs. Could you post any errors that you find for the time where this happens? You can find the log viewer in `Utilities`.

Additionally to the server logs please take a look at the `Event Log` window of SAM and check if there are any error messages that could be helpful.

**Comment by JMultimidia** [comment]
LOG:

2018-11-03 21:07:31	INFO	[MAIN] SHOUTcast DNAS/posix(linux x64) v2.6.0.747 (Oct 31 2018)
2018-11-03 21:07:31	INFO	[MAIN] PID: 4076
2018-11-03 21:07:31	INFO	[MAIN] Saving log output to `/var/azuracast/stations/floresta/config/sc_serv.log'
2018-11-03 21:07:31	INFO	[MAIN] Automatic log rotation interval: 1 day
2018-11-03 21:07:31	INFO	[MAIN] Loaded config from `/var/azuracast/stations/floresta/config/sc_serv.conf'
2018-11-03 21:07:31	INFO	[MAIN] Calculated CPU count is 2 -> using all available CPUs
2018-11-03 21:07:31	INFO	[MAIN] Limited to 1024 file descriptors [relates to ulimit -n]
2018-11-03 21:07:31	DEBUG	ident is DIDCf8a89f28eaab4c7cb15fa059e8702e0d-8042, DID is 8c243c3f6fb575f529556c1dae35756a06c46a3c67b615c4785ab59b02fa28f
2018-11-03 21:07:31	INFO	[MAIN] Starting 2 network threads
2018-11-03 21:07:31	INFO	[MICROSERVER] Listening for source and client connections on port 8042
2018-11-03 21:07:31	INFO	[MICROSERVER] Listening for legacy source connections on port 8043
2018-11-03 21:07:31	INFO	[MICROSERVER] Flash policy file server not enabled
2018-11-03 21:07:44	INFO	[SRC 201.20.75.130:53818] SHOUTcast 2 source connection starting.
2018-11-03 21:07:47	ERROR	[SRC 201.20.75.130:53818 sid=1] SHOUTcast 2 source disconnected. Unable to sync to the stream. Please check the source is valid and in a supported format.
2018-11-03 21:07:48	INFO	[SRC 201.20.75.130:53357] SHOUTcast 2 source connection starting.
2018-11-03 21:07:51	ERROR	[SRC 201.20.75.130:53357 sid=1] SHOUTcast 2 source disconnected. Unable to sync to the stream. Please check the source is valid and in a supported format.

**Comment by Vaalyn** [comment]
This looks like an incompatibility between what SAM is sending to the server and what the server expects as valid source format. What settings are you using for SAM and for your station?

**Comment by SlvrEagle23** [comment]
@JMultimidia In order to understand what's happening here, I think it's important to understand the chain that AzuraCast uses by default when streamers connect.

Simplified, the chain basically looks like:

```
Radio
  v
Liquidsoap <-- Streamer
  v
Icecast/SHOUTcast
```

There are a number of reasons for this:
 - Liquidsoap can call AzuraCast to authenticate DJs in a way that neither Icecast nor SHOUTcast can, allowing for greater control
 - Liquidsoap can then take the signal from the streamer, regardless of what format it's in, and transcode it directly into the various formats used by your mountpoints
 - Streamers can broadcast both to your local stations and remote stations from the same connection
 - The AutoDJ will automatically and seamlessly resume when the DJ disconnects

However, because you're connecting to Liquidsoap and not the actual Icecast/SHOUTcast server, you need to make sure you're broadcasting in a format that Liquidsoap itself can _decode_ properly.

To my knowledge, the two formats it handles best are MP3 and OGG Vorbis. While I know it can encode AAC in order to deliver a signal to SHOUTcast, I'm not confident in its ability to decode that signal.

In this case, it means you should switch formats to MP3 or OGG Vorbis. Unfortunately, this means that no matter what you do, there will be some transcoding taking place between your stream and the listeners; in order to mitigate this, I'd recommend broadcasting at the highest possible bitrate (provided your songs themselves are also that quality) to give the most "overhead" for possible quality loss during the transcoding process.

While AAC+ is an option on AzuraCast, this was only due to popular pressure from users. Our primary preferred formats across the system are MP3 and Ogg.

**Comment by JMultimidia** [comment]
I'm not using auto dj. Broadcast is live. I already own applications by touching the aac + of the azura that runs on another server (with an older version in traditional mode). I need to migrate to a new server and I noticed that in this recent version this problem has arisen.

**Comment by SlvrEagle23** [comment]
@JMultimidia Even if you're not using the AutoDJ, if you're broadcasting following AzuraCast's instructions, then you're connecting to Liquidsoap, not to SHOUTcast itself directly.

If you're connecting to SHOUTcast directly and you're having this problem, then that's likely to do with the newest version of their software (which introduced a "freemium" concept where only 128kbps MP3 is supported for free). That's upstream to them and is absolutely their fault, and I encourage you to yell at them very loudly about it.

**Comment by JMultimidia** [comment]
Can not install from a previous commit? I have on another server, I would like to use the same configuration on the new server, but unfortunately I do not use docker.

**Comment by Vaalyn** [comment]
> I'm not using auto dj. Broadcast is live. I already own applications by touching the aac + of the azura that runs on another server (with an older version in traditional mode). I need to migrate to a new server and I noticed that in this recent version this problem has arisen.

So you have a server where AzuraCast is installed via the traditional installation and there the streaming to the server in AAC+ with the settings you posted works, correct?

What credentials are you using to stream? The ones for the streaming server (IceCast or SHOUTcast) itself or are you using the `Stream User` credentials?

Which streaming server is installed on both servers?

Have you manually changed or added to the AzuraCast on the server where is works?

**Comment by SlvrEagle23** [comment]
@JMultimidia Did you download a new version of the SHOUTcast binary?

AzuraCast no longer ships with SHOUTcast preinstalled due to their licensing terms.

You can always try to go hunt down an older version of the binary out on the web somewhere, and it may work for you. We just can't officially do that.

**Comment by JMultimidia** [comment]
Yeah, I downloaded the torque. What is the oldest version you suggest for me to search the web?

**Comment by SlvrEagle23** [comment]
@JMultimidia Version 2.5.5 is the latest version that doesn't have the Freemium stuff.

**Comment by JMultimidia** [comment]
Thank You.

**Comment by JMultimidia** [comment]
Solved. Installing version 2.5.5 works perfect.
