### ISSUE TITLE
[TUTORIAL] Automated installation using StackScripts on Linode instances

### ISSUE THREAD

**Issue by lamasbr** [AzuraCast/AzuraCast#925]
Hello everyone!

I've made two StackScripts to automate AzuraCast installation on Linode instances:

- Docker Installation: [https://www.linode.com/stackscripts/view/352549](https://www.linode.com/stackscripts/view/352549)
- Traditional Installation: [https://www.linode.com/stackscripts/view/352555](https://www.linode.com/stackscripts/view/352555)

To use these StackScripts, you need to access your [cloud manager](https://cloud.linode.com/stackscripts), search for 'azura' on Community StackScripts tab and click on the option "Deploy New Linode".

@SlvrEagle23 
I do not know if here was the best place to post this but I couldn't find another more appropriate. If I made a mistake, I apologize and ask you to close or delete it.

**Comment by CodeSteele** [comment]
Awesome, at first guess we'll probably stick this in our install docs. Really appreciate more tooling to help making install AzuraCast even easier!

**Comment by SlvrEagle23** [comment]
@lamasbr Thank you for your contribution, and for maintaining these scripts for our Linode users!

I've directly integrated your scripts into our installation instructions on [azuracast.com](https://www.azuracast.com/install.html) to direct people to your StackScripts.

**Comment by ErnestPH** [comment]
As of today, it has a 404 error. Wondering why...

**Comment by SlvrEagle23** [comment]
@ErnestPH Just updated our documentation to reflect changes in Linode's web site architecture. Rather than directly linking to StackScripts from externally, they're now selectable from directly within the cloud management panel, so we've updated our instructions to guide users through that process.

Like we do with DigitalOcean, we'll reach out to Linode to see if they're interested in working with us to set up a one-click application installer for AzuraCast.
