### ISSUE TITLE
Timezone for Brazil + Daylight Savings Time option

### ISSUE THREAD

**Issue by rmacari** [AzuraCast/AzuraCast#937]
Hello,

I'm having some issues trying to adjust the system timezone to our local time, since any major city in Brazil isn't listed, but i was able to setup using Buenos Aires and at first everything was ok, but now Brazil is using DST and i don't any option to tell AzuraCast that the time should be corrected to the new time in effect because of the daylight savings time. 

My request is:
Can you please add timezones to Brazil? We have 3 different timezones (North Region, Northeast and the rest of the country, usually is: Manaus, Salvador and Sao Paulo.

And also add the DST option so the scheduled playlists don't  air in the wrong time.

Appreciate it. 
Thanks!

**Comment by CodeSteele** [comment]
Yeah, I'm not _exactly_ sure why we're not just pulling timezones from PHP's internal list, will have to check in on that.

**Comment by xewl** [comment]
> Yeah, I'm not _exactly_ sure why we're not just pulling timezones from PHP's internal list, will have to check in on that.

Well, I tried (see pull request on the `azuracore` repo)
Basically, it's a hack, where a clean static array would be more sufficient.

**Comment by SlvrEagle23** [comment]
@CodeSteele Long story short, PHP's internal list includes something like 15 Antarctica time zones and removes some of the most commonly used ones, like "US/Central", "US/Eastern", etc.

The curated list is far, far shorter while representing the same time zones. If we're missing a time zone that is genuinely different from one of the ones already listed, we can always add it.

**Comment by SlvrEagle23** [comment]
I've reviewed the issue further and adopted a change to the AzuraCore that's very similar to the contribution made by @xewl, except with some time zones removed (Antarctica, namely) and rearranged and the display switched up a bit.

There's one minor issue that people will need to be aware of: if you have previously set a time zone that was an alias of another (i.e. "US/Central" is just an alias for "America/Chicago"), it will continue to work across the system, but when you go to edit your profile again, it will be reset to UTC, as that alias doesn't exist in the system. There isn't much we can do about this, since if you set your time zone to "US/Central", PHP doesn't return that you're in "America/Chicago", so there's no way to resolve that alias easily.
