### ISSUE TITLE
Crowd Sourced Streaming Software Support

### ISSUE THREAD

**Issue by CodeSteele** [AzuraCast/AzuraCast#943]
Have someone looking at using MB Recaster, another freeware option (#942).

What would be nice is having a crowd sourced list of a _ton_ of software options, that people have tested over the years. So we're not just installing everything ourselves and making sure it works.

Mostly would include a markdown file about how to contribute details to the project on this, some kind of basic sign-off.

**Comment by br0kenlink** [comment]
That is a good idea, sir

**Comment by SlvrEagle23** [comment]
Unfortunately, the GitHub wiki doesn't allow pull requests from the public despite this being a years-long feature request. :( Not to worry, though, I have a solution!

Earlier today I moved the documentation back to the azuracast.com repo so that its build process wouldn't trigger update notifications for AzuraCast installation owners (and so that we could put other Markdown files in there that can be pull-requested), and I've just moved the existing two items that were in the AzuraCast wiki over to this repo:

- [Streaming Software](https://github.com/AzuraCast/azuracast.com/blob/master/StreamingSoftware.md)
- [Advanced Playlists](https://github.com/AzuraCast/azuracast.com/blob/master/AdvancedPlaylists.md)

You can now submit pull-requests to directly modify these documents.

**Comment by CodeSteele** [comment]
I'm reopening this because I'd like to lay out instructions on testing other software.

**Comment by SlvrEagle23** [comment]
@CodeSteele This issue requires your follow-up when you get a chance.
