### ISSUE TITLE
Cronjobs not responding

### ISSUE THREAD

**Issue by NLLucifer** [AzuraCast/AzuraCast#945]
**Installation method**
Docker

**Host OS (for Docker installations)**
Ubuntu 16.04

**Describe the bug**
Appearently after a fresh docker instal the cronjobs doesn't seem to work. 
Also told me the last time they did run was +500 days ago. After manually starting them, they still don't work.
This also means the now-playing status isn't updating.

**Expected behavior**
Make them run 

**Screenshot**
![image](https://user-images.githubusercontent.com/37590500/48372123-f34e4300-e6bd-11e8-941c-ae1efbdf2f31.png)

**Logs**

> {"job":{"command":"php /var/azuracast/www/util/cli.php sync:run nowplaying","name":"NowPlayingSync","status":"Good","time":"*/15 * * * * *"},"startTime":1542054090,"stderr":"\n
>In AbstractMySQLDriver.php line 113:\n
>
>An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user ''@'*IP*' (using password: NO)
>In PDOConnection.php line 50: SQLSTATE[HY000] [1045] Access denied for user ''@'*IP*' (using password: NO)
>In PDOConnection.php line 46: SQLSTATE[HY000] [1045] Access denied for user ''@'*IP*' (using password: NO)
>sync:run [<task>] ","stdout":"Running Now-Playing (15-second) Sync...","succeeded":false,"user":"azuracast","version":"1.4"}

**Device(s):**
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Version: 70.0.3538.77

**Comment by SlvrEagle23** [comment]
@NLLucifer Definitely a valid issue, was caused by a mid-October change to how cron tasks were run in Docker containers. It largely went unnoticed because most Docker users also have a "station watcher" app running that triggers push notifications for song/listener changes and keeps the now playing data rolling along even if cron fails.

The updated web image has been built and should be ready to pull down immediately.

**Comment by NLLucifer** [comment]
Seems to have solved the problem! Thankyou!
