### ISSUE TITLE
External radio url

### ISSUE THREAD

**Issue by webma5ter23** [AzuraCast/AzuraCast#966]
What is the best way to program another radio? example put days and times where a remote url goes through the server.

I tried like you see in the picture but follow the music of the autodj.

![screenshot_2018-11-19 listas de reproduccion - azuracast](https://user-images.githubusercontent.com/41419364/48683006-c4d2db00-eb89-11e8-9a8e-5db7719c0d73.png)
![screenshot_2018-11-18 edit lista de reproduccion - azuracast](https://user-images.githubusercontent.com/41419364/48683011-cdc3ac80-eb89-11e8-99fd-3ee7f90248ff.png)

**Comment by macbroadcast** [comment]
Yes, i have the same problem, remote scheduled  playlist never gets triggered

**Comment by SlvrEagle23** [comment]
@webma5ter23 @macbroadcast This is definitely a valid bug report, and I suppose I should explain what happened under the hood here.

We had one particular installation earlier in AzuraCast's development who insisted that they'd only use the software if it could support playing back remote URLs. As long as Liquidsoap is in charge of playlists, this is fairly simple: just hand Liquidsoap a remote URL and it'll go fetch it and play it back locally.

However, in order to get richer metadata for songs (like how far along in their duration they were, what playlist they came from, etc.), we had to put AzuraCast in charge of the AutoDJ process. We recently added the "Manual AutoDJ" mode to take AzuraCast out of the process entirely and just let Liquidsoap do its thing, and when that mode was turned on, remote URL playlists worked without issue.

We didn't get around to actually implementing support for remote URLs in AzuraCast's internal AutoDJ until...about three minutes ago. :)

Along with implementing full support for remote URLs, I've also added support for remote playlist files (M3U/PLS).

Sorry for the confusion about the fact that this only worked with "Manual AutoDJ" turned on (and that this wasn't documented); my intention had been to come up with a fix for the issue sooner than this!
