### ISSUE TITLE
Port mapping in env file

### ISSUE THREAD

**Issue by TorchwoodPL** [AzuraCast/AzuraCast#968]
**Is your feature request related to a problem? Please describe.**
When I update AC I alvays need to re-edit docker-compose.yml to change mapping of ports.

**Describe the solution you'd like**
Add ports to azuracast.env

**Describe alternatives you've considered**
---

**Additional context**
---

**Comment by Vaalyn** [comment]
I think this would be easier and better doable via the [`extends`](https://docs.docker.com/compose/extends/#understand-the-extends-configuration) feature of docker-compose. That would mean that there would be a default docker-compose.yml with all the standard stuff and the setup could generate a custom docker-compose.yml that extends the default one so that this could be used to override/customize the services without having it overwritten everytime.

**Comment by SlvrEagle23** [comment]
@Vaalyn Sadly, the `extends` feature of Docker Compose files was phased out in version 3 (which we'll have to use to take advantage of Docker App and other future features), and there is still somewhat heated debate about what will replace it. I don't want to encourage its use until it's stabilized.

@TorchwoodPL The link that Vaalyn posted actually talks about another feature that Docker Compose has, one that I didn't even know about: by default, it will also look for and parse `docker-compose.override.yml` and use its values to override any of the ones specified in the main `docker-compose.yml` file. You can (and absolutely should) create that file and use it to modify things like port mappings. That will let your changes persist across updates to the AzuraCast core `docker-compose.yml` file.

**Comment by Vaalyn** [comment]
@SlvrEagle23 Thanks for correcting me. I didn't notice the note saying that `extends` is gone in v3.

The override feature via a docker-compose.override.yml looks exactly like what we should do when customizing the services. Maybe we should add a note about this feature to the AzuraCast documentation in a section about customizing the docker services.

**Comment by SlvrEagle23** [comment]
@Vaalyn Done and done. Updated the support documentation to recommend creating the override file instead of modifying the core one, thus avoiding conflicts when the updater script prompts you to replace the file.

Given this relatively painless solution to this problem, I'm marking this situation as resolved.

**Comment by SlvrEagle23** [comment]
One problem of note with this issue: `docker-compose.override.yml` cannot _remove_ existing port mappings, only add new ones. The new ones just slap right on top of the old ones, but the old ones stay in place and still try to map. This may be resolved by the long-standing (and recently revived) PR docker/compose#6213, if the Compose team can manage to merge it.

It looks like the current easiest way to do this will indeed be to make it an overridable environment variable with a sensible default value. Reopening to go this route instead.

**Comment by SlvrEagle23** [comment]
After looking into the issue further, it appears the current best solution to this issue is indeed to make the port mappings an environment variable so that it can be controlled without needing to modify the `docker-compose.yml` file directly.

As such, per the original request @TorchwoodPL, I have modified the file to use two new environment variables, `AZURACAST_HTTP_PORT` and `AZURACAST_HTTPS_PORT`. In `docker-compose.yml`, if these are unset or empty they will default to the previous values.

Unlike other environment variables, since this one affects Docker Compose itself, you should supply the custom values in `.env` instead of `azuracast.env`.

I have updated the [Support documentation](https://github.com/AzuraCast/AzuraCast/blob/master/SUPPORT.md#use-non-standard-ports) to reflect this updated recommendation.
