### ISSUE TITLE
LiquidSoap error

### ISSUE THREAD

**Issue by czmilosz** [AzuraCast/AzuraCast#970]
**Installation method**

Docker
**Host OS (for Docker installations)**

Ubuntu
**Describe the bug**

LiquidSoap not starting
**To Reproduce**

**Expected behavior**

**Relevant Logs**

web_1          | [19-Nov-2018 17:54:41] WARNING: [pool www] child 243 said into stderr: "[2018-11-19 11:54:41] AzuraCast.ERROR: NO_FILE: can't find command '/var/azuracast/.opam/system/bin/liquidsoap' {"file":"/var/azuracast/www/src/Radio/AdapterAbstract.php","line":185,"code":0} []"

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by SlvrEagle23** [comment]
@czmilosz This is the same issue as has been reported at least twice so far; this is caused by the code for AzuraCast not updating when the Docker containers do.

The easy solution is to run the following commands together:

```bash
./docker.sh update-self
./docker.sh update
```

As a general best practice, these commands should both be run for any future updates as well.
