### ISSUE TITLE
Move

### ISSUE THREAD

**Issue by susl16c** [AzuraCast/AzuraCast#974]
I didn’t understand how the move works. When you select a folder, nothing happens. When you enter the folder, there are no files and it’s not clear how and what moves?

**Comment by Vaalyn** [comment]
The `Move` is for moving the audio files to different folders and works by first selecting which files you want to move, then clicking on the button. Then a modal dialog opens where you can see how many files you have selected in the upper right corner of the modal. Here you will have to select a folder to which you want to have the files you previously selected moved. The modal only shows directories and no files since you can't move files into other files and showing all files and directories there would be rather confusing if your station has hundreds of files in a directory. After you selected a folder in the modal via the select button for a folder the modal will close, the files list will reload and the files you selected to be moved will have been moved to the folder you selected.
