### ISSUE TITLE
Serving Node.js express app on the same machine as AzurCast

### ISSUE THREAD

**Issue by weislanes** [AzuraCast/AzuraCast#975]
Hey, great project. 

**Issue:**
 I'm runing Azuracast on a Digitalocean instance and on the same machine I use ffmeg to serve the audio stream to Youtube live. Works a charm. 

However I'm trying to serve the Node.js app that manages the ffmeg stuff so I can monitor and restart etc. from a URL. I'm serving the Node app on port 3000 and I've added the following code to the Azuracast  Nginx server config:

```
location /ffmpeg {
            proxy_pass http://localhost:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
     }
```

But it results in a 502 or 504 error.  I searched through the issues and couldn't find a solution, wondering am I missing something, or indeed, is this even possible? 

Cheers.

**Comment by SlvrEagle23** [comment]
@weislanes I'm assuming you're using the "traditional" installation that installs directly to the VPS instead of Docker?

If so, there should be no reason you can't run whatever else you want on that same server. The odds are high that the 502/504 errors here are typical nginx "Bad Gateway" permission or access issues and that there's something wrong between nginx and your Node/Express service. It would be worthwhile to look into nginx's logs and see if there's any further information.

**Comment by weislanes** [comment]
Yeah it's the traditional install. OK, good to know. Thought there may have been an AzuraCast limitation.

I'll dig into the logs. Appreciate the help.
