### ISSUE TITLE
status-json.xsl leaking extended data.

### ISSUE THREAD

**Issue by Scraticus** [AzuraCast/AzuraCast#990]
The icecast status xsl after time leaks extended information and becomes download only instead of a http request.

**Installation method**

I am using docker

**Host OS (for Docker installations)**

Ubuntu 18.04

**Describe the bug**

The bug creates a file which contains extended information including ip of listeners, and other information which normally is not issued in a json format.

**To Reproduce**

1. Go to status-json.xsl and select a mountpoint to the station.
2. Click on accept download
3. The file contains this information.

**Expected behavior**

The behaviour expected is a clean view of status-json which doesn't download or give extended information.

**Relevant Logs**

The contents of the json contains information which it shouldnt

**Screenshots**

**Device(s):**
 - Device: VPS
 - OS: Ubuntu 18.04 via Docker
 - Browser: All
 - Version: 

**Additional context**

**Comment by CodeSteele** [comment]
https://github.com/AzuraCast/icecast-kh-ac/pull/11
https://github.com/AzuraCast/AzuraCast/pull/994

Once these are approved we should be good on this.

**Comment by SlvrEagle23** [comment]
@Scraticus @CodeSteele Our version of `status-json.xsl`, which was pulled directly from the upstream Xiph Icecast version, did not explicitly exclude the `listener` value, which allowed individual mount points to reveal listener data without authentication.

Since we don't use this endpoint to retrieve listener data for AzuraCast purposes (we use the authenticated administration point where it originates), we can just "plug the leak" in the `status-json.xsl` file without any issue.

The PR that accomplishes this on our Icecast-KH-AC branch has been approved, and traditional installs that update will have the issue fixed immediately. The Docker image is currently building and will be available shortly.
