### ISSUE TITLE
IceCast KH Reporting missing libCurl for YP pages

### ISSUE THREAD

**Issue by Scraticus** [AzuraCast/AzuraCast#992]
**Installation method**

Docker

**Host OS (for Docker installations)**

Ubuntu 18.04

**Describe the bug**

When 'submit to YPs' is enabled, a warning in the log file is reported.

**To Reproduce**
Enable YP / public stream and it complains in the icecast logfile.

**Expected behavior**

no log entries and YP working correctly.

**Relevant Logs**

[2018-11-25  12:13:31] EROR slave/slave_initialize streamlist request disabled, rebuild with libcurl if required
[2018-11-25  12:13:31] WARN slave/slave_startup process has 1048576 max file descriptor limit
[2018-11-25  12:13:31] WARN slave/slave_startup YP server handling has been disabled

**Comment by SlvrEagle23** [comment]
@Scraticus This was caused by an inconsistency between our traditional and docker build processes. Traditional properly included the libcurl dev library before building Icecast-KH-AC, but the Docker multistage build process didn't reflect that inclusion.

Along with the fix for #990, the updated Docker build for the radio container also fixes this issue by including both OpenSSL and cURL into the Icecast build process.

**Comment by SlvrEagle23** [comment]
(Note: This build is still in the process of being compiled on the Docker Hub and will be available within about 15 minutes.)
