### ISSUE TITLE
Metadata update after StereoTool's pipe

### ISSUE THREAD

**Issue by farsoo** [AzuraCast/AzuraCast#995]
Hi, i'm newbie of AzuraCast.
I'm using azuracast with StereoTool (for sound processing).
From what i read, to make "StereoTool" work, I have to use `drop_metadata`.

This is my "Advanced custom configuration":
`radio = mksafe(pipe(process='/var/azuracast/dsp/stereo_tool_cmd_64 - - -s /var/azuracast/dsp/preset_01.sts', drop_metadata(radio)))`

How can i re-insert metadata, after the StereoTool's pipe?
What is the best way?

Thanks in advance!

**Comment by SlvrEagle23** [comment]
@farsoo I've been able to get StereoTool working without dropping metadata. The command I was able to get working in at least one test installation was:

```
radio = mksafe(pipe(buffer=5., process='/path/to/stereo_tool_cmd_64 - - -s /path/to/preset.sts --quiet -k "<key>" 2> /dev/null', radio))
```

**Comment by ckeurk** [comment]
I would like to know how to set up stereo tools, if there is a little tutorial I don't think I'm the only one ;)

**Comment by stemvantwente** [comment]
> I would like to know how to set up stereo tools, if there is a little tutorial I don't think I'm the only one ;)

Would love this to

**Comment by SlvrEagle23** [comment]
@ckeurk @stemvantwente Since Stereo Tool is proprietary and third-party software that is not shipped with AzuraCast, we don't offer official support for it or package it along with our own software.

However, if someone in the community would like to contribute their knowledge to a collective knowledge base of instructions on how to get Stereo Tool working with AzuraCast, we would happily accept any pull request adding such documentation to our docs repo: https://github.com/AzuraCast/azuracast.com

**Comment by wavespeed** [comment]
After install Stereo Tool I noticed that the song history widget is not working correctly. It shows blank spaces while jingles are playing even with jingle mode activated. Those blank spaces should not show - only the songs names.  When I'm using Liquidssoap processing the widget works correctly.
I read the posts above but  I'm still confused on what line and where I have to paste it to fix the problem.
Could you explain it to me? Thanks!!
